"""Formulation, part B — micro-skills for four macro skills:
Distinguish primary from secondary needs · Consider the likelihood of co-occurring
conditions · Analyse risk and resilience · Account for the biopsychosocial context.

Keyed (macro skill name, micro-skill name), in the micro.py format from HANDOVER.md.
"""

MICRO = {

# ── 2. FORMULATION · Distinguish primary from secondary needs ──

("Distinguish primary from secondary needs","Generate more than one hypothesis"): {
"why":   "Almost every referral arrives with the secondary need on the form: the school refers for behaviour, and the behaviour is downstream of an unidentified reading difficulty. The hypothesis-testing stance in Monsen et al.'s problem analysis framework (Educational Psychology in Practice, 1998) and the Reference sheet both set two genuinely competing hypotheses as the minimum. PSI Code 4.2.6 and CORU SoP 3.5 are mapped here. One hypothesis, tested only for confirming evidence, produces an intervention for a symptom that will not work.",
"s1":    "WATCH FOR — the moment your supervisor first voices an explanation for a referral, and whether a second one follows before any data is gathered. Notice whether the alternatives genuinely compete (escape from literacy demand v. attention-seeking v. a class-wide demand problem) or are the same idea in two phrasings.\n\nWRITE DOWN — every hypothesis named, and for each, the one piece of data that would distinguish it from the others.\n\nASK AFTERWARDS — 'which of those did you think was most likely before you went in, and what would have changed your mind?'",
"s2":    "YOU TAKE — writing two or three competing hypotheses for a live referral before the planning meeting, each with the observation, interview question or test result that would support it and the one that would undermine it.\n\nTHEY HOLD — deciding which hypotheses are worth the data collection time on a busy caseload, and adding the one you did not think of.\n\nWHY THAT SPLIT — generating alternatives is thinking you can practise safely on paper. Knowing which ones a school's time can afford comes from years of seeing which turn out to matter.",
"s3":    "YOU RUN IT — for each new case, bring your hypotheses to supervision in writing before the first school visit, and plan the observation and interviews so each hypothesis gets a fair test.\n\nWHAT THEY ARE WATCHING FOR — a 'second' hypothesis that is a relabelling of the first ('dyslexia' and 'a specific reading difficulty'), and a data plan that could only ever confirm the favoured one.\n\nSTEPPING IN LOOKS LIKE — 'both of those predict the same thing in the classroom. What would you see if you were wrong?'",
"s4":    "YOU DO IT ALONE — at referral, write at least two hypotheses that predict different data, plan a comparison observation or history question that separates them, and record them on the case file before you collect anything.\n\nPASS TEST — An alternative was genuinely considered\n\nEVIDENCE TO FILE — the dated hypothesis note on the case file and the formulation section of the report. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a report for a child referred for behaviour that never asks whether the behaviour clusters around reading tasks, because 'behaviour' was the only hypothesis on the table.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to test whether two hypotheses genuinely compete (do they predict different observations?), and walk through the Reference sheet's three-way example for a behaviour referral, naming the data each predicts.\n\nWHEN IT GOES WRONG — you can say what to do when data arrives that fits none of your hypotheses: stop, write a new one that does fit, say in supervision that your first set was too narrow, and replan rather than squeezing the data into the nearest fit.",
"error": "Offering two hypotheses that are the same explanation in different words, so nothing was actually tested.",
"feeds": "→ Feeds into 'Test each hypothesis against the data' and 'Record the hypothesis you rejected and why'.",
"evidence":"Case file hypothesis note · Report — formulation · Log sheet tagged 2. Formulation"},

("Distinguish primary from secondary needs","Record the hypothesis you rejected and why"): {
"why":   "The Reference sheet identifies the rejected-hypothesis sentence as the single line that most distinguishes a grade 5 report from a grade 3: it shows you tested rather than assumed. PSI Code 4.2.6 is mapped here. A report that reads as if only one explanation was ever entertained cannot be checked, and a later psychologist, CAMHS clinician or parent has no way to see what was ruled out and on what evidence. They may then re-run the same enquiry, or wrongly assume it was never considered.",
"s1":    "WATCH FOR — whether your supervisor's reports name the explanation they did not accept, where it sits (formulation or discussion), and how neutrally it is worded when the rejected hypothesis was the school's or parent's own view.\n\nWRITE DOWN — the exact sentence they use, and the piece of data it cites as the reason for rejecting.\n\nASK AFTERWARDS — 'how do you write a rejected hypothesis when it was the referrer's explanation, without the school feeling told they were wrong?'",
"s2":    "YOU TAKE — drafting the rejected-hypothesis sentence for a joint case, in the Reference sheet's form: 'An attention-maintained explanation was considered and is less consistent with the pattern, because the behaviour did not occur during whole-class oral work.'\n\nTHEY HOLD — the wording decision where the rejected hypothesis belongs to someone who will read the report.\n\nWHY THAT SPLIT — the logic of the sentence is yours to build. Its relational effect on a teacher or parent needs judgement you are still developing.",
"s3":    "YOU RUN IT — include a rejected-hypothesis sentence in every formulation you draft, naming the hypothesis, the data that undermined it, and how strongly.\n\nWHAT THEY ARE WATCHING FOR — a straw man: an alternative that was never plausible, written in to tick the box, or a rejection with no evidence attached.\n\nSTEPPING IN LOOKS LIKE — 'nobody thought it was hearing. Which explanation did the class teacher actually hold, and why did you set it aside?'",
"s4":    "YOU DO IT ALONE — write the rejected hypothesis into every substantial formulation, with the specific observation, history or score that made it less likely, worded so the person who held it can read it without feeling dismissed.\n\nPASS TEST — The rejected one appears somewhere\n\nEVIDENCE TO FILE — the formulation section of the report, flagged in your Appendix 5 reflection for that week. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — the case file shows you considered attention-seeking and discarded it, but the report is silent, so the school keeps running a reward chart for attention.",
"s5":    "YOU CAN TEACH IT — you can explain why a rejected hypothesis strengthens a report rather than weakening it (it shows the conclusion survived a test), and show how to word it for a school or family reader.\n\nWHEN IT GOES WRONG — you can say what to do when a parent reads the rejection as blame ('you're saying it isn't ADHD?'): explain it was considered on the evidence available, say what evidence would reopen it, and offer the route to reopen it.",
"error": "Silently discarding the alternative, so the report reads as if only one explanation was ever entertained.",
"feeds": "→ Feeds into 'State explicitly which need is primary' and into Assessment — honest reporting in the integration section.",
"evidence":"Report — formulation · Appendix 5 · Log sheet tagged 2. Formulation"},

("Distinguish primary from secondary needs","Test each hypothesis against the data"): {
"why":   "A hypothesis is only as good as the test it faced. The Reference sheet names two tests for primary v. secondary: timing (what came first, from more than one source) and situational spread (a primary difficulty shows up wherever its demand is present; a secondary one is tied to the context that provokes it). CORU SoP 3.6 is mapped here. Testing only for confirming evidence is the classic error. Treating co-occurrence as causation is the other: anxiety and a reading difficulty together do not tell you the direction.",
"s1":    "WATCH FOR — how your supervisor uses the developmental history and the comparison observation. Notice whether they ask when the behaviour began, and whether they observe the child in a lesson without the suspected demand (oral maths, PE, art) as well as with it.\n\nWRITE DOWN — for each hypothesis: the evidence for it, the evidence against it, and the source of each.\n\nASK AFTERWARDS — 'which single piece of data moved you most, and how sure were you of its source?'",
"s2":    "YOU TAKE — building a for-and-against table per hypothesis from the file, interviews and observation, including onset dates from more than one informant and a note of which settings the difficulty appears in.\n\nTHEY HOLD — weighing evidence of unequal quality: a vague parent recollection against a dated school record, one observation against a term of teacher report.\n\nWHY THAT SPLIT — assembling the evidence is disciplined work you can do well now. Weighting it needs calibration you get from seeing many cases.",
"s3":    "YOU RUN IT — present each hypothesis with its supporting and undermining evidence in supervision, and state which it survives and which it does not.\n\nWHAT THEY ARE WATCHING FOR — evidence counted only on one side, onset taken from a single informant, and a comparison observation skipped because the first one 'showed enough'.\n\nSTEPPING IN LOOKS LIKE — 'you've told me what supports escape from reading. What did you see that doesn't fit it?'",
"s4":    "YOU DO IT ALONE — for every hypothesis, state the timing evidence, the situational spread and the test results that bear on it, on both sides, before concluding.\n\nPASS TEST — You can say what supports and undermines each\n\nEVIDENCE TO FILE — the for-and-against working table on the case file and the formulation section of the report. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a formulation that lists five supporting points for the chosen hypothesis and none against, when the observation notes show the behaviour also happened in the yard.",
"s5":    "YOU CAN TEACH IT — you can explain timing and situational spread as tests, show how the comparison observation separates task-driven from context-free behaviour, and name confirmation bias as the default failure.\n\nWHEN IT GOES WRONG — you can say what to do when the evidence for two hypotheses is evenly balanced: say so, name the missing data that would separate them, and move to 'Recognise where the sequence is genuinely unclear' rather than choosing one.",
"error": "Listing only the evidence that supports the favoured hypothesis.",
"feeds": "→ Feeds into 'State explicitly which need is primary' and 'Recognise where the sequence is genuinely unclear'.",
"evidence":"Case file working table · Report — formulation · Log sheet tagged 2. Formulation"},

("Distinguish primary from secondary needs","State explicitly which need is primary"): {
"why":   "The Reference sheet calls distinguishing primary from secondary 'the single highest-value move' in formulation: formulate the presenting problem and you recommend for a symptom, and the school concludes psychology does not help. Listing 'literacy difficulty' and 'behavioural difficulty' side by side leaves the reader to guess which to work on first. CORU SoP 3.5 is mapped here. Carr's (2015) predisposing, precipitating and perpetuating factors give one structure for saying which drives which.",
"s1":    "WATCH FOR — the sentence in your supervisor's report where the primary need is named, and whether the recommendations follow its order: primary need addressed first, secondary need addressed as expected to ease, or supported in parallel.\n\nWRITE DOWN — the sentence, and how the recommendations map onto primary and secondary.\n\nASK AFTERWARDS — 'if the school only does one thing from this report, which one, and does the report make that obvious?'",
"s2":    "YOU TAKE — drafting the primary/secondary statement for a joint case, with the evidence that supports the direction, and ordering the recommendations to match.\n\nTHEY HOLD — the final call where evidence is strong on direction but the secondary need carries the immediate risk (for example, behaviour that is leading towards a reduced timetable).\n\nWHY THAT SPLIT — naming the primary need follows from your testing. Deciding what must be managed now, even if it is secondary, needs knowledge of the school and the risk.",
"s3":    "YOU RUN IT — write the primary need in one explicit sentence in every formulation, and explain in supervision why the recommendations are sequenced as they are.\n\nWHAT THEY ARE WATCHING FOR — hedged lists ('difficulties were noted in literacy and behaviour') that avoid committing, and recommendations that target the secondary need only.\n\nSTEPPING IN LOOKS LIKE — 'read me the sentence that tells the teacher which need is driving the other.'",
"s4":    "YOU DO IT ALONE — state which need is primary and why, in one sentence a teacher can act on, and order the recommendations so the primary need is targeted at the right point on the NEPS Continuum of Support.\n\nPASS TEST — The report says which, not just lists both\n\nEVIDENCE TO FILE — the formulation and recommendations sections of the report. Log against 2. Formulation and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a behaviour plan is put in place, the reading difficulty is never targeted, and the same child is referred back a year later.",
"s5":    "YOU CAN TEACH IT — you can explain how a primary/secondary statement follows from timing and situational spread, and why the recommendations must follow its order, using the literacy-to-behaviour pathway (Snowling & Hulme, 2012) as a worked example.\n\nWHEN IT GOES WRONG — you can say what to do when the review shows the primary need improved and the secondary did not: revisit the formulation, consider that the secondary need has become self-maintaining, and target it directly.",
"error": "Listing the needs side by side and leaving the reader to decide which one drives the other.",
"feeds": "→ Feeds into Intervention — 'State the Continuum level for each recommendation' and 'Limit the number so they can be acted on'.",
"evidence":"Report — formulation and recommendations · Log sheet tagged 2. Formulation and 3. Intervention"},

("Distinguish primary from secondary needs","Recognise where the sequence is genuinely unclear"): {
"why":   "Sometimes the order cannot be established: records are missing, the child moved schools, or informants disagree and neither is more reliable. The Reference sheet lists forcing a primary/secondary distinction for the sake of a neater report as a named error. PSI Code 2.3.1 and 4.2.5 (distinguishing facts, opinions and hypotheses) are mapped here. A confident guess recommends the wrong thing first and cannot be revised. An honest 'cannot be established, and here is how we will find out' can be.",
"s1":    "WATCH FOR — how your supervisor words uncertainty in a report without making it sound as though nothing was found, and whether the report goes on to name what would resolve it.\n\nWRITE DOWN — the wording, and the resolving step proposed (a review after a term of targeted support, a request for previous school records, a hearing check).\n\nASK AFTERWARDS — 'how do you decide the evidence is genuinely unclear, rather than that you have not looked hard enough yet?'",
"s2":    "YOU TAKE — noting, for a joint case, where onset or direction cannot be established, what is missing, and what would supply it.\n\nTHEY HOLD — the judgement that enough enquiry has been done to call it unclear, and how the uncertainty is explained to the family.\n\nWHY THAT SPLIT — spotting a gap is part of your testing. Deciding the gap cannot reasonably be filled, and saying so to a parent who wants an answer, needs experience.",
"s3":    "YOU RUN IT — where the sequence is unclear, draft the uncertainty statement and the resolving step yourself, and bring both to supervision.\n\nWHAT THEY ARE WATCHING FOR — two opposite errors: forcing a direction the evidence does not carry, and using 'unclear' to avoid a judgement the evidence does support.\n\nSTEPPING IN LOOKS LIKE — 'have you asked the previous school for their records? Then it's not unclear yet — it's unchecked.'",
"s4":    "YOU DO IT ALONE — write, in the Reference sheet's form, 'The direction of the relationship between X and Y cannot be established from the available information. A review after one term of targeted support would clarify it', and set the review date.\n\nPASS TEST — You said so rather than picking one\n\nEVIDENCE TO FILE — the formulation section and the review date on the case file. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a report that confidently calls anxiety primary on one parent's recollection, when the school records that would have settled it were never requested.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between 'unclear' and 'unchecked', why an honest uncertainty statement is stronger than a guess, and how to turn uncertainty into a planned review that tests the direction.\n\nWHEN IT GOES WRONG — you can say what to do when a school pushes for a definite answer to secure resources: explain what the evidence does and does not show, and describe the need in functional terms that do not depend on the direction.",
"error": "Picking a direction to make the report neater when the evidence does not establish one.",
"feeds": "→ Feeds into Intervention — 'Set a review date' and 'State how progress will be measured', and into Ethical Practice — honest reporting of uncertainty.",
"evidence":"Report — formulation · case file review date · Log sheet tagged 2. Formulation"},

# ── 2. FORMULATION · Consider the likelihood of co-occurring conditions ──

("Consider the likelihood of co-occurring conditions","Know the common co-occurrences in this age band"): {
"why":   "Co-occurrence is the norm, not the exception (Kaplan et al., Journal of Learning Disabilities, 2001; Pennington, Cognition, 2006, on multiple-deficit models). The Reference sheet lists the pairings to expect: ADHD with specific learning difficulty, DLD with literacy difficulty, DCD with ADHD and DLD, autism with ADHD, anxiety and intellectual disability. Which pairings surface also shifts by UCD Table 3 age band. Rates vary widely between studies: check a current source before citing any figure.",
"s1":    "WATCH FOR — which second presentations your supervisor asks about automatically for a given referral and age: a junior infant referred for language, a fourth-class child referred for reading, a Transition Year student referred for anxiety.\n\nWRITE DOWN — for each case, the referral, the age band, and the co-occurrences your supervisor screened for.\n\nASK AFTERWARDS — 'which co-occurrence do you see missed most often in schools here, and at what age does it usually surface?'",
"s2":    "YOU TAKE — building your own one-page table of the common pairings by UCD Table 3 age band, each with a source you have read, and bringing it to supervision.\n\nTHEY HOLD — local knowledge of what is actually seen and missed in the Cavan schools and how the CDNT and CAMHS thresholds shape what reaches the EP.\n\nWHY THAT SPLIT — the literature is yours to read and summarise. How it plays out in this caseload is your supervisor's experience.",
"s3":    "YOU RUN IT — at referral, name the two or three likeliest co-occurrences for this child's profile and age, and plan a screening question or measure for each.\n\nWHAT THEY ARE WATCHING FOR — rates quoted from memory, and pairings recited without a plan to screen for them.\n\nSTEPPING IN LOOKS LIKE — 'you've said DLD often travels with literacy difficulty. Where is the source, and what will you check in this child?'",
"s4":    "YOU DO IT ALONE — for every referral, write down the likely co-occurrences for the age band, screen for them, and cite any rate only from a source you have checked.\n\nPASS TEST — SLD with ADHD, anxiety masking autism, and so on\n\nEVIDENCE TO FILE — the pairings table as a working paper, and the screening noted on the case file. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — an examiner asks where your co-occurrence figure comes from and you cannot say.",
"s5":    "YOU CAN TEACH IT — you can explain why developmental conditions co-occur (shared risk factors and overlapping deficits, per Pennington, 2006) rather than just listing pairings, and why the term 'comorbidity' is questioned (Kaplan et al., 2001).\n\nWHEN IT GOES WRONG — you can say what to do when you find you quoted a rate you cannot source: remove or correct it, and replace it with a sourced statement or with 'commonly co-occur' without a figure.",
"error": "Quoting a co-occurrence rate from memory without a source you have checked.",
"feeds": "→ Feeds into 'Consider a second presentation as routine' and into the Conditions sheet — co-occurring column.",
"evidence":"Pairings table · case file · Log sheet tagged 2. Formulation"},

("Consider the likelihood of co-occurring conditions","Consider twice-exceptionality"): {
"why":   "High ability plus a specific difficulty can produce average attainment and a child who looks unremarkable while working much harder than peers. The Reference sheet notes it is missed constantly because school screening is attainment-based. CORU SoP 5.17 is mapped here, and the NCSE has published on twice-exceptional learners (read the current document before citing it). The signal is scatter within the cognitive profile, not the composite. Miss it and the child gets neither challenge nor support.",
"s1":    "WATCH FOR — how your supervisor reads a cognitive profile: whether they look at index-level scatter (strong verbal reasoning, weak processing speed or working memory) before the composite, and whether they compare attainment with the strongest index as well as the average.\n\nWRITE DOWN — the pattern that prompted them to consider twice-exceptionality, and what else they checked (teacher report of oral contributions, work samples, effort and fatigue).\n\nASK AFTERWARDS — 'when do you trust a big index discrepancy, and when is it just measurement noise?'",
"s2":    "YOU TAKE — scoring and describing the index profile, marking discrepancies, and noting attainment against both the highest and the average index.\n\nTHEY HOLD — interpreting whether a discrepancy is meaningful (using the test manual's own guidance) and how to present high ability to a school that sees an average pupil.\n\nWHY THAT SPLIT — the description is mechanical and you should do it every time. Interpretation of discrepancy depends on the manual and on experience of how often such splits occur.",
"s3":    "YOU RUN IT — for every cognitive assessment, look at index scatter before the composite and state in supervision whether twice-exceptionality is plausible and why.\n\nWHAT THEY ARE WATCHING FOR — reporting only the full-scale score, and treating average attainment as 'no need'.\n\nSTEPPING IN LOOKS LIKE — 'the verbal index is well above the processing speed index. What is her attainment being compared with?'",
"s4":    "YOU DO IT ALONE — consider twice-exceptionality whenever there is marked index scatter, using the manual's criteria for meaningful discrepancy, and say in the report what the pattern suggests.\n\nPASS TEST — High ability masking difficulty was considered\n\nEVIDENCE TO FILE — the cognitive profile section and the formulation. Log against 2. Formulation and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a child with superior verbal reasoning and a decoding difficulty is written up as 'average, no concerns' because her reading age matches her class.",
"s5":    "YOU CAN TEACH IT — you can explain how high ability masks a specific difficulty, why composite scores hide it, and what the NCSE material says about identification — quoting only what you have read.\n\nWHEN IT GOES WRONG — you can say what to do when a school resists ('she's doing fine'): show them the gap between her reasoning and her output, and frame the recommendation around unlocking the stronger ability.",
"error": "Reporting only the full-scale score, so a large index discrepancy is never seen.",
"feeds": "→ Feeds into 'Weigh the evidence for each separately' and into Intervention — 'Build at least one on a strength'.",
"evidence":"Report — cognitive profile and formulation · Log sheet tagged 2. Formulation and 1. Assessment"},

("Consider the likelihood of co-occurring conditions","Consider a second presentation as routine"): {
"why":   "Diagnostic overshadowing is the most common way children get missed: once a child has an autism diagnosis, a reading difficulty gets attributed to autism and never assessed. The term was introduced for intellectual disability and mental illness (Reiss, Levitan & Szyszko, 1982). The Reference sheet's discipline is procedural, not attitudinal: write down what the existing diagnosis does not explain before you start. CORU SoP 5.15 is mapped here.",
"s1":    "WATCH FOR — what your supervisor does with an existing diagnosis on the referral form. Notice whether they accept it as the frame for everything, or ask 'what here would still need explaining if the diagnosis were not there?'\n\nWRITE DOWN — the existing diagnosis, the presenting difficulties, and which of them the diagnosis does not account for.\n\nASK AFTERWARDS — 'when a child comes with a CDNT diagnosis, how do you stop it doing all the explaining?'",
"s2":    "YOU TAKE — writing, before the first visit, the list of difficulties the existing diagnosis does not explain, and a screening step for each.\n\nTHEY HOLD — sensitivity with the family, who may have fought hard for the diagnosis and hear 'something else' as a threat to it.\n\nWHY THAT SPLIT — the list is a procedure you can own. Raising a second possibility with a family who waited years on a CDNT list needs a practised touch.",
"s3":    "YOU RUN IT — for every case, including those without a diagnosis, record at intake what else could be present and how you will check it.\n\nWHAT THEY ARE WATCHING FOR — considering a second presentation only when it is glaring, and every difficulty being attributed to the known condition.\n\nSTEPPING IN LOOKS LIKE — 'autism doesn't explain why he can't decode. Did you assess it, or assume it?'",
"s4":    "YOU DO IT ALONE — at intake on every case, write down what the existing diagnosis or leading hypothesis does not explain, and screen for at least one second presentation.\n\nPASS TEST — Considered, not only when obvious\n\nEVIDENCE TO FILE — the intake note on the case file and the formulation. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a child with a general learning disability whose anxiety is treated as part of the picture, so nobody offers the anxiety support that would have helped.",
"s5":    "YOU CAN TEACH IT — you can explain diagnostic overshadowing, why the fix is procedural (a list written before you start), and give a worked example from each UCD Table 3 age band.\n\nWHEN IT GOES WRONG — you can say what to do when you realise late that you attributed a difficulty to the known diagnosis without checking: assess it now, amend the report, and tell the school and family plainly.",
"error": "Attributing every difficulty to the existing diagnosis without checking what it does not explain.",
"feeds": "→ Feeds into 'Weigh the evidence for each separately' and 'State what would establish the second'.",
"evidence":"Case file intake note · Report — formulation · Log sheet tagged 2. Formulation"},

("Consider the likelihood of co-occurring conditions","Weigh the evidence for each separately"): {
"why":   "Evidence for one condition must not carry the other. The Reference sheet's method: build the case for each presentation independently — what would establish it, what is present, what is absent. CORU SoP 3.4 is mapped here. When one diagnosis is allowed to explain everything, the second presentation is never supported; when evidence for one is borrowed to prop up the other (inattention counted for both ADHD and anxiety), you over-identify. Either error changes the recommendations.",
"s1":    "WATCH FOR — how your supervisor separates overlapping evidence. Inattention can reflect ADHD, anxiety, a language difficulty or tiredness. Notice how they decide which the evidence speaks to, and whether any item is counted twice.\n\nWRITE DOWN — for two presentations in one case: the evidence for each, the evidence against each, and the items that could belong to either.\n\nASK AFTERWARDS — 'when a symptom fits both, how do you decide where it belongs, or do you leave it unassigned?'",
"s2":    "YOU TAKE — building a separate evidence column for each possible presentation, flagging shared items rather than assigning them.\n\nTHEY HOLD — the judgement on shared evidence and on how far the pattern supports each presentation.\n\nWHY THAT SPLIT — separating the columns forces the discipline. Deciding what an ambiguous item means needs experience of how the presentations differ in a school setting.",
"s3":    "YOU RUN IT — present each presentation's case separately in supervision, with shared items named as shared, and state how strongly each is supported.\n\nWHAT THEY ARE WATCHING FOR — a single narrative in which one condition absorbs every finding, and double-counting of the same observation.\n\nSTEPPING IN LOOKS LIKE — 'you've used the same restlessness as evidence for ADHD and for anxiety. Which one does it support better, and why?'",
"s4":    "YOU DO IT ALONE — write the formulation with a separate evidence statement for each presentation considered, naming shared items as shared, so a reader can see that one diagnosis was not allowed to explain everything.\n\nPASS TEST — One diagnosis did not explain everything\n\nEVIDENCE TO FILE — the working evidence columns on the case file and the formulation. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a formulation where 'autism' accounts for social difficulty, reading failure, sleep problems and school refusal, and none of the last three is assessed.",
"s5":    "YOU CAN TEACH IT — you can explain why co-occurring presentations need separate evidential cases, how to handle symptoms that overlap, and how the multiple-deficit view (Pennington, 2006) makes shared evidence expected rather than surprising.\n\nWHEN IT GOES WRONG — you can say what to do when a second presentation looks likely but the evidence is thin: describe what you found, do not conclude, and move to 'State what would establish the second'.",
"error": "Letting evidence for one condition carry the other, so a single diagnosis explains everything.",
"feeds": "→ Feeds into 'State what would establish the second' and into 'Test each hypothesis against the data'.",
"evidence":"Case file evidence columns · Report — formulation · Log sheet tagged 2. Formulation"},

("Consider the likelihood of co-occurring conditions","State what would establish the second"): {
"why":   "Naming a possible second presentation without naming the next step leaves the family with a worry and no route. The Reference sheet's grade 5 marker is stating what would be needed to establish it, and naming the boundary between description and diagnosis. CORU SoP 1.2 is mapped here, and the Reference sheet cites PSI 2.2.2 and 2.2.3 on competence boundaries. As a trainee you do not diagnose ADHD, autism or any medical condition: you describe the profile, say what it is consistent with, and refer.",
"s1":    "WATCH FOR — how your supervisor words a possible second presentation: 'consistent with' rather than 'has', and which service is named (HSE CDNT, CAMHS, the GP, audiology) with what the referral should ask.\n\nWRITE DOWN — the wording, the service, who makes the referral (school, parent, GP, NEPS) and what the family is told to expect.\n\nASK AFTERWARDS — 'how do you tell a parent that something else might be going on without it sounding like a diagnosis?'",
"s2":    "YOU TAKE — drafting the next-step sentence for a joint case: what was observed, what it is consistent with, what would establish it, and which service would do that.\n\nTHEY HOLD — the referral decision and the conversation with the family.\n\nWHY THAT SPLIT — the wording is where you practise the description/diagnosis boundary. The referral itself carries consequences for a waiting list and a family that your supervisor is accountable for.",
"s3":    "YOU RUN IT — in every formulation where a second presentation is possible, write the next step yourself and explain it to your supervisor, including who refers and what the referral should contain.\n\nWHAT THEY ARE WATCHING FOR — diagnostic language ('John has ADHD'), and a vague 'further assessment recommended' with no service and no question.\n\nSTEPPING IN LOOKS LIKE — 'further assessment by whom, for what, and who is sending the referral?'",
"s4":    "YOU DO IT ALONE — write, in the Reference sheet's form, 'this profile is consistent with an attentional difficulty, and referral to [named service] is recommended for diagnostic assessment', naming who refers and what question the referral asks.\n\nPASS TEST — You named the next step\n\nEVIDENCE TO FILE — the formulation and recommendations sections. Log against 2. Formulation and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — the report says 'features of autism noted', the parent does not know what to do next, and nobody makes a referral.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between describing a profile and diagnosing, why it matters for a trainee under PSI 2.2.2 and 2.2.3 (read the clauses themselves), and the local referral routes for each common second presentation.\n\nWHEN IT GOES WRONG — you can say what to do when a school or parent treats 'consistent with' as a diagnosis: correct it in writing, explain the difference, and point them to the service that can assess.",
"error": "Writing a diagnosis ('has ADHD') or a vague 'further assessment' instead of a described profile with a named next step.",
"feeds": "→ Feeds into Ethical Practice — 'Refer on and maintain responsibility until contact is made', and into Working with Others.",
"evidence":"Report — formulation and recommendations · Log sheet tagged 2. Formulation and 6. Ethical Practice"},

# ── 2. FORMULATION · Analyse risk and resilience ──

("Analyse risk and resilience","Identify risk factors across all three levels"): {
"why":   "The Reference sheet sets three levels: child (developmental difficulty, chronic illness, early adversity), family (ill health, bereavement, separation, housing instability, caring responsibilities) and school or community (unstable placement, teacher changes, discrimination, low expectations, distance from services). Gather at only one level and you produce a within-child formulation by omission. CORU SoP 5.17 is mapped here. Carr (2015) frames risk as predisposing, precipitating and perpetuating factors, which is what makes risk usable.",
"s1":    "WATCH FOR — which questions your supervisor asks in the parent and teacher interviews that bring out family and school risk (moves, bereavements, housing, how many teachers this year), and how gently they ask them.\n\nWRITE DOWN — the risk factors identified at each of the three levels, and which level had the least information.\n\nASK AFTERWARDS — 'how do you ask a parent about housing or money without it feeling like an inspection?'",
"s2":    "YOU TAKE — sorting everything on file and from interview into child, family and school or community risk, and noting which level is thin.\n\nTHEY HOLD — the sensitive family questions in interview until you have seen them asked well, and the judgement on what goes in the written report.\n\nWHY THAT SPLIT — sorting is analysis you can own. Asking about family adversity, and deciding what a family would be comfortable seeing written, carries relational risk.",
"s3":    "YOU RUN IT — gather across all three levels in your own interviews, and present the risk picture in supervision, naming which risks are predisposing, precipitating and perpetuating.\n\nWHAT THEY ARE WATCHING FOR — risk tucked into a 'background' paragraph and never used, and a picture that is all child-level.\n\nSTEPPING IN LOOKS LIKE — 'you've written that he's had three teachers this year as background. Is that a risk factor? Then name it as one.'",
"s4":    "YOU DO IT ALONE — gather risk at child, family and school levels on every substantial case, name each as a risk in the formulation, and say what role it plays in the difficulty.\n\nPASS TEST — Risk is named as risk, not as background\n\nEVIDENCE TO FILE — the formulation section. Log against 2. Formulation. Keep identifiable family detail out of your personal Log.\n\nWHAT FAILURE LOOKS LIKE — a report that mentions a parent's recent illness in the history and never connects it to the child's change in presentation that term.",
"s5":    "YOU CAN TEACH IT — you can explain the three levels, why omitting one produces a within-child formulation, and how Carr's (2015) four Ps turn a list of risks into an account of onset and maintenance.\n\nWHEN IT GOES WRONG — you can say what to do when a family does not want a risk factor in the report: discuss what is necessary for the formulation, agree wording, and record the decision, while never omitting anything that engages child protection.",
"error": "Recording risk as background history and never naming it as a risk that shapes the formulation.",
"feeds": "→ Feeds into 'Recognise when risk crosses a safeguarding threshold' and 'Show the levels interacting rather than listed'.",
"evidence":"Report — formulation · Log sheet tagged 2. Formulation"},

("Analyse risk and resilience","Identify protective factors genuinely present"): {
"why":   "The Reference sheet's test is evidence, not optimism: 'supportive family' is not a protective factor unless you can say what the family does. Masten (Child Development, 2014) describes resilience as largely 'ordinary' processes — relationships, competence, belonging — and Rutter (Development and Psychopathology, 2012) as dynamic, not a fixed trait. CORU SoP 1.3 is mapped here. Generic strengths cannot be built on, so the recommendations end up resting only on deficits.",
"s1":    "WATCH FOR — how your supervisor gathers strengths: asking the child who helps and where they like to be, observing which adult the child goes to, asking the teacher what the child is good at and when they last saw it.\n\nWRITE DOWN — each protective factor and its evidence (observed, named by the child, reported with an example).\n\nASK AFTERWARDS — 'how do you get a strength from a teacher who only has concerns to report?'",
"s2":    "YOU TAKE — asking the child directly who helps, what they are good at and where they choose to go, and recording the answers in their words.\n\nTHEY HOLD — checking that each strength you list is evidenced, not aspirational.\n\nWHY THAT SPLIT — eliciting strengths from a child is direct work you can do well now. Telling a real protective factor from a hopeful one needs a second, sceptical view.",
"s3":    "YOU RUN IT — list protective factors with evidence for each, and bring them to supervision alongside the risks.\n\nWHAT THEY ARE WATCHING FOR — generic strengths ('kind', 'supportive home', 'good attender') with no example, and strengths drawn only from adults.\n\nSTEPPING IN LOOKS LIKE — 'what does the family actually do that's supportive? If you can't say, it's not a protective factor yet.'",
"s4":    "YOU DO IT ALONE — name at least one reliable adult, one area of competence or one chosen place, with the evidence for each, specifically enough to build a recommendation on.\n\nPASS TEST — Strengths are specific, not generic\n\nEVIDENCE TO FILE — the formulation section, with the child's words where used. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — 'X is a kind and friendly boy with a supportive family' as the whole strengths section, and no recommendation that uses any of it.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between an evidenced and an aspirational protective factor, Masten's (2014) 'ordinary' processes, and how to elicit strengths from a child at each UCD Table 3 age band.\n\nWHEN IT GOES WRONG — you can say what to do when you genuinely cannot find a protective factor: say so in the formulation, because the absence is itself a finding, and make building one an explicit target.",
"error": "Listing aspirational strengths ('supportive family') with no evidence of what they actually do.",
"feeds": "→ Feeds into 'Build recommendations on a protective factor' and into Intervention — 'Build at least one on a strength'.",
"evidence":"Report — formulation · Log sheet tagged 2. Formulation"},

("Analyse risk and resilience","Recognise when risk crosses a safeguarding threshold"): {
"why":   "This is where risk stops being a formulation matter. Under the Children First Act 2015 and Children First National Guidance (2017), a mandated person must report harm at threshold to Tusla as soon as practicable, and telling the school DLP does not discharge that duty. CORU SoP 1.12 (limits of confidentiality) and PSI Code 3.3.4 are mapped here. Your 4 August review (as the Reference sheet records it) named risk management protocols as a development area. Continuing an assessment after a disclosure, or describing a concern in a report, is the failure.",
"s1":    "WATCH FOR — how your supervisor recognises the shift from 'risk factor' to 'concern', what they do in the first hour, and how they separate the report to Tusla from the DLP conversation and from supervision.\n\nWRITE DOWN — the sequence without identifying detail: stop, record verbatim with time, do not question further, tell the DLP, report to Tusla (jointly or yourself), tell your supervisor, record who and when.\n\nASK AFTERWARDS — 'what made you sure it was over the threshold, and which Guidance wording did you use?'",
"s2":    "YOU TAKE — rehearsing the sequence on anonymised examples, knowing the DLP for every school on your caseload, and your own record-keeping on the day.\n\nTHEY HOLD — support and advice. They do not hold your duty: if you are a mandated person, the report to Tusla is yours, and supervision follows the action rather than approving it.\n\nWHY THAT SPLIT — this is the exception to the usual split. The law makes the duty personal, so what you can hand over is only the support around it.",
"s3":    "YOU RUN IT — when a concern arises in your work, stop the assessment, act through the sequence the same day, and bring it to supervision afterwards.\n\nWHAT THEY ARE WATCHING FOR — continuing because stopping felt rude, questioning the child further, waiting for supervision before acting, and assuming the DLP's report covers you.\n\nSTEPPING IN LOOKS LIKE — 'you've told the principal. Has the report gone to Tusla, and is your name on it?'",
"s4":    "YOU DO IT ALONE — stop the work, record verbatim with the time, inform the DLP and ensure a report is made to Tusla as soon as practicable (jointly or yourself), tell your supervisor the same day, and record each step.\n\nPASS TEST — You escalated rather than described\n\nEVIDENCE TO FILE — your own contemporaneous record, kept per service policy, and a supervision note. Log against 2. Formulation and 6. Ethical Practice, with no identifiable details.\n\nWHAT FAILURE LOOKS LIKE — a concern written into the formulation as 'family stressors' and nobody told that day.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between a risk factor and a reasonable concern, the mandated threshold, why telling the DLP does not discharge your duty, and why supervision follows rather than replaces action — citing the Guidance, not paraphrasing it.\n\nWHEN IT GOES WRONG — you can say what to do when you realise a concern went unreported: report to Tusla now, tell your supervisor, and record what happened and when.",
"error": "Describing a safeguarding concern in the formulation instead of stopping and reporting it that day.",
"feeds": "→ Feeds into Ethical Practice — 'Act the same day without waiting for supervision', 'Report to the DLP and record the time' and 'Bring it to supervision afterwards, not instead'.",
"evidence":"Own contemporaneous record · supervision note · Log sheet tagged 2. Formulation and 6. Ethical Practice (no identifiable details)"},

("Analyse risk and resilience","Build recommendations on a protective factor"): {
"why":   "The Reference sheet puts it plainly: protective factors are not a courtesy paragraph, they are the material the intervention is made from, because an intervention that runs through an existing strength is the one a school will sustain. If a child reads willingly with one teacher, that teacher delivers or her approach is modelled. CORU SoP 5.34 is mapped here. A strengths list with no link to the recommendations is the named error: the formulation stops doing work at the point it matters.",
"s1":    "WATCH FOR — how your supervisor's recommendations use what the child does well: a trusted SNA as the key adult, a strength in oral reasoning turned into a reader for tests, a love of the GAA pitch used as the reward context.\n\nWRITE DOWN — each protective factor in the formulation, and which recommendation (if any) draws on it.\n\nASK AFTERWARDS — 'which recommendations do schools actually keep going after the review, and why those?'",
"s2":    "YOU TAKE — drafting at least one recommendation that runs through an evidenced protective factor, naming the factor in the recommendation itself.\n\nTHEY HOLD — checking the school can resource it at the right Continuum of Support level, and that the adult named is willing and available.\n\nWHY THAT SPLIT — linking strength to recommendation is formulation logic you should own. Whether the named adult can take it on is local knowledge.",
"s3":    "YOU RUN IT — build one recommendation on a protective factor in every report, and explain the link in supervision.\n\nWHAT THEY ARE WATCHING FOR — a strengths paragraph that is never referred to again, and recommendations that rely on a named adult who has not been asked.\n\nSTEPPING IN LOOKS LIKE — 'you said she trusts the SNA. Where is the SNA in your recommendations?'",
"s4":    "YOU DO IT ALONE — write at least one recommendation that explicitly draws on an evidenced protective factor, name the factor, and check with the school that it is feasible.\n\nPASS TEST — At least one uses a strength\n\nEVIDENCE TO FILE — the recommendations section. Log against 2. Formulation and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a formulation that names a reliable adult and a strength in art, and recommendations that are all extra literacy withdrawal with an unfamiliar teacher.",
"s5":    "YOU CAN TEACH IT — you can explain why interventions built on existing strengths are more likely to be sustained, how to translate each type of protective factor into a recommendation, and how this links to 'Build at least one on a strength' in Intervention.\n\nWHEN IT GOES WRONG — you can say what to do when the protective factor disappears (the trusted SNA is reallocated): revisit the formulation, find or build another, and set an early review.",
"error": "Listing strengths in the formulation and never using one in the recommendations.",
"feeds": "→ Feeds into Intervention — 'Build at least one on a strength' and 'Name who delivers'.",
"evidence":"Report — recommendations · Log sheet tagged 2. Formulation and 3. Intervention"},

# ── 2. FORMULATION · Account for the biopsychosocial context ──

("Account for the biopsychosocial context","Name which model of disability you are working from"): {
"why":   "The model you work from decides what you recommend, whether or not you name it. A medical model locates the difficulty in the child; a social model in barriers (Oliver, Disability & Society, 2013); a biopsychosocial model holds both (Engel, Science, 1977). The UN Convention on the Rights of Persons with Disabilities (ratified by Ireland in 2018) and CORU SoP 5.5 are mapped here. The Reference sheet warns most trainee reports are medical-model by default, because the tools are child-focused and the report follows the tools.",
"s1":    "WATCH FOR — which model your supervisor's reports imply: where the recommendations are aimed (child, classroom, school system), and whether the model is ever named.\n\nWRITE DOWN — for one report: every recommendation, and whether it targets the child or the environment.\n\nASK AFTERWARDS — 'if the environment changed and the child did not, would any of these recommendations become unnecessary?' — the Reference sheet's test for a hidden medical model.",
"s2":    "YOU TAKE — stating in writing, before assessment, the model you are working from, and applying the Reference sheet's test to your own draft recommendations.\n\nTHEY HOLD — how explicitly the model is named in a report sent to a school or family, and how it fits the service's own stance.\n\nWHY THAT SPLIT — naming and testing your model is a discipline you own. How visible it should be for a lay reader, and how it sits with NEPS practice, is your supervisor's call.",
"s3":    "YOU RUN IT — name the model at the start of each case, and in supervision show that your recommendations are consistent with it.\n\nWHAT THEY ARE WATCHING FOR — claiming a biopsychosocial or social model and writing a report where every recommendation targets the child.\n\nSTEPPING IN LOOKS LIKE — 'you've said biopsychosocial. Which of these recommendations changes the environment?'",
"s4":    "YOU DO IT ALONE — name the model in the case file and the report method, and check that the recommendations match it: if you claim biopsychosocial, at least one targets the environment.\n\nPASS TEST — Stated and consistent\n\nEVIDENCE TO FILE — the report method and recommendations sections. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a report that opens with a social-model paragraph and closes with six child-directed recommendations and nothing for the classroom.",
"s5":    "YOU CAN TEACH IT — you can explain the medical, social and biopsychosocial models, cite Engel (1977) and Oliver (2013), and show how each produces different recommendations for the same child.\n\nWHEN IT GOES WRONG — you can say what to do when a school expects a within-child report to unlock resources: explain the needs clearly for the resource application and still include the environmental recommendations the formulation requires.",
"error": "Claiming a biopsychosocial or social model while writing a report whose recommendations all target the child.",
"feeds": "→ Feeds into 'Consider the school environment as a contributor' and 'Show the levels interacting rather than listed'.",
"evidence":"Report — method and recommendations · Log sheet tagged 2. Formulation"},

("Account for the biopsychosocial context","Consider biological and developmental contributors"): {
"why":   "Birth and developmental history, hearing and vision, sleep, chronic illness, medication and its timing, genetic conditions and early intervention can all contribute. The Reference sheet's example: a history of glue ear in the infant classes is a live hypothesis for a literacy difficulty presenting at eight, and is routinely missed because nobody asks about hearing once it has resolved. CORU SoP 5.2 is mapped here. Record history without using it and a treatable contributor goes unexamined.",
"s1":    "WATCH FOR — which history questions your supervisor always asks (hearing, vision, sleep, medication, early milestones, early intervention), and how they use the answers in the formulation.\n\nWRITE DOWN — the history questions, and one example of a history item that changed a hypothesis.\n\nASK AFTERWARDS — 'when do you ask for an up-to-date hearing or vision check before interpreting test results?'",
"s2":    "YOU TAKE — taking the developmental history in the parent interview using a structured checklist, and reading any medical or CDNT reports on file (with consent).\n\nTHEY HOLD — interpretation of medical information outside psychology, and the decision to recommend a GP, audiology or ophthalmology check.\n\nWHY THAT SPLIT — history taking is a skill you should practise every time. Interpreting medical information and recommending medical checks sits at the edge of competence.",
"s3":    "YOU RUN IT — take the history and state in supervision which items are live hypotheses for the presenting difficulty, and which are background.\n\nWHAT THEY ARE WATCHING FOR — a history section filled in and then never referred to, and test scores interpreted without asking whether hearing or vision is current.\n\nSTEPPING IN LOOKS LIKE — 'mum mentioned grommets at four. What does that do to your phonological hypothesis?'",
"s4":    "YOU DO IT ALONE — take the developmental and medical history on every case, name any item that bears on the difficulty, and use it in the formulation or recommend the check that would clarify it.\n\nPASS TEST — History used, not just recorded\n\nEVIDENCE TO FILE — the background and formulation sections. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a literacy difficulty attributed entirely to phonological processing, with a history of recurrent ear infections in the background section and never mentioned again.",
"s5":    "YOU CAN TEACH IT — you can explain which biological and developmental factors commonly bear on school difficulties, how to ask about them sensitively, and when to recommend a check before interpreting results.\n\nWHEN IT GOES WRONG — you can say what to do when a hearing or vision problem emerges after you have tested: note it in the report, qualify the affected scores, recommend the check, and plan to reassess.",
"error": "Recording a relevant history item, such as glue ear, and never using it as a hypothesis.",
"feeds": "→ Feeds into 'Generate more than one hypothesis' and 'Show the levels interacting rather than listed'.",
"evidence":"Report — background and formulation · Log sheet tagged 2. Formulation"},

("Account for the biopsychosocial context","Consider family, culture and community influence"): {
"why":   "Home language and exposure to the language of instruction, home literacy practices, parental experience of school, migration and displacement, and the family's own construction of the difficulty all shape what you see. For a child assessed through an interpreter this is not background: it changes what the scores mean (Reference sheet). CORU SoP 5.16 and 5.24 are mapped here. Cummins's (1979) distinction between conversational and academic language is the classic warning: fluent chat does not mean academic English is secure.",
"s1":    "WATCH FOR — how your supervisor asks about home language, time in Ireland and in English-medium schooling, and the family's view of the difficulty, and how those answers change the interpretation of verbal scores.\n\nWRITE DOWN — the questions asked, and where in the report language and culture are addressed.\n\nASK AFTERWARDS — 'when a child has English as an additional language, which scores do you trust least, and how do you say so in the report?'",
"s2":    "YOU TAKE — gathering language, cultural and community information in the parent interview, arranging an interpreter where needed, and noting the family's own explanation of the difficulty.\n\nTHEY HOLD — decisions on which standardised measures are defensible for this child and how their limitations are worded.\n\nWHY THAT SPLIT — gathering context is interview work you can do well. Judging whether a norm-referenced score means anything for this child is a technical call with consequences.",
"s3":    "YOU RUN IT — gather the context, and in supervision explain how it changes the interpretation of each verbally mediated score.\n\nWHAT THEY ARE WATCHING FOR — EAL treated as a footnote, the family's construction of the difficulty left out, and assumptions about a culture made without asking.\n\nSTEPPING IN LOOKS LIKE — 'he has been in English-medium school for eighteen months. What does that do to the vocabulary score?'",
"s4":    "YOU DO IT ALONE — address home language, culture and community in the formulation, say how they affect the meaning of the scores, and include the family's view of the difficulty.\n\nPASS TEST — Cultural and linguistic factors addressed explicitly\n\nEVIDENCE TO FILE — the background, results and formulation sections. Log against 2. Formulation and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a child in her second year in Ireland reported as having a verbal reasoning difficulty on the basis of an English-normed test, with language mentioned only in the background.",
"s5":    "YOU CAN TEACH IT — you can explain why language exposure changes the meaning of verbally mediated scores, how to work with interpreters, and how to include the family's construction without adopting it uncritically.\n\nWHEN IT GOES WRONG — you can say what to do when you realise you interpreted scores without accounting for language: amend the report, qualify or withdraw the affected scores, and explain the change to the school and family.",
"error": "Treating English as an additional language as a footnote rather than as something that changes every verbally mediated score.",
"feeds": "→ Feeds into 'Show the levels interacting rather than listed' and into Assessment — 'Adapt standardised procedure and record the adaptation'.",
"evidence":"Report — background, results and formulation · Log sheet tagged 2. Formulation and 1. Assessment"},

("Account for the biopsychosocial context","Consider the school environment as a contributor"): {
"why":   "The school is a contributor, not a backdrop: class size, teaching approach, how much of the day is independent written work, staff turnover, transitions, acoustics, seating, and whether the NEPS Continuum of Support level documented in the Student Support File is actually happening. The Reference sheet calls the gap between recorded and observed support 'a finding worth stating plainly'. CORU SoP 5.14 is mapped here. Miss the environment and you recommend only what the school already does.",
"s1":    "WATCH FOR — what your supervisor notices in the classroom beyond the child: class size, noise, where the child sits, how instructions are given, how long independent tasks last, and whether the support in the plan is visible in the room.\n\nWRITE DOWN — the environmental features, and any gap between the Student Support File and what you saw.\n\nASK AFTERWARDS — 'how do you raise a gap between the plan and the practice without the teacher feeling blamed?'",
"s2":    "YOU TAKE — reading the Student Support File before the visit, and recording environmental features and support actually delivered during the observation.\n\nTHEY HOLD — how the environmental findings are worded and discussed with the teacher and principal.\n\nWHY THAT SPLIT — observing and comparing is data collection you can do well. Naming a gap in a school's practice needs a relationship with the school and careful wording.",
"s3":    "YOU RUN IT — include class size, teacher changes, transitions and the recorded-v-observed support gap in your formulation, and discuss wording in supervision.\n\nWHAT THEY ARE WATCHING FOR — environment described in a context paragraph and never used, and a gap between file and practice seen but left unsaid.\n\nSTEPPING IN LOOKS LIKE — 'the plan says daily small-group reading. Did you see it? If not, that belongs in the formulation.'",
"s4":    "YOU DO IT ALONE — consider class size, teacher change, transitions and the support actually delivered, name those that contribute, and write at least one recommendation aimed at the environment.\n\nPASS TEST — Class size, teacher change, transitions considered\n\nEVIDENCE TO FILE — the observation notes and the formulation. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — a report that recommends the School Support Plus plan already in the file, without noticing that none of it was happening.",
"s5":    "YOU CAN TEACH IT — you can explain how the school environment contributes to a difficulty, what to look for in an observation, and how to state a recorded-v-observed gap in neutral, factual language.\n\nWHEN IT GOES WRONG — you can say what to do when a school disputes an environmental finding: return to your observation notes, share what you saw factually, and agree a review rather than withdrawing the finding.",
"error": "Describing the classroom as context and never treating it as a contributor to the difficulty.",
"feeds": "→ Feeds into 'Show the levels interacting rather than listed' and into Intervention — 'Check the school can actually resource it'.",
"evidence":"Observation notes · Report — formulation · Log sheet tagged 2. Formulation"},

("Account for the biopsychosocial context","Show the levels interacting rather than listed"): {
"why":   "The Reference sheet names this as the move that separates grade 5 from grade 3. 'John has a phonological difficulty. His class has 29 pupils. His first language is Ukrainian' is a list. Showing how each compounds the others, and which interaction accounts for the size of the gap, is a formulation. CORU SoP 5.16 is mapped here. Bronfenbrenner and Morris's (2006) bioecological model is the theoretical basis. A list leaves the reader unable to see where to intervene.",
"s1":    "WATCH FOR — the sentences in your supervisor's formulation that link levels: 'compounded by', 'which means that', 'so that'. Notice whether they say which interaction accounts for the size of the difficulty.\n\nWRITE DOWN — one linking sentence, and the levels it connects.\n\nASK AFTERWARDS — 'how do you decide which interaction matters most, rather than just connecting everything to everything?'",
"s2":    "YOU TAKE — drafting the formulation paragraph for a joint case as interactions: each contributor, what it does to the others, and the combined effect.\n\nTHEY HOLD — testing whether each claimed interaction is supported by the evidence or only plausible.\n\nWHY THAT SPLIT — writing interactions is the skill you are building. Checking each link against the data needs a second reader who can see an unsupported leap.",
"s3":    "YOU RUN IT — write the formulation as interacting levels and state which interaction explains the size of the gap, then defend it in supervision.\n\nWHAT THEY ARE WATCHING FOR — a list in paragraph form, and interactions asserted with no evidence ('the class size affects his reading').\n\nSTEPPING IN LOOKS LIKE — 'how does the class size make the phonological difficulty worse? What did you see that shows it?'",
"s4":    "YOU DO IT ALONE — write the formulation so each level is connected to at least one other, say which interaction accounts for the size of the difficulty, and base at least one recommendation on changing that interaction.\n\nPASS TEST — The formulation connects them\n\nEVIDENCE TO FILE — the formulation section. Log against 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — separate paragraphs on biological, family and school factors with no sentence connecting any of them.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to turn a list into an interacting formulation, using the Reference sheet's worked example and Bronfenbrenner and Morris (2006), and explain why the interaction points to where to intervene.\n\nWHEN IT GOES WRONG — you can say what to do when you cannot evidence an interaction: say which levels contribute, state that how they interact is not yet clear, and plan what would clarify it.",
"error": "Listing biological, family and school factors in separate paragraphs without showing how they affect each other.",
"feeds": "→ Feeds into Intervention — 'Write recommendations naming the Continuum of Support level', and into the whole-case formulation in 'Show the reasoning step by step'.",
"evidence":"Report — formulation · Appendix 5 · Log sheet tagged 2. Formulation"},

}
