"""Intervention micro-skills, part B.

Macros: Write recommendations naming the Continuum of Support level ·
Observe and deliver parental feedback sessions ·
Observe and then contribute to teacher consultation.
"""

M1 = "Write recommendations naming the Continuum of Support level"
M2 = "Observe and deliver parental feedback sessions"
M3 = "Observe and then contribute to teacher consultation"

MICRO = {

# ---------------------------------------------------------------------------
# M1 · Write recommendations naming the Continuum of Support level
# ---------------------------------------------------------------------------

(M1, "State the Continuum level for each recommendation"): {
"why": "Irish schools allocate support through the NEPS Continuum of Support: Classroom Support, School Support and School Support Plus (NEPS, Special Educational Needs: A Continuum of Support — Guidelines for Teachers, 2007; post-primary guidelines 2010). A recommendation with no level leaves the principal and SET to guess which pot of time it comes from, and the guess is usually the lowest one. Naming the level also tells the school which paperwork follows — a Classroom Support Plan or a Student Support File with review dates.",
"s1": "WATCH FOR — where in your supervisor's reports the level appears: in a heading above each group of recommendations, in each sentence, or once in the summary. Notice whether they justify the level against what has already been tried at the level below.\n\nWRITE DOWN — for two or three of their reports, each recommendation and the level attached to it, and any recommendation that has no level.\n\nASK AFTERWARDS — 'how do you decide between School Support and School Support Plus when the school has already been doing small-group work for a term?'",
"s2": "YOU TAKE — drafting the recommendations section of a supervised case with the level stated in each recommendation, and a one-line justification for any recommendation at School Support Plus.\n\nTHEY HOLD — the final call on the level, because they know how this school and this SENO respond to each level and what has been agreed at previous consultations.\n\nWHY THAT SPLIT — attaching a level is a mechanical habit you can build now. Judging the level against local history and resource needs knowledge of the school you do not yet have.",
"s3": "YOU RUN IT — write the full recommendations section with levels and justifications and bring it to supervision before the report goes out.\n\nWHAT THEY ARE WATCHING FOR — a level named without saying why it is not the one below, and a School Support Plus recommendation with no evidence of what happened at School Support first.\n\nSTEPPING IN LOOKS LIKE — 'you've said School Support Plus. What has the SET already done at School Support, for how long, and what changed?'",
"s4": "YOU DO IT ALONE — every recommendation in every report you write carries a named Continuum level, with a justification wherever the level is higher than the child's current one.\n\nPASS TEST — The level appears in the text\n\nEVIDENCE TO FILE — the recommendations section of an anonymised report extract, with levels visible. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — 'X would benefit from additional literacy support' with no level, so the school files it and nothing changes in the timetable.",
"s5": "YOU CAN TEACH IT — you can explain the three levels, who leads each, what documentation each generates, and why a level must be justified against the one below — citing the NEPS Continuum guidelines rather than memory.\n\nWHEN IT GOES WRONG — you can say what to do when a report has already gone out without levels: send a short addendum to the principal and SET naming the level for each recommendation, and log the correction with your supervisor.",
"error": "Recommendations with no Continuum level, so the school cannot tell which resource they draw on.",
"feeds": "→ Feeds into 'Check the school can actually resource it', 'Name who delivers', and into the Student Support File review.",
"evidence": "Report — recommendations · Appendix 5 · Log sheet tagged 3. Intervention"},

(M1, "Check the school can actually resource it"): {
"why": "A recommendation the school cannot staff becomes a line in a file that nobody delivers, and the family reads it as a promise broken. Special education teaching hours are allocated to schools under the Department of Education's SET allocation model (Circulars 0013/2017 primary and 0014/2017 post-primary — check for the current circular before quoting), and the principal deploys them. CORU SoP 5.35 is the standard mapped here. Asking before you write is how you keep recommendations honest.",
"s1": "WATCH FOR — when your supervisor asks the principal or SET what is possible: before the assessment, during the planning meeting, or after the draft. Notice the questions — how many SET hours are free, which groups already run, whether an SNA is attached to the class.\n\nWRITE DOWN — the resource questions they ask and the answers the school gives, anonymised.\n\nASK AFTERWARDS — 'when a child needs something the school genuinely cannot provide, how do you write that without setting the school up to fail?'",
"s2": "YOU TAKE — preparing a short list of resource questions for the SET before the feedback meeting: existing groups, available time, programmes already bought in, staff trained in them.\n\nTHEY HOLD — the conversation with the principal about deployment, and any recommendation that the school seek resource from outside, such as through the SENO.\n\nWHY THAT SPLIT — factual questions to the SET are safe for you to ask. Asking a principal to re-deploy staff is negotiation that relies on a relationship your supervisor holds.",
"s3": "YOU RUN IT — check each draft recommendation with the SET before the report is finalised, and adjust wording where the resource does not exist.\n\nWHAT THEY ARE WATCHING FOR — recommending a named programme (for example a specific reading intervention) that the school has never bought, has no trained staff for, or cannot timetable.\n\nSTEPPING IN LOOKS LIKE — 'before this goes in — did you ask whether anyone in the school is trained in that? Who would deliver it next Monday?'",
"s4": "YOU DO IT ALONE — before finalising recommendations, confirm with the SET or principal that each one can be resourced, and record that you asked.\n\nPASS TEST — You asked before recommending\n\nEVIDENCE TO FILE — a note on the case file of the date and who you checked with. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — daily one-to-one precision teaching recommended for a child in a school whose SET time is fully committed, discovered at the review when nothing has happened.",
"s5": "YOU CAN TEACH IT — you can explain how SET hours reach a school, who decides their deployment, and the difference between recommending within the school's resource and recommending that the school seek more.\n\nWHEN IT GOES WRONG — you can say what to do when a child's need exceeds what the school can provide: say so plainly, recommend the achievable version first, and name the route for further resource separately, with your supervisor's agreement.",
"error": "Recommending an intervention without asking whether anyone in the school can deliver it.",
"feeds": "→ Feeds into 'Name who delivers', 'Name how often and for how long', and 'Limit the number so they can be acted on'.",
"evidence": "Case file note of resource check · Appendix 5 · Log sheet tagged 3. Intervention"},

(M1, "Name who delivers"): {
"why": "'The school should' is the most common phrase in recommendations and the least likely to be acted on, because it belongs to nobody. Addressing each recommendation to a role — class teacher, SET, SNA, principal, parent — is one of the features the Reference sheet lists as predicting implementation. CORU SoP 5.34 is the standard mapped here. Name a role, not a person, because staff move mid-year.",
"s1": "WATCH FOR — how your supervisor words the first few words of each recommendation. Many start with the role: 'The class teacher will…', 'The SET will…'. Notice whether parents are given recommendations too, and how those are phrased.\n\nWRITE DOWN — any recommendation in their reports that is addressed to 'the school', 'staff' or nobody, and what they would change.\n\nASK AFTERWARDS — 'why do you name the role rather than the teacher's name, and when would you name the person?'",
"s2": "YOU TAKE — rewriting a draft set of recommendations so that each begins with a named role and contains one verb that role can do.\n\nTHEY HOLD — decisions about which role is appropriate where the school's structure is unclear, for example whether an SNA can be asked to deliver a teaching task.\n\nWHY THAT SPLIT — the rewording is a discipline you can practise at once. Knowing the limits of each role (the SNA scheme is for care needs — check the current NCSE/DE guidance) needs supervision.",
"s3": "YOU RUN IT — write the recommendations with roles attached and walk through them with the SET before the report is finalised, asking 'is this the right person for this?'\n\nWHAT THEY ARE WATCHING FOR — teaching tasks assigned to an SNA, and recommendations addressed to 'home and school' that neither side owns.\n\nSTEPPING IN LOOKS LIKE — 'who, specifically, does this on Monday morning? If you can't answer, the sentence isn't finished.'",
"s4": "YOU DO IT ALONE — every recommendation you write opens with the role responsible for it.\n\nPASS TEST — Responsibility assigned to a role\n\nEVIDENCE TO FILE — recommendations section of an anonymised report extract. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — 'Visual supports should be used throughout the day' — nobody makes them, nobody uses them, and at review everyone thought someone else was doing it.",
"s5": "YOU CAN TEACH IT — you can explain why ownership predicts implementation, what each school role can and cannot be asked to do, and how to write a parent recommendation that does not sound like homework.\n\nWHEN IT GOES WRONG — you can say what to do when the named role is vacant or on leave: revise the recommendation with the principal, name the covering role, and adjust the review date if needed.",
"error": "Addressing recommendations to 'the school', so nobody owns them.",
"feeds": "→ Feeds into 'Name how often and for how long', and into 'Agree next steps and who does what' in the feedback session.",
"evidence": "Report — recommendations · Appendix 5 · Log sheet tagged 3. Intervention"},

(M1, "Name how often and for how long"): {
"why": "Dose matters: implementation research finds that how much of an intervention is delivered affects outcome (Durlak & DuPre, 2008, American Journal of Community Psychology). 'Regular phonological awareness work' could mean five minutes a fortnight or twenty minutes daily, and the school will pick the version that fits its timetable. CORU SoP 5.34 and PSI Code 2.3.2 are the standards mapped here. Without frequency and duration you also cannot tell at review whether the intervention failed or was never delivered.",
"s1": "WATCH FOR — whether your supervisor gives frequency (times per week), session length (minutes), and total duration (weeks or until a review date), and where they take the figures from — a programme manual, research, or what the school can manage.\n\nWRITE DOWN — the dosage in each recommendation you see, and any recommendation without one.\n\nASK AFTERWARDS — 'where did the three times a week for ten weeks come from — the programme, the evidence, or the timetable?'",
"s2": "YOU TAKE — adding frequency, session length and duration to each draft recommendation, and noting the source for each figure (programme manual, published study, or negotiated with the SET).\n\nTHEY HOLD — judgement where the evidence-based dose is more than the school can give, and what compromise is still worth recommending.\n\nWHY THAT SPLIT — finding the stated dose is research you can do. Deciding how far below it an intervention stops being worth doing is a clinical judgement.",
"s3": "YOU RUN IT — write dosage into every recommendation and explain in supervision where each figure came from.\n\nWHAT THEY ARE WATCHING FOR — invented precision ('15 minutes, four times weekly') with no source, and dosages that add up across recommendations to more SET time than the child could receive.\n\nSTEPPING IN LOOKS LIKE — 'add these up for me. How many minutes a week is this child out of class?'",
"s4": "YOU DO IT ALONE — each recommendation that involves direct work states how often, for how long each time, and for how many weeks.\n\nPASS TEST — Dosage specified\n\nEVIDENCE TO FILE — recommendations section of an anonymised report extract. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at the review the SET says the programme 'didn't work', and it emerges it ran once a week for four weeks when the manual assumes daily sessions.",
"s5": "YOU CAN TEACH IT — you can explain dosage as frequency × session length × duration, why it matters for fidelity (Durlak & DuPre, 2008), and how to find the intended dose in a programme manual.\n\nWHEN IT GOES WRONG — you can say what to do when a review shows the dose was not delivered: record it as an implementation gap, not an intervention failure, and agree a realistic dose before judging effect.",
"error": "Writing 'regular' or 'ongoing' instead of a frequency and a duration.",
"feeds": "→ Feeds into 'State how progress will be measured' and 'Set a review date'.",
"evidence": "Report — recommendations · Appendix 5 · Log sheet tagged 3. Intervention"},

(M1, "Limit the number so they can be acted on"): {
"why": "A class teacher with 28 children cannot act on fifteen recommendations, so she picks the easiest two, which may not be the most important. The Reference sheet's rule is that five actionable recommendations beat fifteen aspirational ones, sequenced with a small number first. CORU SoP 5.34 is the standard mapped here. Prioritising is also a test of your formulation: if you cannot say which recommendation matters most, you have not yet decided what is driving the difficulty.",
"s1": "WATCH FOR — how many recommendations your supervisor typically writes, whether they number or group them, and whether they mark any as 'first' or 'priority'.\n\nWRITE DOWN — the count per report, and how they handle the extra ideas that did not make the list — an appendix of strategies, a handout, or nothing.\n\nASK AFTERWARDS — 'how do you decide what to leave out when everything in the list would help?'",
"s2": "YOU TAKE — drafting the full list of possible recommendations, then ranking them by how directly each addresses the formulation and how feasible each is.\n\nTHEY HOLD — the cut: which five survive, and whether the rest go in a strategy appendix or are dropped.\n\nWHY THAT SPLIT — generating and ranking is your formulation work made visible. Cutting well needs a sense of what a school actually does with a long list, which comes from seeing reviews.",
"s3": "YOU RUN IT — bring no more than five to seven recommendations to supervision, each linked to a named part of the formulation, with the first two marked as priorities.\n\nWHAT THEY ARE WATCHING FOR — a long list kept because each item felt worth including, and generic strategies that are not linked to this child's formulation.\n\nSTEPPING IN LOOKS LIKE — 'if the teacher only did one of these, which one would you want it to be — and why is it number four?'",
"s4": "YOU DO IT ALONE — write a recommendations section that is short, prioritised and sequenced, with any additional strategies moved to an appendix or handout.\n\nPASS TEST — Five that happen beat fifteen that do not\n\nEVIDENCE TO FILE — recommendations section of an anonymised report extract. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — two pages of recommendations; at review the teacher has done three, none of them the ones that addressed the core difficulty.",
"s5": "YOU CAN TEACH IT — you can explain why fewer recommendations are implemented more, how to link each one to the formulation, and how to use an appendix for everything that is useful but not essential.\n\nWHEN IT GOES WRONG — you can say what to do when a school or parent asks for 'everything that might help': give the prioritised list, add the strategy bank separately, and say plainly which items come first.",
"error": "A long, unprioritised list, so the school chooses the easiest items rather than the important ones.",
"feeds": "→ Feeds into 'State how progress will be measured', and into Formulation — linking each recommendation to a hypothesis.",
"evidence": "Report — recommendations · Appendix 5 · Log sheet tagged 3. Intervention"},

(M1, "State how progress will be measured"): {
"why": "A recommendation with no measure cannot be evaluated, so it continues or stops on impression. CORU SoP 3.8 and PSI Code 3.1.2 are the standards mapped here, and the Reference sheet names the evaluation line as the element most often omitted in trainee reports. The NEPS Continuum expects support plans at School Support and School Support Plus to include targets and review (NEPS Continuum guidelines — read the source for the exact wording). A measure with no named person to take it is not taken.",
"s1": "WATCH FOR — the measures your supervisor names: a curriculum-based probe, a re-administered subtest, a frequency count, a teacher rating, the child's own scaling. Notice who they name to collect it and when.\n\nWRITE DOWN — for each recommendation, the measure and the measurer, and any that have neither.\n\nASK AFTERWARDS — 'how do you choose a measure the teacher will actually take, rather than the one you would ideally want?'",
"s2": "YOU TAKE — proposing a baseline and a measure for each recommendation, chosen from what the school already collects where possible (for example standardised test results, reading records, attendance).\n\nTHEY HOLD — whether the measure is sensitive enough to show change in the time available, and whether it is fair to ask the school to collect it.\n\nWHY THAT SPLIT — matching a measure to a target is a skill you can practise. Knowing which measures actually move over one term comes from seeing many reviews.",
"s3": "YOU RUN IT — write the measure and the measurer into each recommendation and check with the SET that it is realistic.\n\nWHAT THEY ARE WATCHING FOR — a full standardised retest proposed after six weeks (too insensitive, and possibly practice effects — check the test manual for retest interval), and 'teacher observation' with no defined behaviour.\n\nSTEPPING IN LOOKS LIKE — 'what number will the SET write down in March, and what number would tell us it worked?'",
"s4": "YOU DO IT ALONE — each recommendation states the baseline where known, the measure, who takes it, and when.\n\nPASS TEST — A measure and a measurer named\n\nEVIDENCE TO FILE — recommendations section of an anonymised report extract, and the agreed measures on the Student Support File where you contributed. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at review everyone agrees the child 'seems more settled', nobody has data, and the support is withdrawn or continued on opinion.",
"s5": "YOU CAN TEACH IT — you can explain the difference between an outcome measure and an implementation check, how to choose one sensitive enough for a term, and why naming the measurer matters as much as naming the measure.\n\nWHEN IT GOES WRONG — you can say what to do when the measure was not collected: agree a simpler one at review, take a baseline then, and set a new date rather than judging the intervention on nothing.",
"error": "Recommending an intervention with no measure and no named person to collect it.",
"feeds": "→ Feeds into 'Set a review date', and into evaluation of intervention outcomes.",
"evidence": "Report — recommendations · Student Support File contribution · Appendix 5 · Log sheet tagged 3. Intervention"},

(M1, "Set a review date"): {
"why": "Without a date, review happens when someone remembers, which is usually at the next crisis. The Continuum of Support is described by NEPS as a problem-solving cycle of assessment, planning, intervention and review (NEPS Continuum guidelines — read the source for how review is framed at each level). PSI Code 2.3.2 is the standard mapped here. A dated review also protects the child from an intervention continuing for a year after it has stopped working.",
"s1": "WATCH FOR — whether your supervisor writes an actual date or a term ('end of Term 2'), who they expect to convene the review, and whether they plan to attend.\n\nWRITE DOWN — the review points in their reports, and whether they line up with the school's own Student Support File review cycle.\n\nASK AFTERWARDS — 'when you set a review for a school you might not be back in, who makes sure it happens?'",
"s2": "YOU TAKE — proposing a review date for each case, checked against the school calendar (mid-term breaks, Christmas, exam periods at post-primary), and naming who convenes it.\n\nTHEY HOLD — whether the EP attends the review or the school runs it alone, which depends on service time allocation to the school.\n\nWHY THAT SPLIT — picking a workable date is practical and yours. Committing service time to a review is a caseload decision your supervisor makes.",
"s3": "YOU RUN IT — write the review date into the report and the feedback record, and put it in your own diary if you are attending.\n\nWHAT THEY ARE WATCHING FOR — a date too soon for the dose to have had effect, or one that falls after your placement ends with no handover. Cavan runs 05/10/2026–18/12/2026, so a February review needs a named person in the service.\n\nSTEPPING IN LOOKS LIKE — 'you'll be gone by then. Who in the school, and who here, will know this review is due?'",
"s4": "YOU DO IT ALONE — every report and consultation record you write ends with a review date in DD/MM/YYYY and the role responsible for convening it.\n\nPASS TEST — There is a date\n\nEVIDENCE TO FILE — report and consultation record, anonymised extract. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — 'to be reviewed in due course', and the next time the child is discussed is a re-referral eighteen months later.",
"s5": "YOU CAN TEACH IT — you can explain how review fits the Continuum's cycle, how to choose a date that allows the dose to work, and how to hand review over when your placement ends.\n\nWHEN IT GOES WRONG — you can say what to do when a review date passes unheld: contact the school, reset a date, and record in the case file that the original review did not happen.",
"error": "'To be reviewed' with no date and no one responsible for convening it.",
"feeds": "→ Feeds into 'Agree actions with a review point' in consultation, and into the Student Support File review cycle.",
"evidence": "Report — recommendations · consultation record · Appendix 5 · Log sheet tagged 3. Intervention"},

(M1, "Build at least one on a strength"): {
"why": "Recommendations that only compensate for deficit tell the child, the family and the school that the child is a list of problems. CORU SoP 1.3 is the standard mapped here. Strength-based assessment argues that strengths are also leverage for intervention (Buckley & Epstein, 2004, California School Psychologist). A child who is a confident talker but a weak reader may learn more through oral rehearsal before writing than through more of the reading she already avoids.",
"s1": "WATCH FOR — whether your supervisor's recommendations use any strength found in the assessment, and how — as a route into the difficulty, as a role in class, or as a source of confidence.\n\nWRITE DOWN — the strengths named in the findings of their reports, and which of them reappear in the recommendations.\n\nASK AFTERWARDS — 'how do you turn a strength into a recommendation rather than a nice sentence in the summary?'",
"s2": "YOU TAKE — listing the child's strengths from all sources (parent, teacher, child, testing) and drafting one recommendation that uses a strength as the means of intervention.\n\nTHEY HOLD — whether the strength is robust enough to build on, or a single observation that should not carry a recommendation.\n\nWHY THAT SPLIT — finding strengths is part of your assessment. Judging whether one is reliable enough to lean on needs experience of how often apparent strengths hold up.",
"s3": "YOU RUN IT — bring your recommendations to supervision with at least one explicitly built on a named strength, and say which evidence shows that strength.\n\nWHAT THEY ARE WATCHING FOR — a strength that is generic ('she is a lovely girl') or used only as praise, rather than as the means of intervention.\n\nSTEPPING IN LOOKS LIKE — 'you say he's good at drawing. How could that be how he plans a story, rather than a reward after it?'",
"s4": "YOU DO IT ALONE — at least one recommendation in each report uses a specific, evidenced strength as the route to change.\n\nPASS TEST — Not only compensation for deficit\n\nEVIDENCE TO FILE — the strength-based recommendation in an anonymised report extract. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a strengths paragraph in the findings that is never used again, and ten recommendations that each describe something the child cannot do.",
"s5": "YOU CAN TEACH IT — you can explain the difference between naming a strength and building on it, cite the strength-based assessment literature, and give two examples of strengths used as intervention routes.\n\nWHEN IT GOES WRONG — you can say what to do when the assessment found few strengths: go back to the parent and child, ask what they enjoy and are proud of, and treat the gap as a gap in your assessment.",
"error": "A strengths section in the findings that never reaches the recommendations.",
"feeds": "→ Feeds into 'Name strengths specifically rather than as preamble' in feedback, and into Formulation — protective factors.",
"evidence": "Report — recommendations · Appendix 5 · Log sheet tagged 3. Intervention"},

}

# ---------------------------------------------------------------------------
# M2 · Observe and deliver parental feedback sessions
# ---------------------------------------------------------------------------

MICRO.update({

(M2, "Plan the first three sentences"): {
"why": "The opening sets whether a parent can listen for the rest of the session. Parents often arrive braced for a verdict, and until they know the headline they may hear little else (Reference sheet, 'Structuring the session'). CORU SoP 2.1 is the standard mapped here. An improvised opening drifts into test descriptions and pleasantries, and the parent spends ten minutes waiting for the point.",
"s1": "WATCH FOR — your supervisor's exact first three sentences in a feedback session: the welcome, the check on what the parent already knows and wants, and the sign-post of what the session will cover.\n\nWRITE DOWN — those sentences as close to verbatim as you can, straight after, and how the parent's posture changed once the plan was clear.\n\nASK AFTERWARDS — 'do you script your opening, and does it change when you know the news is hard?'",
"s2": "YOU TAKE — writing the first three sentences for a supervised feedback session and saying them aloud in supervision beforehand.\n\nTHEY HOLD — the session itself, and the decision to adapt the opening if the parent arrives upset, late or with someone unexpected.\n\nWHY THAT SPLIT — the script is preparation you can own. Changing course when the room is not what you planned needs the confidence of someone who has done many sessions.",
"s3": "YOU RUN IT — open the session yourself, with your supervisor present, using your planned three sentences, then hand to the structure you agreed.\n\nWHAT THEY ARE WATCHING FOR — an opening that is all warm-up and no sign-post, or that jumps to test names before asking what the parent wants from today.\n\nSTEPPING IN LOOKS LIKE — 'before we go on — can I check what you were hoping we'd get to today?'",
"s4": "YOU DO IT ALONE — before every feedback session, write and rehearse the first three sentences: welcome, check what they know and want, say what the session will cover and roughly how long.\n\nPASS TEST — You knew how you would open\n\nEVIDENCE TO FILE — your session plan (no identifying details) and a reflective note. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — five minutes about the weather and the test battery, and a parent who interrupts with 'so is it dyslexia or not?'",
"s5": "YOU CAN TEACH IT — you can explain why the opening matters, what the three sentences need to do, and how to adapt them when the parent arrives angry, tearful or with a question already.\n\nWHEN IT GOES WRONG — you can say what to do when the opening falls flat: pause, name it ('I've started with a lot — can I check what matters most to you today?'), and restart from their answer.",
"error": "Improvising the opening, so the parent waits through preamble for the point.",
"feeds": "→ Feeds into 'Ask what the parent hopes to hear before starting' and 'Give the overall picture before the detail'.",
"evidence": "Session plan · reflective note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Give the overall picture before the detail"): {
"why": "Parents sit through explanation waiting for the verdict and hear none of it (Reference sheet, 'Structuring the session'). The same principle — say the headline, then explain — appears in breaking-news protocols in medicine, for example SPIKES (Baile et al., 2000, The Oncologist). CORU SoP 5.27 is the standard mapped here: communication suited to the audience. Leading with scores puts a number between the parent and their child.",
"s1": "WATCH FOR — when your supervisor gives the headline: which minute of the session, in what words, and whether any number is mentioned before it.\n\nWRITE DOWN — the headline sentence verbatim, and the order in which detail followed — findings, what it means day to day, recommendations.\n\nASK AFTERWARDS — 'how do you boil a twelve-page report into one sentence a parent can repeat at home?'",
"s2": "YOU TAKE — drafting the one- or two-sentence headline for a supervised case and the order of the detail beneath it.\n\nTHEY HOLD — delivery of the headline in the session, particularly where it names a diagnosis or a significant difficulty.\n\nWHY THAT SPLIT — distilling the formulation into a sentence tests your understanding and is safe to practise. Delivering significant news for the first time is the moment your supervisor should hold until you have watched it done.",
"s3": "YOU RUN IT — deliver the headline yourself within the first few minutes, in plain words, then walk through the supporting detail.\n\nWHAT THEY ARE WATCHING FOR — a percentile or standard score in the first sentence, and a headline so hedged the parent cannot tell what you found.\n\nSTEPPING IN LOOKS LIKE — 'so, in a sentence, what we found is that…' — finishing the headline for you.",
"s4": "YOU DO IT ALONE — state the overall picture in plain language near the start, before any scores, then give the detail in the order you planned.\n\nPASS TEST — You did not lead with scores\n\nEVIDENCE TO FILE — session plan with headline, and a reflective note. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — twenty minutes of subtest results, then the parent asks 'but what does this mean?' and there is no time left to answer.",
"s5": "YOU CAN TEACH IT — you can explain why headline-first works, how to write one sentence that is honest and not alarming, and how to translate a percentile into a comparison with other children or with classroom demand.\n\nWHEN IT GOES WRONG — you can say what to do when you realise mid-session you have buried the headline: stop, say 'let me give you the main point', and state it before continuing.",
"error": "Leading with test scores so the parent never hears the overall picture.",
"feeds": "→ Feeds into 'Avoid jargon and check understanding repeatedly' and 'Deliver difficult information clearly'.",
"evidence": "Session plan · reflective note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Agree next steps and who does what"): {
"why": "A feedback session that ends in understanding but no action is a conversation, not an intervention. CORU SoP 2.16 is the standard mapped here. Parents often leave feedback meetings with a report and no idea what happens next — who will contact them, when the school plan starts, whether they need to do anything. Agreeing actions in the room is also where you learn which recommendations the family will actually take up.",
"s1": "WATCH FOR — how your supervisor closes: whether they summarise actions aloud, name who does each, give dates, and check the parent agrees.\n\nWRITE DOWN — the actions agreed, the person or role holding each, and whether anything was written down for the parent to take away.\n\nASK AFTERWARDS — 'what do you do when a parent agrees to everything in the room and you suspect none of it will happen?'",
"s2": "YOU TAKE — writing the action summary during the session and reading it back at the end, with roles and dates.\n\nTHEY HOLD — negotiation where parent and school disagree about who should do something, or where the parent wants a referral the service cannot make.\n\nWHY THAT SPLIT — summarising is a skill you can practise safely and is useful to your supervisor. Negotiating between parent and school expectations draws on authority you do not yet hold.",
"s3": "YOU RUN IT — close the session yourself: summarise the agreed actions, name who holds each, check the parent agrees, and say when the written report will arrive.\n\nWHAT THEY ARE WATCHING FOR — every action falling to the school with none for home, or a list of actions with no dates.\n\nSTEPPING IN LOOKS LIKE — 'and from your side at home — is there one thing from today you'd like to try?'",
"s4": "YOU DO IT ALONE — end each feedback session with actions agreed aloud, each assigned to a person or role, and confirmed in writing afterwards.\n\nPASS TEST — Someone left with an action\n\nEVIDENCE TO FILE — the post-session note or letter, anonymised. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a parent rings the school three weeks later asking what is happening, and the school thought the psychologist was following up.",
"s5": "YOU CAN TEACH IT — you can explain how to close a session so that each person leaves with a job, why home actions must be small and specific, and how the written follow-up locks in what was said.\n\nWHEN IT GOES WRONG — you can say what to do when the session ends without agreement: say so honestly, agree the next contact date, and write down what was and was not agreed.",
"error": "Ending the session with a shared understanding but no named actions.",
"feeds": "→ Feeds into 'Name who delivers' in recommendations, and into Working with Others — home-school links.",
"evidence": "Post-session note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Avoid jargon and check understanding repeatedly"): {
"why": "Terms such as 'working memory', 'standard score' or 'below average range' mean one thing to you and something else, or nothing, to a parent. PSI Code 4.3.1 is the clause mapped here. A single 'does that make sense?' invites a polite yes. Teach-back — asking the person to say it back in their own words — is a well-studied way to check understanding in health communication (Schillinger et al., 2003, Archives of Internal Medicine).",
"s1": "WATCH FOR — every technical term your supervisor uses in a session and whether they explain it the first time; and each point where they check understanding, and how.\n\nWRITE DOWN — the words that needed explaining and the exact phrasing of their checks ('what will you tell your partner when you get home?').\n\nASK AFTERWARDS — 'how do you know when a parent has understood and is not just being polite?'",
"s2": "YOU TAKE — writing a plain-English version of the key terms for the case, and planning at least two teach-back points in the session.\n\nTHEY HOLD — delivery, and reading the parent's response to decide whether to go back over something.\n\nWHY THAT SPLIT — plain-language translation is preparation you can do well now. Reading whether someone has understood, especially through politeness or distress, is learned by watching.",
"s3": "YOU RUN IT — deliver a section of the feedback, stopping at planned points to ask the parent to say back what they have heard.\n\nWHAT THEY ARE WATCHING FOR — only one check at the end, closed questions ('is that clear?'), and jargon slipping back in when you get nervous.\n\nSTEPPING IN LOOKS LIKE — 'can I just check — when we say working memory, what does that mean for her in the classroom?'",
"s4": "YOU DO IT ALONE — explain technical terms at first use, and check understanding with open questions at more than one point in the session.\n\nPASS TEST — You checked more than once\n\nEVIDENCE TO FILE — session plan with planned checks marked, and reflective note. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the parent nodded throughout, then tells the class teacher the next day that the psychologist said her son has a low IQ.",
"s5": "YOU CAN TEACH IT — you can explain teach-back, give plain-language versions of common assessment terms, and say why 'does that make sense?' is a poor check.\n\nWHEN IT GOES WRONG — you can say what to do when a check reveals a misunderstanding: thank them for saying it, re-explain differently rather than louder, and check again.",
"error": "Checking understanding once, at the end, with a question that invites a polite yes.",
"feeds": "→ Feeds into 'Deliver difficult information clearly', and into report writing for the actual reader.",
"evidence": "Session plan · reflective note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Name strengths specifically rather than as preamble"): {
"why": "Parents recognise the formula: two nice sentences, then 'however'. When strengths are generic they are heard as softening, and the parent waits for the bad news. CORU SoP 1.3 is the standard mapped here. Strength-based feedback, as argued by Buckley and Epstein (2004), treats strengths as information about the child as real as the difficulties. A specific strength also tells a parent you have seen their child, not just their scores.",
"s1": "WATCH FOR — where in the session your supervisor names strengths, how specific they are ('she explained the story's ending better than most children her age' versus 'she's lovely'), and whether strengths reappear later in the recommendations.\n\nWRITE DOWN — each strength named, and the evidence it rested on.\n\nASK AFTERWARDS — 'how do you name a strength so it doesn't sound like the warm-up before the bad news?'",
"s2": "YOU TAKE — drafting two or three specific strengths for the case, each with the evidence behind it (an observation, a subtest, something the child said).\n\nTHEY HOLD — where in the session strengths are placed, which depends on how the parent is likely to receive the main finding.\n\nWHY THAT SPLIT — finding and wording evidenced strengths is your assessment work. Positioning them in a hard conversation is a judgement about this parent that your supervisor is better placed to make.",
"s3": "YOU RUN IT — name the strengths yourself during the session, weaving them into the findings rather than bunching them at the start.\n\nWHAT THEY ARE WATCHING FOR — 'she's a lovely girl, however…', and strengths so general they could describe any child.\n\nSTEPPING IN LOOKS LIKE — 'tell mum what you noticed about how he kept going on that puzzle when it got hard.'",
"s4": "YOU DO IT ALONE — name strengths that are specific to this child, evidenced, and connected to the findings or recommendations.\n\nPASS TEST — It does not sound like a formula\n\nEVIDENCE TO FILE — session plan and reflective note. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the parent's face tightens as soon as you start praising, because they know the 'but' is coming.",
"s5": "YOU CAN TEACH IT — you can explain the difference between strengths as preamble and strengths as findings, and show how one strength can be carried into a recommendation.\n\nWHEN IT GOES WRONG — you can say what to do when a parent dismisses a strength ('she's only like that with you'): take it seriously, ask where else it shows, and treat the difference as information.",
"error": "Using generic praise as a warm-up before the difficulties.",
"feeds": "→ Feeds into 'Build at least one on a strength' in recommendations.",
"evidence": "Session plan · reflective note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Ask what the parent hopes to hear before starting"): {
"why": "Parents arrive with a question — is it autism, will she get an SNA, is it my fault — and until it is addressed they may not hear anything else. Asking takes two minutes and reshapes the session (Reference sheet, 'Structuring the session'). CORU SoP 2.14 and PSI Code 1.4.1 are the standards mapped here (read both for their wording before saying what they require). Asking hands the parent some control over a meeting that is otherwise yours.",
"s1": "WATCH FOR — whether and how your supervisor asks the parent what they are hoping for, and how the answer changes what they say next.\n\nWRITE DOWN — the wording of the question, the parent's answer (anonymised), and any part of the plan the supervisor dropped or moved as a result.\n\nASK AFTERWARDS — 'what do you do when what the parent hopes to hear is not what you are about to tell them?'",
"s2": "YOU TAKE — asking the question at the start of a supervised session and noting the answer.\n\nTHEY HOLD — adjusting the session in response, especially when the parent's hope is for something the findings do not support, such as a diagnosis or a resource.\n\nWHY THAT SPLIT — asking is simple and should be yours early. Responding to a hope you are about to disappoint needs skill you will learn by watching them do it.",
"s3": "YOU RUN IT — ask the question, then adjust your planned order so the parent's main concern is addressed early.\n\nWHAT THEY ARE WATCHING FOR — asking and then ignoring the answer, carrying on with the planned script.\n\nSTEPPING IN LOOKS LIKE — 'you mentioned you were wondering about secondary school — shall we come to that now?'",
"s4": "YOU DO IT ALONE — open every feedback session by asking what the parent wants to know or hopes to hear, and let the answer shape the order.\n\nPASS TEST — You asked\n\nEVIDENCE TO FILE — reflective note recording that you asked and how it changed the session. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at the end of an hour the parent says 'but you haven't told me whether she can get exemption from Irish', which was the only thing they came to ask.",
"s5": "YOU CAN TEACH IT — you can explain why asking first matters for power and listening, and how to respond when the hope and the findings do not match.\n\nWHEN IT GOES WRONG — you can say what to do when the parent's question is outside what you can answer (a resource decision, a diagnosis you cannot make): say so early, name who can, and do not let the whole session wait for it.",
"error": "Delivering a prepared script without finding out what the parent came to hear.",
"feeds": "→ Feeds into 'Answer the question actually asked' and 'Deliver difficult information clearly'.",
"evidence": "Reflective note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Deliver difficult information clearly"): {
"why": "When the news is hard, the temptation is to soften it until it disappears, and the parent leaves reassured about something that is not reassuring. PSI Code 1.3.4 is the clause mapped here — read it for its exact wording. Clear delivery is kinder in the long run: a parent who hears it later from a school, a CDNT or a report they read alone at the kitchen table loses trust in everyone. SPIKES (Baile et al., 2000) is one structure from medicine worth knowing.",
"s1": "WATCH FOR — how your supervisor words the hardest sentence: whether they warn first ('I have some news that may be hard to hear'), say it plainly, and then stop.\n\nWRITE DOWN — the exact words used for the difficult finding, and what they did immediately after.\n\nASK AFTERWARDS — 'how do you stop yourself softening it so much that the parent doesn't hear it?'",
"s2": "YOU TAKE — writing the difficult sentence in advance, plainly, and rehearsing it in supervision.\n\nTHEY HOLD — delivery of the news itself on your early cases, and the decision about whether a second meeting is needed.\n\nWHY THAT SPLIT — writing a clear sentence is the preparation. Saying it to a parent for the first time, and handling what follows, is the part to watch done well before you do it.",
"s3": "YOU RUN IT — deliver the difficult finding yourself, with your supervisor present, using your rehearsed words, then pause.\n\nWHAT THEY ARE WATCHING FOR — hedging so heavy ('there may perhaps be some indication of some difficulties') that the parent cannot tell what was found.\n\nSTEPPING IN LOOKS LIKE — 'to be clear — what we're saying is that…', restating it plainly.",
"s4": "YOU DO IT ALONE — deliver a difficult finding in plain words, warn before it, pause after it, and check what the parent heard.\n\nPASS TEST — The parent left knowing\n\nEVIDENCE TO FILE — reflective note and supervision record. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the parent tells the school afterwards that 'the psychologist said he's grand', when the report says he has a significant language difficulty.",
"s5": "YOU CAN TEACH IT — you can explain warn–say–pause–check, why softening harms, and the difference between being gentle in manner and being unclear in content.\n\nWHEN IT GOES WRONG — you can say what to do when you learn the parent did not take in the message: contact them, offer a follow-up, and say it again plainly — with your supervisor's agreement.",
"error": "Softening difficult news until the parent does not know what was found.",
"feeds": "→ Feeds into 'Hold silence when someone is upset' and 'Say what you do not know'.",
"evidence": "Reflective note · supervision record · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Hold silence when someone is upset"): {
"why": "When a parent cries or goes quiet, the instinct is to fill the silence with more findings, reassurance or recommendations. The Reference sheet names filling a silence after difficult news as a core error. CORU SoP 2.2 is the standard mapped here. Silence gives the parent time to take in what was said and decide what to ask. Filling it tells them the session matters more than their reaction.",
"s1": "WATCH FOR — what your supervisor does in the seconds after difficult news: whether they speak, how long they wait, whether they offer tissues or water, what their first words are when they do speak.\n\nWRITE DOWN — roughly how long the silence lasted, and the first sentence after it.\n\nASK AFTERWARDS — 'how long do you wait, and how do you know when to speak?'",
"s2": "YOU TAKE — the rest of the session after your supervisor has delivered difficult news, with the explicit task of not speaking until the parent does.\n\nTHEY HOLD — the difficult news itself, and any response to strong emotion such as anger.\n\nWHY THAT SPLIT — holding silence is best practised while someone else carries the main responsibility. Your only job is to tolerate the discomfort without rescuing it.",
"s3": "YOU RUN IT — deliver news yourself and then hold the silence, offering only a brief acknowledgement ('this is hard to hear') if needed.\n\nWHAT THEY ARE WATCHING FOR — you rushing on to the recommendations, or filling the gap with reassurance you cannot stand behind ('she'll be absolutely fine').\n\nSTEPPING IN LOOKS LIKE — a small gesture to wait, or 'take your time — there's no hurry today.'",
"s4": "YOU DO IT ALONE — after difficult information, stop talking, acknowledge briefly if needed, and let the parent speak first.\n\nPASS TEST — You did not fill it\n\nEVIDENCE TO FILE — reflective note. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the parent starts to cry and you begin describing the reading programme, and they hear nothing more that day.",
"s5": "YOU CAN TEACH IT — you can explain why silence helps, what a brief acknowledgement sounds like, and how to manage your own discomfort in the pause.\n\nWHEN IT GOES WRONG — you can say what to do when a parent is too upset to continue: offer to stop, agree a second meeting, make sure they are safe to leave, and send the written summary later.",
"error": "Filling the silence after difficult news with more information.",
"feeds": "→ Feeds into 'Answer the question actually asked' and into supervision on the emotional impact of the work.",
"evidence": "Reflective note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Answer the question actually asked"): {
"why": "Parents often ask a hard question — 'will he ever read?', 'did I cause this?', 'will she go to a mainstream secondary?' — and the easy move is to answer an adjacent, safer one. CORU SoP 2.11 is the standard mapped here. Answering a different question tells the parent the real one cannot be spoken, and they carry it home alone. You may not know the answer, but you can still answer the question.",
"s1": "WATCH FOR — the questions parents ask in your supervisor's sessions, and whether the answer given addresses that exact question or a related one.\n\nWRITE DOWN — each hard question (anonymised) and the first sentence of the answer.\n\nASK AFTERWARDS — 'when a parent asks if it's their fault, what do you actually say?'",
"s2": "YOU TAKE — anticipating the three hardest questions a parent might ask in a supervised case and drafting honest answers.\n\nTHEY HOLD — answering those questions in the session on your early cases.\n\nWHY THAT SPLIT — preparing answers is safe and useful. Answering a parent's fear in the moment, with no time to think, is where you need to have seen it done.",
"s3": "YOU RUN IT — take the question-and-answer part of the session yourself, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — sliding from 'will he ever read?' to a description of the reading programme, or from 'is it my fault?' to general information about causes.\n\nSTEPPING IN LOOKS LIKE — 'I think what mum is asking is whether she did something to cause this — is that right?'",
"s4": "YOU DO IT ALONE — when a parent asks a question, check you have understood it, answer that question, and say so if you cannot.\n\nPASS TEST — Not the easier adjacent one\n\nEVIDENCE TO FILE — reflective note. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the parent asks the same question three times in different words, and leaves without an answer.",
"s5": "YOU CAN TEACH IT — you can explain why we drift to adjacent questions, how to check the question before answering ('is what you're asking…?'), and how to answer honestly when the true answer is 'I don't know'.\n\nWHEN IT GOES WRONG — you can say what to do when you realise afterwards you answered the wrong question: contact the parent and say 'I don't think I answered what you asked me — can I try now?'",
"error": "Answering a safer related question instead of the one the parent asked.",
"feeds": "→ Feeds into 'Say what you do not know'.",
"evidence": "Reflective note · Appendix 5 · Log sheet tagged 3. Intervention"},

(M2, "Say what you do not know"): {
"why": "Parents ask about prognosis, cause and the future, and the honest answer is often uncertain. PSI Code 4.1.3 is the clause mapped here — read it for its exact wording. Claiming certainty you do not have leaves the family planning around a guess, and damages trust when it turns out wrong. Saying 'I don't know, and here is how we will find out' is a professional answer, not a failure.",
"s1": "WATCH FOR — how your supervisor words uncertainty: what they say they do not know, and what they add to it (what would help find out, when it will be clearer).\n\nWRITE DOWN — the phrases they use ('we can't tell yet', 'the research doesn't give a clear answer for a child like her').\n\nASK AFTERWARDS — 'how do you say you don't know without the parent losing confidence in the assessment?'",
"s2": "YOU TAKE — listing, before the session, what the assessment cannot answer (prognosis, cause, whether a diagnosis would be made by another service) and drafting how to say each.\n\nTHEY HOLD — questions about other services' decisions (CDNT, CAMHS, NCSE) where a wrong answer from you would mislead.\n\nWHY THAT SPLIT — knowing the limits of your assessment is your job. Other services' thresholds and waiting times change, and your supervisor is more likely to be current on them.",
"s3": "YOU RUN IT — answer parent questions yourself, naming uncertainty where it exists and saying how it could be reduced.\n\nWHAT THEY ARE WATCHING FOR — guessing to fill the gap (for example about CDNT waiting times or whether a diagnosis would follow), and over-hedging answers you do know.\n\nSTEPPING IN LOOKS LIKE — 'that's a fair question, and we honestly don't know yet — what would help us know is…'",
"s4": "YOU DO IT ALONE — say plainly when you do not know, separate it from what you do know, and say what would reduce the uncertainty.\n\nPASS TEST — Uncertainty admitted\n\nEVIDENCE TO FILE — reflective note, and the limitations section of the report. Log against 3. Intervention and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — you tell a parent 'she'll catch up by secondary school' and she doesn't, and the parent later quotes you to the school.",
"s5": "YOU CAN TEACH IT — you can explain the difference between uncertainty and incompetence, how to express uncertainty with a plan attached, and which questions EPs are and are not in a position to answer.\n\nWHEN IT GOES WRONG — you can say what to do when you gave an answer you should not have: correct it in writing, tell your supervisor, and record it.",
"error": "Guessing at an answer rather than saying you do not know.",
"feeds": "→ Feeds into Ethical Practice — working within competence — and 'State what you did not assess and what that limits'.",
"evidence": "Reflective note · report limitations · Appendix 5 · Log sheet tagged 3. Intervention and 6. Ethical Practice"},

})

# ---------------------------------------------------------------------------
# M3 · Observe and then contribute to teacher consultation
# ---------------------------------------------------------------------------

MICRO.update({

(M3, "Use a named consultation model"): {
"why": "Without a model, consultation becomes a chat that ends in advice. A named model gives you a sequence to return to when the conversation drifts. Problem-solving consultation (Bergan & Kratochwill, 1990, Behavioral Consultation and Therapy), consultation as a framework for EP practice (Wagner, 2000, Educational Psychology in Practice) and solution-focused approaches (Rhodes & Ajmal, 1995, Solution Focused Thinking in Schools) are three. CORU SoP 5.38 is the standard mapped here. The Reference sheet's advice: pick one and use it repeatedly.",
"s1": "WATCH FOR — which model your supervisor is using, even if they do not name it: do they move through problem identification, analysis, plan, evaluation; or start from exceptions and preferred futures?\n\nWRITE DOWN — the stages you can see in the meeting, and the question that moved it from one stage to the next.\n\nASK AFTERWARDS — 'which model were you working from there, and where did you depart from it?'",
"s2": "YOU TAKE — choosing one model, reading its core source, and preparing a one-page prompt sheet of its stages and key questions before a supervised consultation.\n\nTHEY HOLD — leading the consultation, while you track the stages on your sheet.\n\nWHY THAT SPLIT — learning a model's structure is reading and preparation. Following it in a live meeting while also listening to a teacher is the harder skill, best learned by tracking someone else first.",
"s3": "YOU RUN IT — lead a consultation using your chosen model, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — skipping from problem statement straight to plan, which is where problem-solving consultation most often fails (Reference sheet; see Gutkin & Curtis, 2009, for the evidence).\n\nSTEPPING IN LOOKS LIKE — 'before we talk about what to do — can we get a clearer picture of when this happens?'",
"s4": "YOU DO IT ALONE — use one named model consistently in your consultations and be able to say which stage each part of the meeting was.\n\nPASS TEST — You can say which one\n\nEVIDENCE TO FILE — consultation record with the model named, anonymised. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — asked in supervision which model you used, you say 'just a general chat, really', and cannot describe how the meeting was structured.",
"s5": "YOU CAN TEACH IT — you can explain the stages of your chosen model, cite its source, say why problem identification carries so much weight, and compare it briefly with one other model.\n\nWHEN IT GOES WRONG — you can say what to do when the model does not fit a meeting (for example a crisis): name the departure in your record, deal with the immediate need, and return to the model at the next meeting.",
"error": "Running consultations as unstructured conversations with no model you can name.",
"feeds": "→ Feeds into 'Contract at the start', 'Ask questions that open rather than close', and Systemic Change.",
"evidence": "Consultation record · Appendix 5 · Log sheet tagged 3. Intervention"},

(M3, "Contract at the start"): {
"why": "A teacher who expected an assessment and gets a conversation, or who expected advice and gets questions, will leave frustrated. Contracting — agreeing at the start what the meeting is for, how long it will take and what will come out of it — is part of the consultation process described by Wagner (2000). CORU SoP 5.38 is the standard mapped here. Without it, the teacher's unspoken expectation, usually 'take the child and fix him', governs the meeting.",
"s1": "WATCH FOR — how your supervisor opens a consultation: whether they say what the meeting is for, how long it will take, what the teacher will leave with, and what happens with the notes.\n\nWRITE DOWN — the opening words, and any moment later where the contract was referred back to ('we said we'd focus on the mornings').\n\nASK AFTERWARDS — 'what do you do when the teacher clearly expected you to take the child out and assess him?'",
"s2": "YOU TAKE — writing a short contracting script for your service: purpose, time, roles, what is recorded and who sees it, what happens next.\n\nTHEY HOLD — the opening itself, especially with teachers or principals who have strong expectations of what an EP visit is.\n\nWHY THAT SPLIT — scripting the contract is preparation. Holding it with a principal who wants something else is authority you are still building.",
"s3": "YOU RUN IT — open a supervised consultation with your contract, and check the teacher agrees before moving on.\n\nWHAT THEY ARE WATCHING FOR — a contract rushed through as a formality, and not noticing when the teacher's expectation is different.\n\nSTEPPING IN LOOKS LIKE — 'can I just check — what were you hoping to get from today?'",
"s4": "YOU DO IT ALONE — begin each consultation by agreeing its purpose, time, roles and output, and check the teacher's own expectation.\n\nPASS TEST — Both parties know what this meeting is for\n\nEVIDENCE TO FILE — consultation record showing the agreed purpose. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — forty minutes in, the teacher asks 'so when will you be seeing him?', and it is clear she thought this meeting was the preamble to an assessment.",
"s5": "YOU CAN TEACH IT — you can explain what contracting covers, why it matters in a service where schools expect assessment, and how to renegotiate when the teacher wants something else.\n\nWHEN IT GOES WRONG — you can say what to do when the contract breaks down mid-meeting: stop, name it, re-agree the purpose, and if necessary agree a different meeting for the other need.",
"error": "Starting a consultation without agreeing what it is for.",
"feeds": "→ Feeds into 'Ask questions that open rather than close' and 'Agree actions with a review point'.",
"evidence": "Consultation record · Appendix 5 · Log sheet tagged 3. Intervention"},

(M3, "Ask questions that open rather than close"): {
"why": "The presenting concern is rarely the workable problem, and questions — not suggestions — get you from 'he's disruptive' to a defined, observable pattern (Reference sheet, 'Problem identification'). 'Have you tried…?' reads as criticism however it is meant. CORU SoP 5.38 and 5.40 are the standards mapped here. A teacher who generates the solution owns it and is more likely to implement it; one handed a solution is less so (Reference sheet, 'Staying out of the expert role').",
"s1": "WATCH FOR — the questions your supervisor asks, and how many are open (what, when, how) versus closed or leading ('have you tried a sticker chart?').\n\nWRITE DOWN — the questions that visibly shifted the teacher's thinking — often 'when does it not happen?' or 'what do you think is going on?'\n\nASK AFTERWARDS — 'how do you stop yourself suggesting something when you can see the answer?'",
"s2": "YOU TAKE — preparing a bank of opening questions for each stage of your model, and in the meeting asking two or three of them at points your supervisor signals.\n\nTHEY HOLD — the flow of the consultation and the decision on when to move to planning.\n\nWHY THAT SPLIT — asking a prepared question is a safe contribution. Knowing when enough has been understood to move on is a judgement that takes many consultations.",
"s3": "YOU RUN IT — lead the problem-identification and analysis stages with open questions, holding back your own suggestions.\n\nWHAT THEY ARE WATCHING FOR — 'have you tried…?', questions that are suggestions in disguise, and moving to solutions before the problem is defined.\n\nSTEPPING IN LOOKS LIKE — 'what do you think is going on for him?' — the question the teacher is rarely asked.",
"s4": "YOU DO IT ALONE — run a consultation in which your contribution is mainly questions, and the plan comes from the teacher.\n\nPASS TEST — The teacher generated the solution\n\nEVIDENCE TO FILE — consultation record noting who proposed each action. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — you leave with a list of your own strategies, the teacher agreed politely, and at review none has been tried.",
"s5": "YOU CAN TEACH IT — you can explain why open questions build ownership, give examples at each stage of a problem-solving model, and say why 'have you tried' backfires.\n\nWHEN IT GOES WRONG — you can say what to do when the teacher insists on being told what to do: offer two or three options, ask which fits the class, and let them choose and adapt.",
"error": "Offering solutions before the problem is defined, or asking 'have you tried…?'",
"feeds": "→ Feeds into 'Identify who holds the problem and who holds the power' and 'Build capacity rather than doing it for them'.",
"evidence": "Consultation record · Appendix 5 · Log sheet tagged 3. Intervention"},

(M3, "Identify who holds the problem and who holds the power"): {
"why": "The person most worried about a child is not always the person who can change things. A class teacher may carry the problem while the principal controls timetabling and SET deployment; a parent may carry it while the school holds the resource. CORU SoP 5.22 is the standard mapped here. Consulting with someone who has no power over the change produces plans nobody can implement. Schein's work on process consultation (Schein, 1999, Process Consultation Revisited) is one source on reading these relationships.",
"s1": "WATCH FOR — who is in the consultation, who is not, who speaks most, and who defers to whom. Notice whether the plan depends on someone who is not present.\n\nWRITE DOWN — for one consultation, who owns the concern, who can change timetabling, staffing or the classroom, and who would have to agree.\n\nASK AFTERWARDS — 'how do you decide whether the principal needs to be in the room?'",
"s2": "YOU TAKE — mapping, before the meeting, who holds the concern and who holds each resource the plan might need (class teacher, SET, principal, SNA, parent).\n\nTHEY HOLD — the decision to widen the meeting or approach the principal separately.\n\nWHY THAT SPLIT — mapping is analysis you can do from the file. Approaching a principal about who should attend is a relationship move your supervisor makes on behalf of the service.",
"s3": "YOU RUN IT — lead a consultation and, before agreeing actions, check whether those present can carry them out or need someone else's agreement.\n\nWHAT THEY ARE WATCHING FOR — a plan that needs the principal's agreement, agreed with a class teacher who cannot give it.\n\nSTEPPING IN LOOKS LIKE — 'is this something you can decide, or does it need to go to the principal first?'",
"s4": "YOU DO IT ALONE — before closing a consultation, identify who holds the problem and who holds the power to act, and address the gap.\n\nPASS TEST — You noticed the difference\n\nEVIDENCE TO FILE — consultation record noting who needs to agree, anonymised. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the class teacher agrees to extra SET input, the principal knows nothing about it, and nothing changes.",
"s5": "YOU CAN TEACH IT — you can explain the difference between holding a problem and holding the power to change it, and how to map this in any school.\n\nWHEN IT GOES WRONG — you can say what to do when the person with power will not engage: record it, discuss it with your supervisor, and plan within what those present can control.",
"error": "Agreeing a plan with someone who has no power to carry it out.",
"feeds": "→ Feeds into 'Agree actions with a review point', and into Systemic Change.",
"evidence": "Consultation record · Appendix 5 · Log sheet tagged 3. Intervention"},

(M3, "Agree actions with a review point"): {
"why": "Consultations without a written record and a review date evaporate, and the teacher concludes psychology is talk (Reference sheet, 'Closing the loop'). CORU SoP 5.37 is the standard mapped here. Your placement review named record-keeping and consultation write-up as a development area, and this is the habit that addresses it. Sending the record within 24 hours, as the Reference sheet advises, makes the actions visible to everyone.",
"s1": "WATCH FOR — how your supervisor closes a consultation: summarising actions, naming who does each, setting a review date, and saying when the record will be sent.\n\nWRITE DOWN — the actions as agreed, the review date, and how soon afterwards the record went out.\n\nASK AFTERWARDS — 'what do you actually send the teacher, and how long does it take you?'",
"s2": "YOU TAKE — writing the consultation record for your supervisor's consultation and sending it to them within 24 hours for checking.\n\nTHEY HOLD — the closing summary in the meeting and approval of the record before it goes to the school.\n\nWHY THAT SPLIT — the write-up is the named development area and should be yours at once. Your supervisor approves it so you learn what a school needs to see.",
"s3": "YOU RUN IT — close a consultation yourself: summarise actions, roles and a review date aloud, then send the record within 24 hours.\n\nWHAT THEY ARE WATCHING FOR — actions like 'monitor behaviour' with no specifics, and a record that arrives a week later.\n\nSTEPPING IN LOOKS LIKE — 'let's read those back — who, what, by when, and when do we meet again?'",
"s4": "YOU DO IT ALONE — close every consultation with specific actions, named roles and a dated review, and send the record within 24 hours.\n\nPASS TEST — Specific and dated\n\nEVIDENCE TO FILE — anonymised consultation record, with the date sent. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at the review, nobody can remember what was agreed and you have no record to check.",
"s5": "YOU CAN TEACH IT — you can explain what a consultation record needs to contain, why it goes out within a day, and how the review date connects to the Student Support File cycle.\n\nWHEN IT GOES WRONG — you can say what to do when a record has not been sent: send it now, apologise briefly, and confirm the review date is still right.",
"error": "No written record and no review date after the consultation.",
"feeds": "→ Feeds into 'Set a review date' in recommendations, and into 'Build capacity rather than doing it for them'.",
"evidence": "Consultation record · Appendix 5 · Log sheet tagged 3. Intervention"},

(M3, "Build capacity rather than doing it for them"): {
"why": "One psychologist cannot see every child, and consultation is how the work reaches more of them (Reference sheet; Gutkin & Curtis, 2009). CORU SoP 5.40 frames this as building capacity. When you solve the problem for the teacher, the next similar child comes back to you. When the teacher understands the process, they can use it again. The pull toward being the expert is strongest when you are a trainee who wants to be useful.",
"s1": "WATCH FOR — moments where your supervisor holds back an answer and lets the teacher reach it, and whether they name the process ('what we did there was look for when it doesn't happen').\n\nWRITE DOWN — anything your supervisor did to make the process transferable — a framework handed over, a summary of the steps, a question the teacher can reuse.\n\nASK AFTERWARDS — 'how do you know a teacher could do this without you next time?'",
"s2": "YOU TAKE — preparing a short, practical resource for the teacher based on the consultation process (for example the key questions from problem identification), checked by your supervisor.\n\nTHEY HOLD — judgement on how much process to make explicit with this teacher, since some welcome it and some find it patronising.\n\nWHY THAT SPLIT — preparing resources is safe and useful. Reading a teacher's appetite for learning the process needs experience of many teachers.",
"s3": "YOU RUN IT — lead a consultation and, at the end, name the process you used and ask the teacher how they might use it with another child.\n\nWHAT THEY ARE WATCHING FOR — you doing the thinking for the teacher, or delivering a lecture on the model the teacher did not ask for.\n\nSTEPPING IN LOOKS LIKE — 'if another child in your class started doing this next month, what would you do first?'",
"s4": "YOU DO IT ALONE — in each consultation, leave the teacher with a process they can use again, not only a plan for this child.\n\nPASS TEST — They could do it again without you\n\nEVIDENCE TO FILE — consultation record and any resource left with the teacher. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the same teacher refers a second child with the same pattern a term later, without having tried anything from the first consultation.",
"s5": "YOU CAN TEACH IT — you can explain the difference between solving a problem and building capacity, why it matters for a service with limited time, and how to make a process visible without lecturing.\n\nWHEN IT GOES WRONG — you can say what to do when a school relies on you to solve every problem: raise it with your supervisor, and plan a staff session or a series of consultations that hand the process over.",
"error": "Solving the teacher's problem for them, so they cannot solve the next one.",
"feeds": "→ Feeds into Systemic Change, and into 'Use a named consultation model' with the next teacher.",
"evidence": "Consultation record · Appendix 5 · Log sheet tagged 3. Intervention"},

})
