MICRO = {

# ---------------------------------------------------------------------------
# Educational interventions in literacy
# ---------------------------------------------------------------------------

("Educational interventions in literacy","Know the programmes available locally"): {
"why":   "CORU SoP 5.33 is the standard mapped here. A recommendation the school cannot deliver is wasted, and one that ignores what the school already holds asks it to buy or train for something new when it may not need to. The Reference sheet names UFLI and the NEPS literacy materials as what Irish schools are likely to have, but 'likely' is not 'does' — you have to ask each school. The failure is recommending a brand from memory, or recommending only what the school owns without checking it matches the need.",
"s1":    "WATCH FOR — how your supervisor finds out, early in a school visit, which literacy interventions the school actually runs: which programmes or approaches, for which class groups, who is trained, and how the special education teaching (SET) timetable is used. Notice whether they ask to see the materials rather than accepting a name.\n\nWRITE DOWN — a school-by-school list with no pupil names: the programme or approach, the reading component it targets (phonics, fluency, vocabulary, comprehension), who delivers it, and the usual group size.\n\nASK AFTERWARDS — 'when a school tells you it runs a programme, how do you find out whether it is actually being run as designed?'",
"s2":    "YOU TAKE — building the inventory for each of your Cavan schools in the first weeks from 05/10/2026: ask the principal or SET coordinator what literacy interventions they hold and sort each one against the component it addresses, using the National Reading Panel (2000) headings.\n\nTHEY HOLD — the judgement on whether a school's version is close enough to the evidence-based design to count, and any conversation where a school relies on something the evidence does not support (coloured overlays, learning-styles matching).\n\nWHY THAT SPLIT — listing is fact-gathering you can do from week one. Judging fidelity and redirecting a school away from a favoured approach needs relationship and tact that your supervisor already has with that school.",
"s3":    "YOU RUN IT — at a school planning meeting, ask the school what it holds for literacy and map it aloud against the components, with your supervisor present. Name any gap plainly: 'you have strong phonics provision in the junior classes — what do you use for older pupils who decode accurately but read very slowly?'\n\nWHAT THEY ARE WATCHING FOR — accepting a programme name as proof of what happens in the room, and missing the gap because you only asked about phonics.\n\nSTEPPING IN LOOKS LIKE — your supervisor adding: 'could we see the materials, and how many sessions a week the group actually gets at the moment?'",
"s4":    "YOU DO IT ALONE — for each school on your caseload, hold a current list of the literacy interventions it runs, the component each targets, who is trained to deliver it, and where the gaps are — and use that list every time you write a recommendation.\n\nPASS TEST — You can name what these schools hold\n\nEVIDENCE TO FILE — the school inventory (no pupil identifiers) and one case note showing a recommendation matched to what that school holds. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a report recommending a programme the school has never heard of, with no trained staff and no budget, so the recommendation sits in the file and nothing changes for the child.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to build a school literacy inventory in one visit, sort it by component, and spot the gap, and explain why knowing a programme's name is not the same as knowing what it teaches — read each programme's own manual and evidence claims rather than its marketing.\n\nWHEN IT GOES WRONG — you can say what to do when the school holds nothing for the component the child needs: say so plainly, specify the approach rather than a brand (for example, repeated reading with feedback for fluency, per the Reference sheet), and raise the gap with your supervisor as a possible systemic issue for that school.",
"error": "Recommending a programme by brand name without checking whether the school holds it, has trained staff, or runs it as designed.",
"feeds": "→ Feeds into 'Match the programme to the phonological profile' and 'Identify who delivers and whether they are trained'.",
"evidence":"School literacy inventory (no identifiers) · case note · Appendix 5 · Log sheet tagged 3. Intervention"},

("Educational interventions in literacy","Match the programme to the phonological profile"): {
"why":   "CORU SoP 5.34 requires intervention designed on the basis of the data, evidence-informed judgement and formulation. Reading is made up of separable components — phonological awareness, phonics and decoding, fluency, vocabulary and comprehension (National Reading Panel, 2000) — and a child can fail at one with the others intact. Phonics for a child who decodes accurately but slowly will not touch the fluency problem (Reference sheet, literacy). Match wrongly and the child spends a term in the wrong group, and the school concludes that 'intervention doesn't work for him'.",
"s1":    "WATCH FOR — how your supervisor moves from scores to a component: which results they put side by side (phonological awareness, non-word reading, single-word reading accuracy, reading rate, reading comprehension, oral vocabulary) and how the pattern points to one component rather than another.\n\nWRITE DOWN — the pattern and the component it pointed to, for example: 'non-word reading and phoneme tasks low → decoding'; 'accuracy secure, rate slow → fluency'; 'decoding and fluency secure, comprehension and vocabulary low → language'.\n\nASK AFTERWARDS — 'when the profile points to two components at once, which do you target first, and why?'",
"s2":    "YOU TAKE — drafting the component analysis from the assessment data: a simple table listing each component, the evidence for it from your data, and whether it looks intact or impaired — done before any programme is named.\n\nTHEY HOLD — the final choice of intervention and how it is framed for the school and family.\n\nWHY THAT SPLIT — the analysis is checkable line by line against the data. Choosing between competing priorities when two components are weak draws on the formulation and on experience; Snowling and Hulme (2011) is the reading for why the order and the oral-language foundations matter.",
"s3":    "YOU RUN IT — write the intervention section yourself: name the impaired component, then the approach with evidence for it (systematic synthetic phonics for decoding; repeated reading with feedback or paired reading for fluency; deep direct teaching of a small number of words for vocabulary; explicit, modelled strategy instruction for comprehension — Reference sheet), and only then what the school holds that delivers it.\n\nWHAT THEY ARE WATCHING FOR — a programme named first and the component fitted to it afterwards, and a comprehension difficulty treated as a phonics problem.\n\nSTEPPING IN LOOKS LIKE — 'which score tells you this is decoding and not fluency?'",
"s4":    "YOU DO IT ALONE — every literacy recommendation names the impaired component, points to the assessment finding it rests on, and names an approach with evidence for that component, before naming anything the school holds.\n\nPASS TEST — The recommendation follows the assessment\n\nEVIDENCE TO FILE — the report's intervention section with the finding-to-component-to-approach link visible, and the supervision note where it was checked. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — 'daily phonics group recommended' for a Fifth Class pupil whose decoding is secure and whose real difficulty is vocabulary and comprehension, so a term is spent practising what she can already do.",
"s5":    "YOU CAN TEACH IT — you can explain the component model, how to read an assessment profile against it, and what the evidence supports for each component, citing the National Reading Panel (2000), Ehri (2005) on how children learn to read words, and Snowling and Hulme (2011) on evidence-based interventions.\n\nWHEN IT GOES WRONG — you can say what to do when a child has been placed in the wrong group: go back to the data, tell the school without blame what the profile actually shows, re-specify the intervention, and use the progress data already gathered to explain why the change is needed.",
"error": "Naming a programme before identifying which reading component is impaired.",
"feeds": "→ Feeds into 'Specify how often, how long, over what period' and into Formulation — linking assessment findings to hypotheses and plans.",
"evidence":"Report — intervention section · supervision note · Log sheet tagged 3. Intervention"},

("Educational interventions in literacy","Specify how often, how long, over what period"): {
"why":   "The Reference sheet names intensity as the variable schools most often get wrong and psychologists most often leave unspecified. A usable recommendation has five parts: what, who delivers it, how often and for how long per session, over what period, and what will be measured — 'literacy support' is a wish, not a recommendation. CORU SoP 5.34 and PSI Code 2.3.2 are the standards mapped here. Leave intensity out and the school may deliver fifteen minutes a week and conclude, wrongly, that the intervention does not work.",
"s1":    "WATCH FOR — how your supervisor words intensity in a report and in a school meeting: sessions per week, minutes per session, group size, number of weeks, and whether they check that it fits the SET timetable before the meeting ends.\n\nWRITE DOWN — the exact sentence they use and the numbers in it, and where each number came from (the programme's manual, the research, or what the school could offer).\n\nASK AFTERWARDS — 'when the programme's recommended dose and what the school can fit do not match, how do you decide what to write?'",
"s2":    "YOU TAKE — drafting the five-part specification for a case, and checking the programme's own manual or evidence summary for its intended dose. Read the manual itself; do not quote a dosage from memory or from another trainee's report.\n\nTHEY HOLD — negotiating with the principal or SET coordinator when the school's special education teaching allocation cannot meet the intensity you specified.\n\nWHY THAT SPLIT — drafting is technical and checkable. Negotiating how a school spends its DE special education teaching allocation involves the school's wider caseload and a relationship your supervisor holds.",
"s3":    "YOU RUN IT — present the specification at the school meeting and agree it with the SET, supervisor present. If the school can offer less than specified, say plainly what the reduced version can and cannot be expected to do, and adjust the period or review date accordingly.\n\nWHAT THEY ARE WATCHING FOR — letting the numbers dissolve into 'as often as possible', or agreeing to a dose you believe is too thin without saying so.\n\nSTEPPING IN LOOKS LIKE — 'if it is twice a week rather than daily, do we extend it to the Easter break, and when do we look at it again?'",
"s4":    "YOU DO IT ALONE — every intervention recommendation states sessions per week, minutes per session, group size, number of weeks, and a start date and review date written DD/MM/YYYY, and the school has agreed it can deliver that.\n\nPASS TEST — Frequency and duration stated\n\nEVIDENCE TO FILE — the report recommendation and the school's support plan showing the same numbers. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a review meeting in March where nobody can say how many sessions the child actually received, so no one can tell whether the intervention failed or was never delivered at strength.",
"s5":    "YOU CAN TEACH IT — you can explain why intensity is part of the intervention and not an administrative detail, where to find a programme's intended dose, and how to write the five-part specification, using the Reference sheet's worked example ('daily 20-minute structured phonics delivered by the SET in a group of no more than three, for one term...').\n\nWHEN IT GOES WRONG — you can say what to do when the school delivered far less than agreed: before judging the intervention, establish and record the dose actually received, discuss the barriers without blame, and re-plan on that basis rather than switching programme.",
"error": "Recommending an intervention with no frequency, session length or duration, so the dose is whatever the timetable leaves over.",
"feeds": "→ Feeds into 'Identify who delivers and whether they are trained' and 'Set a review point and a measure'.",
"evidence":"Report recommendation · school support plan · Log sheet tagged 3. Intervention"},

("Educational interventions in literacy","Identify who delivers and whether they are trained"): {
"why":   "An intervention is only as good as its delivery, and 'to be delivered in school' assigns it to nobody. CORU SoP 5.40 asks you to build capacity among those responsible for delivery, which starts with knowing who they are and what training they have. Irish schools deploy class teachers and special education teachers differently, and special needs assistant posts are allocated for care needs rather than teaching — check the current DE circular before assigning any task. Get this wrong and three staff each assume someone else is doing it.",
"s1":    "WATCH FOR — how your supervisor establishes who will deliver the intervention, and whether they ask about training as well as role. Notice whether the plan names a role (class teacher, SET) rather than 'the school'.\n\nWRITE DOWN — the roles in that school that deliver literacy support, what training each has had in which approach (roles only, no staff names in your own log), and how your supervisor recorded the agreement.\n\nASK AFTERWARDS — 'what do you do when the only person available to deliver it has not been trained in it?'",
"s2":    "YOU TAKE — finding out who is trained: ask the SET coordinator which staff have had training in which approach, roughly when, and whether they have delivered it since. Record it against your school inventory.\n\nTHEY HOLD — any recommendation about staff training and anything touching staff deployment, which is the principal's decision.\n\nWHY THAT SPLIT — gathering facts is safe for a trainee. Deployment is a management matter, and a trainee pressing on it can feel to a school like an audit of its staff, which damages the working relationship your supervisor has built.",
"s3":    "YOU RUN IT — write the delivery section yourself: the named role, their training status, and what support they will have (a modelling session, a check-in after two weeks, who to ask). Agree it with the SET at the meeting, supervisor present.\n\nWHAT THEY ARE WATCHING FOR — 'the school' written as deliverer; a teaching task assigned to an SNA without checking the SNA role; assuming that owning a programme means someone is trained in it.\n\nSTEPPING IN LOOKS LIKE — 'by role, who is in the room with this child on Tuesday at ten, and have they done this before?'",
"s4":    "YOU DO IT ALONE — every recommendation names the delivering role, states whether that person is trained or how the gap will be met, and says who they can go to with questions once you have left.\n\nPASS TEST — Delivery assigned to a named role\n\nEVIDENCE TO FILE — the support plan with the delivering role, and the note of the meeting where it was agreed. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a recommendation that says 'in school', the class teacher assumes the SET has it, the SET assumes the class teacher has it, and at review the child has had nothing.",
"s5":    "YOU CAN TEACH IT — you can explain why the deliverer and their training are part of the specification, how to ask about training without it sounding like an inspection, and how CORU SoP 5.40 frames building capacity rather than simply assigning tasks.\n\nWHEN IT GOES WRONG — you can say what to do when the deliverer leaves or goes on leave mid-term: agree a named cover role with the school, record the gap in delivery honestly, and move the review date so the outcome data is not read as the intervention failing.",
"error": "Writing 'to be delivered in school' with no named role and no check that the person is trained.",
"feeds": "→ Feeds into 'Leave the teacher able to run it' and into Working with Others — consultation with school staff.",
"evidence":"Support plan — delivery section · meeting note · Log sheet tagged 3. Intervention"},

("Educational interventions in literacy","Take a baseline before it starts"): {
"why":   "Without a baseline there is no way to attribute change (Reference sheet, literacy), and CORU SoP 3.8 requires you to evaluate what you do. The measure must be sensitive to short-term change — curriculum-based measurement, words correct per minute, non-word reading — not the school's annual standardised test, which will not move in a term. Deno (1985) is the classic source on curriculum-based measurement. Skip the baseline and the review will rest on 'she seems more confident', which cannot tell anyone whether to continue.",
"s1":    "WATCH FOR — which measure your supervisor chooses for which reading component, and how carefully they administer it: timing, passage level, instructions, and the conditions they note so it can be repeated identically later.\n\nWRITE DOWN — the measure, the component it tracks, and the conditions (time of day, who gave it, which materials, any interruptions) so that someone else could repeat it exactly.\n\nASK AFTERWARDS — 'how many baseline points do you like to take, and what do you do when the child's scores bounce around from day to day?'",
"s2":    "YOU TAKE — administering the baseline probe (for example a one-minute oral reading fluency passage or a non-word reading list) under your supervisor's guidance, and recording the conditions.\n\nTHEY HOLD — the choice of measure where a tool is restricted, and the interpretation of the baseline.\n\nWHY THAT SPLIT — administering a probe is procedural and easy to check. Choosing a measure and interpreting it depends on knowing its sensitivity and limits, which you read in the measure's own manual or source rather than taking on trust.",
"s3":    "YOU RUN IT — choose a measure matched to the targeted component and take the baseline yourself before session one, with your supervisor checking your choice. Take more than one data point if you can, and record the dates DD/MM/YYYY.\n\nWHAT THEY ARE WATCHING FOR — the school's annual standardised score used as the baseline; a baseline taken after the intervention has already begun; a measure that does not match the component being taught.\n\nSTEPPING IN LOOKS LIKE — 'if this intervention works, will this number move in eight weeks? If not, pick another.'",
"s4":    "YOU DO IT ALONE — before the first session, there is a dated baseline on a measure sensitive to the targeted component, with the conditions recorded well enough that someone else could repeat it.\n\nPASS TEST — There is a pre-measure\n\nEVIDENCE TO FILE — the baseline record attached to the support plan. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at review, the only numbers are this year's and last year's standardised test results; the question 'did it work?' cannot be answered, and the school keeps the child in the group out of habit.",
"s5":    "YOU CAN TEACH IT — you can explain why a baseline matters, why short-term-sensitive measures beat annual tests for this purpose, and how to record conditions so the measure is repeatable, pointing a peer to Deno (1985) and the Reference sheet's section on measuring it.\n\nWHEN IT GOES WRONG — you can say what to do when an intervention has started without a baseline: take one now, label it clearly as taken after the start, and be honest in the review about what that does and does not allow you to conclude.",
"error": "Starting an intervention with no pre-measure, or using the annual standardised test as the only measure.",
"feeds": "→ Feeds into 'Set a review point and a measure' and into Research — practice-based evaluation.",
"evidence":"Baseline record · support plan · Log sheet tagged 3. Intervention"},

("Educational interventions in literacy","Set a review point and a measure"): {
"why":   "CORU SoP 3.8 and 5.37 require you to evaluate and revise, and you cannot revise what you did not measure (Reference sheet). PSI Code 3.1.2 is also mapped here. The review date and measure belong in the report, written so that the school can carry them out without you — a trainee leaves Cavan on 18/12/2026, and most reviews will fall after that. A review that only you could run is a review that will not happen.",
"s1":    "WATCH FOR — how your supervisor writes the review: the date, the measure, who takes it, what will count as enough progress, and what decisions the review will lead to (continue, intensify, change approach, stop).\n\nWRITE DOWN — their wording for the review section and the decision options, and how they decide in advance what counts as progress.\n\nASK AFTERWARDS — 'how do you decide beforehand what counts as enough progress, so the review is not just a feeling in the room?'",
"s2":    "YOU TAKE — drafting the review section: date, measure, who will administer it, and the decision options.\n\nTHEY HOLD — the threshold for 'enough progress' and how that is explained to the school and the family.\n\nWHY THAT SPLIT — a threshold needs judgement about what change is realistic for this child. Check the measure's own guidance on expected growth rather than inventing a rate; your supervisor knows what the service uses and what has been defensible in past reviews.",
"s3":    "YOU RUN IT — write the review section and present it at the meeting, then hand the SET the probe materials and a one-page instruction sheet so they can take the measure themselves.\n\nWHAT THEY ARE WATCHING FOR — a measure only you can administer; a review date after you leave with nobody named to hold it; 'progress will be reviewed' with no date at all.\n\nSTEPPING IN LOOKS LIKE — 'if you were off sick on the review date, could the SET do this from what you have written? Show me the instruction sheet.'",
"s4":    "YOU DO IT ALONE — every plan has a dated review, a named measure, the role who takes it, and the decisions it will inform, written so that the school can run it without you.\n\nPASS TEST — Measurable by someone other than you\n\nEVIDENCE TO FILE — the plan with its review section, and the instruction sheet you gave the SET. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — you leave Cavan on 18/12/2026, the review date passes in February, and nobody in the school knows what to measure, how, or what the numbers are meant to be compared against.",
"s5":    "YOU CAN TEACH IT — you can explain how to design a review a school can run alone: a repeatable measure, decision rules set in advance, and a named role holding the date.\n\nWHEN IT GOES WRONG — you can say what to do when the review shows no change: check first the dose actually received and whether it was delivered as designed, then whether the component was right, and only then change the approach — which is what Grade 5 in the Reference sheet asks you to be able to say.",
"error": "A review that depends on you being there, so it lapses when the placement ends.",
"feeds": "→ Feeds into 'Leave the teacher able to run it', into 'Specify what success would look like' for numeracy, and into Systemic Change.",
"evidence":"Support plan — review section · SET instruction sheet · Log sheet tagged 3. Intervention"},

# ---------------------------------------------------------------------------
# Educational interventions in numeracy
# ---------------------------------------------------------------------------

("Educational interventions in numeracy","Know concrete–pictorial–abstract sequencing"): {
"why":   "Concrete–pictorial–abstract sequencing, with the concrete stage not rushed, is one of the approaches the Reference sheet lists as evidence-supported for numeracy. Its roots are usually traced to Bruner's (1966) enactive, iconic and symbolic modes of representation. Most teachers know the phrase; the common problems are moving to numerals too early and using manipulatives as an activity rather than to show mathematical structure. CORU SoP 5.33 is mapped here. If you cannot explain it plainly, you cannot tell whether a classroom is doing it.",
"s1":    "WATCH FOR — how your supervisor or an experienced SET moves a child from objects (cubes, counters, ten-frames, base-ten blocks) to drawings (dots, bar models, number lines) to numerals, and what they check before moving on.\n\nWRITE DOWN — one worked example for one skill, for example subtraction as taking away counters → crossing out drawn dots → 7 − 3 = 4, and the question used at each step to check the link.\n\nASK AFTERWARDS — 'how do you tell whether a child needs to go back to the concrete stage, or is just using the cubes out of habit?'",
"s2":    "YOU TAKE — writing a one-page CPA explanation with a worked example for a specific skill on your caseload, and checking the wording with your supervisor before using it.\n\nTHEY HOLD — the conversation with a teacher whose classroom practice does not fit the approach.\n\nWHY THAT SPLIT — writing the explanation tests whether you actually understand it. Advising an experienced teacher on their own maths teaching needs a credibility that you build over the placement, and a clumsy first attempt can close the door.",
"s3":    "YOU RUN IT — explain CPA to a class teacher or SET in a consultation, linked to the child's target skill, with your supervisor present. Show the pictorial bridge, not only the two ends.\n\nWHAT THEY ARE WATCHING FOR — jargon; presenting manipulatives as the point rather than as a picture of structure; implying that the concrete stage is only for infant classes.\n\nSTEPPING IN LOOKS LIKE — 'could you show her what the pictorial step would look like for this child's sum, using the ten-frame she already has?'",
"s4":    "YOU DO IT ALONE — explain CPA to a teacher, briefly and without jargon, with one example tied to the child's actual target, and say what the teacher should see at each stage before moving on.\n\nPASS TEST — You can explain it to a teacher in two minutes\n\nEVIDENCE TO FILE — the consultation note and your one-page explanation. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the teacher leaves thinking the advice was 'use more cubes', and the child is still counting every cube from one in Fourth Class with no link to the written sum.",
"s5":    "YOU CAN TEACH IT — you can explain where CPA comes from (Bruner, 1966), why the concrete stage should not be rushed, and how representations carry structure, with one example for place value and one for fractions. Point a peer to the EEF guidance reports on improving mathematics listed in the Reference sheet and read their recommendations on manipulatives and representations directly.\n\nWHEN IT GOES WRONG — you can say what to do when a child is stuck at the concrete stage: check whether the pictorial bridge was skipped, and whether the real difficulty is conceptual (cardinality, part–whole) rather than representation.",
"error": "Recommending 'use concrete materials' without explaining the move through pictorial to abstract.",
"feeds": "→ Feeds into 'Distinguish fact retrieval from conceptual difficulty' and 'Specify what success would look like'.",
"evidence":"Consultation note · one-page CPA explanation · Log sheet tagged 3. Intervention"},

("Educational interventions in numeracy","Distinguish fact retrieval from conceptual difficulty"): {
"why":   "A child who has not secured cardinality cannot meaningfully do addition, and drilling addition facts will not help (Reference sheet, numeracy). A child who understands number relationships but cannot retrieve facts quickly needs something quite different. Gersten et al. (2009) and Butterworth, Varma and Laurillard (2011) are the Reference sheet's sources on this. CORU SoP 3.4 and 5.34 are mapped. Confuse the two and the child gets flashcard drill for a conceptual gap, or is re-taught concepts they already hold.",
"s1":    "WATCH FOR — how your supervisor probes strategy rather than accuracy: asking the child to show or explain how they got an answer; watching for counting all from one versus counting on; noticing derived facts ('6 + 7 is 6 + 6 and one more'); giving the same problem orally and in writing.\n\nWRITE DOWN — the strategies you saw, in the child's words, with rough time taken and the errors made.\n\nASK AFTERWARDS — 'what exactly did you see that made you think this was retrieval and not understanding?'",
"s2":    "YOU TAKE — the strategy interview part ('how did you work that out?') and recording what the child does, word for word where possible.\n\nTHEY HOLD — the interpretation, and the decision whether a standardised mathematics measure is needed and which one.\n\nWHY THAT SPLIT — careful observation is something you can do well from the start. Interpretation depends on knowing the developmental sequence (subitising, counting, cardinality, comparison, part–whole, derived facts, procedures — Reference sheet) well enough to place the child in it.",
"s3":    "YOU RUN IT — give tasks that separate the two: untimed conceptual tasks (show it with objects, place it on a number line, explain why) alongside a brief timed fact probe, and a calculation with and without the language wrapper. Your supervisor watches.\n\nWHAT THEY ARE WATCHING FOR — reading 'slow' as 'does not understand'; reading correct answers reached by slow counting as mastery; ignoring reading load, working memory or anxiety as sources of failure.\n\nSTEPPING IN LOOKS LIKE — 'she got it right — but how? Ask her to show you.'",
"s4":    "YOU DO IT ALONE — your report states whether the difficulty is fact retrieval, conceptual, or both, gives the observed evidence for that, and the recommendation targets the one you found.\n\nPASS TEST — The recommendation targets the right one\n\nEVIDENCE TO FILE — the strategy notes and the report section linking evidence to recommendation. Log against 3. Intervention and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — daily times-table drill recommended for a child who still counts all from one to add 4 and 3, who then learns to fear maths as well as not understand it.",
"s5":    "YOU CAN TEACH IT — you can explain the developmental sequence in number, what a retrieval difficulty and a conceptual difficulty each look like in a child's behaviour, and which quick tasks separate them, citing Gersten et al. (2009) and Dowker (2004).\n\nWHEN IT GOES WRONG — you can say what to do when a review shows fact speed improved but word problems did not: re-examine the other sources the Reference sheet names — reading load, working memory, anxiety — and re-specify rather than extending the drill.",
"error": "Recommending fact drill for a child whose difficulty is conceptual, such as unsecured cardinality.",
"feeds": "→ Feeds into 'Recommend at the right point on the Continuum' and into Formulation.",
"evidence":"Strategy observation notes · report · Log sheet tagged 3. Intervention and 1. Assessment"},

("Educational interventions in numeracy","Recommend at the right point on the Continuum"): {
"why":   "Irish schools allocate support through the NEPS Continuum of Support: Classroom Support, School Support and School Support Plus. A recommendation that does not name a level leaves the school guessing how to resource it (Reference sheet). If you recommend School Support Plus, say what makes it that rather than School Support — usually intensity, individualisation and the involvement of outside services. Jumping to the top level because a psychologist is involved can pull resource from a child who needed it more, and can skip what the class teacher could have done.",
"s1":    "WATCH FOR — how your supervisor asks where the child currently sits on the Continuum, what has been tried at each level and for how long, and how that is recorded in the school's Student Support File or equivalent.\n\nWRITE DOWN — the current level, the interventions tried, their duration and dose, and the outcome, as the school described them.\n\nASK AFTERWARDS — 'what would make you recommend School Support Plus rather than School Support for a maths difficulty?'",
"s2":    "YOU TAKE — reviewing the Student Support File (with consent in place) and summarising what has been tried at each level, including gaps in the record.\n\nTHEY HOLD — any recommendation that moves the child to a different level, especially to School Support Plus, which carries implications for NEPS and outside-agency involvement.\n\nWHY THAT SPLIT — summarising the record is careful reading. Moving a child between levels affects how the school allocates its special education teaching, and your supervisor knows the school's caseload and the service's practice.",
"s3":    "YOU RUN IT — state the level with your reasons in the consultation, supervisor present, and include what the class teacher does at Classroom Support level whatever else is recommended.\n\nWHAT THEY ARE WATCHING FOR — jumping to School Support Plus because the child was referred to psychology; leaving out the classroom-level actions; naming a level without saying what distinguishes it.\n\nSTEPPING IN LOOKS LIKE — 'whatever level we agree, what does the class teacher do differently on Monday morning?'",
"s4":    "YOU DO IT ALONE — every numeracy recommendation names the Continuum level, says why that level rather than the one below, and includes the classroom-level actions that continue alongside.\n\nPASS TEST — Level stated\n\nEVIDENCE TO FILE — the report recommendation and the school's updated support plan. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — 'the school should provide maths support' — the principal cannot tell whether that means a change in class, a place in the SET group, or a referral on, and does nothing until the next contact.",
"s5":    "YOU CAN TEACH IT — you can explain the three Continuum levels, how a numeracy difficulty is placed on them, and why the classroom level never drops out, pointing a peer to the NEPS Continuum of Support guidelines. You can also say, per PSI Code 2.3.1, why a report should admit that the numeracy evidence base is thinner than the literacy one.\n\nWHEN IT GOES WRONG — you can say what to do when the school disagrees about the level: return to what has been tried and its outcomes, agree a time-limited trial at the lower level with a review date, and involve your supervisor.",
"error": "Omitting the Continuum level, so the school cannot tell how to allocate the support.",
"feeds": "→ Feeds into 'Specify what success would look like' and into Systemic Change — school-level provision.",
"evidence":"Report recommendation · Student Support File summary (no identifiers in Log) · Log sheet tagged 3. Intervention"},

("Educational interventions in numeracy","Specify what success would look like"): {
"why":   "CORU SoP 3.8 requires evaluation, and in numeracy, where the evidence base is thinner than for literacy (Reference sheet), a clear local definition of success matters even more. 'Improved number skills' cannot be checked. A success criterion a teacher can observe — for example, 'counts on from the larger number to add within 20 without prompting' — can. Without one, the review becomes a matter of opinion and the child either stays in a group that is not working or leaves one that is.",
"s1":    "WATCH FOR — how your supervisor turns a finding into an observable target: the behaviour, the conditions, how often it must be seen, and how the teacher will check it.\n\nWRITE DOWN — two or three targets they write, and note which part is the behaviour, which the condition, and which the level expected.\n\nASK AFTERWARDS — 'how do you set a target ambitious enough to matter but modest enough that the child can reach it this term?'",
"s2":    "YOU TAKE — drafting two or three observable success criteria for a child on your caseload, each tied to where you placed them in the developmental sequence.\n\nTHEY HOLD — judgement on whether the targets are realistic for the period and the dose agreed.\n\nWHY THAT SPLIT — writing observable targets is a learnable technical skill. Judging how far a child is likely to move in a term takes experience, and there is no universal rate to look up — check any growth expectation against the measure's own guidance.",
"s3":    "YOU RUN IT — agree the success criteria with the class teacher or SET at the meeting, supervisor present, and check that the teacher can say how they would see each one in an ordinary lesson.\n\nWHAT THEY ARE WATCHING FOR — targets that describe what the adult will do ('will receive support') rather than what the child will do; targets only a psychologist could assess.\n\nSTEPPING IN LOOKS LIKE — 'Ms X, if you saw this on a Wednesday, how would you know? What would he be doing?'",
"s4":    "YOU DO IT ALONE — every numeracy plan has observable success criteria, stated in terms of what the child will do, under what conditions, checked how and by whom, by a stated date.\n\nPASS TEST — A teacher would know whether it worked\n\nEVIDENCE TO FILE — the plan with success criteria, and the consultation note where the teacher agreed them. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at review, the teacher says 'he's doing a bit better, I think', the SET says 'not really', and there is nothing written to settle it.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to turn a developmental finding into an observable target (behaviour, condition, level, date, checker) and why targets about the adult's input do not count.\n\nWHEN IT GOES WRONG — you can say what to do when the criteria turn out to be set wrongly: revise them openly at the review, record why, and do not move the goalposts quietly to make an intervention look successful.",
"error": "Writing targets about the support given rather than what the child will be able to do.",
"feeds": "→ Feeds into 'Measure something before and after' and into Intervention review at the next placement.",
"evidence":"Support plan — success criteria · consultation note · Log sheet tagged 3. Intervention"},

# ---------------------------------------------------------------------------
# Wellbeing interventions at class and group level
# ---------------------------------------------------------------------------

("Wellbeing interventions at class and group level","Know the evidence base for what you recommend"): {
"why":   "CORU SoP 5.33 and 5.41 are mapped here. The evidence is uneven: social and emotional learning delivered with fidelity produces modest but real gains (Durlak et al., 2011); CBT-informed anxiety groups have reasonable support; universal mindfulness is mixed, and the MYRIAD trial (Kuyken et al., 2022) complicated the story for adolescents (Reference sheet). Grouping children with conduct difficulties carries a documented risk of harm (Dishion, McCord & Poulin, 1999). Recommend what a school likes rather than what the evidence supports and you misrepresent effectiveness — which PSI Code 4.2.2 prohibits.",
"s1":    "WATCH FOR — how your supervisor answers when a principal asks 'should we do X with Sixth Class?': what evidence they cite, how they phrase uncertainty, and whether they ask what the difficulty is before discussing a programme.\n\nWRITE DOWN — the programme, the claim made for it, the source cited, and any caveat your supervisor added. Note which programmes your service actually uses (the Reference sheet names Friends for Life as one used in Irish settings — check what your service holds).\n\nASK AFTERWARDS — 'how do you tell a school their favourite programme lacks evidence without losing them?'",
"s2":    "YOU TAKE — reading the core sources yourself — Durlak et al. (2011), Weare and Nind (2011), Dishion et al. (1999), Kuyken et al. (2022) — and writing a one-page evidence note for each approach your Cavan service uses, with effect sizes copied from the papers, not from memory.\n\nTHEY HOLD — the advice to the school, and any conversation redirecting a school from something it has invested in.\n\nWHY THAT SPLIT — reading and summarising is yours to do. Redirecting a school is relational work your supervisor already holds.",
"s3":    "YOU RUN IT — answer a school's question about a wellbeing programme yourself in a consultation, supervisor present: state what the evidence supports, what it does not, and what fidelity requires, and cite the source.\n\nWHAT THEY ARE WATCHING FOR — presenting mindfulness as established; quoting an effect size you have not read; recommending a targeted group when a third of the class shares the difficulty.\n\nSTEPPING IN LOOKS LIKE — 'what does the Kuyken trial actually say for this age group? Let's check before we advise.'",
"s4":    "YOU DO IT ALONE — every group or class-level recommendation you make is accompanied by a citation you have read, a plain statement of the strength of evidence, and any known risk.\n\nPASS TEST — You can cite it\n\nEVIDENCE TO FILE — your evidence notes and the consultation record. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — you recommend a universal mindfulness course to a post-primary school as 'proven to reduce anxiety', and a teacher who has read the MYRIAD findings asks you where that claim comes from.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the tiers (universal, targeted, indicated), what the evidence supports at each, why fidelity predicts outcome, and the deviancy-training risk, citing the Reference sheet's sources and the Department of Education Wellbeing Policy Statement and Framework for Practice.\n\nWHEN IT GOES WRONG — you can say what to do when you realise you overstated evidence: correct it with the school in writing, explain what the evidence does support, and tell your supervisor.",
"error": "Presenting a programme as effective without having read the evidence, or presenting mindfulness as established.",
"feeds": "→ Feeds into 'Co-facilitate rather than only observe' and 'Measure something before and after'.",
"evidence":"Evidence notes · consultation record · Log sheet tagged 3. Intervention"},

("Wellbeing interventions at class and group level","Co-facilitate rather than only observe"): {
"why":   "CORU SoP 5.36 is mapped here. Watching a group is not the same as running one: facilitation means managing time, participation, disclosure and the child who will not join in, all at once. The Reference sheet names class and group work as the area Irish trainees evidence most thinly. Co-facilitating with school staff from the first session is also how the work survives your leaving (CORU SoP 5.40). A trainee who only observed has no evidence of the competency at all.",
"s1":    "WATCH FOR — how the facilitator opens a session, sets ground rules with the group rather than for them, handles the child who dominates and the child who says nothing, and what they say at the start about what they will do if someone shares something worrying.\n\nWRITE DOWN — the session structure, the phrases used for ground rules and for the limits of confidentiality in children's terms, and one moment where the plan changed.\n\nASK AFTERWARDS — 'what do you do in a group when a child begins to disclose something in front of the others?'",
"s2":    "YOU TAKE — one defined segment of each session (the warm-up, an activity, or the closing round), planned in advance with your co-facilitator.\n\nTHEY HOLD — the session as a whole, ground rules, and any disclosure or distress — which goes to the DLP the same day through the child protection route, with supervision afterwards.\n\nWHY THAT SPLIT — a defined segment lets you practise facilitation with a safety net. Disclosure in a group needs a practised response and a clear route.",
"s3":    "YOU RUN IT — lead whole sessions with the school's co-facilitator, and with your supervisor or the lead facilitator present for at least the first. Agree beforehand who handles distress and who keeps the group going.\n\nWHAT THEY ARE WATCHING FOR — talking more than the children; letting one child set the tone; not stating the limits of confidentiality at the start; the co-facilitator from the school left as a spectator.\n\nSTEPPING IN LOOKS LIKE — the lead taking over the moment a child starts to disclose: 'thank you for telling us — I'd like to hear more of that with you after the group.'",
"s4":    "YOU DO IT ALONE — deliver identified sessions or parts of sessions as a named co-facilitator, with the school's staff member alongside you, with ground rules and limits stated at the start.\n\nPASS TEST — You delivered part of it\n\nEVIDENCE TO FILE — session plans showing your part, a session log, and supervisor feedback. Log against 3. Intervention. No child names in your own Log.\n\nWHAT FAILURE LOOKS LIKE — eight weeks sitting at the back taking notes; the Appendix 5 entry says 'observed group' every week and there is nothing to evidence facilitation.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer how to plan a co-facilitated session, split roles, set ground rules with a group, and state the limits of confidentiality in children's words, drawing on the Reference sheet's section on facilitating without doing harm.\n\nWHEN IT GOES WRONG — you can say what to do when a session runs badly (conflict, a child leaves upset): make sure the child is safe and with an adult, debrief with your co-facilitator the same day, and bring it to supervision.",
"error": "Spending the whole group as an observer, so there is no evidence you facilitated anything.",
"feeds": "→ Feeds into 'Adapt delivery to the group in front of you' and 'Leave the teacher able to run it'.",
"evidence":"Session plans · session log · supervisor feedback · Appendix 5 · Log sheet tagged 3. Intervention"},

("Wellbeing interventions at class and group level","Adapt delivery to the group in front of you"): {
"why":   "CORU SoP 5.36 is mapped here. The Reference sheet says fidelity predicts whether social and emotional learning works, so adaptation is not a licence to rewrite a programme. The skill is adapting the surface — pacing, examples, language, format, seating — while keeping the core components intact. The implementation literature discusses this tension between fidelity and adaptation (Kelly & Perkins, 2012; read the relevant chapters). Deliver a manual rigidly to a group it does not fit and the children switch off; change the core and you cannot tell whether the programme works.",
"s1":    "WATCH FOR — the moments an experienced facilitator changes something mid-session — shortening an activity, swapping an example for one closer to the children's lives, moving from talk to drawing — and the moments they deliberately do not.\n\nWRITE DOWN — what was changed, what prompted it (what the children were doing), and whether the change touched a core component or only the surface.\n\nASK AFTERWARDS — 'how do you know which parts of this programme you must not change?'",
"s2":    "YOU TAKE — reading the programme manual to identify its core components, and proposing surface adaptations in advance for this group (age, language, literacy level, any child with additional needs).\n\nTHEY HOLD — any decision to change a core component or drop a session.\n\nWHY THAT SPLIT — planned surface adaptation is checkable against the manual. Changing core content affects whether the programme is still the programme, and whether the outcome data mean anything.",
"s3":    "YOU RUN IT — make adaptations in the moment during your part of the session, with your co-facilitator present, and note each one afterwards.\n\nWHAT THEY ARE WATCHING FOR — ploughing on with a discussion the group has clearly left; or, the opposite, dropping the difficult core activity because the group resisted it.\n\nSTEPPING IN LOOKS LIKE — 'they've lost the thread — try the drawing version of that activity' or, after the session, 'that change cut the practice step; that one is core.'",
"s4":    "YOU DO IT ALONE — notice when the group is not with you, change something on the surface in response, keep the core components intact, and record what you changed and why.\n\nPASS TEST — You changed something in response\n\nEVIDENCE TO FILE — the session log with adaptations noted, and the fidelity record showing core components delivered. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a session delivered word for word from the manual to a group of children who were visibly lost for forty minutes, with nothing noted.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between core components and surface features, how to find which is which in a manual, and why recording adaptations matters for interpreting outcomes.\n\nWHEN IT GOES WRONG — you can say what to do when you realise an adaptation changed a core component: record it honestly, restore the component in the next session if possible, and note it when you interpret the outcome data.",
"error": "Either delivering the manual rigidly to a group it does not fit, or quietly cutting core components.",
"feeds": "→ Feeds into 'Measure something before and after' and 'Leave the teacher able to run it'.",
"evidence":"Session log with adaptations · fidelity record · Log sheet tagged 3. Intervention"},

("Wellbeing interventions at class and group level","Measure something before and after"): {
"why":   "CORU SoP 3.8 is mapped here. The Reference sheet asks for pre and post measures on the children, a fidelity check on delivery, and a teacher or facilitator view — without them you cannot say whether the group worked, or whether a null result reflects the programme or its delivery. A brief measure at week one and the final week is often enough. It also gives you a practice-based research output, which the Reference sheet notes is another development area met by the same piece of work.",
"s1":    "WATCH FOR — what your supervisor or service uses to evaluate groups: which child measure, which teacher measure, how consent covers them, and how fidelity is recorded session by session.\n\nWRITE DOWN — the measures, when each is given, who gives it, and how the results are reported back to the school.\n\nASK AFTERWARDS — 'what do you do when the post-measures are no better — do you tell the school the group did not work?'",
"s2":    "YOU TAKE — setting up the evaluation for a group: proposing a brief validated measure the service approves (check the tools list on the Reference sheet and any licensing), a fidelity checklist from the manual, and a short teacher questionnaire.\n\nTHEY HOLD — sign-off on the measures and on consent, and how the results are communicated.\n\nWHY THAT SPLIT — setting up is organisation you can own. Choosing measures and agreeing consent for data collection on children involves service policy and ethics your supervisor holds.",
"s3":    "YOU RUN IT — administer the pre-measure before session one, complete the fidelity checklist after each session, and take the post-measure in the final session. In Cavan, plan backwards from 18/12/2026 so the post-measure is not lost to the Christmas break.\n\nWHAT THEY ARE WATCHING FOR — no pre-measure; measures given in different conditions pre and post; outcomes overclaimed from small numbers.\n\nSTEPPING IN LOOKS LIKE — 'with eight children and no comparison group, what can you honestly say from these numbers?'",
"s4":    "YOU DO IT ALONE — every group you run has a pre-measure, a post-measure, a fidelity record and a staff view, and you report the result honestly with its limits.\n\nPASS TEST — There is outcome data, however simple\n\nEVIDENCE TO FILE — the anonymised summary of pre and post data, the fidelity record, and the report back to the school. Log against 3. Intervention and 8. Research.\n\nWHAT FAILURE LOOKS LIKE — an eight-week group ends, the children liked it, and nobody can say whether anything changed.",
"s5":    "YOU CAN TEACH IT — you can explain why pre, post and fidelity data are all needed, how to choose a brief measure, and how to state the limits of small-group data without dismissing it.\n\nWHEN IT GOES WRONG — you can say what to do when the data show no change or worse: check fidelity first, report honestly to the school, bring it to supervision, and consider — with reference to Dishion et al. (1999) — whether the group composition could have contributed.",
"error": "Running a group with no pre-measure, so no outcome can be shown.",
"feeds": "→ Feeds into 'Leave the teacher able to run it' and into Research — practice-based evaluation.",
"evidence":"Anonymised pre/post summary · fidelity record · Log sheet tagged 3. Intervention and 8. Research"},

("Wellbeing interventions at class and group level","Leave the teacher able to run it"): {
"why":   "The Reference sheet puts it bluntly: the intervention that ends when you leave has failed. CORU SoP 5.40 asks you to build capacity among those responsible for delivery. The sequence is co-facilitate, then hand over, then review, and the handover has to be written into the plan at the start — it does not happen as an afterthought. A trainee on a ten-week placement is the clearest case: in Cavan you leave on 18/12/2026, and the school keeps the children.",
"s1":    "WATCH FOR — how your supervisor structures handover: when the school's staff member moves from assisting to leading, what materials they are given, and how the review is arranged after the psychologist steps back.\n\nWRITE DOWN — the handover stages, the materials handed over (manual, session plans, fidelity checklist, measures), and the date of the follow-up review.\n\nASK AFTERWARDS — 'which handovers have stuck in your schools, and what made the difference?'",
"s2":    "YOU TAKE — preparing the handover pack: session plans annotated with the adaptations that worked, the fidelity checklist, the measures, and a one-page 'if this happens' guide including the disclosure route to the DLP.\n\nTHEY HOLD — the agreement with the principal about staff time to continue, and the follow-up review after you leave.\n\nWHY THAT SPLIT — the pack is concrete work. Securing staff time is a management decision, and the follow-up needs someone who will still be in the service after 18/12/2026.",
"s3":    "YOU RUN IT — move the school's co-facilitator from assisting to leading over the later sessions, with you supporting, and review each session with them.\n\nWHAT THEY ARE WATCHING FOR — you still leading the final session; a pack left in a staffroom with no conversation; no date for the next run.\n\nSTEPPING IN LOOKS LIKE — 'she's ready to lead next week — step back and let her, even if it goes differently from how you would do it.'",
"s4":    "YOU DO IT ALONE — plan and carry out a handover so that a named staff member has led sessions, holds the materials, knows the disclosure route, and has a date to run it again.\n\nPASS TEST — Capacity remains after you go\n\nEVIDENCE TO FILE — the handover plan, the pack contents list, and a note of the handover meeting. Log against 3. Intervention and 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — in March, the school says 'the psychologist ran a lovely group before Christmas' and nothing has happened since.",
"s5":    "YOU CAN TEACH IT — you can explain the co-facilitate, hand over, review sequence and why it must be planned at the start, and what a usable handover pack contains.\n\nWHEN IT GOES WRONG — you can say what to do when the staff member cannot continue (moves school, loses the time): discuss with the principal who else might take it on, leave the pack with the SET coordinator, and flag it to your supervisor for the follow-up.",
"error": "No handover planned, so the work ends when the placement does.",
"feeds": "→ Feeds into Systemic Change — building school capacity — and into Working with Others.",
"evidence":"Handover plan · pack contents list · meeting note · Log sheet tagged 3. Intervention and 4. Systemic Change"},

# ---------------------------------------------------------------------------
# Foundations in counselling skills
# ---------------------------------------------------------------------------

("Foundations in counselling skills","Use open questions and reflective listening"): {
"why":   "Every parent meeting and pupil interview runs on these micro-skills, and without them you get thin information and damaged relationships (Reference sheet). Open questions get an account; closed questions confirm a detail. Reflection of content shows you heard; reflection of feeling, offered tentatively, shows you understood — and it is the one trainees skip (Egan & Reese, 2021). CORU SoP 5.18 is mapped here. This is foundation communication under supervision, not therapy.",
"s1":    "WATCH FOR — the ratio of open to closed questions your supervisor uses in a pupil interview, and how they reflect feeling tentatively ('that sounds like it was really frightening') rather than labelling ('you're anxious').\n\nWRITE DOWN — three open questions and two reflections they used, word for word, and what the young person said next each time.\n\nASK AFTERWARDS — 'when a young person gives one-word answers to open questions, what do you try next?'",
"s2":    "YOU TAKE — part of a pupil interview (for example, the section on what school is like), using open questions and reflections you have prepared.\n\nTHEY HOLD — the rest of the interview, and anything that moves toward risk or distress.\n\nWHY THAT SPLIT — a bounded section lets you practise the technique with support. Anything touching risk — self-harm, suicidal thinking or abuse — goes through the child protection and risk route the same day, and your supervisor holds that until you are practised.",
"s3":    "YOU RUN IT — lead a whole pupil interview or parent conversation, supervisor present, and afterwards count roughly who spoke more.\n\nWHAT THEY ARE WATCHING FOR — strings of closed questions; 'why' questions that sound like blame; labelling feeling; filling the young person's pauses with your next question.\n\nSTEPPING IN LOOKS LIKE — your supervisor, gently: 'you said it was hard at lunchtime — tell us a bit more about lunchtime', modelling the open prompt you missed.",
"s4":    "YOU DO IT ALONE — conduct an interview where most of the talking is the young person's, using open questions, reflections of content and feeling offered tentatively, and summaries that let them correct you.\n\nPASS TEST — The young person speaks more than you do\n\nEVIDENCE TO FILE — the interview record (with consent) and a reflective note on your questioning. Log against 3. Intervention. No identifying details in your own Log.\n\nWHAT FAILURE LOOKS LIKE — an interview note full of your questions and the young person's 'yeah' and 'dunno'.",
"s5":    "YOU CAN TEACH IT — you can explain the purpose of each micro-technique (open question, closed question, reflection of content, reflection of feeling, summary), why tentative reflection invites correction, and where they come from (Rogers, 1957; Egan & Reese, 2021).\n\nWHEN IT GOES WRONG — you can say what to do when a reflection lands badly ('no, I'm not sad'): accept the correction, thank them, and use it — the correction is information.",
"error": "Asking a string of closed questions and labelling feelings instead of reflecting them tentatively.",
"feeds": "→ Feeds into 'Hold silence without filling it' and into Assessment — including the child's voice.",
"evidence":"Interview record · reflective note · Log sheet tagged 3. Intervention"},

("Foundations in counselling skills","Hold silence without filling it"): {
"why":   "The Reference sheet says a silence of three to five seconds after an answer produces more than any follow-up question, and is the hardest to tolerate. Rowe's (1974) classroom research on teacher 'wait-time' is a related source — read it for the detail rather than quoting figures from memory. CORU SoP 5.21 is mapped here. Filling silence — the Reference sheet's first listed error — cuts off the thought the young person was about to share and teaches them you will do the talking.",
"s1":    "WATCH FOR — how long your supervisor waits after asking a question or after a young person stops speaking, and what the young person does in that gap. Count silently.\n\nWRITE DOWN — two moments where the silence produced something new, and one where your supervisor judged the silence as distress rather than thinking and responded.\n\nASK AFTERWARDS — 'how do you tell a thinking silence from a stuck or distressed one, especially with a younger child?'",
"s2":    "YOU TAKE — deliberately practising a count of five after each answer during the interview section you lead.\n\nTHEY HOLD — reading silences that may signal distress, withdrawal of assent or something hard to say, and responding to them.\n\nWHY THAT SPLIT — waiting can be practised mechanically at first. Judging when silence has become distress, and what to offer then, is a skill built on experience, and a silence before a disclosure needs a practised response.",
"s3":    "YOU RUN IT — hold silence in your own interviews, supervisor present, and offer a gentle prompt only when the young person seems stuck rather than thinking ('take your time').\n\nWHAT THEY ARE WATCHING FOR — jumping in within a second or two; answering your own question; rephrasing the same question three ways; and the opposite error — leaving a distressed child sitting in silence.\n\nSTEPPING IN LOOKS LIKE — afterwards: 'you asked about home, she opened her mouth, and you asked about school. What might she have said?'",
"s4":    "YOU DO IT ALONE — after questions and answers, wait before speaking; use silence to let the young person continue; distinguish distress from thought and respond to distress.\n\nPASS TEST — You waited\n\nEVIDENCE TO FILE — a reflective note on one interview recording where you held silence and what followed (no identifiers). Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — every pause filled with a new question, and a young person who learns to wait you out.",
"s5":    "YOU CAN TEACH IT — you can explain why silence works, how long it feels versus how long it is, and how to tell thinking from distress, citing the Reference sheet and Rowe (1974).\n\nWHEN IT GOES WRONG — you can say what to do when silence has tipped into distress: name it gently, offer a break or a different way to respond (drawing, pointing, writing), and check whether the young person wants to stop — respecting withdrawal of assent.",
"error": "Filling every silence, so the young person never gets to finish the thought.",
"feeds": "→ Feeds into 'Use scaling or solution-focused questioning' and into Ethical Practice — recognising non-verbal withdrawal.",
"evidence":"Reflective note · Log sheet tagged 3. Intervention"},

("Foundations in counselling skills","Use scaling or solution-focused questioning"): {
"why":   "The Reference sheet describes solution-focused approaches as widely used in Irish educational psychology, within trainee competence with supervision, and well suited to school work. Scaling questions, the miracle question, exception-finding and identifying what already works give a pupil interview a defensible structure (Ratner, George & Iveson, 2012). CORU SoP 5.18 is mapped. You used this framework at Roscommon; the aim now is to use it deliberately. Without a technique, an interview drifts into a conversation that may be pleasant but is hard to use.",
"s1":    "WATCH FOR — how your supervisor introduces a scale (0 to 10, or a visual ladder for younger children), asks 'what makes it a 4 and not a 2?', and asks 'what would one point higher look like?'. Notice how they adapt the miracle question for a younger child.\n\nWRITE DOWN — the exact wording of the scaling and exception questions and the young person's answers.\n\nASK AFTERWARDS — 'when would you not use the miracle question with a child?'",
"s2":    "YOU TAKE — the scaling segment of a pupil interview, using wording and a visual scale prepared and checked with your supervisor.\n\nTHEY HOLD — the rest of the interview, and the decision about whether a solution-focused approach suits this young person at all (for example, where there is recent loss or trauma, which is outside your competence).\n\nWHY THAT SPLIT — scaling is a bounded technique you can practise safely. Choosing the approach depends on the formulation and on knowing when a young person's difficulties need more than you can offer.",
"s3":    "YOU RUN IT — use a full solution-focused structure in a pupil interview — best hopes, scaling, exceptions, next small step — with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — using the scale as a rating and moving on without the follow-up questions; pushing past a young person's problem talk so fast that they feel unheard.\n\nSTEPPING IN LOOKS LIKE — 'you got a 3 — ask what's keeping it at 3 and not lower. That's where the strengths are.'",
"s4":    "YOU DO IT ALONE — conduct a pupil interview structured by a named solution-focused technique, adapted to age, and record what the technique produced.\n\nPASS TEST — You have a technique, not just a conversation\n\nEVIDENCE TO FILE — the interview record and a note on the technique used and its adaptations. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — an interview note that reads 'chatted about school, seems happy enough', with nothing that can inform a plan.",
"s5":    "YOU CAN TEACH IT — you can explain the core solution-focused techniques, how to adapt scaling for a young child (faces, a ladder, a number line on the floor), and when the approach is not appropriate, citing Ratner, George and Iveson (2012).\n\nWHEN IT GOES WRONG — you can say what to do when a young person answers '0' or 'nothing is working': acknowledge it, ask how they are coping at all, and if risk may be present, follow the risk route the same day and bring it to supervision.",
"error": "Asking the scaling question and moving on without the follow-up questions that make it useful.",
"feeds": "→ Feeds into 'Recognise when the work exceeds your competence' and into Intervention planning with the young person.",
"evidence":"Interview record · technique note · Log sheet tagged 3. Intervention"},

("Foundations in counselling skills","Recognise when the work exceeds your competence"): {
"why":   "You can listen, contain and help someone think; you cannot deliver therapy, treat a mental health condition, or work with trauma (Reference sheet). PSI Code 2.2.2 and CORU SoP 1.2 are mapped here — read the Code's wording on Part B of the Reference sheet. Drifting into therapy with a parent because it felt unkind to stop is one of the Reference sheet's named errors, and crossing this boundary is among the more serious things a trainee can do. Any disclosure of self-harm, suicidal thinking or abuse goes through the child protection and risk route the same day; supervision follows action.",
"s1":    "WATCH FOR — the moment in a meeting when your supervisor recognises the conversation moving outside the purpose of the work (a parent's own mental health, a child's trauma history) and how they acknowledge it, contain it and redirect.\n\nWRITE DOWN — the signal they noticed and the words they used to redirect, without identifying details.\n\nASK AFTERWARDS — 'how early do you name the limit — and how do you do it without the person feeling pushed away?'",
"s2":    "YOU TAKE — writing out in advance, for each case, what your role is and is not, and preparing a sentence you can use to name the limit kindly.\n\nTHEY HOLD — conversations likely to move into risk, trauma or a parent's own mental health, and any decision about what to do next.\n\nWHY THAT SPLIT — preparing the boundary is something you can do before the meeting. Holding a person in distress while redirecting them, and judging risk, needs experience you are not expected to have yet.",
"s3":    "YOU RUN IT — lead a meeting where the boundary may be tested, supervisor present; name the purpose at the start, and redirect if the conversation moves beyond it.\n\nWHAT THEY ARE WATCHING FOR — continuing because it feels unkind to stop; offering advice on a parent's own difficulties; asking a child questions that open up trauma.\n\nSTEPPING IN LOOKS LIKE — 'it sounds like you've been carrying a lot yourself. That matters, and it deserves proper support — can we talk about who could help you with that?'",
"s4":    "YOU DO IT ALONE — state your role at the start, recognise when the conversation is moving beyond it, name the limit kindly before you are in it, and route risk disclosures through the child protection and risk route the same day.\n\nPASS TEST — You named your limit before reaching it\n\nEVIDENCE TO FILE — the case note recording the redirection and any onward action, and the supervision note. Log against 3. Intervention and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a parent meeting that became a weekly listening session about the parent's own depression, with no referral made.",
"s5":    "YOU CAN TEACH IT — you can explain where a trainee's competence ends, why (PSI Code 2.2.2, 2.2.3), what the early signals are, and how to name the limit without rejecting the person.\n\nWHEN IT GOES WRONG — you can say what to do when you realise you have already crossed the line: stop, tell your supervisor the same day, agree how to close that thread with the person and where to refer, and record it.",
"error": "Continuing into therapy with a parent or child because stopping felt unkind.",
"feeds": "→ Feeds into 'Know the onward referral route and use it' and into Ethical Practice — working within competence.",
"evidence":"Case note · supervision note · Log sheet tagged 3. Intervention and 6. Ethical Practice"},

("Foundations in counselling skills","Know the onward referral route and use it"): {
"why":   "PSI Code 3.4.3 is mapped here. When a conversation moves beyond your competence, the Reference sheet says you must have a name to give rather than a vague suggestion to 'see someone', and the routes must be written out in advance. In Ireland these may include the GP, HSE CAMHS (usually via GP), HSE Primary Care psychology, a Children's Disability Network Team, Tusla, and for any child protection concern the school's DLP. Referral criteria and waiting times vary — check each locally. A vague signpost leaves the person with nowhere to go.",
"s1":    "WATCH FOR — how your supervisor signposts: the service named, how to access it, whether a referral is made or the family self-refers, and how they check the family understood.\n\nWRITE DOWN — for each route: who it is for, how to access it, whether a GP letter is needed, and what the family should expect. Note the service's own list of crisis lines — check numbers there before giving any out.\n\nASK AFTERWARDS — 'which referral routes in this area actually work, and which look good on paper?'",
"s2":    "YOU TAKE — building a referral route sheet for your Cavan area before the placement starts on 05/10/2026: services, access routes, criteria, and the DLP for each of your schools.\n\nTHEY HOLD — decisions to refer, and making referrals on the service's behalf.\n\nWHY THAT SPLIT — compiling the sheet is research you can own. A referral commits the service, needs consent, and relies on your supervisor's judgement about which route is right.",
"s3":    "YOU RUN IT — signpost or propose a referral yourself in a meeting, supervisor present: name the service, explain how to access it, and check the parent or young person knows the next step.\n\nWHAT THEY ARE WATCHING FOR — 'you might want to talk to someone'; recommending a service without knowing its criteria; forgetting the same-day risk route when self-harm or abuse is mentioned.\n\nSTEPPING IN LOOKS LIKE — 'the GP is the way in to CAMHS here — would it help if we wrote a short note you could bring?'",
"s4":    "YOU DO IT ALONE — when the work exceeds your competence, stop and refer, naming a specific route, how to access it and what happens next; for risk, use the child protection and risk route the same day, then bring it to supervision.\n\nPASS TEST — You referred rather than continued\n\nEVIDENCE TO FILE — the case note of the referral or signpost and the route sheet. Log against 3. Intervention and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a parent told to 'look into some counselling' who leaves with no name, no number and no plan.",
"s5":    "YOU CAN TEACH IT — you can explain the main referral routes in the Irish system, how to access each, and how to signpost in a way a family can act on.\n\nWHEN IT GOES WRONG — you can say what to do when a referral is refused or the wait is long: tell the family honestly, identify interim supports with your supervisor, and record it.",
"error": "Signposting vaguely ('talk to someone') with no named service or route.",
"feeds": "→ Feeds into 'Close the relationship properly' and into Working with Others — interagency practice.",
"evidence":"Referral route sheet · case note · Log sheet tagged 3. Intervention and 5. Working with Others"},

("Foundations in counselling skills","Close the relationship properly"): {
"why":   "The Reference sheet says to signal the ending before it arrives, summarise what was said and what happens next, and be explicit about what you will and will not do and what will be written down and who will see it. An unclear ending leaves a parent expecting contact that is not coming, which does more damage than a blunt but clear one. CORU SoP 5.21 and PSI Code 3.4.4 are mapped here. For a trainee, placement end is a fixed ending: in Cavan, 18/12/2026.",
"s1":    "WATCH FOR — how your supervisor ends a session and ends an involvement: the signal ('we have about ten minutes left'), the summary, what happens next, and who the family contacts after.\n\nWRITE DOWN — the words used for each part, and anything written down for the family.\n\nASK AFTERWARDS — 'how do you end with a young person who has told you a lot, without it feeling like being dropped?'",
"s2":    "YOU TAKE — the summary and 'what happens next' part at the end of a session your supervisor led.\n\nTHEY HOLD — ending the involvement with the family and handing on to whoever holds the case after you.\n\nWHY THAT SPLIT — summarising is a learnable micro-skill. Ending a relationship, especially for a trainee who is leaving, means managing expectations and case transfer, which your supervisor holds.",
"s3":    "YOU RUN IT — end your own sessions, supervisor present: signal the end, summarise, state what you will and will not do, what gets written and who sees it, and who to contact.\n\nWHAT THEY ARE WATCHING FOR — running out of time and ending abruptly; promising contact you cannot deliver; not telling a young person that you are leaving at the end of the placement.\n\nSTEPPING IN LOOKS LIKE — 'before you finish, tell him who he can go to in school after you've gone.'",
"s4":    "YOU DO IT ALONE — close every session and every involvement with a signalled ending, a summary, clear next steps, what is recorded and who sees it, and a named contact after you leave.\n\nPASS TEST — There was an ending, not a lapse\n\nEVIDENCE TO FILE — the closing case note, the handover note, and the letter or summary given to the family. Log against 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a parent phones the service in January asking when the trainee is coming back, and nobody told her.",
"s5":    "YOU CAN TEACH IT — you can explain the components of a good ending, why an unclear ending harms more than a clear one, and how to plan endings from the start of a time-limited placement.\n\nWHEN IT GOES WRONG — you can say what to do when an involvement ended without closure: tell your supervisor, contact the family with a clear summary and next step, and record it.",
"error": "Letting contact lapse without a signalled ending, summary and named next contact.",
"feeds": "→ Feeds into Working with Others — case transfer — and into Ethical Practice — record-keeping.",
"evidence":"Closing case note · handover note · Log sheet tagged 3. Intervention"},

}
