"""Working with Others (part A): rapport with the child, communication with school
staff, and feedback to parents. Written in the micro.py format from HANDOVER.md.

Keyed (macro skill name, micro-skill name).
"""

MICRO = {

# ── 5. WORKING WITH OTHERS · Build rapport with a child during assessment ──

("Build rapport with a child during assessment","Meet the child at their level, literally and in register"): {
"why":   "The Reference sheet puts it bluntly: rapport is measurement validity, because an anxious or suspicious child produces scores that underestimate them. Sattler (Assessment of Children: Cognitive Foundations, 6th ed., 2018) treats establishing rapport and observing test behaviour as part of the assessment itself, not a warm-up. An adult standing over a six-year-old, or talking to a fifteen-year-old as if they were six, starts the session with the child managing you. CORU SoP 2.2 is the standard mapped here. Get it wrong and every score that follows is in question.",
"s1":    "WATCH FOR — where your supervisor puts their body in the first minute: sitting or crouching to eye level, side-on rather than across a desk, or leaving the child the seat nearest the door. Then listen to register — sentence length, vocabulary, humour — and how it shifts between a Junior Infant and a Leaving Cert student.\n\nWRITE DOWN — the first three sentences they said to the child, word for word, and the child's age band (UCD Table 3).\n\nASK AFTERWARDS — 'what did you notice about this child in the corridor that changed how you spoke to them in the room?'",
"s2":    "YOU TAKE — setting up the room before the child arrives (chair heights, table side, materials out of sight until needed) and doing the walk from the classroom, where most of the first impression is made.\n\nTHEY HOLD — the introduction and the move into the first task.\n\nWHY THAT SPLIT — room set-up and the corridor walk are low-risk and teach you to read a child before anything is at stake. The introduction sets the tone for scores that will be reported, so it stays with the person accountable for them.",
"s3":    "YOU RUN IT — collect the child, introduce yourself, and settle them into the room, with your supervisor present but not leading.\n\nWHAT THEY ARE WATCHING FOR — the two opposite failures: talking down (sing-song voice, over-praise, questions a younger child would be asked) and talking over (adult vocabulary, long sentences, talking about the child to the teacher in front of them).\n\nSTEPPING IN LOOKS LIKE — your supervisor sitting down beside you so you follow suit, or rephrasing one of your sentences more simply without comment.",
"s4":    "YOU DO IT ALONE — adjust position, pace and language to the child in front of you, not to their age on the referral form, and keep adjusting as you learn more about them in the first ten minutes.\n\nPASS TEST — Not talked down to or over\n\nEVIDENCE TO FILE — the behavioural observations section of the report, noting how the child presented and engaged, and a reflective note in Appendix 5 (no identifying details in the Log). Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a teenager who answers in single words for an hour because you opened with 'Hi there, are you having a nice day?', or a young child who never looks up because you talked across a desk.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why register is a validity issue and not just manners, give examples of the same introduction pitched for a five-year-old, a ten-year-old and a sixteen-year-old, and name what to adjust for a child with a language difficulty or a hearing impairment.\n\nWHEN IT GOES WRONG — you can say what to do when you misjudge it: name it lightly ('that was a bit babyish, sorry — you're in fifth class'), recalibrate, and note in the observations section that engagement improved after the adjustment.",
"error": "Pitching language to the age on the referral form rather than to the child actually in front of you.",
"feeds": "→ Feeds into 'Explain what will happen and why', 'Notice and respond to reluctance', and the validity statement in every assessment report.",
"evidence":"Report — behavioural observations · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Build rapport with a child during assessment","Explain what will happen and why"): {
"why":   "The Reference sheet's first three minutes: who you are in a sentence they can repeat, why you are there, what will happen, how long, that some tasks will be too hard for everyone, and what happens to the information. PSI Code 4.3.1 is the clause mapped here. Children often assume they have been sent to a psychologist because they are in trouble or 'stupid'; unless you say otherwise, that belief sits in the room with every item. A child who does not know the tasks get harder will read their first failure as proof.",
"s1":    "WATCH FOR — the exact words your supervisor uses for 'psychologist', 'test' and 'why you are here', and how these change with age. Notice whether they say that the tasks get harder for everyone, and whether they say who will hear about the session.\n\nWRITE DOWN — the explanation near verbatim, then a version for a younger child and one for a teenager in your own words.\n\nASK AFTERWARDS — 'what do children most often think a psychologist is, and how do you correct it without making it a big deal?'",
"s2":    "YOU TAKE — writing a scripted explanation for each UCD Table 3 age band you will see in Cavan, and checking it with your supervisor before you use it.\n\nTHEY HOLD — the explanation to any child whose referral involves a sensitive reason (bereavement, a child protection history, a recent exclusion).\n\nWHY THAT SPLIT — a script can be tested safely and corrected. Where the reason for referral is itself painful, deciding how much to say needs knowledge of the family and the history that sits with your supervisor.",
"s3":    "YOU RUN IT — give the whole explanation yourself, then ask the child to tell you back what is going to happen, with your supervisor observing.\n\nWHAT THEY ARE WATCHING FOR — explanations that are accurate but too long, jargon ('assessment', 'cognitive'), leaving out what happens to the information, and moving on without waiting for questions.\n\nSTEPPING IN LOOKS LIKE — 'can I add one thing — some of these puzzles get really tricky, and that's the same for everyone who does them.'",
"s4":    "YOU DO IT ALONE — explain purpose, activities, length, the difficulty gradient and who will be told what, in words the child uses, and check it by asking them to say it back rather than asking 'OK?'.\n\nPASS TEST — The child could repeat it back\n\nEVIDENCE TO FILE — a line in the case note recording what was explained and the child's account of it; your age-band scripts as working papers. Log against 5. Working with Others and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a child who asks at the end 'am I in trouble?' or 'will my mam find out?', which means they spent the session not knowing.",
"s5":    "YOU CAN TEACH IT — you can explain why a teach-back ('tell me what we're going to do') is a better check than a closed question, why the difficulty-gradient sentence protects effort on later items, and how the explanation links to assent.\n\nWHEN IT GOES WRONG — you can say what to do when a child's repeat-back shows a misunderstanding: correct it before starting, not mid-battery, and if the misunderstanding was about confidentiality, redo that part in full.",
"error": "Asking 'is that OK?' instead of having the child say back what will happen.",
"feeds": "→ Feeds into 'Obtain informed consent and assent', 'Give the child a real choice early', and 'Close so the child leaves feeling competent'.",
"evidence":"Case note · age-band scripts · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Build rapport with a child during assessment","Give the child a real choice early"): {
"why":   "A child in an assessment has almost no control: someone else chose the day, the room, the adult and the tasks. Giving them one genuine decision early changes the power in the room and usually increases effort. PSI Code 1.4.1 is the clause mapped here; read the Code for its exact wording. The error is the fake choice — 'shall we start?' when refusal is not an option — which children recognise quickly and which teaches them that your other offers are not real either.",
"s1":    "WATCH FOR — every point where your supervisor offers the child a decision, and whether each one is real: which seat, pencil or pen, which of two permitted tasks first, when to take the break, whether the door is open or closed.\n\nWRITE DOWN — each choice offered, and whether the child's answer changed anything.\n\nASK AFTERWARDS — 'which choices can you give without breaking standardised administration, and where does the manual stop you?'",
"s2":    "YOU TAKE — listing, for the battery you are using, the decisions that genuinely belong to the child (seating, break timing, order of subtests only where the manual permits it, materials) and checking the list against the administration manual.\n\nTHEY HOLD — any decision about altering order or procedure in the testing itself.\n\nWHY THAT SPLIT — finding the real choices is a reading task you can do alone. Deciding whether a change to order is permitted affects validity, and the Reference sheet is clear: know exactly what the manual permits before you need it.",
"s3":    "YOU RUN IT — offer the child at least one real choice in the first five minutes and honour the answer, with your supervisor observing.\n\nWHAT THEY ARE WATCHING FOR — choices with a correct answer ('would you like to do some puzzles now?'), choices you then override, and choices that break standard procedure.\n\nSTEPPING IN LOOKS LIKE — 'you asked if she wanted to start — what would you have done if she'd said no? Let's offer her the seat or the break time instead.'",
"s4":    "YOU DO IT ALONE — build at least one genuine, permitted decision into the opening of every session, offer it in words the child understands, and act on whatever they choose.\n\nPASS TEST — Something was actually theirs to decide\n\nEVIDENCE TO FILE — a note in the session record of the choice offered and taken; a reflective line in Appendix 5 on how it affected engagement. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a session transcript where every question to the child had only one acceptable answer, or where the child chose and you then did the other thing.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between a real and a rhetorical choice, list the choices that are safe within standardised administration, and link agency to both effort and to the child's right to be heard (UNCRC, 1989, Art. 12).\n\nWHEN IT GOES WRONG — you can say what to do when the child chooses something you cannot allow: say so honestly, explain why in a sentence, and offer a different decision that is genuinely theirs.",
"error": "Offering a choice the child is not actually allowed to refuse.",
"feeds": "→ Feeds into 'Notice and respond to reluctance', 'Ask the child what they think would help', and the voice of the child in Formulation.",
"evidence":"Session record · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Build rapport with a child during assessment","Notice and respond to reluctance"): {
"why":   "The Reference sheet: refusal is data, and a completed protocol obtained under pressure is worse data than stopping and returning another day. CORU SoP 5.31 is mapped here — adapting and re-evaluating as appropriate, which includes writing it down. Reluctance is rarely a single refusal; it is quieter answers, faster guessing, 'I don't know' before the item is finished, and the shift from effort to compliance. Miss it and you report a low score that measures the child's state, not their ability.",
"s1":    "WATCH FOR — the early signs your supervisor reacts to: longer response times, rapid guessing, glancing at the door, slumping, asking how many are left. Notice what they do first — a break, a change of task within permitted limits, a brief acknowledgement — and what they do not do.\n\nWRITE DOWN — the sign, the item or subtest at which it appeared, what preceded it, and the response.\n\nASK AFTERWARDS — 'at what point would you have stopped the session altogether, and how would you have explained that to the school?'",
"s2":    "YOU TAKE — keeping a running behaviour record during the session (time, subtest, sign) while your supervisor administers.\n\nTHEY HOLD — the in-the-moment decision to pause, change task or stop.\n\nWHY THAT SPLIT — recording reluctance trains you to see it and gives the report its evidence. Deciding to stop has consequences for validity, for the school's expectations and for the child, and your supervisor is accountable for it.",
"s3":    "YOU RUN IT — administer the session and make the call when reluctance appears: pause, acknowledge, offer a break or a permitted change, and record it, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — pushing on to finish the battery because the room is booked or the school expects a report, and encouragement that shades into pressure ('just a few more, come on').\n\nSTEPPING IN LOOKS LIKE — 'let's take a break there' said to the child, then a quiet 'what did you see just now?' to you.",
"s4":    "YOU DO IT ALONE — notice reluctance early, respond by adjusting rather than pushing, record what you saw and did at the moment it happened, and state in the report what it means for how the scores can be read.\n\nPASS TEST — You adjusted rather than pushed on\n\nEVIDENCE TO FILE — the behavioural observations and validity statement in the report; the session record with timings. Log against 5. Working with Others and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a full battery reported as valid when your own notes show the child was guessing from the second half onward.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between fatigue, anxiety, boredom and opposition as causes of reluctance, what the manual permits for each, and why stopping can be the more rigorous choice.\n\nWHEN IT GOES WRONG — you can say what to do when you realise afterwards that you pushed through: flag it in supervision, weaken or withhold the affected scores in the report, and plan a return visit if needed.",
"error": "Completing the battery through visible reluctance and reporting the scores as valid.",
"feeds": "→ Feeds into 'Recognise when standard procedure is not working', 'Re-evaluate whether to continue at all', and 'State the effect on validity in the report'.",
"evidence":"Report — behavioural observations and validity · session record · Log sheet tagged 5. Working with Others"},

("Build rapport with a child during assessment","Ask the child what they think would help"): {
"why":   "UNCRC Article 12 (United Nations, 1989) gives a child capable of forming views the right to express them in matters affecting them, with due weight given according to age and maturity. Lundy (British Educational Research Journal, 2007) argues that voice alone is not enough: the child also needs space, an audience and influence. Children often know exactly what helps — sitting near the window, being told the plan for the day, not being picked to read aloud — and no one asks. A report without the child's view is missing a source.",
"s1":    "WATCH FOR — when and how your supervisor asks the child for their view: after rapport is built, not as the first question, and often through an activity rather than directly (drawing, rating scales, sorting cards, a 'best day / worst day').\n\nWRITE DOWN — the questions or tools used, and the child's answers in their own words.\n\nASK AFTERWARDS — 'how do you decide how much weight a seven-year-old's suggestion gets in the recommendations?'",
"s2":    "YOU TAKE — preparing an age-appropriate way of gathering the child's view for this case, and running that part of the session.\n\nTHEY HOLD — deciding which of the child's suggestions go into the report and how they are attributed.\n\nWHY THAT SPLIT — gathering views well is a skill you build by doing. Putting a child's words into a report that the school and family will read needs a judgement about what is safe and fair to the child to include.",
"s3":    "YOU RUN IT — ask the child what makes school harder and what would help, using a method suited to their age and language, with your supervisor observing.\n\nWHAT THEY ARE WATCHING FOR — leading questions ('would it help if your teacher…?'), asking only at the very end when the child is tired, and hearing an answer without following it up.\n\nSTEPPING IN LOOKS LIKE — 'you said the yard is the worst bit — tell me more about the yard.'",
"s4":    "YOU DO IT ALONE — seek the child's view on what would help in every assessment, record it in their words, and show in the report where it shaped a recommendation, or why it did not.\n\nPASS TEST — The child's view was sought\n\nEVIDENCE TO FILE — the 'child's view' section of the report, and the record of the method used. Log against 5. Working with Others (and UNCRC Art. 12 as the mapped standard).\n\nWHAT FAILURE LOOKS LIKE — a report whose recommendations came entirely from adults, with the child mentioned only as the subject of test scores.",
"s5":    "YOU CAN TEACH IT — you can explain Article 12 and Lundy's four elements (space, voice, audience, influence), describe methods for gathering views across the UCD Table 3 age bands and for a child with limited language, and say how due weight is judged.\n\nWHEN IT GOES WRONG — you can say what to do when the child's suggestion conflicts with the adults': report both, explain the reasoning, and tell the child honestly what happened to their idea.",
"error": "Recording the child's view in the report but letting it change nothing.",
"feeds": "→ Feeds into the voice of the child in Formulation, recommendations, and 'Include the child's own self-report where age-appropriate'.",
"evidence":"Report — child's view · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Build rapport with a child during assessment","Close so the child leaves feeling competent"): {
"why":   "The Reference sheet: thank them specifically, tell them what happens next and who will be told what — children worry about this more than adults assume, and an unclear ending can undo a good session. The child walks back into a classroom of peers who saw them leave with the psychologist; how they walk in matters. CORU SoP 5.21 is mapped here. A session that ends on the hardest item of the hardest subtest leaves the child with that item as their memory of you, and makes a return visit harder.",
"s1":    "WATCH FOR — how your supervisor ends: whether they finish on a task the child can do, what they thank the child for, whether they say what happens next, and how they walk the child back (do they go in with them, or leave them at the door?).\n\nWRITE DOWN — the closing words, and the child's demeanour walking out compared with walking in.\n\nASK AFTERWARDS — 'what do you tell a child about who will hear about today, and what do you never promise?'",
"s2":    "YOU TAKE — the specific thank-you and the walk back to class.\n\nTHEY HOLD — what the child is told about next steps and who will hear what.\n\nWHY THAT SPLIT — a specific thank-you ('you kept going on the block puzzles even when they got tricky') is something you can practise at once. Next steps depend on the plan for feedback to parents and school, which your supervisor holds, and a wrong promise to a child is hard to undo.",
"s3":    "YOU RUN IT — close the whole session: end on a manageable activity, thank the child for something specific, explain next steps and who will be told, and return them to class, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — ending abruptly when time runs out, generic praise ('you did great'), promises you cannot keep ('I won't tell anyone'), and leaving the child to walk back alone into a class that is watching.\n\nSTEPPING IN LOOKS LIKE — 'before you go — do you remember what happens next?'",
"s4":    "YOU DO IT ALONE — plan the ending before the session starts, leave time for it, and close with a specific thank-you, a clear account of next steps and a return to class that protects the child's dignity in front of peers.\n\nPASS TEST — How they walk out\n\nEVIDENCE TO FILE — the session record's closing note on the child's presentation; a reflective line in Appendix 5. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a child who leaves near tears after a failed ceiling item, or a teacher who tells you later the child asked if they had 'failed the test'.",
"s5":    "YOU CAN TEACH IT — you can explain why the ending shapes the child's memory of the session, how to build a manageable final activity into a standardised battery without breaking it, and how to explain next steps at different ages without promising what you cannot deliver.\n\nWHEN IT GOES WRONG — you can say what to do when a session ends badly: tell the class teacher, check in with the child before you leave the school, and plan the next contact to start differently.",
"error": "Ending on the child's hardest failure because the time ran out.",
"feeds": "→ Feeds into 'Give feedback to parents on assessment findings', return visits, and the relationship the school keeps with the child after you leave.",
"evidence":"Session record · Appendix 5 · Log sheet tagged 5. Working with Others"},

# ── 5. WORKING WITH OTHERS · Communicate with school staff, SENCO and principal ──

("Communicate with school staff, SENCO and principal","Know who does what in this school"): {
"why":   "The Reference sheet: the principal decides and allocates; the SENCO holds the overview and usually the documentation; the class teacher delivers most of what you recommend; the SNA often knows the child best and is asked least. In Irish schools the SENCO role is usually a special education teacher (SET) or SET co-ordinator, and at post-primary there is often a Student Support Team — titles and roles vary by school. CORU SoP 5.13 is mapped here. Treating 'the school' as one entity is on the Reference sheet's error list.",
"s1":    "WATCH FOR — who your supervisor asks for what in the first visit to a school: who they book time with, who they ask for the Student Support File, who they ask about the child's day, and who they tell when they leave.\n\nWRITE DOWN — a one-page role map for each school: principal, deputy, SET co-ordinator, class teacher(s), SNA, secretary, and at post-primary year head and guidance counsellor. Names stay in the service record, not your Log.\n\nASK AFTERWARDS — 'in this school, who actually decides whether a recommendation happens?'",
"s2":    "YOU TAKE — building and updating the role map for each Cavan school on your caseload, and checking it with the SET co-ordinator.\n\nTHEY HOLD — the relationship with the principal, including agreeing the school's priorities for the service's time.\n\nWHY THAT SPLIT — mapping roles is information-gathering you can do from week one. The principal relationship covers the whole service's work in the school, not only your cases, and it is your supervisor's to hold.",
"s3":    "YOU RUN IT — make first contact with each role yourself for your own cases: book time through the right person, ask the SNA for their view, and brief the principal at the right point, with your supervisor reviewing who you approached.\n\nWHAT THEY ARE WATCHING FOR — going to the teacher you like rather than the one with the responsibility, and bypassing the SET co-ordinator or the principal on a decision that is theirs.\n\nSTEPPING IN LOOKS LIKE — 'before you agree that with the class teacher, has the SET co-ordinator seen it?'",
"s4":    "YOU DO IT ALONE — for each request (information, a meeting, a room, a change in provision) identify whose role it is in this particular school and approach them first.\n\nPASS TEST — You approached the right person\n\nEVIDENCE TO FILE — the school role map as a working paper and the case contact log. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a recommendation for extra SET time agreed with the class teacher, who cannot allocate it, and a principal who hears about it from a parent.",
"s5":    "YOU CAN TEACH IT — you can explain the typical division of roles in Irish primary and post-primary schools, how the NEPS Continuum of Support (Classroom Support, School Support, School Support Plus) maps onto who leads at each level, and why the SNA's knowledge is often overlooked.\n\nWHEN IT GOES WRONG — you can say what to do when you went to the wrong person: tell the right person directly, explain what was said, and do not leave the first person holding a commitment they cannot keep.",
"error": "Treating 'the school' as one entity and agreeing a change with someone who cannot deliver it.",
"feeds": "→ Feeds into 'Negotiate a shared referral question', consultation, and implementation of recommendations.",
"evidence":"School role map · contact log · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Communicate with school staff, SENCO and principal","Negotiate a shared referral question"): {
"why":   "The referral form often carries a request ('assess for dyslexia', 'is it ADHD?') rather than a question the psychologist can usefully answer. Consultation models treat agreeing the question as the first piece of work, not a formality (Wagner, 2000, Consultation: Developing a comprehensive approach to service delivery — read the source itself). CORU SoP 2.13 is mapped here. If school, parent and psychologist hold different questions, the report will satisfy none of them, and the school will read a careful formulation as 'the psychologist didn't give us an answer'.",
"s1":    "WATCH FOR — how your supervisor turns the school's request into a question: which follow-up questions they ask ('what would be different if this went well?', 'what have you tried?', 'what are you hoping the assessment tells you?'), and whether the parent's question is asked separately.\n\nWRITE DOWN — the original request in the referrer's words, the agreed question, and each step between them.\n\nASK AFTERWARDS — 'what do you do when the school's question and the parent's question are different?'",
"s2":    "YOU TAKE — reading the referral and the Student Support File beforehand and drafting two or three possible questions to bring to the planning meeting.\n\nTHEY HOLD — the planning conversation with the SET co-ordinator and teacher, including any reframing the school may resist.\n\nWHY THAT SPLIT — drafting questions from the file teaches you to see the gap between request and question. Reframing a school's request in the room needs a relationship and credibility you are still building.",
"s3":    "YOU RUN IT — lead the planning conversation for your own case, with your supervisor present, and end it by reading back the agreed question.\n\nWHAT THEY ARE WATCHING FOR — accepting the request unchanged, imposing your own question over the school's, and ending the meeting without saying the question aloud.\n\nSTEPPING IN LOOKS LIKE — 'can I just check we're all agreed what we're trying to find out — would you read it back for us?'",
"s4":    "YOU DO IT ALONE — take a school referral, explore the concern behind it with the teacher and SET co-ordinator, agree a question the assessment can answer, check it with the parent, and confirm it in writing.\n\nPASS TEST — Both parties recognise the question\n\nEVIDENCE TO FILE — the agreed question on the case file and in the written summary sent after the planning meeting. Log against 5. Working with Others and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — at feedback the teacher says 'but we wanted to know if he needs a special class', and nothing in your file shows that was discussed.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between a request and a referral question, show a peer the questions that uncover the concern behind a request, and explain why the parent's question is part of the negotiation, not an afterthought.\n\nWHEN IT GOES WRONG — you can say what to do when the question shifts mid-assessment: go back to the school and parent, renegotiate openly, and record the change rather than quietly answering a different question.",
"error": "Accepting 'assess for X' as the referral question without finding out what the school needs to know.",
"feeds": "→ Feeds into 'Ask whether the profile answers the referral question', choice of framework in Formulation, and 'Manage disagreement rather than avoiding it'.",
"evidence":"Case file — agreed question · written summary · Log sheet tagged 5. Working with Others"},

("Communicate with school staff, SENCO and principal","Manage disagreement rather than avoiding it"): {
"why":   "The Reference sheet: teachers sometimes disagree with findings, and sometimes they are right, so ask what they see and get to the specific observation behind the position. CORU SoP 2.13 is mapped here. Stone, Patton and Heen (Difficult Conversations, 2010) separate the 'what happened' conversation from the feelings and identity conversations running underneath it, which is useful when a finding implies a teacher's practice is part of the problem. Avoided disagreement does not go away; it resurfaces as recommendations that are politely never implemented.",
"s1":    "WATCH FOR — how your supervisor responds when a teacher or principal disagrees: whether they defend the finding or ask a question, and how they word a message that implicates provision (describe, don't evaluate; lead with shared purpose; offer one change).\n\nWRITE DOWN — the disagreement in neutral terms, the question your supervisor asked, and what the teacher's specific observation turned out to be.\n\nASK AFTERWARDS — 'when did a teacher's disagreement change your view of a case?'",
"s2":    "YOU TAKE — preparing for a likely disagreement: listing the evidence, the teacher's probable view, and a descriptive rather than evaluative way to say the difficult part.\n\nTHEY HOLD — the conversation itself where the message implicates provision or the relationship with the school is fragile.\n\nWHY THAT SPLIT — preparation is where most of the skill lies and can be done safely. A provision-level message delivered badly can, as the Reference sheet warns, end the relationship, and that relationship belongs to the service.",
"s3":    "YOU RUN IT — handle a disagreement yourself in a meeting on your own case, with your supervisor present but letting you lead.\n\nWHAT THEY ARE WATCHING FOR — repeating the finding more firmly, conceding to end the discomfort, and evaluative language ('the differentiation is inadequate') where description would do.\n\nSTEPPING IN LOOKS LIKE — 'can we hear more about what you're seeing in class? That might be something we didn't capture.'",
"s4":    "YOU DO IT ALONE — raise or respond to a disagreement directly: ask what the other person sees, find the specific observation behind their view, say what would change your view, and agree a next step even if you still differ.\n\nPASS TEST — The disagreement was addressed\n\nEVIDENCE TO FILE — the meeting note recording both positions and the agreed next step; a reflective entry in Appendix 5 without identifying details. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a meeting that ends with everyone nodding, followed by an email from the principal a week later disputing the report.",
"s5":    "YOU CAN TEACH IT — you can explain why asking 'what do you see?' works better than restating evidence, how to phrase a provision-level message descriptively, and when a disagreement should change your finding versus when it should be recorded as a difference.\n\nWHEN IT GOES WRONG — you can say what to do when a disagreement escalates: pause the meeting, acknowledge the strength of feeling, agree to return with more information, and bring it to supervision the same day.",
"error": "Defending a finding by restating it instead of asking what the teacher is seeing.",
"feeds": "→ Feeds into 'Maintain the relationship afterwards', consultation, and 'Identify where sources diverge and say so'.",
"evidence":"Meeting note · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Communicate with school staff, SENCO and principal","Maintain the relationship afterwards"): {
"why":   "The Reference sheet: send a short written summary of what was agreed within a day — it prevents misremembering, gives the school something to act from, and evidences record-keeping, which your placement review named as a development area (per the Reference sheet). CORU SoP 2.17 is mapped here. Schools notice psychologists who appear for the assessment and vanish; implementation depends on someone coming back to ask how it is going. Relationships after a disagreement need repair most of all, and they rarely repair themselves.",
"s1":    "WATCH FOR — what your supervisor does after a school meeting: whether a written summary goes out and how quickly, what is in it, and whether they return to the school to review — especially after a difficult conversation.\n\nWRITE DOWN — the structure of their follow-up summary (agreed actions, who, by when, next contact) and when they next contacted the school.\n\nASK AFTERWARDS — 'after a meeting that went badly, what's the first thing you do to repair it?'",
"s2":    "YOU TAKE — drafting the written summary within one working day of every school meeting on shared cases, for your supervisor to check before it goes.\n\nTHEY HOLD — the follow-up call or visit where a relationship has been strained.\n\nWHY THAT SPLIT — the written summary is a discrete, checkable task and the fastest way to build a reputation for reliability. Repair after strain needs the standing your supervisor has with the principal.",
"s3":    "YOU RUN IT — send the summary yourself and make the review contact on your own cases (a call or visit to ask how the recommendations are going), with your supervisor reviewing the summary and your plan.\n\nWHAT THEY ARE WATCHING FOR — summaries that arrive a week late, summaries that record what you said rather than what was agreed, and review contact that never happens because the case felt finished.\n\nSTEPPING IN LOOKS LIKE — 'when are you next in contact with that school about this child? Put it in the diary now.'",
"s4":    "YOU DO IT ALONE — send a written summary of agreed actions within a day, diarise a review, go back to the school to check implementation, and after any disagreement make a repair contact.\n\nPASS TEST — You went back\n\nEVIDENCE TO FILE — the follow-up summaries and the review contact note on the case file. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a school that, three months later, has not implemented the plan, and a file showing no contact since the feedback meeting. In Cavan (05/10/2026–18/12/2026) plan review dates that fall inside the placement.",
"s5":    "YOU CAN TEACH IT — you can explain why follow-up drives implementation, what a good one-page summary contains, how to plan review within a time-limited placement, and how to hand a school relationship over at the end of placement so it does not lapse.\n\nWHEN IT GOES WRONG — you can say what to do when you missed the follow-up: contact the school, acknowledge the delay without excuses, send the summary, and set the review date.",
"error": "No written follow-up, so the school acts on what it remembers rather than what was agreed.",
"feeds": "→ Feeds into implementation of recommendations, review in Intervention, and record-keeping in Ethical Practice.",
"evidence":"Follow-up summary · case contact note · Appendix 5 · Log sheet tagged 5. Working with Others"},

# ── 5. WORKING WITH OTHERS · Give feedback to parents on assessment findings ──

("Give feedback to parents on assessment findings","Prepare the structure before the meeting"): {
"why":   "The Reference sheet: parents wait through explanation for the verdict and hear almost none of it, so give the headline in the first two minutes, then the detail, then what it means, then what happens next. That order has to be decided before the meeting; under the pressure of a parent's face it will not be improvised. CORU SoP 2.1 is mapped here. Patients forget much of what clinicians tell them (Kessels, Journal of the Royal Society of Medicine, 2003 — check the figures before quoting), which is why a structure matters more than completeness.",
"s1":    "WATCH FOR — what your supervisor prepares before a feedback meeting: notes on one page, the headline written out, the order of topics, the room and who is attending, and anything they expect to be difficult.\n\nWRITE DOWN — their plan, and afterwards how closely the meeting followed it and where it departed.\n\nASK AFTERWARDS — 'what's the one sentence you want the parent to repeat to their partner tonight?'",
"s2":    "YOU TAKE — writing the one-page feedback plan for a case: headline, one evidenced strength, key findings in plain words, what it means, next steps, and the likely questions.\n\nTHEY HOLD — the headline wording where the finding is significant or distressing, and the decision on who attends (school staff, the young person).\n\nWHY THAT SPLIT — the plan is the thinking and is fully checkable in advance. How to word a diagnosis-level or distressing headline, and who should be in the room, carry relational risk your supervisor holds.",
"s3":    "YOU RUN IT — prepare the plan and lead the feedback meeting for your own case, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — a plan that follows the report's section order (test by test) instead of the parent's, and a headline that is buried after ten minutes of background.\n\nSTEPPING IN LOOKS LIKE — in the pre-meeting: 'read me your first two minutes.' In the meeting: 'maybe it would help to say where we got to overall, and then go through how.'",
"s4":    "YOU DO IT ALONE — before every feedback meeting, write a one-page plan with the headline, order, plain-language translations, next steps and expected questions, and follow it.\n\nPASS TEST — You knew the order you would take\n\nEVIDENCE TO FILE — the feedback plan as a working paper on the case file. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — forty minutes of subtest-by-subtest explanation and a parent who asks at the door 'so does he have dyslexia or not?'.",
"s5":    "YOU CAN TEACH IT — you can explain why the headline-first structure works, how to write a headline that is honest without being brutal, and how to adapt the plan when the young person or school staff are in the room.\n\nWHEN IT GOES WRONG — you can say what to do when the meeting departs from the plan (a parent arrives with a different concern, or becomes distressed): follow the parent, then return to the headline before the end so it is not lost.",
"error": "Walking in without a written headline and working through the report in section order.",
"feeds": "→ Feeds into 'Use plain language and check understanding', 'Lead with the child, not the scores', and 'Leave the parent with something concrete'.",
"evidence":"Feedback plan on case file · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Give feedback to parents on assessment findings","Use plain language and check understanding"): {
"why":   "The Reference sheet: plain language is a professional obligation — replace 'percentile' with a comparison to peers, 'working memory' with holding information in mind while doing something with it. If you cannot explain a finding without the term, you do not yet understand it well enough to report it. PSI Code 4.3.1 is mapped here. 'Does that make sense?' is on the Reference sheet's error list because almost everyone says yes. A parent who does not understand the findings cannot advocate for their child.",
"s1":    "WATCH FOR — every technical term your supervisor avoids or translates in a feedback meeting, and how they check understanding. Notice whether they ask the parent to put it in their own words, and what that reveals.\n\nWRITE DOWN — a glossary: each term (standard score, percentile, processing speed, phonological awareness, working memory) with your supervisor's plain-language version.\n\nASK AFTERWARDS — 'when a parent says it back, what are the misunderstandings you hear most often?'",
"s2":    "YOU TAKE — building your own plain-language glossary for the tests you use and rehearsing the translations with your supervisor before a meeting.\n\nTHEY HOLD — the understanding check at the end of the meeting, until you have seen it done several times.\n\nWHY THAT SPLIT — translating terms is preparation you can practise and have corrected. The teach-back check can feel like a test to a parent, and the tone of asking it is learned by watching.",
"s3":    "YOU RUN IT — deliver the findings in plain language and run the understanding check yourself ('when you tell his dad about today, what will you say?'), with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — jargon that slips back in under pressure, translations that are accurate but still abstract, and 'does that make sense?' used as the only check.\n\nSTEPPING IN LOOKS LIKE — your supervisor asking the parent 'what's your sense of what that means for him in class?' after you use a technical term.",
"s4":    "YOU DO IT ALONE — explain every finding without jargon, and before the end ask the parent to say back what they will tell someone else; correct anything that did not land.\n\nPASS TEST — You checked\n\nEVIDENCE TO FILE — the feedback plan (with your plain-language versions) and a case note recording the parent's summary in their words. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a parent who tells the school afterwards that the psychologist said their child was 'in the bottom percent for everything', from a profile that said nothing of the kind.",
"s5":    "YOU CAN TEACH IT — you can give a plain-language explanation for each score type and cognitive term you use, explain why teach-back is more reliable than a closed question, and adapt both for a parent with literacy difficulties or for whom English is an additional language, including when to use an interpreter.\n\nWHEN IT GOES WRONG — you can say what to do when the say-back reveals a major misunderstanding: thank them, re-explain the central point differently, check again, and put the headline in writing.",
"error": "Using technical language and checking understanding with 'does that make sense?'.",
"feeds": "→ Feeds into 'Leave the parent with something concrete', plain-language report writing, and the parent's own advocacy with the school.",
"evidence":"Feedback plan · case note · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Give feedback to parents on assessment findings","Lead with the child, not the scores"): {
"why":   "Leading with scores is the first item on the Reference sheet's error list. Parents know their child as a person, and a feedback meeting that opens with numbers tells them the psychologist met a profile, not their son or daughter. CORU SoP 5.27 is mapped here. Starting from something recognisable — how the child approached the tasks, what they said, what they enjoyed — earns the credibility that makes the harder findings believable, and it gives the parent evidence that you actually saw their child.",
"s1":    "WATCH FOR — how your supervisor opens a feedback meeting: the first thing they say about the child, whether it is a specific observation or a general comment, and how long before any number is mentioned.\n\nWRITE DOWN — the opening description word for word, and the parent's reaction to it.\n\nASK AFTERWARDS — 'how do you choose the detail about the child to open with, especially when the session was difficult?'",
"s2":    "YOU TAKE — writing the opening paragraph of the feedback plan: two or three specific observations of how the child engaged, drawn from your session record.\n\nTHEY HOLD — the transition from the child to the findings, where the tone shifts.\n\nWHY THAT SPLIT — describing the child from your notes tests how well you observed, and is safe to practise. The move into findings sets the emotional register for the rest of the meeting.",
"s3":    "YOU RUN IT — open the meeting with your description of the child, then move into the findings, keeping the child present throughout ('this is why he found the reading tasks so tiring'), with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — a description that could fit any child ('she was lovely to work with'), and findings reported as scores detached from anything the parent recognises.\n\nSTEPPING IN LOOKS LIKE — 'do you see that at home — the way she checks everything twice before she answers?'",
"s4":    "YOU DO IT ALONE — begin with a specific, evidenced description of the child as you met them, and tie each finding back to something the parent can recognise at home or in school.\n\nPASS TEST — The child is recognisable in your description\n\nEVIDENCE TO FILE — the feedback plan and the report's background and observation sections. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a parent who says 'that doesn't sound like him' in the first five minutes, after which nothing else you say is trusted.",
"s5":    "YOU CAN TEACH IT — you can explain why the child-first opening builds credibility for the findings, how to select observations that are specific and honest, and how to keep linking scores back to everyday behaviour.\n\nWHEN IT GOES WRONG — you can say what to do when the parent does not recognise your description: ask what they see, treat it as information about context (home vs school, one session vs years), and say so in the report.",
"error": "Opening with scores before the parent has recognised their child in anything you have said.",
"feeds": "→ Feeds into 'Name strengths specifically', 'Hold distress without rushing past it', and the parent's trust in the findings.",
"evidence":"Feedback plan · report — observations · Log sheet tagged 5. Working with Others"},

("Give feedback to parents on assessment findings","Name strengths specifically"): {
"why":   "The Reference sheet: lead with a strength, but only one you can evidence from the assessment — invented strengths are heard as consolation and undermine everything else you say. CORU SoP 1.3 is mapped here. 'He's a lovely boy' is not a strength finding; 'his vocabulary is well above what we'd expect for his age, and he used it to explain the picture tasks in real detail' is. Specific strengths also do work: they are what recommendations can build on.",
"s1":    "WATCH FOR — the strengths your supervisor names in feedback and whether each one is tied to evidence (a score, an observation, a teacher report) or is a general compliment.\n\nWRITE DOWN — each strength named and its evidence, and note any that were generic.\n\nASK AFTERWARDS — 'what do you do when the assessment genuinely didn't show a cognitive strength?'",
"s2":    "YOU TAKE — going through the file and your session record to list every evidenced strength: cognitive, attainment, approach to tasks, social, interests, and what other adults report.\n\nTHEY HOLD — deciding which strength leads, especially where the overall picture is of significant difficulty.\n\nWHY THAT SPLIT — finding strengths across sources is thorough, checkable work. Choosing the lead strength when the news is hard is a judgement about how the parent will hear it.",
"s3":    "YOU RUN IT — name the strengths in the feedback meeting, each with its evidence, and link at least one to a recommendation, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — generic praise, a strength the scores do not support, and strengths mentioned once at the start then dropped.\n\nSTEPPING IN LOOKS LIKE — 'and that persistence you saw on the puzzles — that's something the school can really use when they set up the reading programme.'",
"s4":    "YOU DO IT ALONE — name at least one real strength with the evidence for it, in plain words, and show how it connects to what happens next.\n\nPASS TEST — Not generic praise\n\nEVIDENCE TO FILE — the strengths section of the report and the feedback plan. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — 'he's a great kid and he tried really hard' as the only positive, followed by twenty minutes of difficulty, and a parent who hears the positive as a cushion.",
"s5":    "YOU CAN TEACH IT — you can explain why specificity is what makes a strength credible, where to look for strengths when test scores are uniformly low (approach to tasks, interests, relationships, adult reports), and how strengths should drive recommendations rather than decorate the report.\n\nWHEN IT GOES WRONG — you can say what to do when a parent dismisses a strength ('you're just saying that'): give the evidence for it, and do not inflate it to persuade them.",
"error": "Offering a strength the assessment does not support, so the parent discounts the real findings.",
"feeds": "→ Feeds into strengths-based recommendations, Intervention planning, and 'Leave the parent with something concrete'.",
"evidence":"Report — strengths · feedback plan · Log sheet tagged 5. Working with Others"},

("Give feedback to parents on assessment findings","Hold distress without rushing past it"): {
"why":   "Feedback can confirm something a parent has feared for years, or tell them something they did not expect; either can bring grief, anger, guilt or relief. Rushing to reassurance or to the recommendations tells them their reaction is in the way. CORU SoP 2.2 is mapped here. Baile and colleagues' SPIKES protocol for breaking bad news in medicine (The Oncologist, 2000) names responding to emotion as a distinct step before moving on; it was written for oncology, so adapt rather than transplant it.",
"s1":    "WATCH FOR — what your supervisor does when a parent becomes upset: the pause, the tone, whether they name the feeling, whether they offer tissues or water, how long before they return to the content, and how they check the parent is ready.\n\nWRITE DOWN — what was said at the moment of distress and what brought the meeting back — without identifying details in your Log.\n\nASK AFTERWARDS — 'how do you know when a parent is ready to hear the next part?'",
"s2":    "YOU TAKE — preparing for likely distress: which finding is most likely to land hard, what you will say if it does, and making sure there is time, privacy and tissues.\n\nTHEY HOLD — responding to the distress in the room.\n\nWHY THAT SPLIT — anticipating distress is planning you can do. Being with a distressed parent without rushing, while holding the professional frame, is learned by watching someone who does it well first.",
"s3":    "YOU RUN IT — lead the feedback meeting and respond yourself when the parent becomes upset, with your supervisor present and ready to support.\n\nWHAT THEY ARE WATCHING FOR — filling the silence, premature reassurance ('lots of children have this'), jumping to recommendations, and the opposite: losing the structure so the parent leaves without the key message.\n\nSTEPPING IN LOOKS LIKE — a hand signal to wait, or 'we don't have to go on right now — take whatever time you need.'",
"s4":    "YOU DO IT ALONE — when a parent is distressed, stop, acknowledge it in plain words, allow silence, and return to the content only when they indicate they are ready; offer a second meeting if needed.\n\nPASS TEST — You slowed down\n\nEVIDENCE TO FILE — the case note (including any offer of a follow-up meeting) and a supervision note on the meeting. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a parent in tears while you talk them through the recommendations, and a complaint afterwards that 'she just kept going'.",
"s5":    "YOU CAN TEACH IT — you can explain why pausing is a professional act and not a loss of control, how to name emotion without interpreting it, how cultural context shapes how distress is shown (Tervalon & Murray-García, 1998, on cultural humility), and when to end a meeting and reschedule.\n\nWHEN IT GOES WRONG — you can say what to do when you realise afterwards that you rushed: contact the parent, acknowledge it, offer another meeting, and take it to supervision.",
"error": "Rushing to reassurance or recommendations the moment a parent becomes upset.",
"feeds": "→ Feeds into 'Leave the parent with something concrete', relationship with the family, and your own wellbeing (Ethical Practice — Manage workload and your own wellbeing).",
"evidence":"Case note · supervision note · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Give feedback to parents on assessment findings","Leave the parent with something concrete"): {
"why":   "A parent who leaves with a feeling but no plan will ring the school, the GP or you within a week. They need to know what happens next, who does it, by when, and what they can do themselves. CORU SoP 2.16 is mapped here. In the Irish system, next steps usually sit on the NEPS Continuum of Support (Classroom Support, School Support, School Support Plus) or involve onward referral to HSE CDNT or CAMHS; parents rarely know what these mean, or how long waits may be, unless someone tells them.",
"s1":    "WATCH FOR — how your supervisor ends a feedback meeting: whether they summarise next steps, name who does what, say when the report will arrive, explain any onward referral and its process, and give the parent something written.\n\nWRITE DOWN — the next steps as your supervisor stated them, and what the parent was given to take away.\n\nASK AFTERWARDS — 'what do you tell a parent about a CDNT or CAMHS referral when you don't know how long the wait will be?'",
"s2":    "YOU TAKE — preparing the next-steps section of the feedback plan and a short written summary for the parent: actions, who, when, contacts, and what they can do at home.\n\nTHEY HOLD — anything involving onward referral or service commitments, until you know the local pathways and what the service can promise.\n\nWHY THAT SPLIT — a written next-steps summary is concrete and checkable. Referral pathways and waiting times are local knowledge; a wrong promise about a CDNT or CAMHS referral damages trust in the whole service.",
"s3":    "YOU RUN IT — close the feedback meeting yourself: summarise next steps, check the parent knows what happens next, and hand over the written summary, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — vague endings ('the school will be in touch'), promises about other services' timelines, and next steps that are all for professionals with nothing the parent can do.\n\nSTEPPING IN LOOKS LIKE — 'just so you've got it clearly — the three things that happen now are…'",
"s4":    "YOU DO IT ALONE — end every feedback meeting with next steps stated, a named person and timescale for each, when the report will arrive, one thing the parent can do, and a written summary to take away.\n\nPASS TEST — They know what happens next\n\nEVIDENCE TO FILE — the written next-steps summary and the case note. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a parent phoning the school a week later to ask whether a referral was made, and nobody knowing who was meant to do it.",
"s5":    "YOU CAN TEACH IT — you can explain the Continuum of Support levels and the main onward pathways (HSE CDNT, CAMHS, and Tusla where relevant) in plain words, how to talk about waiting lists without guessing, and why a parent needs one action of their own.\n\nWHEN IT GOES WRONG — you can say what to do when a next step does not happen: find out who held it, tell the parent honestly, and make sure it is picked up and recorded.",
"error": "Ending the meeting without saying who will do what, and by when.",
"feeds": "→ Feeds into implementation and review in Intervention, 'Maintain the relationship afterwards', and the parent's advocacy for their child.",
"evidence":"Written next-steps summary · case note · Log sheet tagged 5. Working with Others"},

}
