"""Working with Others (part B): case notes, the psychological report, and
adapting written communication to the audience.

Keyed (macro skill name, micro-skill name), in the micro.py format from HANDOVER.md.
"""

MICRO = {

# ── 5. WORKING WITH OTHERS · Keep case notes to service standard ──

("Keep case notes to service standard","Use the service's format and terminology"): {
"why":   "Every service records differently: a NEPS team, a CDNT and a CAMHS team each have their own headings, file structure and accepted abbreviations. The note has to be usable by the next person who opens the file, not only by you. CORU SoP 2.10 is the standard mapped here — read the full text on the Reference sheet, Part B. A note in your own format, or in shorthand only you understand, cannot be used once you leave, and in Cavan you leave on 18/12/2026 with cases still open.",
"s1":    "WATCH FOR — the template or headings your supervisor uses for each kind of contact (school visit, consultation, parent phone call, review meeting), where each kind of note sits in the file, and which abbreviations the service accepts. Check even ones that look standard, such as 'SS+' for School Support Plus or 'SSF' for Student Support File.\n\nWRITE DOWN — the headings in order, the document-naming convention, and a list of accepted abbreviations with what they stand for. Ask for the written records policy if the service has one.\n\nASK AFTERWARDS — 'if you were off sick tomorrow, what would a colleague need to find in this note to pick up the case?'",
"s2":    "YOU TAKE — drafting the note of a visit your supervisor led, on the service template, in the service's terms, and sending it to them the same day.\n\nTHEY HOLD — corrections to format and terminology, and the decision on what goes on the formal file and what stays a working paper.\n\nWHY THAT SPLIT — you learn a template by using it, and mistakes cost nothing if they are corrected before filing. What counts as part of the record is a service policy question, and you do not yet know this service's policy.",
"s3":    "YOU RUN IT — for your first few weeks in Cavan, write every note on your own cases in the service format and submit it for review before it is filed.\n\nWHAT THEY ARE WATCHING FOR — Roscommon habits or university assignment conventions carried into a new service's file; private shorthand; notes filed under the wrong heading or name, so that nobody can find them.\n\nSTEPPING IN LOOKS LIKE — 'what does \"SC re WM\" mean here? Would the new principal know, or the psychologist who takes this case after you?'",
"s4":    "YOU DO IT ALONE — every note is on the service template, filed in the right place, uses only accepted abbreviations, and can be read by a colleague who has never met the child.\n\nPASS TEST — Notes match the service standard\n\nEVIDENCE TO FILE — your supervisor's comment, in the supervision record, on a sample of your notes checked against the template. Do not copy notes into your own Log. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a colleague covering the case cannot tell from the file what was agreed at the last school meeting, because the note is in a format only you use.",
"s5":    "YOU CAN TEACH IT — you can explain to a new trainee that format is not bureaucracy. It serves continuity of care, handover, audit and subject access. You can show them where the template lives and walk them through one of your own anonymised notes line by line.\n\nWHEN IT GOES WRONG — you find your early notes used a different format. Do not rewrite or back-date them. If something needs clarifying, add a dated, signed entry marked as a later addition, and use the correct format from then on. Check the service policy on how to amend a record.",
"error": "Bringing the last service's format and private shorthand into a new service's file.",
"feeds": "→ Feeds into 'Record consent, contacts and decisions', 'Write the same day', and handover of open cases at the end of the Cavan placement.",
"evidence":"Supervision record — sample of notes reviewed · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Keep case notes to service standard","Store and transfer records lawfully"): {
"why":   "Psychological records hold health data, which is special category data under GDPR Article 9. The Data Protection Act 2018 adds further rules in Irish law. The Article 5 principles, including data minimisation and integrity and confidentiality, apply to every note, test protocol and draft report. PSI Code 1.2.6 and 1.2.7 and CORU SoP 1.13 are mapped here. The Reference sheet names records as the area where trainees most often slip through convenience: a draft on a personal laptop, a photo of a record form on a phone, a child's name in an email subject line. Each can be a personal data breach.",
"s1":    "WATCH FOR — where your supervisor keeps protocols between the school and the office, how they send a report to a school or family (secure email, portal, post, by hand), what goes in an email subject line, and what happens to rough notes once they are typed up.\n\nWRITE DOWN — the service's approved route for storing, sending and destroying each kind of record, and the name of the data protection contact. Do not rely on a remembered retention period — check the service policy for that.\n\nASK AFTERWARDS — 'what's the most common near miss you've seen with records here, and what should I do if I have one?'",
"s2":    "YOU TAKE — carrying and returning protocols by the approved route, sending documents only through service systems, and keeping a simple list of which files you have taken out of the office.\n\nTHEY HOLD — any sharing with other agencies (CDNT, CAMHS, Tusla), and any decision on retention or destruction of the formal record.\n\nWHY THAT SPLIT — handling records is a daily routine you must get right from day one. Sharing across agencies needs a lawful basis and a consent decision, and those belong to the service.",
"s3":    "YOU RUN IT — manage the records for your own cases from start to finish (storage, sending to school, destroying rough notes as the policy says), with your supervisor spot-checking.\n\nWHAT THEY ARE WATCHING FOR — shortcuts taken for convenience: a draft typed on your own laptop, protocols left in the car overnight, the child's name and school in a subject line, a WhatsApp message to a teacher about a pupil.\n\nSTEPPING IN LOOKS LIKE — 'where is that draft saved right now? Is that a service device?'",
"s4":    "YOU DO IT ALONE — every identifiable record is stored and moved only by approved routes. Nothing goes on a personal phone, laptop, cloud account or messaging app. Rough notes are destroyed as the policy says.\n\nPASS TEST — Nothing identifiable on a personal device\n\nEVIDENCE TO FILE — a line in the supervision record confirming your records practice was reviewed. Your own Log entries contain no identifiers. Log against 5. Working with Others and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a photo of a record form in your phone's camera roll, syncing to your personal cloud account.",
"s5":    "YOU CAN TEACH IT — you can explain special category data, the Article 5 principles, why a trainee's own device is outside the service's control, and why 'how long do we keep it?' is answered from the service's retention policy, not from memory.\n\nWHEN IT GOES WRONG — you send something to the wrong person, or lose a protocol. Tell your supervisor and the data protection contact the same day. Do not try to fix it quietly. The service has to assess it, and may have to notify the Data Protection Commission (GDPR Article 33).",
"error": "Working on an identifiable draft report on a personal laptop because the service device was slow.",
"feeds": "→ Feeds into 'Learn the records, IT and information governance policy', 'Record consent, contacts and decisions', and 6. Ethical Practice.",
"evidence":"Supervision record — records practice reviewed · Log sheet tagged 5. Working with Others and 6. Ethical Practice"},

("Keep case notes to service standard","Separate fact from opinion and label opinion"): {
"why":   "'Left his seat four times in twenty minutes' is observation. 'Was not engaged' is inference. The Reference sheet maps PSI Code 1.2.8 as requiring you to avoid conjecture and label opinion clearly; PSI Code 4.2.5 is also mapped — read both clauses in the Code itself. Notes can be disclosed through a subject access request, or read by Tusla or a court. Whoever reads them must be able to tell what you saw, what you were told and by whom, and what you concluded. Inference written as fact cannot be checked by the reader, and you cannot defend it either.",
"s1":    "WATCH FOR — the verbs in your supervisor's notes: 'observed', 'said', 'reported by' against 'appeared', 'in my view', 'suggests'. Notice that every reported statement is attributed to someone: teacher, parent, child or psychologist.\n\nWRITE DOWN — three sentences from an anonymised note, each marked as observed, reported (by whom) or opinion. Note the exact words that give each one away.\n\nASK AFTERWARDS — 'how do you write down a strong clinical impression without it reading as fact?'",
"s2":    "YOU TAKE — writing the observation section of a note as pure description: the behaviour, how often, how long, where, and what came before and after.\n\nTHEY HOLD — the interpretive sentence, and how it is worded and labelled.\n\nWHY THAT SPLIT — plain description is the discipline to learn first. Once you can write a paragraph with no inference leaking into it, adding a labelled opinion is safe, because the reader can see what it rests on.",
"s3":    "YOU RUN IT — write the full note using a visible split, such as 'Observed:', 'Reported by (role):' and 'Psychologist's view:'.\n\nWHAT THEY ARE WATCHING FOR — judgement words ('defiant', 'chaotic home', 'anxious mother') sitting in the factual part, and something a teacher told you written as though you saw it yourself.\n\nSTEPPING IN LOOKS LIKE — '\"Mum is overprotective\" — did you see that, did someone tell you, or is it your reading? Then which heading does it go under?'",
"s4":    "YOU DO IT ALONE — every note separates observed, reported and opinion, names the source of every reported statement, and labels your opinion as yours.\n\nPASS TEST — A reader can tell which is which\n\nEVIDENCE TO FILE — an anonymised extract reviewed in supervision, with the labelling noted in the supervision record. Log against 5. Working with Others and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — 'child is anxious about school due to difficulties at home' in a note, with no source and no label, read by the parent after a subject access request.",
"s5":    "YOU CAN TEACH IT — you can explain the three categories (observed, reported by a named person, your labelled opinion) and why a labelled opinion is professional while an unlabelled one is a liability. You can rewrite a peer's sentence to show the difference.\n\nWHEN IT GOES WRONG — a parent disputes a note. Check whether the disputed line was fact or opinion. Do not alter the original entry. Add a dated correction, marked as later, for a factual error. Record the parent's disagreement beside an opinion. Follow the service's procedure for correction requests.",
"error": "Writing an interpretation such as 'disengaged' or 'chaotic home' in the factual part of the note without a source or a label.",
"feeds": "→ Feeds into 'Avoid conjecture', into 'Identify where sources converge' in Assessment, and into writing a report the family can read.",
"evidence":"Anonymised extract reviewed in supervision · Appendix 5 · Log sheet tagged 5. Working with Others and 6. Ethical Practice"},

("Keep case notes to service standard","Avoid conjecture"): {
"why":   "Conjecture is a guess written down as if it were evidence: 'probably ADHD', 'likely something going on at home'. It is different from labelled opinion, because it goes beyond anything your evidence supports. PSI Code 1.2.8 is the clause mapped here. A guess about diagnosis in a case note can travel into the school's records, a SENO application or a family's view of their child. It can be disclosed, and it shapes how the next professional reads the child before they have met them.",
"s1":    "WATCH FOR — what your supervisor does with a hunch. Many record it as a question to explore, in the supervision record or a working hypothesis, and never as a conclusion in the case note.\n\nWRITE DOWN — where hypotheses are kept in this service (case note, working paper, supervision record) and the exact wording used for a hypothesis that has not been tested yet.\n\nASK AFTERWARDS — 'where do you write down a hypothesis you haven't tested yet, and what words do you use?'",
"s2":    "YOU TAKE — writing notes that stop at the evidence, and bringing your hunches to supervision to talk through.\n\nTHEY HOLD — deciding whether a hypothesis is strong enough to go on the file as a labelled question for further assessment, and how it is worded.\n\nWHY THAT SPLIT — hunches are useful and should be discussed. The risk is in where they are written down, and your supervisor knows what this service's file can safely carry.",
"s3":    "YOU RUN IT — write notes on your own cases, then reread each one before filing and take out any sentence that goes beyond what you saw, heard or were told.\n\nWHAT THEY ARE WATCHING FOR — diagnostic labels you are not in a position to give ('presents as autistic'), guesses about family life, and words like 'probably', 'likely' and 'seems to be due to'.\n\nSTEPPING IN LOOKS LIKE — 'what in this visit would let you write \"likely dyslexic\"? If nothing, where does that sentence belong?'",
"s4":    "YOU DO IT ALONE — reread every note for conjecture before filing. A hypothesis goes to supervision, or onto the file as a clearly labelled question for further assessment. It never goes in as a finding.\n\nPASS TEST — You did not speculate in the record\n\nEVIDENCE TO FILE — an anonymised before-and-after rewrite discussed in supervision, noted in the supervision record. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — 'possible ASD?' in a note after a single classroom visit, which the school then repeats in a letter home.",
"s5":    "YOU CAN TEACH IT — you can show a peer the difference between observation, labelled opinion that rests on evidence, and conjecture. You can rewrite a guess as a question for assessment, e.g. 'attention across settings to be explored through teacher rating scales and a second observation'.\n\nWHEN IT GOES WRONG — you find a guess on the file. Do not delete it. Add a dated, signed entry marked as a later addition, saying the comment was a hypothesis and not a finding. Tell your supervisor, and follow the service policy on amending records.",
"error": "Writing a possible diagnosis into a case note after one visit.",
"feeds": "→ Feeds into 'Separate fact from opinion and label opinion', into Formulation (hypotheses tested, not assumed), and into 'Include a limitations paragraph'.",
"evidence":"Before-and-after rewrite in supervision record · Log sheet tagged 5. Working with Others"},

("Keep case notes to service standard","Write the same day"): {
"why":   "Contemporaneous notes carry weight because they are written at or near the time, before memory starts filling gaps. CORU SoP 2.8 is the standard mapped here. The Reference sheet records that record keeping and the write-up of observations and consultations were named in your review. It says this one habit addresses that more than anything else in the skill. A note written on the day takes minutes. A note rebuilt a week later takes far longer, loses detail, and reads as rebuilt.",
"s1":    "WATCH FOR — when and where your supervisor writes notes: in the car, in the staffroom, in the last slot of the day. Notice roughly how long each one takes, and how they plan a school day to leave room for it.\n\nWRITE DOWN — the gap between contact and note for every note you see written, and the method (typed, dictated, handwritten then typed).\n\nASK AFTERWARDS — 'what's your rule when a day runs over and you can't write up before you leave?'",
"s2":    "YOU TAKE — writing your own note of every meeting you attend jointly, before you leave the school, and sending it to your supervisor that day.\n\nTHEY HOLD — the official note on their cases, and a comparison of your note with theirs.\n\nWHY THAT SPLIT — you build the habit when little rides on it. Comparing the two notes while memory is still fresh shows you exactly what you missed and what you added.",
"s3":    "YOU RUN IT — same-day notes on all your own cases, with your supervisor checking the dates of notes against the dates of contact.\n\nWHAT THEY ARE WATCHING FOR — a Friday batch of the week's notes, and notes dated the day of contact but written later, which misrepresents the record.\n\nSTEPPING IN LOOKS LIKE — 'this note is for Tuesday. When did you actually write it? Then that's the date that goes on it.'",
"s4":    "YOU DO IT ALONE — plan every school day with a writing slot after each contact. The Reference sheet suggests eight minutes in the car before you drive off. If same-day truly fails, write it the next working day and record both the contact date and the date written.\n\nPASS TEST — Notes are contemporaneous\n\nEVIDENCE TO FILE — dates on the file, checked by your supervisor, plus a weekly tally in your Log of notes written the same day and later (numbers only, no identifiers). Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — five school visits written up from memory on a Sunday evening, each dated as if written on the day.",
"s5":    "YOU CAN TEACH IT — you can explain why contemporaneity matters, both legally and for accuracy, and show a peer how to fit writing time into a rural school-visit day with long drives between schools.\n\nWHEN IT GOES WRONG — you have a backlog. Write the oldest notes first, each with the true date of writing. Tell your supervisor. If the backlog comes from the workload rather than from habit, raise it as a workload issue.",
"error": "Writing up a week's notes in one batch and dating them as though they were written on the day.",
"feeds": "→ Feeds into 'Record consent, contacts and decisions', 'Raise workload before it becomes a problem', and the review development area on record keeping.",
"evidence":"Dated notes on file · Log tally of same-day notes · Log sheet tagged 5. Working with Others"},

("Keep case notes to service standard","Record consent, contacts and decisions"): {
"why":   "The file should let anyone rebuild what you did, with whom, when, on what consent, and what was decided. CORU SoP 1.15 is the standard mapped here. The Reference sheet lists 'recording what was discussed but not what was decided' as a common error. In a complaint or review, a file that holds the conversation but not the decision, who owns it and the date leaves the service unable to show what was agreed. It also leaves the school unable to show it did what was agreed.",
"s1":    "WATCH FOR — whether your supervisor keeps a contact log (date, who, how, why) apart from the narrative notes, and how they end every meeting note: the action, who owns it, and the date.\n\nWRITE DOWN — the closing structure they use, e.g. 'Agreed: … / By whom: … / By when: … / Review: …', and how phone calls and emails are logged.\n\nASK AFTERWARDS — 'when a school says \"we never agreed that\", what does the file need to show?'",
"s2":    "YOU TAKE — keeping the contact log for a shared case, and drafting the decisions section of each meeting note.\n\nTHEY HOLD — confirming decisions with the school and parents, and settling any disagreement about what was agreed.\n\nWHY THAT SPLIT — logging contacts is mechanical and teaches you the rhythm of a case. Confirming decisions with other people is consultation, and a mistake there affects the relationship with the school.",
"s3":    "YOU RUN IT — on your own cases: a consent note of what was explained, every contact logged (phone calls and emails included), and every meeting closed by reading back the decisions, owners and dates to the group before it ends.\n\nWHAT THEY ARE WATCHING FOR — phone calls with parents that never reach the file, and 'discussed next steps' with no step named.\n\nSTEPPING IN LOOKS LIKE — 'who is running the reading intervention, from when, and when do we check it?'",
"s4":    "YOU DO IT ALONE — the file shows consent and what was explained, every contact, and every decision with an owner, a date and a review point.\n\nPASS TEST — The file shows what you did and when\n\nEVIDENCE TO FILE — the contact log and meeting notes on the case file, and an anonymised count of contacts in your Log. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — the file shows three school visits but not the phone call in which the parent withdrew consent for a classroom observation.",
"s5":    "YOU CAN TEACH IT — you can set out the minimum a file needs: consent and what was explained, every contact, and each decision with owner, date and review. You can explain why reading decisions back at the end of a meeting prevents most later disputes.\n\nWHEN IT GOES WRONG — you find a contact that was never recorded. Add it now, dated today and marked as a later entry, giving the date of the original contact and why it was missed.",
"error": "Recording what was discussed at a meeting but not what was decided, by whom, or by when.",
"feeds": "→ Feeds into 'Record what was explained, not just that consent was given', 'Write recommendations a teacher could act on Monday', and review meetings on the Continuum of Support.",
"evidence":"Contact log · meeting notes · Appendix 5 · Log sheet tagged 5. Working with Others"},

# ── 5. WORKING WITH OTHERS · Produce the psychological report to countersigning standard ──

("Produce the psychological report to countersigning standard","Know the countersigning standard before drafting"): {
"why":   "Countersigning means your supervisor puts their name to your report. The Reference sheet calls that a higher bar than 'accurate', because they are staking their registration on your reasoning. Each supervisor and service has a standard: template version, section order, how scores are reported, what goes in an appendix, what is sent with the draft, and turnaround. CORU SoP 2.10 is mapped here. The Reference sheet points to NEPS templates and house style. Ask for the current version rather than reusing Roscommon's. Finding the standard out from a returned draft wastes a draft and a week.",
"s1":    "WATCH FOR — ask for two or three recent anonymised reports your supervisor wrote or countersigned. Look at section order, length, how scores and confidence intervals are shown, whether raw scores appear, and how recommendations are laid out.\n\nWRITE DOWN — a one-page house-standard checklist: template version, headings, score conventions, what goes with the draft (raw data, scoring), and the expected turnaround.\n\nASK AFTERWARDS — 'what makes you send a trainee's draft back unread, rather than edit it?'",
"s2":    "YOU TAKE — drafting the house-standard checklist and bringing it to supervision in the first week in Cavan.\n\nTHEY HOLD — the standard itself, and any exceptions for particular cases, referrers or report types.\n\nWHY THAT SPLIT — you can only aim at a standard you can see. Writing it down makes your supervisor's unspoken expectations explicit, and gives you both something to point to when a draft comes back.",
"s3":    "YOU RUN IT — before each draft, say the standard back to your supervisor: template, length, main reader, due date, and what you will send with it.\n\nWHAT THEY ARE WATCHING FOR — assuming the Roscommon template or a university assignment format applies, and starting to draft before asking.\n\nSTEPPING IN LOOKS LIKE — 'before you start: what is this one for, who reads it first, and when do I get it?'",
"s4":    "YOU DO IT ALONE — ask for the standard at the start of every placement and with every new supervisor, keep the checklist, and draft to it.\n\nPASS TEST — You asked at the start\n\nEVIDENCE TO FILE — the checklist (no identifiers) with the Placement Plan, and the supervision record of the conversation. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a first draft in the wrong template, with scores reported differently from the service's convention, returned before the reasoning was even read.",
"s5":    "YOU CAN TEACH IT — you can explain why countersigning is a higher bar than accuracy, and give a new trainee the questions to ask a supervisor in week one.\n\nWHEN IT GOES WRONG — two psychologists you work with hold different standards. Name it in supervision and agree which applies to which case. Do not blend the two into a report that meets neither.",
"error": "Drafting the first report of a placement in the previous service's template without asking.",
"feeds": "→ Feeds into 'Proofread against the service template', every other report micro-skill, and the Cavan Placement Plan.",
"evidence":"House-standard checklist with Placement Plan · supervision record · Log sheet tagged 5. Working with Others"},

("Produce the psychological report to countersigning standard","Proofread against the service template"): {
"why":   "Most errors a supervisor catches are not reasoning errors. They are another child's name left over from a previous report, a score copied wrongly from the record form, a percentile that does not match the standard score, the wrong pronoun, or the wrong age at testing. A parent who spots one stops trusting the whole report, and a wrong score can change what a school or SENO does. CORU SoP 2.8 is the standard mapped here. Proofreading is a method, not a final skim.",
"s1":    "WATCH FOR — how your supervisor checks a report before it leaves: whether they check every score against the protocol, check names and dates in a separate pass, or read it aloud.\n\nWRITE DOWN — their checking sequence as a numbered list, and which classification descriptors the service uses for each test.\n\nASK AFTERWARDS — 'what's the worst error you've seen reach a family, and how was it caught?'",
"s2":    "YOU TAKE — a score-by-score check of one of your supervisor's draft reports against the record forms and scoring output, before they send it.\n\nTHEY HOLD — sign-off, and the decision on any discrepancy you find.\n\nWHY THAT SPLIT — checking someone else's report trains your eye. You are not blind to text you did not write, the way every author is to their own.",
"s3":    "YOU RUN IT — proofread your own draft in separate passes: (1) names, pronouns, date of birth, age at testing, school, class; (2) every score, confidence interval, percentile and descriptor against the protocol; (3) template headings and order; (4) read aloud for sense.\n\nWHAT THEY ARE WATCHING FOR — a previous report reused as a starting point (the usual source of wrong names), and descriptors taken from a different test's classification system.\n\nSTEPPING IN LOOKS LIKE — 'your text says \"average\" but the table says 78. Which test's descriptors are you using?'",
"s4":    "YOU DO IT ALONE — every draft goes to your supervisor already checked in separate passes against the protocols and the template, with raw data and scoring attached.\n\nPASS TEST — No score or name errors\n\nEVIDENCE TO FILE — your supervisor's feedback on the draft, and your proofreading checklist. Log against 5. Working with Others and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a report reaches a family with another child's first name in paragraph four.",
"s5":    "YOU CAN TEACH IT — you can show a peer the multi-pass method, and explain why scores are checked against the protocol, not against your own earlier table, which may already hold the error.\n\nWHEN IT GOES WRONG — an error is found after the report is issued. Tell your supervisor at once. Issue a corrected version marked as corrected, dated, with the reason, as the service policy says. If personal data went to the wrong person, treat it as a possible data breach.",
"error": "Building a new report from an old one and leaving the previous child's name in the text.",
"feeds": "→ Feeds into 'Score the phonological composites correctly', 'Store and transfer records lawfully', and requiring only house-style edits (Reference sheet grade 5).",
"evidence":"Supervisor feedback on draft · proofreading checklist · Log sheet tagged 5. Working with Others and 1. Assessment"},

("Produce the psychological report to countersigning standard","Include a tool rationale"): {
"why":   "The reader needs to know why these tools were chosen for this referral question, not only which were used. A rationale shows the assessment was planned from the question rather than run as a default battery. It also lets a later psychologist judge what the results can and cannot answer. CORU SoP 3.2 is the standard mapped here. Without a rationale, a report that used a cognitive battery for a question about peer relationships has no defence.",
"s1":    "WATCH FOR — whether your supervisor's reports explain why each tool was chosen, and how: one line per tool, or a paragraph linking tools to hypotheses.\n\nWRITE DOWN — the chain they use: referral question → hypothesis → tool → what the result could tell us. Note also where they explain choosing not to use a tool.\n\nASK AFTERWARDS — 'when do you decide not to do a cognitive assessment, and how do you explain that to the school?'",
"s2":    "YOU TAKE — drafting a rationale table for a shared case: each tool, the question or hypothesis it addresses, whether its age norms fit, and any limitation for this child (language, sensory, cultural).\n\nTHEY HOLD — the choice of tools, and whether each is within your agreed competence.\n\nWHY THAT SPLIT — writing the rationale shows whether you understand why the tools were chosen. The choice itself has consequences, and competence levels, that you do not yet carry.",
"s3":    "YOU RUN IT — choose the tools for your own case, write the rationale before you administer anything, and defend it in supervision.\n\nWHAT THEY ARE WATCHING FOR — a rationale written after the fact to justify a default battery; tools named with no link to the question; norms that may not fit the child. Check the manual's norm sample rather than assuming.\n\nSTEPPING IN LOOKS LIKE — 'which hypothesis does this subtest test? What would you conclude if it came out average?'",
"s4":    "YOU DO IT ALONE — the report states, for every tool, why it was used for this question, plus any reason its results should be read with caution for this child.\n\nPASS TEST — It is there\n\nEVIDENCE TO FILE — the rationale section of the report, named in your Appendix 5 entry. Log against 5. Working with Others and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — an 'assessments administered' list of five tools with no reason given for any, one of them normed on an age range that does not include the child.",
"s5":    "YOU CAN TEACH IT — you can explain the hypothesis-testing logic of choosing tools (Sattler, 2018, report-writing chapters; read the source for detail) and show a peer how one referral question leads to a short battery.\n\nWHEN IT GOES WRONG — you realise after administering that a tool was the wrong fit. Say so in the rationale and the limitations, give its results less weight, and do not build conclusions on them.",
"error": "Listing the tools administered with no reason linking any of them to the referral question.",
"feeds": "→ Feeds into 'Know your publisher competence level for every tool', 'Include a limitations paragraph', and 'Judge which source to weight and why'.",
"evidence":"Report — rationale section · Appendix 5 · Log sheet tagged 5. Working with Others and 1. Assessment"},

("Produce the psychological report to countersigning standard","Include an integration section"): {
"why":   "The Reference sheet puts it plainly. The findings section can be organised by source, but the formulation cannot. It must name where sources agree, where they conflict, and what you make of the conflict, and this is the biggest single difference between a grade 3 and a grade 5 report. Report-writing texts agree: organise the synthesis by theme or question, not by instrument (Lichtenberger, Mather, Kaufman & Kaufman, 2004). CORU SoP 5.27 and 5.32 are mapped here. Without integration, your supervisor cannot see your reasoning, so cannot countersign it.",
"s1":    "WATCH FOR — in your supervisor's reports, where the findings end and the integration begins, and whether each integration paragraph draws on more than one source.\n\nWRITE DOWN — the paragraph pattern: a claim about the child → evidence from two or more sources → any conflict named → what it means for the referral question.\n\nASK AFTERWARDS — 'when your test results and the teacher's account point opposite ways, how do you write that so the family doesn't feel disbelieved?'",
"s2":    "YOU TAKE — drafting the integration section of a shared case, working from the source-by-domain grid you built in Assessment.\n\nTHEY HOLD — the conclusions, and the wording of any conflict between a parent's account and a teacher's.\n\nWHY THAT SPLIT — drafting integration is where you find out whether you understood the case. Wording conflict between people the family knows has consequences for relationships your supervisor holds.",
"s3":    "YOU RUN IT — write the integration section for your own case. Your supervisor reads it on its own, without the findings, to see if it stands.\n\nWHAT THEY ARE WATCHING FOR — the findings repeated in the order collected, joined by 'furthermore'; conflicting evidence quietly dropped; paragraphs that open with a test name.\n\nSTEPPING IN LOOKS LIKE — 'cover the findings section. Does this still tell me what you think is going on, and why?'",
"s4":    "YOU DO IT ALONE — the report has an integration section organised by question or theme, where each paragraph makes a claim, cites more than one source, and names any conflict.\n\nPASS TEST — Not a list of tests\n\nEVIDENCE TO FILE — the report, with the integration section named in your Appendix 5 entry. Log against 5. Working with Others and 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a section headed 'Integration' that repeats the index scores in the order the subtests were given.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between findings and integration, and take a peer's test-by-test summary through a rewrite into claim-first paragraphs.\n\nWHEN IT GOES WRONG — the sources will not integrate. Say so. Name the competing readings, say which evidence supports each, and state what further information would decide between them.",
"error": "An integration section that lists findings in the order they were collected.",
"feeds": "→ Feeds into 'Name the framework in the formulation', 'Write recommendations a teacher could act on Monday', and 'Identify where sources diverge and say so'.",
"evidence":"Report — integration section · Appendix 5 · Log sheet tagged 5. Working with Others and 1. Assessment"},

("Produce the psychological report to countersigning standard","Name the framework in the formulation"): {
"why":   "A formulation without a named framework is the author's intuition, and the reader cannot check it. Naming the framework tells the reader how the evidence was organised and what kind of explanation to expect. The Reference sheet's reading for this macro is the problem-analysis framework (Monsen & Frederickson, 2008, as cited there; the original is Monsen, Graham, Frederickson & Cameron, 1998, Educational Psychology in Practice — check the citation before using it). CORU SoP 5.29 is mapped here. Grade 4 on the Reference sheet requires a named framework.",
"s1":    "WATCH FOR — whether your supervisor names a framework in the formulation, where it appears (a heading, the first sentence, a citation), and whether the paragraphs follow its structure.\n\nWRITE DOWN — the framework used in each report you read, the citation, and one sentence on why it fitted that case.\n\nASK AFTERWARDS — 'do you name the framework even in a short report? Do schools and parents notice?'",
"s2":    "YOU TAKE — proposing a framework for a shared case with one line of reasoning, and drafting the formulation under its headings.\n\nTHEY HOLD — whether the framework fits, and the final formulation.\n\nWHY THAT SPLIT — proposing and drafting show whether you can use a framework or can only name it. Whether it truly fits the case is a judgement your supervisor models first.",
"s3":    "YOU RUN IT — choose, name and cite the framework in your own report, and write the formulation using its steps.\n\nWHAT THEY ARE WATCHING FOR — a framework named in the first sentence and then ignored, so the paragraphs still follow the order of the tests, or a citation copied from someone else's report without being read.\n\nSTEPPING IN LOOKS LIKE — 'you've named problem analysis. Show me where in this section the problem is defined and the hypotheses are tested.'",
"s4":    "YOU DO IT ALONE — the formulation names a framework, cites it in APA style in the text and the reference list, and follows its structure.\n\nPASS TEST — Named and cited\n\nEVIDENCE TO FILE — the formulation section of the report, named in your Appendix 5 entry. Log against 5. Working with Others and 2. Formulation.\n\nWHAT FAILURE LOOKS LIKE — 'using an interactive factors approach' in one line, with no citation and nothing afterwards that follows the approach.",
"s5":    "YOU CAN TEACH IT — you can explain what naming a framework gives the reader, and show a peer how the same evidence reads differently under two frameworks named in the UCD Handbook.\n\nWHEN IT GOES WRONG — halfway through, the framework does not fit the case. Say so in supervision, switch deliberately, and name the change rather than blending two frameworks without saying so.",
"error": "Naming a framework in the formulation and then writing a formulation that does not follow it.",
"feeds": "→ Feeds into 'Name and cite it in the report' and 'Use the framework's own structure' in Formulation, and into 'Include a limitations paragraph'.",
"evidence":"Report — formulation section · Appendix 5 · Log sheet tagged 5. Working with Others and 2. Formulation"},

("Produce the psychological report to countersigning standard","Include a limitations paragraph"): {
"why":   "The Reference sheet is blunt: a report with no limitations section is not at countersigning standard. The limitations must be specific. Not 'all assessment has limitations', but, for example, that a test was given in the child's second language, so the verbal index is likely to underestimate their reasoning. PSI Code 2.3.1 is the clause mapped here. Specific limitations show competence. A generic paragraph shows a template, and a supervisor putting their name to the report will notice.",
"s1":    "WATCH FOR — the limitations paragraph in each of your supervisor's reports: its position, its length, and whether each point is tied to this child and this assessment.\n\nWRITE DOWN — every limitation named across three reports, sorted into types: language, attention or fatigue on the day, a missing informant, norms, a single observation, a tool adapted from standard procedure.\n\nASK AFTERWARDS — 'which limitation do you most often see missed in trainee reports?'",
"s2":    "YOU TAKE — drafting the limitations paragraph for a shared case from your session notes, the adaptation record and your list of sources not reached.\n\nTHEY HOLD — the final wording, and how strongly each limitation should qualify the conclusions.\n\nWHY THAT SPLIT — collecting limitations is systematic work you can do. Judging how much each one weakens a conclusion is a skill your supervisor demonstrates first.",
"s3":    "YOU RUN IT — write the limitations paragraph for your own report and link each limitation to the conclusion it affects.\n\nWHAT THEY ARE WATCHING FOR — a paragraph copied from the last report, and limitations stated but never linked to the conclusions they weaken.\n\nSTEPPING IN LOOKS LIKE — 'you say the teacher form wasn't returned. Which conclusion does that make less certain?'",
"s4":    "YOU DO IT ALONE — every report has a limitations paragraph, specific to this child and this assessment, with each limitation linked to the conclusion it affects.\n\nPASS TEST — Every report, no exceptions\n\nEVIDENCE TO FILE — the reports, and a running tally in your Log of reports with a specific limitations paragraph (numbers only). Log against 5. Working with Others and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — 'the results should be interpreted with caution' as the whole paragraph, word for word as in your last three reports.",
"s5":    "YOU CAN TEACH IT — you can take the Reference sheet's second-language example and show a peer how to turn a generic caution into a specific one, and why that specific version is what makes the conclusions trustworthy.\n\nWHEN IT GOES WRONG — a limitation comes to light after the report is issued. Discuss it with your supervisor and issue a dated addendum if it changes how a conclusion should be read.",
"error": "Pasting the same generic caution into every report instead of naming this child's specific limitations.",
"feeds": "→ Feeds into 'Include a limitations paragraph in every report' in Ethical Practice, 'State what you did not assess and what that limits', and 'State the effect on validity in the report'.",
"evidence":"Reports · Log tally · Appendix 5 · Log sheet tagged 5. Working with Others and 6. Ethical Practice"},

("Produce the psychological report to countersigning standard","Write recommendations a teacher could act on Monday"): {
"why":   "The class teacher's question is 'what do I do on Monday?' (Reference sheet). Recommendations are the part most readers turn to first. The Reference sheet requires them to be addressed to roles and set at a level of the NEPS Continuum of Support (Classroom Support, School Support, School Support Plus). CORU SoP 5.34 is mapped here. A recommendation such as 'provide a structured literacy programme' gives nobody a task, a time or a resource, so it is unlikely to happen, and there is nothing to review.",
"s1":    "WATCH FOR — how your supervisor words recommendations: whether each one names who does it, what exactly, how often, with what resource, from when, and how it will be reviewed. Notice how they link it to the school's Student Support File.\n\nWRITE DOWN — two or three recommendations you think work, and the parts that make them usable.\n\nASK AFTERWARDS — 'how do you know if a school can actually deliver what you recommend before you write it?'",
"s2":    "YOU TAKE — drafting recommendations for a shared case, grouped by Continuum level and by role (class teacher, special education teacher, parent, child).\n\nTHEY HOLD — checking that the school can realistically resource each one, and the final list.\n\nWHY THAT SPLIT — drafting shows whether your recommendations flow from the formulation. Knowing what a particular school can deliver comes from a relationship with that school that your supervisor holds.",
"s3":    "YOU RUN IT — write the recommendations for your own report and test them: give them to the class teacher or a non-psychologist and ask what they would do first.\n\nWHAT THEY ARE WATCHING FOR — jargon, recommendations that do not follow from the formulation, and wish lists no school could resource.\n\nSTEPPING IN LOOKS LIKE — 'who does this, how often, starting when, and what does it look like on a Tuesday morning in third class?'",
"s4":    "YOU DO IT ALONE — every recommendation names a role, a specific action, frequency, a resource the school has or can get, a start date and a review point, set at a Continuum level.\n\nPASS TEST — Specific, resourced, dated\n\nEVIDENCE TO FILE — the recommendations section, and a note of the readability test you ran. Log against 5. Working with Others and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — 'the school should consider social skills support' in a report, and at review no one can say who was meant to deliver it.",
"s5":    "YOU CAN TEACH IT — you can take a vague recommendation and rebuild it with role, action, frequency, resource, date and review, and explain why the Continuum level matters for the school's planning.\n\nWHEN IT GOES WRONG — at review, a recommendation was not carried out. Find out why (resource, clarity, buy-in) before recommending it again, and rewrite it so it can be delivered.",
"error": "Recommendations with no named role, no Continuum level and no date, so nobody owns them and nothing can be reviewed.",
"feeds": "→ Feeds into 'Link the profile to what the school can deliver', Intervention planning, and 'Judge who will read this and what they need'.",
"evidence":"Report — recommendations · readability test note · Appendix 5 · Log sheet tagged 5. Working with Others and 3. Intervention"},

("Produce the psychological report to countersigning standard","Quote the child's own words"): {
"why":   "Children have the right to express their views in matters affecting them, and to have those views given due weight (UNCRC Article 12). Lundy (2007, British Educational Research Journal) argues that voice alone is not enough: the view needs an audience and has to have influence. A report that describes a child only through scores and adult accounts is about the child without the child being in it. Quoting their own words, with their knowledge, puts the child in the report as a person, and often gives the recommendation that matters most.",
"s1":    "WATCH FOR — how your supervisor gathers the child's views (a conversation, a drawing, scaling, a sort of what helps and what is hard) and where those words appear in the report.\n\nWRITE DOWN — the methods used at different ages, and how quotations are introduced and placed near the recommendations they inform.\n\nASK AFTERWARDS — 'do you tell the child their words will be in the report? What do you leave out, and why?'",
"s2":    "YOU TAKE — gathering the child's views in a session, recording their exact words at the time, and proposing which quotations belong in the report.\n\nTHEY HOLD — deciding whether any quotation could expose or embarrass the child if read by peers, parents or staff, and the final choice.\n\nWHY THAT SPLIT — recording the child's words accurately is yours from the start. Judging how a quotation will land with each reader is a risk judgement your supervisor models first.",
"s3":    "YOU RUN IT — include the child's own words in your report, with the child told beforehand that what they say may be written down and who will read it.\n\nWHAT THEY ARE WATCHING FOR — a token quotation at the end with no link to the recommendations, words paraphrased into adult language, and quotations that reveal more than the child agreed to.\n\nSTEPPING IN LOOKS LIKE — 'she said \"I hate reading out loud\". Which recommendation answers that?'",
"s4":    "YOU DO IT ALONE — the report quotes the child's own words, with their knowledge, in a section on their views, and at least one recommendation responds to what they said.\n\nPASS TEST — The child appears as a person\n\nEVIDENCE TO FILE — the child's-views section of the report, named in your Appendix 5 entry. Log against 5. Working with Others and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a twelve-page report on a ten-year-old in which the only mention of the child's view is 'X was cooperative throughout'.",
"s5":    "YOU CAN TEACH IT — you can explain Article 12 and Lundy's model, and show age-appropriate ways to get views from a child who is non-speaking, very young or reluctant (visual scales, choices, AAC, observation of preferences).\n\nWHEN IT GOES WRONG — a parent objects to a quotation, or the child regrets saying something. Talk it through with your supervisor, and weigh removing or rewording it against the child's right to be heard.",
"error": "Describing the child only through test scores and adult reports, with no trace of their own view.",
"feeds": "→ Feeds into 'Include the child's own self-report where age-appropriate', 'Include the child's construction of the problem', and 'Check the young person could read what is written about them'.",
"evidence":"Report — child's views section · Appendix 5 · Log sheet tagged 5. Working with Others and 6. Ethical Practice"},

# ── 5. WORKING WITH OTHERS · Adapt written communication to the audience ──

("Adapt written communication to the audience","Judge who will read this and what they need"): {
"why":   "The same findings must reach a parent, a class teacher, a SENCO, a SENO and sometimes another professional, and each reads for a different question (Reference sheet). A parent asks what it means for their child and what happens now. A teacher asks what to do on Monday. A SENO asks what is being applied for and what evidence supports it. Another professional asks what you found and how confident you are. CORU SoP 5.27 is mapped here. Writing without deciding who the primary reader is produces a document that serves nobody fully.",
"s1":    "WATCH FOR — how your supervisor decides who a document is for before writing: a report, a letter to a family, a referral to a CDNT or CAMHS, a note to a principal. Notice what changes in each: length, vocabulary, what comes first.\n\nWRITE DOWN — for each document you see, the primary reader, the question that reader brings, and where in the document it is answered.\n\nASK AFTERWARDS — 'when a report goes to the family and the school, who do you write it for first?'",
"s2":    "YOU TAKE — before drafting any shared document, writing one line at the top: primary reader, their question, and other readers.\n\nTHEY HOLD — the call when readers' needs conflict, e.g. a parent who will read a sentence the SENO needs for an application.\n\nWHY THAT SPLIT — naming the reader is a habit you can build at once. Balancing readers with competing needs involves relationships and service processes your supervisor knows.",
"s3":    "YOU RUN IT — for your own documents, name the primary reader in supervision before drafting, and show where their question is answered in the first page.\n\nWHAT THEY ARE WATCHING FOR — writing for your supervisor or your university marker rather than the actual reader, and forgetting that the family will read everything.\n\nSTEPPING IN LOOKS LIKE — 'who reads this first, and what do they want to know by the end of page one?'",
"s4":    "YOU DO IT ALONE — every document you write has a named primary reader, their question answered early, and other readers accounted for.\n\nPASS TEST — You can name the primary reader\n\nEVIDENCE TO FILE — the reader line on your drafts (kept with working papers) and supervision discussion. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a referral letter to a CDNT written like a parent summary, missing the developmental and assessment detail the receiving team needs to accept it.",
"s5":    "YOU CAN TEACH IT — you can set out the Reference sheet's reader-by-reader questions and show a peer how the same finding is placed differently for each.\n\nWHEN IT GOES WRONG — a reader says the document did not help them. Ask what question they came with, and fix the layering (summary, body, recommendations) rather than adding more text.",
"error": "Writing every document for your supervisor or marker rather than for the person who will act on it.",
"feeds": "→ Feeds into 'Change register between family and professional audiences' and 'Write recommendations a teacher could act on Monday'.",
"evidence":"Draft with reader line · supervision record · Log sheet tagged 5. Working with Others"},

("Adapt written communication to the audience","Change register between family and professional audiences"): {
"why":   "A single register cannot serve a parent and a consultant at once (Reference sheet). CORU SoP 2.2 and 5.25 both require communication adapted to the audience. A family letter full of index names and percentiles leaves a parent unsure what it means for their child. A referral to CAMHS written in a warm, informal register can be read as lacking the detail needed to triage it. Harvey (2006, Journal of Clinical Psychology) examined what makes psychological reports clear to readers — read it for the specific variables.",
"s1":    "WATCH FOR — two documents your supervisor wrote about the same child, one to a family and one to another professional. Compare sentence length, technical terms, how scores are described, and what is said first.\n\nWRITE DOWN — pairs of sentences that say the same thing in the two registers, e.g. a standard score with confidence interval against 'within the range we would expect for his age'.\n\nASK AFTERWARDS — 'what do you leave out of the family letter that must go in the professional one, and why?'",
"s2":    "YOU TAKE — drafting the family version of a document your supervisor wrote for professionals, or the other way round.\n\nTHEY HOLD — checking that the meaning did not shift between versions, and that nothing in the family version is softened into inaccuracy.\n\nWHY THAT SPLIT — rewriting is the exercise that builds the skill. The check matters because the commonest failure is a family version that is kinder but no longer true.",
"s3":    "YOU RUN IT — write both versions for your own case and bring them side by side to supervision.\n\nWHAT THEY ARE WATCHING FOR — a family version that is the professional version with a glossary added; a professional version that has lost precision; the two versions contradicting each other.\n\nSTEPPING IN LOOKS LIKE — 'read me the first paragraph of each. If the parent later read the professional one, would it feel like the same child?'",
"s4":    "YOU DO IT ALONE — produce family and professional versions that read differently in register, but say the same thing in substance, with no contradiction between them.\n\nPASS TEST — Two versions read differently\n\nEVIDENCE TO FILE — both versions on the case file, and an anonymised pair of sentences in your supervision notes. Log against 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a family letter reading 'FSIQ 82 (12th percentile), VCI relative weakness', with no explanation of what that means for the child.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to translate a finding between registers without changing its meaning, and why the family can read the professional version too, so it must also be respectful.\n\nWHEN IT GOES WRONG — the family reads the professional version and is upset by a phrase. Look at what the phrase implied. Change the wording if it was disrespectful or unclear, not if it was accurate and simply unwelcome, and talk it through with them.",
"error": "Sending a family the professional report with a glossary attached and calling it the family version.",
"feeds": "→ Feeds into 'Produce an accessible or plain-language version' and feedback meetings with families.",
"evidence":"Both versions on case file · supervision notes · Appendix 5 · Log sheet tagged 5. Working with Others"},

("Adapt written communication to the audience","Produce an accessible or plain-language version"): {
"why":   "Some readers need more than a change of register: a parent with literacy difficulties, a parent reading in a second language or through an interpreter, a parent with an intellectual disability, or a young person. The Equal Status Acts 2000–2018 prohibit discrimination in providing services, including on grounds of disability and race — read the Acts for the exact duty on reasonable accommodation. NALA's plain English guidance is a practical standard. The Reference sheet records a report issued in Ukrainian at Boyle as strong evidence of this skill.",
"s1":    "WATCH FOR — how your supervisor finds out a family's reading and language needs before writing (a question at intake, the school's knowledge, the parent's own request), and what they produce: a plain-language summary, a translated report, easy-read, or a feedback meeting with a written summary to follow.\n\nWRITE DOWN — the service's arrangements for interpreters and translation, and any accessible templates it uses.\n\nASK AFTERWARDS — 'how do you ask a parent about their reading without embarrassing them?'",
"s2":    "YOU TAKE — drafting the plain-language version: short sentences, common words, no idiom, one idea per sentence, headings that are questions the parent would ask.\n\nTHEY HOLD — arranging and paying for translation or interpreters, and checking the plain version still says what the full report says.\n\nWHY THAT SPLIT — plain-language drafting is a writing skill you can practise now. Translation involves service budgets and approved providers.",
"s3":    "YOU RUN IT — produce the accessible version for your own case, and state in the report that it was prepared with the reader's needs in mind (Reference sheet).\n\nWHAT THEY ARE WATCHING FOR — idiom that will not survive an interpreter ('on the right track', 'a bit all over the place'), long sentences, and a plain version that drops the key finding.\n\nSTEPPING IN LOOKS LIKE — 'read that sentence as if it were going through an interpreter. What comes out the other side?'",
"s4":    "YOU DO IT ALONE — where a reader needs it, produce a plain-language or accessible version, and record in the report and case file that you did and why.\n\nPASS TEST — It exists where it is needed\n\nEVIDENCE TO FILE — the accessible version on the case file and the sentence in the report recording the adaptation. Log each translated or accessible report you produce, with no identifying details. Log against 5. Working with Others and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a parent who reads little English receives a twelve-page report and signs off on recommendations they could not read.",
"s5":    "YOU CAN TEACH IT — you can explain plain-language principles (NALA guidance), the difference between plain language, easy-read and translation, and why the adaptation is recorded in the report.\n\nWHEN IT GOES WRONG — you learn after issue that the parent could not read the report. Offer a meeting, with an interpreter if needed, go through it verbally, follow up with an accessible written summary, and record it.",
"error": "Using idiom and long sentences in a report that will be read through an interpreter.",
"feeds": "→ Feeds into 'Check the young person could read what is written about them', 'Obtain assent from the child in their own language', and feedback with families.",
"evidence":"Accessible version on file · report sentence recording the adaptation · Appendix 5 · Log sheet tagged 5. Working with Others and 6. Ethical Practice"},

("Adapt written communication to the audience","Check the young person could read what is written about them"): {
"why":   "The young person is a reader of their own report, now or later. They may read it at home, see it at a review meeting or request their records. They have a right of access to their personal data under GDPR Article 15, and the service will have a policy on requests made by or for a child — check it. UNCRC Article 12 is mapped here. A teenager who reads that they are 'low functioning' or 'oppositional' learns how adults see them. Writing as though they will read it is both respectful and good practice.",
"s1":    "WATCH FOR — whether your supervisor writes with the young person in mind as a reader: how they describe difficulties, whether strengths come first, whether the young person is addressed directly or talked about.\n\nWRITE DOWN — phrases they avoid and what they use instead, e.g. 'finds reading effortful' rather than 'poor reader'.\n\nASK AFTERWARDS — 'have you ever gone through a report with a teenager? What did they react to?'",
"s2":    "YOU TAKE — rereading a shared draft as the young person, marking every phrase that would hurt, confuse or label them, and suggesting alternatives.\n\nTHEY HOLD — deciding what stays because it must be said, and whether to share the report or a version of it directly with the young person.\n\nWHY THAT SPLIT — reading as the young person is a skill of perspective you can practise now. Whether and how to share with a minor involves consent, guardians and service policy.",
"s3":    "YOU RUN IT — for your own report, reread it as the young person before sending, and where it fits, prepare a short version for them in their own terms.\n\nWHAT THEY ARE WATCHING FOR — deficit labels, third-person language about a young person in the room, and difficulties described without strengths or context.\n\nSTEPPING IN LOOKS LIKE — 'if Aoife read this sentence at fifteen, what would she take from it about herself?'",
"s4":    "YOU DO IT ALONE — every report is reread from the young person's point of view before issue, with the language adjusted so it is accurate and respectful. Where appropriate, a version for the young person is prepared.\n\nPASS TEST — You considered them as a reader\n\nEVIDENCE TO FILE — the version for the young person, if made, and a note of the reread in supervision. Log against 5. Working with Others and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a post-primary student reads 'significant cognitive deficits' about themselves in a report left on the school's shared drive.",
"s5":    "YOU CAN TEACH IT — you can explain why a young person is a reader of their own report (Article 12; right of access), show strengths-based wording that is still accurate, and show a peer how to make a one-page version for a young person.\n\nWHEN IT GOES WRONG — a young person is upset by what they read. Meet them with your supervisor, listen, explain what was meant, and change wording that was unnecessarily hurtful, recording the change as a dated amendment.",
"error": "Writing a report about a teenager in language you would not be willing to read out to them.",
"feeds": "→ Feeds into 'Quote the child's own words', 'Obtain assent from the child in their own language', and Working with Others with young people and families.",
"evidence":"Young person's version if made · supervision note · Appendix 5 · Log sheet tagged 5. Working with Others and 6. Ethical Practice"},

}
