"""Research: search and critically appraise evidence, cite evidence for
recommendations, and state how a recommendation would be evaluated.

Keyed (macro skill name, micro-skill name), in the micro.py format from HANDOVER.md.
"""

MICRO = {

# ── 8. RESEARCH · Search and critically appraise evidence ──

("Search and critically appraise evidence","Frame an answerable question from a real referral"): {
"why":   "A referral arrives as a worry ('he can't read', 'she won't come in'), not as a question you can search. The Reference sheet maps CORU SoP 5.42 here. Evidence-based medicine made the structured question its first step (Richardson, Wilson, Nishikawa & Hayward, 1995, the 'well-built clinical question'; Sackett et al., 1996, BMJ), and the Reference sheet uses the same population–intervention–comparison–outcome shape. Search on the worry and you get thousands of hits and no answer; search on a framed question and twenty minutes is enough.",
"s1":    "WATCH FOR — the moment in a planning conversation where your supervisor turns 'what can we do about his reading?' into something narrower: which age, which difficulty (decoding, fluency or comprehension), which kind of help, delivered by whom, measured how.\n\nWRITE DOWN — the referral worry in the school's own words, then the question your supervisor would actually look up, set out as population, intervention, comparison, outcome.\n\nASK AFTERWARDS — 'what did you already know about this child that made you narrow the question that way?'",
"s2":    "YOU TAKE — drafting the structured question from an anonymised referral form before the planning meeting, in one sentence, with each of the four parts named.\n\nTHEY HOLD — whether the question is the right one. Often the referral question is not the real question, and that is a formulation judgement.\n\nWHY THAT SPLIT — writing the four parts is a technical skill you can practise at once. Deciding that the school asked about behaviour but the real issue is language is case judgement, and that stays with your supervisor until your formulations are trusted.",
"s3":    "YOU RUN IT — for each new Cavan referral, write the answerable question in the case note before you search anything, and bring it to supervision.\n\nWHAT THEY ARE WATCHING FOR — a question too broad to search ('interventions for anxiety'), a question that assumes the answer ('does a weighted blanket help'), or one with no outcome anyone could measure.\n\nSTEPPING IN LOOKS LIKE — 'if you found the perfect paper, what age would the children be, what would they be compared with, and what would have changed?'",
"s4":    "YOU DO IT ALONE — every case where you intend to recommend something has a written question naming the population (age band and difficulty), the intervention, the comparison and a measurable outcome.\n\nPASS TEST — Specific enough to search\n\nEVIDENCE TO FILE — the question as the first line of your search note, and the same question at the head of the Appendix 5 research entry. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — you type 'dyslexia interventions' into a database, get several thousand records, read the first three abstracts and stop.",
"s5":    "YOU CAN TEACH IT — you can take a peer's vague referral and, out loud, turn it into a four-part question, explaining why each part narrows the search and why the outcome must be something a school could observe. You can show why 'what works for autism?' has no answer and 'what helps a nine-year-old autistic child tolerate transitions between lessons?' might.\n\nWHEN IT GOES WRONG — the search returns nothing. Widen one part at a time, usually the population first (age band, then diagnosis), and note each change so you know what the evidence is actually about.",
"error": "Searching on the referral worry instead of a framed question, so the search is unbounded and the answer is whatever came up first.",
"feeds": "→ Feeds into 'Search a database rather than a search engine', 'Judge applicability to this child in this context', and 2. Formulation.",
"evidence":"Search note on case file · Appendix 5 research entry · Log sheet tagged 8. Research"},

("Search and critically appraise evidence","Search a database rather than a search engine"): {
"why":   "The Reference sheet's order is syntheses first (Cochrane, Campbell Collaboration, the EEF Teaching and Learning Toolkit, What Works Clearinghouse), then PsycINFO or ERIC with a structured question, with Google Scholar kept for chasing a known paper. CORU SoP 5.41 is mapped here. A general search engine ranks by popularity and advertising, not by study quality, so the first page is full of commercial programme sites and testimonials — exactly the weak evidence the Reference sheet warns is sold to schools.",
"s1":    "WATCH FOR — where your supervisor goes first when a school asks 'is this programme any good?': a synthesis, a database, a NEPS good practice guide, or a colleague. Notice whether they check the EEF Toolkit or a Cochrane or Campbell review before looking at single studies.\n\nWRITE DOWN — the databases the service or UCD gives you access to, how to reach them through the UCD library proxy, and any NEPS or Department guidance your supervisor treats as the starting point.\n\nASK AFTERWARDS — 'when you have only twenty minutes, what is your search order?'",
"s2":    "YOU TAKE — running the search: synthesis sources first, then PsycINFO and ERIC with your four-part question turned into search terms, with limits set for age and date.\n\nTHEY HOLD — which synthesis or guidance the service treats as authoritative, and what counts as good enough to put in front of a school.\n\nWHY THAT SPLIT — the mechanics of database searching are yours from your UCD training. What a service is prepared to recommend on the strength of a search is a professional standard your supervisor sets.",
"s3":    "YOU RUN IT — for each case, search at least one synthesis source and one bibliographic database before recommending anything, and bring a one-page summary to supervision.\n\nWHAT THEY ARE WATCHING FOR — a search that began and ended in Google or Google Scholar, a programme's own website cited as evidence, or a single hit treated as the literature.\n\nSTEPPING IN LOOKS LIKE — 'is there a systematic review on this? Did you check the Toolkit or Campbell before you went to single studies?'",
"s4":    "YOU DO IT ALONE — you search syntheses first, then at least one of PsycINFO or ERIC, using subject headings as well as free text, and you use Google Scholar only to find the full text of a paper you already know about.\n\nPASS TEST — PsycINFO, ERIC, not Google\n\nEVIDENCE TO FILE — the search note (databases, date searched, terms, number of hits) attached to the Appendix 5 research entry. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — a school report recommends a programme on the strength of its publisher's website and a blog post.",
"s5":    "YOU CAN TEACH IT — you can explain why a database indexes peer-reviewed work by subject and a search engine does not, why a synthesis beats a single study, and how to use thesaurus terms (PsycINFO's index terms, ERIC descriptors) as well as keywords. You can demonstrate a twenty-minute search on a peer's question.\n\nWHEN IT GOES WRONG — the proxy fails or you are in a school with no access. Note the question, search later, and do not recommend from memory in the meantime; tell the school the recommendation will follow once you have checked the evidence.",
"error": "Treating the first page of a general search engine as the literature, and ending up citing a publisher's own website.",
"feeds": "→ Feeds into 'Record the search terms and databases used', 'Appraise quality rather than accepting the first result', and 'Cite evidence for recommendations'.",
"evidence":"Search note on case file · Appendix 5 research entry · Log sheet tagged 8. Research"},

("Search and critically appraise evidence","Record the search terms and databases used"): {
"why":   "A search you cannot repeat is a search nobody can check, including you in six months. CORU SoP 5.43 is mapped here. Systematic review reporting standards (PRISMA 2020, Page et al., 2021, BMJ) ask for the full search to be reported so others can reproduce it; a placement search does not need that rigour, but it needs the same principle. The Reference sheet's advice is a note per topic — question, what you searched, what you found, what you concluded — because you will be asked the same questions across a career.",
"s1":    "WATCH FOR — whether your supervisor keeps any record of past searches or reading on common referral topics (a folder, a shared drive, a reading list), and how they decide a previous search is still current.\n\nWRITE DOWN — a template for your own search note: question, date, databases, exact search string, limits applied, number of hits, number read in full, what you concluded.\n\nASK AFTERWARDS — 'which questions do you get asked so often that you wish you'd kept a note the first time?'",
"s2":    "YOU TAKE — keeping the search note for every search you run on a case, completed on the day you search.\n\nTHEY HOLD — any shared resource the service keeps, and whether your note is good enough to add to it.\n\nWHY THAT SPLIT — the record of your own search is plainly your job. Adding to a service's shared reading is a decision about what the whole team will rely on, which is not yours to make alone on placement.",
"s3":    "YOU RUN IT — keep a search log across the Cavan placement, one entry per search, and bring it to supervision when a recommendation depends on it.\n\nWHAT THEY ARE WATCHING FOR — notes that say 'searched PsycINFO for social skills' with no terms, date or limits, so the search cannot be rerun and the gaps cannot be seen.\n\nSTEPPING IN LOOKS LIKE — 'if I ran your search tomorrow, would I get the same papers? Which terms, which years, which age limit?'",
"s4":    "YOU DO IT ALONE — every search behind a recommendation has a note someone else could rerun: databases, date, exact string with Boolean operators, limits, hits, and which papers you read in full.\n\nPASS TEST — Reproducible\n\nEVIDENCE TO FILE — the search note, kept with no child identifiers, attached to or summarised in the Appendix 5 research entry. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — a supervisor asks why you did not find a well-known review, and you cannot say what you searched, so nobody can tell whether the gap was in the literature or in your search.",
"s5":    "YOU CAN TEACH IT — you can explain why the exact string matters (a missing synonym or truncation symbol changes the results), why the date matters (the literature moves), and why a search note with no identifiers can be reused across cases and shared.\n\nWHEN IT GOES WRONG — you realise a past recommendation rested on a search you did not record. Rerun it now, record it properly, and check whether the answer still holds; if it does not, raise it in supervision.",
"error": "Keeping no record of what was searched, so the search cannot be checked, repeated or reused.",
"feeds": "→ Feeds into 'Log the search as an Appendix 5 research entry', 'Cite current sources rather than the familiar ones', and 8. Research.",
"evidence":"Search log (no identifiers) · Appendix 5 research entry · Log sheet tagged 8. Research"},

("Search and critically appraise evidence","Appraise quality rather than accepting the first result"): {
"why":   "Most of what a search returns will not stand up. The Reference sheet gives five questions: design, sample, comparison, effect size, and who funded it and who developed the programme. CORU SoP 5.41 and 5.3 are mapped here. The CASP checklists give a free, design-specific version of the same discipline. Evaluations run or commissioned by a programme's developer have been reported to show larger effects than independent ones (for education, see Wolf, Morrison, Inns, Slavin & Risman, 2020 — read the paper before quoting a figure). Accept the first result and you may recommend something that technically works and practically does not.",
"s1":    "WATCH FOR — how your supervisor reacts to a programme a school is already using or has been sold: what they ask first, whether they look at who ran the evaluation, and whether they ask about effect size or only 'is there research on it'.\n\nWRITE DOWN — the five Reference sheet questions, and the CASP checklist that fits each design you meet (randomised trial, systematic review, qualitative study, cohort).\n\nASK AFTERWARDS — 'what's the most common weak evidence schools show you, and how do you tell them without offending anyone?'",
"s2":    "YOU TAKE — reading the full paper, not the abstract, and completing the relevant CASP checklist or the five questions for each study a recommendation rests on.\n\nTHEY HOLD — the overall judgement about how confident the evidence lets the service be, and how that is said to a school.\n\nWHY THAT SPLIT — appraising a single paper is a skill your UCD training has given you. Weighing a body of evidence and putting it in words a principal will accept is judgement built over years of practice.",
"s3":    "YOU RUN IT — for each recommendation, appraise the two or three key studies behind it and give your supervisor a short note: design, sample, comparison, effect size, funder or developer, and your verdict.\n\nWHAT THEY ARE WATCHING FOR — statistical significance treated as practical importance; a pre-post design with no control accepted as proof; outcome measures built by the programme's own developer; a small sample making large claims.\n\nSTEPPING IN LOOKS LIKE — 'compared with what? And who wrote the evaluation?'",
"s4":    "YOU DO IT ALONE — you read the method section, name the design, check sample and comparison, look for an effect size, check who developed and funded the work, and reject what does not stand up. For effect-size benchmarks, Cohen's (1988) small, medium and large are a rough guide only; check the current EEF Toolkit entry rather than quoting a figure from memory.\n\nPASS TEST — You judged the study, not the abstract\n\nEVIDENCE TO FILE — the completed appraisal note with the Appendix 5 research entry. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — you recommend a programme because an abstract said 'significant improvement', and the study turns out to be twelve children with no control group, evaluated by the author.",
"s5":    "YOU CAN TEACH IT — you can explain to a teacher, without jargon, why 'significant' does not mean 'big', why a comparison group matters, and why a developer's own evaluation is a starting point and not a verdict. You can walk a peer through one CASP checklist on a real paper.\n\nWHEN IT GOES WRONG — you find the evidence for something already in a report is weaker than you said. Raise it in supervision, agree how to correct it with the school, and adjust the evaluation line so the school can see whether it is working for this child.",
"error": "Reading the abstract, seeing 'significant', and never checking design, comparison, effect size or who ran the evaluation.",
"feeds": "→ Feeds into 'Judge applicability to this child in this context', 'Say where the evidence is thin', and 'Cite evidence for recommendations'.",
"evidence":"Appraisal note (CASP or five questions) · Appendix 5 research entry · Log sheet tagged 8. Research"},

("Search and critically appraise evidence","Judge applicability to this child in this context"): {
"why":   "A well-run trial tells you what worked on average, for those participants, delivered by those staff. It does not tell you it will work for this child in this school. Cartwright and Hardie (2012, Evidence-based policy, Oxford University Press) set out this gap between 'it worked there' and 'it will work here'. CORU SoP 5.4 is mapped here (read the clause for its wording). Ignore applicability and you recommend a programme built for groups of eight with a trained tutor to a two-teacher rural school with one SET and no one to run it.",
"s1":    "WATCH FOR — the questions your supervisor asks about a school before recommending anything: who would deliver it, how often, with what training, in what room, alongside what else the child already gets under the Continuum of Support.\n\nWRITE DOWN — the gap between the study and this case: the sample's age, language, difficulty and setting, set against the child's; and the delivery the study used, set against what this school can realistically provide.\n\nASK AFTERWARDS — 'when do you recommend something with good evidence that the school can only half deliver, and when do you choose something weaker that they'll actually do?'",
"s2":    "YOU TAKE — writing the comparison between the study conditions and this child's situation: age band, needs, co-occurring difficulties, school size, staffing, and the level of the Continuum the child is at.\n\nTHEY HOLD — the trade-off between strength of evidence and feasibility, and the conversation with the principal about capacity.\n\nWHY THAT SPLIT — setting out the differences is careful reading you can do now. Deciding what a school can carry depends on knowing the school, its history with the service, and what has been tried before.",
"s3":    "YOU RUN IT — for each evidence-based recommendation, add two or three lines to your working notes: how this child and school differ from the study, and what adaptation, if any, is needed.\n\nWHAT THEY ARE WATCHING FOR — a programme recommended at a dose or group size the school cannot provide; evidence from a different age band or population applied without comment; adaptations that remove the part that made it work.\n\nSTEPPING IN LOOKS LIKE — 'the trial ran three sessions a week with trained staff. Who is going to do that here?'",
"s4":    "YOU DO IT ALONE — you check the study sample against the child (age, needs, language, setting) and the delivery against the school's capacity, and your recommendation says what has been adapted and why.\n\nPASS TEST — Transferability considered\n\nEVIDENCE TO FILE — the transferability lines in your working notes, and a sentence in the report recommendation where adaptation matters. Log against 8. Research and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — the report recommends a well-evidenced programme, the school cannot resource it, it is delivered at a fraction of the dose, and at review everyone concludes the child 'did not respond'.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between whether something works (efficacy in a trial) and whether it will work here (fit, fidelity and capacity), and why fidelity to the active ingredients matters more than fidelity to every detail. Fixsen et al. (2005, implementation research synthesis) is a useful starting point for the implementation side.\n\nWHEN IT GOES WRONG — the school has adapted a programme beyond recognition. Find out what they kept, agree which parts are essential, and build the review so you can tell whether the reduced version is doing anything.",
"error": "Recommending the best-evidenced option without asking whether this school, with this staffing, can deliver it as it was tested.",
"feeds": "→ Feeds into 'Say where the evidence is thin', 'State how a recommendation would be evaluated', and 3. Intervention.",
"evidence":"Working notes — transferability · Report — recommendations · Log sheet tagged 8. Research and 3. Intervention"},

("Search and critically appraise evidence","Log the search as an Appendix 5 research entry"): {
"why":   "A search that is done but not recorded does not count towards the Research competency, and on placement the Research competency is mostly evidenced through this kind of practice-based work rather than a separate project. The Reference sheet maps 'Handbook Appendix 5' here — check the current UCD Placement Handbook for the exact headings and expectations of an Appendix 5 entry before writing one; do not rely on memory or on this row. The entry is yours to write: this row gives structure and prompts, not text to submit.",
"s1":    "WATCH FOR — how your supervisor links a piece of reading to a case decision when they talk it through, and what they think a good research entry shows: the question, the search, the appraisal, and what changed as a result.\n\nWRITE DOWN — the Appendix 5 headings from the current Handbook, and one example (from your Roscommon entries or a peer's, anonymised, with permission) of an entry your supervisor thought was strong.\n\nASK AFTERWARDS — 'when you read a trainee's research entry, what tells you they actually used the evidence and didn't just find it?'",
"s2":    "YOU TAKE — writing the entry: the question, how you searched, what you found, how you appraised it, what you concluded, and how it shaped what you recommended. The wording is yours.\n\nTHEY HOLD — feedback on whether the entry shows applied research competence, and the countersignature where the Handbook requires it.\n\nWHY THAT SPLIT — the entry is your own evidence of learning and must be in your own words. Your supervisor judges it; they do not write it, and neither does this workbook.",
"s3":    "YOU RUN IT — aim for at least one research entry tied to a real Cavan case in the first half of the placement, completed within a week of the search while it is fresh, and bring it to supervision.\n\nWHAT THEY ARE WATCHING FOR — an entry that is a literature summary with no case link; child identifiers; a search with no record; a conclusion that never says what you then did differently.\n\nSTEPPING IN LOOKS LIKE — 'what did you recommend because of this reading that you wouldn't have otherwise?'",
"s4":    "YOU DO IT ALONE — each entry names the question, the search (reproducibly), the appraisal, the conclusion and the effect on your practice, with no child or school identifiers, in your own words, under the Handbook headings.\n\nPASS TEST — It is recorded\n\nEVIDENCE TO FILE — the Appendix 5 entry itself, with the search note behind it kept on your own file. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — at the end of Cavan you have run several good searches and none of them is in Appendix 5, so the Research competency looks unevidenced.",
"s5":    "YOU CAN TEACH IT — you can explain to a new trainee why a research entry is about using evidence rather than listing it, and show the chain from question to search to appraisal to recommendation to review, using an anonymised example of your own.\n\nWHEN IT GOES WRONG — you reach the end of a block with no entries. Go back through your search log, choose the search that most changed a recommendation, and write it up now while you can still reconstruct it. Do not write up a search you cannot evidence, and do not use generated text for the entry.",
"error": "Doing the searching but never writing it up, so the Research competency has no evidence at the end of the placement.",
"feeds": "→ Feeds into 8. Research, 'Cite evidence for recommendations', and the Research evidence reviewed at end-of-placement evaluation.",
"evidence":"Appendix 5 research entry (trainee's own words) · search log · Log sheet tagged 8. Research"},

# ── 8. RESEARCH · Cite evidence for recommendations ──

("Cite evidence for recommendations","Attach a source to every substantial recommendation"): {
"why":   "A cited recommendation tells the reader the claim is not only your opinion and lets them check it; the Reference sheet names this as one of the features that moves a report from a 3 to a 5. CORU SoP 5.4 is mapped here. The Reference sheet's rule is to cite the intervention, the framework and any claim about what typically works, at synthesis level, and not to pad: two or three well-chosen citations in a school report, not fifteen. An uncited recommendation invites the question 'says who?', and you may not be in the room when it is asked.",
"s1":    "WATCH FOR — which recommendations in your supervisor's reports carry a citation and which do not. Usually the intervention and the framework do; routine classroom strategies and test scores do not.\n\nWRITE DOWN — where the citation sits (in the sentence, in a footnote, in a short reference list at the end), how many a typical school report carries, and which sources your supervisor cites often.\n\nASK AFTERWARDS — 'how do you decide which recommendation is substantial enough to need a source?'",
"s2":    "YOU TAKE — adding the citation to each substantial recommendation in your draft, drawn from your own search note, and building the reference list.\n\nTHEY HOLD — whether the service's report template carries references at all, and how many are appropriate for this reader.\n\nWHY THAT SPLIT — finding and attaching the source is your research work. Some services keep school reports reference-light for readability, and that is a house style your supervisor knows and you do not yet.",
"s3":    "YOU RUN IT — draft every Cavan report with a source attached to each intervention and framework recommendation, and a short reference list.\n\nWHAT THEY ARE WATCHING FOR — a report with no citations, or the opposite: a reference list padded with test manuals and single trials so it looks scholarly and reads like a literature review.\n\nSTEPPING IN LOOKS LIKE — 'this recommends a structured phonics programme. Where would the teacher go to check that's well supported? And do we need the other twelve references?'",
"s4":    "YOU DO IT ALONE — each intervention, framework and 'what typically works' claim carries a synthesis-level source; routine strategies do not; the reference list is short and complete.\n\nPASS TEST — There is a reference list\n\nEVIDENCE TO FILE — the report recommendations and reference list, named in the Appendix 5 entry. Log against 8. Research and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a principal asks why the report recommends a particular approach over the one the school already uses, and the report gives no basis beyond your say-so.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between citing to support a claim and citing to impress, why the synthesis is usually the right level for a school reader (for example, citing a review such as Snowling & Hulme, 2011, rather than one trial), and why test manuals are not cited for every score.\n\nWHEN IT GOES WRONG — you realise a report has gone out with a key recommendation unsupported. Note the source in the case file and add it at the next review or addendum; if the recommendation cannot be supported, raise it in supervision.",
"error": "Leaving the main intervention recommendation uncited, or padding the report with references that do no work.",
"feeds": "→ Feeds into 'Cite current sources rather than the familiar ones', 'Use APA 7th consistently', and 'Say where the evidence is thin'.",
"evidence":"Report — recommendations and reference list · Appendix 5 · Log sheet tagged 8. Research and 3. Intervention"},

("Cite evidence for recommendations","Cite current sources rather than the familiar ones"): {
"why":   "Everyone has sources they learned in first year and have cited ever since. Evidence moves: syntheses are updated, recommendations change and programmes are re-evaluated. The EEF Toolkit, for instance, is revised over time, so any rating you quote may have changed — check the current toolkit entry. PSI Code 2.4.1 is the clause mapped here; read it in the Code itself. Citing an outdated source can mean recommending something the evidence has since moved away from, and an examiner notices a reference list with nothing from the last decade.",
"s1":    "WATCH FOR — how your supervisor keeps up to date: journals they read, NEPS or Department guidance updates, PSI Division of Educational, Child and Adolescent Psychology events, and how they check whether a source they have used for years is still current.\n\nWRITE DOWN — the date of each synthesis you rely on, whether a newer version or update exists, and any guidance document the service treats as current.\n\nASK AFTERWARDS — 'what's something you used to recommend that you've stopped recommending because the evidence changed?'",
"s2":    "YOU TAKE — checking the date and currency of every source you cite: looking for a newer version of a review, checking the current EEF Toolkit entry, and noting when a classic is cited for a concept rather than for current evidence.\n\nTHEY HOLD — the service's view on which guidance is current, and when an older source is still the right one.\n\nWHY THAT SPLIT — checking dates is mechanical and yours. Knowing that a newer paper has not displaced an older one, or that a guidance document is under revision, often comes from experience in the field.",
"s3":    "YOU RUN IT — before each report goes to your supervisor, check each reference: is there a newer synthesis, update or edition? Note the check in your search log.\n\nWHAT THEY ARE WATCHING FOR — every citation a decade old or more; a superseded edition; a Toolkit rating quoted from memory; a classic used as though it were current evidence of effectiveness.\n\nSTEPPING IN LOOKS LIKE — 'this review is quite old. Has it been updated? What does the Toolkit say now?'",
"s4":    "YOU DO IT ALONE — each source is the most recent adequate synthesis you could find, older sources are there for a reason you could state, and figures from living resources such as the EEF Toolkit are checked on the day.\n\nPASS TEST — Recency checked\n\nEVIDENCE TO FILE — the recency check noted in your search log, and the reference list in the report. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — a report quotes a Toolkit rating that has since been revised, and a teacher who checked the website points it out at the review meeting.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between a foundational source cited for an idea (Vygotsky for the zone of proximal development, for example) and a source cited as evidence that something works, which should be current. You can show a peer how to check for updates to a review.\n\nWHEN IT GOES WRONG — you find a newer review that changes the picture after the report has gone. Raise it in supervision, decide with your supervisor whether the school needs to be told, and update your search note so it is not repeated.",
"error": "Citing the source you have always cited without checking whether it has been updated or superseded.",
"feeds": "→ Feeds into 'Say where the evidence is thin', 'Record the search terms and databases used', and 8. Research.",
"evidence":"Search log — recency check · Report — reference list · Log sheet tagged 8. Research"},

("Cite evidence for recommendations","Use APA 7th consistently"): {
"why":   "APA 7th (American Psychological Association, 2020, Publication manual, 7th ed.) is the convention your reports and your thesis use. The Reference sheet maps the UCD Academic Integrity Policy here: accurate referencing is part of how you show whose ideas are whose. Inconsistent or wrong referencing reads as careless thinking to an examiner, and a citation that does not match its reference list entry cannot be checked.",
"s1":    "WATCH FOR — how references appear in the service's reports: whether they follow APA 7th strictly, whether the house style changes anything, and how guidance documents from NEPS, the Department or the HSE are referenced (corporate author, year, title, URL).\n\nWRITE DOWN — model references for the source types you cite most: journal article with DOI, book, chapter, government or agency report, webpage such as the EEF Toolkit, and test manual.\n\nASK AFTERWARDS — 'does the service follow APA exactly in reports to schools, or is there a house variation I should use?'",
"s2":    "YOU TAKE — every in-text citation and reference list entry in your drafts, checked against the manual or the UCD library APA guide.\n\nTHEY HOLD — the service's house style, where it differs from APA, and the final sign-off on the report.\n\nWHY THAT SPLIT — formatting is entirely checkable and entirely yours. A service may deliberately simplify referencing for parents, and that is its decision.",
"s3":    "YOU RUN IT — format every reference in your Cavan reports and Appendix entries yourself, using a reference manager if you have one, and check the final list by hand before submission.\n\nWHAT THEY ARE WATCHING FOR — in-text citations with no matching entry; 'et al.' used wrongly; missing DOIs; a mix of styles pasted from different sources; agency reports with no author or year.\n\nSTEPPING IN LOOKS LIKE — 'this cites Hulme 2011 in the text, but the list has Snowling and Hulme. Which is it?'",
"s4":    "YOU DO IT ALONE — every in-text citation matches a list entry and every entry is cited; format follows APA 7th throughout, including DOIs and agency authors.\n\nPASS TEST — Formatting is correct\n\nEVIDENCE TO FILE — the report reference list and your Appendix 5 entries. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — a report reference list with three styles, a missing year and a citation to a paper that is not in the list, returned by your supervisor with the note 'please tidy before this goes out'.",
"s5":    "YOU CAN TEACH IT — you can explain the main APA 7th rules for the source types EPs use most, how to reference a living webpage (with a retrieval date only where the manual requires one — check), and how a reference manager helps and where it gets things wrong.\n\nWHEN IT GOES WRONG — a report goes out with referencing errors. Correct the master copy on the file, fix your template, and do a final check of the list against the text before every future report.",
"error": "Letting in-text citations and the reference list drift apart, so a reader cannot find the source.",
"feeds": "→ Feeds into 'Attach a source to every substantial recommendation', written report quality, and the thesis.",
"evidence":"Report — reference list · Appendix 5 entries · Log sheet tagged 8. Research"},

("Cite evidence for recommendations","Say where the evidence is thin"): {
"why":   "PSI Code 4.2.6 is mapped here, and the Reference sheet reads it as requiring you not to suppress disconfirming evidence; it also cites 4.2.2 on not exaggerating effectiveness — read both clauses in the Code itself before quoting them. The Reference sheet's position is that 'evidence for Y is mixed, and it is recommended here because of [case-specific reason]' is more impressive than pretending certainty. Overstate the evidence and a school invests a term in something that was never likely to deliver, and trusts the next report less.",
"s1":    "WATCH FOR — the words your supervisor uses for strength of evidence: 'strong', 'promising', 'mixed', 'limited', 'no trials, but'. Notice how they recommend something with a thin base without apologising for it.\n\nWRITE DOWN — a short scale of phrases matched to evidence strength, and the phrases your supervisor avoids ('proven', 'guaranteed', 'research shows' with no qualifier).\n\nASK AFTERWARDS — 'how do you tell a school the evidence is mixed without them hearing \"don't bother\"?'",
"s2":    "YOU TAKE — drafting the sentence that states the strength of the evidence for each recommendation, based on your appraisal note.\n\nTHEY HOLD — how that is framed for this school and family, particularly when a family is committed to an approach with little evidence behind it.\n\nWHY THAT SPLIT — the evidence judgement follows from your appraisal. Telling parents that something they value has a thin base is a relationship conversation that your supervisor has had many times.",
"s3":    "YOU RUN IT — in each Cavan report, give every substantial recommendation one of: strong evidence, mixed or limited evidence with a case-specific reason, or no trial base with reasoning and an evaluation plan.\n\nWHAT THEY ARE WATCHING FOR — certainty the evidence does not support; a single trial presented as settled; disconfirming findings left out; a no-evidence recommendation with no evaluation line.\n\nSTEPPING IN LOOKS LIKE — 'you've written \"research shows\". Does it? How strongly, and in children like this one?'",
"s4":    "YOU DO IT ALONE — each recommendation states how strong its evidence is, mixed or absent evidence is named honestly, and any recommendation with no trial base carries its reasoning and a plan to evaluate it for this child.\n\nPASS TEST — Honest about the base\n\nEVIDENCE TO FILE — the report recommendations, cross-referenced to your appraisal note in the Appendix 5 entry. Log against 8. Research and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a report says an approach 'has been shown to be effective' when your own appraisal found one small uncontrolled study.",
"s5":    "YOU CAN TEACH IT — you can explain why stating uncertainty is an ethical requirement and a mark of competence, not a weakness, and why an honest 'no trials, but here is the reasoning and here is how we will know' is evidence-informed practice (CORU SoP 5.4).\n\nWHEN IT GOES WRONG — you overstated the evidence in a report that has gone out. Raise it in supervision, agree a correction for the school, and make sure the evaluation line will show whether the recommendation is working for this child.",
"error": "Writing 'research shows' when the evidence is mixed or thin, and leaving out what did not support the recommendation.",
"feeds": "→ Feeds into 'State how a recommendation would be evaluated', 6. Ethical Practice, and 3. Intervention.",
"evidence":"Report — recommendations · appraisal note · Appendix 5 · Log sheet tagged 8. Research and 6. Ethical Practice"},

# ── 8. RESEARCH · State how a recommendation would be evaluated ──

("State how a recommendation would be evaluated","Name the measure"): {
"why":   "CORU SoP 3.8 is mapped here, and the Reference sheet reads it as requiring evaluation of intervention plans with recognised outcome measures and revision in the light of them. The measure has to be able to move within the timescale: curriculum-based measurement (Deno, 2003), frequency counts and brief validated rating scales can move within a term; standardised annual tests usually cannot. Choose a measure that cannot move and the review is inconclusive before it starts.",
"s1":    "WATCH FOR — the measures your supervisor names in review lines: a words-correct-per-minute probe, a frequency count of a defined behaviour, a brief rating scale, attendance figures, a goal attainment scale. Notice how they match the measure to the outcome and the timescale.\n\nWRITE DOWN — for each common referral type (reading, maths, attendance, behaviour, anxiety), a measure that can move within a term and who could realistically take it.\n\nASK AFTERWARDS — 'which measures do schools actually keep up for a whole term, and which ones get dropped after two weeks?'",
"s2":    "YOU TAKE — proposing the measure for each recommendation, defined well enough that two people would record the same thing, and checking it can move within the review period.\n\nTHEY HOLD — whether the school can realistically keep it up, and whether a standardised measure is needed for a later decision such as a resource application.\n\nWHY THAT SPLIT — matching a measure to an outcome is technical and yours. What a school will sustain, and what another agency will later ask for, your supervisor knows from experience.",
"s3":    "YOU RUN IT — every recommendation in your Cavan reports ends with a named measure: a specific instrument, a CBM probe, or a behaviour defined in observable terms.\n\nWHAT THEY ARE WATCHING FOR — 'monitor progress' with no measure; a behaviour described in terms nobody could count ('improved engagement'); an annual standardised test named as the review measure for a ten-week intervention.\n\nSTEPPING IN LOOKS LIKE — 'what exactly will the SET write down, and could it change in eight weeks?'",
"s4":    "YOU DO IT ALONE — every recommendation names a specific instrument or an observable, countable behaviour that can move within the review period. Goal attainment scaling (Kiresuk & Sherman, 1968) is an option where no standard measure fits — check the original method before using it.\n\nPASS TEST — Specific instrument or observable\n\nEVIDENCE TO FILE — the evaluation line in each report recommendation. Log against 8. Research and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at the review the teacher says the child 'seems a bit better', and there is nothing to check that against.",
"s5":    "YOU CAN TEACH IT — you can explain why the measure must match both the outcome and the timescale, why an observable definition matters (so two raters would agree), and why CBM probes suit short cycles (Deno, 2003). You can help a teacher turn 'more settled' into something they can count.\n\nWHEN IT GOES WRONG — the measure turns out not to move, or not to capture what matters. Keep the data you have, agree a better measure at the next contact, and record the change so the review can account for it.",
"error": "Naming a measure that cannot change within the review period, or no measure at all.",
"feeds": "→ Feeds into 'Name who will measure it', 'Name when', and 'Say what would count as no progress'.",
"evidence":"Report — recommendations with evaluation line · Log sheet tagged 8. Research and 3. Intervention"},

("State how a recommendation would be evaluated","Name who will measure it"): {
"why":   "The Reference sheet lists 'assigning review to nobody in particular' as a common error. 'The school will monitor progress' means nobody will. CORU SoP 5.37 is mapped here — read it on the Reference sheet, Part B. In Irish schools the realistic people are the class teacher, the special education teacher, the year head or the guidance counsellor at post-primary, a special needs assistant only within the limits of that role, and sometimes the parent. Name a role that has not agreed, and the data will not exist at review.",
"s1":    "WATCH FOR — how your supervisor agrees the 'who' in the meeting, not afterwards in the report, and how they check that the person named actually has the time and knows how to take the measure.\n\nWRITE DOWN — for each school you visit, the roles available to measure progress (SET, class teacher, year head, guidance counsellor), and who holds the Student Support File.\n\nASK AFTERWARDS — 'how do you get a busy SET to commit to a measure without it becoming one more job they resent?'",
"s2":    "YOU TAKE — naming the role in the draft recommendation and preparing the measure so it is easy to take: a probe sheet, a tally chart, a rating form.\n\nTHEY HOLD — the negotiation with the principal or SET about who can take it on, particularly where staffing is stretched.\n\nWHY THAT SPLIT — the design of the recording tool is yours. Asking a school to commit staff time is part of the service's relationship with that school, and your supervisor holds that relationship.",
"s3":    "YOU RUN IT — at each consultation or feedback meeting in Cavan, agree out loud who will take the measure and write the role into the note and the report.\n\nWHAT THEY ARE WATCHING FOR — 'the school', 'staff' or 'the team' as the named measurer; a role named who was not at the meeting and has not agreed; a special needs assistant asked to do something outside that role.\n\nSTEPPING IN LOOKS LIKE — 'which person, in which role, will fill in this sheet on a Tuesday afternoon? Did they agree?'",
"s4":    "YOU DO IT ALONE — every evaluation line names a role (not a person's name in the report unless the service does so), and that role agreed to it at the meeting.\n\nPASS TEST — A role, not 'the school'\n\nEVIDENCE TO FILE — the consultation note recording the agreement, and the evaluation line in the report. Log against 8. Research and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — at review, the class teacher thought the SET was recording, the SET thought the class teacher was, and there is no data.",
"s5":    "YOU CAN TEACH IT — you can explain why the named role must be agreed rather than assigned, how to design a recording tool that takes under five minutes, and how the 'who' fits the Continuum of Support level the child is at.\n\nWHEN IT GOES WRONG — the named person leaves or goes on leave mid-term. Contact the school, agree a replacement role, record the change and the gap in data, and account for it at review.",
"error": "Writing 'the school will monitor' so that nobody in particular is responsible for the data.",
"feeds": "→ Feeds into 'Name when', 'Follow up whether anyone acted on it', and 5. Working with Others.",
"evidence":"Consultation note · Report — evaluation line · Log sheet tagged 8. Research and 5. Working with Others"},

("State how a recommendation would be evaluated","Name when"): {
"why":   "A review with no date does not happen. The Reference sheet's one line is 'review at the end of term 2 using [measure], with progress monitored fortnightly by the SET': what, when, how, who. PSI Code 2.3.2 is mapped here — read it in the Code itself. Two times matter: how often data are taken (so a trend can be seen) and when the decision is made. The Reference sheet also asks for a baseline before the intervention starts, even three data points over a week, because without it no change can be attributed to anything.",
"s1":    "WATCH FOR — the review points your supervisor uses: the end of a term, the next Student Support Plan review, a set number of weeks, or the next planned school visit. Notice whether they set a baseline date as well as a review date.\n\nWRITE DOWN — the school calendar for each Cavan school (term dates, midterms, Christmas), so review points do not land in a holiday, and the service's usual cycle of school visits.\n\nASK AFTERWARDS — 'how long do you give an intervention before you'd expect to see anything, and how do you decide?'",
"s2":    "YOU TAKE — setting the baseline window, the monitoring interval and the review date in the draft recommendation, checked against the school calendar.\n\nTHEY HOLD — whether the review falls within the service's planned contact with the school, and who will attend it.\n\nWHY THAT SPLIT — timing the data collection is a design decision you can make. Whether the service will be there for the review depends on its time allocation to that school, which your supervisor manages.",
"s3":    "YOU RUN IT — every Cavan recommendation carries a baseline window, a monitoring interval and a review date in DD/MM/YYYY or a named school week.\n\nWHAT THEY ARE WATCHING FOR — 'review in due course'; a review date after 18/12/2026 with no handover to whoever holds the case after you; no baseline before the intervention begins; monitoring too infrequent to show a trend.\n\nSTEPPING IN LOOKS LIKE — 'your placement ends before this review. Who picks it up, and does the note tell them?'",
"s4":    "YOU DO IT ALONE — every recommendation states when the baseline is taken, how often progress is measured, and a date or interval for the decision, with handover recorded for any review after your placement ends.\n\nPASS TEST — A date or interval\n\nEVIDENCE TO FILE — the evaluation line in the report, and the handover note for reviews falling after 18/12/2026. Log against 8. Research.\n\nWHAT FAILURE LOOKS LIKE — the intervention starts in November with no baseline, the review is set for 'the new year', and nobody has it in their diary.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between a monitoring interval and a decision point, why a baseline comes first (Kazdin, 2011, on single-case designs), and why a review date must fall when both the school and the service will be available.\n\nWHEN IT GOES WRONG — the review date passes with nobody there. Contact the school, set a new date, record what happened, and use whatever data exist; do not let the recommendation quietly lapse.",
"error": "Setting no baseline and no review date, so the intervention cannot be judged and nobody returns to it.",
"feeds": "→ Feeds into 'Say what would count as no progress', 'Follow up whether anyone acted on it', and handover of open cases at the end of Cavan.",
"evidence":"Report — evaluation line · handover note · Log sheet tagged 8. Research"},

("State how a recommendation would be evaluated","Say what would count as no progress"): {
"why":   "Without a threshold set in advance, any result can be read as 'some progress' and an intervention that is not working carries on for a year. PSI Code 2.3.2 is mapped here. CBM practice uses a goal line and a decision rule (for example, several consecutive data points below the line prompts a change — check the rule in the CBM source you use, e.g. Deno, 2003, before quoting a number). Goal attainment scaling (Kiresuk & Sherman, 1968) sets the expected outcome and the levels above and below it before the work begins. Either way, the point is agreeing what failure looks like before you see the data.",
"s1":    "WATCH FOR — whether your supervisor agrees, at the planning meeting, what result would lead to a change of course, and how they phrase it so it does not sound like predicting failure.\n\nWRITE DOWN — the thresholds you see used: a goal line on a CBM chart, a GAS scale with a defined expected level, a frequency target, or a plain 'if X has not happened by the review, we will try Y'.\n\nASK AFTERWARDS — 'how do you decide the bar for \"not working\" without setting it so low that everything passes?'",
"s2":    "YOU TAKE — drafting the threshold for each recommendation from the baseline and the evidence: the expected level, and the level below which the plan changes.\n\nTHEY HOLD — whether the threshold is realistic for this child, and what the next step would be if it is not met.\n\nWHY THAT SPLIT — calculating a goal line or writing a scale is technical and yours. Judging how much change this child can realistically make, and what the fallback should be, draws on your supervisor's experience of similar cases.",
"s3":    "YOU RUN IT — every Cavan recommendation says what would count as no or insufficient progress by the review, and what would happen then.\n\nWHAT THEY ARE WATCHING FOR — no threshold at all; a threshold so low any change passes; a threshold set after the data came in; no stated next step if progress is insufficient.\n\nSTEPPING IN LOOKS LIKE — 'if at review he's reading five more words a minute than at baseline, is that working or not? Decide now.'",
"s4":    "YOU DO IT ALONE — each recommendation names, before it starts, the result that would count as no or insufficient progress and the action that would follow, based on the baseline.\n\nPASS TEST — A threshold for changing course\n\nEVIDENCE TO FILE — the evaluation line with its threshold in the report, and any GAS scale or goal-line chart on the case file. Log against 8. Research and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — at review the child has barely moved, the school says 'he's getting there', and the intervention continues unchanged for another term.",
"s5":    "YOU CAN TEACH IT — you can explain why the threshold is set before seeing the data, how a goal line or a GAS scale works, and why a clear 'change course' point protects the child's time. Read Kiresuk and Sherman (1968) and a CBM decision-rule source before teaching the detail.\n\nWHEN IT GOES WRONG — the threshold proves unrealistic in either direction. Record that, reset it with the school using the data you now have, and note what you learned for setting the next one.",
"error": "Leaving 'no progress' undefined so that any result can be read as success and nothing ever changes.",
"feeds": "→ Feeds into 'Follow up whether anyone acted on it', 3. Intervention, and single-case evaluation as Research evidence.",
"evidence":"Report — evaluation line with threshold · GAS or goal-line chart on file · Log sheet tagged 8. Research and 3. Intervention"},

("State how a recommendation would be evaluated","Follow up whether anyone acted on it"): {
"why":   "The Reference sheet's error list ends with 'never going back to look'. CORU SoP 3.9 and PSI Code 3.1.2 are mapped here (read both for their wording before quoting what they require). Implementation research shows that a recommendation is not the same as its delivery (Fixsen et al., 2005). A recommendation reviewed and revised is worth more in the portfolio than three delivered and abandoned, and following up is the only way you learn whether your formulations are any good.",
"s1":    "WATCH FOR — how and when your supervisor checks back with a school after a report: a phone call, an item at the next planning meeting, a review visit. Notice what they ask: was it started, was it delivered as planned, what did the data show.\n\nWRITE DOWN — the service's routine for follow-up (if there is one), how it is recorded on the file, and how the result feeds into the next planning meeting.\n\nASK AFTERWARDS — 'what do you usually find when you go back, and what have you changed in your recommendations because of it?'",
"s2":    "YOU TAKE — keeping a follow-up list of every recommendation you have made in Cavan, with its review date, and making the contact on time.\n\nTHEY HOLD — what happens if a school has not acted, particularly where a child's needs are serious, and any conversation with the principal about it.\n\nWHY THAT SPLIT — tracking your own recommendations is plainly your job. A school that has not delivered may have reasons the service needs to handle within its wider relationship with that school.",
"s3":    "YOU RUN IT — before the end of the placement, follow up each recommendation you can: was it started, delivered as planned, measured, and what did the measure show against the threshold?\n\nWHAT THEY ARE WATCHING FOR — follow-up that asks only 'how is he getting on?'; no check on whether the recommendation was delivered; data collected but not compared with the baseline or threshold; no revision when it did not work.\n\nSTEPPING IN LOOKS LIKE — 'before you ask whether it worked, did you ask whether it happened?'",
"s4":    "YOU DO IT ALONE — you contact the named person at the review point, ask whether the recommendation was delivered and measured, compare the data with baseline and threshold, record the result and revise the plan. For reviews after 18/12/2026 you hand the list on.\n\nPASS TEST — You asked afterwards\n\nEVIDENCE TO FILE — the follow-up note on the case file, and a summary in the Appendix 5 entry if the result is written up as practice-based research (for example as an AB single-case evaluation, Kazdin, 2011). Log against 8. Research and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — you leave Cavan with a stack of reports and no idea whether any recommendation was acted on.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between 'was it done' (implementation) and 'did it work' (outcome), why both must be checked, and how a follow-up result becomes a small single-case evaluation that evidences the Research competency.\n\nWHEN IT GOES WRONG — you find nothing was done. Do not blame the school in the note; record what happened, find out why (time, training, staffing, disagreement with the recommendation), and bring it to supervision so the next recommendation is one the school can deliver.",
"error": "Never going back to check whether a recommendation was delivered or worked.",
"feeds": "→ Feeds into 3. Intervention, 2. Formulation (testing whether the formulation held), and 8. Research through single-case evaluation.",
"evidence":"Follow-up note on case file · Appendix 5 · Log sheet tagged 8. Research and 3. Intervention"},

}
