"""Supervision (part A): the supervision contract, the weekly hour, the agenda,
supervision session records, and observing your supervisor with a client.
Written in the micro.py format from HANDOVER.md.

Keyed (macro skill name, micro-skill name).
"""

MICRO = {

# ── 7. SUPERVISION · Agree and sign the supervision contract ──

("Agree and sign the supervision contract","Know the 30 minutes per placement day entitlement"): {
"why":   "The Reference sheet summarises PSI Accreditation Standards (2022) 3.3.9 as requiring thirty minutes of supervision per placement day; read 3.3.9 itself so you quote the standard's words rather than a paraphrase. At four Cavan days a week that is two hours weekly — the formal hour plus an hour of informal contact. A trainee who does not know the figure cannot notice a shortfall, and one who cannot state it turns a requirement into a favour she has to ask for.",
"s1":    "WATCH FOR — how your supervisor talks about supervision time in the first meeting: as a fixed commitment with a figure attached, or as 'whenever we get a chance'. Notice whether they count informal contact (a call after a visit, a drive to a school) as supervision or treat only the booked hour as real.\n\nWRITE DOWN — the figure, the 3.3.9 reference, and the weekly total it produces for four days a week.\n\nASK AFTERWARDS — 'how have you tracked supervision time with previous trainees, and what counted?'",
"s2":    "YOU TAKE — reading PSI Accreditation 3.3.9 in full before week one (the text is on the Reference sheet, Part B), doing the arithmetic for the Cavan pattern, and bringing both to the contract conversation.\n\nTHEY HOLD — the decision about how the time is split between formal and informal contact, within the standard.\n\nWHY THAT SPLIT — knowing the entitlement is your job and no one else will do it for you. How the time is delivered depends on the supervisor's diary and service, so the shape is agreed, not dictated.",
"s3":    "YOU RUN IT — state the entitlement yourself in the contract meeting, citing 3.3.9, and propose how the two weekly hours will be made up, with your supervisor responding.\n\nWHAT THEY ARE WATCHING FOR — apologetic framing ('I know you're busy, but…') that makes the standard sound optional, or the opposite — reading it out like a grievance before any problem exists.\n\nSTEPPING IN LOOKS LIKE — 'you're right, that's the figure — let's write down what counts as the informal hour so neither of us has to guess later.'",
"s4":    "YOU DO IT ALONE — carry the figure and the source in your head, apply it to whatever days-per-week pattern you are on, and use it calmly the first time the hour moves, without needing to look it up.\n\nPASS TEST — You can state it if the hour slips\n\nEVIDENCE TO FILE — the signed contract recording the entitlement and how it will be met; running totals on the supervision records. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — reaching December unable to say whether the standard was met, because you never knew the figure and never counted.",
"s5":    "YOU CAN TEACH IT — you can explain to a first-year peer where the figure comes from, how to convert it for a three-, four- or five-day pattern, why informal contact counts only if it is recorded, and why quoting a standard is less awkward than making a request.\n\nWHEN IT GOES WRONG — you can say what to do when the total falls short: raise it with the figure and the dates in hand, propose a make-up plan, and if it persists, use the UCD route for placement concerns — read the Handbook for the route itself.",
"error": "Treating supervision time as whatever the supervisor can spare rather than as a stated, countable standard.",
"feeds": "→ Feeds into 'Record day, time, duration and format', 'Keep to 30 minutes per placement day cumulatively', and 'Raise it if it slips twice'.",
"evidence":"Signed supervision contract · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Agree and sign the supervision contract","Know the four components expected"): {
"why":   "Supervision is not one thing. The pass test names four components — educative, supportive, evaluative and safeguarding — mapped here to Handbook §6.1; read that section yourself for UCD's exact wording. They echo Proctor's (1986) formative, restorative and normative functions and Kadushin's (1976) educational, supportive and administrative ones. A trainee who knows only the educative strand accepts sessions that never check her wellbeing, never give her a judgement of her standard, and never look at risk.",
"s1":    "WATCH FOR — which component each part of a session is actually doing: teaching you something (educative), attending to how you are coping (supportive), telling you where your work stands (evaluative), or checking that clients and you are safe (safeguarding). Notice which your supervisor defaults to and which rarely appears.\n\nWRITE DOWN — one example of each from the first sessions, with the component label.\n\nASK AFTERWARDS — 'which of the four do you find hardest to fit into an hour, and why?'",
"s2":    "YOU TAKE — writing the four components into the draft contract with one line each on what they will look like in practice, and noting Proctor's (1986) three functions alongside as the underlying model.\n\nTHEY HOLD — the evaluative component — the judgement of your competence that feeds the mid-placement review and written feedback.\n\nWHY THAT SPLIT — you can name and ask for all four. Evaluation is the one that is genuinely theirs: it is the gatekeeping part of the role, and a trainee cannot evaluate herself on the supervisor's behalf.",
"s3":    "YOU RUN IT — in the contract meeting, walk through the four components and agree how each will be met over the placement, with your supervisor adding or amending.\n\nWHAT THEY ARE WATCHING FOR — reciting labels without being able to say what each looks like in an EP service, and folding safeguarding into 'supportive' when it is about the child, not about you.\n\nSTEPPING IN LOOKS LIKE — 'give me an example of what safeguarding in supervision would look like for a school visit next month.'",
"s4":    "YOU DO IT ALONE — name the four components without prompting, give a practice example of each, and use them to notice when supervision has run on one strand for weeks.\n\nPASS TEST — Educative, supportive, evaluative, safeguarding\n\nEVIDENCE TO FILE — the contract listing the four components; component tags on each supervision record. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — a run of records that are all educative case discussion, no evaluative feedback until the mid-placement review surprises you, and no safeguarding item logged in a term of school visits.",
"s5":    "YOU CAN TEACH IT — you can explain the four components, map them roughly onto Proctor (1986) and Kadushin (1976) — noting the mapping is approximate, not one-to-one — and show why safeguarding and evaluation protect clients and the profession, not just the trainee.\n\nWHEN IT GOES WRONG — you can say what to do when one component is missing: name it on the next agenda ('I'd like some evaluative feedback on my report writing'), rather than waiting for the review.",
"error": "Knowing only the teaching function of supervision, so the evaluative and safeguarding components go missing unnoticed.",
"feeds": "→ Feeds into 'Tag which of the four components the session covered', 'Take the weekly supervision hour', and 7. Supervision competency evidence.",
"evidence":"Signed supervision contract · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Agree and sign the supervision contract","Bring a draft to week one"): {
"why":   "The Reference sheet's point: signing in week one is the only moment when asking for something feels normal rather than like a complaint. Arriving with a draft means the conversation is about your terms rather than a template you skim and sign. Scaife (2019, Supervision in Clinical Practice, 3rd ed.) and Page and Wosket (Supervising the Counsellor; edition — check) both treat contracting as the first stage of supervision, not an administrative extra. With nothing prepared, the default fills the gap.",
"s1":    "WATCH FOR — how your supervisor responds to a trainee who arrives with a draft versus one who arrives empty-handed: which items they accept without discussion, which they amend, and which they add that you did not think of (usually cover arrangements and out-of-hours contact).\n\nWRITE DOWN — every item they added or changed, and the reason given.\n\nASK AFTERWARDS — 'what do trainees usually leave out of a first contract that causes trouble in the second month?'",
"s2":    "YOU TAKE — drafting it before week one: entitlement (3.3.9), four components, day and time, cancellations, out-of-session contact, leave cover, disagreement, records and who holds them, observation dates, any adjustments you want in writing.\n\nTHEY HOLD — service-specific items you cannot know: cover within the Cavan team, local protocols, diary constraints.\n\nWHY THAT SPLIT — the draft shows you know the standard; the service detail is theirs, and a contract that ignores it will not survive the term.",
"s3":    "YOU RUN IT — lead the week-one meeting from your draft, item by item, and agree amendments on the page, with your supervisor responding.\n\nWHAT THEY ARE WATCHING FOR — a draft so rigid it reads as distrust, or so thin it is a template with names added. Also watch for leaving out the Table 3 Early Years and Young Adult bands and PSI 3.3.6 special-setting visits, which belong in the Appendix 1 conversation at the same meeting.\n\nSTEPPING IN LOOKS LIKE — 'this is good — can we leave the observation dates until I've seen the diary, but agree a week for each now?'",
"s4":    "YOU DO IT ALONE — produce a first draft for any new placement without being asked, tailored to that service, and use it to structure the first supervision meeting.\n\nPASS TEST — You arrived with something\n\nEVIDENCE TO FILE — the draft (dated) and the signed final version, so the changes are visible; a supervision record for the contracting session. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — signing the service's standard form in week three, after casework has started, with 'weekly' as the only commitment and no observation dates.",
"s5":    "YOU CAN TEACH IT — you can explain why contracting comes first in the supervision literature (Scaife, 2019; Page & Wosket), which items prevent the common breakdowns, and why a new supervisor means a new contract — the Roscommon arrangement does not carry over.\n\nWHEN IT GOES WRONG — you can say what to do if week one passes without a contract: raise it at the next meeting, bring the draft, and do not start new casework on an unwritten arrangement if you can avoid it.",
"error": "Arriving in week one with nothing and signing whatever template the service uses.",
"feeds": "→ Feeds into 'Record day, time, duration and format', 'Agree how cancellations are handled', and 'Arrange it in the first weeks' (observation).",
"evidence":"Draft and signed contract · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Agree and sign the supervision contract","Record day, time, duration and format"): {
"why":   "'Weekly' is not a commitment; 'Tuesday 10:00–11:00, in person, at the service base' is. The Reference sheet lists writing 'weekly' as a named error: an unspecified hour is the first thing to move when the caseload grows, and there is nothing to point to when it does. Carroll (2014, Effective Supervision for the Helping Professions, 2nd ed.) places responsibility for the structure of supervision partly on the supervisee. Vague terms protect neither of you.",
"s1":    "WATCH FOR — how your supervisor's week is actually shaped: which days they are in schools, which are admin or team days, and when they are least likely to be called away. Notice whether they propose a slot that is realistic or one that is ideal.\n\nWRITE DOWN — the proposed day, start and end time, whether it is in person, online or phone, and the location.\n\nASK AFTERWARDS — 'which slot in your week has survived best with other trainees, and which has always been eaten?'",
"s2":    "YOU TAKE — proposing two or three specific slots that fit your placement days, avoiding the last hour of the day, and writing the agreed one into the contract in full.\n\nTHEY HOLD — the final choice, since their diary carries more constraints than yours.\n\nWHY THAT SPLIT — you bring options so the decision is quick and specific. They choose because a slot they cannot protect will fail, however well you have drafted it.",
"s3":    "YOU RUN IT — put the specifics into the contract yourself, read them back, and set the recurring calendar invitation from your side the same day, with your supervisor confirming.\n\nWHAT THEY ARE WATCHING FOR — 'as arranged', 'weekly', or 'Tuesdays' with no time; a slot at the end of a school day; online by default when in person is available and better for the difficult items.\n\nSTEPPING IN LOOKS LIKE — 'let's not put it at four — that's when the phone calls come. Can you do Tuesday morning?'",
"s4":    "YOU DO IT ALONE — write every supervision arrangement with day, time, duration, format and location, and put it in both calendars as a recurring appointment before you leave the room.\n\nPASS TEST — Specific, not 'as arranged'\n\nEVIDENCE TO FILE — the signed contract; a recurring calendar entry; supervision records showing the agreed slot was used. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — a contract that says 'weekly supervision as arranged', and by November you cannot say when the last formal hour was.",
"s5":    "YOU CAN TEACH IT — you can explain why specificity is what makes the hour defensible, why the end-of-day slot fails, and why format matters (in-person sessions tend to be where the harder items get raised — your experience, not a research claim).\n\nWHEN IT GOES WRONG — you can say what to do when the agreed slot proves unworkable: renegotiate a new specific slot and amend the contract, rather than drifting into 'whenever suits'.",
"error": "Writing 'weekly' or 'as arranged' instead of a named day, time, duration and format.",
"feeds": "→ Feeds into 'Protect the hour', 'Agree how cancellations are handled', and 'Send it the day before'.",
"evidence":"Signed supervision contract · calendar entry · Log sheet tagged 7. Supervision"},

("Agree and sign the supervision contract","Agree how cancellations are handled"): {
"why":   "Supervision is rarely lost in one decision; the Reference sheet describes it going gradually — moved once, shortened, merged into a car journey. A cancellation clause stops that drift by deciding in advance who rearranges and by when. PSI Supervision Guidelines (2024) are mapped here; read them for the wording. The Reference sheet's rule is that a missed hour is rescheduled within the same week, not dropped. Without that, each cancellation is negotiated from scratch, and the trainee usually concedes.",
"s1":    "WATCH FOR — what actually happens when your supervisor's day is disrupted: do they rebook the hour on the spot, leave it to you, or let it lapse? Notice whether trainee-initiated and supervisor-initiated cancellations are treated the same.\n\nWRITE DOWN — the rule you agree: who rearranges, the deadline for the replacement, and what happens if it cannot be found.\n\nASK AFTERWARDS — 'when you've had to cancel before, what made it easy or hard to put the hour back?'",
"s2":    "YOU TAKE — drafting a clause naming who rebooks (whoever cancels, or always you), the window (same week), and the fallback (a phone session rather than nothing).\n\nTHEY HOLD — agreement on what counts as a legitimate reason to move it, and on cover when they are on leave.\n\nWHY THAT SPLIT — the mechanics are yours to propose. Cover arrangements depend on the team, and only the supervisor can commit a colleague.",
"s3":    "YOU RUN IT — raise cancellations as a contract item, propose your clause, and agree it in writing, with your supervisor amending.\n\nWHAT THEY ARE WATCHING FOR — a clause that only binds the supervisor (which reads as mistrust), or one with no deadline ('we'll rearrange') that permits drift.\n\nSTEPPING IN LOOKS LIKE — 'whoever cancels books the replacement before the end of the same day — does that work for you?'",
"s4":    "YOU DO IT ALONE — apply the clause every time without it becoming a confrontation: when the hour is cancelled, reply the same day with two replacement slots in the same week, and log the change.\n\nPASS TEST — Who rearranges, and by when\n\nEVIDENCE TO FILE — the clause in the signed contract; supervision records noting rescheduled sessions with original and new dates (DD/MM/YYYY). Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — three cancelled hours in a term, none replaced, and no record that they were ever due.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why the cancellation clause is the part of the contract that does most work, how to draft one that binds both people, and how the record of rescheduled sessions becomes evidence of the 3.3.9 total.\n\nWHEN IT GOES WRONG — you can say what to do when the clause is ignored: name it at the next session with dates, and if it continues, follow 'Raise it if it slips twice'.",
"error": "Agreeing 'we'll rearrange' with no named person and no deadline.",
"feeds": "→ Feeds into 'Protect the hour', 'Raise it if it slips twice', and 'Keep to 30 minutes per placement day cumulatively'.",
"evidence":"Signed supervision contract · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Agree and sign the supervision contract","Both sign and date it"): {
"why":   "An unsigned contract is a draft, and a draft carries no weight when you need to point to it. The row maps this to Handbook Appendix 8; check which form UCD expects the signed contract on. Signing and dating makes the agreement visible to UCD if a problem arises later. The Reference sheet's Appendix 4 lesson applies directly: an 84-day log still waiting for countersignature is the position a same-day signature avoids.",
"s1":    "WATCH FOR — whether your supervisor treats signing as a formality at the end or as the moment the agreement becomes real, and whether they keep a copy themselves.\n\nWRITE DOWN — the date signed, where each copy is held, and whether UCD needs a copy and by when (check the Handbook; do not assume).\n\nASK AFTERWARDS — 'have you ever had to go back to a signed contract with a trainee, and what did it settle?'",
"s2":    "YOU TAKE — preparing the final version with all agreed amendments incorporated, bringing two copies (or a signable digital version), and filing yours the same day.\n\nTHEY HOLD — their signature and their copy, and any service-level sign-off their line manager requires.\n\nWHY THAT SPLIT — the administration is yours because you carry the consequence if it is missing. Any internal service approval is outside your reach.",
"s3":    "YOU RUN IT — close the contracting meeting by reading back the final terms, signing and dating it together, and confirming where the copies go, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — 'I'll sign it later' left open, undated signatures, a signed version that differs from what was agreed, and no copy kept.\n\nSTEPPING IN LOOKS LIKE — 'print it now and we'll both sign before you go — otherwise it'll sit in my inbox.'",
"s4":    "YOU DO IT ALONE — ensure every placement contract is signed and dated by both of you in the first week, in DD/MM/YYYY, with a copy filed where you and UCD can find it.\n\nPASS TEST — It is signed\n\nEVIDENCE TO FILE — the signed and dated contract in your placement folder; a supervision record for the session in which it was signed. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an unsigned Word document in your email drafts in March, when you need it to show what was agreed about the hour or the observations.",
"s5":    "YOU CAN TEACH IT — you can explain why signature and date matter (evidence, accountability, a fixed point for review), why the same-day habit applies to Appendix 4 and every other countersigned form, and why the contract should be revisited at the mid-placement review.\n\nWHEN IT GOES WRONG — you can say what to do if it was never signed: get it signed now with the actual date, not backdated, and note in the record that it was signed late.",
"error": "Leaving the contract unsigned 'for later', so it cannot be relied on when it is needed.",
"feeds": "→ Feeds into 'Get them co-signed', 'Protect the hour', and the mid-placement review.",
"evidence":"Signed contract · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

# ── 7. SUPERVISION · Take the weekly supervision hour ──

("Take the weekly supervision hour","Protect the hour"): {
"why":   "The Reference sheet calls the weekly hour the single most protective thing in the placement and the first to disappear. It is where you find out what you did not know you did not know. PSI Accreditation 3.3.9 is mapped here. The hour goes by small erosions, and each one feels reasonable; a trainee who does not guard it structurally will find in December that it has not been happening and nobody said so.",
"s1":    "WATCH FOR — what your supervisor does to keep the hour intact: phone off, door closed, not taking calls, starting on time. Notice what they treat as a legitimate reason to interrupt it (a child protection matter) and what they defer.\n\nWRITE DOWN — for each week, whether the hour happened, its actual length, and anything that cut into it.\n\nASK AFTERWARDS — 'what's the thing that most often takes supervision time away from you, and how do you stop it?'",
"s2":    "YOU TAKE — keeping the recurring calendar entry, confirming the room, arriving on time with the agenda sent, and rebooking at once when it moves.\n\nTHEY HOLD — deciding whether a genuine emergency overrides the hour on the day.\n\nWHY THAT SPLIT — most of protecting the hour is logistics, and a trainee who manages them removes most of the reasons it slips. Judging a service emergency requires authority and information you do not have.",
"s3":    "YOU RUN IT — manage the weekly hour yourself: calendar, room, agenda, start and finish, with your supervisor attending.\n\nWHAT THEY ARE WATCHING FOR — accepting moves without rebooking, letting it become the last slot of the day, and filling it with updates that could have been an email so it feels dispensable.\n\nSTEPPING IN LOOKS LIKE — 'we've moved this three times — let's find a slot we can both actually keep.'",
"s4":    "YOU DO IT ALONE — keep the hour happening weekly across the placement, rebook within the week when it moves, and keep it for supervision rather than case management.\n\nPASS TEST — It happened\n\nEVIDENCE TO FILE — a supervision record for every session held, with date and duration; rescheduled sessions noted. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — records for six sessions in an eleven-week placement, with no note of why the others did not happen.",
"s5":    "YOU CAN TEACH IT — you can explain how the hour erodes (moved, shortened, merged into a journey), the structural protections that stop it, and why keeping it is part of ethical practice rather than a personal preference.\n\nWHEN IT GOES WRONG — you can say what to do when it has lapsed: count the missed sessions with dates, raise it functionally at the next contact, and agree a make-up plan in writing.",
"error": "Letting the hour move, shrink or merge into other contact without rebooking it.",
"feeds": "→ Feeds into 'Raise it if it slips twice', 'Complete a record for every session', and 'Keep to 30 minutes per placement day cumulatively'.",
"evidence":"Supervision records (Appendix 8) · calendar · Log sheet tagged 7. Supervision"},

("Take the weekly supervision hour","Raise it if it slips twice"): {
"why":   "The Reference sheet's rule: cancelled twice in a row is a pattern, and you name it at the next session. PSI Accreditation 3.3.9 makes supervision a requirement of the programme, not a courtesy; read the standard so you can say so accurately. Supervision can be insufficient without anyone behaving badly — a stretched service, a supervisor across too many schools. Trainees often decide the shortfall is their fault for needing too much and wait until the end, when nothing can be fixed.",
"s1":    "WATCH FOR — how your supervisor responds when a pattern is named: whether they treat it as information to act on or as criticism. Notice how they talk about supervision shortfalls in their own work, if they do.\n\nWRITE DOWN — dates of the sessions that did not happen, the reason if given, and what was agreed when you raised it.\n\nASK AFTERWARDS — 'if supervision started slipping with a trainee, how would you want them to tell you?'",
"s2":    "YOU TAKE — keeping the count, and raising it yourself in functional terms at the next contact: 'we've had two of the last four sessions — can we look at how to protect it?'\n\nTHEY HOLD — the fix inside the service, and any conversation with their manager about capacity.\n\nWHY THAT SPLIT — you are the person who notices first and whose placement depends on it. The remedy often sits with workload and staffing, which only the supervisor can address.",
"s3":    "YOU RUN IT — raise the slippage at the start of the next session, with dates, and propose a remedy, with your supervisor responding.\n\nWHAT THEY ARE WATCHING FOR — apologising for raising it, framing it as a complaint about them rather than a problem to solve together, or not naming the standard at all.\n\nSTEPPING IN LOOKS LIKE — 'thanks for saying it — you're right, and it's a requirement. Let's book the next four now.'",
"s4":    "YOU DO IT ALONE — raise any second consecutive miss at the next contact, calmly, with dates and the standard; if it does not change, contact UCD placement staff through the route the Handbook sets out (read §6.4.3 for the route yourself).\n\nPASS TEST — It is a requirement, not a courtesy\n\nEVIDENCE TO FILE — supervision records noting the missed dates and the conversation; any email to UCD kept. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — telling your tutor at the end-of-placement review that supervision 'hadn't really happened since November'.",
"s5":    "YOU CAN TEACH IT — you can explain why the second miss is the trigger, how to raise it without blame, why using the UCD route is not disloyalty (the Reference sheet's point), and why waiting harms the children on your caseload as well as you.\n\nWHEN IT GOES WRONG — you can say what to do when raising it changes nothing: document, contact UCD, and keep practising safely — which may mean holding back from new complex work until supervision is back.",
"error": "Deciding a supervision shortfall is your fault for needing too much, and saying nothing until the end.",
"feeds": "→ Feeds into 'Keep to 30 minutes per placement day cumulatively', 6. Ethical Practice (working within competence), and the mid-placement review.",
"evidence":"Supervision records (Appendix 8) · email trail · Log sheet tagged 7. Supervision"},

("Take the weekly supervision hour","Keep to 30 minutes per placement day cumulatively"): {
"why":   "The Reference sheet summarises PSI Accreditation 3.3.9 as thirty minutes per placement day; read the standard itself. At four days a week that is two hours weekly: the formal hour plus an hour of informal contact — corridor conversations, a call after a difficult visit, a joint drive to a school. The informal hour is real supervision but only counts if it is logged. At the end of placement the log is the evidence the standard was met.",
"s1":    "WATCH FOR — the informal supervision that happens around the formal hour: advice in the car, a phone call after a feedback meeting, a quick check before a consultation. Notice how much of your learning happens there.\n\nWRITE DOWN — each informal contact the same day: date, minutes, format, topic in a line.\n\nASK AFTERWARDS — 'would you count that conversation in the car as supervision? What would make it count?'",
"s2":    "YOU TAKE — keeping a running cumulative total: placement days to date × 30 minutes against minutes logged, formal and informal, updated weekly.\n\nTHEY HOLD — agreement that a given informal contact was supervision, confirmed by their countersignature on the records.\n\nWHY THAT SPLIT — the arithmetic is yours and takes a minute a week. Only the supervisor can confirm that a conversation was supervision rather than chat, which is why records need their signature.",
"s3":    "YOU RUN IT — bring the running total to supervision monthly and state where it stands, with your supervisor checking it against their own recollection.\n\nWHAT THEY ARE WATCHING FOR — counting every conversation generously, or the opposite — logging only the formal hour and showing a shortfall that did not exist.\n\nSTEPPING IN LOOKS LIKE — 'that phone call was ten minutes of logistics, not supervision — don't count it. The drive to the school was, though.'",
"s4":    "YOU DO IT ALONE — keep a cumulative total from day one, know at any point whether you are ahead or behind, and act before the gap is too big to close.\n\nPASS TEST — You track the total\n\nEVIDENCE TO FILE — supervision records for formal and informal contact with minutes; a running total you can show on request. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an end-of-placement claim that the standard was met, with records showing only the formal hours and no way to evidence the rest.",
"s5":    "YOU CAN TEACH IT — you can explain how to calculate the requirement for any days-per-week pattern, what informal contact legitimately counts, and why the record rather than the memory is what evidences the standard.\n\nWHEN IT GOES WRONG — you can say what to do if the total falls behind: show the figures, propose added sessions, and raise it early through 'Raise it if it slips twice' rather than at the final review.",
"error": "Not logging the informal contact, then being unable to show the standard was met.",
"feeds": "→ Feeds into 'Complete a record for every session', 'Get them co-signed', and the end-of-placement review.",
"evidence":"Supervision records with minutes (Appendix 8) · running total · Log sheet tagged 7. Supervision"},

# ── 7. SUPERVISION · Prepare and send an agenda in advance ──

("Prepare and send an agenda in advance","Send it the day before"): {
"why":   "An agenda sent the day before means your supervisor arrives having thought about your questions, and the hour starts at the substance. Sending it as you walk in removes the only benefit, as the Reference sheet notes. It also leaves a dated, searchable record of what you raised and when, which matters if a concern later turns out to have been raised early. Handbook §6.2 is mapped here; read it for UCD's expectation. Carroll (2014) places this responsibility with the supervisee.",
"s1":    "WATCH FOR — how your supervisor uses an agenda that arrives in advance: do they come with a view, a resource, or a question back? Compare a session where they had it the day before with one where they saw it on arrival.\n\nWRITE DOWN — when you sent it, whether they had read it, and what difference it made to the first ten minutes.\n\nASK AFTERWARDS — 'is the day before enough notice for you, or would another time work better for you to think about it?'",
"s2":    "YOU TAKE — writing and sending the agenda by email at a fixed time the day before, every week, as a fifteen-minute habit.\n\nTHEY HOLD — adding their own items, and deciding whether anything on yours needs to move earlier (a risk item should not wait for Tuesday).\n\nWHY THAT SPLIT — the habit is entirely yours. The supervisor may know that an item needs action sooner than the hour, and advance notice gives them the chance to say so.",
"s3":    "YOU RUN IT — send the agenda the day before each session for several weeks, with your supervisor responding by email or at the start of the session.\n\nWHAT THEY ARE WATCHING FOR — agendas that drift to the morning of the session, then to arrival; and urgent items (a safeguarding concern) held for the agenda when they needed action that day.\n\nSTEPPING IN LOOKS LIKE — 'item two shouldn't have waited for supervision — ring me the same day next time.'",
"s4":    "YOU DO IT ALONE — send an agenda the day before every supervision session, at a regular time, by email so it is timestamped, and act on anything urgent immediately rather than parking it.\n\nPASS TEST — In advance, not on arrival\n\nEVIDENCE TO FILE — the sent agendas in a dedicated email folder; agenda items reflected in the supervision record. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an agenda typed on your phone in the car park, which your supervisor reads for the first time while you wait.",
"s5":    "YOU CAN TEACH IT — you can explain why advance notice changes the quality of the hour, why email beats a verbal list (timestamp, record), and where the line sits between an agenda item and something that needs action now.\n\nWHEN IT GOES WRONG — you can say what to do in a week you miss it: send a short agenda as early as you can, and never hold a child protection concern for supervision — report to Tusla as soon as practicable, then bring it.",
"error": "Sending the agenda as you walk in, which removes the only benefit.",
"feeds": "→ Feeds into 'Keep it to three items', 'Update on actions agreed last time', and 'Record topics, actions and who does what'.",
"evidence":"Sent agenda emails · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Prepare and send an agenda in advance","Keep it to three items"): {
"why":   "The Reference sheet: an hour holds roughly three substantive items, not eight. Ten items turn supervision into a list read aloud and push the difficult item off the end. Good items share a shape — you have already thought about them and got stuck — and priority order means that if time runs out, you lose the least important thing. Handbook §6.2 is mapped here. Case updates that could be an email should be an email.",
"s1":    "WATCH FOR — how long a single substantive item actually takes in your supervisor's sessions, and what happens to the items at the bottom of a long list.\n\nWRITE DOWN — for each session, how many items were covered in depth, and which were rushed or dropped.\n\nASK AFTERWARDS — 'when a trainee brings a long list, which items do you wish they'd sent by email instead?'",
"s2":    "YOU TAKE — choosing three items the day before: one case you are stuck on, one thing you did that you are unsure about, one forward-looking item — each a line, in priority order, with updates moved to email.\n\nTHEY HOLD — the right to reorder or swap an item if something more pressing needs the time.\n\nWHY THAT SPLIT — selection is the skill you are building. The supervisor may see a risk or priority you cannot, which is a reason to let them move items, not to add more.",
"s3":    "YOU RUN IT — bring a three-item agenda each week and keep the session to it, with your supervisor following your lead.\n\nWHAT THEY ARE WATCHING FOR — items that are status updates ('case update'), items with no thinking behind them, and a list that quietly grows back to six.\n\nSTEPPING IN LOOKS LIKE — 'what's the actual question on item one? Tell me the two options you're stuck between.'",
"s4":    "YOU DO IT ALONE — produce a focused agenda every week: three items, each showing your prior thinking and the question you want answered, updates handled elsewhere.\n\nPASS TEST — Focused\n\nEVIDENCE TO FILE — the sent agendas; supervision records showing each item discussed in depth, with cases identified by reference number only. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an eight-item agenda where item eight, the one you were worried about, is 'if we have time' and never happens.",
"s5":    "YOU CAN TEACH IT — you can explain the three-item shape, how to turn 'case update' into a real question ('two competing formulations — which does the data support?'), and why the limit is what protects the difficult item.\n\nWHEN IT GOES WRONG — you can say what to do when more than three things genuinely need supervision: prioritise, email the rest, and ask for extra time rather than squeezing.",
"error": "Bringing a long list of status updates so the hour becomes a list read aloud.",
"feeds": "→ Feeds into 'Include at least one thing that went badly', 'Record topics, actions and who does what', and 7. Supervision.",
"evidence":"Sent agenda emails · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Prepare and send an agenda in advance","Update on actions agreed last time"): {
"why":   "The Reference sheet: end the agenda with last week's actions and their status, in two lines. It makes the sessions cumulative rather than a series of unconnected hours, and it produces the record of change that your reflections and the reflective essay draw on. Handbook §6.2 is mapped here. Without the loop, actions agreed in supervision quietly lapse, and the same problem returns three weeks later as if new.",
"s1":    "WATCH FOR — whether your supervisor refers back to what was agreed last time, and how they respond when an action was not done — curiosity about why, or moving on.\n\nWRITE DOWN — the actions from each session in a running list with owner and due date, and their status the following week.\n\nASK AFTERWARDS — 'when an action from supervision doesn't get done, what does that usually tell you?'",
"s2":    "YOU TAKE — keeping the running action list, and adding a short 'Last time' section to each agenda: action, owner, done / partly / not, and one line on why.\n\nTHEY HOLD — their own actions (a resource, a phone call, a decision) and accountability for those.\n\nWHY THAT SPLIT — the tracking is yours because it is your development being recorded. The supervisor's actions stay theirs, but listing them keeps both sides honest.",
"s3":    "YOU RUN IT — open or close each session with the action update, spending no more than a few minutes on it, with your supervisor listening.\n\nWHAT THEY ARE WATCHING FOR — actions marked 'done' that were half done, undone actions carried forward week after week without comment, and actions too vague to judge.\n\nSTEPPING IN LOOKS LIKE — 'that's been on the list three weeks — what's actually in the way?'",
"s4":    "YOU DO IT ALONE — carry every action from one session into the next agenda, report its status honestly, and treat a repeatedly undone action as an item worth discussing.\n\nPASS TEST — You closed the loop\n\nEVIDENCE TO FILE — agendas with a 'Last time' section; supervision records whose actions match the next agenda. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — a term of records with actions that are never mentioned again, so no one can tell what changed as a result of supervision.",
"s5":    "YOU CAN TEACH IT — you can explain why closing the loop makes supervision cumulative, how a run of action updates becomes evidence of development over the placement, and why a stuck action is information rather than failure.\n\nWHEN IT GOES WRONG — you can say what to do when actions keep slipping: check whether they were too big, too vague, or the wrong action, and redesign them in the session.",
"error": "Never referring back to last week's actions, so nothing accumulates.",
"feeds": "→ Feeds into 'Record topics, actions and who does what', the reflective essay (hers to write), and the mid-placement review.",
"evidence":"Agendas with action update · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Prepare and send an agenda in advance","Include at least one thing that went badly"): {
"why":   "The Reference sheet: the item you are avoiding is almost always the highest-value item. CORU SoP 4.3 (reflecting critically on your own practice) and PSI Code 4.1.2 are mapped here — read both for their exact wording. Ladany, Hill, Corbett and Nutt (1996, Journal of Counseling Psychology) found supervisees commonly withhold material from supervisors, including clinical mistakes; read the paper for the figures. Unwritten, the difficult item will not survive the first twenty minutes.",
"s1":    "WATCH FOR — how your supervisor responds when you or another trainee brings a mistake: whether they get curious, reassure too fast, or move straight to fixing. Notice whether they ever describe something of their own that went badly.\n\nWRITE DOWN — what made it easier or harder to raise, in your own notes only.\n\nASK AFTERWARDS — 'what's something that went badly early in your career that supervision helped you with?'",
"s2":    "YOU TAKE — putting one thing that went badly on the agenda in writing each week — a subtest mis-administered, a feedback meeting that landed badly, a decision you are unsure of — stated plainly without self-criticism.\n\nTHEY HOLD — deciding whether it needs action beyond supervision (correcting a report, contacting a family, reporting).\n\nWHY THAT SPLIT — naming it is your responsibility and the core of reflective practice. Whether it has consequences for a client is a professional judgement the supervisor is accountable for.",
"s3":    "YOU RUN IT — raise the difficult item yourself, early in the session rather than at the end, with your supervisor responding.\n\nWHAT THEY ARE WATCHING FOR — leaving it until the last five minutes, softening it until it is not recognisable, or only ever bringing minor errors while the real one stays off the list.\n\nSTEPPING IN LOOKS LIKE — 'let's take that one first — tell me exactly what happened, not what you should have done.'",
"s4":    "YOU DO IT ALONE — include at least one thing that went badly on every agenda, raise it without being prompted, and follow through on whatever it needs.\n\nPASS TEST — Not only successes\n\nEVIDENCE TO FILE — agendas showing the item; supervision records noting what was discussed and decided; your reflection on it (yours to write — prompts only here). Log against 7. Supervision and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a term of agendas that read like a success log, and a mid-placement review that raises a problem you never brought.",
"s5":    "YOU CAN TEACH IT — you can explain why non-disclosure undermines supervision (Ladany et al., 1996 — check the details in the source), why a written item is more likely to be raised, and how naming mistakes protects clients.\n\nWHEN IT GOES WRONG — you can say what to do if something serious went badly — a missed safeguarding concern — act first (Tusla as soon as practicable; the DLP does not discharge your duty), then bring it; supervision follows action, never replaces it.",
"error": "Omitting the difficult item from the agenda and then not raising it.",
"feeds": "→ Feeds into 'Record any ethical dilemma using the seven steps', 6. Ethical Practice, and the reflective essay (hers to write).",
"evidence":"Agendas · supervision records (Appendix 8) · Log sheet tagged 7. Supervision and 6. Ethical Practice"},

# ── 7. SUPERVISION · Keep supervision session records ──

("Keep supervision session records","Complete a record for every session"): {
"why":   "The Reference sheet treats the supervision record (Appendix 8) as both assessed and the only proof that the supervision standard was met. Written on the day it takes about ten minutes; reconstructed in June it is visibly reconstructed. The pass test's figure — nineteen for a 75-day placement — is roughly one per week of a four-day pattern; count your own placement weeks rather than assuming. Missing records leave no evidence that supervision happened.",
"s1":    "WATCH FOR — whether your supervisor keeps their own note of sessions, what they record, and how quickly after the session they write it.\n\nWRITE DOWN — a list of all expected sessions for the placement (one per placement week), ticked off as each record is completed.\n\nASK AFTERWARDS — 'what's in your supervision notes that isn't in mine, and should it be?'",
"s2":    "YOU TAKE — writing every record within the day: date (DD/MM/YYYY), duration, format, who was present, items discussed, decisions, actions.\n\nTHEY HOLD — checking the record is accurate, correcting anything they would put differently, and countersigning.\n\nWHY THAT SPLIT — the record is yours because it is your evidence and your learning. The supervisor's check is what makes it a shared account rather than one person's memory.",
"s3":    "YOU RUN IT — complete the record after each session and send or show it to your supervisor within the week, with them reading and correcting.\n\nWHAT THEY ARE WATCHING FOR — records that slip to Friday, then to 'batch them later'; records so brief they could describe any session; and informal contact never recorded.\n\nSTEPPING IN LOOKS LIKE — 'I haven't seen last week's or the week before — let's do them now before we start.'",
"s4":    "YOU DO IT ALONE — keep a complete, same-day set of records for every formal session and logged informal contact across the placement, so the count matches the weeks.\n\nPASS TEST — 19 for a 75-day placement\n\nEVIDENCE TO FILE — the full set of records in date order on the supervision record form (Appendix 8). Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — eleven records for a nineteen-week placement, several in identical wording, written the same week in June.",
"s5":    "YOU CAN TEACH IT — you can explain how to calculate the expected number for any placement length and pattern, why same-day records are more accurate and more credible, and how the sequence becomes evidence of development.\n\nWHEN IT GOES WRONG — you can say what to do when records are missing: write them now from agendas and emails, marked honestly as written late with the date written, and never present them as contemporaneous.",
"error": "Writing records up in bulk at the end of placement, so they are visibly reconstructed.",
"feeds": "→ Feeds into 'Get them co-signed', 'Keep to 30 minutes per placement day cumulatively', and the reflective essay (hers to write).",
"evidence":"Supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Keep supervision session records","Record topics, actions and who does what"): {
"why":   "The Reference sheet's error: recording what was discussed but not what was decided. A record of topics shows supervision happened; a record of decisions and named actions shows it changed something. Handbook §6.1 is mapped here. Vague actions ('think about the case') cannot be checked the following week, and a disputed recollection of who agreed to do what is exactly what a specific record prevents. Cases are identified by reference number, never by name.",
"s1":    "WATCH FOR — how your supervisor closes each item: do they summarise the decision and who does what, or does the conversation move on without one?\n\nWRITE DOWN — for each item: the question, the decision, who does what, and by when (DD/MM/YYYY).\n\nASK AFTERWARDS — 'can we agree the actions out loud at the end, so we both write the same thing?'",
"s2":    "YOU TAKE — reading back the actions in the last five minutes and writing them into the record with owner and date; asking for a short email of agreed actions if that helps you (a reasonable workflow request, as the Reference sheet puts it).\n\nTHEY HOLD — decisions that are theirs to make (case allocation, whether to contact a family, risk) and their own actions.\n\nWHY THAT SPLIT — writing it down is yours. Who decides is part of the record: a supervisor's decision recorded as yours, or vice versa, causes problems later.",
"s3":    "YOU RUN IT — close each session by reading the actions back and write the record the same day, with your supervisor confirming.\n\nWHAT THEY ARE WATCHING FOR — actions with no owner, no date, or no verb you can check ('consider', 'reflect on'); children named instead of referenced; third-party detail that belongs in the case file.\n\nSTEPPING IN LOOKS LIKE — ''look into it' isn't an action — what will you actually do, and by when?'",
"s4":    "YOU DO IT ALONE — produce records where every item has a decision or an explicit 'no decision yet', and every action has an owner, a checkable verb and a date.\n\nPASS TEST — Actions are specific\n\nEVIDENCE TO FILE — supervision records (Appendix 8) with an actions section; the next agenda's 'Last time' update. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — a record reading 'discussed case, discussed report, discussed wellbeing' with nothing decided and nothing to follow up.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between a topic record and a decision record, what makes an action specific, and what must not go into supervision records (names, third-party detail, personal health detail — PSI Code 1.2.6 and 1.2.8 as mapped on the Reference sheet).\n\nWHEN IT GOES WRONG — you can say what to do when you and your supervisor remember a decision differently: go back to the record, correct it together, and agree to read back actions in future.",
"error": "Recording what was discussed but not what was decided, or by whom.",
"feeds": "→ Feeds into 'Update on actions agreed last time', 'Get them co-signed', and 7. Supervision evidence.",
"evidence":"Supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Keep supervision session records","Get them co-signed"): {
"why":   "A record signed by both people is evidence; one written only by the trainee is a claim. The Reference sheet's advice is to get records signed periodically rather than all at the end: a signature each month is administration, a run of unsigned records in June is a problem. The row maps this to Handbook Appendix 8. The Appendix 4 lesson applies — an 84-day log still awaiting countersignature is exactly the position to avoid repeating.",
"s1":    "WATCH FOR — how your supervisor handles paperwork: do they sign on the spot, take things away, or need reminders? Notice what they check before signing.\n\nWRITE DOWN — the date each record was signed, and which records are outstanding.\n\nASK AFTERWARDS — 'would it be easier for you to sign records monthly at the end of a session, or as I send them?'",
"s2":    "YOU TAKE — keeping a signature tracker, bringing unsigned records to supervision at a fixed interval (monthly works), and making signing take two minutes.\n\nTHEY HOLD — the signature, and any corrections before they sign.\n\nWHY THAT SPLIT — you carry the consequence if signatures are missing, so the administration is yours. The signature is theirs because it confirms the account is accurate — they should not sign what they have not read.",
"s3":    "YOU RUN IT — set a monthly signing point in the contract or diary and bring the records, with your supervisor reading and signing in the session.\n\nWHAT THEY ARE WATCHING FOR — waiting to be asked, bringing a large bundle at once, or records the supervisor disagrees with presented for signature without discussion.\n\nSTEPPING IN LOOKS LIKE — 'leave these with me' — and you agreeing a date by which you'll collect them.",
"s4":    "YOU DO IT ALONE — keep every record countersigned within about a month of the session, with no backlog at the end of placement, and chase outstanding signatures without awkwardness.\n\nPASS TEST — Signed, not just written\n\nEVIDENCE TO FILE — the countersigned supervision records (Appendix 8); your signature tracker. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — the last week of placement with twelve unsigned records and a supervisor on leave.",
"s5":    "YOU CAN TEACH IT — you can explain why countersignature matters (shared accountability, evidential weight), why monthly beats final-week, and how the same habit applies to Appendix 4 and Appendix 7.\n\nWHEN IT GOES WRONG — you can say what to do when signatures are outstanding at the end: list them, agree a date with your supervisor, tell UCD if they cannot be obtained, and do not sign on anyone's behalf.",
"error": "Leaving all countersignature to the final week.",
"feeds": "→ Feeds into 'Complete a record for every session', the end-of-placement submission, and the Appendix 4 countersignature habit.",
"evidence":"Countersigned supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Keep supervision session records","Tag which of the four components the session covered"): {
"why":   "The pass test's shorthand — E, S, Ev, Sg — tags each record as educative, supportive, evaluative or safeguarding (Handbook §6.1 is mapped here; check its wording). Tagging costs nothing at the time and means that in December you can see by filtering whether you ever had evaluative feedback or safeguarding discussion. The Reference sheet makes the same point for competency tags: supervision is evidence, not just support. Untagged, a gap stays invisible.",
"s1":    "WATCH FOR — which components each session actually covered, as opposed to what the agenda intended. A session about a report can be educative and evaluative; one after a difficult visit can be supportive and safeguarding.\n\nWRITE DOWN — the tags on each record, and the competency tags (1–8) alongside.\n\nASK AFTERWARDS — 'looking at this month's tags, which component have we under-done?'",
"s2":    "YOU TAKE — tagging each record with the components and the competencies it touched, and reviewing the pattern monthly.\n\nTHEY HOLD — confirming or amending the tags when they countersign, particularly Ev, since that is their judgement.\n\nWHY THAT SPLIT — tagging is a quick self-audit you can do alone. The supervisor's check stops you tagging a session as evaluative when no evaluation of your standard was actually given.",
"s3":    "YOU RUN IT — tag each record and bring a monthly tally to supervision, with your supervisor reviewing the balance.\n\nWHAT THEY ARE WATCHING FOR — every session tagged with all four (which means the tags mean nothing), or a month with no Sg tag in a caseload of school visits.\n\nSTEPPING IN LOOKS LIKE — 'I wouldn't call that session evaluative — I didn't give you a view on your standard. Let's do that next time.'",
"s4":    "YOU DO IT ALONE — tag every record accurately, notice when a component has been absent for several weeks, and put it on the next agenda.\n\nPASS TEST — E, S, Ev, Sg\n\nEVIDENCE TO FILE — tagged supervision records (Appendix 8); a monthly tally. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — records with no tags, or all four on every record, and no way to show what kind of supervision you received.",
"s5":    "YOU CAN TEACH IT — you can explain the four components, how they relate to Proctor's (1986) normative, formative and restorative functions (approximately), and how tagging turns records into an audit of the supervision itself.\n\nWHEN IT GOES WRONG — you can say what to do when the tally shows a gap: name the missing component on the next agenda with a specific request.",
"error": "Tagging every session with all four components so the tags show nothing.",
"feeds": "→ Feeds into 'Know the four components expected', 'Prepare and send an agenda in advance', and 7. Supervision evidence.",
"evidence":"Tagged supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

("Keep supervision session records","Record any ethical dilemma using the seven steps"): {
"why":   "PSI Code of Professional Ethics (2025) Appendix A sets out a seven-step ethical decision-making procedure, and the Reference sheet maps PSI 3.6.1 as requiring a systematic procedure; copy the step wording from the Code (reproduced on the Reference sheet), not from memory. The Reference sheet's point: a single well-written dilemma entry is worth more than twenty routine records, and Ethical Practice is hard to evidence any other way. A dilemma recorded as 'discussed a tricky case' shows no reasoning.",
"s1":    "WATCH FOR — how your supervisor reasons through a dilemma aloud: do they identify who is affected, name the clauses in tension, generate more than one option? Notice which Appendix A steps they do intuitively and which they skip.\n\nWRITE DOWN — the dilemma in one sentence without identifying details, then each step as it is discussed.\n\nASK AFTERWARDS — 'which step do you think trainees most often skip, and what does it cost?'",
"s2":    "YOU TAKE — drafting the dilemma entry using all seven Appendix A step headings, filling in your reasoning at each, cases by reference number only.\n\nTHEY HOLD — the decision where the case is theirs, and any action that must happen outside supervision.\n\nWHY THAT SPLIT — the structured reasoning is yours to practise and evidence. Where a dilemma involves child protection, the action is not a supervision matter: report to Tusla as soon as practicable, and telling the DLP does not discharge your duty. Supervision follows action.",
"s3":    "YOU RUN IT — bring a dilemma to supervision, work it through the seven steps yourself, and write the entry, with your supervisor challenging each step.\n\nWHAT THEY ARE WATCHING FOR — jumping from the problem to the decision, only one option generated, clauses named without saying what they require, and no record of the outcome.\n\nSTEPPING IN LOOKS LIKE — 'you've told me what you did. What else could you have done, and which clause would each option have honoured?'",
"s4":    "YOU DO IT ALONE — recognise a dilemma when it arises, record it through all seven steps, and complete the entry once the outcome is known.\n\nPASS TEST — All seven, from PSI Appendix A\n\nEVIDENCE TO FILE — a dilemma entry in the supervision records (Appendix 8), countersigned; any reflection on it is yours to write. Log against 7. Supervision and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — an entry that states the problem and what you decided, with steps three to six missing and no Code clause named.",
"s5":    "YOU CAN TEACH IT — you can walk a peer through the Appendix A steps using an anonymised example, explain why generating options matters more than the decision, and explain why a safeguarding concern is acted on first and recorded after.\n\nWHEN IT GOES WRONG — you can say what to do when a dilemma entry reveals a poor decision: record it honestly, note what you would do differently, and discuss any remedial action with your supervisor.",
"error": "Recording a dilemma as a problem and a decision with none of the reasoning steps between them.",
"feeds": "→ Feeds into 6. Ethical Practice evidence, 'Include at least one thing that went badly', and the reflective essay (hers to write).",
"evidence":"Dilemma entry in supervision records (Appendix 8) · Log sheet tagged 7. Supervision and 6. Ethical Practice"},

# ── 7. SUPERVISION · Observe your supervisor with a client ──

("Observe your supervisor with a client","Arrange it in the first weeks"): {
"why":   "The Reference sheet summarises PSI Accreditation 3.3.9 as requiring observation in both directions; trainees routinely complete being observed and skip observing. Handbook §6.2 is mapped here. Asking vaguely ('could I observe you sometime?') produces agreement and no date. Family consent must be arranged by your supervisor, so it needs time. Left to the end of the Cavan placement (to 18/12/2026), it will not happen.",
"s1":    "WATCH FOR — which parts of your supervisor's diary in the first weeks offer good observation opportunities: a feedback meeting, a consultation, a first meeting with a wary parent, a session in a special setting.\n\nWRITE DOWN — two or three candidate events with dates, and what you would learn from each.\n\nASK AFTERWARDS — 'which kind of meeting do you think I'd learn most from watching you in at this stage?'",
"s2":    "YOU TAKE — asking in week one for a specific kind of event, writing agreed dates into the contract, and linking one where possible to a special-education setting to help with PSI 3.3.6.\n\nTHEY HOLD — choosing the case, seeking family and school consent, and deciding whether your presence is appropriate.\n\nWHY THAT SPLIT — asking early and specifically is yours. Consent and suitability are the supervisor's professional responsibility to the family.",
"s3":    "YOU RUN IT — make the request in the contracting meeting with specific events in mind, and follow up until a date is in the diary, with your supervisor arranging consent.\n\nWHAT THEY ARE WATCHING FOR — vague requests, waiting to be offered, and leaving it until the final month.\n\nSTEPPING IN LOOKS LIKE — 'I've a feedback meeting on the third week — I'll ask the family this week, put it in your diary.'",
"s4":    "YOU DO IT ALONE — arrange observations of your supervisor in the first weeks of every placement, with dates agreed and consent in hand before the caseload builds.\n\nPASS TEST — Front-loaded, as the handbook expects\n\nEVIDENCE TO FILE — observation dates in the signed contract; the Appendix 7 forms for each observation. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — the last week of placement, no observation of your supervisor done, and one of the 3.3.9 requirements unmet.",
"s5":    "YOU CAN TEACH IT — you can explain why observation is front-loaded (you need the learning before you face the situation), how to ask specifically, and how to use observations to widen setting experience.\n\nWHEN IT GOES WRONG — you can say what to do when a planned observation falls through: ask for the next similar event immediately, and if none arises, raise it as a requirement, not a favour.",
"error": "Asking vaguely to observe 'sometime' and never getting a date.",
"feeds": "→ Feeds into 'Agree a focus before observing', PSI 3.3.6 setting coverage, and Appendix 7.",
"evidence":"Signed contract · Appendix 7 · Log sheet tagged 7. Supervision"},

("Observe your supervisor with a client","Agree a focus before observing"): {
"why":   "The Reference sheet: watch for process, not content. You already know what a standardised administration looks like; what you do not know is how they manage the room, the interruption, the run of wrong answers. CORU SoP 5.8 is mapped here — read it for its wording. Bandura's (1977, Social Learning Theory) account of observational learning puts attention first: without a focus, you watch everything and learn little.",
"s1":    "WATCH FOR — the moments linked to your agreed focus: how they open with a wary parent, what they say when a child refuses, how they decline to give a score on the day, how they close a meeting that has gone badly.\n\nWRITE DOWN — the focus agreed beforehand, and every moment that relates to it, with verbatim phrases where possible.\n\nASK AFTERWARDS — 'was that a typical example of how you handle that, or did something about this case change it?'",
"s2":    "YOU TAKE — choosing a focus from your own development needs (supervision records and agendas will show them) and proposing it before the observation.\n\nTHEY HOLD — refining it to fit the event, and telling you if the case makes the focus inappropriate or unlikely to arise.\n\nWHY THAT SPLIT — the focus should come from your learning needs, which you know. The supervisor knows the case and whether the moment you want to see is likely to happen.",
"s3":    "YOU RUN IT — agree the focus with your supervisor before the observation, observe against it, and debrief against it, with them adjusting where needed.\n\nWHAT THEY ARE WATCHING FOR — a focus so broad it is not a focus ('how you do assessments'), or one on content you already know rather than process.\n\nSTEPPING IN LOOKS LIKE — 'you know the WISC — watch what I do when the parent starts to cry, if she does.'",
"s4":    "YOU DO IT ALONE — set a specific, process-focused aim for every observation, tied to your development needs, and record against it.\n\nPASS TEST — You knew what you were watching for\n\nEVIDENCE TO FILE — the focus written on the Appendix 7 form before the observation; notes against it. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an Appendix 7 form that says 'observed an assessment, very useful' with nothing specific learned.",
"s5":    "YOU CAN TEACH IT — you can explain why a focus matters (Bandura, 1977, on attention in observational learning), the difference between process and content, and how to choose a focus from your own records.\n\nWHEN IT GOES WRONG — you can say what to do when the moment you wanted to see does not arise: observe what did happen, and ask your supervisor to talk you through how they would have handled the moment.",
"error": "Watching the content you already know rather than the process you do not.",
"feeds": "→ Feeds into 'Record what they did that you would not have' and 'Ask afterwards why they did it that way'.",
"evidence":"Appendix 7 · Log sheet tagged 7. Supervision"},

("Observe your supervisor with a client","Record what they did that you would not have"): {
"why":   "The value of observation lies in the gap between what you would have done and what an experienced practitioner did. General admiration ('she was very good with the parent') records nothing you can use. CORU SoP 4.3 is mapped here — reflecting critically on your own practice. The Reference sheet advises writing verbatim phrases: the actual words someone uses to decline to give a score on the day are more useful than a principle about managing expectations.",
"s1":    "WATCH FOR — the moments where your supervisor made a choice you would not have: waited instead of speaking, sat beside rather than opposite, named a feeling, changed plan, stopped a task.\n\nWRITE DOWN — the moment, what they did (verbatim phrases where possible), and what you would have done instead.\n\nASK AFTERWARDS — 'I'd have kept going at that point — what made you stop?'",
"s2":    "YOU TAKE — writing the notes during or immediately after the observation, and completing your section of the Appendix 7 form on the day.\n\nTHEY HOLD — checking you have not recorded identifying detail about the family or child, and confirming your account of what happened.\n\nWHY THAT SPLIT — the reflection is yours; no one else can say what you would have done. The supervisor protects the family's information, which your notes must respect.",
"s3":    "YOU RUN IT — after the observation, write two or three specific differences between their practice and yours, and share them in the debrief, with your supervisor responding.\n\nWHAT THEY ARE WATCHING FOR — notes that praise rather than analyse, notes that summarise the case, and identifying details in your record.\n\nSTEPPING IN LOOKS LIKE — ''good rapport' isn't a note — what exactly did I do in the first two minutes?'",
"s4":    "YOU DO IT ALONE — record specific moments, verbatim where possible, where your supervisor's practice differed from what you would have done, and name what you will adopt.\n\nPASS TEST — Specific, not general admiration\n\nEVIDENCE TO FILE — your section of the Appendix 7 form, completed on the day (yours to write; prompts only here). Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an Appendix 7 section left blank until June, or completed with 'very informative, excellent rapport'.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between admiration and analysis, why verbatim phrases are useful, and how to turn an observation into a technique you then use.\n\nWHEN IT GOES WRONG — you can say what to do when you disagree with something you observed: note it, raise it respectfully in the debrief, and treat the answer as learning either way.",
"error": "Recording general admiration instead of specific moments you would have handled differently.",
"feeds": "→ Feeds into 'Ask afterwards why they did it that way', Appendix 7, and the reflective essay (hers to write).",
"evidence":"Appendix 7 · Log sheet tagged 7. Supervision"},

("Observe your supervisor with a client","Ask afterwards why they did it that way"): {
"why":   "The Reference sheet: experienced practitioners make moves automatically and often have not put them into words until asked. Polanyi (1966, The Tacit Dimension) — 'we can know more than we can tell' — and Schön (1983, The Reflective Practitioner) on reflection-in-action describe the same gap. CORU SoP 4.5 is mapped here. If you do not ask, you copy the surface of what they did without the reasoning that makes it transferable.",
"s1":    "WATCH FOR — the decision points: a change of tack, a pause before speaking, a question not asked, a task abandoned. These are the moments with reasoning behind them.\n\nWRITE DOWN — two or three decision points, each as a question you want to ask ('you changed tack when she mentioned the older brother — what were you thinking?').\n\nASK AFTERWARDS — the questions you wrote down, starting with the one you are least sure about.",
"s2":    "YOU TAKE — preparing the questions, booking ten minutes for the debrief the same day, and writing up the answers.\n\nTHEY HOLD — deciding how much of their reasoning about the case can be shared, particularly where it involves confidential family information.\n\nWHY THAT SPLIT — the curiosity is yours. Some reasoning rests on information you are not party to, and the supervisor decides what can be said.",
"s3":    "YOU RUN IT — lead the debrief with your questions, listen, and ask follow-ups, with your supervisor explaining.\n\nWHAT THEY ARE WATCHING FOR — questions about content ('what score did he get?') instead of decisions, questions framed as criticism, and debriefs postponed until the detail has faded.\n\nSTEPPING IN LOOKS LIKE — 'good question — and what would you have done if I'd kept going?'",
"s4":    "YOU DO IT ALONE — debrief every observation on the same day with specific questions about decisions, and record the reasoning you were given.\n\nPASS TEST — You asked\n\nEVIDENCE TO FILE — the debrief notes on the Appendix 7 form; a supervision record if the debrief used supervision time. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an observation with no debrief, so you can describe what they did but not why.",
"s5":    "YOU CAN TEACH IT — you can explain why the question is where the learning is (Polanyi, 1966; Schön, 1983), how to phrase it so it invites reasoning rather than defence, and how to use the answer.\n\nWHEN IT GOES WRONG — you can say what to do when your supervisor cannot articulate why: ask what they noticed first, or what would have made them do it differently.",
"error": "Not asking about the decisions you noticed, so you learn the what and not the why.",
"feeds": "→ Feeds into 'Record what they did that you would not have', 7. Supervision, and your own practice in 5. Working with Others.",
"evidence":"Appendix 7 debrief notes · supervision records (Appendix 8) · Log sheet tagged 7. Supervision"},

}
