"""Supervision, part B — micro-skills for five macro skills:
Be observed with a client · Raise immediate concerns out of session ·
Contribute to peer and group supervision · Complete Appendix 6 before and after ·
Write the reflective learning essay.

Keyed (macro skill name, micro-skill name), in the micro.py format from HANDOVER.md.
The Appendix 6 and reflective essay rows are scaffolds only: the ratings, targets,
reflections and essay text are the trainee's own to write.
"""

MICRO = {

# ── 7. SUPERVISION · Be observed with a client ──

("Be observed with a client","Arrange both observations early"): {
"why":   "Observation is the only point at which your supervisor sees what you actually do rather than your account of it; every other supervision conversation passes through your own report. The UCD Handbook §6.2 is the reference mapped here — read it for the exact number and timing the programme sets rather than relying on this row. An observation in the last fortnight produces feedback you have no time left to act on, and the Appendix 7 form then records a comment with no follow-through.",
"s1":    "WATCH FOR — how your supervisor slots observations into the diary: which kinds of visit they think suit it (a consultation, a parent meeting, part of an assessment), and how much notice the school and family need so that consent for a second adult in the room is sought properly.\n\nWRITE DOWN — the dates proposed, the activity, who has to agree to the observer being present, and where the Appendix 7 form will be kept.\n\nASK AFTERWARDS — 'when in a placement have you found observation most useful to a trainee, and why then?'",
"s2":    "YOU TAKE — raising observation at the first supervision session, proposing two or more dates in the first month, and choosing an ordinary piece of work rather than a showcase.\n\nTHEY HOLD — the final choice of session, checking that consent for their presence is in place, and completing their half of Appendix 7.\n\nWHY THAT SPLIT — the timing is your responsibility because an early observation serves your learning. Whether a given family or school can accommodate an observer is a service judgement.",
"s3":    "YOU RUN IT — book the first observation in the opening weeks of the Cavan placement (05/10/2026 onwards) and the second with enough weeks left to act on what comes out of it; put both in the supervision record.\n\nWHAT THEY ARE WATCHING FOR — dates that keep sliding because 'the right case' has not come up, or an over-prepared session chosen to look polished.\n\nSTEPPING IN LOOKS LIKE — 'the parent meeting on Tuesday is ordinary enough — shall I just come to that one?'",
"s4":    "YOU DO IT ALONE — within the first month the first observation is booked and dated, the second is scheduled with time to act on it, and consent for the observer is arranged through the usual service route.\n\nPASS TEST — Booked in the first month\n\nEVIDENCE TO FILE — the dated booking in the supervision record, then the completed Appendix 7 forms. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — both observations crammed into the last fortnight in December, with no time to show any change in practice before the placement ends on 18/12/2026.",
"s5":    "YOU CAN TEACH IT — you can explain to a newer trainee why the minimum is not a target, why early observation is worth more than polished observation, and how to ask for it in week one without it sounding like a request for approval.\n\nWHEN IT GOES WRONG — an observation is cancelled (child absent, school closure). Rebook at the same session, not 'when things settle'. Record the cancellation and new date in the supervision record so the gap is explained.",
"error": "Waiting for the ideal case, so that both observations fall at the end of placement.",
"feeds": "→ Feeds into 'Request a focus you find hard', 'Act on the feedback and say so next time', and the Appendix 7 trainee section.",
"evidence":"Supervision record — observation dates · Appendix 7 · Log sheet tagged 7. Supervision"},

("Be observed with a client","Request a focus you find hard"): {
"why":   "Feedback is only as useful as the question it answers: 'any feedback welcome' tends to produce reassurance, while 'watch how I handle a parent who disagrees' produces something you can use. CORU SoP 4.5 is the standard mapped here — read its full text on the Reference sheet. Choosing a focus you find hard is also evidence that you are directing your own development. Being observed only on administration, where you are already fluent, wastes the one chance to have someone see your weak spot.",
"s1":    "WATCH FOR — which parts of practice your supervisor finds hardest to teach by telling: managing a disagreement, pacing a feedback meeting, engaging a reluctant adolescent, handling silence. These are the areas where observation adds most.\n\nWRITE DOWN — a short list of your own candidate focuses, ranked by how uncomfortable they make you, with one concrete behaviour for each that an observer could watch.\n\nASK AFTERWARDS — 'which part of my work do you think you'd learn most from seeing?'",
"s2":    "YOU TAKE — naming the focus in writing before the session, as a behaviour an observer can see (for example 'how I respond when a parent rejects a recommendation').\n\nTHEY HOLD — agreeing whether the chosen session will actually show that behaviour, and adding a second focus if they have noticed something you have not.\n\nWHY THAT SPLIT — the focus is yours because self-direction is what is being assessed. Your supervisor may see a blind spot you cannot name, and their addition is part of the learning.",
"s3":    "YOU RUN IT — pick the session that exposes the hard skill, send the focus to your supervisor a few days before, and resist the urge to swap to an easier activity nearer the date.\n\nWHAT THEY ARE WATCHING FOR — a focus so broad it cannot be observed ('my rapport'), or a quiet switch back to standardised administration because it feels safer.\n\nSTEPPING IN LOOKS LIKE — '\"rapport\" is too wide for me to watch. Which moment in the meeting do you actually dread?'",
"s4":    "YOU DO IT ALONE — each observation has a written focus, chosen by you, on something you find hard and that the observer can see happen.\n\nPASS TEST — Not administration, which is easiest\n\nEVIDENCE TO FILE — the stated focus written at the top of your Appendix 7 section and in the supervision record. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — two observations of a cognitive assessment you have given many times, and feedback that says 'well administered, good rapport' and nothing you can change.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between a focus and a topic, and show a peer how to turn 'my feedback meetings' into 'how I explain a low score to a parent without softening it into meaninglessness'.\n\nWHEN IT GOES WRONG — the hard moment does not arise (the parent agrees with everything). Say so in your section of the form, take what feedback there is, and ask to keep the same focus for the next observation.",
"error": "Asking to be observed on the activity you are best at and inviting general feedback.",
"feeds": "→ Feeds into 'Receive critical feedback without defending' and into the targets you set in Appendix 6.",
"evidence":"Appendix 7 — stated focus · Supervision record · Log sheet tagged 7. Supervision"},

("Be observed with a client","Receive critical feedback without defending"): {
"why":   "Defending and collapsing cost you the same thing: the information. Stone and Heen (Thanks for the Feedback, 2014) describe how people reject feedback by arguing with the giver or the accuracy rather than hearing what is being said. CORU SoP 4.3 and PSI Code 3.5.2 are mapped here — read both in full. A trainee who argues each point in the room teaches their supervisor to give less feedback, and supervisors are likely to read defensiveness as a problem with using supervision.",
"s1":    "WATCH FOR — how your supervisor gives difficult feedback: whether they lead with the observation, the effect on the child or parent, or a question. Notice your own body and the first sentence that forms in your head.\n\nWRITE DOWN — the feedback word for word as it is said, before you interpret it. Mark anything you disagree with privately, for later, not now.\n\nASK AFTERWARDS — 'is there anything you held back today because you weren't sure how I'd take it?'",
"s2":    "YOU TAKE — listening, writing it down, and asking only clarifying questions ('what did you see that made you think that?'). No explanation of why you did it.\n\nTHEY HOLD — the content and framing of the feedback, and the pace at which it is given.\n\nWHY THAT SPLIT — your job in the room is to receive, not to respond on substance. The response comes the following week, once you have had time to think, which is when you can disagree properly if you still do.",
"s3":    "YOU RUN IT — after an observation, take the feedback, summarise it back in one or two sentences, and say when you will return to it. Stop there.\n\nWHAT THEY ARE WATCHING FOR — 'yes, but the child was tired', a justification after every point, or the opposite: agreeing with everything, apologising, and taking nothing specific away.\n\nSTEPPING IN LOOKS LIKE — 'you don't need to explain it now. Write down what I said and tell me next week what you make of it.'",
"s4":    "YOU DO IT ALONE — take critical feedback without arguing or apologising, record it accurately, ask one clarifying question, and return to it at the next session.\n\nPASS TEST — You listened\n\nEVIDENCE TO FILE — your verbatim note of the feedback in your Appendix 7 section and the supervision record. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — the supervision record shows a discussion of why the feedback was unfair, and nothing about what you will try.",
"s5":    "YOU CAN TEACH IT — you can explain why 'receive now, respond later' protects the information, name the common ways feedback gets deflected (Stone & Heen, 2014), and model a clarifying question that is not a defence in disguise.\n\nWHEN IT GOES WRONG — you catch yourself defending mid-sentence. Stop, say 'sorry, I'll take that away', and write it down. If you still disagree a week later, bring your reasoning to supervision calmly, with evidence.",
"error": "Explaining why you did it before you have finished hearing what was seen.",
"feeds": "→ Feeds into 'Act on the feedback and say so next time' and into CORU SoP 4.3 evidence in Appendix 6.",
"evidence":"Appendix 7 — trainee section · Supervision record · Log sheet tagged 7. Supervision"},

("Be observed with a client","Act on the feedback and say so next time"): {
"why":   "The return is what gets noticed: coming back the following week with what you tried is the difference between receiving feedback and using it. CORU SoP 4.3 is mapped here. The Reference sheet sets the top grade as a specific change in practice that followed an observation. A trainee who nods, fills in the form and changes nothing leaves no trace of learning in the record, and the next observation finds the same thing.",
"s1":    "WATCH FOR — how your supervisor follows up on feedback they have given earlier: do they ask, or wait for you to raise it? Notice which changes they consider meaningful and which they treat as cosmetic.\n\nWRITE DOWN — one change you will try, where you will try it (the next similar session), and how you will know whether it made a difference.\n\nASK AFTERWARDS — 'what would you need to see next time to know I've taken this on?'",
"s2":    "YOU TAKE — choosing the change, trying it in the next comparable session, and opening the following supervision with what happened.\n\nTHEY HOLD — judging whether the change addresses what they saw, and deciding whether to observe the same skill again.\n\nWHY THAT SPLIT — acting on feedback is the trainee's half of the contract. Only the observer can say whether the change reached what they were pointing at.",
"s3":    "YOU RUN IT — put the observation feedback as the first item on the next supervision agenda, report what you did differently and what you noticed, and record it.\n\nWHAT THEY ARE WATCHING FOR — a change that is a restatement of the feedback ('I'll be more aware of pace') rather than something done; or the feedback silently dropped.\n\nSTEPPING IN LOOKS LIKE — 'you said you'd pause after giving the scores. Did you, in the Thursday meeting? What happened?'",
"s4":    "YOU DO IT ALONE — within a week or two of each observation, you try a specific change, tell your supervisor unprompted, and the record shows the before and after.\n\nPASS TEST — Something changed\n\nEVIDENCE TO FILE — the supervision record entry reporting the change, cross-referenced to the Appendix 7 form. This is also raw material for the reflective essay. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — the second observation's feedback repeats the first almost word for word.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to turn a feedback comment into one behaviour, one setting and one sign of success, and explain why reporting back unprompted matters more than getting it right first time.\n\nWHEN IT GOES WRONG — the change did not work, or made things worse. Report that too: it is still acting on feedback. Ask in supervision what else to try, and record both attempts.",
"error": "Completing the form and never mentioning the feedback again.",
"feeds": "→ Feeds into 'Trace a change in practice to a specific reflection' in the reflective essay and 'Rate again at the end and compare' in Appendix 6.",
"evidence":"Supervision record — follow-up · Appendix 7 · Log sheet tagged 7. Supervision"},

# ── 7. SUPERVISION · Raise immediate concerns out of session ──

("Raise immediate concerns out of session","Know what counts as immediate here"): {
"why":   "Trainees rarely fail to raise a crisis because they missed it; more often they did not want to interrupt or were unsure it was serious enough. The UCD Handbook §6.2 is the reference mapped here — read its wording for the programme's requirement. The Reference sheet's test is deliberately low: if you are asking whether it is serious enough to interrupt someone, it is. The cost of an unnecessary call is minutes; the cost of waiting can be a child's safety.",
"s1":    "WATCH FOR — which situations your supervisor treats as needing a same-day call: a child protection or welfare concern, a disclosure, a child indicating intent to harm self or others, an escalating parent or school conflict, an error you have made with consequences.\n\nWRITE DOWN — the service's own list, if it has one, and any categories it adds for this area (for example contact with CAMHS or Tusla already open on a case).\n\nASK AFTERWARDS — 'what's something a trainee sat on that you wish they'd rung you about?'",
"s2":    "YOU TAKE — learning the categories (crisis, welfare concern, ethical dilemma) and, when in doubt, making the call rather than deciding alone that it can wait.\n\nTHEY HOLD — the judgement on anything borderline once you have raised it, and the decision about further escalation within the service.\n\nWHY THAT SPLIT — your part is not to under-call. Grading severity is where experience matters, and you only get that experience by bringing borderline cases forward.",
"s3":    "YOU RUN IT — for the first weeks in Cavan, raise any borderline concern with your supervisor the same day and say which category you think it falls into and why.\n\nWHAT THEY ARE WATCHING FOR — concerns held to the weekly session because they 'weren't really child protection', and ethical dilemmas (a school asking you to alter a report, a consent problem) not recognised as urgent.\n\nSTEPPING IN LOOKS LIKE — 'you were right to ring. Next time something like this, don't wait until Friday.'",
"s4":    "YOU DO IT ALONE — you can name the three kinds of concern that cannot wait, recognise them in the moment, and raise them the same day without talking yourself out of it.\n\nPASS TEST — Crisis, welfare concern, ethical dilemma\n\nEVIDENCE TO FILE — a supervision record note that the categories and service protocol were reviewed at induction. Log against 7. Supervision and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — an unexplained injury noted during an observation and first mentioned at supervision four days later.",
"s5":    "YOU CAN TEACH IT — you can explain the low threshold for interrupting, why trainees under-call, and the difference between 'immediate' (same day) and 'important' (next session).\n\nWHEN IT GOES WRONG — you realise you held something that should have been raised. Raise it now, act on any duty that still applies, and record honestly when you became aware and when you raised it.",
"error": "Deciding alone that a concern was not serious enough to interrupt your supervisor.",
"feeds": "→ Feeds into 'Know how to reach your supervisor out of session', 'Act first where the duty is yours', and 6. Ethical Practice.",
"evidence":"Supervision record — induction review · Log sheet tagged 7. Supervision and 6. Ethical Practice"},

("Raise immediate concerns out of session","Know how to reach your supervisor out of session"): {
"why":   "A concern that has to be raised the same day needs a route that works when your supervisor is in another school, on leave or in a meeting. The UCD Handbook §6.2 is mapped here. The Reference sheet notes that the supervision contract should say who covers; if it does not, find out before you need it. Discovering on the day that you only have an office email address wastes time a child may not have.",
"s1":    "WATCH FOR — how your supervisor is reached when out of the office, who covers when they are on leave, and whether the service has a senior psychologist or duty line for urgent queries.\n\nWRITE DOWN — mobile number, a named deputy and their number, the DLP for each school you visit, and the Tusla contact route for the area, kept on paper and on your service phone.\n\nASK AFTERWARDS — 'if I can't get you and it can't wait, who exactly do I ring next?'",
"s2":    "YOU TAKE — collecting the numbers in week one, keeping them with you in every school, and checking them against your diary so you know who covers on any given day.\n\nTHEY HOLD — writing the cover arrangement into the supervision contract and telling you when it changes (leave, courses).\n\nWHY THAT SPLIT — carrying the route is yours because you are the one who will need it. Cover depends on service rotas that only your supervisor can arrange.",
"s3":    "YOU RUN IT — at the start of each week, check who covers on each day you are in a school and confirm the DLP name for each visit.\n\nWHAT THEY ARE WATCHING FOR — a contact list that lives only in an email, a deputy never named, and no DLP name for a school you are visiting for the first time.\n\nSTEPPING IN LOOKS LIKE — 'I'm at a course on Wednesday. Who are you ringing if something comes up at the school that afternoon?'",
"s4":    "YOU DO IT ALONE — before every school day you have your supervisor's number, the named cover, the school DLP's name and the Tusla route, and you know which to use first.\n\nPASS TEST — You have the number\n\nEVIDENCE TO FILE — the supervision contract clause on out-of-session contact and cover. Do not log personal phone numbers in your own Log. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — a disclosure at 2.30pm, your supervisor unreachable, and nobody else's number on you.",
"s5":    "YOU CAN TEACH IT — you can explain why the route has to be set up before the day, what goes on a contact card, and why not reaching your supervisor never suspends a Children First duty.\n\nWHEN IT GOES WRONG — you cannot reach anyone. Act on any duty that is yours (DLP, and Tusla if at threshold; An Garda Síochána if a child is in immediate danger), record every attempt at contact with times, and tell your supervisor as soon as you reach them.",
"error": "Having only an office email address for your supervisor and no named cover.",
"feeds": "→ Feeds into 'Act first where the duty is yours' and 'Record the contact and what was agreed'.",
"evidence":"Supervision contract — cover clause · Log sheet tagged 7. Supervision"},

("Raise immediate concerns out of session","Act first where the duty is yours"): {
"why":   "Under the Children First Act 2015 a mandated person must report to Tusla as soon as practicable; telling the DLP does not discharge that duty, though a joint report can meet it. CORU SoP 1.17 is also mapped — read its full text. Supervision informs what you do and supports you afterwards; it does not replace the report or grant permission to make it. Waiting to consult first is the commonest way a trainee falls short of the duty.",
"s1":    "WATCH FOR — the order in which your supervisor acts on a concern: stop, record, DLP, Tusla, then supervision. Notice that the conversation with their own supervisor comes after the report, not before.\n\nWRITE DOWN — the sequence as this service practises it, and whether you are a mandated person in this role (check with UCD and the service rather than assuming).\n\nASK AFTERWARDS — 'when did you last act before you could talk it through, and how did you know that was right?'",
"s2":    "YOU TAKE — the actions that are your duty: stopping the activity, not questioning further, recording, telling the DLP, and reporting to Tusla or joining a joint report.\n\nTHEY HOLD — advice on the process, escalation if the DLP does not act, and review afterwards.\n\nWHY THAT SPLIT — the legal duty sits with the person who holds the concern. A supervisor can guide you, but cannot take the duty off you, and cannot make it wait.",
"s3":    "YOU RUN IT — in a live or role-played concern, follow the sequence to the end yourself, ringing your supervisor if reachable but not holding any step for them.\n\nWHAT THEY ARE WATCHING FOR — 'I'll run it past you first', continuing the assessment after a disclosure, or asking the child more questions to be sure.\n\nSTEPPING IN LOOKS LIKE — 'don't wait for me. Go to the DLP now, make sure a report goes in today, and we'll talk after.'",
"s4":    "YOU DO IT ALONE — where a concern meets the threshold you act the same day (DLP and Tusla report, jointly or yourself) and inform your supervisor, whether or not they were reachable beforehand.\n\nPASS TEST — Supervision informs, it does not replace\n\nEVIDENCE TO FILE — the timed record on the case file and the report reference, per service policy. Log against 7. Supervision and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a concern held overnight because your supervisor was at a course and you wanted their view first.",
"s5":    "YOU CAN TEACH IT — you can explain 'as soon as practicable', why the DLP route does not discharge a mandated person's duty, and why supervision follows action. Point peers to Children First National Guidance (DCYA, 2017) rather than your summary.\n\nWHEN IT GOES WRONG — you realise you waited. Act now, record the delay and the reason honestly, and bring it to supervision as a learning event rather than hiding it.",
"error": "Waiting to consult your supervisor before making a report that is yours to make.",
"feeds": "→ Feeds into 'Record the contact and what was agreed', 'Bring it to supervision afterwards, not instead', and 6. Ethical Practice.",
"evidence":"Timed record on case file · report reference · Log sheet tagged 7. Supervision and 6. Ethical Practice"},

("Raise immediate concerns out of session","Record the contact and what was agreed"): {
"why":   "The record of who you told, when and what was agreed is what shows the duty was met and the concern was handled; without it, a well-handled concern looks like an unhandled one. Handbook Appendix 8 is mapped here — check the form itself for its headings. The Reference sheet also advises writing a dilemma entry afterwards. A managed concern that exists only as a line in the day log is lost as evidence for Ethical Practice and Supervision.",
"s1":    "WATCH FOR — what your supervisor writes after an urgent contact: time of each call, who was spoken to, what was said, what each person agreed to do, and when they followed up.\n\nWRITE DOWN — the elements of a usable record, and where each part goes: the case file (per service policy), the supervision record, and an Appendix 8 dilemma entry.\n\nASK AFTERWARDS — 'if this record were read in a year by someone who wasn't there, what would they need?'",
"s2":    "YOU TAKE — writing the timed record of each contact and agreement the same day, and drafting your own Appendix 8 entry.\n\nTHEY HOLD — reviewing the record for completeness, adding their own note of the out-of-session contact, and countersigning where the form requires it.\n\nWHY THAT SPLIT — the person who made the calls holds the facts. Your supervisor checks that the record would stand up and that the agreed actions were completed.",
"s3":    "YOU RUN IT — after any out-of-session contact, record it the same day and bring it to the next formal session even though the matter is resolved.\n\nWHAT THEY ARE WATCHING FOR — no times, 'discussed with supervisor' with no content, agreed actions with no owner, and no Appendix 8 entry.\n\nSTEPPING IN LOOKS LIKE — 'what time did you ring me, and what did we agree you'd do next? Put that in, and who was doing each part.'",
"s4":    "YOU DO IT ALONE — every urgent contact has a record with time, person, content and agreed actions, and any dilemma is written up in Appendix 8 with your own reflection.\n\nPASS TEST — Time and content\n\nEVIDENCE TO FILE — case file record (per service policy), supervision record, Appendix 8 dilemma entry. The Appendix 8 reflection is yours to write. Log against 7. Supervision and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a managed disclosure that appears only as 'CP concern — DLP informed' in the day log.",
"s5":    "YOU CAN TEACH IT — you can show a peer what a complete contact record contains and explain why a resolved concern still goes to formal supervision and Appendix 8.\n\nWHEN IT GOES WRONG — you find a past concern was never written up properly. Write it now from your contemporaneous notes, date it as written today, and state that it was written later. Do not back-date.",
"error": "Recording that you raised a concern but not when, with whom, or what was agreed.",
"feeds": "→ Feeds into Appendix 8 dilemma entries, 'Work an ethical dilemma through a decision procedure', and the reflective learning essay.",
"evidence":"Case file record · Supervision record · Appendix 8 · Log sheet tagged 7. Supervision and 6. Ethical Practice"},

# ── 7. SUPERVISION · Contribute to peer and group supervision ──

("Contribute to peer and group supervision","Attend consistently"): {
"why":   "Peer supervision is the first thing dropped when placement gets busy, usually by everyone at once, after which the group stops existing. PSI Accreditation Standards 3.3.9 is the standard mapped here — read the clause itself for what the programme must provide. Attendance is most of the contribution. It also only counts if it can be evidenced: sessions not recorded cannot be counted toward supervision requirements later.",
"s1":    "WATCH FOR — how established peer or group supervision in the service or cohort runs: who convenes, how often, how cancellations are handled, and whether practising psychologists attend their own group.\n\nWRITE DOWN — the schedule, format (in person, online), convenor, and the ground rules agreed at the first meeting.\n\nASK AFTERWARDS — 'what has kept your peer group going, and what made previous ones stop?'",
"s2":    "YOU TAKE — putting every session in the diary as a fixed appointment, protecting it from school visits, and logging attendance the same day.\n\nTHEY HOLD — (your supervisor) agreeing that the time is protected within placement days, and counting it toward supervision where the programme allows.\n\nWHY THAT SPLIT — attending is entirely in your control. Whether peer time counts toward requirements is a programme and service decision you should confirm, not assume.",
"s3":    "YOU RUN IT — attend every scheduled session across the Cavan placement, and if a clash is unavoidable, send apologies in advance and rearrange the clash, not the group.\n\nWHAT THEY ARE WATCHING FOR — sessions quietly skipped for report writing, and a log that shows none of them.\n\nSTEPPING IN LOOKS LIKE — 'I see the peer group isn't in your diary this week. What's it been displaced by?'",
"s4":    "YOU DO IT ALONE — you attend peer supervision as a fixed commitment and each session is logged with date, format, and a brief note of what was discussed (anonymised).\n\nPASS TEST — Attendance is recorded\n\nEVIDENCE TO FILE — Appendix 8 entry for each session, per the Reference sheet guidance; check the form for its headings. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — you attended six sessions but logged none, and cannot evidence peer supervision at the end-of-year review.",
"s5":    "YOU CAN TEACH IT — you can explain why groups fail by gradual attrition, why logging is part of attending, and how to rescue a group that has lapsed (propose one date, one case, one convenor).\n\nWHEN IT GOES WRONG — the group stops meeting. Offer to convene the next session yourself, and tell your supervisor, so the gap is visible and can be addressed rather than silently lost.",
"error": "Attending but not logging, so the sessions cannot be evidenced.",
"feeds": "→ Feeds into 'Present a case at least once a trimester' and the supervision evidence in Appendix 8.",
"evidence":"Appendix 8 — peer sessions · Log sheet tagged 7. Supervision"},

("Contribute to peer and group supervision","Present a case at least once a trimester"): {
"why":   "Presenting is where you practise explaining a case to people who are not obliged to be kind about it, which later becomes multidisciplinary team work. CORU SoP 4.5 (seeking peer review) is mapped here. Listening to other people's cases is useful but does not evidence that you sought review of your own work. A case you have already solved wastes the group's time and your own.",
"s1":    "WATCH FOR — how experienced presenters structure a case: referral question, what was done, formulation and the framework behind it, where they are stuck, and the specific question for the group.\n\nWRITE DOWN — that structure as a one-page template, and how much anonymisation each presenter used (no names, no school, no identifying detail).\n\nASK AFTERWARDS — 'what question did you want the group to answer, and did they answer it?'",
"s2":    "YOU TAKE — choosing a case you are stuck on, preparing a structured, anonymised presentation, and ending with one clear question.\n\nTHEY HOLD — (your supervisor) a check beforehand that the case is anonymised enough and that sharing it fits service policy.\n\nWHY THAT SPLIT — preparing and presenting is the skill. What may be shared outside the service is a governance question that your supervisor should confirm.",
"s3":    "YOU RUN IT — present at least once each trimester, allow time for preparation, bring the stuck part rather than the resolved part, and note what the group raised.\n\nWHAT THEY ARE WATCHING FOR — a narrative of everything you did with no question at the end, identifying detail, or a case chosen because it went well.\n\nSTEPPING IN LOOKS LIKE — 'what's the one thing you want them to help you with? Start with that.'",
"s4":    "YOU DO IT ALONE — each trimester you present an anonymised case with a structured account and a specific question, and record what you took away.\n\nPASS TEST — Listening does not evidence it\n\nEVIDENCE TO FILE — Appendix 8 entry naming the date, that you presented, the question, and what changed in the case as a result. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — a year of regular attendance and no record of ever presenting your own work.",
"s5":    "YOU CAN TEACH IT — you can give a newer trainee the presentation structure, explain why the stuck part is the valuable part, and show how to anonymise a case properly.\n\nWHEN IT GOES WRONG — the group does not answer your question, or you realise mid-presentation that you have identified the school. Stop, ask the group not to record or repeat it, and tell your supervisor the same day.",
"error": "Presenting a case you have already resolved, so the group has nothing to work on.",
"feeds": "→ Feeds into 'Bring a case from an under-covered age band', 5. Working with Others, and multidisciplinary case discussion.",
"evidence":"Appendix 8 — case presented · Log sheet tagged 7. Supervision"},

("Contribute to peer and group supervision","Bring a case from an under-covered age band"): {
"why":   "UCD Table 3 age bands are the frame for breadth across the programme, and your own coverage record shows Early Years and Young Adult unevidenced so far. A case from a thin age band brought to peer supervision earns both a presentation and breadth evidence, and exposes you to reasoning you have had less practice with. Breadth cannot be added retrospectively, so this has to be planned: the case only exists if the Appendix 1 plan put you in contact with that age group.",
"s1":    "WATCH FOR — which age bands the other trainees' cases come from, and which questions come up in each (for example transition to school, or transition from post-primary). Notice whose reasoning is least familiar to you.\n\nWRITE DOWN — your own coverage against the Table 3 bands from your Log, and which band is thinnest.\n\nASK AFTERWARDS — 'what do you think about differently with a case at that age that I wouldn't think of?'",
"s2":    "YOU TAKE — mapping your coverage, flagging the thinnest band at your first Cavan supervision, and choosing a case from it to present when one arises.\n\nTHEY HOLD — (your supervisor) allocating work in that band where the service can, and confirming it is planned in Appendix 1.\n\nWHY THAT SPLIT — you know your gaps; the service controls the caseload. Coverage only happens if both sides plan for it at the start.",
"s3":    "YOU RUN IT — once you hold a case from the under-covered band, present it to the peer group with the age-specific question you are unsure about.\n\nWHAT THEY ARE WATCHING FOR — a case chosen from a thin band but presented as though age made no difference, or an identifying detail slipping through because the setting is small.\n\nSTEPPING IN LOOKS LIKE — 'what's different about this because of the child's age? Ask the group that.'",
"s4":    "YOU DO IT ALONE — you track your age-band coverage, bring at least one case from a thin band to peer supervision, and log it as both a presentation and breadth evidence.\n\nPASS TEST — It doubles as breadth evidence\n\nEVIDENCE TO FILE — Appendix 8 entry for the presentation; Log row tagged with the age band and 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — every case you present is primary-age, and the end-of-year review finds the same gaps as the start.",
"s5":    "YOU CAN TEACH IT — you can explain Table 3 breadth, why it cannot be evidenced after the fact, and how peer supervision can be used to deepen learning in a thin band once contact exists.\n\nWHEN IT GOES WRONG — no case in the thin band arises. Record that it was planned and did not happen, raise it in supervision, and carry it forward into the next Appendix 1 rather than inventing coverage.",
"error": "Presenting only from the age band you already know best.",
"feeds": "→ Feeds into Table 3 breadth, 'Carry the targets into the next Placement Plan', and PSI 3.3.6 setting coverage planning.",
"evidence":"Appendix 8 · Appendix 1 · Log sheet tagged 7. Supervision with age band"},

("Contribute to peer and group supervision","Offer something useful to someone else's case"): {
"why":   "The useful contribution is usually a question, not a suggestion: 'what did the child say about it?' opens a case, while 'have you tried X?' tends to close it. CORU SoP 5.8 (mentoring and supervision) is mapped here. Proctor (Group supervision, 2nd ed., 2008) and Hawkins and McMahon (Supervision in the helping professions, 2020) discuss group process in supervision. A group that converges too quickly on one explanation stops thinking, and someone has to say so.",
"s1":    "WATCH FOR — which contributions change how a presenter sees their case, and which are ignored. Notice the ratio of questions to advice, and the moment a group settles on one explanation.\n\nWRITE DOWN — two or three questions that opened a case up, word for word, to reuse. Nothing identifying about other people's cases.\n\nASK AFTERWARDS — (of a presenter) 'which comment was actually useful to you, and why?'",
"s2":    "YOU TAKE — listening to the whole presentation, then offering one question that tests the formulation, or naming a hypothesis the group has not considered.\n\nTHEY HOLD — (the presenter) the decision on what to take away; (the convenor) managing time and turn-taking.\n\nWHY THAT SPLIT — your role is to widen someone else's thinking, not to take the case over. The presenter owns the case and the choice.",
"s3":    "YOU RUN IT — in each session, contribute at least once to someone else's case, and at least once in a while name the group process ('we've all agreed quite quickly — what would make us wrong?').\n\nWHAT THEY ARE WATCHING FOR — advice given before the question has been asked, a contribution that retells your own case, or silence all session.\n\nSTEPPING IN LOOKS LIKE — 'can you turn that suggestion into a question for her?'",
"s4":    "YOU DO IT ALONE — you contribute to others' cases with questions that open them up, and you notice and name premature agreement in the group.\n\nPASS TEST — You contributed\n\nEVIDENCE TO FILE — a brief line in your Appendix 8 peer entry noting your contribution in general terms (no case details). Log against 7. Supervision and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — you attend every session and say nothing, or say 'have you tried a reward chart?' before the presenter has finished.",
"s5":    "YOU CAN TEACH IT — you can explain why questions help more than solutions, give examples of opening questions, and describe how a group can converge too early.\n\nWHEN IT GOES WRONG — a contribution lands badly and the presenter becomes defensive. Acknowledge it, rephrase as a question, and check with them afterwards. If group dynamics are persistently unhelpful, raise it with the convenor.",
"error": "Offering a solution before understanding the case, which closes the discussion down.",
"feeds": "→ Feeds into 5. Working with Others, consultation skills, and CORU SoP 5.8.",
"evidence":"Appendix 8 — peer session · Log sheet tagged 7. Supervision and 5. Working with Others"},

# ── 7. SUPERVISION · Complete Appendix 6 before and after ──
# Scaffold only. The ratings, targets and comparison text are the trainee's own to write.

("Complete Appendix 6 before and after","Rate all eight before day one, dated"): {
"why":   "The before-and-after structure is the point of the self-evaluation: the comparison is the evidence of development, and it only works if the first rating was genuinely made first. The UCD Handbook §4.5a is mapped here — read its wording, and the form itself, for exactly what is rated. A rating written after the placement has started is visibly retrospective and forfeits the comparison. This row is a scaffold: the ratings are yours to make and write.",
"s1":    "WATCH FOR — how the form is laid out: which competencies it lists, what the rating descriptors actually say, and where the date goes. The Reference sheet cautions that the Handbook describes a range without explicitly setting out a five-point scale, so read the descriptors rather than assuming one.\n\nWRITE DOWN — the exact descriptor wording and any questions to ask the programme about the scale.\n\nASK AFTERWARDS — (your supervisor) 'how do you read a before-rating when it arrives on your desk?'",
"s2":    "YOU TAKE — completing and dating the before ratings for every competency listed, yourself, before the first Cavan placement day (05/10/2026) or at the very latest in week one.\n\nTHEY HOLD — reading the ratings at the first supervision session and discussing them; not writing them for you.\n\nWHY THAT SPLIT — self-evaluation is only evidence if it is your own judgement. Your supervisor's role is to see it and use it to plan, which also makes the date credible.",
"s3":    "YOU RUN IT — sit down with your Roscommon Log, supervision records and end-of-year feedback, rate each competency against the form's own descriptors, date the document, and share it at the first supervision.\n\nWHAT THEY ARE WATCHING FOR — a form still blank at week three, one competency skipped because it felt hard to judge, or a date that does not match when it was actually written.\n\nSTEPPING IN LOOKS LIKE — 'can I see your before-ratings this week? We'll use them to plan the Appendix 1.'",
"s4":    "YOU DO IT ALONE — every competency on the form is rated by you, the document is dated before or in the first week of placement, and it has been seen by your supervisor.\n\nPASS TEST — Before, genuinely\n\nEVIDENCE TO FILE — the dated Appendix 6 (before), with the supervision record noting it was discussed. Your ratings and wording are your own. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — the before and after versions are both written in the same week in December.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why the date matters more than the number, why the form's descriptors should be quoted rather than paraphrased, and why you ask the programme about the scale instead of assuming it.\n\nWHEN IT GOES WRONG — you missed the start. Complete it now, date it truthfully, and say in the document that it was completed late and when. Do not back-date.",
"error": "Completing the 'before' rating after the placement has started and dating it as though it had not.",
"feeds": "→ Feeds into 'Rate honestly, including low', 'Name two or three priority targets', and 'Rate again at the end and compare'.",
"evidence":"Appendix 6 (before, dated) · Supervision record · Log sheet tagged 7. Supervision"},

("Complete Appendix 6 before and after","Rate honestly, including low"): {
"why":   "A low rating at the start feels like an admission, but it is what makes development visible; a trainee who rates high at the start has nothing to show at the end. CORU SoP 4.3 and PSI Code 4.1.3 are mapped here — read both in full. The Reference sheet notes that supervisors can read an inflated first rating as poor self-awareness, which is itself assessed. Boud, Keogh and Walker (1985) treat returning honestly to experience as the start of learning from it. The judgement is yours; this row only offers prompts.",
"s1":    "WATCH FOR — the gap between what you have done and what you have done independently. Notice where you have only observed, or done a task with close support, compared with where you have done it alone.\n\nWRITE DOWN — for each competency, one piece of evidence from your Log or supervision records that supports the rating you are considering, and one thing you have not yet done at all.\n\nASK AFTERWARDS — (your supervisor) 'where do you think I'm over- or under-rating myself?'",
"s2":    "YOU TAKE — rating each competency against the form's descriptors and your evidence, including low ratings where you have little or no experience.\n\nTHEY HOLD — a view on whether your ratings match what they have seen, offered for discussion rather than as a correction to your form.\n\nWHY THAT SPLIT — the rating is a measure of your self-awareness, so it has to be yours. Their view is calibration, and the discussion itself can be recorded in supervision.",
"s3":    "YOU RUN IT — rate each competency with one evidence point beside it, then check the whole set for consistency: are the ratings where you have least evidence also the lowest?\n\nWHAT THEY ARE WATCHING FOR — uniform middling ratings that avoid any judgement, high ratings on areas you have barely touched (for example organisational or systemic work), and ratings justified by effort rather than evidence.\n\nSTEPPING IN LOOKS LIKE — 'what have you actually done in this area on your own? Does the rating match that?'",
"s4":    "YOU DO IT ALONE — each rating reflects your evidence, low where experience is thin, and you can defend any rating with a specific example.\n\nPASS TEST — An honest low start shows trajectory\n\nEVIDENCE TO FILE — Appendix 6 (before), in your own words, and a supervision record note that ratings were discussed. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — every competency rated near the top at the start of Year 1, so the end rating cannot show movement and the self-evaluation reads as unaware.",
"s5":    "YOU CAN TEACH IT — you can explain why an honest low rating is a strength in this document, how to anchor each rating to evidence, and why the descriptors must be read in the Handbook's own words.\n\nWHEN IT GOES WRONG — your supervisor thinks a rating is inflated or too harsh. Discuss the evidence, then decide yourself whether to revise. If you keep your rating, note the discussion in the supervision record.",
"error": "Rating yourself high at the start because a low rating feels like failure.",
"feeds": "→ Feeds into 'Name two or three priority targets' and 'Rate again at the end and compare'.",
"evidence":"Appendix 6 (before) · Supervision record · Log sheet tagged 7. Supervision"},

("Complete Appendix 6 before and after","Name two or three priority targets"): {
"why":   "A target is only useful if you can tell at the end whether you met it: 'improve at formulation' cannot be evidenced, whereas a target with a named framework, a number of cases and a visible product can. CORU SoP 4.3 is mapped here. The Reference sheet suggests drawing targets from the development areas identified at your end-of-year review. Too many targets dilute effort; two or three priorities give a comparison that writes itself. The targets are yours to set and word.",
"s1":    "WATCH FOR — how your supervisor frames development goals for themselves or other trainees: whether each has an action, a setting, an amount and a product you could point to.\n\nWRITE DOWN — your development areas from the end-of-year review, the lowest before-ratings, and which of these the Cavan placement can realistically support.\n\nASK AFTERWARDS — 'which of these could this placement actually give me the work to meet?'",
"s2":    "YOU TAKE — choosing two or three targets and wording each so that it names what you will do, how often or in which cases, and what evidence will show it.\n\nTHEY HOLD — a judgement on whether the service can provide the opportunities each target needs, and agreement to plan for them.\n\nWHY THAT SPLIT — the priorities come from your self-evaluation, so they are yours. Whether a target is achievable here depends on caseload and settings the service controls.",
"s3":    "YOU RUN IT — draft the targets, test each with the question 'how will I know in December?', and bring them to the first supervision session for discussion.\n\nWHAT THEY ARE WATCHING FOR — targets that are traits ('be more confident'), targets that need work this placement cannot offer, or six targets where two would do.\n\nSTEPPING IN LOOKS LIKE — 'what would I see in your file in December that shows you met this one?'",
"s4":    "YOU DO IT ALONE — you set two or three targets, each specific, linked to a low rating or a named development area, and achievable in this placement.\n\nPASS TEST — Specific and achievable\n\nEVIDENCE TO FILE — targets in your own words in Appendix 6, agreed in the supervision record. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — 'develop my formulation skills' as the only target, with nothing at the end that shows whether it happened.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to turn a vague aim into an evidenceable target, and why fewer targets make a better comparison.\n\nWHEN IT GOES WRONG — mid-placement, a target becomes impossible (no cases of that kind arrive). Record why in supervision, adjust the target with your supervisor, and explain the change in the end comparison rather than dropping it silently.",
"error": "Writing targets that cannot be evidenced, such as 'improve at formulation'.",
"feeds": "→ Feeds into 'Carry the targets into the next Placement Plan' and 'Rate again at the end and compare'.",
"evidence":"Appendix 6 — targets · Supervision record · Log sheet tagged 7. Supervision"},

("Complete Appendix 6 before and after","Carry the targets into the next Placement Plan"): {
"why":   "Targets that live only in Appendix 6 do not shape what work you are given; targets in the Placement Plan do. Handbook Appendix 1 is mapped here — read the form for where targets and settings go. This matters especially for PSI 3.3.6, which is not yet met: it requires mainstream primary, post-primary and special education, and special-setting visits must be written into the Appendix 1 before the placement starts, not added afterwards.",
"s1":    "WATCH FOR — how your supervisor turns a trainee's development needs into caseload decisions: which schools, which referrals, which settings (including special schools or special classes) are allocated and why.\n\nWRITE DOWN — each Appendix 6 target alongside the specific opportunity in Cavan that could meet it, and the outstanding breadth needs (special education setting, further post-primary contact, thin age bands).\n\nASK AFTERWARDS — 'which of these can we write into the plan now, and which depend on referrals we don't have yet?'",
"s2":    "YOU TAKE — bringing your Appendix 6 targets and outstanding breadth needs to the planning meeting, and drafting how each appears in Appendix 1.\n\nTHEY HOLD — deciding what the service can commit to, arranging access to settings such as special schools, and signing the plan.\n\nWHY THAT SPLIT — you know your gaps and targets. The service controls allocation and access, so the plan has to be a joint document signed before work begins.",
"s3":    "YOU RUN IT — before the placement begins, check that every priority target and the special-setting visits needed for PSI 3.3.6 appear in Appendix 1 with a named opportunity.\n\nWHAT THEY ARE WATCHING FOR — an Appendix 1 that repeats generic programme aims, no special education setting named, and targets that appear nowhere in the plan.\n\nSTEPPING IN LOOKS LIKE — 'your target on consultation isn't in here. Which school could that happen in?'",
"s4":    "YOU DO IT ALONE — each Appendix 6 target has a matching line in Appendix 1, and required settings (including special education for PSI 3.3.6) are planned in before day one.\n\nPASS TEST — They appear in Appendix 1\n\nEVIDENCE TO FILE — the signed Appendix 1, cross-referenced to Appendix 6. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — December arrives with the targets met in name only, and no special education contact because it was never in the plan.",
"s5":    "YOU CAN TEACH IT — you can explain why the Placement Plan, not the self-evaluation, is what drives allocation, and why breadth and setting requirements cannot be evidenced retrospectively.\n\nWHEN IT GOES WRONG — a planned opportunity falls through. Record it in supervision, agree an alternative, and amend the plan in writing with your supervisor rather than letting the target lapse.",
"error": "Setting targets in Appendix 6 that never appear in the Appendix 1 Placement Plan.",
"feeds": "→ Feeds into PSI 3.3.6 setting coverage, Table 3 breadth, and 'Rate again at the end and compare'.",
"evidence":"Appendix 1 (signed) · Appendix 6 · Log sheet tagged 7. Supervision"},

("Complete Appendix 6 before and after","Rate again at the end and compare"): {
"why":   "The end comparison is where development is either shown or merely claimed. The UCD Handbook §4.5a is mapped here. The Reference sheet advises accounting for every change, including ratings that did not move: an unchanged rating explained by lack of opportunity, with a forward plan, is strong; an unexplained identical rating looks like disengagement. This row is a scaffold for structuring the comparison; the ratings and explanations are yours to write.",
"s1":    "WATCH FOR — how your supervisor reads change: what they count as evidence of movement (a dated product, observed practice, feedback) and what they discount (confidence, effort).\n\nWRITE DOWN — a two-column comparison: before rating and after rating for each competency, with a space for the evidence and reason beside each, and a separate list of competencies that did not move.\n\nASK AFTERWARDS — 'where have you seen me change this term, and where haven't you?'",
"s2":    "YOU TAKE — re-rating each competency in the final weeks, before reading your before-ratings again, then comparing and writing the explanation for each change or non-change.\n\nTHEY HOLD — their own view of your progress, given in the end-of-placement review, and discussion of any large disagreement.\n\nWHY THAT SPLIT — the comparison is your self-evaluation. Their perspective checks it but does not replace it.",
"s3":    "YOU RUN IT — for each competency, prompt yourself: what moved, what shows it (dated Log entry, report, observation feedback), what did not move and why, and what that means for the next placement.\n\nWHAT THEY ARE WATCHING FOR — every rating raised by one point with no evidence, unchanged ratings left unexplained, and a claim of change contradicted by the supervision record.\n\nSTEPPING IN LOOKS LIKE — 'this one hasn't moved. Why not, and what would move it next time?'",
"s4":    "YOU DO IT ALONE — you complete the after-ratings, place them beside the before-ratings, and account for each change and non-change with evidence and a forward plan.\n\nPASS TEST — Movement is visible\n\nEVIDENCE TO FILE — Appendix 6 (after), in your own words, and the supervision record of the end-of-placement review. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — before and after forms that differ by a point here and there, with no explanation of why anything changed or stayed the same.",
"s5":    "YOU CAN TEACH IT — you can explain why unchanged ratings need a reason, how to anchor change to dated evidence, and how the comparison feeds the next Placement Plan.\n\nWHEN IT GOES WRONG — you find a rating went down. That can be honest: you now understand the competency better. Say so plainly, give the evidence, and set it as a target for the next placement.",
"error": "Leaving unchanged ratings unexplained, so the comparison reads as disengagement.",
"feeds": "→ Feeds into the reflective learning essay, the next Appendix 1, and CORU SoP 4.3.",
"evidence":"Appendix 6 (before and after) · Supervision record · Log sheet tagged 7. Supervision"},

# ── 7. SUPERVISION · Write the reflective learning essay ──
# Scaffold only. The essay is the trainee's own to write; nothing here is draft text to submit.

("Write the reflective learning essay","Cover placement, college sessions and independent study"): {
"why":   "The essay is where the portfolio either becomes a coherent account of the year or stays a pile of forms. The UCD Handbook §4.5b is mapped here; read it yourself and list its requirements before writing, because the Reference sheet notes that Appendix 6 does two jobs and you need to check whether you are writing one document or two. Writing only about placement and omitting college sessions and independent study means writing the wrong thing well. The essay is yours to write; this row gives structure only.",
"s1":    "WATCH FOR — in §4.5b and any marking guidance the programme provides, the exact strands required, the word limit, and whether it is submitted within Appendix 6 or separately.\n\nWRITE DOWN — a planning table with a row per strand (placement, college sessions, independent study) and columns for a dated example, what it changed in your practice, and the source record you will draw on.\n\nASK AFTERWARDS — (programme tutor) 'is this one document with the self-evaluation, or two?'",
"s2":    "YOU TAKE — reading the requirements yourself, building the planning table, and drafting the essay in your own words.\n\nTHEY HOLD — (your supervisor or tutor) clarification of what the programme requires; they do not read drafts for content unless the programme allows it.\n\nWHY THAT SPLIT — the essay is assessed as your own reflection. Clarifying requirements is fair; shaping the content for you is not.",
"s3":    "YOU RUN IT — for each strand, find at least one dated example and ask: what did I learn, where did I use it, what changed? Link college teaching to a placement moment where you applied (or failed to apply) it.\n\nWHAT THEY ARE WATCHING FOR — an essay that is all placement, reading lists named without saying what they changed, and college sessions described as a timetable.\n\nSTEPPING IN LOOKS LIKE — 'where did something from a lecture actually turn up in your practice?'",
"s4":    "YOU DO IT ALONE — your essay addresses each required strand with dated examples, linked to changes in practice, in your own words.\n\nPASS TEST — All three strands\n\nEVIDENCE TO FILE — the essay (yours to write) in Appendix 6 or as the programme directs, with the planning table kept privately. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — a strong placement narrative that never mentions college teaching or independent reading, so a required strand is missing.",
"s5":    "YOU CAN TEACH IT — you can explain how to read §4.5b into a checklist, how a planning table stops a strand being forgotten, and why reading only counts when you can say what it changed.\n\nWHEN IT GOES WRONG — you realise late that a strand is thin. Go back to your Log and supervision records for dated material, and write honestly about what that strand contributed, even if it was less than the others.",
"error": "Writing only about placement and leaving out college sessions and independent study.",
"feeds": "→ Feeds into 'Trace a change in practice to a specific reflection' and the completed Appendix 6.",
"evidence":"Reflective essay (trainee's own) · Appendix 6 · Log sheet tagged 7. Supervision"},

("Write the reflective learning essay","Name what was hard and what it cost"): {
"why":   "An account with no difficulty in it is not credible, and markers tend to read it as performance. The UCD Handbook §4.5b and CORU SoP 5.45 (recognising personal emotional responses and developing self-care) are mapped here. The unit of analysis is your practice, not your private life: you are not required to disclose anything personal you do not wish to. This row offers structure and prompts; the reflection is yours to write.",
"s1":    "WATCH FOR — in your own supervision records and Log, the moments you found hard: a feedback meeting that went badly, a disclosure, a case you felt out of your depth on, a workload peak. Notice which ones changed how you practise.\n\nWRITE DOWN — for two or three moments: what happened (briefly), what you noticed in yourself, what it cost (time, sleep, confidence, a relationship with a school), and what you did about it.\n\nASK AFTERWARDS — (yourself) 'which difficulty do I most want to leave out, and why?'",
"s2":    "YOU TAKE — choosing which difficulties to write about, and how much of your personal response to include.\n\nTHEY HOLD — (your supervisor) nothing in the essay itself; they may have discussed the same moments in supervision, which you can draw on.\n\nWHY THAT SPLIT — disclosure is your choice. The essay needs honesty about practice, not about your private life, and you set that boundary.",
"s3":    "YOU RUN IT — use a structure to move from event to learning: for example Gibbs's (1988) reflective cycle (description, feelings, evaluation, analysis, conclusion, action plan) as a scaffold, not a set of headings to copy into the essay.\n\nWHAT THEY ARE WATCHING FOR — difficulty written as a confession with no link to practice, or difficulty minimised so it reads as a success story.\n\nSTEPPING IN LOOKS LIKE — (your own check) 'have I said what it cost and what I did about it, or only that it was hard?'",
"s4":    "YOU DO IT ALONE — the essay names real challenges, what they cost, and how you responded, in your own words, while keeping the focus on practice.\n\nPASS TEST — Challenges are expected\n\nEVIDENCE TO FILE — the essay (yours to write); supporting supervision records stay on file. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — an essay in which everything went well, or one that discloses personal material at length without any link to practice.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between reflection and confession, how a model like Gibbs (1988) can scaffold thinking, and why honest difficulty strengthens the essay.\n\nWHEN IT GOES WRONG — writing about a hard moment stirs up more than expected. Stop, take it to supervision or the university counselling service, and choose a different example if that one is not ready to be written about.",
"error": "Leaving out every difficulty, so the essay reads as a performance.",
"feeds": "→ Feeds into 'Reflect on your own culture, values and biases' and 'Name a self-care strategy and evidence it works'.",
"evidence":"Reflective essay (trainee's own) · Supervision record · Log sheet tagged 7. Supervision"},

("Write the reflective learning essay","Reflect on your own culture, values and biases"): {
"why":   "CORU SoP 5.44 asks you to reflect critically on the 'self' and the impact of your own culture, values, experiences, beliefs and biases, using supervision to assist the process. The Reference sheet treats this and 5.45 as the essay's real brief. Schön (1983) distinguishes reflection-in-action from reflection-on-action; the essay is largely the latter, but noting moments you adjusted in the room shows both. The reflection is yours to write; this row gives prompts only.",
"s1":    "WATCH FOR — moments when your own assumptions shaped a judgement: what you expected of a family, a school, a child's language or background, and where that expectation was wrong or had to be checked.\n\nWRITE DOWN — two or three such moments (anonymised), what you assumed, where the assumption came from, and what happened when it was tested.\n\nASK AFTERWARDS — (in supervision) 'where do you think my own background has shaped how I've read a case?'",
"s2":    "YOU TAKE — identifying your own values and assumptions, and choosing which examples to write about and how.\n\nTHEY HOLD — (your supervisor) questions in supervision that help you see what you might have missed; the supervision record of those discussions is source material.\n\nWHY THAT SPLIT — CORU 5.44 names supervision as an aid to this reflection, but the insight and the writing must be yours.",
"s3":    "YOU RUN IT — for each example, prompt yourself: what did I assume, what did it lead me to do, how did I find out, what do I do differently now? Quote your supervision record where a question changed your view.\n\nWHAT THEY ARE WATCHING FOR — a general statement ('I am aware of my biases') with no example, or a list of identity characteristics with no link to a decision you made.\n\nSTEPPING IN LOOKS LIKE — (your own check) 'can I point to a specific moment where this assumption changed something I did?'",
"s4":    "YOU DO IT ALONE — the essay names at least one specific way your culture, values or assumptions affected your practice, how you noticed, and what changed, in your own words.\n\nPASS TEST — This is where CORU 5.44 lands\n\nEVIDENCE TO FILE — the essay (yours to write), with the supervision record entries you drew on. Log against 7. Supervision and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a paragraph asserting awareness of bias without a single example from practice.",
"s5":    "YOU CAN TEACH IT — you can explain CORU 5.44, Schön's (1983) distinction as a way into it, and how supervision records provide evidence that the reflection is real rather than reconstructed.\n\nWHEN IT GOES WRONG — you cannot find an example. Look at cases where you and a parent or teacher disagreed, or where your first hypothesis was wrong, and take that question to supervision.",
"error": "Stating awareness of bias without a specific example of it affecting practice.",
"feeds": "→ Feeds into 6. Ethical Practice, culturally responsive assessment, and CORU SoP 5.44.",
"evidence":"Reflective essay (trainee's own) · Supervision record · Log sheet tagged 7. Supervision and 6. Ethical Practice"},

("Write the reflective learning essay","Trace a change in practice to a specific reflection"): {
"why":   "'I have developed in confidence' is an assertion; a dated sequence showing what you did before, what you reflected on, and what you did afterwards is evidence. CORU SoP 4.3 is mapped here. The Reference sheet suggests a ten-minute weekly habit — one dated paragraph about what you noticed — so the essay becomes an editing task rather than writing from memory. The essay is yours to write; this row suggests how to find and structure the evidence.",
"s1":    "WATCH FOR — in your Log's development column, supervision records and Appendix 7 feedback, a chain: a moment you noticed something, a reflection or piece of feedback, and a later dated occasion where you did it differently.\n\nWRITE DOWN — two or three such chains, each with dates (DD/MM/YYYY), the source record, and what specifically changed.\n\nASK AFTERWARDS — (yourself) 'what would someone reading my file see that shows this change, without my telling them?'",
"s2":    "YOU TAKE — finding the chains in your own records and writing them up in your own words, with dates and sources.\n\nTHEY HOLD — (your supervisor) the supervision records and observation feedback that corroborate the change.\n\nWHY THAT SPLIT — the change and its account are yours. Records held jointly show the reflection was real, which is why quoting them strengthens the essay.",
"s3":    "YOU RUN IT — keep a weekly dated paragraph through the Cavan placement; when drafting, pick the chains with the clearest before and after, and quote the supervision record at the turning point.\n\nWHAT THEY ARE WATCHING FOR — change asserted without dates, a before and after with no reflection between them, or examples that are all descriptions of what happened.\n\nSTEPPING IN LOOKS LIKE — (your own check) 'where exactly is the reflection in this example, and when did the practice change?'",
"s4":    "YOU DO IT ALONE — the essay traces at least one change in practice back to a specific, dated reflection or piece of feedback, in your own words.\n\nPASS TEST — Reflection that changed something\n\nEVIDENCE TO FILE — the essay (yours to write), cross-referenced to the Log, supervision record and Appendix 7. Log against 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — 'I grew in confidence over the year' with no example, no date and no source.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between asserting and evidencing change, how a weekly dated habit produces material, and how to use supervision records as source material.\n\nWHEN IT GOES WRONG — you reach the essay with no weekly notes. Reconstruct from dated records you already hold (Log, supervision notes, Appendix 7), say plainly where memory is filling gaps, and start the weekly habit now.",
"error": "Asserting development instead of evidencing it with dated examples.",
"feeds": "→ Feeds into 'Rate again at the end and compare' and the completed portfolio.",
"evidence":"Reflective essay (trainee's own) · Log · Supervision record · Appendix 7 · Log sheet tagged 7. Supervision"},

("Write the reflective learning essay","Name a self-care strategy and evidence it works"): {
"why":   "CORU SoP 5.45 asks you to recognise personal emotional responses and develop effective self-care; PSI Code 4.1.1 is also mapped — read both in full. Burnout builds slowly (Maslach & Jackson, 1981), and an intention ('I will look after myself') is not a strategy. The essay needs a specific activity you actually did, and some evidence that it helped. What you disclose is your choice; this row gives prompts, and the text is yours to write.",
"s1":    "WATCH FOR — what you actually did when the work was heavy: a boundary on evening emails, a walk between schools, raising workload in supervision, using the employee assistance or university counselling service.\n\nWRITE DOWN — one or two strategies, when you used them (dated), what prompted them, and what you noticed afterwards (sleep, backlog, mood, quality of records).\n\nASK AFTERWARDS — (in supervision) 'have you noticed any difference in how I've been working since I started doing this?'",
"s2":    "YOU TAKE — choosing and using a strategy, noting its effect, and deciding how much to say about it in the essay.\n\nTHEY HOLD — (your supervisor) noticing and naming signs of strain, and space in supervision to talk about wellbeing; nothing private needs to go on file.\n\nWHY THAT SPLIT — self-care is yours. Supervision is one place it can be supported, and a brief record that wellbeing was discussed is enough evidence.",
"s3":    "YOU RUN IT — use the strategy consistently for several weeks, note briefly when you did and what changed, and raise it in supervision at least once.\n\nWHAT THEY ARE WATCHING FOR — a strategy that exists only in the essay, a general list ('exercise, sleep, friends') with no evidence of use, or over-disclosure that moves the essay away from practice.\n\nSTEPPING IN LOOKS LIKE — (your own check) 'can I show when I did this and what difference it made?'",
"s4":    "YOU DO IT ALONE — the essay names a specific self-care activity you carried out, when, and what evidence shows it helped, in your own words.\n\nPASS TEST — An activity, not an intention\n\nEVIDENCE TO FILE — the essay (yours to write); a supervision record line that wellbeing was discussed. Log against 7. Supervision and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — 'I will prioritise self-care next year' as the only statement on the subject.",
"s5":    "YOU CAN TEACH IT — you can explain CORU 5.45, why an intention is not evidence, and how to record a strategy's effect without over-disclosing.\n\nWHEN IT GOES WRONG — the strategy stops working, or strain continues. Raise it in supervision, use the employee assistance or university counselling service, see your GP, and write honestly about what you learned from it not working.",
"error": "Writing a self-care intention with no evidence it was ever carried out.",
"feeds": "→ Feeds into 'Manage workload and your own wellbeing' in 6. Ethical Practice and CORU SoP 5.45.",
"evidence":"Reflective essay (trainee's own) · Supervision record · Log sheet tagged 7. Supervision and 6. Ethical Practice"},

}
