"""Systemic Change: SET provision and allocation, mapping the school's
organisation of supports, special education settings (PSI 3.3.6), service team
meetings, consultation models, and the good practice presentation.

Keyed (macro skill name, micro-skill name), in the micro.py format from HANDOVER.md.
"""

MICRO = {

# ── 4. SYSTEMIC CHANGE · Familiarise with SET provision and allocation ──

("Familiarise with SET provision and allocation","Understand how SET hours are allocated"): {
"why":   "The Reference sheet sets out the principle: special education teaching (SET) hours come to the school as a block under a profiled model, not per child and not per diagnosis, and the school decides how to deploy them. Parents very often believe that a report or a diagnosis 'gets' their child hours. If you say or imply that, you set up a conflict between the family and the school and then leave. The detail of the profile changes, so for how it is calculated this year check the current Department of Education circular and the NCSE guidance rather than working from memory. CORU SoP 5.13 is the standard mapped here.",
"s1":    "WATCH FOR — what your supervisor says when a parent or teacher asks 'will the report get him resource hours?' Listen for the exact words: whether they say 'the school has an allocation', whether they explain that the school decides, and how quickly they move on to what the support should be for. Notice how the explanation changes for a principal and for a parent.\n\nWRITE DOWN — the sentence they use with a parent, as close to word for word as you can, plus the terms this school uses ('resource', 'learning support', 'SET') and what each means here.\n\nASK AFTERWARDS — 'what do parents most often get wrong about hours, and what's the one sentence that puts it right without making the school look bad?'",
"s2":    "YOU TAKE — reading the NCSE guidance on the allocation model and the current Department of Education SET circular (check it has not been replaced), then drafting a five-sentence plain-English explanation for parents. Your supervisor checks it before you use it.\n\nTHEY HOLD — the conversation with any parent who is already in dispute with the school about support, or who has been told elsewhere that a report will secure hours.\n\nWHY THAT SPLIT — getting the model right on paper is safe to practise. A parent in conflict with a school needs someone who knows the history, and one wrong sentence from you becomes 'the psychologist said'.",
"s3":    "YOU RUN IT — explain the allocation model to a parent at a feedback meeting, with your supervisor present, and then move straight on to what the support for their child should look like.\n\nWHAT THEY ARE WATCHING FOR — implying the report or diagnosis unlocks hours; quoting figures or parts of the formula from memory; blaming the school ('they get the hours and decide who gets them'); using 'profiled model' without explaining it.\n\nSTEPPING IN LOOKS LIKE — 'can I add something — the school gets its support teaching as one allocation for everyone, so what this report does is help them decide how to use it well for your son.'",
"s4":    "YOU DO IT ALONE — explain in plain words to a parent that SET is allocated to the school and not to the child, that the school decides how it is used through its support planning, and that the report's job is to say what the support should target. Check understanding by asking what they now plan to ask the school.\n\nPASS TEST — You can explain the model to a parent\n\nEVIDENCE TO FILE — a line in the case record noting what was explained; your parent script as a working paper. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a parent who goes from your meeting to the principal and says 'the psychologist said he's entitled to so many hours a week'.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why allocation to schools rather than to children changes how every recommendation must be worded; how SET differs from SNA access and from special class placement; and where to find the current basis of the allocation (the current circular and NCSE guidance, read rather than recalled).\n\nWHEN IT GOES WRONG — if you realise you told a parent something inaccurate, correct it quickly by phone or in writing, tell your supervisor, and give the school a heads-up so they are not caught off guard at the next meeting.",
"error": "Telling a parent, or implying in a report, that a diagnosis or assessment will secure a set number of hours for their child.",
"feeds": "→ Feeds into 'Know how the school deploys what it has', 'Cite the specific circular rather than guidance', and the recommendations section of every report.",
"evidence":"Case record · parent explanation script · Log sheet tagged 4. Systemic Change"},

("Familiarise with SET provision and allocation","Cite the specific circular rather than 'guidance'"): {
"why":   "The Reference sheet: circulars change, so check the current Department circular before you cite anything in a report. CORU SoP 1.13 is mapped here; the Reference sheet reads it as requiring you to be aware of current legislation and to seek out new legislation. 'Department guidance says' cannot be checked and is often out of date. A circular number and title let a principal check what you wrote, and make you check it too. This file does not give circular numbers on purpose: look up the current one each time, because a number you learned last year may have been replaced.",
"s1":    "WATCH FOR — whether your supervisor names circulars in reports and meetings or says 'the guidelines'; where they look them up (the Department of Education circulars search on gov.ie, the NCSE website); and how they confirm a circular is still in force (a later circular that replaces it, the issue date).\n\nWRITE DOWN — the circulars the service cites routinely for SET, SNA access and special class or special school placement, with where you found each one and the date you checked it.\n\nASK AFTERWARDS — 'how do you find out when a circular has been replaced, and has an old one ever caught you out in a meeting?'",
"s2":    "YOU TAKE — building a one-page reference list of the circulars that currently apply to SET, SNA access and special class/school placement: number, title, issue date, link, and the date you last opened it.\n\nTHEY HOLD — confirming that list is current for the service, and deciding which circulars are cited in reports and which are only for background.\n\nWHY THAT SPLIT — finding documents is desk research you can do alone. Knowing which ones the service treats as governing, and whether a replacement is expected, is service knowledge you do not yet have.",
"s3":    "YOU RUN IT — draft a report or letter paragraph that refers to allocation, SNA access or placement, citing the circular by number and title; your supervisor reviews it before it goes anywhere.\n\nWHAT THEY ARE WATCHING FOR — 'as per Department guidance'; a number copied from an old report without opening the current version; paraphrasing a paragraph that has since changed; citing a circular for something it does not say.\n\nSTEPPING IN LOOKS LIKE — 'which circular is that from, and when did you last open it? Show me the paragraph.'",
"s4":    "YOU DO IT ALONE — whenever you refer in writing to SET allocation, SNA access or placement criteria, name the circular by number and title, having opened the current version on the day you wrote it, and quote only what it actually says.\n\nPASS TEST — You name the circular number\n\nEVIDENCE TO FILE — your dated reference list of circulars; the report paragraph that cites one. Log against 4. Systemic Change and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a report that cites a replaced circular, and the principal points it out at the review meeting in front of the parents.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to find a circular, how to check it is still in force, why 'guidance' is not a citation, and the difference between a Department circular, NCSE guidance and the Education for Persons with Special Educational Needs (EPSEN) Act 2004. You can also explain why this encyclopedia tells you to check rather than giving a number.\n\nWHEN IT GOES WRONG — if you cited an outdated circular in a report already issued, tell your supervisor and agree a correction or addendum. Do not quietly fix it in the next version.",
"error": "Writing 'Department guidance states' or copying a circular number from an old report without opening the current version.",
"feeds": "→ Feeds into 'Understand how SET hours are allocated', 'Know the SENO route and what the NCSE can do', and 6. Ethical Practice (keeping knowledge current).",
"evidence":"Dated circulars reference list · report paragraph · Log sheet tagged 4. Systemic Change"},

("Familiarise with SET provision and allocation","Know how the school deploys what it has"): {
"why":   "Allocation is what arrives at the school; deployment is what the school does with it. The Reference sheet says the principal and SET team deploy the allocation, usually through a support plan review, with the SENCO or SET coordinator holding the overview. It also warns that recommending 'additional SET time' asks the school to take it from another child. A recommendation that ignores how support is actually deployed either asks for something that does not exist or repeats what is already happening. CORU SoP 5.14 is the standard mapped here.",
"s1":    "WATCH FOR — how your supervisor finds out how support is actually used: in-class or withdrawal, group sizes, who decides which children get what, how often that is reviewed, and whether the timetable matches the plan. Notice the questions they ask the SET coordinator that are not in any form.\n\nWRITE DOWN — for one school, how support is organised this year, who decides, and when it is reviewed. No pupil names in your notes.\n\nASK AFTERWARDS — 'how do you find out how a school really uses its hours, as opposed to what they tell you at the first planning meeting?'",
"s2":    "YOU TAKE — asking the SET coordinator to walk you through how support is organised this year, and asking to see the SEN policy and, with permission, a Student Support File for a child you are working with.\n\nTHEY HOLD — any conversation that questions the school's deployment decisions.\n\nWHY THAT SPLIT — gathering the picture is information-gathering and teaches you the terrain. Questioning deployment is systemic influence, and it depends on a relationship with the principal that your supervisor has built over years and you have not.",
"s3":    "YOU RUN IT — for a child you are assessing, find out exactly what support they currently get (who delivers it, how often, group size, in-class or withdrawal, what targets) and write the recommendations around it. Your supervisor reviews them.\n\nWHAT THEY ARE WATCHING FOR — 'additional SET support' instead of what the support should target; assuming the child gets what the Student Support File says without checking; recommendations the timetable cannot hold.\n\nSTEPPING IN LOOKS LIKE — 'what is he actually getting now? Then your recommendation is about what that time should be used for.'",
"s4":    "YOU DO IT ALONE — keep allocation and deployment separate in your notes and reports: find out how support is deployed for this child, and write recommendations about how that time is used, not about how much of it there should be.\n\nPASS TEST — Allocation and deployment are different things\n\nEVIDENCE TO FILE — a note of current provision in the case record; the recommendations section of the report. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a report recommending 'increased resource hours', which the principal reads as a psychologist who does not know how schools work.",
"s5":    "YOU CAN TEACH IT — you can explain the difference with an example: the same hours used as withdrawal groups of six on one programme, or as in-class team teaching, with very different results. You can also show how the NEPS Continuum of Support and the Student Support File shape deployment decisions, and why recommendations should name a purpose rather than a quantity.\n\nWHEN IT GOES WRONG — if the school says your recommendation cannot be delivered, ask what could be done within how support is organised now, and revise it with them rather than defending it.",
"error": "Recommending 'more SET hours' rather than saying what the existing support time should be used for.",
"feeds": "→ Feeds into 'Map each Continuum level against provision', 'Identify a gap in the continuum', and the recommendations section of every report.",
"evidence":"Case record — current provision · report recommendations · Log sheet tagged 4. Systemic Change"},

("Familiarise with SET provision and allocation","Know the SENO route and what the NCSE can do"): {
"why":   "The Reference sheet: the Special Educational Needs Organiser (SENO) handles applications for SNA access and for special class or special school placement. That is a different process from SET hours, and trainees routinely mix them up. SNA support is for significant care needs, not learning support. NCSE structures and application routes have changed in recent years, so check the NCSE website for how things work now, including how SNA access is currently decided and how schools reach the local SENO, before you advise anyone. CORU SoP 5.5 is mapped here.",
"s1":    "WATCH FOR — when your supervisor points a school or family to the SENO, what for, and what they say the SENO can and cannot do. Listen for how they separate SNA access (care needs), special class or special school places, and SET (which the school decides).\n\nWRITE DOWN — a simple table: the need, who handles it, and how to make contact. Include the SENO, the principal or SET coordinator, the HSE CDNT, CAMHS, and the NCSE's teacher support services (check current names on the NCSE website).\n\nASK AFTERWARDS — 'how do you usually work with the SENO for these schools, and what do families most often ask them for that isn't theirs to give?'",
"s2":    "YOU TAKE — finding the NCSE's current information on the SENO role, the special class and special school application process and SNA access, and turning it into a contact table for the Cavan schools.\n\nTHEY HOLD — direct contact with the SENO about individual children, and anything said to a parent about whether their child is likely to get a special class place.\n\nWHY THAT SPLIT — reading the process is safe and quick. Anything a psychologist says about eligibility is heard by parents as a promise, and the working relationship with the SENO belongs to the service.",
"s3":    "YOU RUN IT — at a feedback meeting, explain to a parent which route fits their question and who they should contact, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — recommending an SNA for a reading difficulty (the Reference sheet calls this a category error); implying the psychologist decides placement; promising a place; sending a parent to the SENO about SET hours the school decides.\n\nSTEPPING IN LOOKS LIKE — 'just to be clear, the SENO deals with applications for places and SNA access. The support teaching is something the school organises, so that's a conversation with the principal.'",
"s4":    "YOU DO IT ALONE — for any question a school or parent raises about provision, say who decides it and how to contact them, and word recommendations so the right person can act on them. Where you mean an adult nearby for safety, say that and why, rather than writing 'SNA'.\n\nPASS TEST — You know who to contact and for what\n\nEVIDENCE TO FILE — your contact table (roles, not personal names); the case record entry. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a family waiting months on a SENO reply about something the school could have decided in a week.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the difference between SET, SNA access and special class/school placement, who decides each one, why SNA is about care and not teaching, and where the NCSE's role is set out in law (read the EPSEN Act 2004 and the NCSE's own description of its functions rather than summarising from memory).\n\nWHEN IT GOES WRONG — if a report you drafted sends someone down the wrong route, tell your supervisor, contact the family with the correct route, and correct the report.",
"error": "Recommending SNA support for a learning difficulty, or sending a parent to the SENO for something the school decides.",
"feeds": "→ Feeds into 'Cite the specific circular rather than guidance', 'Visit a range of special education settings', and placement recommendations.",
"evidence":"Contact table · case record · Log sheet tagged 4. Systemic Change"},

# ── 4. SYSTEMIC CHANGE · Map the school's organisation of supports ──

("Map the school's organisation of supports","Map each Continuum level against provision"): {
"why":   "The NEPS Continuum of Support (Classroom Support, School Support, School Support Plus) describes what should happen at each level; the map shows what actually does in this school. The Reference sheet lists what to map: who is on the SEN team, how children are identified, withdrawal versus in-class, group sizes, how plans are written and reviewed, how information moves between the SET and the class teacher, and what happens at transitions. Two schools with the same allocation get very different results, and the difference is organisation. A map built from the policy document alone describes a school that does not exist.",
"s1":    "WATCH FOR — how your supervisor gets from policy to practice. The Reference sheet's contrast: 'how does it usually work when a teacher is worried about someone?' gets the real process, while 'what is your identification procedure?' gets the policy. Notice who they ask (class teacher, SET, coordinator, principal) and where the accounts differ.\n\nWRITE DOWN — a grid with a row for each Continuum level and columns for: who identifies, what is offered, who delivers, group size, how plans are written and reviewed, and how information returns to the class teacher.\n\nASK AFTERWARDS — 'which parts of this map would you check with a second person before trusting them?'",
"s2":    "YOU TAKE — filling in the grid from short conversations with a class teacher, a SET and the coordinator, and from the SEN policy.\n\nTHEY HOLD — the conversation with the principal about the map, and the decision about which parts are firm enough to use in a report or planning meeting.\n\nWHY THAT SPLIT — collecting the picture teaches you how Irish schools work in practice. Checking it with the principal touches on how the school is led, and needs a relationship you do not yet have.",
"s3":    "YOU RUN IT — build the full map for one Cavan school; your supervisor checks it against what they know of the school.\n\nWHAT THEY ARE WATCHING FOR — the SEN policy copied into the grid; a Classroom Support row left empty because nobody thought to describe it; one person's account taken as the whole picture; transitions (class to class, primary to post-primary) missed out.\n\nSTEPPING IN LOOKS LIKE — 'that's what the policy says. What did the class teacher tell you actually happens when she's worried about a child?'",
"s4":    "YOU DO IT ALONE — map all three Continuum levels for a school from at least two sources, mark where accounts differ, and keep it as a working document that informs your formulations for children in that school.\n\nPASS TEST — The map is complete and accurate\n\nEVIDENCE TO FILE — the map as a working paper, with no pupil names; a note of how it was gathered. Log against 4. Systemic Change, not as casework (the Reference sheet names this as why Systemic Change ends up thinly evidenced).\n\nWHAT FAILURE LOOKS LIKE — a map saying School Support Plus plans are reviewed every term, because the policy says so, when none have been reviewed this year.",
"s5":    "YOU CAN TEACH IT — you can explain the three Continuum levels and what each should contain (read the NEPS Continuum of Support guidelines for primary and post-primary for the wording), how to gather practice rather than policy, and why the map belongs in formulation: it tells you whether a difficulty sits in the child or in how support is delivered.\n\nWHEN IT GOES WRONG — if staff feel checked up on, stop, explain what the map is for (planning support for the children you are seeing), and go back to open, curious questions.",
"error": "Building the map from the SEN policy and believing it describes what happens.",
"feeds": "→ Feeds into 'Identify a gap in the continuum', 'Present the map back to the school', and the context section of Formulation.",
"evidence":"School support map (working paper) · Log sheet tagged 4. Systemic Change"},

("Map the school's organisation of supports","Identify a gap in the continuum"): {
"why":   "The Reference sheet's examples: if every child is withdrawn in groups of six for the same programme regardless of need, the organisation is doing the deciding, not the assessment; if plans are written by the SET and never seen by the class teacher, nothing will generalise. These are findings, and they tell you whether a child's difficulty is about the child or about delivery. If it is delivery, an individual intervention will not fix it. CORU SoP 5.35 is mapped here. Naming one gap clearly is worth more than listing everything you noticed.",
"s1":    "WATCH FOR — how your supervisor notices a delivery-level pattern across cases: several referrals from one class, the same programme for every child, no Classroom Support level before a referral, plans that stop at School Support. Notice how they check it is a pattern and not a single case.\n\nWRITE DOWN — the gap in one sentence, the evidence for it (at least two sources), and which Continuum level it sits at.\n\nASK AFTERWARDS — 'how do you tell the difference between a gap in the school's system and a gap in one teacher's practice, and why does that difference matter?'",
"s2":    "YOU TAKE — going through your map and your cases in this school and drafting one candidate gap with the evidence for it.\n\nTHEY HOLD — deciding whether the gap is real, whether it is worth raising, and whether now is the right time given what else is happening in the school.\n\nWHY THAT SPLIT — spotting patterns is analytical work you can do from the map. Whether and when to raise something depends on the school's current pressures and relationships, which your supervisor knows.",
"s3":    "YOU RUN IT — present your candidate gap in supervision with its evidence and say what it means for a child you are working with.\n\nWHAT THEY ARE WATCHING FOR — a gap that is really a complaint about a named teacher; a gap based on one source; five gaps where one was asked for; a gap outside the school's control (such as the allocation itself).\n\nSTEPPING IN LOOKS LIKE — 'which of these is the one that, if it changed, would make the most difference to the children you're seeing? Just that one.'",
"s4":    "YOU DO IT ALONE — name one gap in how support is organised, at a stated Continuum level, backed by more than one source, and link it to what it means for at least one child you are working with.\n\nPASS TEST — You named one\n\nEVIDENCE TO FILE — the gap and its evidence in your map; a line in the relevant formulation showing the link. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a formulation that locates everything in the child when your own map shows the child has had no Classroom Support at all before being referred.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer what a delivery-level factor is, give two examples from the Reference sheet, show how to test whether it is a real pattern, and explain why it belongs in a formulation and not just in your notes (Frederickson & Cline, 2009, on whole-school approaches, is the Reference sheet's reading).\n\nWHEN IT GOES WRONG — if the gap you named turns out to be wrong once you learn more, say so in supervision, update the map, and remove it from any formulation that relied on it.",
"error": "Naming a gap that is really criticism of one named staff member rather than a feature of how support is organised.",
"feeds": "→ Feeds into 'Say what would close the gap', 'Present the map back to the school', and 2. Formulation.",
"evidence":"School support map · formulation · Log sheet tagged 4. Systemic Change"},

("Map the school's organisation of supports","Say what would close the gap"): {
"why":   "A gap with no suggested change is an observation the school cannot use. The Reference sheet: offer one change, not five, because schools implement one. Fullan (2016, The New Meaning of Educational Change, 5th ed.) argues that change depends on what it means to the people who have to carry it out, so a proposal has to fit the school's existing time, staff and routines. CORU SoP 5.35 is mapped here. A proposal that needs extra resources the school does not have will be nodded at and dropped.",
"s1":    "WATCH FOR — the kind of changes your supervisor suggests: small, specific, within existing resources and routines (a ten-minute handover between SET and class teacher each fortnight; grouping by need rather than year group; a shared one-page plan). Notice how they frame it as the school's idea to build on.\n\nWRITE DOWN — the gap, the proposed change, who would do it, when, and how anyone would know it had worked.\n\nASK AFTERWARDS — 'what's a change you've suggested that a school actually took up, and what was different about it from the ones they didn't?'",
"s2":    "YOU TAKE — drafting one proposal for the gap you named: who, what, when, with what existing resource, and one sign that it is working.\n\nTHEY HOLD — deciding whether the proposal is realistic for this school now, and how it is pitched to the principal.\n\nWHY THAT SPLIT — designing the proposal teaches you to think at school level. Judging what this school can absorb this term depends on its history of change, which your supervisor knows.",
"s3":    "YOU RUN IT — take your proposal through a consultation with the SET coordinator or a class teacher, with your supervisor present, and adjust it based on what they say.\n\nWHAT THEY ARE WATCHING FOR — proposals that need new hours or staff; several changes bundled together; a proposal the school has already tried; telling rather than building the proposal with them.\n\nSTEPPING IN LOOKS LIKE — 'before we go further — has anything like this been tried here before? What happened?'",
"s4":    "YOU DO IT ALONE — propose one concrete change that the school could make within its current resources, agreed with the people who would carry it out, with a named way to check if it has worked.\n\nPASS TEST — You proposed something the school could do\n\nEVIDENCE TO FILE — the proposal and consultation note; any follow-up showing what happened. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a feedback letter ending 'the school may wish to review its model of SEN provision', which nobody can act on.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why one change beats five, what makes a proposal realistic (existing resources, existing routines, someone who owns it), and how to link it to a review point. You can connect this to Fullan (2016) on the meaning of change for those who implement it.\n\nWHEN IT GOES WRONG — if the school agrees but nothing happens, go back at the review point, ask what got in the way without blame, and shrink the change until it fits.",
"error": "Proposing a change that needs resources the school does not have, or proposing several changes at once.",
"feeds": "→ Feeds into 'Present the map back to the school', 'End with three things the school could do this term', and 3. Intervention at school level.",
"evidence":"Proposal and consultation note · Log sheet tagged 4. Systemic Change"},

("Map the school's organisation of supports","Present the map back to the school"): {
"why":   "A map filed in your placement folder changes nothing for children. The Reference sheet's approach to feedback: describe rather than judge, for example 'support is currently organised by year group rather than by need, which means one child is working on material above his current level', and offer one change. CORU SoP 5.40 is mapped here, on building capacity among those responsible for delivering interventions. Wagner (2000, Educational Psychology in Practice, 16(1)) describes consultation that works at school and organisational level as well as with individual cases; this is that work.",
"s1":    "WATCH FOR — how your supervisor gives school-level feedback: who is in the room (principal, coordinator), how they open (what is working first), how they describe the gap in neutral, descriptive terms, and how they end with one agreed action and a date.\n\nWRITE DOWN — the structure of the conversation, the phrases used to describe a gap without blame, and what was agreed.\n\nASK AFTERWARDS — 'how do you decide whether to give this kind of feedback to the principal alone or to the whole SEN team?'",
"s2":    "YOU TAKE — preparing a one-page version of the map and the proposed change, written descriptively, with no names of staff or pupils.\n\nTHEY HOLD — leading the feedback meeting with the principal.\n\nWHY THAT SPLIT — writing it teaches you descriptive, blame-free wording. The meeting is about how the school is organised, and the principal will expect to hear it from the psychologist who has the ongoing relationship with the school.",
"s3":    "YOU RUN IT — present the map and one proposal to the SET coordinator or SEN team, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — judging words ('inadequate', 'failing'); anything that identifies a teacher; presenting it as an inspection finding; leaving without an agreed next step or date.\n\nSTEPPING IN LOOKS LIKE — 'what's been picked up here is a pattern we see in lots of schools — can we talk about which bit of it would be easiest to try first?'",
"s4":    "YOU DO IT ALONE — present the map and one proposed change to the school in descriptive terms, agree an action with a named owner and a review date, and follow up at that date.\n\nPASS TEST — It was used, not just submitted\n\nEVIDENCE TO FILE — the one-page summary; a note of what was agreed and what happened at follow-up. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a well-received meeting, a thank-you email, and no change by the time you leave Cavan on 18/12/2026, because nobody owned the next step.",
"s5":    "YOU CAN TEACH IT — you can explain how to turn a map into feedback a school will act on: descriptive language, strengths first, one change, a named owner and a date. You can also explain why it is logged as systemic work and what that does for the portfolio.\n\nWHEN IT GOES WRONG — if a staff member takes the feedback personally, acknowledge it, restate that the pattern is about organisation not individuals, and follow up privately through your supervisor.",
"error": "Handing the school a map and leaving without an agreed action, an owner and a follow-up date.",
"feeds": "→ Feeds into 'Deliver the good practice presentation', 'Collect and file feedback from the school', and 4. Systemic Change evidence.",
"evidence":"One-page map summary · follow-up note · Log sheet tagged 4. Systemic Change"},

# ── 4. SYSTEMIC CHANGE · Visit a range of special education settings ──

("Visit a range of special education settings","Arrange visits early in the placement"): {
"why":   "PSI 3.3.6 is NOT yet met. It requires experience in mainstream primary, post-primary AND special education settings; so far there is one post-primary day and no special education at all. The Reference sheet says it plainly: it will not happen unless you ask in week one and get a date. The visits need to be planned into the Cavan Appendix 1 before the placement starts on 05/10/2026, because the placement runs only to 18/12/2026, four days a week, and settings may need several weeks' notice for a visitor. Handbook Table 3 is the standard mapped here. Leave it late and the gap carries into Year 2.",
"s1":    "WATCH FOR — in your first contact with your Cavan supervisor, which special settings the service works with most (special schools, special classes in primary and post-primary, early intervention classes), and who in the service has the link with each one. The Reference sheet's advice: go to the settings the service works with most.\n\nWRITE DOWN — each setting type, the named service contact for it (in your own diary, not this file), and the date you asked.\n\nASK AFTERWARDS — 'which of these settings would be most useful to see given the referrals you're expecting this term, and could we go together?'",
"s2":    "YOU TAKE — writing the visits into your draft Appendix 1 before 05/10/2026 as a stated objective tied to PSI 3.3.6, and drafting the request emails to settings for your supervisor to approve.\n\nTHEY HOLD — the first approach to each setting's principal, and agreement on which visits go into the placement plan.\n\nWHY THAT SPLIT — the gap is yours to plan for and evidence. The approach goes through the service because settings agree to visitors on the strength of an existing professional relationship, not a trainee's email.",
"s3":    "YOU RUN IT — by the end of week two, have at least two different setting types (for example, a special school and a special class attached to a mainstream school) booked with confirmed dates, with your supervisor checking progress in supervision.\n\nWHAT THEY ARE WATCHING FOR — one visit treated as covering the category; dates left as 'sometime in November'; visits squeezed into the last fortnight where there is no time to act on what you learn.\n\nSTEPPING IN LOOKS LIKE — 'let's ring them now while we're sitting here and get a date in the diary.'",
"s4":    "YOU DO IT ALONE — get visits to a range of special education settings written into the Appendix 1 before the placement begins and booked with confirmed dates in the first weeks of Cavan, with a backup date for each.\n\nPASS TEST — Booked in the first weeks\n\nEVIDENCE TO FILE — the Appendix 1 objective naming PSI 3.3.6; the confirmed booking in your placement diary; the visit days in the Log. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — reaching 18/12/2026 with no special education visit because the first request went out in November and the setting was fully booked.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer what PSI 3.3.6 requires (read the PSI Accreditation Standards, 2022, for the wording), why it must be in the Appendix 1 before the placement starts, which setting types count as different, and how to approach a setting through the service.\n\nWHEN IT GOES WRONG — if a visit falls through, tell your supervisor the same week, rebook or find an equivalent setting, and tell your university placement tutor early if it looks like PSI 3.3.6 will not be met in Cavan, so it can be planned for Year 2.",
"error": "Leaving special education visits out of the Appendix 1 and asking for them late in the placement.",
"feeds": "→ Feeds into 'Observe structure, staffing and communication supports', 'Log each visit separately in Appendix 5', and PSI 3.3.6.",
"evidence":"Appendix 1 objective · placement diary · Log sheet tagged 4. Systemic Change"},

("Visit a range of special education settings","Observe structure, staffing and communication supports"): {
"why":   "You will be asked whether a child needs a special class or a special school, and the Reference sheet says you cannot answer that honestly if you have never been in one. Its list of what to look at: staffing ratios and how adults are deployed; the curriculum in use (L1LP, L2LP or adapted mainstream); communication systems and whether everyone uses them; the sensory environment; what integration looks like in practice; where pupils go afterwards. CORU SoP 5.13 is mapped here. These visits are also how PSI 3.3.6, currently unmet, gets met, so observe the system, not only the children.",
"s1":    "WATCH FOR — how adults are deployed across the day (who leads, who supports, who does personal care); which curriculum framework is actually in use (for L1LP and L2LP read the NCCA material first); which communication system is used and whether every adult uses it the same way; noise, light and the use of quiet spaces.\n\nWRITE DOWN — a structured note under the Reference sheet's headings, with no pupil names or identifying details.\n\nASK AFTERWARDS — ask a teacher 'what does a child need to be able to do to do well here, and what kind of child finds it hard?'",
"s2":    "YOU TAKE — preparing an observation frame from the Reference sheet's headings before the visit, and completing it during and just after.\n\nTHEY HOLD — (if they come) the conversation with the principal about admissions, and interpreting what you saw for placement decisions on current cases.\n\nWHY THAT SPLIT — observing a setting systematically is the learning. Linking it to a live placement question involves individual children and the SENO process, which stay with your supervisor.",
"s3":    "YOU RUN IT — lead your own observation in a second setting of a different type, and compare it with the first in supervision.\n\nWHAT THEY ARE WATCHING FOR — describing the children rather than the system; general impressions ('lovely atmosphere') instead of structure; assuming all special classes work alike; a visit that confirms whatever view you arrived with.\n\nSTEPPING IN LOOKS LIKE — 'you've told me about the children. Tell me how many adults were in the room, what each one was doing, and how the children communicated with them.'",
"s4":    "YOU DO IT ALONE — for each setting, describe how it works (staffing, curriculum, communication, environment, links with mainstream, where pupils go next) well enough to explain what kind of need it fits, and note how it differs from the other settings you have seen.\n\nPASS TEST — You can describe how the setting works\n\nEVIDENCE TO FILE — the structured observation note (no identifying details); the Appendix 5 entry for that visit. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a later placement recommendation that says 'a special class would be appropriate' without being able to say what that class provides.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer how special schools, special classes and early intervention classes differ, what L1LP and L2LP are (read the NCCA source for the detail), and why the Reference sheet frames placement as fit between need and provision rather than severity.\n\nWHEN IT GOES WRONG — if you notice your notes are full of judgements rather than descriptions, rewrite them before supervision, and bring your assumptions about special provision to supervision as the Reference sheet suggests (CORU SoP 5.44).",
"error": "Observing the children and not the system, so you cannot say what the setting actually offers.",
"feeds": "→ Feeds into 'Talk to therapy and SNA staff, not only teachers', placement recommendations framed as fit, and PSI 3.3.6.",
"evidence":"Structured observation note · Appendix 5 · Log sheet tagged 4. Systemic Change"},

("Visit a range of special education settings","Talk to therapy and SNA staff, not only teachers"): {
"why":   "In special settings a large part of the day may be delivered by SNAs and, where present, by therapists; a teacher-only account misses how communication systems, personal care and regulation work in practice. CORU SoP 5.39 is mapped here. The Reference sheet asks whether communication systems are used consistently by everyone, and only the people using them can tell you. Speaking to the whole team also helps PSI 3.3.6 evidence: it shows you understood the setting as a system, not a classroom.",
"s1":    "WATCH FOR — who does what during the visit: which adults support communication, meals, toileting and transitions; who manages distress; whether therapy happens in the classroom or elsewhere, and whether it comes from the HSE CDNT or another arrangement (ask; do not assume).\n\nWRITE DOWN — the roles present, not names, and one thing each role told you about how the setting works.\n\nASK AFTERWARDS — ask an SNA 'what do you wish psychologists knew about a day here?' and ask a therapist, if present, 'how does your work link with what happens in the classroom?'",
"s2":    "YOU TAKE — preparing two or three short questions for each role before the visit, and asking the teacher or principal at the start whether you may speak briefly with SNAs and therapy staff.\n\nTHEY HOLD — any discussion of individual children in the setting, and any agreement about future joint work.\n\nWHY THAT SPLIT — the questions are about how the setting works, which is safe and useful. Individual children are not your cases, and discussing them would need consent the visit does not have.",
"s3":    "YOU RUN IT — hold brief conversations with at least one SNA and, where available, one therapist during a visit, and bring what you learned to supervision.\n\nWHAT THEY ARE WATCHING FOR — speaking only to the teacher and principal; treating SNAs as a less reliable source; questions about particular children; taking staff away from pupils at busy moments.\n\nSTEPPING IN LOOKS LIKE — 'the SNAs are on their break at eleven — that might be a good moment to ask them how the visual timetable is used.'",
"s4":    "YOU DO IT ALONE — at every setting visit, speak with the people delivering the day-to-day support, not only the teaching staff, and record what each role contributes to how the setting works.\n\nPASS TEST — You spoke to the people delivering\n\nEVIDENCE TO FILE — the observation note, with a section for each role's account (no names); the Appendix 5 entry. Log against 4. Systemic Change and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — an account of a special class that describes the teacher's plan in detail and says nothing about how the three adults supporting it actually spend the day.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why SNA and therapy staff hold information teachers do not, how to approach them respectfully and briefly, and how their accounts change what you would write about fit between a child and a setting.\n\nWHEN IT GOES WRONG — if staff are wary of talking to a psychologist, explain you are there to learn how the setting works, not to assess anyone, and leave it there if they still prefer not to.",
"error": "Taking the teacher's or principal's account as the whole picture of how a special setting works.",
"feeds": "→ Feeds into 'Log each visit separately in Appendix 5', 'Contribute a psychological perspective', and placement recommendations.",
"evidence":"Observation note · Appendix 5 · Log sheet tagged 4. Systemic Change"},

("Visit a range of special education settings","Log each visit separately in Appendix 5"): {
"why":   "The Reference sheet warns against treating one visit as covering special education: a special school, a special class and an early intervention class are different settings with different pupils. PSI 3.3.6 is currently unmet, and the evidence that it has been met will be your record. If three visits sit in one combined entry, nobody reading the portfolio can tell what range you saw. Handbook Appendix 5 is the standard mapped here; read the Handbook itself for what each entry must contain. The reflection is yours to write — this row gives structure only.",
"s1":    "WATCH FOR — how your supervisor, or a more senior trainee, records placement activity that counts towards a settings requirement: what they name (setting type, age range, date), and how they separate what happened from what they learned.\n\nWRITE DOWN — for each visit, while fresh: date (DD/MM/YYYY), setting type, age range and UCD Table 3 band, what you observed under each heading, and who you spoke to by role.\n\nASK AFTERWARDS — 'when you read a trainee's Appendix 5, what tells you they actually learned something from a visit?'",
"s2":    "YOU TAKE — writing a separate Appendix 5 entry for each visit, in your own words, and logging each visit day on its own row in the Log.\n\nTHEY HOLD — reading the entries in supervision and confirming the visits as placement activity.\n\nWHY THAT SPLIT — the reflection must be your own work; nobody, including this file, writes it for you. Your supervisor's role is to confirm what took place and to push your thinking in supervision.",
"s3":    "YOU RUN IT — bring the entry for your first setting visit to supervision within a week of the visit and use the discussion to strengthen the next one.\n\nWHAT THEY ARE WATCHING FOR — entries that list activities without learning; visits merged into one entry; identifying details of pupils or staff; an entry that does not say what kind of setting it was, so it cannot show range.\n\nSTEPPING IN LOOKS LIKE — 'this reads as a timetable of the day. What do you now think about special class placement that you didn't think before?'",
"s4":    "YOU DO IT ALONE — write a separate, dated Appendix 5 entry for every setting visited, naming the setting type and age range, what you observed, and what changed in your thinking, in your own words, with no identifying details.\n\nPASS TEST — Each setting is its own entry\n\nEVIDENCE TO FILE — one Appendix 5 entry per visit; one Log row per visit day. Log against 4. Systemic Change. Prompts to structure your own reflection: what you expected, what you saw, what surprised you, what you would now write differently about fit.\n\nWHAT FAILURE LOOKS LIKE — one paragraph headed 'special education visits' covering three settings, which cannot show PSI 3.3.6 has been met.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why each visit needs its own entry, what makes an entry show learning rather than attendance, and how the entries together show range against PSI 3.3.6. You can offer prompts, but you can also explain why a reflection has to be written by the person who had the experience.\n\nWHEN IT GOES WRONG — if you find visits were merged or not logged, correct the Log and write the missing entries from your notes now, dated as written, and tell your supervisor.",
"error": "Combining several setting visits into one entry, so the range required by PSI 3.3.6 cannot be seen.",
"feeds": "→ Feeds into PSI 3.3.6 evidence, 7. Supervision discussion, and the reflective learning essay (which is yours to write).",
"evidence":"Appendix 5 — one entry per setting · Log sheet tagged 4. Systemic Change"},

# ── 4. SYSTEMIC CHANGE · Attend service team meetings ──

("Attend service team meetings","Understand how casework is prioritised here"): {
"why":   "The Reference sheet: team meetings are where you learn what the service actually is — its priorities, pressures and how decisions are made — and the referral pathway, waiting times and priorities are 'not written down anywhere'. Every service decides differently who is seen first, whether by school prioritisation within allocated time, by clinical urgency, or by other criteria; do not assume Cavan works like Roscommon. CORU SoP 5.5 is mapped here. If you do not know what drives the queue, your recommendations will assume a speed of follow-up the service cannot give.",
"s1":    "WATCH FOR — at team meetings, how referrals are discussed: who brings them, what makes one urgent (safety, exclusion risk, a transition deadline), who decides, and what happens to cases that wait. Notice what is never said aloud but clearly shapes decisions.\n\nWRITE DOWN — the pathway from referral to closure as a simple flowchart, and the factors that move a case up or down the queue. No child or school names.\n\nASK AFTERWARDS — 'can I ask how a referral like that one usually gets prioritised?' — the Reference sheet's example of a question useful to you and unthreatening to everyone.",
"s2":    "YOU TAKE — drafting the pathway flowchart from what you hear in your first few meetings, and checking it with your supervisor.\n\nTHEY HOLD — any decision about the priority of your own cases.\n\nWHY THAT SPLIT — mapping the pathway is learning the service. Prioritising cases involves risk and fairness between schools, and those decisions rest with qualified staff and the service's management.",
"s3":    "YOU RUN IT — for a case you are working on, explain in supervision where it sits in the queue and why, and what that means for when any follow-up can realistically happen.\n\nWHAT THEY ARE WATCHING FOR — assuming the Roscommon pathway applies; forming opinions on whether the prioritisation is right before you understand it; recommending reviews on timescales the service cannot meet.\n\nSTEPPING IN LOOKS LIKE — 'you've recommended a review in six weeks — given where this school's time sits, is that something we can actually do?'",
"s4":    "YOU DO IT ALONE — describe accurately how this service decides what gets seen and when, and use it to set realistic timescales in your own recommendations and to tell schools and families honestly what to expect.\n\nPASS TEST — You know what determines the queue\n\nEVIDENCE TO FILE — your pathway flowchart as a working paper; a note in the team-meeting record of what you learned. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — telling a parent 'we'll see him again before Christmas' when the school has already used its time for the term.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer how this service prioritises, how it differs from another service you know, and why knowing the queue is part of writing realistic recommendations. You can name what drives prioritisation without judging it.\n\nWHEN IT GOES WRONG — if you have promised a timescale the service cannot meet, tell your supervisor, and contact the family or school to correct it before they are left waiting.",
"error": "Assuming the prioritisation rules from your last placement apply to this service.",
"feeds": "→ Feeds into 'Note what the service can and cannot offer', realistic recommendations, and 6. Ethical Practice (honesty about timescales).",
"evidence":"Pathway flowchart · team meeting record · Log sheet tagged 4. Systemic Change"},

("Attend service team meetings","Note what the service can and cannot offer"): {
"why":   "The Reference sheet lists, among the things to note in team meetings, caseload sizes, what gets prioritised and which other services are often involved, because this is what makes recommendations realistic. A recommendation for weekly psychologist sessions from a service that works through consultation and time allocated to schools will not happen, and the family will blame the school or the service. CORU SoP 5.5 is mapped here. Knowing the limits also tells you when to signpost to the HSE CDNT, CAMHS or Tusla rather than promise something yourself.",
"s1":    "WATCH FOR — what colleagues say the service does and does not do: individual therapy or not, how often reviews happen, group work, training for schools, which age groups and settings, and what is routinely passed to other services (CDNT, CAMHS, Tusla, primary care psychology).\n\nWRITE DOWN — two lists, 'this service offers' and 'this service refers on for', each with the route.\n\nASK AFTERWARDS — 'what do schools most often ask this service for that it can't provide, and how do you explain that to them?'",
"s2":    "YOU TAKE — building the two lists and checking them against any written service description or policy you are given.\n\nTHEY HOLD — decisions about whether an exception can be made for a particular case.\n\nWHY THAT SPLIT — knowing the standard offer is basic orientation. Exceptions weigh one school's needs against the service's capacity, which is a management judgement.",
"s3":    "YOU RUN IT — review the recommendations in your own draft reports against the lists, and bring any you are unsure of to supervision.\n\nWHAT THEY ARE WATCHING FOR — recommendations the service cannot deliver ('the psychologist will provide weekly sessions'); signposting to services with long waiting lists as if they were quick; not signposting at all.\n\nSTEPPING IN LOOKS LIKE — 'who would deliver that? If it's us, we don't offer that. If it's the CDNT, what's the route in, and what do we tell the family about the wait?'",
"s4":    "YOU DO IT ALONE — before finalising any recommendation, check who will deliver it and whether they can, and signpost honestly to other services where this one cannot help.\n\nPASS TEST — You know the limits before recommending\n\nEVIDENCE TO FILE — your service offer and signposting lists as working papers; report recommendations each naming who delivers them. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a report whose recommendations assume ongoing psychologist involvement the service has never offered, discovered by the school at the review meeting.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer what this service offers, what it refers on and to whom, and why every recommendation should name who delivers it. You can explain how to tell a family about waiting times honestly without discouraging them.\n\nWHEN IT GOES WRONG — if an issued report promised something the service cannot give, tell your supervisor, agree how to tell the family and school, and correct the record.",
"error": "Recommending something that no one in the service, or in any service the child can actually reach, will deliver.",
"feeds": "→ Feeds into 'Understand how casework is prioritised here', 'Know the SENO route and what the NCSE can do', and 5. Working with Others.",
"evidence":"Service offer list · report recommendations · Log sheet tagged 4. Systemic Change"},

("Attend service team meetings","Prepare something to contribute"): {
"why":   "The Reference sheet: sitting silently for a term is a wasted term. Team meetings are the one routine place to practise contributing among colleagues rather than in supervision, which CORU SoP 2.16 names directly and which is mapped here. The advice is to prepare one small, specific thing — a case question, a resource you found, an offer to take something on — because small and specific beats impressive. Logging attendance without logging a contribution leaves you nothing to show for the meetings.",
"s1":    "WATCH FOR — what kinds of contribution land well in this team: brief case questions, sharing a resource, offering to take a task, a short update. Notice how long people speak, how they introduce a case without identifying it unnecessarily, and when in the agenda a newcomer can speak.\n\nWRITE DOWN — two or three contributions from others that were useful, and what made them useful.\n\nASK AFTERWARDS — ask your supervisor 'is there anything coming up at the next meeting where it would be useful for me to bring something?'",
"s2":    "YOU TAKE — preparing one contribution for each meeting and agreeing it with your supervisor beforehand: a question, a resource, or an offer.\n\nTHEY HOLD — deciding whether your contribution fits the agenda, and any presentation of a case that is still active.\n\nWHY THAT SPLIT — preparing and delivering a small contribution is the practice. Deciding what the team needs to hear about an active case depends on the service's priorities and the case's sensitivity.",
"s3":    "YOU RUN IT — make your prepared contribution at the meeting, with your supervisor there, and ask them afterwards how it came across.\n\nWHAT THEY ARE WATCHING FOR — silence; a contribution that runs too long; opinions on how the service should be run (the Reference sheet: save those until you understand why it runs as it does); jargon.\n\nSTEPPING IN LOOKS LIKE — your supervisor making a gap for you: 'our trainee found something useful on this last week — do you want to say?'",
"s4":    "YOU DO IT ALONE — go into every team meeting with one prepared contribution, make it briefly, and log what you contributed as well as that you attended.\n\nPASS TEST — You spoke\n\nEVIDENCE TO FILE — a Log entry for each meeting with date, meeting type and your contribution; a note in supervision of any feedback. Log against 4. Systemic Change and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — ten Log rows reading 'attended team meeting' and nothing else, from a whole term.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why preparing one small thing is better than waiting for the right moment, give examples of useful trainee contributions, and explain the difference between a question and an opinion on service design.\n\nWHEN IT GOES WRONG — if a contribution falls flat or overreaches, talk it through with your supervisor afterwards, and make the next one smaller and more specific rather than going quiet.",
"error": "Attending for a whole term without speaking, then logging only attendance.",
"feeds": "→ Feeds into 'Contribute a psychological perspective', 'Deliver the good practice presentation', and 5. Working with Others.",
"evidence":"Log entry with contribution noted · supervision note · Log sheet tagged 4. Systemic Change"},

("Attend service team meetings","Contribute a psychological perspective"): {
"why":   "The Reference sheet: in multi-disciplinary meetings different professions formulate differently and use the same words for different things, and the disagreement is usually about the model, not the facts. Hall (2005, Journal of Interprofessional Care, 19(S1)) describes professional cultures as barriers to teamwork; Frost and Robinson (2007, Child Abuse Review, 16(3)) look at joining up children's services. Your contribution is the psychological formulation, stated plainly and without jargon. CORU SoP 2.11 is mapped here. If you add nothing another discipline would not, the team has lost the reason for having a psychologist there.",
"s1":    "WATCH FOR — how your supervisor adds a psychological view in a multi-disciplinary meeting: linking behaviour to function or context, pointing to interacting factors rather than one cause, asking what the child's view is, or questioning an assumption. Listen for where people use the same word ('anxiety', 'regulation', 'behaviour') to mean different things.\n\nWRITE DOWN — the contribution and why it was psychological rather than medical, therapeutic or educational.\n\nASK AFTERWARDS — 'what did you think the other professions in the room were missing, and how did you decide how to say it?'",
"s2":    "YOU TAKE — preparing a short psychological formulation of a case you know, in plain language (three or four sentences), for your supervisor to review before the meeting.\n\nTHEY HOLD — speaking for the service in the meeting, and handling any disagreement with another discipline.\n\nWHY THAT SPLIT — writing a jargon-free formulation is practice you need. Disagreements between disciplines about an active case have consequences for the child and the working relationships, which your supervisor manages.",
"s3":    "YOU RUN IT — give the psychological formulation of a case in a multi-disciplinary or team meeting, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — jargon; repeating what the teacher or therapist already said; arguing with another profession's view rather than adding to it; a formulation too long to be heard.\n\nSTEPPING IN LOOKS LIKE — 'to put that another way — the pattern seems to be that it happens when demands go up and the adults nearby change, which gives us something to try.'",
"s4":    "YOU DO IT ALONE — in a team or multi-disciplinary meeting, offer a psychological view of a case, in plain language, that adds something the other disciplines did not bring, and notice where your model differs from theirs.\n\nPASS TEST — You added something another discipline would not\n\nEVIDENCE TO FILE — Log entry with meeting type and your contribution; supervision note on how it was received. Log against 4. Systemic Change and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a contribution that restated the diagnosis already given, in more technical words, and changed nothing about the plan.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer what a psychological perspective adds in a team (formulation of interacting factors, function, the child's voice, testable hypotheses), how professions use the same words differently, and how to find where a disagreement really lies (Hall, 2005).\n\nWHEN IT GOES WRONG — if another professional dismisses your view, do not argue it in the room; ask a question that brings out the difference in models, and take it to supervision.",
"error": "Repeating another discipline's view in psychological jargon instead of adding a distinct perspective.",
"feeds": "→ Feeds into 2. Formulation, 5. Working with Others, and 'Learn consultation models'.",
"evidence":"Log entry with contribution · supervision note · Log sheet tagged 4. Systemic Change"},

# ── 4. SYSTEMIC CHANGE · Learn consultation models ──

("Learn consultation models","Learn a structured problem-solving model"): {
"why":   "The Reference sheet sets out the stages of problem-solving consultation: problem identification, problem analysis, plan design, implementation, evaluation. The model comes from behavioural consultation (Bergan & Kratochwill, 1990, Behavioral Consultation and Therapy). The Reference sheet says the evidence consistently shows problem identification predicts outcome; an early source often cited for this is Bergan and Tombari (1976, Journal of School Psychology) — read it before quoting the finding. Without a model you default to advice-giving, which the Reference sheet calls the least effective form of consultation and the most likely to be politely ignored. CORU SoP 5.38 is mapped here.",
"s1":    "WATCH FOR — in a consultation your supervisor leads, how long they stay on defining the problem before any strategy is mentioned; the questions that turn 'he's disruptive' into something observable ('calls out during whole-class maths, about how often?'); and whether they agree a way to measure change before planning.\n\nWRITE DOWN — the stage-by-stage sequence as it actually happened, and the time spent on each stage.\n\nASK AFTERWARDS — 'at what point did you know you and the teacher agreed on what the problem was, and what did you do when you didn't?'",
"s2":    "YOU TAKE — reading one source on the model (Bergan & Kratochwill, 1990, or a UK version such as the problem analysis framework of Monsen, Graham, Frederickson and Cameron, 1998, Educational Psychology in Practice), and writing a one-page crib sheet of the stages with example questions for each.\n\nTHEY HOLD — leading the consultation itself at first.\n\nWHY THAT SPLIT — learning the stages is desk work. Running them live with a teacher under pressure takes judgement about when to hold back from solutions, which you learn by watching first.",
"s3":    "YOU RUN IT — lead a problem-solving consultation with a teacher, using your crib sheet, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — jumping to strategies before the problem is defined; accepting a vague problem ('his behaviour'); skipping the agreement on how change will be measured; losing the stages when the teacher goes off track.\n\nSTEPPING IN LOOKS LIKE — 'before we get to what to try — can we pin down exactly what it looks like, when it happens most, and what you'd see if it were better?'",
"s4":    "YOU DO IT ALONE — lead a consultation through each stage in order, name the model in your case note, and record the agreed problem definition, plan and review date.\n\nPASS TEST — You can name and follow its stages\n\nEVIDENCE TO FILE — the consultation record, headed by stage, with the model named; your crib sheet. Log against 4. Systemic Change and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a case note that reads 'discussed concerns; advised visual timetable and movement breaks', with no problem definition and no way to tell if anything worked.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the five stages, why problem identification carries the most weight, how to turn a vague concern into an observable definition, and where the model struggles (for example, when the problem is a relationship or a system rather than a behaviour).\n\nWHEN IT GOES WRONG — if a plan fails, go back to problem identification before designing a new plan; the problem was often defined wrongly in the first place.",
"error": "Moving to strategies before you and the teacher have agreed exactly what the problem is.",
"feeds": "→ Feeds into 'Follow one model explicitly for a set of consultations', 3. Intervention, and 'Identify a gap in the continuum'.",
"evidence":"Consultation record by stage · crib sheet · Log sheet tagged 4. Systemic Change"},

("Learn consultation models","Learn a solution-focused approach"): {
"why":   "The Reference sheet: solution-focused consultation starts from exceptions and preferred futures rather than causes, using scaling, the miracle question and amplifying what already works. It is quick and suits teachers under time pressure, and it is the framework you already used at Roscommon. The approach comes from solution-focused brief therapy (de Shazer, 1985, Keys to Solution in Brief Therapy); Rhodes and Ajmal (1995, Solution Focused Thinking in Schools) apply it to schools. CORU SoP 5.38 is mapped here. Using the techniques without the stance gives a list of questions with nothing behind them.",
"s1":    "WATCH FOR — how your supervisor asks exception questions ('when is it a bit better, even slightly?') and scaling questions ('on a scale of 0 to 10, where is it now, and what would one point higher look like?'), and how they follow the answer with 'what's different then?' rather than moving on.\n\nWRITE DOWN — the exact wording of the scaling and exception questions, the teacher's answers, and the small next step agreed.\n\nASK AFTERWARDS — 'how do you keep a teacher who wants to talk about everything that's wrong focused on the exceptions, without seeming to dismiss them?'",
"s2":    "YOU TAKE — writing your own scaling and exception questions for an upcoming consultation, adjusted from what you used in Roscommon for this service's settings.\n\nTHEY HOLD — deciding whether a solution-focused approach suits this consultation (for example, not where a child protection concern or a serious risk needs a full account of what is happening).\n\nWHY THAT SPLIT — the questions are a skill you already have and can sharpen. Judging when the approach is wrong for the situation needs experience you are still gaining.",
"s3":    "YOU RUN IT — lead a solution-focused consultation with a teacher using scaling and exception questions, with your supervisor observing.\n\nWHAT THEY ARE WATCHING FOR — asking the scaling question and not following it up; drifting back into problem talk; the stance slipping into advice; brushing aside a teacher's real concern too quickly.\n\nSTEPPING IN LOOKS LIKE — 'you said it's a four now — what's making it a four and not a two?'",
"s4":    "YOU DO IT ALONE — use scaling and exception questions fluently in a consultation, follow each answer up, agree one small step that builds on what already works, and name the approach in your record.\n\nPASS TEST — You can use scaling and exception questions\n\nEVIDENCE TO FILE — consultation record with the scaling scores and agreed step, with the approach named. Log against 4. Systemic Change and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a record showing a scaling question was asked, a number noted, and then a list of your suggestions with no link to the number.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the solution-focused stance (the client has resources; build on exceptions), how scaling and exception questions work and how to follow them up, and where the approach is not enough, such as where a problem needs a full account of cause and risk.\n\nWHEN IT GOES WRONG — if a teacher says 'it's never better', ask about times it was less bad or about coping, and if that does not open anything, switch to a problem-solving approach and say so.",
"error": "Using scaling and exception questions as a script while still giving advice, so the stance is missing.",
"feeds": "→ Feeds into 'Follow one model explicitly for a set of consultations', 'Ask your supervisor which model they use', and 3. Intervention.",
"evidence":"Consultation record · Log sheet tagged 4. Systemic Change"},

("Learn consultation models","Ask your supervisor which model they use"): {
"why":   "The Reference sheet points out that the Irish standards fold consultation into other competencies rather than naming it, so you can get through a placement without ever learning a model. The BPS Standards for Accreditation (2023) name consultation as a competency in its own right; read them for the wording. Asking your supervisor which model they use, and whether they were trained in it, tells you what you can learn by watching and where you need other sources. CORU SoP 4.5 is mapped here. A supervisor working from an informal blend is common, and it is worth knowing.",
"s1":    "WATCH FOR — in the consultations you observe, what your supervisor actually does: the sequence, the typical questions, whether they define the problem first or look for exceptions, and whether they name a model to the teacher.\n\nWRITE DOWN — your guess at the model, with the evidence, before you ask them.\n\nASK AFTERWARDS — 'which consultation model do you use, were you trained in it formally, and where do you depart from it?'",
"s2":    "YOU TAKE — asking the question in supervision, comparing their answer with what you observed, and noting where they differ.\n\nTHEY HOLD — their account of their own practice and training, and any recommendation for what you should read or which model you should adopt this year.\n\nWHY THAT SPLIT — asking is part of your learning. What model they practise, and why, is their professional judgement, and knowing it lets you use supervision well.",
"s3":    "YOU RUN IT — after a consultation you observed, discuss with your supervisor which stages or techniques they used and where the model was adjusted for the setting.\n\nWHAT THEY ARE WATCHING FOR — asking in a way that sounds like a test of them; assuming that a model named on paper is the model in practice; not following up on the training question.\n\nSTEPPING IN LOOKS LIKE — 'good question — honestly, I was trained in one approach and I've mixed in bits of another over the years. Let me show you where.'",
"s4":    "YOU DO IT ALONE — find out which consultation model your supervisor uses, whether they were trained in it and how, and use that to decide what you can learn from them and what you need to read or seek elsewhere.\n\nPASS TEST — You know whether they were trained in it\n\nEVIDENCE TO FILE — a supervision note recording the discussion and what you agreed to learn. Log against 4. Systemic Change and 7. Supervision.\n\nWHAT FAILURE LOOKS LIKE — ending the placement having watched a dozen consultations without being able to say what model your supervisor used.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why asking this question is useful, how to ask it respectfully, and how to learn from a supervisor whose model is informal or mixed while still learning one model properly yourself.\n\nWHEN IT GOES WRONG — if your supervisor uses a model you have not been taught, ask for a reading, and agree in supervision which model you will follow for your own consultations this placement.",
"error": "Assuming your supervisor follows a formal model without asking whether they were trained in it.",
"feeds": "→ Feeds into 'Follow one model explicitly for a set of consultations', 7. Supervision, and the supervision contract.",
"evidence":"Supervision record · Log sheet tagged 4. Systemic Change and 7. Supervision"},

("Learn consultation models","Follow one model explicitly for a set of consultations"): {
"why":   "The Reference sheet: learn one model properly this year rather than sampling four; name it in supervision, use it repeatedly, and notice where it fails, because competence comes from repetition with reflection, not from breadth. Never naming the model means it cannot be evidenced. Wagner (2008, in Kelly, Woolfson & Boyle, Frameworks for Practice in Educational Psychology) describes consultation as a framework for practice. CORU SoP 5.38 is mapped here. By the end of Cavan you should be able to say what the model gave you and where it fell short.",
"s1":    "WATCH FOR — across several consultations your supervisor leads, what stays the same (structure, stance, recording) and what they change for different teachers and problems.\n\nWRITE DOWN — for each consultation you observe, the model's stages and where the supervisor departed from them and why.\n\nASK AFTERWARDS — 'when do you decide the model isn't working for this teacher, and what do you do instead?'",
"s2":    "YOU TAKE — choosing one model with your supervisor at the start of Cavan and writing it into the Appendix 1 as a learning objective, with a target number of consultations to be agreed with your supervisor.\n\nTHEY HOLD — observing and giving feedback on selected consultations, and agreeing when you may move away from the model.\n\nWHY THAT SPLIT — the repeated practice has to be yours. Feedback on whether you are following the model, or only its surface, needs someone who has seen it done well.",
"s3":    "YOU RUN IT — run a series of consultations using the chosen model, naming it in each record, with your supervisor observing some and reviewing all the records.\n\nWHAT THEY ARE WATCHING FOR — drifting away from the model without noticing; using its techniques without its stance; not naming it in the record; not noticing where it fails.\n\nSTEPPING IN LOOKS LIKE — 'in this one you skipped straight from problem definition to strategies. What would the analysis stage have added?'",
"s4":    "YOU DO IT ALONE — follow one named model for a series of consultations, record it each time, and be able to say what it gave you, where it failed, and what you would use instead in those situations.\n\nPASS TEST — You can say what the model gave you\n\nEVIDENCE TO FILE — consultation records naming the model; supervision notes on what you learned; your Appendix 5 entries (your reflection to write). Log against 4. Systemic Change and 3. Intervention.\n\nWHAT FAILURE LOOKS LIKE — a set of consultations each run differently, none naming a model, so you cannot evidence that you learned one.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the model you used, what it is good for and poor at, and when you would choose something else — the Reference sheet's grade 5. Prompts for your own reflection: what the model made easier, where it got in the way, what you would do differently. The reflection itself is yours to write.\n\nWHEN IT GOES WRONG — if the model keeps failing in one kind of situation, that is a finding: bring it to supervision, read about an alternative, and record the switch rather than drifting.",
"error": "Sampling several models across the placement so none is learned properly or evidenced.",
"feeds": "→ Feeds into 3. Intervention, 7. Supervision, and consultation evidence for 4. Systemic Change.",
"evidence":"Consultation records naming the model · supervision record · Appendix 5 · Log sheet tagged 4. Systemic Change"},

# ── 4. SYSTEMIC CHANGE · Deliver the good practice presentation ──

("Deliver the good practice presentation","Cite current peer-reviewed evidence"): {
"why":   "The Reference sheet: if you say an approach works, cite something. PSI Code 4.2.2 is cited there as requiring you not to misrepresent the effectiveness of what you offer, and a training audience will act on what you tell them, so be as careful about overclaiming in a presentation as in a report. CORU SoP 5.41 is mapped here. A slide saying 'research shows' with no source cannot be checked by the teachers and should not be trusted by you. Evidence reviews such as the EEF's (Education Endowment Foundation) guidance reports are useful starting points, but check that the findings apply to Irish classrooms.",
"s1":    "WATCH FOR — how your supervisor or experienced colleagues use evidence in training: how many citations appear, how they say the strength of evidence in plain terms ('several good trials', 'promising but early'), and how they deal with popular approaches with weak evidence.\n\nWRITE DOWN — the sources they cite, how they describe the strength of the evidence, and anything they deliberately left out.\n\nASK AFTERWARDS — 'how do you handle it when teachers are already using something the evidence doesn't support?'",
"s2":    "YOU TAKE — searching for current peer-reviewed evidence on your topic (systematic reviews first, then key trials), reading the sources you cite yourself, and listing each claim on your slides with its source.\n\nTHEY HOLD — reviewing your claims-and-sources list for overclaiming before the presentation.\n\nWHY THAT SPLIT — finding and reading evidence is core work for a doctoral trainee. A second reader who knows the field catches the claim that goes further than the study did.",
"s3":    "YOU RUN IT — present a draft to your supervisor and defend each effectiveness claim with its source.\n\nWHAT THEY ARE WATCHING FOR — 'research shows' with no source; citing a book summary rather than the study; old evidence when newer reviews exist; findings from very different settings presented as if they transfer directly; strong words ('proven') for modest evidence.\n\nSTEPPING IN LOOKS LIKE — 'where's this claim from? What did the study actually find, and with which pupils?'",
"s4":    "YOU DO IT ALONE — make every effectiveness claim traceable to current peer-reviewed evidence you have read, state its strength honestly, and include a short reference list the audience can follow.\n\nPASS TEST — The evidence base is visible\n\nEVIDENCE TO FILE — slides and reference list; your claims-and-sources check. Log against 4. Systemic Change and 8. Research.\n\nWHAT FAILURE LOOKS LIKE — a teacher asks 'where's the evidence for that?' and you cannot name a study.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer how to find and weigh evidence for a training topic, how to describe strength of evidence without jargon, and why overclaiming in training is an ethical issue (the Reference sheet's reading of PSI 4.2.2 — check the Code for the exact wording).\n\nWHEN IT GOES WRONG — if you realise after the session that you overstated a finding, send a short correction with the handout, and tell your supervisor.",
"error": "Saying an approach 'works' or 'research shows' without a source you have read yourself.",
"feeds": "→ Feeds into 'Pitch it at teachers rather than examiners', 8. Research, and 6. Ethical Practice.",
"evidence":"Slides and reference list · Log sheet tagged 4. Systemic Change and 8. Research"},

("Deliver the good practice presentation","Pitch it at teachers rather than examiners"): {
"why":   "The Reference sheet: teachers want something usable on Monday, so every section should end with what to do, not what to know; cut the theory to what makes the practice make sense and put the rest in a handout. CORU SoP 5.40 and 5.8 are mapped here. Your review named delivery of training as a strength, so this is where you build on it. A presentation written for an examiner — citation-heavy, theory first — loses a staffroom in ten minutes, and nothing changes in classrooms.",
"s1":    "WATCH FOR — how experienced presenters turn a study into practice: one sentence on what was found, then 'what this means in your classroom is...'. Notice how much theory they use, where they put the references (often the handout), and how they use examples from Irish classrooms.\n\nWRITE DOWN — two or three translations you thought worked well, from finding to classroom action.\n\nASK AFTERWARDS — 'how do you decide what to cut when you have twenty minutes at a staff meeting?'",
"s2":    "YOU TAKE — rewriting each evidence slide so that it ends with a classroom action, and moving detail to a one-page handout.\n\nTHEY HOLD — feedback on the pitch, and knowledge of this staff's context (what they have already had training on, what they are sceptical of).\n\nWHY THAT SPLIT — translating evidence is the skill you are building. Knowing what this staffroom has already heard, and where the resistance is, is local knowledge your supervisor has.",
"s3":    "YOU RUN IT — rehearse the presentation with your supervisor or a peer acting as a teacher who asks 'so what do I do?' after every slide.\n\nWHAT THEY ARE WATCHING FOR — slides with an author and year but no 'so what'; jargon ('executive functioning', 'effect size') without translation; too many slides; reading from slides.\n\nSTEPPING IN LOOKS LIKE — 'I'm a second-class teacher with twenty-eight children — what do I do tomorrow morning because of this slide?'",
"s4":    "YOU DO IT ALONE — deliver a presentation in which every cited finding is followed by what it means for the audience's practice, in their language, with the theory and full references in a one-page handout.\n\nPASS TEST — Every citation is translated\n\nEVIDENCE TO FILE — slides, handout, and a note of the audience and setting. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — polite applause, no questions, and a staffroom conversation afterwards about how it was 'very academic'.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer how to turn a finding into a classroom action, how to decide what goes on a slide and what goes in the handout, and why training that stays at the level of knowledge rarely changes practice (Joyce & Showers, 2002, on the need for follow-up and coaching).\n\nWHEN IT GOES WRONG — if the audience is disengaged partway through, stop, ask what would be most useful to them now, and skip to the practical part.",
"error": "Presenting findings with author and year but never saying what the teacher should do differently because of them.",
"feeds": "→ Feeds into 'End with three things the school could do this term', 'Collect and file feedback from the school', and 5. Working with Others.",
"evidence":"Slides and handout · Log sheet tagged 4. Systemic Change"},

("Deliver the good practice presentation","End with three things the school could do this term"): {
"why":   "The Reference sheet: a one-page summary beats fifty slides, because people keep one page, and every section should end with what to do. Joyce and Showers (2002, Student Achievement Through Staff Development, 3rd ed.) are cited on the Reference sheet for why training alone rarely changes practice without follow-up. Three specific actions the school could take this term, within its own resources, give the training a way to reach classrooms. CORU SoP 5.40 is mapped here. Aspirations ('foster a culture of inclusion') cannot be done, so they won't be.",
"s1":    "WATCH FOR — how presenters close: whether the last slide is a summary of content or a short list of actions; how specific the actions are (who, what, when); whether they link to anything the school already does.\n\nWRITE DOWN — the closing actions from a training session you attend, and whether you could tell who would do each one and by when.\n\nASK AFTERWARDS — ask a teacher after a training session 'which of those will you actually try?' and note which kind of action they pick.",
"s2":    "YOU TAKE — drafting three actions, each specific, doable within existing time and staff, and fitting the school's current priorities as far as you know them.\n\nTHEY HOLD — checking the actions against what the school is already doing and has capacity for this term.\n\nWHY THAT SPLIT — writing concrete actions is the skill. Whether they fit the school's calendar and other demands is local knowledge, and an action that clashes with another initiative will be dropped.",
"s3":    "YOU RUN IT — close the presentation with your three actions and ask the staff which one they would start with, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — actions that need extra resources; vague verbs ('promote', 'foster', 'consider'); more than three; actions that are really the psychologist's to do, not the school's.\n\nSTEPPING IN LOOKS LIKE — 'can we make that second one smaller — what would a teacher do in the first week?'",
"s4":    "YOU DO IT ALONE — end the presentation, and the one-page handout, with three concrete actions the school could take this term within its resources, each saying who does what, and link them to the follow-up.\n\nPASS TEST — Actionable, not aspirational\n\nEVIDENCE TO FILE — the final slide and handout; any note of which action the school chose. Log against 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — a closing slide that reads 'Key messages: every child is different; relationships matter; inclusion is everyone's responsibility'.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the difference between an actionable and an aspirational recommendation, why three is better than ten, and why follow-up matters more than the presentation itself (Joyce & Showers, 2002).\n\nWHEN IT GOES WRONG — if staff say none of the actions is realistic, ask what would be, and agree one action with them before you leave the room.",
"error": "Closing with principles or aspirations rather than specific actions the school can take this term.",
"feeds": "→ Feeds into 'Collect and file feedback from the school', 'Say what would close the gap', and 3. Intervention at school level.",
"evidence":"Closing slide and handout · Log sheet tagged 4. Systemic Change"},

("Deliver the good practice presentation","Collect and file feedback from the school"): {
"why":   "The Reference sheet suggests a three-question form at the end: what will you do differently, what was most useful, what was missing. It takes two minutes, gives you evidence for the portfolio, and turns a presentation into a small piece of practice-based research. Kirkpatrick and Kirkpatrick (2006, Evaluating Training Programs, 3rd ed.) separate reaction, learning, behaviour and results; a feedback form measures reaction and intended behaviour, not actual change. CORU SoP 5.40 is mapped here. Without feedback you cannot show the presentation built capacity.",
"s1":    "WATCH FOR — how the service evaluates training: whether forms are used, what they ask, whether they are anonymous, and whether anyone follows up weeks later to see if practice changed.\n\nWRITE DOWN — the questions used, how responses are summarised, and where they are filed.\n\nASK AFTERWARDS — 'have you ever gone back to a school after training to see if anything changed? What did you find?'",
"s2":    "YOU TAKE — designing a short anonymous form using the Reference sheet's three questions, collecting it at the end, and summarising the responses honestly, including the critical ones.\n\nTHEY HOLD — any follow-up contact with the principal to find out whether the agreed actions were taken.\n\nWHY THAT SPLIT — designing and summarising the evaluation is your evidence and research practice. Follow-up with the principal is part of the service's ongoing relationship with the school.",
"s3":    "YOU RUN IT — collect the forms, write a half-page summary, and discuss it in supervision, including what you would change.\n\nWHAT THEY ARE WATCHING FOR — reporting only the positive comments; treating 'enjoyed it' as evidence of change; forms that collect names without need; no follow-up question about actual practice.\n\nSTEPPING IN LOOKS LIKE — 'what did the people who said something was missing tell you, and what would you change because of it?'",
"s4":    "YOU DO IT ALONE — collect anonymous feedback at the end, summarise it honestly, and where possible follow up (through your supervisor) to find out whether any of the three actions were taken, stating clearly which Kirkpatrick level each piece of evidence reaches.\n\nPASS TEST — You have evidence it built capacity\n\nEVIDENCE TO FILE — the form, the summary, any follow-up note; Appendix 5 entry (your reflection to write). Log against 4. Systemic Change and 8. Research.\n\nWHAT FAILURE LOOKS LIKE — no forms, or a folder of forms nobody summarised, and a portfolio that says only 'delivered training to staff'.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the difference between reaction and behaviour change (Kirkpatrick & Kirkpatrick, 2006), how to design a two-minute form that gives usable evidence, and how to write it up honestly as practice-based evaluation. Prompts for your own reflection: what the feedback told you, what surprised you, what you would change. The reflection is yours to write.\n\nWHEN IT GOES WRONG — if feedback is poor, report it as it is, take it to supervision, and say what you will change next time; honest poor feedback with a clear response is better evidence than no feedback.",
"error": "Collecting no feedback, or reporting positive reactions as if they showed practice had changed.",
"feeds": "→ Feeds into 8. Research (practice-based evaluation), 4. Systemic Change evidence, and the portfolio.",
"evidence":"Feedback form and summary · Appendix 5 · Log sheet tagged 4. Systemic Change and 8. Research"},
}
