"""CONDS records: EBSA, Separation Anxiety Disorder, Social Anxiety Disorder."""

_CORU = "3.1 · 3.2 · 5.28 · 5.29 · 5.30 · 5.31 · 5.32"
_PSI = "2.2.2 · 2.3.1 · 1.3.1 · 1.2.8"

CONDS = [
# =====================================================================
# 1. EBSA
# =====================================================================
{
 "name": "Emotionally Based School Avoidance (EBSA)",
 "code": "Not a DSM diagnosis · descriptive term (school refusal / EBSA / EBSNA)",
 "neps": "3. EMOTIONAL (3.6 School attendance) — and 3.2 Anxiety where anxiety is the driver",
 "coru": _CORU,
 "psi": _PSI,
 "law": "Education (Welfare) Act 2000 · Children First Act 2015 · EPSEN Act 2004 · Equal Status Acts 2000–2018 · GDPR",

 "what_it_is": [
  "A DESCRIPTION, NOT A DIAGNOSIS. A pattern in which a child or young person has severe difficulty attending school because of emotional distress — usually anxiety — rather than because they have chosen not to go or because a parent keeps them home. It appears in no DSM-5-TR or ICD-11 chapter; the underlying anxiety or low mood may.",
  "NEPS's own term is 'reluctant attendance and school avoidance behaviour' and it covers reluctance, lateness, missing specific classes or times of day, and regular or long absence. NEPS notes 'emotionally based school avoidance' and 'school refusal' as commonly used equivalents (NEPS, Managing Reluctant Attendance and School Avoidance Behaviour: A Good Practice Guide for Primary Schools, 2023 — separate post-primary guide; check current versions on gov.ie).",
  "The classic distinction (Berg, Nichols & Pritchard, 1969; refined by Heyne et al., 2019): in school refusal the child is at home WITH the parents' knowledge, is distressed at the prospect of school, and the parents have usually tried to get them in. In truancy the parents typically do not know. Heyne et al. (2019) add SCHOOL WITHDRAWAL (parent keeps the child home) and SCHOOL EXCLUSION (the school keeps the child out, including informal exclusion).",
  "FUNCTION, NOT FORM. Kearney & Silverman (1990) proposed four functions that maintain non-attendance: (1) avoiding school-based things that provoke distress; (2) escaping aversive social or evaluative situations; (3) seeking attention or proximity to a parent; (4) pursuing tangible rewards outside school. Functions 1–2 are negatively reinforced, 3–4 positively. The same absence can serve different functions in different children — this is what the formulation must establish.",
  "THE MAINTAINING CYCLE is the core mechanism: anxiety → avoidance → immediate relief → the next attempt is harder, while gaps in learning, isolation and questions about absence make return more aversive and home more comfortable (West Sussex EPS, 2018; reproduced in the NEPS guide as the cycle that reinforces school avoidance).",
  "It is SYSTEMIC. NEPS (2023) groups risk factors into child, family, school and social, and stresses there is no single cause. Unmet special educational needs, bullying, transition, loss and family stress all appear. A formulation that sits only inside the child is incomplete.",
  "Onset tends to cluster at TRANSITIONS — starting primary, moving to post-primary — and after holidays, illness or a long weekend (NEPS, 2023; Kearney, 2008).",
 ],
 "what_it_is_not": [
  "NOT truancy. Different formulation, different response. Treating an anxious child as a truant (sanctions, pressure without support) typically increases avoidance (Heyne et al., 2019; Elliott & Place, 2019).",
  "NOT bad parenting. NEPS (2023) explicitly warns that parents often fear blame and judgement, and that this blocks the conversation. Parents of children with EBSA have usually been fighting the battle every morning for weeks.",
  "NOT 'just anxiety that will pass if left alone'. Waiting usually entrenches it: the maintaining cycle means every day out makes the next day harder. Early action is the single most consistent recommendation in the guidance (NEPS, 2023; West Sussex EPS, 2018).",
  "NOT solved by a reduced timetable on its own. A reduced day can be one planned step of a graduated return; open-ended, it becomes informal exclusion. The Department of Education's guidelines on reduced school days set out recording and notification requirements (Department of Education, 2021 — check current guidance).",
  "NOT a problem of the child's will. 'He could come in if he wanted to' misreads the mechanism. Avoidance is learned because it works in the short term; the child usually wants to be able to go.",
  "NOT only an adolescent problem. It can present at school entry as separation distress and in primary as somatic complaints — tummy aches and headaches that fade once the child is allowed to stay home (NEPS, 2023).",
  "NOT the same as home education. Parents in Ireland may educate at home under the Education (Welfare) Act 2000 but must register with Tusla; a child out of school with no registration is a non-attendance matter, not home education.",
 ],
 "prevalence": [
  "OVERALL: school refusal is commonly cited as affecting around 1–2% of school-age children, and a larger share of clinic-referred children (Heyne & King, 2004; Elliott & Place, 2019) — rate varies with definition; check before quoting.",
  "IRELAND — CHRONIC ABSENCE (all causes, not EBSA): Tusla's annual attendance report for 2022/23, as reported by the Department of Education (19/05/2025), recorded over 110,000 primary and 65,000 post-primary pupils missing 20 or more days. This is total absence, not EBSA — never quote it as an EBSA rate. Check the latest Tusla report.",
  "IRELAND — EBSA SPECIFICALLY: no national EBSA rate is published — rate not stated here, check before quoting. Local CYPSC and NEPS data may exist.",
  "EARLY YEARS 0–5: separation-based reluctance at school entry is common and usually transient. Compulsory attendance under the Education (Welfare) Act 2000 begins at 6.",
  "SCHOOL AGE 6–12: peaks around school entry and again at 10–11 (Kearney, 2008 — check). Somatic complaints and separation themes dominate.",
  "ADOLESCENT 13–16: the peak in most accounts, especially at the move to post-primary. Social-evaluative and academic pressures dominate; co-occurring low mood is more common.",
  "SEX RATIO: studies generally report no strong sex difference (Kearney, 2008) — check before quoting.",
 ],
 "cooccurring": [
  {"name": "SEPARATION ANXIETY", "rate": "common, especially in younger children — rate not stated here, check (Egger et al., 2003 found a strong association)",
   "presents": "distress at drop-off, ringing home, calm once home. Function is usually proximity to the parent (Kearney function 3)."},
  {"name": "SOCIAL ANXIETY", "rate": "common, especially in adolescents — rate not stated here, check",
   "presents": "avoidance of specific classes, oral work, PE changing rooms, the canteen. Function is escape from evaluation (Kearney function 2)."},
  {"name": "DEPRESSION / LOW MOOD", "rate": "elevated (Egger et al., 2003) — rate not stated here, check",
   "presents": "withdrawal, sleep reversal, loss of interest beyond school. ALWAYS screen and ask about risk; long absence can cause as well as reflect low mood."},
  {"name": "AUTISM", "rate": "elevated — rate not stated here, check",
   "presents": "sensory overload, unpredictability, masking all day then refusal. NEPS (2023) points to the Autism Good Practice Guidance for Schools (2022)."},
  {"name": "UNMET LEARNING NEED (SLD, DLD, ADHD)", "rate": "elevated — rate not stated here, check",
   "presents": "avoidance of specific subjects or reading aloud; distress about falling behind. Assess attainment — escape from failure looks identical to anxiety."},
  {"name": "BULLYING / PEER DIFFICULTY", "rate": "a frequent precipitant — rate not stated here, check",
   "presents": "sudden onset in a previously settled child, avoidance of yard or bus. Ask directly and privately; check the school's anti-bullying procedures."},
  {"name": "PHYSICAL ILLNESS / SOMATIC COMPLAINT", "rate": "common — rate not stated here, check",
   "presents": "real symptoms that peak on school mornings. A GP review is appropriate before assuming the cause is emotional, and does not preclude it."},
 ],
 "recommendations": [
  "ACT EARLY AND SAY SO. Name in the report that early, consistent action is the strongest predictor of return, and that delay entrenches avoidance (NEPS, 2023; West Sussex EPS, 2018).",
  "ONE KEY ADULT. A named key school contact, ideally chosen with the pupil, who holds the plan, meets the child at the door and is the link with home (NEPS, 2023).",
  "FORMULATE THE FUNCTION. Use the pupil's, parents' and school's accounts separately — they usually differ — and a functional measure such as the SRAS-R (Kearney, 2002). Write the hypothesised function(s) in the report, because the plan follows from them.",
  "GRADUATED RETURN, written as small agreed steps the pupil believes they can manage (e.g. arrive at the gate → sit in the library with the key adult → one favoured class), with dates. NEPS (2023) provides templates: 'My Being in School Plan' and 'Steps in a Gradual Return'. Steps go forward; setbacks mean pause, not restart.",
  "REDUCE THE PULL OF HOME. Agree with parents that school hours at home look like school hours — no screens, no treats — so staying home is not rewarded. Frame this as kind firmness, not punishment.",
  "ADDRESS THE SCHOOL-SIDE TRIGGERS the formulation identified: bullying, a subject pitched too high, a changing room, a particular corridor, a teacher relationship. A plan that changes only the child is incomplete.",
  "TEACH COPING SKILLS in school — relaxation, coping self-talk, graded exposure. NEPS supports FRIENDS programmes in many schools (check local availability).",
  "REDUCED DAY ONLY AS A TIME-LIMITED STEP, recorded and notified per the Department's reduced school day guidelines, with a review date and a plan to build back.",
  "CONTINUUM LEVEL: School Support for emerging reluctance; School Support Plus where absence is extended or outside agencies are involved. Record in the Student Support File.",
  "REFER: Tusla Education Support Service (Educational Welfare Service) when the pupil is absent more than 20 days and school-level efforts have been tried (NEPS, 2023 wording). Separately, the principal must notify the Educational Welfare Officer when a pupil has been absent for an aggregate of not less than 20 school days in a school year — i.e. 20 days or more (Education (Welfare) Act 2000, s.21(4)). GP → CAMHS or Primary Care Psychology for moderate to severe anxiety or low mood. Consider Meitheal for multi-agency need.",
  "DO NOT recommend home tuition or an indefinite reduced timetable as the plan. Both remove the exposure that recovery depends on, and home tuition has its own eligibility criteria — check.",
 ],
 "explain_parent": [
  "'This isn't bad behaviour and it isn't your parenting. It's anxiety — and the way anxiety works is that avoiding the thing makes you feel better right now and worse tomorrow.'",
  "'Every morning she stays home, the relief teaches her brain that school was dangerous and home was safe. That's why it gets harder, not easier, the longer it goes on.'",
  "'The aim isn't to force her through the door. It's small steps she can actually manage, planned with her, and then keeping going with those steps even on hard days.'",
  "'Some upset on the way in is expected and it doesn't mean the plan is failing. What matters is that she learns she can cope with the feeling.'",
  "'School hours at home need to look like school hours — not punishment, just not more attractive than school.'",
  "'You'll be asked about Tusla at some point. The school has to report it once a child has missed 20 days or more in the school year — that's the law for every child, and the Education Welfare Officer is there to help as well as to monitor.'",
  "SIGNPOST: NEPS guidance for parents on supporting a child who is reluctant to attend school (primary and post-primary versions on gov.ie), the GP, and the local CYPSC school avoidance resources where they exist.",
 ],
 "explain_teacher": [
  "'This is anxiety-driven non-attendance, not truancy. Pressure and sanctions usually make it worse; predictability and a warm key adult make it better.'",
  "'The welcome matters more than anything you teach on the first day back. No comments about the absence in front of the class. A quiet, ordinary welcome.'",
  "'Please agree in advance what you'll say if a classmate asks where she's been — and give her a cover line she's happy with.'",
  "'The plan is a set of small steps. If she only manages the library today, that's the plan working. Please don't push beyond the step agreed — it damages trust in the plan.'",
  "'Tell the key contact what you notice: which lessons, which days, which people. That's the information the formulation depends on.'",
  "'Send work home in small, doable chunks. Falling behind is one of the things that makes going back harder.'",
 ],
 "explain_child": [
  "YOUNGER: 'Sometimes our body gets a big worried feeling about school — tummy aches, wobbly legs. Staying home makes the feeling go away for a while, but then it comes back even bigger. We're going to make a plan together with really small steps, so the worry gets smaller.'",
  "OLDER: 'Anxiety works like this: avoid it, feel better now, find it harder next time. You're not weak and you're not in trouble. We're going to work out what the hardest bits are and plan steps you think you can manage.'",
  "ASK: 'If school was a bit better, what would be different?' and 'What's the hardest part — getting up, getting there, walking in, or something during the day?' The answer locates the function.",
  "ASK ABOUT THE GOOD BITS TOO: 'Is there any part of the day that's okay?' That is often the first step of the return.",
  "OFFER CONTROL where you honestly can: the order of steps, the key adult, what to say to classmates. Do not offer control over whether to return — that is not honest.",
  "ASK DIRECTLY AND CALMLY about bullying, and about feeling so low they wish they weren't here. Children rarely volunteer either.",
 ],
 "analogies": [
  "THE COLD SWIMMING POOL: 'Jumping out every time it's cold means it always feels cold. Staying in, a bit at a time, is how you get used to it.' Works with children of all ages and with parents who fear the distress.",
  "THE SMOKE ALARM: 'Your alarm is going off for toast, not for a fire. It's a real alarm and a real feeling — it's just set too sensitive for school.' Good with older children; validates without agreeing that school is dangerous.",
  "THE PATH IN LONG GRASS: 'Every time you walk the avoidance path it gets clearer and easier to take. The school path grows over. We need to start walking the school path again — a little bit each day.' Good for parents; explains why delay matters.",
  "THE LADDER: steps of a graduated return as rungs. 'We don't jump to the top. We go up one rung and stay there until it feels okay.' Works with younger children and gives a visual for the plan.",
 ],
 "language": [
  "'EBSA' is the most widely used term in UK EP practice (West Sussex EPS, 2018). NEPS uses 'reluctant attendance and school avoidance behaviour'. Use NEPS's term in NEPS paperwork and explain the equivalence.",
  "'EBSNA' (emotionally based school non-attendance) is preferred by some services and families because 'avoidance' can sound like a choice. Ask what the family is comfortable with.",
  "'School refusal' is the older research term (Berg et al., 1969; Kearney & Silverman, 1990) and is still used in the literature. Many families dislike it for the same reason — it implies wilfulness.",
  "Avoid: 'school phobic' (outdated), 'refuses', 'won't come in', 'playing the system', 'truant' for an anxious child. PSI 1.2.8 requires opinion to be labelled as opinion.",
  "In reports: describe what happens ('attended 23 of 60 days; arrives distressed; leaves before lunch') rather than interpreting motive.",
 ],
 "red_flags": [
  "RED FLAG — self-harm, suicidal thoughts, or talk of not wanting to be alive. Same-day risk route: stay with it, inform the DLP and your supervisor today, follow the service risk protocol, GP/CAMHS or emergency route as indicated. Supervision follows action; it never replaces it.",
  "RED FLAG — anything suggesting the reason is at home: domestic violence, a parent's illness or addiction leaving the child as carer, neglect, or a child kept home to meet an adult's need. Children First: a mandated person reports to Tusla as soon as practicable; telling the DLP does not discharge that duty.",
  "RED FLAG — total non-attendance with near-total withdrawal from peers, activities and leaving the house. Moderate to severe mental health need — GP and CAMHS, not a school-only plan.",
  "RED FLAG — sudden onset in a previously settled child. Ask about bullying, a specific incident, a loss or a safeguarding concern before treating it as generalised anxiety.",
  "BOUNDARY — you do not diagnose an anxiety disorder or depression and do not advise on medication (PSI 2.2.2). You describe, formulate, recommend and refer.",
  "WATCH — a reduced timetable that has quietly become permanent, or a child 'on home tuition' with no return plan. Name it, gently, as a risk to the child's education.",
 ],
 "child_voice": [
  "'MY VIEWS ABOUT SCHOOL' (NEPS, 2023, Appendix B of the good practice guide) — Irish, free, designed for this. Good because staff recognise it and it maps positives as well as worries.",
  "SRAS-R child version (Kearney, 2002) — good because it gives the child's own view of the function, which frequently differs from the parent's.",
  "SCHOOL-DAY MAPPING — the child colours a timeline of the day green/amber/red. Good because it locates the difficulty in specific places and times and produces the first steps of the return.",
  "SCALING — 'where are you now, 0–10, on managing school? what would one point higher look like?' Good because it produces a small next step in the child's own words.",
  "DRAWING THE IDEAL SCHOOL (Williams & Hanke, 2007, adapting Moran's Drawing the Ideal Self — check reference) — good because it lets a child who cannot say what is wrong show what a tolerable school would look like.",
  "Always see the child without the parent for part of the session where age allows. Bullying, home concerns and low mood are rarely raised with a parent present.",
 ],
 "questions": [
  "Q: 'Should I just make him go?' — A: 'Not by force — that tends to make the fear bigger. But keeping him home isn't the answer either. What works is a plan with small steps he can manage, and all of us sticking to it on the hard mornings.'",
  "Q: 'Is she going to be reported to Tusla?' — A: 'Schools must report any child who misses 20 or more days in a school year — it's the law for every child, not a judgement on you. The Education Welfare Officer can also be a real support to the plan.'",
  "Q: 'Can she go on a reduced timetable?' — A: 'As a short, planned step in building back up, sometimes yes — with a review date. As the long-term answer, no, because it can keep the avoidance going. The Department has rules about how reduced days are recorded.'",
  "Q: 'Should we get home tuition?' — A: 'I'd be cautious. It can remove the very practice she needs to get back. If she's too unwell to attend, that's a conversation with the GP and CAMHS, not a school decision.'",
  "Q: 'Is it anxiety or is he just manipulating us?' — A: 'The two aren't opposites. Staying home can become rewarding even when the anxiety is real. That's why we look at what the absence is doing for him — and plan for both.'",
  "Q: 'Does she need a diagnosis?' — A: 'Not to get help in school. EBSA isn't a diagnosis. If there's significant anxiety or low mood underneath, the GP can refer on, and that runs alongside the school plan.'",
  "Q: 'She was fine all through primary — why now?' — A: 'The move to post-primary is one of the most common starting points. More teachers, more rooms, more people, more evaluation. It tells us where to look rather than meaning something is wrong with her.'",
  "Q: 'What does the school need to change?' — A: 'That depends on what we find. Often it's something specific — a class, a corridor, a person, the canteen. The plan works on the school side as well as on her.'",
 ],
 "supervision": [
  "Bring the function hypothesis for each EBSA case and ask your supervisor to challenge it — especially where parent and pupil accounts diverge.",
  "Ask how your service works with TESS locally: when EWOs are involved, what they expect from the EP report, and how joint meetings run.",
  "Ask what your supervisor says to a parent requesting home tuition or an open-ended reduced day, word for word.",
  "Raise any case where you are unsure whether the reason for absence is at home. That is a child protection conversation — act first, then bring it.",
  "Bring a graduated return plan that stalled and work through why: steps too big, school side unchanged, function misread, or an unrecognised mental health need.",
  "Ask about local CAMHS thresholds for anxiety-based non-attendance and what referrals actually get accepted.",
 ],
 "reflection": [
  "ON FUNCTION — did I formulate what the absence does for this child, or did I write 'anxiety' and stop?",
  "ON BLAME — how did the parents leave the meeting? Did anything I said sound like it was their fault? Did anything I said to the school sound like it was the child's?",
  "ON THE SCHOOL SIDE — did my recommendations change anything about the school, or only about the child?",
  "ON THE STEPS — were the steps the pupil's, or mine? Did I check she believed she could manage step one?",
  "ON TUSLA — did I explain the 20-day reporting duty in a way that reduced fear rather than raised it?",
  "ON RISK — did I ask directly about mood, self-harm and bullying, and about home, with the child alone?",
  "WHAT GOOD LOOKS LIKE: 'The school wanted a reduced timetable. I asked what the pupil found hardest; it was the first ten minutes in the busy corridor. We agreed she'd arrive five minutes early and go straight to the library with the key adult. She was in full-time within six weeks.'",
  "WHAT POOR LOOKS LIKE: 'Anxious about school; recommend reduced timetable and CAMHS referral.' — no function, no school-side change, no steps, and a waiting list the child will spend at home.",
 ],
 "citations": [
  "Berg, I., Nichols, K., & Pritchard, C. (1969). School phobia — its classification and relationship to dependency. Journal of Child Psychology and Psychiatry, 10(2), 123–141.",
  "Kearney, C. A., & Silverman, W. K. (1990). A preliminary analysis of a functional model of assessment and treatment for school refusal behavior. Behavior Modification, 14(3), 340–366.",
  "Kearney, C. A. (2002). Identifying the function of school refusal behavior: A revision of the School Refusal Assessment Scale. Journal of Psychopathology and Behavioral Assessment, 24(4), 235–245.",
  "Kearney, C. A. (2008). School absenteeism and school refusal behavior in youth: A contemporary review. Clinical Psychology Review, 28(3), 451–471.",
  "Egger, H. L., Costello, E. J., & Angold, A. (2003). School refusal and psychiatric disorders: A community study. Journal of the American Academy of Child and Adolescent Psychiatry, 42(7), 797–807.",
  "Heyne, D., Gren-Landell, M., Melvin, G., & Gentle-Genitty, C. (2019). Differentiation between school attendance problems: Why and how? Cognitive and Behavioral Practice, 26(1), 8–34.",
  "Elliott, J. G., & Place, M. (2019). Practitioner review: School refusal: Developments in conceptualisation and treatment since 2000. Journal of Child Psychology and Psychiatry, 60(1), 4–15.",
  "West Sussex County Council Educational Psychology Service. (2018). Emotionally based school avoidance: Good practice guidance for schools and support agencies. West Sussex County Council.",
  "National Educational Psychological Service. (2023). Managing reluctant attendance and school avoidance behaviour: A good practice guide for primary schools [and post-primary version]. Department of Education. (Guide dated 2023; check current version on gov.ie.)",
  "Heyne, D., & King, N. J. (2004). Treatment of school refusal. In P. M. Barrett & T. H. Ollendick (Eds.), Handbook of interventions that work with children and adolescents: Prevention and treatment. Wiley. (Check page range.)",
  "Education (Welfare) Act 2000, No. 22 of 2000 (Ireland). s.21 — school attendance reporting. (Amendment announced 2025 — check current status.)",
 ],

 "pathway": {
  "age": "Any age, with peaks at school entry, around 10–11 and at the move to post-primary (Kearney, 2008 — check). Transitions raise demand at the same moment familiar support drops away, and absence after a holiday or illness often becomes the start of a pattern.",
  "who_diagnoses": "Ireland: nobody — EBSA is not a diagnosis. It is identified by the school through attendance data and described by NEPS or another psychologist. An underlying anxiety disorder or depression is diagnosed by CAMHS, Primary Care Psychology or a private clinician.",
  "who_wrote_report": "NEPS or a private educational psychologist (formulation and return plan). Tusla EWO (attendance and welfare report). CAMHS or Primary Care (if there is an anxiety or mood diagnosis). A GP letter confirming illness does not explain the pattern.",
  "refer_to": "Tusla Education Support Service (Educational Welfare Service) once the pupil is absent more than 20 days and school-level supports have been tried (NEPS, 2023) — the school must notify the EWO at 20 or more days regardless (Education (Welfare) Act 2000, s.21(4)). GP → CAMHS or Primary Care Psychology for moderate to severe anxiety or low mood. Jigsaw (12–25) for milder adolescent need. Meitheal for multi-agency need.",
  "sooner": "'The earlier the better is true for this, and you're here now — that's what matters. Most families try everything they can think of before asking for help, and it isn't obvious at the start that a few days off is becoming a pattern.'",
 },
 "differential": [
  "TRUANCY — parent unaware; child often out with peers; less anxiety, more conduct concern. Different response (Heyne et al., 2019).",
  "SCHOOL WITHDRAWAL — the parent keeps the child home (e.g. for company, childcare, the parent's own anxiety). Assess the family's role gently and consider welfare concerns.",
  "SCHOOL EXCLUSION — the school keeps the child out, including informal exclusion through an open-ended reduced timetable or 'come in when you're ready'.",
  "CHRONIC ILLNESS — genuine medical absence. Needs a health plan, not an exposure plan; the two can co-exist.",
  "YOUNG CARER / HOME CONCERN — the child is needed at home or afraid to leave a parent. Check for safeguarding concerns.",
 ],
 "next": [
  "Get the attendance data — days out of days, pattern by weekday, lesson and time — before the first meeting.",
  "Meet parents, pupil and key school contact SEPARATELY first; then agree the plan together.",
  "Formulate the function(s) and write a graduated return plan with dates and a review date in the Student Support File.",
  "Screen for anxiety, mood and risk; refer via GP to CAMHS or Primary Care where the need is moderate to severe.",
  "Confirm the school has notified TESS where absence has reached 20 days or more in the school year, and that parents know.",
 ],
 "presentations": [
  "Truancy distinguished from EBSA",
  "Parentally condoned absence",
  "Absence due to chronic illness",
  "Late arrival and partial attendance",
  "Return-to-school planning after extended absence",
  "Somatic complaints presenting at school (tummy aches, headaches)",
  "Anticipatory anxiety about transitions",
 ],

 "bands": {
  "Early Years": {
   "applies": "RARELY — attendance is not compulsory before 6 (Education (Welfare) Act 2000); reluctance at school entry is usually separation distress.",
   "prevalence": "Transient reluctance at school entry is common; persistent EBSA at this age — rate not stated here, check.",
   "see": "Crying and clinging at drop-off in junior infants, tummy aches on school mornings, a child who settles within minutes of the parent leaving. Usually developmental and responds to a quick, warm, consistent handover. Persistence beyond the first term, or distress that does not settle, warrants a closer look at separation anxiety and family stress.",
   "tools": ["SDQ (2–4 version)", "Conners EC"],
  },
  "School Age": {
   "applies": "YES — identification rises through primary, often around school entry and 10–11.",
   "prevalence": "School refusal commonly cited around 1–2% of school-age children (Heyne & King, 2004) — check before quoting.",
   "see": "Somatic complaints that fade at home, distress at drop-off, difficulty after weekends and holidays, requests to ring home, specific-subject avoidance where a learning need is unrecognised. Separation and fear of something happening to a parent are common themes. Parents are usually still getting the child in on some days — this is the window where early action works best.",
   "tools": ["SDQ", "RCADS", "BASC-3", "Piers-Harris 3", "WIAT-III UK",
             "SRAS-R (School Refusal Assessment Scale – Revised) — AGE school age, child and parent forms (check manual) · MEASURES: relative strength of the four Kearney functions maintaining non-attendance · CANNOT TELL YOU: whether an anxiety disorder is present, or anything about risk · TIME: 10–15 min per informant"],
  },
  "Adolescent": {
   "applies": "YES — the peak in most accounts, especially at the move to post-primary.",
   "prevalence": "Peak prevalence band in most studies — rate not stated here, check. Tusla reports higher overall absence in post-primary than primary.",
   "see": "Missing particular classes, arriving late, leaving at lunch, days out that become weeks. Social-evaluative fear (oral work, PE, the canteen), academic pressure and low mood dominate; sleep reversal and heavy screen use are common and bidirectional. Self-report becomes essential and risk must be asked about directly.",
   "tools": ["RCADS self-report", "MFQ (Mood and Feelings Questionnaire)", "Beck Youth Inventories-2", "BASC-3 SRP",
             "SRAS-R (School Refusal Assessment Scale – Revised) — AGE adolescent, child and parent forms (check manual) · MEASURES: relative strength of the four Kearney functions · CANNOT TELL YOU: diagnosis or risk — ask directly · TIME: 10–15 min per informant"],
  },
  "Young Adult": {
   "applies": "RARELY — outside compulsory attendance; seen as non-attendance at post-primary senior cycle, FET or third level.",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Non-attendance at senior cycle or college, often with social anxiety or depression underneath and a history of school avoidance. The pathway is adult or youth mental health and college disability or access services rather than a school return plan.",
   "tools": ["Adult self-report measures via the service"],
  },
  "Special Setting": {
   "applies": "YES — pupils with SEN are at elevated risk (NEPS, 2023).",
   "prevalence": "Elevated compared with mainstream — rate not stated here, check.",
   "see": "Refusal at the transport stage, distress in transition between spaces, behaviour of concern on arrival. Sensory load, unpredictability, communication difficulty and changes of staff are frequent drivers. Communication-accessible methods for the pupil's view and an ABC record across a week are more informative than questionnaires.",
   "tools": ["Functional behaviour assessment (ABC)", "SDQ", "Vineland-3 / ABAS-3"],
  },
 },
},

# =====================================================================
# 2. SEPARATION ANXIETY DISORDER
# =====================================================================
{
 "name": "Separation Anxiety Disorder",
 "code": "DSM-5-TR Separation Anxiety Disorder (F93.0) · ICD-11 6B05",
 "neps": "3. EMOTIONAL (3.2 Anxiety) — and 3.6 School attendance where it drives non-attendance",
 "coru": _CORU,
 "psi": _PSI,
 "law": "Children First Act 2015 · Education (Welfare) Act 2000 · EPSEN Act 2004 · Equal Status Acts 2000–2018 · GDPR",

 "what_it_is": [
  "An anxiety disorder defined by DEVELOPMENTALLY INAPPROPRIATE and EXCESSIVE fear or anxiety about separation from attachment figures (American Psychiatric Association, 2022, DSM-5-TR).",
  "Criteria require at least three of eight features — e.g. excessive distress when separation occurs or is anticipated; persistent worry that harm will befall an attachment figure or that an event (getting lost, kidnapped) will cause separation; reluctance or refusal to go to school or elsewhere; reluctance to sleep away from the attachment figure; nightmares of separation; physical complaints when separation is anticipated (APA, 2022). Check the full list before relying on it.",
  "DURATION: at least 4 weeks in children and adolescents; typically 6 months or more in adults (APA, 2022). Significant distress or impairment, and not better explained by another condition (e.g. autism-related resistance to change).",
  "Since DSM-5 (2013) it sits in the anxiety disorders chapter and can be diagnosed in adults; the earlier requirement of onset before 18 was removed.",
  "THE KEY WORD IS 'DEVELOPMENTALLY'. Separation distress is normal from around 8 months to preschool (Bowlby, 1969/1982). The disorder is the same fear, out of proportion for age and persisting.",
  "MAINTAINED BY ACCOMMODATION. Well-meant parental accommodation — staying with the child, avoiding separations, answering calls from school — reduces distress now and maintains the fear (Lebowitz et al., 2013). This is the lever parent-led treatments pull.",
 ],
 "what_it_is_not": [
  "NOT an attachment disorder. Children with separation anxiety usually have strong, selective attachments; the fear is about losing them. Reactive attachment disorder is a different, much rarer condition linked to severe early neglect.",
  "NOT caused by 'overprotective parenting' in any simple sense. Temperament, genetics, life events and parental anxiety interact; accommodation maintains the fear but rarely created it. Say so plainly to parents.",
  "NOT normal clinginess. Most young children protest at separation and settle quickly. The disorder is persistent, excessive for age and impairing.",
  "NOT only a young-child problem. It can persist into or begin in adolescence and adulthood (APA, 2022), and in adolescence is often hidden behind 'I feel sick' or refusal to go on school trips.",
  "NOT treated by keeping the child close until they grow out of it. Avoidance maintains anxiety; CBT with graded exposure and parent involvement is the best-supported treatment for childhood anxiety (James et al., 2020).",
  "NOT the same as EBSA, though often its driver in younger children. A child can have separation anxiety and attend school, and many children with EBSA do not have separation anxiety.",
 ],
 "prevalence": [
  "OVERALL (CHILDREN): 6–12-month prevalence around 4% (APA, 2022, DSM-5-TR). Commonly described as the most prevalent anxiety disorder in children under 12 (APA, 2022) — check the current text.",
  "ADOLESCENTS: 12-month prevalence around 1.6% in US data (APA, 2022).",
  "ADULTS: 12-month prevalence around 0.9–1.9% (APA, 2022).",
  "IRELAND: no national prevalence figure identified — rate not stated here, check before quoting.",
  "EARLY YEARS 0–5: diagnosis is difficult because separation distress is developmentally expected; identification rises at school entry.",
  "SEX RATIO: community samples suggest it is somewhat more common in girls; clinic samples are more even (APA, 2022) — check before quoting.",
 ],
 "cooccurring": [
  {"name": "EBSA / SCHOOL NON-ATTENDANCE", "rate": "strongly associated (Egger et al., 2003) — rate not stated here, check",
   "presents": "distress at drop-off, calls home, somatic complaints on school mornings. Function usually proximity to the parent."},
  {"name": "OTHER ANXIETY DISORDERS (GAD, SPECIFIC PHOBIA)", "rate": "high — anxiety disorders commonly co-occur; rate not stated here, check",
   "presents": "worry that spreads beyond separation — health, safety, the future. Assess the breadth, not just the separation theme."},
  {"name": "LATER PANIC DISORDER / AGORAPHOBIA", "rate": "elevated risk reported in some studies — check before quoting",
   "presents": "in adolescence, fear of being away from a 'safe' person or place. Watch for panic attacks."},
  {"name": "DEPRESSION / LOW MOOD", "rate": "elevated, particularly in older children — rate not stated here, check",
   "presents": "withdrawal, tearfulness, loss of interest. Screen for mood and risk alongside anxiety."},
  {"name": "AUTISM", "rate": "anxiety is very common in autism (van Steensel et al., 2011) — rate not stated here, check",
   "presents": "distress at separation that is really about unpredictability and change. Ask whether the fear is about the PERSON or the ROUTINE."},
  {"name": "SLEEP DIFFICULTY", "rate": "very common — rate not stated here, check",
   "presents": "refusal to sleep alone, night waking, the child in the parent's bed. Ask; it drives daytime presentation."},
 ],
 "recommendations": [
  "BRIEF, WARM, PREDICTABLE HANDOVER. Same adult, same place, same short goodbye every morning. Long goodbyes and slipping away unannounced both increase distress.",
  "A NAMED KEY ADULT at arrival who takes over from the parent and has a first job ready for the child.",
  "REDUCE ACCOMMODATION, GRADUALLY AND WITH THE FAMILY. Agree which accommodations to reduce first (e.g. the parent staying in the classroom, phone calls home). Parent-led approaches such as SPACE have trial evidence comparable to child CBT (Lebowitz et al., 2020).",
  "GRADED EXPOSURE through small, planned separations the child rates as manageable, practised at home and in school. Praise the brave behaviour, not the absence of worry.",
  "NO CALLS HOME AS STANDARD during the day, unless agreed as a step in the plan. A pre-agreed 'check-in' time can replace ad hoc calls.",
  "TRANSITIONAL OBJECTS for younger children (a photo, a note in the lunchbox) as a planned, time-limited support.",
  "PARENT GUIDANCE: point to parent-led CBT materials (Creswell & Willetts, 2019) and, where available, parent-led CBT via Primary Care Psychology.",
  "CONTINUUM LEVEL: Classroom Support for mild, transient distress; School Support where it persists or affects attendance; School Support Plus with CAMHS or Primary Care involvement.",
  "REFER: GP → Primary Care Psychology for mild to moderate; CAMHS for severe or complex presentations or where mood or risk is a concern.",
  "DO NOT recommend that the parent stay in class long term, that the child be collected when upset as the default response, or a reduced timetable as the plan. Each reinforces the fear.",
 ],
 "explain_parent": [
  "'Separation anxiety is a real fear, not attention-seeking. Her brain is treating being away from you as dangerous — even though part of her knows it isn't.'",
  "'When she's upset and you stay, the fear drops straight away. That feels like the right thing — and it teaches her brain that you staying was what kept her safe. That's why it keeps coming back.'",
  "'The kind thing is a warm, short, confident goodbye and then leaving. The crying usually stops within minutes of you going — the school can tell you exactly how long.'",
  "'None of this means you did anything wrong. Anxious children often have loving, protective parents because the child's fear pulls protection out of everyone.'",
  "'If you've an anxious streak yourself, that's common and worth knowing — children watch how we handle worry. It's not blame, it's something you can use.'",
  "SIGNPOST: Creswell & Willetts, 'Helping Your Child with Fears and Worries' (2nd ed., 2019); the GP for Primary Care Psychology or CAMHS; NEPS guidance for parents on reluctant attendance.",
 ],
 "explain_teacher": [
  "'This is anxiety about being apart from her parent. It's not about your class, and it's not manipulation.'",
  "'The first five minutes decide the day. Have the same adult meet her, have a job ready, and help the parent leave quickly.'",
  "'Please don't ring home when she's upset unless that's in the plan. Collecting her teaches her that being upset brings Mum.'",
  "'Notice and praise the brave bit — coming in, joining the line — rather than asking if she's still sad.'",
  "'Keep a quick record: how long the distress lasts after drop-off. That number is how we'll know the plan is working.'",
 ],
 "explain_child": [
  "YOUNGER: 'You have a worry that something might happen when you're not with Mum. That worry is like a loud alarm — it's very loud, but it's a false alarm. Mum is safe, and you're safe here.'",
  "OLDER: 'Anxiety can make your brain think something bad will happen when you're apart from the people you love. The feeling is real. The danger usually isn't. Every time you manage to stay, your brain learns a bit more that you're okay.'",
  "ASK: 'What does the worry say will happen?' The content often surprises adults — an accident, illness, Mum not coming back — and it tells you what reassurance or information will help.",
  "ASK: 'What helps, even a tiny bit?' and 'When was a time you were apart and it was okay?' The exceptions become the plan.",
  "BE CAREFUL WITH PROMISES you cannot keep ('nothing bad will ever happen'). Honest, calm confidence works better.",
 ],
 "analogies": [
  "THE FALSE ALARM: 'The alarm is real and loud — it's just going off when there's no fire.' Works with younger children and with parents who worry that exposure is cruel.",
  "THE ELASTIC BAND: 'Each time you manage a bit further away, the band stretches — and it stays stretched a little more next time.' Good for younger children; gives a picture of graded exposure.",
  "THE SCAFFOLDING: 'Staying with her is like scaffolding. It's needed at first, and the building can't stand on its own until it comes down, bit by bit.' Good for parents deciding to reduce accommodation.",
  "THE WAVE: 'The worry rises like a wave, peaks, and comes down on its own if you wait. Leaving before it drops means you never find that out.' Good with older children and teachers.",
 ],
 "language": [
  "'Separation anxiety' is the accepted term and is widely understood by families. Use 'separation anxiety disorder' only where the diagnosis has been made by CAMHS, Primary Care or a clinician.",
  "Where there is no diagnosis, describe: 'significant distress at separation from her parent that is persisting and affecting attendance'.",
  "Avoid: 'clingy', 'babyish', 'manipulative', 'mammy's boy'. These are judgements and follow a child in the file.",
  "Avoid over-pathologising normal early-years separation distress. 'Settling-in difficulty' is often the more accurate term at school entry.",
 ],
 "red_flags": [
  "RED FLAG — the fear is about a real threat: domestic violence, a parent's serious illness, a parent threatening to leave or self-harm. The child may be right to worry. Children First applies: report to Tusla as soon as practicable; telling the DLP does not discharge a mandated person's duty.",
  "RED FLAG — a young person expressing hopelessness, self-harm or suicidal thoughts. Same-day risk route; supervision follows action.",
  "RED FLAG — sudden onset after a loss, a hospitalisation, a family break-up or a frightening event. Consider grief or trauma rather than a primary anxiety disorder, and refer accordingly.",
  "BOUNDARY — you do not diagnose separation anxiety disorder and do not advise on medication (PSI 2.2.2). Describe, formulate, recommend, refer.",
  "WATCH — the parent's own anxiety. It is common and relevant, but it is not yours to assess or treat. Signpost to the GP gently if the parent raises it.",
 ],
 "child_voice": [
  "DRAWING 'THE WORRY' — the child draws the worry and gives it a name. Good because externalising makes it talkable and separates the child from the problem.",
  "WORRY THERMOMETER or scaling (0–10) for each step of the morning. Good because it produces the hierarchy for graded exposure in the child's own ratings.",
  "'MY VIEWS ABOUT SCHOOL' (NEPS, 2023) — good because it surfaces what is and isn't hard about school itself, which separates separation worry from school-based triggers.",
  "RCADS separation anxiety subscale, child version (Chorpita et al., 2000) — good because the child's own report can differ sharply from the parent's, and the difference is informative.",
  "SENTENCE COMPLETION ('When Mum leaves I…', 'The worst thing that could happen is…') — good for children who find open questions hard.",
 ],
 "questions": [
  "Q: 'Should I stay with her until she settles?' — A: 'Short-term it helps; long-term it keeps the fear going, because she learns that you staying is what made it okay. A warm, quick goodbye with a trusted adult taking over is what helps her learn she can cope.'",
  "Q: 'Is it my fault?' — A: 'No. Anxiety comes from a mix of temperament, genes and what happens in life. Parents' responses can keep it going, which is good news — it means there's something you can change.'",
  "Q: 'She screams when I leave — how can that be good for her?' — A: 'The distress is real, and it usually drops quickly once you've gone. Ask the school to time it. Watching that number fall is how you'll both know it's working.'",
  "Q: 'Will she grow out of it?' — A: 'Many children do become less anxious with age, but untreated separation anxiety can persist or change into other worries. Acting now gives her a skill she'll use again.'",
  "Q: 'Does she need a referral?' — A: 'If it's mild and responding to the school plan, maybe not. If it's severe, widespread, or not shifting after a few weeks of consistent effort, the GP can refer to Primary Care Psychology or CAMHS.'",
  "Q: 'Should the school ring me if she's upset?' — A: 'Let's agree now exactly when they will — for illness or injury, yes; for upset, only if it goes beyond what we've planned for. Otherwise the call teaches her that being upset brings you.'",
 ],
 "supervision": [
  "Bring a case where the child's fear might be realistic — a parent's illness, instability at home — and discuss how to hold both the anxiety formulation and the welfare question.",
  "Ask how your supervisor talks to a parent about accommodation without it landing as blame. Get the words.",
  "Discuss where the line sits between normal settling-in distress and something to refer.",
  "Ask about local availability of parent-led CBT through Primary Care Psychology, and waiting times.",
  "Bring any case where you were unsure whether the fear was about the person or the routine (possible autism).",
 ],
 "reflection": [
  "ON BLAME — when I talked about accommodation, did the parent hear 'you're doing it wrong', or 'here's something you can change'?",
  "ON DEVELOPMENT — did I check what is typical for this age before treating distress as a problem?",
  "ON REALISM — did I ask whether there was a reason for the child to fear for their parent?",
  "ON MEASUREMENT — did I set up something simple and sensitive (minutes of distress after drop-off) so everyone can see progress?",
  "ON MY OWN DISCOMFORT — did I soften the plan because watching a child cry at the door is hard?",
  "WHAT GOOD LOOKS LIKE: 'I asked the teacher to time the crying after Mum left. It was four minutes. When Mum heard that, she agreed to a short goodbye at the gate. Within two weeks it was under a minute.'",
  "WHAT POOR LOOKS LIKE: 'Mum to stay in class until child settles; review in a month.' — accommodation built into the plan, no steps out of it.",
 ],
 "citations": [
  "American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.). — Separation Anxiety Disorder.",
  "World Health Organization. (2019/2022). ICD-11 for mortality and morbidity statistics — 6B05 Separation anxiety disorder.",
  "Bowlby, J. (1982). Attachment and loss: Vol. 1. Attachment (2nd ed.). Basic Books. (Original work published 1969)",
  "Lebowitz, E. R., Woolston, J., Bar-Haim, Y., Calvocoressi, L., Dauser, C., Warnick, E., … Leckman, J. F. (2013). Family accommodation in pediatric anxiety disorders. (Check full author list.) Depression and Anxiety, 30(1), 47–54.",
  "Lebowitz, E. R., Marin, C., Martino, A., Shimshoni, Y., & Silverman, W. K. (2020). Parent-based treatment as efficacious as cognitive-behavioral therapy for childhood anxiety: A randomized noninferiority study of Supportive Parenting for Anxious Childhood Emotions. Journal of the American Academy of Child and Adolescent Psychiatry, 59(3), 362–372.",
  "James, A. C., Reardon, T., Soler, A., James, G., & Creswell, C. (2020). Cognitive behavioural therapy for anxiety disorders in children and adolescents. Cochrane Database of Systematic Reviews, 11, CD013162.",
  "Creswell, C., & Willetts, L. (2019). Helping your child with fears and worries (2nd ed.). Robinson.",
  "Chorpita, B. F., Yim, L., Moffitt, C., Umemoto, L. A., & Francis, S. E. (2000). Assessment of symptoms of DSM-IV anxiety and depression in children: A Revised Child Anxiety and Depression Scale. Behaviour Research and Therapy, 38(8), 835–855.",
  "Egger, H. L., Costello, E. J., & Angold, A. (2003). School refusal and psychiatric disorders: A community study. Journal of the American Academy of Child and Adolescent Psychiatry, 42(7), 797–807.",
 ],

 "pathway": {
  "age": "Most often identified at school entry and in the early primary years, when daily separation becomes compulsory and prolonged. Also after life events — a move, a bereavement, a parent's illness — at any age. Adolescent and adult presentations are recognised (APA, 2022).",
  "who_diagnoses": "Ireland: Primary Care Psychology (mild to moderate) or CAMHS (severe, complex, or with mood or risk concerns), usually via GP referral. Private clinical psychologists and psychiatrists also diagnose. The EP does not diagnose.",
  "who_wrote_report": "CAMHS psychiatrist or psychologist. Primary Care psychologist. Private clinical psychologist. An SDQ or RCADS completed in school is a screen, not a diagnosis.",
  "refer_to": "GP → Primary Care Psychology for mild to moderate; CAMHS for severe or complex, or where mood or risk is present. Tusla if the fear points to a welfare concern. NEPS consultation for the school plan.",
  "sooner": "'It's genuinely hard to tell normal settling-in from something more at the start — most children do settle. That it's lasted this long is what tells us it needs a plan, and now there is one.'",
 },
 "differential": [
  "NORMAL SEPARATION DISTRESS — developmentally expected, brief, settles quickly. Check age and duration before concluding anything.",
  "GENERALISED ANXIETY — worry spans many topics, not just separation. The separation theme may be one of several.",
  "AUTISM — resistance to change and need for a predictable person or routine rather than fear of harm to the parent.",
  "GRIEF OR TRAUMA — onset after a loss or frightening event; the fear may be realistic or trauma-linked.",
  "REALISTIC FEAR — domestic violence, parental illness or instability. A welfare question before an anxiety question.",
 ],
 "next": [
  "Establish duration, age-appropriateness and what the worry says will happen — with the child alone where possible.",
  "Ask about recent life events and home circumstances; follow Children First if anything points to a welfare concern.",
  "Agree a brief, consistent handover and a simple measure (minutes of distress) with parent and school.",
  "Screen with SDQ and RCADS parent/child; refer via GP where severe, widespread or not responding.",
 ],
 "presentations": [
  "School anxiety presentations (not a standalone diagnosis)",
  "Anticipatory anxiety about transitions",
  "Somatic complaints presenting at school (tummy aches, headaches)",
  "Emotionally Based School Avoidance (school refusal)",
  "Late arrival and partial attendance",
 ],

 "bands": {
  "Early Years": {
   "applies": "YES — but separation distress is developmentally normal here; the question is degree and persistence.",
   "prevalence": "Diagnosis is less common because distress is expected — rate not stated here, check.",
   "see": "Crying and clinging at preschool or junior infants drop-off, refusing to let go, distress lasting long after the parent has left, sleep refusal without the parent. Most children settle within minutes; the concern is the child who does not, or whose distress is escalating after the first term. Parent and staff report only — no self-report.",
   "tools": ["SDQ (2–4 version)", "Conners EC",
             "Preschool Anxiety Scale (Spence et al., 2001) — AGE preschool, parent report (check manual) · MEASURES: anxiety symptoms including a separation subscale · CANNOT TELL YOU: whether distress is outside the developmental norm without context · TIME: 10 min"],
  },
  "School Age": {
   "applies": "YES — peak identification; commonly described as the most prevalent anxiety disorder under 12 (APA, 2022).",
   "prevalence": "Around 4% of children, 6–12-month prevalence (APA, 2022) — check the current text.",
   "see": "Somatic complaints on school mornings, calls home, worry about a parent's safety, refusal of sleepovers and trips, and difficulty after weekends and holidays. Often the driver of EBSA in primary. Self-report becomes possible from around 8 with the RCADS; compare child and parent reports.",
   "tools": ["SDQ", "RCADS", "BASC-3",
             "SCAS (Spence Children's Anxiety Scale) — AGE roughly 8–15 child, parent version available (check) · MEASURES: anxiety symptoms by DSM-type subscale including separation anxiety · CANNOT TELL YOU: diagnosis or risk · TIME: 10 min"],
  },
  "Adolescent": {
   "applies": "YES — less common than in childhood; ask why now.",
   "prevalence": "Around 1.6% 12-month prevalence in US adolescents (APA, 2022) — check.",
   "see": "Hidden behind 'feeling sick', refusing trips or overnight activities, staying close to a parent who is ill or unwell, reluctance to leave home. More often linked to a specific stressor or to panic, depression or a home concern than in younger children. Self-report and a direct risk question are essential.",
   "tools": ["RCADS self-report", "MFQ (Mood and Feelings Questionnaire)", "Beck Youth Inventories-2"],
  },
  "Young Adult": {
   "applies": "RARELY — recognised in adults since DSM-5, but seen here mainly as difficulty leaving home for college or work.",
   "prevalence": "Adult 12-month prevalence around 0.9–1.9% (APA, 2022) — check.",
   "see": "Difficulty moving away for college, returning home at weekends by necessity, calling a parent many times a day, anxiety about a partner's or parent's safety. Adult mental health or college counselling territory — know the boundary and refer.",
   "tools": ["Adult self-report measures via the service"],
  },
  "Special Setting": {
   "applies": "YES — separation distress is common and often intertwined with communication and predictability needs.",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Distress at the transport handover or arrival, behaviour of concern when a key adult is absent, difficulty with staff changes. Distinguish fear for the parent from need for a predictable person or routine. Visual schedules showing when the parent returns, consistent key staff and an ABC record are usually more useful than questionnaires.",
   "tools": ["Functional behaviour assessment (ABC)", "SDQ"],
  },
 },
},

# =====================================================================
# 3. SOCIAL ANXIETY DISORDER
# =====================================================================
{
 "name": "Social Anxiety Disorder (social phobia)",
 "code": "DSM-5-TR Social Anxiety Disorder (F40.10) · ICD-11 6B04",
 "neps": "3. EMOTIONAL (3.2 Anxiety) — and 4. SOCIAL (4.1 Friendships and social skills) · 3.6 School attendance where it drives non-attendance",
 "coru": _CORU,
 "psi": _PSI,
 "law": "Children First Act 2015 · EPSEN Act 2004 · Equal Status Acts 2000–2018 · GDPR",

 "what_it_is": [
  "An anxiety disorder defined by marked fear or anxiety about one or more social situations in which the person may be scrutinised by others — conversations, meeting new people, being observed eating or drinking, performing or speaking in front of others (American Psychiatric Association, 2022, DSM-5-TR).",
  "The core fear is of NEGATIVE EVALUATION — acting in a way, or showing anxiety symptoms (blushing, shaking), that will be humiliating or lead to rejection. Situations are avoided or endured with intense fear, out of proportion to the actual threat, typically for 6 months or more (APA, 2022).",
  "IN CHILDREN, the anxiety must occur in PEER settings, not only with adults, and may be expressed as crying, tantrums, freezing, clinging, shrinking or failing to speak (APA, 2022). A 'performance only' specifier applies where the fear is restricted to speaking or performing in public.",
  "THE BEST-SUPPORTED MODEL is cognitive: Clark & Wells (1995) describe self-focused attention, a distorted internal image of how one appears, SAFETY BEHAVIOURS (avoiding eye contact, rehearsing sentences, hiding the face) and anticipatory and post-event rumination. Safety behaviours prevent disconfirmation and make the person look more awkward. Leigh & Clark (2018) apply the model to adolescents.",
  "TEMPERAMENT MATTERS. Behavioural inhibition — a tendency to withdraw from the unfamiliar, identifiable in toddlers (Kagan et al., 1984) — substantially raises risk (Clauss & Blackford, 2012 — check the effect size before quoting).",
  "Onset is typically in late childhood to adolescence. DSM-5 reported a median age of onset in the US of 13, with most onsets between 8 and 15 (APA, 2013; check DSM-5-TR text).",
 ],
 "what_it_is_not": [
  "NOT shyness. Shyness is a common, normal temperament; social anxiety disorder is marked, persistent and impairing. Many shy children never develop it.",
  "NOT autism. Autistic young people may avoid social situations because of social communication difference, sensory load or the effort of masking; in social anxiety the social understanding is typically intact and the driver is fear of evaluation. They can co-occur, and both must be assessed separately.",
  "NOT a lack of interest in people. Socially anxious young people usually want friendships and feel the loss keenly. 'He prefers his own company' can be a misreading.",
  "NOT fixed by 'just throwing them in'. Unplanned exposure with safety behaviours intact rarely helps; planned, graded exposure with safety behaviours dropped is what the evidence supports (Clark & Wells, 1995; NICE, 2013).",
  "NOT a phase that will pass unaided. Untreated, it tends to be chronic and is associated with later depression and substance use (NICE, 2013) — check the specific figures before quoting.",
  "NOT selective mutism, although they are closely related. Selective mutism is its own DSM-5-TR anxiety disorder, in which the child consistently does not speak in specific settings; social anxiety is commonly present alongside it.",
 ],
 "prevalence": [
  "OVERALL: 12-month prevalence in the US around 7%, with much lower estimates in many other countries using the same instruments (APA, 2013/2022) — check the DSM-5-TR text before quoting any European or international figure.",
  "IRELAND: no national figure identified — rate not stated here, check before quoting.",
  "EARLY YEARS 0–5: rarely diagnosed. Behavioural inhibition and selective mutism are the related presentations at this age.",
  "SCHOOL AGE 6–12: emerging, particularly in the later primary years.",
  "ADOLESCENT 13–16: the main onset window (APA, 2013 — median onset 13 in US data).",
  "SEX RATIO: more common in females in community samples, with the difference more pronounced in adolescents (APA, 2022) — check the ratio before quoting.",
 ],
 "cooccurring": [
  {"name": "OTHER ANXIETY DISORDERS", "rate": "high — rate not stated here, check",
   "presents": "generalised worry, panic attacks in social situations, or specific phobias alongside. Map the full picture before recommending."},
  {"name": "DEPRESSION", "rate": "elevated, often following social anxiety (NICE, 2013) — rate not stated here, check",
   "presents": "withdrawal that has become hopelessness, loss of interest beyond social situations. Screen for mood and risk."},
  {"name": "EBSA / SCHOOL NON-ATTENDANCE", "rate": "common in adolescents — rate not stated here, check",
   "presents": "avoiding specific classes, oral work, PE, the canteen or the bus. Kearney function 2 — escape from evaluation."},
  {"name": "SELECTIVE MUTISM", "rate": "strongly associated — rate not stated here, check",
   "presents": "consistent absence of speech in school while speaking freely at home. Often an early form of the same fear."},
  {"name": "AUTISM", "rate": "social anxiety is elevated in autism — rate not stated here, check",
   "presents": "social avoidance with social communication difference. Assess both; do not let one explain the other."},
  {"name": "SUBSTANCE USE (ADOLESCENTS)", "rate": "elevated risk reported — rate not stated here, check",
   "presents": "alcohol or cannabis used to cope with social situations. Ask directly and non-judgementally."},
  {"name": "DLD / LANGUAGE DIFFICULTY", "rate": "elevated — rate not stated here, check",
   "presents": "avoidance of speaking because expressive language is effortful. Assess language before attributing it to anxiety."},
 ],
 "recommendations": [
  "PLANNED, GRADED EXPOSURE in school, agreed with the young person: e.g. answering a closed question to the teacher alone → reading one line in a small group → contributing once in class. Never a surprise.",
  "REDUCE SPOTLIGHTING. No cold-calling, no reading aloud without warning, no being singled out for praise in front of peers. Offer advance notice of questions.",
  "STRUCTURED SOCIAL OPPORTUNITIES rather than 'encourage him to join in': a lunchtime club with a shared task, a job with a peer, a buddy for group work.",
  "NOTICE AND DROP SAFETY BEHAVIOURS in the plan (hood up, head down, always sitting at the back, having a friend speak for them) — gradually, with agreement, because they maintain the fear (Clark & Wells, 1995).",
  "ORAL ASSESSMENT: agreed alternatives as a step, not a permanent exemption — e.g. presenting to the teacher alone before presenting to a small group.",
  "TEACH ABOUT ANXIETY: a psychoeducational explanation of the cycle, for the pupil and for key staff. Class or group programmes such as FRIENDS may be available through NEPS (check locally).",
  "CONTINUUM LEVEL: Classroom Support for mild difficulty; School Support where it affects participation or attendance; School Support Plus where outside services are involved.",
  "REFER: GP → Primary Care Psychology or CAMHS for assessment and CBT. NICE (2013) recommends CBT focused on social anxiety for children and young people. Jigsaw (12–25) for milder adolescent need.",
  "DO NOT recommend permanent exemption from oral work, class presentations or PE as the plan, and do not comment on medication — that is a medical decision (PSI 2.2.2).",
 ],
 "explain_parent": [
  "'Social anxiety is an intense fear of being judged or embarrassed in front of others. It's much more than shyness — it's stopping him doing things he wants to do.'",
  "'The things he does to feel safer — keeping his head down, not answering, letting you order for him — make sense, but they stop him ever finding out it would have been okay.'",
  "'It's very treatable. The approach with the best evidence is a type of CBT that helps him face situations step by step and drop the safety habits.'",
  "'You can help by gently not stepping in — letting him order his own food, answer the phone, ask the question — in small doses and with praise for trying.'",
  "'It isn't something you caused. Temperament plays a big part, and many socially anxious children were cautious toddlers.'",
  "SIGNPOST: the GP for Primary Care Psychology or CAMHS; Jigsaw for 12–25s; NEPS guidance on reluctant attendance where school attendance is affected.",
 ],
 "explain_teacher": [
  "'This is fear of being judged, not rudeness or disinterest. Not answering is usually freezing, not refusing.'",
  "'Cold-calling and reading aloud without warning are the hardest things for her. Tell her the day before what you'll ask — then she'll answer.'",
  "'We want her doing more, not less, over time — in planned steps. An exemption from oral work solves this week and makes next term harder.'",
  "'Praise privately. Public praise is still attention, and attention is what she fears.'",
  "'Group her with kind, steady peers for group work and give her a defined role — timekeeper, scribe — rather than leaving her to find a way in.'",
 ],
 "explain_child": [
  "YOUNGER: 'Some people get a big worried feeling when other people might look at them or hear them. Your body might go hot or shaky. That's your brain trying to protect you — it's just being too careful.'",
  "OLDER: 'Social anxiety is when your brain is on high alert for being judged. It makes you focus on yourself — how red you are, what you'll say — which makes it harder to talk. And people notice much less than it feels like.'",
  "ASK: 'What do you think people would think if…?' and 'What's the worst bit?' The specific feared outcome is what the plan tests.",
  "ASK ABOUT SAFETY BEHAVIOURS: 'What do you do to get through it?' Most young people are relieved to be asked and can list them.",
  "Offer written or drawn response options in the session itself. A young person who cannot speak freely to you is showing you the difficulty, not being uncooperative.",
 ],
 "analogies": [
  "THE SPOTLIGHT: 'It feels like you're on stage with a spotlight on you. Everyone else is actually watching their own spotlight.' Good with adolescents; introduces the spotlight effect without dismissing the feeling.",
  "THE CRUTCHES: 'Safety behaviours are like crutches on a leg that's already healed. You'll never find out the leg works until you try without them — a bit at a time.' Good for explaining why safety behaviours are dropped.",
  "THE INTERNAL CAMERA: 'Anxiety points the camera at you instead of at the other person. You end up watching yourself and missing the conversation.' Good with older adolescents; plain-language Clark & Wells.",
  "THE SMOKE ALARM: 'Real alarm, no fire.' Works across ages for any anxiety.",
 ],
 "language": [
  "'Social anxiety' is widely understood and generally acceptable to young people. Use 'social anxiety disorder' only where diagnosed.",
  "Where undiagnosed, describe: 'marked anxiety in social and performance situations, especially speaking in class, which is limiting participation'.",
  "Avoid: 'painfully shy', 'antisocial', 'refuses to answer', 'rude', 'withdrawn by choice'. PSI 1.2.8 requires interpretations to be labelled as opinion.",
  "Mirror the young person's own words where possible — many say 'I get nervous' or 'I hate being looked at' rather than 'anxiety'.",
 ],
 "red_flags": [
  "RED FLAG — low mood, hopelessness, self-harm or suicidal thoughts. Social anxiety raises the risk of later depression. Same-day risk route; supervision follows action.",
  "RED FLAG — near-total withdrawal: not leaving the house, not attending, contact with peers only online. Moderate to severe need; GP and CAMHS.",
  "RED FLAG — alcohol or drug use to cope with social situations. Ask directly; follow service protocol and involve the GP.",
  "RED FLAG — onset after a specific humiliating incident, online abuse or image sharing. Check for bullying and for child protection concerns; Children First applies where abuse or exploitation is suspected.",
  "BOUNDARY — you do not diagnose social anxiety disorder or advise on medication (PSI 2.2.2).",
  "WATCH — social avoidance explained as anxiety when it is autism, DLD or hearing difficulty. Assess language and social communication before concluding.",
 ],
 "child_voice": [
  "WRITTEN OR TYPED RESPONSES and rating scales — good because they lower the evaluative demand of face-to-face talk and let the young person say more than they would aloud.",
  "RCADS self-report social phobia subscale (Chorpita et al., 2000) — good because the young person's own report is usually more accurate than adult report for internalising difficulty.",
  "SITUATION LADDER — the young person ranks social situations from easiest to hardest. Good because it becomes the exposure hierarchy, in their own order.",
  "'MY VIEWS ABOUT SCHOOL' (NEPS, 2023) — good because it locates which parts of school are hardest without requiring the young person to name 'anxiety'.",
  "Side-by-side activity (drawing, a task) rather than face-to-face interview — good because it reduces eye-contact demand and scrutiny.",
 ],
 "questions": [
  "Q: 'Isn't she just shy?' — A: 'Shyness is common and fine. What we're seeing is more than that — the fear is strong enough to stop her doing things she wants to do, like answering in class or seeing friends.'",
  "Q: 'Should he be excused from presentations?' — A: 'In the short term, a step-down version can help — presenting to the teacher alone, then a small group. A permanent exemption usually makes it harder, because avoidance keeps the fear going.'",
  "Q: 'Will she grow out of it?' — A: 'Some young people do, but social anxiety often continues if it isn't addressed, and it can lead to low mood. The good news is it responds well to CBT.'",
  "Q: 'Is it autism?' — A: 'They can look similar from the outside — both can mean avoiding social situations. In social anxiety the main thing is fear of being judged. It's worth assessing both properly rather than assuming.'",
  "Q: 'Should I keep inviting friends over for him?' — A: 'Small, planned, low-pressure contact with one friend and a shared activity is better than big gatherings. Ask him what feels manageable, and build from there.'",
  "Q: 'She speaks fine at home, so why not at school?' — A: 'That's typical of anxiety — it depends on who's watching. It tells us she has the skills and the fear is about evaluation, which is what we'll work on.'",
 ],
 "supervision": [
  "Bring any case where you were unsure whether social avoidance was anxiety, autism or language. Talk through what would distinguish them.",
  "Ask how your supervisor negotiates with a post-primary school over oral assessment and presentations.",
  "Discuss how to ask about substance use and self-harm with a socially anxious adolescent who struggles to speak to you.",
  "Ask about local routes: Jigsaw, Primary Care Psychology, CAMHS — what threshold, what wait.",
 ],
 "reflection": [
  "ON THE SESSION ITSELF — did I set up the assessment in a way that the anxiety I was assessing made impossible? Did I offer written or side-by-side options?",
  "ON SAFETY BEHAVIOURS — did my recommendations build new ones (permanent exemptions, a friend who always speaks for her) or plan their removal?",
  "ON DIFFERENTIAL — did I assess language and social communication, or assume anxiety because it was the referral question?",
  "ON RISK — did I ask about mood, self-harm and substance use directly?",
  "ON LANGUAGE — did I write 'refused to answer' when the young person froze?",
  "WHAT GOOD LOOKS LIKE: 'The school asked to exempt him from the Irish oral. We agreed he would record his first answers at home, then do them with the teacher alone, then with a classmate present. He sat the oral in the room.'",
  "WHAT POOR LOOKS LIKE: 'Shy pupil; recommend reduced oral demands.' — no formulation, no plan to reduce the demand-reduction, and the fear untouched.",
 ],
 "citations": [
  "American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.). — Social Anxiety Disorder.",
  "Clark, D. M., & Wells, A. (1995). A cognitive model of social phobia. In R. G. Heimberg, M. R. Liebowitz, D. A. Hope, & F. R. Schneier (Eds.), Social phobia: Diagnosis, assessment, and treatment (pp. 69–93). Guilford Press.",
  "Leigh, E., & Clark, D. M. (2018). Understanding social anxiety disorder in adolescents and improving treatment outcomes: Applying the cognitive model of Clark and Wells (1995). Clinical Child and Family Psychology Review, 21(3), 388–414.",
  "National Institute for Health and Care Excellence. (2013). Social anxiety disorder: Recognition, assessment and treatment (Clinical Guideline CG159). NICE. (Check for updates.)",
  "Kagan, J., Reznick, J. S., Clarke, C., Snidman, N., & Garcia-Coll, C. (1984). Behavioral inhibition to the unfamiliar. Child Development, 55(6), 2212–2225.",
  "Clauss, J. A., & Blackford, J. U. (2012). Behavioral inhibition and risk for developing social anxiety disorder: A meta-analytic study. Journal of the American Academy of Child and Adolescent Psychiatry, 51(10), 1066–1075.",
  "Chorpita, B. F., Yim, L., Moffitt, C., Umemoto, L. A., & Francis, S. E. (2000). Assessment of symptoms of DSM-IV anxiety and depression in children: A Revised Child Anxiety and Depression Scale. Behaviour Research and Therapy, 38(8), 835–855.",
  "James, A. C., Reardon, T., Soler, A., James, G., & Creswell, C. (2020). Cognitive behavioural therapy for anxiety disorders in children and adolescents. Cochrane Database of Systematic Reviews, 11, CD013162.",
 ],

 "pathway": {
  "age": "Usually late primary to mid-adolescence (US median onset 13; APA, 2013 — check). Social-evaluative demands rise sharply at the move to post-primary, and peer judgement becomes developmentally central, so the fear becomes both more intense and more visible.",
  "who_diagnoses": "Ireland: Primary Care Psychology (mild to moderate), CAMHS (severe, complex, or with mood or risk concerns), usually via the GP. Private clinical psychologists and psychiatrists. The EP does not diagnose.",
  "who_wrote_report": "CAMHS psychiatrist or psychologist. Primary Care psychologist. Private clinical psychologist. Jigsaw may provide a summary of brief intervention rather than a diagnosis.",
  "refer_to": "GP → Primary Care Psychology or CAMHS depending on severity. Jigsaw (12–25) for milder adolescent need. SLT where language may be contributing. CDNT where autism is a question.",
  "sooner": "'Social anxiety is one of the easiest difficulties to miss — quiet, compliant young people don't cause problems in class. That she's been noticed now is good, and it responds well to help.'",
 },
 "differential": [
  "NORMAL SHYNESS — common temperament, not impairing. Ask what she wants to do but cannot.",
  "AUTISM — social avoidance with social communication difference, sensory drivers or masking fatigue. Assess social communication separately.",
  "DLD OR HEARING DIFFICULTY — avoidance of speaking because language is effortful or conversation is hard to follow.",
  "DEPRESSION — withdrawal from loss of interest or energy rather than fear of evaluation.",
  "BULLYING OR A SPECIFIC INCIDENT — realistic fear after humiliation or online abuse. Ask directly.",
 ],
 "next": [
  "Ask the young person — in writing if needed — which situations are hardest and what they fear will happen.",
  "Screen with RCADS (social phobia subscale) and for mood and risk; assess language where speaking is the issue.",
  "Agree a graded participation plan with the pupil and key teachers, with a review date.",
  "Refer via GP to Primary Care Psychology or CAMHS where impairment is significant; Jigsaw for milder adolescent need.",
 ],
 "presentations": [
  "Performance anxiety in oral work",
  "Test and exam anxiety",
  "School anxiety presentations (not a standalone diagnosis)",
  "Peer relationship difficulties and social isolation",
  "Loneliness without observable difficulty",
  "Emotionally Based School Avoidance (school refusal)",
 ],

 "bands": {
  "Early Years": {
   "applies": "RARELY — diagnosis is uncommon; behavioural inhibition and selective mutism are the related presentations.",
   "prevalence": "Rarely diagnosed at this age — rate not stated here, check.",
   "see": "A child who is very slow to warm up, watches rather than joins, freezes when addressed by unfamiliar adults and may not speak in the setting. Much of this is temperament and settles with warmth and time. Consistent non-speaking in the setting while speaking at home points toward selective mutism and an SLT and Primary Care referral.",
   "tools": ["SDQ (2–4 version)",
             "Preschool Anxiety Scale (Spence et al., 2001) — AGE preschool, parent report (check manual) · MEASURES: anxiety symptoms including a social anxiety subscale · CANNOT TELL YOU: whether withdrawal is temperament, anxiety or a language or social communication difference · TIME: 10 min"],
  },
  "School Age": {
   "applies": "YES — emerging, especially in the later primary years.",
   "prevalence": "Rate not stated here for this band — check before quoting.",
   "see": "Not answering in class, avoiding reading aloud, reluctance at the school concert or sports day, few friends despite wanting them, stomach aches before oral work. Must occur with peers, not only with adults (APA, 2022). Quiet and compliant — easily missed.",
   "tools": ["SDQ", "RCADS", "BASC-3", "Piers-Harris 3",
             "SCAS (Spence Children's Anxiety Scale) — AGE roughly 8–15 child, parent version available (check) · MEASURES: anxiety symptoms by subscale including social phobia · CANNOT TELL YOU: diagnosis, or whether avoidance is anxiety or social communication difference · TIME: 10 min"],
  },
  "Adolescent": {
   "applies": "YES — the main onset window.",
   "prevalence": "US median onset around 13 (APA, 2013) — prevalence for this band not stated here, check.",
   "see": "Avoiding oral exams and presentations, eating alone or not eating in school, not using the canteen, avoiding PE changing rooms, class-specific non-attendance, heavy reliance on online contact. Blushing, trembling and mind-going-blank are common. Ask about mood, self-harm and substance use.",
   "tools": ["RCADS self-report", "Beck Youth Inventories-2", "MFQ (Mood and Feelings Questionnaire)", "BASC-3 SRP"],
  },
  "Young Adult": {
   "applies": "YES — often persists or is first recognised as college and work demands rise.",
   "prevalence": "Adult 12-month prevalence around 7% in US data (APA, 2022) — check for other populations.",
   "see": "Avoiding tutorials, presentations, placements and interviews; dropping out of college; difficulty with part-time work. Adult mental health, college counselling and disability services are the pathway.",
   "tools": ["Adult self-report measures via the service"],
  },
  "Special Setting": {
   "applies": "YES — but distinguish carefully from autism-related social difference.",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Withdrawal in group settings, distress when observed, reluctance to communicate with unfamiliar adults. In pupils with autism or intellectual disability, social avoidance may reflect communication difference, sensory load or unpredictability rather than fear of evaluation. Observation across contexts and staff who know the pupil best are the key sources.",
   "tools": ["Functional behaviour assessment (ABC)", "SDQ", "SRS-2"],
  },
 },
},
]
