"""CONDS records, batch c20: Relational problems and children in care (DSM-5-TR 'other conditions that may be a
focus of clinical attention' — NOT mental disorders) · Psychotic disorders · Bipolar and related disorders."""

CORU = "1.2 · 1.12 · 3.1 · 3.2 · 3.10 · 5.28 · 5.29 · 5.30 · 5.31 · 5.32 · 5.45"
PSI = "2.2.2 · 2.2.4 · 2.3.1 · 1.2.5 · 1.3.1 · 1.2.8 · 3.3.2"

CP_ROUTE = ("CHILD PROTECTION — if anything suggests abuse or neglect (a disclosure, an injury, a child afraid to go home "
            "or to contact): listen, do not question or investigate, do not promise secrecy, write down the child's exact "
            "words with date and time. Report to Tusla as soon as practicable (Children First Act 2015; you are a mandated "
            "person) AND inform the school's DLP. Telling the DLP does NOT discharge your own duty. For a child already in "
            "care, ALSO tell the allocated social worker — being 'known to Tusla' is not the same as Tusla knowing THIS. "
            "Supervision follows the action the same day; it never replaces it.")

RISK_ROUTE = ("Same-day risk route: stay with the young person (or make sure a named adult does) if risk is imminent; "
              "inform your supervisor the same day; inform parents/guardians (or the allocated Tusla social worker for "
              "a child in care) unless that would increase risk; contact the GP or CAMHS the same day, and emergency "
              "services (112/999) or the Emergency Department if risk is imminent. Record what was said and done. "
              "Supervision follows action; it never replaces it.")

CIT_DSM = ("American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders "
           "(5th ed., text rev.; DSM-5-TR). American Psychiatric Publishing.")
CIT_ICD = ("World Health Organization. (2019/2022). International classification of diseases for mortality and "
           "morbidity statistics (11th rev.; ICD-11). https://icd.who.int/ — check codes before quoting.")
CIT_CF = ("Department of Children and Youth Affairs. (2017). Children First: National guidance for the protection and "
          "welfare of children. Government Publications.")

CONDS = [
# ---------------------------------------------------------------------------------------------------------------
{
 "name": "Relational problems and children in care (upbringing away from parents)",
 "code": ("NOT a mental disorder · DSM-5-TR 'Other Conditions That May Be a Focus of Clinical Attention' — Relational "
          "Problems (e.g. Parent-Child Relational Problem, Sibling Relational Problem, Upbringing Away From Parents, "
          "Child Affected by Parental Relationship Distress) coded with ICD-10-CM Z-codes (Z62.x group) · ICD-11 "
          "Chapter 24 'Factors influencing health status or contact with health services' — check exact codes before quoting"),
 "neps": "4. SOCIAL (4.2 Relationships with adults) — and 5. OTHER (5.5 Involvement of other services) · 3. EMOTIONAL (3.5 Trauma, attachment and loss · 3.7 Risk and safeguarding) where relevant",
 "coru": CORU,
 "psi":  PSI,
 "law":  ("Child Care Act 1991 (voluntary care s.4; emergency care order s.13; interim care order s.17; care order "
          "s.18; supervision order s.19 — check sections before quoting) · Child Care (Amendment) Acts 2007 and 2015 "
          "(foster carer authority; aftercare) · Children First Act 2015 · Guardianship of Infants Act 1964 as amended "
          "by the Children and Family Relationships Act 2015 · International Protection Act 2015 · Education (Welfare) "
          "Act 2000 · EPSEN Act 2004 · GDPR / Data Protection Act 2018"),

 "what_it_is": [
  "NOT A DIAGNOSIS. DSM-5-TR lists relational problems under 'Other Conditions That May Be a Focus of Clinical Attention' — conditions that are NOT mental disorders but that affect a person's care, prognosis or treatment (APA, 2022). They are recorded to make the context visible, not to pathologise it.",
  "THE MAIN RELATIONAL CATEGORIES in DSM-5-TR: PARENT-CHILD RELATIONAL PROBLEM (a pattern of interaction — e.g. harsh or inconsistent discipline, over-involvement, hostility, scapegoating — associated with impairment); SIBLING RELATIONAL PROBLEM; UPBRINGING AWAY FROM PARENTS (child in welfare custody, in institutional or residential care, or living away from parents in a non-custodial arrangement such as kinship care); CHILD AFFECTED BY PARENTAL RELATIONSHIP DISTRESS (including separation, divorce and high conflict). Codes are ICD-10-CM Z-codes — check before quoting.",
  "WHY IT IS IN THE ENCYCLOPEDIA: in Irish EP practice this row is where you will meet children in care, children in kinship care, separated children seeking international protection, and children whose difficulty is best understood as a problem IN A RELATIONSHIP rather than IN THE CHILD. Part D lists 'care-experienced children' and 'parenting capacity concerns' as descriptive presentations — the same logic applies.",
  "CHILDREN IN CARE IN IRELAND are placed by Tusla (the Child and Family Agency) under the Child Care Act 1991 — mostly in general foster care or relative (kinship) foster care, a smaller number in residential care, and some in special care. Tusla publishes figures regularly; the large majority are in foster care — check Tusla's latest data before quoting any number.",
  "LEGAL STATUS MATTERS: VOLUNTARY CARE (s.4, with parental agreement — parents usually keep guardianship and consent rights); INTERIM CARE ORDER or CARE ORDER (s.17/s.18, made by the District Court — under a care order Tusla has, broadly, the rights and duties of a parent, including consent to medical or psychiatric examination and assessment); EMERGENCY CARE ORDER (s.13); SUPERVISION ORDER (s.19 — the child stays at home, Tusla visits). Who can consent to YOUR involvement depends on which — check with the allocated social worker every time.",
  "EVERY CHILD IN CARE should have an ALLOCATED SOCIAL WORKER, a written CARE PLAN and statutory CHILD IN CARE REVIEWS (Child Care (Placement of Children in Foster Care) Regulations 1995 and residential equivalents — check current regulations and HIQA standards). Education is part of the care plan. A Guardian ad litem may be appointed in court proceedings to represent the child's views and interests.",
  "SEPARATED CHILDREN SEEKING INTERNATIONAL PROTECTION (arriving without a parent or customary caregiver) are taken into Tusla care and supported by Tusla's dedicated team for separated children — check current service name and arrangements. They may carry trauma, interrupted schooling, EAL needs and uncertainty about their protection claim all at once.",
  "THE ONE-LINE FORMULATION: a relational problem or care status is a CONTEXT that shapes almost everything you see. It is never the explanation for everything, and it never replaces assessment of learning, language, attention, mood and safety.",
 ],
 "what_it_is_not": [
  "NOT a mental disorder or a label on the child. DSM-5-TR is explicit that these are not disorders (APA, 2022). Writing 'has a parent-child relational problem' in a school report without context is unhelpful and can wound; describe the relationship pattern and its effect.",
  "NOT the same as attachment disorder. Most children in care do NOT have Reactive Attachment Disorder or DSED; those are specific, uncommon diagnoses (see the RAD and DSED rows). 'Attachment issues' is not a diagnosis and should not be written as one.",
  "NOT proof of low ability. Children in care do, on average, less well in school, but Sebba et al. (2015, Rees Centre, England) found that time in care, placement and school moves, special educational needs and absence explained much of the gap — and that longer stable care was associated with BETTER progress than for children in need who stayed at home. Care is often protective, not the cause.",
  "NOT the same system as England. 'Virtual School Heads', 'Designated Teachers for looked-after children', 'Personal Education Plans' and 'Pupil Premium Plus' are statutory features in ENGLAND (Children and Families Act 2014 and related guidance). Ireland has NO virtual school and no equivalent funding stream; UK books and training use these terms constantly. Irish arrangements are the care plan, the allocated social worker, Tusla Education Support Service (TESS), and the Tusla–Department of Education joint protocol on the educational inclusion of children in care (2017 — check current version).",
  "NOT a reason for the foster carer to sign the EP consent form automatically. Foster carers provide day-to-day care; legal consent usually sits with Tusla (care order) or the parents (voluntary care). Some long-term foster carers can be given enhanced authority under the Child Care (Amendment) Act 2007 — check. Ask; do not assume.",
  "NOT something to be explained only by 'trauma'. Many children in care have DLD, FASD, ADHD, learning difficulty or hearing problems that were missed during early instability. Trauma framing can create diagnostic overshadowing in reverse.",
  "NOT a problem 'in' one person. A parent-child relational problem is a pattern between people. The child's behaviour and the adult's response maintain each other (Patterson's coercion model, 1982), which is why parent-focused and relationship-focused interventions work.",
 ],
 "prevalence": [
  "CHILDREN IN CARE, IRELAND: Tusla publishes monthly/quarterly performance data on the number of children in care, placement type and allocation of social workers. The figure has been in the region of several thousand, with the large majority in foster care (general and relative) — check the latest Tusla figures before quoting any number.",
  "ALLOCATED SOCIAL WORKER: not every child in care has one at any given time; Tusla reports the proportion allocated — check the current figure and ask for the name of the social worker (or team leader) on every case.",
  "EDUCATION OUTCOMES, IRELAND: Darmody, McCoy and Smyth (2013), for the Ombudsman for Children's Office, reviewed the education of children in care in Ireland and found gaps in data, placement-driven school moves and variable school support — no national attainment figure stated here; check before quoting.",
  "EDUCATION OUTCOMES, ENGLAND: Sebba et al. (2015) linked care and education data and found looked-after children on average well behind peers at 16, with high rates of identified SEN — figures are English and should not be transferred to Ireland as if local.",
  "SEPARATED CHILDREN SEEKING PROTECTION: numbers vary with international events — check Tusla figures.",
  "PARENT-CHILD RELATIONAL PROBLEMS: no prevalence figure is meaningful — it is a clinical focus, not a population diagnosis. Rate not stated here.",
  "SPECIAL EDUCATIONAL NEEDS: identified SEN and mental health needs are considerably more common among children in care than in the general population in UK and international studies — exact rates not stated here; check before quoting.",
 ],
 "cooccurring": [
  {"name": "TRAUMA RESPONSES / PTSD", "rate": "elevated where maltreatment occurred — rate not stated here, check",
   "presents": "hypervigilance, startle, dissociation ('zoning out'), reactions to reminders — contact visits, raised voices, court dates. See the PTSD row; do not interview for trauma."},
  {"name": "ATTACHMENT DIFFICULTY (and, uncommonly, RAD / DSED)", "rate": "attachment insecurity common; RAD and DSED uncommon — rate not stated here, check",
   "presents": "difficulty trusting adults, controlling or indiscriminate relating, testing new carers and teachers. Describe the pattern; a diagnosis belongs to CAMHS or a specialist team."},
  {"name": "DEVELOPMENTAL LANGUAGE DISORDER / LANGUAGE DELAY", "rate": "elevated after early neglect — rate not stated here, check",
   "presents": "misread as defiance or 'not listening'; narrative and vocabulary gaps. Request SLT assessment — undetected language need is one of the commonest misses in this group."},
  {"name": "FASD (prenatal alcohol exposure)", "rate": "elevated in care-experienced and adopted children — rate not stated here, check",
   "presents": "memory, executive and adaptive difficulties out of line with IQ; often unrecognised and diagnosed only by specialist teams. Ask the social worker what is known of pregnancy history — do not speculate in writing."},
  {"name": "ADHD", "rate": "elevated — rate not stated here, check",
   "presents": "restlessness, impulsivity and poor concentration; overlaps with hyperarousal. Establish history across placements and settings before concluding either way."},
  {"name": "DEPRESSION, ANXIETY AND SELF-HARM", "rate": "elevated — rate not stated here, check",
   "presents": "withdrawal, sleep disturbance, anxiety around contact and placement change; adolescents in care are at higher risk of self-harm. Ask directly about risk."},
  {"name": "LEARNING GAPS FROM INTERRUPTED SCHOOLING", "rate": "common — rate not stated here, check",
   "presents": "attainment gaps that follow school moves and missed schooling rather than a learning disorder. Map the school history before diagnosing a specific learning difficulty."},
  {"name": "BEHAVIOUR THAT CHALLENGES / SCHOOL EXCLUSION RISK", "rate": "elevated — rate not stated here, check",
   "presents": "reactive aggression, absconding, refusal. Suspension or reduced timetable can destabilise a placement — the school decision has consequences at home."},
 ],
 "recommendations": [
  "START WITH WHO HOLDS WHAT: name in the report the allocated social worker, the carers, the parents' role and consent basis (as confirmed by Tusla), and who receives the report. Getting this wrong is a data-protection breach and can damage a placement.",
  "ONE KEY ADULT in school, known to the child and the carer, who meets the pupil briefly and predictably (a daily check-in, not only when things go wrong). Relationship-based practice is the core intervention; PACE (Playfulness, Acceptance, Curiosity, Empathy — Hughes, 2009) is a widely used staff stance, though school-based evaluation is limited — check.",
  "PLAN FOR TRANSITIONS: contact visits, court dates, review meetings, placement moves and holidays are predictable stress points. Agree with the carer and social worker how school will be told (not the details, just that it is a hard week) and what changes that week.",
  "EDUCATIONAL STABILITY: recommend that school moves be avoided where possible when placements change, and that records and support plans move with the child the same week when they cannot. Name the Tusla–Department of Education joint protocol (2017 — check current version) and TESS where attendance or school place is at issue.",
  "ASSESS THE LEARNING, NOT THE LABEL: do a full educational picture (attainment, language, attention, cognitive profile where warranted) — gaps are common and often missed. Request SLT where language is in doubt; flag FASD questions to the social worker for specialist routes, not in the report.",
  "FOR PARENT-CHILD RELATIONAL PROBLEMS AT HOME: signpost evidence-based parenting support — Incredible Years (Webster-Stratton; Irish trial McGilloway et al., 2012) or Parents Plus (Irish, Sharry and colleagues) — via Primary Care, Tusla family support, Family Resource Centres or Meitheal (Tusla's early intervention model). Name what is locally available — check.",
  "BEHAVIOUR POLICY: ask the school to consider the impact of suspension, exclusion and reduced timetables on placement stability, and to inform the social worker before (not after) any such decision. Reduced timetables have Department guidance and notification requirements — check the current circular.",
  "CONTINUUM LEVEL: most children in care with identified needs sit at School Support Plus because Tusla is involved; some need only School Support. Name the level.",
  "REFER: CAMHS (via GP, or via the social worker where Tusla arranges access) for mental health difficulty with impairment or risk; Primary Care Psychology for milder difficulties; SLT/OT via Primary Care or CDNT; Tusla-commissioned therapeutic services where available (check locally). Aftercare planning from 16 (Child Care (Amendment) Act 2015 — check eligibility details).",
  "DO NOT write 'attachment disorder', 'traumatised' or 'relational problem' as a diagnosis; do not include details of the care history beyond what is needed and agreed; do not share the report with birth parents, carers or others without confirming with Tusla who is entitled to it; do not accept the foster carer's signature as consent without confirming legal status.",
 ],
 "explain_parent": [
  "TO A FOSTER CARER: 'You know her better than anyone in the room. What I want is your picture of what helps and what sets her back — especially around contact and changes. School will do better if we plan around those weeks.'",
  "TO A FOSTER CARER ABOUT CONSENT: 'Because she's in care, Tusla holds some of the decisions — so I'll check the consent with her social worker. That's not about trusting you less; it's about making sure the right people have signed.'",
  "TO A BIRTH PARENT (where they retain guardianship and are involved): 'You're still her mother and your view matters. I'm here to help school understand how she learns and what she needs. I'll tell you what I'm doing and what I find, within what the social worker and the court arrangements allow.'",
  "TO A PARENT WHERE THE RELATIONSHIP AT HOME IS STRAINED: 'A lot of families get stuck in a cycle where every instruction becomes a battle, and both of you end up exhausted. It's a pattern between you, not a fault in either of you — and patterns can be changed. Parent programmes like Parents Plus are designed for exactly this.'",
  "AFTER SEPARATION OR HIGH CONFLICT: 'What children tell us helps most is not being put in the middle — not carrying messages, not hearing the other parent criticised. You don't have to get on, just keep her out of it.'",
  "SIGNPOST: GP; Tusla family support / Family Resource Centre / Meitheal; Parents Plus or Incredible Years locally (check); Irish Foster Care Association for carers; EPIC (Empowering People in Care) for young people in and leaving care; Barnardos; One Family for separated parents — check current services.",
 ],
 "explain_teacher": [
  "'Children in care have usually had adults who were unpredictable. So expect him to test whether you'll stay the same. Being consistent through the testing is the intervention.'",
  "'Contact weeks and review meetings are hard. You don't need the details — just know the week, and lower the demands a bit.'",
  "'Please don't make assumptions in front of the class: family-tree projects, \"bring in a baby photo\", Mother's Day cards, \"ask your mum to sign it\". Offer a way to take part that doesn't expose him.'",
  "'He's entitled to privacy. Only the staff who need to know should know he's in care — and not the reasons.'",
  "'If the behaviour escalates, please tell the social worker and the carer before any suspension decision. A suspension can put a placement at risk, and a placement move usually means a school move.'",
  "'Don't let \"it's trauma\" stop anyone checking his reading, language and hearing. Children in care often have learning needs that were missed in all the moves.'",
  "'If he tells you something about being hurt — at home, at contact, anywhere — listen, don't question, don't promise secrecy, write his words down and go to the DLP, and remember your own duty to report to Tusla.'",
 ],
 "explain_child": [
  "YOUNGER: 'Lots of children live with foster families for a while, or for a long time. It is never because a child did something wrong. My job is to help school be a good place for you.'",
  "OLDER: 'I'm not from Tusla and I'm not here about your care arrangements. I work with schools. I want to know what school is like for you and what would make it better — and you can decide what you want the teachers to know.'",
  "ASK: 'Who in school do you get on with?' 'What's the hardest part of the week?' 'What do you want people to know — and what do you NOT want people to know?' 'Have you changed schools? What was that like?'",
  "SEPARATED CHILD SEEKING PROTECTION: use a trained interpreter (never a peer or a relative), explain who you are and who you are not (not immigration, not the Gardaí, not the court), and do not ask about the journey or the claim.",
  "CONFIDENTIALITY, SAID PLAINLY: 'Most of what you tell me stays between us and the people helping you in school. If I'm worried you or someone else isn't safe, I have to tell someone whose job is to keep you safe — and I'll tell you first.'",
  "GIVE CHOICE AND CONTROL: many children in care have had decisions made about them in rooms they were not in. Tell them what the report will say and who will see it.",
 ],
 "analogies": [
  "THE NEW HOUSE WITH OLD RULES: 'Imagine you lived for years somewhere where rules changed every day. When you move somewhere safe, you keep checking — because the old rules kept you safe. The checking is sensible, not bad.' Works with foster carers and teachers.",
  "THE DANCE, NOT THE DANCER (relational problem): 'When two people keep stepping on each other's toes, you don't fix it by blaming one dancer — you change the steps.' Works with parents stuck in coercive cycles; reduces blame.",
  "THE SCHOOL BAG THAT GETS LEFT BEHIND: 'Every time a child moves placement, some of what they learned, and who knew them, gets left in the last school.' Works with principals and in multi-agency meetings when arguing for educational stability.",
  "THE SECURE BASE (Bowlby, 1988): 'Children explore — and learn — when they know someone has their back.' Works with staff to explain why a key adult matters more than a reward chart.",
 ],
 "language": [
  "Use 'child in care', 'care-experienced', 'in foster care', 'in relative / kinship care', 'in residential care'. Ask the young person what they prefer; many dislike 'LAC' and 'looked-after child' (UK terms).",
  "Avoid 'care kid', 'placement breakdown' in front of the child (say 'placement ended'), 'contact' used coldly ('family time' is increasingly used — follow the service), and 'real parents' (say 'birth parents').",
  "'Relational problem' is a clinical recording category, not everyday language — in reports describe the relationship pattern and its impact instead.",
  "Separated children: 'separated child seeking international protection' is the Irish service term; avoid 'unaccompanied minor' as a label, 'illegal', or 'asylum seeker' as an identity.",
  "Write the care history only to the extent needed and agreed. Say 'Tusla is involved' rather than listing reasons unless the social worker has agreed the wording.",
 ],
 "red_flags": [
  "RED FLAG — any disclosure or sign of abuse or neglect, in placement, at contact or elsewhere. " + CP_ROUTE,
  "RED FLAG — self-harm, suicidal thinking, running away/going missing, or signs of child sexual or criminal exploitation (older friends, unexplained money or phones, missing from placement). " + RISK_ROUTE,
  "RED FLAG — a placement at risk of ending, or a sudden unplanned move. Contact the social worker; the school's next decision (suspension, reduced timetable) may tip it.",
  "BOUNDARY — consent: confirm the legal basis with the allocated social worker BEFORE assessment and before sharing the report. Do not accept a foster carer's signature by default; do not share with birth parents without confirming entitlement.",
  "BOUNDARY — you do not assess parenting capacity, placement suitability or contact arrangements; these belong to Tusla and the courts. If asked to comment in court proceedings, stop and take it to supervision first.",
  "BOUNDARY — you do not diagnose attachment disorder, PTSD or FASD; you describe, formulate and refer (PSI 2.2.2).",
  "WATCH — 'nothing can be done until the placement settles'. Educational support should not wait; school may be the most stable thing in the child's life.",
 ],
 "child_voice": [
  "'MY THOUGHTS ABOUT SCHOOL' (NEPS) — gets the pupil's view of school without asking about care or family. → https://www.gov.ie/en/publication/52ee2-neps-resources-and-publications/",
  "SCALING AND DAY MAPPING — green/amber/red across the school week, then 'what's different on the green days?' Locates predictable hard points (contact, Mondays, transitions) without discussing the history.",
  "'WHAT I WANT PEOPLE TO KNOW / NOT KNOW' — a two-column sheet the pupil controls, which becomes the basis of the staff information note. Good because privacy is often what children in care most want and least get.",
  "SAFE PEOPLE / HELPING HAND — names the adults the child trusts in school and at home; tells you who the key adult should be.",
  "THE CHILD'S VIEWS IN THEIR CARE REVIEW — ask (with the social worker) whether the child's views on school from your work can feed into the next child-in-care review. Article 12 UNCRC and Article 42A of the Constitution support the child's voice in decisions about them.",
  "EPIC (Empowering People in Care) supports young people to have a say in their care — signpost for adolescents.",
 ],
 "questions": [
  "Q: (foster carer) 'Can I sign the consent form?' — A: 'Possibly, but it depends on the legal arrangement. Under a care order Tusla usually gives consent; under voluntary care, usually the parents. Some long-term carers have been given extra authority. I'll check with the social worker so it's done right.'",
  "Q: (principal) 'Isn't this just attachment disorder?' — A: 'Attachment disorders are specific, uncommon diagnoses made by clinicians. Most children in care don't have one. What I can do is describe how she relates to adults here and what helps — and check her learning and language, which are often missed.'",
  "Q: 'Should we tell the class she's in care?' — A: 'No, not unless she wants that. Staff who need to know should know, and not the reasons. Ask her what she wants people to know.'",
  "Q: (teacher) 'In England they have a virtual school head — who's that here?' — A: 'There's no equivalent role in Ireland. Here it's the care plan and the allocated social worker, with Tusla Education Support Service where attendance or a school place is the issue, and a joint Tusla–Department protocol on education of children in care. I'll check the current arrangements locally.'",
  "Q: (birth parent) 'Can I get a copy of the report?' — A: 'I want you to be informed. Who can receive the report depends on the legal arrangement and what's been agreed with Tusla, so I'll confirm that with the social worker before I send it to anyone.'",
  "Q: (parent) 'Is it my fault he's like this at home?' — A: 'I'm not looking at fault. When things get tense, parents and children get into cycles that are hard to break — it happens in lots of families. Programmes like Parents Plus or Incredible Years help parents change the pattern, and they have good evidence, including in Ireland.'",
  "Q: 'He's moving placement next month — should we hold off on the assessment?' — A: 'Let's ask the social worker whether he'll stay in this school. If he's moving school, a clear summary of what we know now will help the next school start well. Support shouldn't wait on the placement.'",
  "Q: (young person, 17) 'What happens when I turn 18?' — A: 'You may be entitled to aftercare support, including help with education — your social worker or aftercare worker can explain what applies to you. I can help make sure your education plans are in writing.'",
 ],
 "supervision": [
  "Bring the consent question on every child in care: what order is in place, who confirmed it, who can receive the report. Ask your supervisor how the service records this.",
  "Ask how your service works with Tusla locally — who to call when the social worker is unallocated, and how to get into a child-in-care review.",
  "Bring any request to comment on placement, contact or parenting capacity, or to provide a report for court. Ask what the service's policy is before responding.",
  "Bring the case where 'trauma' or 'attachment' was the explanation offered before anyone checked language, hearing or learning.",
  "Bring your own reaction — frustration at systems, sadness, identification with a child or carer. CORU 5.45 and PSI 4.1.2 treat this as practice.",
  "Ask about separated children seeking protection: interpreter arrangements, trauma-informed practice, and liaison with Tusla's separated children team.",
 ],
 "reflection": [
  "ON CONSENT — Did I confirm the legal basis myself, or did I assume the person in front of me could sign?",
  "ON THE LABEL — Did 'in care' become the explanation for everything? What did I rule in or out about learning, language and attention?",
  "ON WHOSE VOICE — Did the child's own view of school appear in my report, in their words? Did they know what I would write?",
  "ON THE SYSTEM — Did my recommendations take account of the consequences at home (placement stability) of what school does?",
  "ON LANGUAGE — Did I write 'relational problem', 'attachment disorder' or 'LAC' where a description would have been kinder and more accurate?",
  "ON UK IMPORTS — Did I recommend a 'PEP' or a 'virtual school' referral that does not exist in Ireland?",
  "WHAT GOOD LOOKS LIKE: 'I confirmed with the social worker that a care order was in place and Tusla consented; the carer and the pupil's views shaped the plan; I found an unidentified language difficulty and requested SLT; the plan names a key adult, flags contact weeks, and asks the school to consult the social worker before any suspension.'",
  "WHAT POOR LOOKS LIKE: 'Pupil is a LAC with attachment issues due to trauma. Recommend nurture approach.' — consent unchecked, no assessment of learning, no child's voice, a non-diagnosis written as a diagnosis, and a UK acronym.",
 ],
 "citations": [
  CIT_DSM,
  CIT_ICD,
  CIT_CF,
  "Darmody, M., McCoy, S., & Smyth, E. (2013). The education of children in care in Ireland: An exploratory study. Ombudsman for Children's Office. — check title and details before quoting.",
  "Sebba, J., Berridge, D., Luke, N., Fletcher, J., Bell, K., Strand, S., Thomas, S., Sinclair, I., & O'Higgins, A. (2015). The educational progress of looked after children in England: Linking care and educational data. Rees Centre, University of Oxford / University of Bristol. — check author list.",
  "Tusla – Child and Family Agency & Department of Education and Skills. (2017). Joint protocol for interagency collaboration between Tusla and the Department of Education and Skills to promote the educational inclusion of children and young people in care. — check title and current version.",
  "McGilloway, S., Ní Mháille, G., Bywater, T., Furlong, M., Leckey, Y., Kelly, P., Comiskey, C., & Donnelly, M. (2012). A parenting intervention for childhood behavioral problems: A randomized controlled trial in disadvantaged community-based settings. Journal of Consulting and Clinical Psychology, 80(1), 116–127.",
  "Hughes, D. A. (2009). Attachment-focused parenting: Effective strategies to care for children. W. W. Norton.",
  "Patterson, G. R. (1982). Coercive family process. Castalia.",
  "Bowlby, J. (1988). A secure base: Parent-child attachment and healthy human development. Basic Books.",
 ],

 "pathway": {
  "age": "Any age. Care entry can happen from birth; in schools, children in care are met throughout primary and post-primary, often at a placement or school move, a behaviour crisis, or an exam-arrangements question. Separated children seeking protection are mostly adolescents. Relational problems at home are usually raised alongside behaviour or attendance concerns.",
  "who_diagnoses": "Ireland: not a diagnosis. Relational problems may be recorded by CAMHS or Primary Care as a focus of clinical attention. Care status is a legal fact established by the District Court (orders) or a voluntary care agreement with Tusla. Mental health or developmental diagnoses in children in care are made by CAMHS, CDNT, Primary Care, paediatrics or Tusla-commissioned clinicians.",
  "who_wrote_report": "Tusla social work (care plan, child-in-care review minutes — shared only as agreed); Guardian ad litem report (court — usually not shareable); CAMHS, CDNT or Primary Care reports; a Tusla-commissioned psychologist; a previous school or NEPS psychologist from an earlier placement area.",
  "refer_to": "Allocated Tusla social worker first (and Tusla duty social work where unallocated or where there is a new concern); CAMHS via GP or social worker for mental health with impairment or risk; Primary Care Psychology, SLT, OT; CDNT where a disability is suspected; TESS for attendance or school place; parenting supports (Parents Plus, Incredible Years, Meitheal, Family Resource Centres) for relational problems at home — check local availability.",
  "sooner": "'For a child who has had a lot of change, noticing at all is an achievement. What matters is that school stays steady from here — and that we check nothing about his learning was missed along the way.'",
 },
 "differential": [
  "ATTACHMENT DISORDER (RAD / DSED) — specific, uncommon diagnoses after pathogenic care; most children in care do not meet them. See those rows.",
  "PTSD / TRAUMA RESPONSE — event-linked intrusions, avoidance and threat; can co-exist with relational difficulty.",
  "NEURODEVELOPMENTAL CONDITIONS (DLD, ADHD, autism, FASD, intellectual disability) — may have been missed during instability; the relational context does not rule them out.",
  "ONGOING HARM — not a differential diagnosis but the first thing to consider when behaviour changes suddenly.",
  "ODD / CONDUCT DIFFICULTY — oppositional behaviour across settings; in a relational problem it may be confined to one relationship. Assess across settings.",
  "ADJUSTMENT DISORDER — distress after a specific change (placement move, separation) that is time-limited.",
 ],
 "next": [
  "Confirm the legal status and consent basis with the allocated social worker before anything else.",
  "Gather the child's view, the carer's view and the school's view; map school history and moves.",
  "Assess learning and language properly; request SLT or other assessment where needed.",
  "Write a plan with a key adult, transition/contact-week adjustments and a request that the social worker be consulted before any suspension — at School Support Plus where Tusla is involved.",
  "Agree who receives the report and feed the child's educational views into the next child-in-care review.",
 ],
 "presentations": [
  "Care-experienced children (foster, kinship, residential, aftercare)",
  "Child protection and welfare concerns",
  "Parenting capacity concerns",
  "Family functioning difficulties",
  "Parental separation and high-conflict co-parenting",
  "Domestic violence exposure",
  "Separated children seeking international protection",
  "Placement or school moves and interrupted schooling",
  "Knowing which service does what, and the referral route",
  "Professional and service boundaries — what is not yours to do",
 ],

 "bands": {
  "Early Years": {
   "applies": "YES — care entry and parent-child relational concerns often begin here",
   "prevalence": "Rate not stated here — check Tusla figures by age before quoting.",
   "see": "Sleep and feeding difficulties, indiscriminate or wary relating, language delay, developmental gaps, distress around contact. Work through the setting, carers and Primary Care/CDNT; the EP rarely sees preschool children in care directly. Parent-child relational problems show as stuck, coercive interaction — refer to parenting support.",
   "tools": ["Ages & Stages Questionnaires (ASQ-3)", "SDQ (2–4 version)", "Schedule of Growing Skills II"]},
  "School Age": {
   "applies": "YES — the most common point of EP involvement",
   "prevalence": "Rate not stated here — check Tusla figures before quoting.",
   "see": "Testing relationships with teachers, reactive behaviour around contact and review weeks, learning gaps after moves, missed language needs. Consent through Tusla or parents as the order dictates; full educational assessment plus consultation with carer and social worker; child's voice through non-intrusive methods.",
   "tools": ["SDQ", "WIAT-III UK", "CELF-5 UK", "BASC-3", "WISC-V UK"]},
  "Adolescent": {
   "applies": "YES — includes separated children seeking protection and young people approaching aftercare",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Identity questions, anger at the system, absconding, exploitation risk, self-harm, relationship difficulties with carers, and exam planning. The young person's own consent and view carry growing weight; aftercare planning begins around 16. Always ask about risk and substance use.",
   "tools": ["SDQ", "RCADS self-report", "BASC-3 SRP", "Access arrangements evidence (RACE)"]},
  "Young Adult": {
   "applies": "YES — aftercare (Child Care (Amendment) Act 2015 — check eligibility and age limits)",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Care leavers moving to further or higher education, training or work, often without family backing. The EP role is educational: disability supports, access routes, transition reports. Aftercare workers and EPIC are key allies; signpost Jigsaw for mental health support.",
   "tools": ["Adult self-report measures via the service"]},
  "Special Setting": {
   "applies": "YES — children with disabilities are over-represented among children in care in international studies (check)",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Residential or shared-care arrangements, respite, multiple carers and staff, and communication difficulties that make distress hard to read. Consistency across home, respite and school is the intervention; confirm consent carefully where arrangements are complex.",
   "tools": ["Vineland-3 / ABAS-3", "Functional behaviour assessment (ABC)"]},
 },
},

# ---------------------------------------------------------------------------------------------------------------
{
 "name": "Psychotic disorders (schizophrenia spectrum and other psychotic disorders)",
 "code": ("DSM-5-TR Schizophrenia Spectrum and Other Psychotic Disorders (Delusional Disorder, Brief Psychotic Disorder, "
          "Schizophreniform Disorder, Schizophrenia, Schizoaffective Disorder, substance/medication-induced and due to "
          "another medical condition) · ICD-11 6A20–6A2Z (6A20 Schizophrenia, 6A23 Acute and transient psychotic "
          "disorder, 6A24 Delusional disorder — check codes before quoting)"),
 "neps": "5. OTHER (5.5 Involvement of other services) — and 3. EMOTIONAL (3.7 Risk and safeguarding)",
 "coru": CORU,
 "psi":  PSI,
 "law":  "Children First Act 2015 · Mental Health Act 2001 (admission of children — a matter for the HSE and the District Court, not the EP) · EPSEN Act 2004 · Equal Status Acts 2000–2018 · Disability Act 2005 · GDPR",

 "what_it_is": [
  "PSYCHOSIS is a state in which a person's experience of reality is altered: HALLUCINATIONS (most often hearing voices), DELUSIONS (fixed beliefs not shared by the person's culture and not changed by evidence — e.g. being followed, controlled or specially chosen), DISORGANISED THINKING AND SPEECH, grossly disorganised behaviour or catatonia, and NEGATIVE SYMPTOMS (reduced motivation, emotional expression and speech) (APA, 2022, DSM-5-TR).",
  "PSYCHOTIC DISORDERS are the diagnoses in which these are central: SCHIZOPHRENIA (at least six months of disturbance including an active phase); SCHIZOPHRENIFORM (as schizophrenia but one to six months); BRIEF PSYCHOTIC DISORDER (under one month, full return to functioning); DELUSIONAL DISORDER; SCHIZOAFFECTIVE DISORDER (psychosis plus major mood episodes). Psychosis can also be caused by substances, medication or medical illness, or occur within bipolar disorder or severe depression (APA, 2022).",
  "EARLY-ONSET PSYCHOSIS (before 18) is uncommon; VERY EARLY ONSET (before about 13) is rare. Onset usually rises from mid-to-late adolescence into early adulthood (APA, 2022; NICE, 2013, CG155). Most EPs will meet it only a handful of times in a career — which is why the route must be known in advance.",
  "THE PRODROME: first episodes are often preceded by months of change — withdrawal, falling grades, suspiciousness, odd beliefs, unusual perceptual experiences, sleep disturbance, loss of drive. Services describe 'at risk mental state' (ARMS) or 'clinical high risk'. Only a minority of young people with these features go on to a psychotic disorder (Fusar-Poli et al., 2012 — check figures before quoting); many have other needs (anxiety, depression, trauma) that still deserve help.",
  "EARLY INTERVENTION MATTERS: longer duration of untreated psychosis is associated with poorer outcomes (Marshall et al., 2005). The HSE has a National Clinical Programme for Early Intervention in Psychosis with a published Model of Care (HSE, 2019) — check which age range and which local teams operate in your area; for under-18s, CAMHS is usually the route.",
  "TREATMENT belongs to CAMHS/psychiatry: NICE (2013, CG155 — check for updates) recommends for children and young people with first-episode psychosis a combination of antipsychotic medication (a specialist decision), individual CBT for psychosis (CBTp) and family intervention, plus support with education. The EP does not diagnose psychosis and never advises on medication (PSI 2.2.2).",
  "RECOVERY IS REAL. Outcomes vary widely; many young people return to education and work, especially with early help and continued educational support. The school's job is to hold the place, adapt the demands and keep the young person connected.",
 ],
 "what_it_is_not": [
  "NOT the same as psychotic-like experiences in childhood. Hearing a voice or having an unusual belief is surprisingly common in children and young adolescents and usually passes. Kelleher et al. (2012), in a meta-analysis led by an Irish group, reported median prevalences of psychotic symptoms of around 17% in 9–12-year-olds and around 7.5% in 13–18-year-olds — check before quoting. Most do not develop a psychotic disorder, but these experiences are linked to other mental health difficulties and to suicidal behaviour (Kelleher et al., 2013) — so they are asked about kindly and taken seriously, not dismissed and not catastrophised.",
  "NOT imaginary friends. An imaginary companion in a young child is common and usually benign; the child typically knows it is pretend, enjoys it and can control it.",
  "NOT 'split personality'. Schizophrenia has nothing to do with multiple personalities (that confusion refers to dissociative identity disorder, a separate and contested diagnosis).",
  "NOT violence. People experiencing psychosis are far more likely to be victims than perpetrators of violence; media stereotypes drive stigma and delay help-seeking.",
  "NOT caused simply by cannabis — but NOT unrelated either. Cannabis use, especially early, frequent and high-potency use, is associated with increased risk of psychosis (Moore et al., 2007; Di Forti et al., 2019). Causation is debated and most cannabis users do not develop psychosis; the association is strong enough that it should be discussed honestly with young people.",
  "NOT something a school can screen for or an EP can identify with a questionnaire. No school-administered measure diagnoses psychosis; the right action is a same-day conversation with parents and an urgent medical route.",
  "NOT always psychosis when a young person says they 'hear things'. Trauma (intrusive memories, dissociation), anxiety, OCD intrusive thoughts, sleep-related experiences, autistic literal description, cultural or religious experience and medical causes all need considering — by clinicians.",
 ],
 "prevalence": [
  "LIFETIME (ALL AGES): DSM-5-TR gives a lifetime prevalence of schizophrenia of roughly 0.3–0.7% (APA, 2022) — check before quoting; figures vary by country and method.",
  "UNDER 18: early-onset schizophrenia is uncommon and very early onset (before 13) is rare — rate not stated here, check before quoting.",
  "PSYCHOTIC-LIKE EXPERIENCES: common in childhood and early adolescence, decreasing with age — median about 17% (9–12) and 7.5% (13–18) in Kelleher et al. (2012) — check before quoting.",
  "IRELAND: incidence of first-episode psychosis has been studied in Irish catchment areas (e.g. Cavan-Monaghan and Dublin studies) — rates not stated here; check before quoting.",
  "SEX RATIO: schizophrenia is somewhat more common in males, with earlier onset in males (APA, 2022) — ratio not stated here; check.",
  "HIGHER RISK GROUPS: family history of psychosis; 22q11.2 deletion syndrome (markedly elevated risk — check figures); heavy early cannabis use; migration and urban upbringing; childhood adversity. These raise risk; none determines outcome.",
 ],
 "cooccurring": [
  {"name": "DEPRESSION AND SUICIDAL THINKING", "rate": "elevated in first-episode psychosis — rate not stated here, check",
   "presents": "low mood, hopelessness and self-harm, especially early in the illness and after discharge. Ask about risk directly at every contact; same-day route if present."},
  {"name": "ANXIETY AND SOCIAL WITHDRAWAL", "rate": "common — rate not stated here, check",
   "presents": "fearfulness, avoidance of crowded places, suspicion of peers. Can precede psychosis or follow it; do not assume it is 'just anxiety' if beliefs are becoming fixed."},
  {"name": "SUBSTANCE USE (especially cannabis)", "rate": "elevated — rate not stated here, check",
   "presents": "use to cope with voices, anxiety or sleep; can trigger or worsen symptoms. Ask non-judgementally; refer through CAMHS or local youth substance services."},
  {"name": "AUTISM", "rate": "elevated co-occurrence reported — rate not stated here, check",
   "presents": "literal descriptions, intense interests and social difficulty can be misread as psychosis, and psychosis can be missed in autistic young people. Needs specialist assessment."},
  {"name": "TRAUMA AND ADVERSITY", "rate": "elevated — rate not stated here, check",
   "presents": "voices or intrusive images linked to past trauma; paranoia rooted in real experiences. Keep child protection in view."},
  {"name": "COGNITIVE AND LEARNING DIFFICULTIES", "rate": "common during and after an episode — rate not stated here, check",
   "presents": "slowed processing, reduced attention and memory, loss of drive; falling grades often precede diagnosis. Plan a graded return with realistic demands."},
  {"name": "22q11.2 DELETION SYNDROME AND OTHER GENETIC CONDITIONS", "rate": "psychosis risk markedly elevated in 22q11.2DS — check figures",
   "presents": "a known genetic diagnosis plus new withdrawal, anxiety or odd beliefs in adolescence. Flag to the medical team; do not speculate to the family."},
 ],
 "recommendations": [
  "IF YOU SUSPECT A NEW PSYCHOTIC PRESENTATION: this is a same-day action, not a report recommendation. Speak to the parents (or Tusla social worker for a child in care) the same day, advise urgent GP review (or CAMHS where already open, or ED/112 if the young person is at risk or very distressed), inform your supervisor, and record exactly what was said and seen.",
  "WRITE WHAT YOU OBSERVED, NOT WHAT YOU THINK IT IS: 'Pupil reported hearing a voice commenting on her actions over the past three weeks; she appeared frightened; grades have dropped markedly since September.' Never 'is psychotic', 'is schizophrenic' or 'prodromal'.",
  "RETURN TO SCHOOL AFTER AN EPISODE: plan with the young person, parents and the treating team (with consent): graded or part-time return with a review date, a key adult, a quiet base, reduced homework and assessment load, and a plan for what to do if symptoms return. Reduced timetables should be time-limited and follow current Department guidance — check the circular.",
  "COGNITIVE AND ENERGY ADJUSTMENTS: expect slower processing, reduced concentration and fatigue (from the illness and sometimes from medication — report side effects you notice to parents; do not advise). Chunk tasks, give written summaries, allow extra time and breaks.",
  "STATE EXAMINATIONS: check eligibility for RACE and for deferral or other options with the school and SEC — do not promise.",
  "STAFF KNOWLEDGE, WITH CONSENT: brief the staff who need to know, in plain, non-stigmatising language — what to look for (early signs agreed with the treating team) and whom to tell.",
  "CONTINUUM LEVEL: School Support Plus — CAMHS or an early intervention team will be involved. Name the level.",
  "REFER: urgent GP/CAMHS for first presentation; CAMHS for under-18s (HSE Early Intervention in Psychosis services — check local age range); ED/112 where there is immediate risk. For young adults, adult mental health / EIP team via GP. Jigsaw is NOT the route for suspected psychosis.",
  "DO NOT diagnose, speculate about schizophrenia to parents, use the words 'prodrome' or 'at risk mental state' as findings, or advise on medication or on stopping it (PSI 2.2.2). DO NOT wait for the next scheduled visit.",
 ],
 "explain_parent": [
  "'I'm worried about some of the things she's told me and some of the changes school has seen. I'm not able to say what's causing them — that needs a doctor — but I don't think we should wait. I'd like you to see your GP today or tomorrow, and I'll write down what I've seen so you can bring it.'",
  "'Experiences like hearing voices can have a lot of different causes — stress, sleep, anxiety, something medical, or sometimes the start of something that needs specialist care. The important thing is that getting help early makes a real difference.'",
  "'If at any point she seems at risk of harming herself, or is very frightened and you can't reassure her, go to the Emergency Department or call 112 or 999.'",
  "AFTER A DIAGNOSIS: 'School's job now is to keep her connected — a gradual return, less pressure, a key person. Many young people get back to their studies after an episode like this. We'll plan it with her and with her team.'",
  "ABOUT CANNABIS (if relevant, and gently): 'The team may talk to her about cannabis. There's good evidence it can make these experiences more likely or worse for some young people, especially strong cannabis. It's worth hearing that from them.'",
  "SIGNPOST: GP; CAMHS; the HSE Early Intervention in Psychosis service where available; Shine (supporting people affected by mental ill health, including families); Mental Health Ireland; See Change (stigma reduction) — check current services.",
 ],
 "explain_teacher": [
  "'She has been unwell with an illness that affects how she experiences things. It's treatable, and she's getting treatment. What she needs from school is calm, predictability and fewer demands for a while.'",
  "'You may notice she's slower, tired, flat or finds it hard to concentrate. That's part of recovery (and sometimes of the treatment), not a lack of effort.'",
  "'Please don't argue with an unusual belief or try to prove it wrong — and don't agree with it either. Acknowledge how she feels: \"That sounds frightening. Let's get you somewhere quiet.\"'",
  "'If you notice the early signs we agreed — less sleep, becoming suspicious, saying odd things, withdrawing — tell the key person the same day. Early is what counts.'",
  "'Language matters in the staffroom and the classroom. \"Psycho\" and \"schizo\" as jokes are part of why young people hide symptoms.'",
  "'If she ever talks about harming herself or someone else, that's the same-day route — go straight to the DLP/principal and the parents are contacted.'",
 ],
 "explain_child": [
  "YOUNGER (for a child who has described a voice or unusual experience): 'Thank you for telling me. Lots of children sometimes hear or see things other people don't. It's good to tell a grown-up. I'm going to talk to your mum/dad so a doctor can help work out what's happening and help you feel less worried.'",
  "OLDER: 'What you're describing sounds really hard. I can't tell you what's causing it — that's something a doctor or specialist team can help with, and they help lots of young people with exactly this. I'd like to talk to your parents today so you can get that help quickly.'",
  "ASK (gently, in your own words, only as needed to act): 'Is this happening now?' 'Does it ever tell you to do things?' 'Have you had thoughts of hurting yourself or anyone else?' 'Who else knows?' — you are gathering enough to act, not assessing.",
  "AFTER DIAGNOSIS: 'What would help school feel manageable? What do you want teachers to know — and not know?' Let the young person choose the words used about them.",
  "BE HONEST ABOUT CONFIDENTIALITY: 'I can't keep this just between us, because I'm worried about you and you deserve help. I'll tell you exactly who I'm telling and why.'",
 ],
 "analogies": [
  "THE BRAIN'S VOLUME KNOB ON MEANING: 'When someone's becoming unwell, the brain can start turning up the importance of ordinary things — a look, a number plate — until everything feels like it means something. It's the meaning-making system working too hard.' Useful for parents and older teens; non-blaming, and consistent with salience accounts (Kapur, 2003) without overclaiming.",
  "THE RADIO BETWEEN STATIONS: 'Sometimes the brain picks up signals that aren't coming from outside — like a radio catching interference. It's real to the person hearing it.' Works with teachers to explain why arguing with the experience doesn't help.",
  "THE BROKEN LEG RETURN: 'You wouldn't expect someone back from a broken leg to run the 100 m on day one. Returning after an episode of psychosis is the same — a graded return, then build up.' Works with principals and year heads planning timetables.",
  "THE SMOKE ALARM FOR EARLY SIGNS: 'We agree the early signs in advance — less sleep, suspiciousness — so if the alarm sounds, everyone knows what to do.' Works for relapse planning with families and staff.",
 ],
 "language": [
  "Use 'a young person experiencing psychosis', 'hearing voices', 'unusual beliefs', 'a first episode of psychosis'. Use the diagnostic term only when the young person's clinicians have given it, and as they want it used.",
  "AVOID 'psychotic' or 'schizophrenic' as nouns or adjectives for a person, 'psycho', 'schizo', 'mad', 'lost the plot', 'split personality'.",
  "AVOID writing 'prodromal', 'at risk mental state' or 'clinical high risk' in school reports — these are clinical constructs made by specialist teams.",
  "The Hearing Voices movement (e.g. Romme & Escher, 1989) prefers 'voice-hearer' and frames voices as meaningful experiences — respect the young person's own framing while ensuring they have access to treatment.",
  "Say 'recovery', not 'burnt out' or 'never the same again'. Stigma delays help-seeking (see See Change, the Irish stigma-reduction partnership).",
 ],
 "red_flags": [
  "RED FLAG — new hallucinations, fixed unusual beliefs, disorganised speech or behaviour, or a marked unexplained change in functioning. Same-day contact with parents (or Tusla social worker) and urgent GP/CAMHS; inform your supervisor the same day.",
  "RED FLAG — voices telling the young person to harm themselves or others, suicidal thinking, or behaviour that puts them at immediate risk. " + RISK_ROUTE,
  "RED FLAG — sudden confusion, disorientation, fluctuating consciousness, severe headache, fever or seizure alongside unusual experiences. This may be MEDICAL (e.g. encephalitis, drug toxicity) — emergency medical assessment (ED/112).",
  "RED FLAG — beliefs or experiences involving abuse, or a disclosure. " + CP_ROUTE,
  "BOUNDARY — you do not diagnose psychosis or 'at risk mental state', do not conduct a psychiatric or risk assessment, and never advise on starting, stopping or changing antipsychotic medication (PSI 2.2.2).",
  "BOUNDARY — you do not 'test' beliefs, challenge voices or deliver CBT for psychosis; that is specialist clinical work.",
  "WATCH — the quiet decline: withdrawal, falling grades and oddness read as 'teenage laziness' or drug use. Early recognition is the most useful thing a school system can offer.",
 ],
 "child_voice": [
  "'MY THOUGHTS ABOUT SCHOOL' (NEPS) — after diagnosis, when the young person is well enough, to plan return and adjustments. Not a screening tool for symptoms. → https://www.gov.ie/en/publication/52ee2-neps-resources-and-publications/",
  "SCALING (0–10) FOR ENERGY AND COPING across the school week — gives a review measure the young person controls and flags when to ease demands.",
  "DAY MAPPING — green/amber/red timetable to design a graded return with the young person, not for them.",
  "'WHAT I WANT STAFF TO KNOW / NOT KNOW' — the young person drafts the staff information note. Good because stigma fear is often the biggest barrier to return.",
  "RELAPSE SIGNS IN THEIR OWN WORDS — with the treating team's agreement, the young person names their own early signs and what they want adults to do. Owning the plan improves engagement.",
 ],
 "questions": [
  "Q: (teacher) 'He says he hears his name being called when no one's there. Should I be worried?' — A: 'It's worth taking seriously and kindly. Many young people have experiences like this and most don't have a serious illness — but we don't guess. I'll talk to him and his parents today and suggest a GP visit. If he mentions harming himself or anyone else, that's the same-day route.'",
  "Q: (parent) 'Is it schizophrenia?' — A: 'I can't say, and it would be wrong for me to guess. There are many possible causes, some quite simple. A doctor, and then specialist services if needed, can work that out. What I can say is that getting it looked at early is the right thing.'",
  "Q: (parent) 'Did smoking weed cause this?' — A: 'Cannabis, especially strong cannabis used often, is linked to a higher risk of psychosis for some young people. It's rarely the whole story. His team can talk it through with him properly.'",
  "Q: (principal) 'Is she safe to be in school?' — A: 'That's a question for her clinical team, and I'd ask them with the family's consent. Most young people recovering from psychosis are no risk to others; what we plan for is her wellbeing, her workload and what we do if early signs come back.'",
  "Q: (young person) 'Will I be able to do my Leaving Cert?' — A: 'Lots of young people do, sometimes on a different timeline. We can look at what supports might be possible and plan your return step by step. Your health comes first, and the options don't close.'",
  "Q: (teacher) 'Should I play along with what she believes so she stays calm?' — A: 'No need to agree or argue. Acknowledge the feeling — \"that sounds really scary\" — and help her get somewhere quiet and to the key person.'",
  "Q: 'Should the EP do a cognitive assessment now?' — A: 'Not during an acute episode. When she's stable and the team agrees, an educational picture can help plan supports — and scores taken soon after an episode should be read cautiously.'",
 ],
 "supervision": [
  "Know the route BEFORE you need it: ask your supervisor who to call for an urgent CAMHS consultation locally, what the out-of-hours route is, and whether there is an early intervention in psychosis team for your area and age group.",
  "Bring any report of voices or unusual beliefs, even if you acted and it settled — ask how to weigh psychotic-like experiences against risk.",
  "Bring your wording: check a report or letter describing unusual experiences for accuracy, neutrality and stigma-free language.",
  "Ask how the service supports a return-to-school plan after an inpatient admission, and how to liaise with the hospital school.",
  "Bring your own response — fear, uncertainty, or the pull to reassure. CORU 5.45 applies.",
 ],
 "reflection": [
  "ON SPEED — Did I act the same day, or did I wait for the next visit or for supervision before calling the parents?",
  "ON LANGUAGE — Did my notes and report describe what I saw and heard, or did I reach for a label?",
  "ON THE DIFFERENTIAL — Did I hold trauma, autism, anxiety, substances, sleep and medical causes in mind — and leave the decision to clinicians?",
  "ON STIGMA — Did my own reaction, or the school's, show fear? What did I do about it?",
  "ON THE RETURN — Was the young person the author of their return plan?",
  "WHAT GOOD LOOKS LIKE: 'The year head told me a pupil had become withdrawn and said her phone was being used to watch her. I met her with the year head, listened, didn't challenge the belief, asked about safety, and rang her father the same day; he took her to the GP that evening. My note records her words and the change in grades. I informed my supervisor that afternoon.'",
  "WHAT POOR LOOKS LIKE: 'Pupil may be in prodromal phase of schizophrenia. Recommend monitoring and review next term.' — a diagnosis the EP cannot make, stigmatising language, and a delay that could cost the young person months of untreated illness.",
 ],
 "citations": [
  CIT_DSM,
  CIT_ICD,
  "National Institute for Health and Care Excellence. (2013, updated 2016). Psychosis and schizophrenia in children and young people: Recognition and management (Clinical guideline CG155). https://www.nice.org.uk/guidance/cg155 — check for updates.",
  "Health Service Executive. (2019). Early intervention in psychosis: Model of care. HSE National Clinical Programme for Early Intervention in Psychosis. — check title and current version.",
  "Kelleher, I., Connor, D., Clarke, M. C., Devlin, N., Harley, M., & Cannon, M. (2012). Prevalence of psychotic symptoms in childhood and adolescence: A systematic review and meta-analysis of population-based studies. Psychological Medicine, 42(9), 1857–1863.",
  "Kelleher, I., Corcoran, P., Keeley, H., et al. (2013). Psychotic symptoms and population risk for suicide attempt: A prospective cohort study. JAMA Psychiatry, 70(9), 940–948. — check full author list.",
  "Kapur, S. (2003). Psychosis as a state of aberrant salience: A framework linking biology, phenomenology, and pharmacology in schizophrenia. American Journal of Psychiatry, 160(1), 13–23.",
  "Romme, M. A. J., & Escher, A. D. M. A. C. (1989). Hearing voices. Schizophrenia Bulletin, 15(2), 209–216.",
  "Fusar-Poli, P., Bonoldi, I., Yung, A. R., Borgwardt, S., Kempton, M. J., Valmaggia, L., Barale, F., Caverzasi, E., & McGuire, P. (2012). Predicting psychosis: Meta-analysis of transition outcomes in individuals at high clinical risk. Archives of General Psychiatry, 69(3), 220–229.",
  "Marshall, M., Lewis, S., Lockwood, A., Drake, R., Jones, P., & Croudace, T. (2005). Association between duration of untreated psychosis and outcome in cohorts of first-episode patients: A systematic review. Archives of General Psychiatry, 62(9), 975–983.",
  "Moore, T. H. M., Zammit, S., Lingford-Hughes, A., Barnes, T. R. E., Jones, P. B., Burke, M., & Lewis, G. (2007). Cannabis use and risk of psychotic or affective mental health outcomes: A systematic review. The Lancet, 370(9584), 319–328.",
  "Di Forti, M., Quattrone, D., Freeman, T. P., et al. (2019). The contribution of cannabis use to variation in the incidence of psychotic disorder across Europe (EU-GEI): A multicentre case-control study. The Lancet Psychiatry, 6(5), 427–436.",
 ],

 "pathway": {
  "age": "Most first episodes arise from mid-to-late adolescence into the twenties; onset before 13 is rare. In schools it is usually noticed in senior cycle or at third level, often after months of withdrawal and falling grades, or suddenly when a young person discloses voices or frightening beliefs.",
  "who_diagnoses": "Ireland: CAMHS consultant psychiatrist and team for under-18s (with inpatient CAMHS units for acute care); HSE Early Intervention in Psychosis teams where available (check local age range); adult mental health services from 18. GP is the usual gateway; ED for emergencies. The EP never diagnoses.",
  "who_wrote_report": "CAMHS consultant psychiatrist or team; inpatient CAMHS unit discharge summary; EIP team; adult psychiatry for older students; private psychiatrist. A school rating scale or SDQ is not an assessment of psychosis.",
  "refer_to": "SAME DAY: parents/guardians (or Tusla social worker) → GP urgently, or CAMHS if already open; ED or 112/999 if immediate risk or confusion. Afterwards: liaison with CAMHS/EIP (with consent) for return-to-school planning; hospital school where admitted; SEC/school for exam arrangements. Not Jigsaw.",
  "sooner": "'Psychosis often starts so gradually that it looks like ordinary teenage change — families and schools very commonly only see it looking back. You've noticed now, and acting now is what counts.'",
 },
 "differential": [
  "PSYCHOTIC-LIKE EXPERIENCES WITHOUT DISORDER — common in children, often transient; still warrant a kind conversation, a risk question and a GP route where distressing.",
  "TRAUMA / PTSD / DISSOCIATION — intrusive memories, voices linked to an abuser, dissociative experiences.",
  "AUTISM — literal or idiosyncratic descriptions, intense interests, social withdrawal; can co-occur with psychosis.",
  "MOOD DISORDERS WITH PSYCHOTIC FEATURES — bipolar mania or severe depression (see the Bipolar row).",
  "SUBSTANCE OR MEDICATION EFFECTS — cannabis, stimulants, hallucinogens, some prescribed medicines.",
  "MEDICAL CAUSES — epilepsy, encephalitis (including autoimmune), delirium, metabolic disorders; sleep-related hallucinations on falling asleep or waking.",
  "OCD — intrusive thoughts recognised as the person's own, versus voices experienced as external.",
 ],
 "next": [
  "Act the same day: parents (or social worker), urgent GP/CAMHS, ED/112 if risk; inform your supervisor.",
  "Record exactly what the young person said and what was observed, dated, without interpretation.",
  "Once the young person is under care, obtain consent to liaise with the treating team.",
  "Plan a graded return at School Support Plus with the young person, family and team; review early and often.",
 ],
 "presentations": [
  "Hearing voices / unusual perceptual experiences",
  "Unusual or fixed beliefs (suspiciousness, paranoia)",
  "Psychotic-like experiences in childhood",
  "Marked decline in functioning and withdrawal in adolescence",
  "Disorganised speech or behaviour",
  "Return to school after psychiatric admission",
  "Cannabis use and mental health",
  "Reduced timetable and graded return",
 ],

 "bands": {
  "Early Years": {
   "applies": "N/A — psychotic disorders are not diagnosed at this age in ordinary practice",
   "prevalence": "Not applicable — imaginary companions and fantasy play are developmentally normal.",
   "see": "Vivid imagination, imaginary friends and magical thinking are typical. Any concern about hallucination-like behaviour in a young child is a medical question (e.g. seizures, illness, medication) — GP/paediatrics — and a context question (safety at home).",
   "tools": []},
  "School Age": {
   "applies": "RARELY — very early-onset psychosis is rare; psychotic-like experiences are common and usually transient",
   "prevalence": "Psychotic-like experiences median about 17% at 9–12 (Kelleher et al., 2012) — check; psychotic disorder rare, rate not stated here.",
   "see": "A child describing voices or frightening beliefs, often with anxiety, trauma or sleep problems. Kind conversation, a risk question, same-day contact with parents and GP. Consider trauma, autism and medical causes — for clinicians to weigh.",
   "tools": []},
  "Adolescent": {
   "applies": "YES — onset begins to rise in mid-to-late adolescence",
   "prevalence": "Early-onset psychotic disorder uncommon — rate not stated here, check; psychotic-like experiences about 7.5% at 13–18 (Kelleher et al., 2012) — check.",
   "see": "Months of withdrawal, falling grades, suspiciousness, odd beliefs, sleep change and loss of drive, sometimes with cannabis use; or an abrupt disclosure. Same-day route to GP/CAMHS; later, a graded return plan with the treating team. No school measure assesses psychosis.",
   "tools": ["SDQ"]},
  "Young Adult": {
   "applies": "YES — peak age of onset for first-episode psychosis",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "First episodes during Leaving Cert, further education, college or work. EIP / adult mental health via GP; the EP role is educational — disability support services, deferral and return planning — never clinical.",
   "tools": ["Adult self-report measures via the service"]},
  "Special Setting": {
   "applies": "RARELY — but under-recognised where communication is limited; higher risk in 22q11.2 deletion syndrome",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Change from the pupil's own baseline: new fearfulness, responding to unseen stimuli, loss of skills, sleep change. Rule out pain, illness, epilepsy and medication effects first via GP/paediatrics; Mental Health of Intellectual Disability (MHID) teams where available — check local arrangements.",
   "tools": ["Functional behaviour assessment (ABC)"]},
 },
},

# ---------------------------------------------------------------------------------------------------------------
{
 "name": "Bipolar and related disorders (Bipolar I, Bipolar II, Cyclothymic Disorder)",
 "code": ("DSM-5-TR Bipolar and Related Disorders (Bipolar I Disorder, Bipolar II Disorder, Cyclothymic Disorder, "
          "substance/medication-induced, due to another medical condition, other specified/unspecified) · ICD-11 "
          "6A60 Bipolar type I, 6A61 Bipolar type II, 6A62 Cyclothymic disorder — check codes before quoting"),
 "neps": "5. OTHER (5.5 Involvement of other services) — and 3. EMOTIONAL (3.4 Mood · 3.7 Risk and safeguarding)",
 "coru": CORU,
 "psi":  PSI,
 "law":  "Children First Act 2015 · Mental Health Act 2001 (a matter for clinicians and courts, not the EP) · EPSEN Act 2004 · Equal Status Acts 2000–2018 · Disability Act 2005 · GDPR",

 "what_it_is": [
  "A group of mood disorders defined by EPISODES of abnormally elevated, expansive or irritable mood with increased energy — MANIA or HYPOMANIA — usually alternating with episodes of depression (APA, 2022, DSM-5-TR). The episodes are a CHANGE from the person's usual self.",
  "BIPOLAR I: at least one MANIC episode — at least one week (or any duration if hospitalisation is needed), with marked impairment, sometimes psychotic features. Depressive episodes are common but not required (APA, 2022).",
  "BIPOLAR II: at least one HYPOMANIC episode (at least four days, a clear change noticed by others, but not severe enough to cause marked impairment) AND at least one major depressive episode. Not a 'milder' disorder — the depressive burden can be heavy (APA, 2022).",
  "CYCLOTHYMIC DISORDER: numerous periods of hypomanic and depressive symptoms that do not meet full episode criteria, for at least two years in adults or ONE year in children and adolescents (APA, 2022).",
  "KEY SYMPTOMS OF MANIA/HYPOMANIA: inflated self-esteem or grandiosity; DECREASED NEED FOR SLEEP (feeling rested after very little — different from insomnia); pressured speech; racing thoughts; distractibility; increased goal-directed activity or agitation; risky behaviour (spending, sexual, driving). Clinicians look at the FIND features — Frequency, Intensity, Number and Duration — to separate episodes from ordinary exuberance (Kowatch et al., 2005).",
  "TREATMENT is specialist and usually combines medication (a psychiatrist's decision — never the EP's), psychoeducation, family-focused therapy and attention to sleep and routine (NICE, 2014, CG185 — check for updates, which includes a section on children and young people). The EP never advises on mood stabilisers, antipsychotics or antidepressants (PSI 2.2.2).",
  "FOR THE EP the task is to recognise a possible episode, act on risk the same day, avoid mislabelling, and help school adapt around a long-term, episodic condition — attendance, workload, exams, sleep and relapse signs.",
 ],
 "what_it_is_not": [
  "NOT mood swings. Everyone's mood varies within a day; adolescents' more so. Bipolar disorder involves distinct EPISODES lasting days to weeks, with a clear change from baseline and associated symptoms (sleep, energy, thinking), not reactive shifts within hours.",
  "NOT chronic irritability and temper outbursts. After US rates of paediatric bipolar diagnosis rose sharply (Moreno et al., 2007 reported a roughly 40-fold rise in US outpatient visits with the diagnosis between 1994–95 and 2002–03 — check before quoting), research suggested many of these children had chronic, non-episodic irritability (Leibenluft, 2011). DSM-5 introduced DISRUPTIVE MOOD DYSREGULATION DISORDER partly in response (APA, 2013/2022). See the DMDD row.",
  "NOT a settled diagnosis in young children. Whether and how bipolar disorder presents before adolescence remains debated; UK and European practice diagnoses it in children far less often than historically in the US. Hedge any statement about 'paediatric bipolar' and defer to the treating psychiatrist.",
  "NOT ADHD. ADHD is chronic and present from early childhood; bipolar is episodic, with a change from baseline. Both can involve distractibility and talkativeness; decreased need for sleep, grandiosity and elation that are episodic point away from ADHD (Geller et al., 2002; Kowatch et al., 2005). They can co-occur — a psychiatric judgement.",
  "NOT 'creative genius' or a character trait. Romanticising mania minimises the risk: mania can involve dangerous behaviour, exploitation and severe consequences, and bipolar disorder carries a raised suicide risk (APA, 2022).",
  "NOT something a questionnaire in school can identify. Parent-report mania rating scales exist for clinical use, but no school-administered measure diagnoses bipolar disorder.",
 ],
 "prevalence": [
  "ADULTS: DSM-5-TR reports 12-month prevalence of Bipolar I of around 0.6% in the US and lower cross-nationally, and Bipolar II of around 0.8% in the US — check figures in DSM-5-TR before quoting (APA, 2022).",
  "YOUTH: Van Meter, Moreira and Youngstrom (2011) meta-analysed community studies and reported a pooled rate of around 1.8% for the bipolar SPECTRUM in young people, with much lower rates for Bipolar I, and no significant difference between US and non-US samples — check before quoting.",
  "AGE OF ONSET: DSM-5-TR gives a mean age of onset of the first manic, hypomanic or major depressive episode for Bipolar I of about 18 years; onset before adolescence is uncommon (APA, 2022) — check before quoting.",
  "IRELAND: no national child or adolescent figure stated here — check before quoting.",
  "SEX RATIO: Bipolar I roughly equal between sexes; Bipolar II may be more common in females in some clinical samples (APA, 2022) — check.",
  "HIGHER RISK: a first-degree relative with bipolar disorder is the strongest known risk factor — children of parents with bipolar disorder have raised rates of mood disorders (e.g. Birmaher et al., 2009) — rates not stated here, check.",
 ],
 "cooccurring": [
  {"name": "ADHD", "rate": "commonly reported in youth bipolar samples — rate not stated here, check",
   "presents": "chronic inattention and hyperactivity with superimposed episodes of mood and sleep change. Separate the baseline from the episode; clinicians decide."},
  {"name": "ANXIETY DISORDERS", "rate": "common — rate not stated here, check",
   "presents": "worry, panic and social anxiety between episodes; can be the first presenting difficulty."},
  {"name": "DEPRESSION AND SUICIDAL THINKING", "rate": "depressive episodes are often the first episode; suicide risk elevated (APA, 2022) — rate not stated here, check",
   "presents": "the first episode is often depressive, so a young person may be treated as unipolar depression until a (hypo)manic episode appears. Ask about risk every time."},
  {"name": "SUBSTANCE USE", "rate": "elevated — rate not stated here, check",
   "presents": "alcohol and cannabis use during episodes or to manage sleep and mood; worsens course. Ask non-judgementally."},
  {"name": "PSYCHOTIC FEATURES", "rate": "can occur during severe manic or depressive episodes — rate not stated here, check",
   "presents": "grandiose or paranoid beliefs, hallucinations during an episode. Emergency route (see the Psychotic disorders row)."},
  {"name": "LEARNING AND ATTAINMENT DISRUPTION", "rate": "common — rate not stated here, check",
   "presents": "lost weeks during episodes, reduced concentration between them, medication effects on energy and thinking. Plan for interruptions rather than treat each one as a crisis."},
  {"name": "BEHAVIOUR AND RISK-TAKING DURING EPISODES", "rate": "common in mania — rate not stated here, check",
   "presents": "disinhibition, sexualised behaviour, spending, conflict with authority. Can create exploitation risk; keep safeguarding in view."},
 ],
 "recommendations": [
  "IF YOU SUSPECT AN EPISODE: describe and act. Speak to parents (or Tusla social worker) the same day about what you have seen — especially reduced need for sleep, a marked change in energy and speech, grandiose plans, risky behaviour or low mood with hopelessness — and advise urgent GP/CAMHS review. Risk → same-day route. Inform your supervisor.",
  "WRITE CHANGE FROM BASELINE: 'Over the past ten days, staff report she has been talking rapidly, sleeping two to three hours a night by her account, and planning to start several businesses; this is a marked change from her usual presentation.' Never 'appears bipolar' or 'manic'.",
  "AFTER A DIAGNOSIS (with consent): a school plan built with the young person, family and treating team — early warning signs, what staff do, whom they tell, and how work is scaled back during and after an episode. Review each term and after any episode.",
  "PROTECT SLEEP AND ROUTINE where school can: avoid scheduling that pushes late nights (e.g. overnight trips, late-evening events) without planning; note that exam periods and transitions are known stress points. Regular routine is a core part of self-management in clinical guidance (NICE, 2014, CG185 — check).",
  "FLEXIBILITY ACROSS EPISODES: agreed options for reduced workload, extended deadlines, catch-up plans and a quiet base. A reduced timetable, if used, should be short, reviewed and follow current Department guidance — check.",
  "MEDICATION EFFECTS: tiredness, thirst and frequent toilet trips, weight change or tremor may be noticed in school. Staff should allow water and toilet access and tell parents what they notice; they do not comment on or advise about medication.",
  "STATE EXAMINATIONS: raise RACE eligibility and other SEC options with the school early — do not promise.",
  "CONTINUUM LEVEL: School Support Plus — CAMHS or adult psychiatry will be involved. Name the level.",
  "REFER: urgent GP/CAMHS for a suspected episode; ED/112 if immediate risk; CAMHS for under-18s, adult mental health services from 18 via GP. Jigsaw is not the route for suspected mania or bipolar disorder.",
  "DO NOT diagnose, suggest bipolar disorder to parents as a likely explanation, relabel ADHD or DMDD as bipolar (or the reverse), or advise on medication (PSI 2.2.2).",
 ],
 "explain_parent": [
  "'I've noticed some real changes in him over the past week or so — sleeping very little but not tired, talking fast, making big plans. I'm not able to say what's causing it, but changes like this should be looked at by a doctor soon. Can you see the GP in the next day or two?'",
  "'Lots of things can cause changes in mood and energy, including stress, sleep problems, substances and illness. A doctor needs to work that out — please don't search for a label online in the meantime.'",
  "'If he talks about hurting himself, or does something that puts him in danger, go to the Emergency Department or call 112 or 999.'",
  "AFTER A DIAGNOSIS: 'This is a condition that comes in episodes, with long stretches of being well in between. School can plan for the episodes — we'll agree what early signs to look for and what we'll do — so each one isn't a crisis.'",
  "IF THE PARENT HAS BIPOLAR DISORDER (and has told you): 'You'll know better than anyone what an early sign looks like. What would you want school to notice?' Be careful not to assume the child will have it.",
  "SIGNPOST: GP; CAMHS; Aware (depression and bipolar disorder support, including family programmes — check current offer); Shine; Mental Health Ireland — check current services.",
 ],
 "explain_teacher": [
  "'This is a mood condition that comes in episodes. Between episodes she may be completely herself. During one, her energy, sleep and thinking change, and she may not see it.'",
  "'The early signs we've agreed are: less sleep but not tired, talking faster, big new plans, or pulling right back and going flat. If you see them, tell the key person that day.'",
  "'During a high period, keep instructions short and calm, avoid getting into debates, and give her a place to go. During a low period, reduce the demand and check in.'",
  "'Medication can make her tired and thirsty and need the toilet more. Please allow it without fuss — and let us know what you notice, rather than commenting to her.'",
  "'Please don't talk about being \"so bipolar\" about the weather or anyone's mood. It's a serious condition, and casual use makes it harder for young people to tell anyone.'",
  "'If she ever says something about harming herself, or is doing something risky, that's the same-day route — straight to the DLP/principal.'",
 ],
 "explain_child": [
  "YOUNGER (rare — only once a clinician has explained a diagnosis): 'Sometimes your body and brain get lots of energy, so you can't sleep and your thoughts go really fast. Other times you feel very low. Your doctors are helping with that, and school will help too.'",
  "OLDER: 'Bipolar disorder means your mood and energy can go into episodes — very high, or very low — that are different from your usual self. It's common, treatable, and lots of people learn to spot their own early signs and manage it. What would help school fit around that?'",
  "ASK: 'How have you been sleeping?' 'Have your thoughts felt faster or slower than usual?' 'Have you felt like you don't need sleep?' 'Have you had thoughts of hurting yourself?' — enough to act, not to assess.",
  "INVOLVE THEM IN THE PLAN: 'What are your early signs? What do you want teachers to do — and not do — if they notice?' Ownership improves engagement.",
  "CONFIDENTIALITY: 'If I'm worried about your safety I'll need to tell someone — your parents, and people who can help — and I'll tell you first.'",
 ],
 "analogies": [
  "THE THERMOSTAT: 'Most people's mood thermostat keeps things in a comfortable range. In bipolar disorder, the thermostat can drift too high or too low for a while, and needs help to reset.' Works with parents and older teens.",
  "THE ACCELERATOR AND BRAKE: 'In a high episode, the accelerator is floored and the brakes are weak — ideas, energy and risk all speed up.' Works with teachers to explain why reasoning in the moment doesn't work.",
  "THE WEATHER FORECAST: 'We can't stop the weather, but we can learn the signs a storm is coming and plan for it.' Works for relapse-signature planning with young people and schools.",
  "THE ADHD vs BIPOLAR CLIMATE vs WEATHER: 'ADHD is the climate — always there. A mood episode is the weather — it comes and goes.' Works with teachers confused by overlapping behaviour; keep it as an explanation, not a diagnostic test.",
 ],
 "language": [
  "Use 'a young person with bipolar disorder', 'a mood episode', 'a period of elevated mood' or 'a depressive episode'. Avoid 'bipolar' as a noun for a person ('a bipolar') and 'manic' or 'mental' as insults.",
  "Avoid casual use — 'the weather's so bipolar', 'I'm a bit OCD/bipolar today'. It trivialises and stigmatises.",
  "In reports, describe change from baseline (sleep, energy, speech, activity, mood) with dates; do not write 'manic' or 'hypomanic' unless quoting a clinician's diagnosis.",
  "When a clinician has given a diagnosis, use their exact terms (Bipolar I, Bipolar II, cyclothymic disorder) and attribute it.",
 ],
 "red_flags": [
  "RED FLAG — suicidal thinking, self-harm or hopelessness, including during or after a high period (mixed states and the crash after mania are high-risk). " + RISK_ROUTE,
  "RED FLAG — signs of mania: little or no sleep without tiredness, rapid speech, grandiose plans, reckless or dangerous behaviour, psychotic features. Same-day contact with parents (or social worker) and urgent GP/CAMHS; ED/112 if at immediate risk.",
  "RED FLAG — sexual disinhibition, older contacts, or exploitation risk during an episode. " + CP_ROUTE,
  "RED FLAG — a young person on treatment who suddenly seems very unwell, confused, vomiting or with marked tremor — tell parents immediately and advise urgent medical review (medication effects are a medical matter).",
  "BOUNDARY — you do not diagnose bipolar disorder, decide whether it is ADHD or DMDD instead, or advise on medication (PSI 2.2.2).",
  "WATCH — the depressed young person who has 'never been this well' after an antidepressant starts, or who describes past periods of not needing sleep. Tell parents and the prescriber's team via the family; do not interpret.",
 ],
 "child_voice": [
  "'MY THOUGHTS ABOUT SCHOOL' (NEPS) — when well, to plan support and understand what helps. → https://www.gov.ie/en/publication/52ee2-neps-resources-and-publications/",
  "MOOD AND SLEEP DIARY (as agreed with the treating team) — the young person's own record of mood, energy and sleep; school can support without taking ownership. Good because it builds self-monitoring, which is central to self-management.",
  "RELAPSE SIGNATURE IN THEIR WORDS — 'my early signs' and 'what I want adults to do', written by the young person with their team, shared with key staff.",
  "SCALING (0–10) FOR ENERGY AND COPING at check-ins — a simple, non-intrusive measure the key adult can use.",
  "'WHAT I WANT STAFF TO KNOW / NOT KNOW' — privacy and control over the story matter a great deal to adolescents with a psychiatric diagnosis.",
 ],
 "questions": [
  "Q: (parent) 'I read that ADHD kids are often really bipolar. Could that be him?' — A: 'That idea was more common in the US some years ago and has been widely questioned since. ADHD is there all the time from early childhood; bipolar disorder comes in episodes. Only a psychiatrist can sort that out — if you have concerns, bring them to your GP or his CAMHS team.'",
  "Q: (teacher) 'She's up one minute and down the next — is that bipolar?' — A: 'Mood changes within a day are common, especially in teenagers. Bipolar disorder is about episodes lasting days or weeks, with big changes in sleep and energy too. I wouldn't use the word — but if you're worried about her, let's describe what you're seeing and talk to her parents.'",
  "Q: (parent) 'Is DMDD just a new name for childhood bipolar?' — A: 'No — it was introduced partly because many children being called bipolar actually had long-lasting irritability and outbursts rather than episodes. They're different conditions, and a psychiatrist decides which fits.'",
  "Q: (principal) 'Can he go on the school tour?' — A: 'Probably, with planning. Sleep disruption can be a trigger, so it's worth agreeing a plan with him, his parents and his team — sleeping arrangements, medication times, who to contact.'",
  "Q: (young person) 'Will I always have to take medication?' — A: 'That's a really important question for your psychiatrist — I'm not the right person to answer it. What I can do is help school work with whatever plan you and your team agree.'",
  "Q: (teacher) 'He's been brilliant this week — full of energy and ideas. That's good, isn't it?' — A: 'It might be. If it's a real change from his usual self, especially with less sleep, it's worth mentioning to the key person — for someone with his diagnosis, that can be an early sign.'",
 ],
 "supervision": [
  "Bring any case where a family or professional has used 'bipolar' for a child, especially a pre-adolescent, and ask how your supervisor responds without contradicting a clinician or colluding with a mislabel.",
  "Ask about the local route for urgent CAMHS review and the out-of-hours route.",
  "Bring an ADHD/DMDD/bipolar question where the history is unclear — practise describing episodes versus baseline in writing.",
  "Ask how the service supports school plans for young people with episodic psychiatric conditions and how liaison with CAMHS works in practice.",
  "Bring your own response — anxiety about risk, or the temptation to 'spot' a diagnosis. CORU 5.45.",
 ],
 "reflection": [
  "ON LABELS — Did I use 'bipolar', 'manic' or 'high' loosely in notes or conversation?",
  "ON THE DIFFERENTIAL — Did I describe episodes versus baseline clearly enough for a clinician to use? Did I keep ADHD, DMDD, substance use and trauma in view without deciding between them?",
  "ON RISK — Did I ask directly about suicidal thinking, including after a high period?",
  "ON THE BOUNDARY — Was I asked about medication? What did I say?",
  "ON THE YOUNG PERSON — Were they the author of their early-warning plan?",
  "WHAT GOOD LOOKS LIKE: 'A year head reported a pupil sleeping very little and talking about grand plans. I met the pupil with the year head, asked about sleep and safety, rang her mother the same day, and wrote a dated note of the changes from baseline for the GP. After CAMHS confirmed a diagnosis, the pupil wrote her own early-signs plan with her key teacher.'",
  "WHAT POOR LOOKS LIKE: 'Pupil presents with bipolar tendencies — recommend mood stabiliser review.' — a diagnosis the EP cannot make, a medication recommendation outside PSI 2.2.2, and no action on risk.",
 ],
 "citations": [
  CIT_DSM,
  CIT_ICD,
  "National Institute for Health and Care Excellence. (2014, updated). Bipolar disorder: Assessment and management (Clinical guideline CG185). https://www.nice.org.uk/guidance/cg185 — check for updates.",
  "Van Meter, A. R., Moreira, A. L. R., & Youngstrom, E. A. (2011). Meta-analysis of epidemiologic studies of pediatric bipolar disorder. Journal of Clinical Psychiatry, 72(9), 1250–1256.",
  "Moreno, C., Laje, G., Blanco, C., Jiang, H., Schmidt, A. B., & Olfson, M. (2007). National trends in the outpatient diagnosis and treatment of bipolar disorder in youth. Archives of General Psychiatry, 64(9), 1032–1039.",
  "Leibenluft, E. (2011). Severe mood dysregulation, irritability, and the diagnostic boundaries of bipolar disorder in youths. American Journal of Psychiatry, 168(2), 129–142.",
  "Kowatch, R. A., Fristad, M., Birmaher, B., Wagner, K. D., Findling, R. L., Hellander, M., & the Child Psychiatric Workgroup on Bipolar Disorder. (2005). Treatment guidelines for children and adolescents with bipolar disorder. Journal of the American Academy of Child and Adolescent Psychiatry, 44(3), 213–235.",
  "Geller, B., Zimerman, B., Williams, M., DelBello, M. P., Frazier, J., & Beringer, L. (2002). Phenomenology of prepubertal and early adolescent bipolar disorder: Examples of elated mood, grandiose behaviors, decreased need for sleep, racing thoughts and hypersexuality. Journal of Child and Adolescent Psychopharmacology, 12(1), 3–9.",
  "Birmaher, B., Axelson, D., Monk, K., Kalas, C., Goldstein, B., Hickey, M. B., et al. (2009). Lifetime psychiatric disorders in school-aged offspring of parents with bipolar disorder: The Pittsburgh Bipolar Offspring Study. Archives of General Psychiatry, 66(3), 287–296.",
 ],

 "pathway": {
  "age": "Usually first recognised in late adolescence or early adulthood, often after one or more depressive episodes treated as unipolar depression. Pre-adolescent diagnosis is uncommon outside the US and remains debated. In schools it surfaces as a marked, episodic change in sleep, energy and behaviour, or when a diagnosed student needs a school plan.",
  "who_diagnoses": "Ireland: CAMHS consultant psychiatrist and team for under-18s; adult psychiatry from 18; GP as gateway; ED for emergencies. Private psychiatrists also. Medication is prescribed and monitored by psychiatry. The EP never diagnoses.",
  "who_wrote_report": "CAMHS consultant psychiatrist or team; inpatient unit discharge summary; adult mental health team; private psychiatrist. Older or overseas reports (especially US) may use 'paediatric bipolar' or 'bipolar NOS' for a young child — read these carefully and refer questions back to the treating clinician.",
  "refer_to": "SAME DAY for a suspected episode or risk: parents (or Tusla social worker) → urgent GP/CAMHS; ED or 112/999 if immediate risk. Planned: CAMHS liaison (with consent) for school planning; SEC/school for exam arrangements; Aware and Shine for family support. Not Jigsaw for suspected mania.",
  "sooner": "'The first episode is often depression, so it's very common for bipolar disorder to be recognised only when a high period appears later. That's how it usually goes — not a failure on anyone's part.'",
 },
 "differential": [
  "ADHD — chronic, present from early childhood, not episodic; distractibility and talkativeness overlap.",
  "DISRUPTIVE MOOD DYSREGULATION DISORDER — chronic irritability with severe outbursts, onset before 10, not episodic; DSM-5-TR does not allow both (see the DMDD row).",
  "MAJOR DEPRESSIVE DISORDER — depressive episodes without any history of (hypo)mania; the first bipolar episode is often depressive.",
  "SUBSTANCE OR MEDICATION EFFECTS — stimulants, cannabis, steroids, antidepressant-associated activation.",
  "TRAUMA, CONDUCT DIFFICULTY OR PERSONALITY DEVELOPMENT — reactive mood shifts linked to relationships and events rather than episodes.",
  "NORMAL ADOLESCENT MOOD VARIATION — short-lived, reactive, without sleep and energy change.",
 ],
 "next": [
  "If risk or a suspected episode: same-day route with parents (or social worker) and GP/CAMHS; inform your supervisor.",
  "Record change from baseline with dates — sleep, energy, speech, activity, mood.",
  "After diagnosis, with consent, co-produce a school plan with the young person, family and team at School Support Plus.",
  "Review after each episode and at key transitions (exams, trips, moving school or into third level).",
 ],
 "presentations": [
  "Episodic change in energy and sleep",
  "Elevated or expansive mood out of character",
  "Irritability (see DMDD and depression rows)",
  "Low mood and depressive episodes",
  "Risk-taking and disinhibition",
  "Return to school after psychiatric admission",
  "Medication side effects noticed in school",
 ],

 "bands": {
  "Early Years": {
   "applies": "N/A — bipolar disorder is not diagnosed at this age in ordinary practice",
   "prevalence": "Not applicable — high energy, tantrums and mood variability are developmentally normal.",
   "see": "Exuberance, tantrums and rapid mood change are typical of young children. Severe or persistent dysregulation is a question for Primary Care, paediatrics or CAMHS about development, sleep, language and family context — not a bipolar question.",
   "tools": []},
  "School Age": {
   "applies": "RARELY — pre-adolescent bipolar disorder is uncommon and its diagnosis contested",
   "prevalence": "Rate not stated here — Van Meter et al. (2011) pooled youth estimates are mostly adolescent; check before quoting.",
   "see": "Chronic irritability and outbursts are far more likely to be DMDD, ADHD, anxiety, trauma or language difficulty. Describe patterns over time, note any true episodic change in sleep and energy, and refer via GP/CAMHS; do not suggest bipolar disorder to families.",
   "tools": ["SDQ", "BASC-3"]},
  "Adolescent": {
   "applies": "YES — onset becomes more likely from mid-adolescence",
   "prevalence": "Bipolar spectrum around 1.8% in pooled youth community samples, much lower for Bipolar I (Van Meter et al., 2011) — check before quoting.",
   "see": "Depressive episodes, sometimes followed by periods of reduced need for sleep, rapid speech, grandiosity and risk-taking; attendance and attainment disrupted by episodes. Same-day route for suspected mania or risk; after diagnosis, a co-produced school plan. Mood screens do not detect bipolar disorder.",
   "tools": ["MFQ (Mood and Feelings Questionnaire)", "RCADS self-report", "BASC-3 SRP"]},
  "Young Adult": {
   "applies": "YES — common age of first recognition",
   "prevalence": "Mean age of onset around 18 for Bipolar I (APA, 2022) — check before quoting.",
   "see": "Episodes around Leaving Cert, college entry or work, often with sleep disruption and alcohol. Adult mental health via GP; the EP role is educational — disability services, deferral, exam and return planning.",
   "tools": ["Adult self-report measures via the service"]},
  "Special Setting": {
   "applies": "RARELY — and hard to identify where communication is limited",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Cyclical change from the pupil's own baseline — periods of reduced sleep, increased activity or distress alternating with withdrawal — recorded carefully over time. Rule out pain, illness, epilepsy and medication effects via GP/paediatrics; MHID teams where available — check.",
   "tools": ["Functional behaviour assessment (ABC)", "Vineland-3 / ABAS-3"]},
 },
},
]
