# CONDS batch c12 — rare, psychiatry-diagnosed conditions: hoarding and the impulse-control disorders.
# 1 Hoarding Disorder · 2 Intermittent Explosive Disorder · 3 Pyromania and Kleptomania
# Context: Reference Part D — 3. EMOTIONAL (3.3 Obsessive-compulsive and related) for hoarding;
# 2. BEHAVIOUR (2.1 / 2.2) for IED, pyromania and kleptomania, all bands.
# Stance throughout: these are rare in children and diagnosed by psychiatry. The behaviour (collecting,
# outbursts, fire-setting, stealing) is common; the disorder is not. Formulate first. PSI 2.2.2.

NEPS_BEH = "2. BEHAVIOUR (2.1 Behaviour in class · 2.2 Behaviour during break times and around the school)"
CORU = "3.1 · 3.2 · 3.4 · 3.10 · 3.12 · 5.28 · 5.29 · 5.30 · 5.31 · 5.32 · 5.34"
PSI = "2.2.2 · 2.2.4 · 2.3.1 · 1.3.1 · 1.2.8 · 1.1.4"
LAW = ("Children First Act 2015 · Children First National Guidance (2017) · EPSEN Act 2004 · "
       "Education Act 1998 · Education (Welfare) Act 2000 · Equal Status Acts 2000–2018 · "
       "GDPR / Data Protection Act 2018")

CIT_DSM = ("American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders "
           "(5th ed., text rev.). https://doi.org/10.1176/appi.books.9780890425787")
CIT_ICD = ("World Health Organization. (2019/2022). International classification of diseases for mortality and "
           "morbidity statistics (11th revision). https://icd.who.int/ [Check the browser for current codes.]")
CIT_NEPS = ("National Educational Psychological Service. (2010). Behavioural, emotional and social difficulties: "
            "A continuum of support — Guidelines for teachers. Department of Education and Skills.")
CIT_IFF = ("Frederickson, N., & Cline, T. (2015). Special educational needs, inclusion and diversity (3rd ed.). "
           "Open University Press.")
CIT_HOLLO = ("Hollo, A., Wehby, J. H., & Oliver, R. M. (2014). Unidentified language deficits in children with "
             "emotional and behavioral disorders: A meta-analysis. Exceptional Children, 80(2), 169–186.")
CIT_SUKH = ("Sukhodolsky, D. G., Kassinove, H., & Gorman, B. S. (2004). Cognitive-behavioral therapy for anger in "
            "children and adolescents: A meta-analysis. Aggression and Violent Behavior, 9(3), 247–269.")
CIT_TUSLA = ("Department of Children and Youth Affairs. (2017). Children First: National guidance for the protection "
             "and welfare of children. Government Publications. [Check gov.ie / tusla.ie for updates.]")

CONDS = []

# ============================================================================ 1 · HOARDING DISORDER
CONDS.append({
 "name": "Hoarding Disorder",
 "code": "DSM-5-TR Hoarding Disorder (ICD-10-CM F42.3) · ICD-11 6B24 Hoarding disorder (within Obsessive-compulsive or related disorders) — check codes before quoting",
 "neps": "3. EMOTIONAL (3.3 Obsessive-compulsive and related) — and 3.7 Risk and safeguarding where home conditions are a welfare concern",
 "coru": CORU,
 "psi": PSI,
 "law": LAW + " · Housing and fire-safety matters sit with the local authority, not the school",

 "what_it_is": [
  "A DSM-5-TR diagnosis in the 'Obsessive-Compulsive and Related Disorders' chapter, first introduced as a separate disorder in DSM-5 (2013). Core feature: PERSISTENT DIFFICULTY DISCARDING or parting with possessions, regardless of their actual value, because of a perceived need to save them and distress at discarding them (American Psychiatric Association [APA], 2022).",
  "The difficulty must result in accumulation that CONGESTS AND CLUTTERS ACTIVE LIVING AREAS so that their intended use is substantially compromised — unless third parties (often parents) keep the space clear. It must cause clinically significant distress or impairment, including in keeping a safe environment (APA, 2022). Verify criterion wording before quoting.",
  "SPECIFIERS: 'with excessive acquisition' (buying, collecting free items, or taking items), and level of INSIGHT — good or fair, poor, or absent insight / delusional beliefs (APA, 2022).",
  "EXCLUSIONS matter in children: not attributable to another medical condition (DSM-5-TR names brain injury, cerebrovascular disease and Prader-Willi syndrome) and not better explained by another mental disorder — e.g. obsessions in OCD, restricted interests in autism, cognitive deficits in major neurocognitive disorder (APA, 2022).",
  "The cognitive-behavioural model (Frost & Hartl, 1996) explains hoarding through INFORMATION-PROCESSING difficulties (categorising, deciding, attention), strong EMOTIONAL ATTACHMENT to objects (safety, identity, memory), and AVOIDANCE — discarding is postponed because deciding is distressing. Each part is a formulation target.",
  "In CHILDREN the diagnosis is hard to apply: parents control the home, so the 'cluttered living areas' criterion may be met only in the child's bedroom, or masked because adults clear it. DSM-5-TR notes onset often in adolescence, with severity increasing over the lifespan — check text for detail (APA, 2022).",
  "For the EP there are usually TWO different referrals: (1) a child who cannot part with things — often within OCD, autism, anxiety or loss; and (2) a child LIVING IN a hoarded home because of a parent's difficulty. The second is far more common in school practice and is primarily a welfare, dignity and social question.",
 ],
 "what_it_is_not": [
  "NOT collecting. Collecting stickers, stones, cards or toys is developmentally ordinary and often peaks in early and middle childhood. Evans et al. (1997) showed that ritualistic, 'just right' and other compulsive-like behaviours are common in typically developing young children and decline with age. Collections are organised, displayed, enjoyed and shared; hoarding is disorganised, distressing and interferes with the use of space.",
  "NOT untidiness or 'a messy teenager'. A cluttered bedroom is not a disorder unless there is real difficulty discarding, distress when items are removed, and impairment. Ask 'what happens if someone throws something out?' — the answer separates the two.",
  "NOT simply OCD. Since DSM-5 it has been a separate disorder. Hoarding driven by obsessions (e.g. fear something bad will happen if an item is thrown out) is coded as OCD. Tolin and Villavicencio (2011) found inattention, rather than OCD symptoms, predicted core hoarding features — check wording before quoting.",
  "NOT the same as food hoarding after deprivation. Children who have experienced neglect, food insecurity or institutional care may hide or store food. That is a trauma- and need-related behaviour, not Hoarding Disorder, and it resolves with safety and predictability rather than CBT for hoarding.",
  "NOT an autistic special interest. Organised, meaningful collections linked to a passion are a strength. DSM-5-TR says hoarding is not diagnosed where it is better explained by restricted interests in autism (APA, 2022).",
  "NOT automatically neglect when a parent hoards. A cluttered home is not in itself a child protection matter. It becomes one when the child's safety, health, sleep, hygiene or development is affected. Judge on impact on the child, with Children First thresholds and supervision.",
  "NOT a reflection of poverty or culture. Crowded housing, many siblings or keeping things out of thrift are not hoarding. Check your own assumptions before describing a home.",
 ],
 "prevalence": [
  "OVERALL (adults): Postlethwaite, Kellett and Mataix-Cols (2019) meta-analysed community studies and reported a pooled prevalence of about 2.5% — check figure before quoting. DSM-5-TR gives community estimates in a similar low-single-figure range (APA, 2022).",
  "CHILDREN AND ADOLESCENTS: population prevalence of Hoarding Disorder in youth is not established — rate not stated here, check before quoting. Hoarding SYMPTOMS are more common in children with OCD (Storch et al., 2007) and in samples with ADHD or autism.",
  "AGE OF ONSET: symptoms often begin in adolescence. Grisham et al. (2006) reported onset of hoarding symptoms typically in the early teens in an adult clinical sample — check figure before quoting. Severity usually worsens with age; most people are identified in later adulthood.",
  "IRELAND: no Irish prevalence figure is stated here — check before quoting.",
  "SEX RATIO: DSM-5-TR discusses sex differences, with clinical samples often female and some community samples finding the opposite — check the current text before quoting any ratio.",
  "CHILDREN OF A PARENT WHO HOARDS: no reliable figure for how many Irish pupils live in hoarded homes — rate not stated here. Tolin et al. (2008) documented family burden, embarrassment and conflict reported by relatives who grew up in such homes.",
 ],
 "cooccurring": [
  {"name": "OBSESSIVE-COMPULSIVE DISORDER", "rate": "elevated in youth with OCD (Storch et al., 2007) — rate not stated here, check before quoting",
   "presents": "saving driven by fear or 'just right' feelings, checking bins, distress if anything is thrown out. If obsessions drive it, it is coded as OCD, not Hoarding Disorder — CAMHS decides."},
  {"name": "ADHD", "rate": "inattention linked to hoarding features (Tolin & Villavicencio, 2011) — rate not stated here, check",
   "presents": "disorganised bags and lockers, inability to sort or decide, impulsive acquisition, lost items. School organisation supports help; do not over-read clutter as a separate disorder."},
  {"name": "AUTISM", "rate": "elevated hoarding-type behaviour reported — rate not stated here, check",
   "presents": "collections tied to interests, distress at change to belongings, insistence on keeping items in place. Usually better explained by autism; describe the function."},
  {"name": "ANXIETY AND DEPRESSION", "rate": "common co-occurrence in adult samples — youth rate not stated here, check",
   "presents": "keeping items to feel safe, indecision, withdrawal, shame about home. Screen mood; ask about worry and sleep."},
  {"name": "LOSS, TRAUMA AND DEPRIVATION", "rate": "clinically recognised association — rate not stated here, check",
   "presents": "keeping belongings of a person who died or left; hiding food after neglect or care. Formulate as attachment and safety need; follow Children First where needed."},
  {"name": "PRADER-WILLI SYNDROME AND SOME GENETIC CONDITIONS", "rate": "hoarding/food-seeking is a recognised feature of Prader-Willi — check before quoting",
   "presents": "food-seeking, collecting and storing items. DSM-5-TR excludes Hoarding Disorder when attributable to this; medical team leads."},
  {"name": "CHILD LIVING IN A HOARDED HOME (parent's difficulty)", "rate": "rate not stated here — check",
   "presents": "tiredness, hygiene concerns, lost uniform or books, no quiet space for homework, never inviting friends home, embarrassment, reluctance to let adults visit. Judge impact on the child, not the house."},
 ],
 "recommendations": [
  "CLARIFY WHICH REFERRAL THIS IS. Is the concern the child's own saving behaviour, or the home environment? Write this in the first line of the formulation — they lead to different plans and different services.",
  "FORMULATE THE FUNCTION. For the child's saving: what does keeping the item do (comfort, memory, safety, avoiding a decision, completing a set)? Interactive Factors Framework (Frederickson & Cline, 2015) — learning, attention, emotion, family, loss, school system.",
  "CLASSROOM SUPPORT: practical organisation — labelled trays, a 'keep / home / bin' routine with adult help, photographs of work instead of keeping every sheet, a limited 'treasure box'. Never clear a child's space without warning or consent; that is experienced as loss and increases distress.",
  "SCHOOL SUPPORT: a named adult; a short, planned sorting slot each week; graded practice in letting go of low-value items; praise effort, not tidiness. Link to anxiety supports where anxiety drives it (NEPS, 2010 BESD continuum strategies).",
  "CHILD IN A HOARDED HOME: practical school supports without shame — a spare uniform, homework done in school, a locker for books, breakfast club, discreet access to washing facilities. Sensitive, non-judgemental contact with the parent. Consider Tusla Family Support or Meitheal (with consent).",
  "SAFEGUARDING: where the home appears to threaten the child's safety or health (blocked exits, no working bed or kitchen, infestation, fire risk, poor hygiene affecting health), follow Children First the same day: DLP, and your own mandated report to Tusla as soon as practicable.",
  "REFER: GP → CAMHS where hoarding is severe, persists, is linked to OCD or other moderate–severe mental health difficulty (check CAMHS acceptance criteria). For a parent, suggest (with sensitivity) their GP and adult mental health services — you do not treat or assess the parent. Local authority fire services may offer home fire-safety advice — check locally.",
  "CONTINUUM LEVEL: Classroom Support or School Support for most children; School Support Plus when outside services are involved or welfare concerns exist. Review dates, not 'ongoing'.",
  "DO NOT diagnose hoarding, and DO NOT describe a family's home in a school report beyond what is necessary for the child's needs (PSI 1.2.8; GDPR data minimisation). DO NOT recommend a 'big clear-out'. Evidence-based treatment works through the person's own decisions (Tolin et al., 2015); clearing without their involvement is widely reported in the hoarding literature to cause distress and re-accumulation — check before quoting.",
 ],
 "explain_parent": [
  "(Child's saving) 'Lots of children collect and keep things, and that's usually healthy. What we're noticing is that it's become really hard for her to let go of anything, and she gets upset when things are moved. We want to understand what the keeping does for her.'",
  "(Child's saving) 'Please don't clear it all out while she's at school. It can feel like losing something precious and makes the worry bigger. Small, planned steps with her in charge work better.'",
  "(Hoarded home) 'I'm not here to judge anyone's home. My focus is on him — that he's rested, has what he needs for school and feels OK about things. Is there anything that would make mornings or homework easier?'",
  "(Hoarded home) 'Lots of people find it really hard to let go of things, and it's a recognised difficulty that there is help for. Your GP is a good first step if you ever want to talk about it for yourself.'",
  "'If I'm ever worried about safety — for example fire or a place to sleep — I'll talk to you about it honestly, and I have a duty to pass that on. I'd rather we sorted it together.'",
  "SIGNPOST: GP (for child: CAMHS referral; for parent: adult services); Tusla Family Resource Centre / Meitheal; local authority fire service for home fire-safety advice (check locally); International OCD Foundation hoarding pages (iocdf.org — check) for information.",
 ],
 "explain_teacher": [
  "'Collecting is normal. What we're watching for is distress when something is thrown out and whether the keeping gets in the way of her work or space.'",
  "'Please don't clear her tray or bag without her. Do it together, with a simple keep / home / bin system, and let her photograph things she wants to remember.'",
  "'If a child's uniform, hygiene or tiredness makes you wonder about home, write down what you see, factually, and talk to the DLP. Don't speculate with colleagues or in the staffroom.'",
  "'For a child from a very cluttered home, the kindest things are practical: homework time in school, books kept in a locker, a spare jumper, no public comments about smell or lost items.'",
  "'Food hidden in a bag or desk can mean the child has known hunger. Tell the DLP and me; it needs a safety response, not a sanction.'",
 ],
 "explain_child": [
  "YOUNGER: 'Some things feel really special and it's hard to say goodbye to them. That's OK. We'll make a special box for your most important things, and you get to choose what goes in.'",
  "OLDER: 'It sounds like getting rid of stuff feels really uncomfortable — like you might need it, or you'd lose something. Lots of people feel that. What goes through your mind when you think about throwing something out?'",
  "(Hoarded home, older) 'Some young people tell me home is hard to invite friends to, or hard to find their things. You don't have to tell me anything, but if something is making school harder, we can sort practical bits here.'",
  "ASK: 'What's the most important thing you've kept, and why?' — tells you the function (memory, safety, interest, completeness).",
  "ASK: 'Where do you do your homework? Where do you sleep?' — gentle, factual questions that can surface welfare concerns without accusing anyone.",
 ],
 "analogies": [
  "THE ANCHOR: 'For some people, belongings are like anchors — each one holds a memory or a feeling of safety. Pulling them all up at once leaves you adrift.' Explains why forced clearing fails; good with parents and staff.",
  "THE JUST-IN-CASE DRAWER: 'Everyone has one drawer of things we might need someday. Imagine that drawer spreading until it takes over the room.' Normalises the experience; good with older children and parents.",
  "THE SORTING OFFICE WITH NO STAFF: 'Every item needs a decision — keep, give away, bin — and deciding is exhausting, so the post keeps piling up.' Frost and Hartl's (1996) decision-making difficulty in plain terms; good with teachers.",
  "THE COLLECTION VERSUS THE PILE: 'A collection has a shelf and a story; a pile has neither.' Helps teachers and parents tell ordinary collecting from something that needs support.",
 ],
 "language": [
  "Say 'difficulty letting go of possessions' or 'difficulty discarding' in reports, not 'hoarder'. The person is not the behaviour.",
  "Avoid TV language: 'hoarder house', 'filthy', 'squalor', 'junk'. These shame families and are not observations. Describe impact on the child: 'X reports no desk space for homework.'",
  "Where the concern is a parent, write about the child's needs and what school can provide. Do not name or describe the parent's mental health in the child's report unless the parent has agreed and it is necessary.",
  "Attribute any diagnosis: 'X was diagnosed with Hoarding Disorder by [service], [DD/MM/YYYY].' In children, it is more often recorded as a feature within OCD or anxiety.",
  "Food hoarding after deprivation: describe as 'hiding/storing food' and name the context sensitively; avoid 'stealing food'.",
 ],
 "red_flags": [
  "RED FLAG — signs the home threatens the child's safety or health: fire risk, blocked exits, no bed or working kitchen, infestation, persistent hunger, untreated health or hygiene problems. Children First route the same day: DLP, and as a mandated person you report to Tusla as soon as practicable — telling the DLP does not discharge your own duty. Supervision follows action.",
  "RED FLAG — food hiding, hunger or weight loss. Consider neglect, food insecurity and eating difficulties; do not treat as a behaviour issue.",
  "RED FLAG — hoarding with low mood, self-harm or hopelessness. Same-day risk protocol.",
  "BOUNDARY — you do not diagnose Hoarding Disorder or OCD, you do not assess or treat a parent, and you do not advise on medication (PSI 2.2.2). You formulate for the child, recommend school supports, and refer.",
  "WATCH — sudden onset of saving, rituals or distress in a younger child, especially after infection. Ask the family to consult their GP; sudden-onset OCD-type symptoms need medical review.",
  "WATCH — your own reaction. Disgust or judgement about a home shows up in report language and damages the relationship with the family.",
 ],
 "child_voice": [
  "'MY MOST SPECIAL THINGS' drawing or photo task — the child draws or photographs three kept items and tells you why. Good because it shows the function (memory, safety, interest) without challenging the behaviour.",
  "SCALING DISTRESS ('if your teacher moved this, how upset out of 10?') — good because it measures the core feature of difficulty discarding, and can track change in a graded plan.",
  "'MY THOUGHTS ABOUT SCHOOL' (NEPS) — good because it opens questions about space, belongings and friendships without focusing on home.",
  "SOLUTION-FOCUSED QUESTIONS: 'What would be different if your bag / room felt the way you want it?' — good because the child sets the goal, which is essential when possessions feel like part of the self.",
  "For a child from a hoarded home: the THREE HOUSES tool (house of worries / good things / dreams; Weld & Greenwood, New Zealand, used within Signs of Safety practice — check reference) — good because it lets the child talk about home through a structured, child-led task familiar in safeguarding practice.",
 ],
 "questions": [
  "Q: 'Is my child a hoarder? She keeps everything.' — A: 'Most children who keep lots of things are collecting, and that's normal. What makes it different is if letting go causes real distress and the keeping gets in the way of daily life. That's what we'll look at together.'",
  "Q: 'Should I just clear her room while she's out?' — A: 'That usually makes the worry worse, because it feels like losing something without warning. Small steps, with her deciding, work much better.'",
  "Q (teacher): 'His uniform smells and he's always tired — is that neglect?' — A: 'It might be, or there might be another explanation. Write down what you see, factually, and speak to the DLP today. If you're a mandated person and have reasonable grounds for concern, your duty to report to Tusla stands.'",
  "Q: 'Is hoarding a type of OCD?' — A: 'It used to be seen that way, but it's now its own diagnosis. Sometimes keeping things is driven by OCD fears, and then it's treated as OCD. A psychiatric team would decide that.'",
  "Q: 'Can you help my husband with his hoarding?' — A: 'I work with children and schools, so I can't assess or treat adults, but your GP can refer him to adult services. What I can do is make sure school is supporting your son.'",
  "Q: 'Is there treatment?' — A: 'Yes — specialist cognitive-behavioural therapy for hoarding has the best evidence in adults (Tolin et al., 2015). For children, help usually comes through CAMHS, often working on anxiety or OCD.'",
 ],
 "supervision": [
  "Bring the distinction: is this the child's own difficulty, or the home? Talk through the threshold for a Children First report when a parent hoards — impact on the child, not the state of the house.",
  "Rehearse how you would raise home conditions with a parent without shame, and how you would explain your reporting duty.",
  "Ask what the service's practice is on home visits, and whether you should visit at all — lone working and data protection apply.",
  "Discuss your emotional reaction to a cluttered or unhygienic home, and how that might shape your report.",
  "Check local availability: CAMHS acceptance of OCD-related hoarding; Tusla Family Support; whether the local fire service offers home fire-safety visits.",
 ],
 "reflection": [
  "ON THE REFERRAL — Did I separate the child's own behaviour from the family's circumstances, or did I blur the two?",
  "ON JUDGEMENT — Would I describe this home the same way if the family were wealthier? Did my words describe impact on the child or my own reaction?",
  "ON DEVELOPMENT — Did I test whether this was ordinary collecting, an autistic interest, or loss-related keeping before accepting a clinical frame?",
  "ON SAFEGUARDING — Did I act on concern the same day, or wait to see whether it got worse?",
  "ON THE CHILD'S VOICE — Did the child choose the goal, or did adults decide what 'tidy' meant?",
  "WHAT GOOD LOOKS LIKE: 'The referral said \"hoards rubbish in her tray\". The child explained each sheet recorded a day her dad was home. We agreed a photo album of her work and a weekly sorting slot. Distress fell. Bereavement support was arranged. No clinical label was needed.'",
  "WHAT POOR LOOKS LIKE: 'Possible hoarding disorder; home described by teacher as \"a tip\". Refer to CAMHS.' — diagnostic speculation, a judgement about the family repeated as fact, no function, no safeguarding decision.",
 ],
 "citations": [
  CIT_DSM,
  "Evans, D. W., Leckman, J. F., Carter, A., Reznick, J. S., Henshaw, D., King, R. A., & Pauls, D. (1997). Ritual, habit, and perfectionism: The prevalence and development of compulsive-like behavior in normal young children. Child Development, 68(1), 58–68.",
  "Frost, R. O., & Hartl, T. L. (1996). A cognitive-behavioral model of compulsive hoarding. Behaviour Research and Therapy, 34(4), 341–350.",
  "Grisham, J. R., Frost, R. O., Steketee, G., Kim, H.-J., & Hood, S. (2006). Age of onset of compulsive hoarding. Journal of Anxiety Disorders, 20(5), 675–686.",
  "Postlethwaite, A., Kellett, S., & Mataix-Cols, D. (2019). Prevalence of hoarding disorder: A systematic review and meta-analysis. Journal of Affective Disorders, 256, 309–316.",
  "Storch, E. A., Lack, C. W., Merlo, L. J., Geffken, G. R., Jacob, M. L., Murphy, T. K., & Goodman, W. K. (2007). Clinical features of children and adolescents with obsessive-compulsive disorder and hoarding symptoms. Comprehensive Psychiatry, 48(4), 313–318. [Check author list before quoting.]",
  "Tolin, D. F., Frost, R. O., Steketee, G., & Fitch, K. E. (2008). Family burden of compulsive hoarding: Results of an internet survey. Behaviour Research and Therapy, 46(3), 334–344.",
  "Tolin, D. F., & Villavicencio, A. (2011). Inattention, but not OCD, predicts the core features of hoarding disorder. Behaviour Research and Therapy, 49(2), 120–125.",
  "Tolin, D. F., Frost, R. O., Steketee, G., & Muroff, J. (2015). Cognitive behavioral therapy for hoarding disorder: A meta-analysis. Depression and Anxiety, 32(3), 158–166.",
  CIT_TUSLA,
 ],

 "pathway": {
  "age": "Rarely diagnosed in childhood. Symptoms often begin in early adolescence (Grisham et al., 2006 — check figure), but most people are identified in mid to later adulthood, when clutter and impairment are obvious. In children it is usually noticed as part of OCD, anxiety or autism assessment, or through concern about a parent's home.",
  "who_diagnoses": "Ireland: CAMHS psychiatrist or clinical psychologist for a young person; adult mental health services or a private psychiatrist or clinical psychologist for an adult. The EP does not diagnose it.",
  "who_wrote_report": "CAMHS (often within an OCD or anxiety assessment), a private clinical psychologist or psychiatrist, or — for a parent — adult mental health services. Reports about a parent should not normally be in the child's school file.",
  "refer_to": "GP → CAMHS for the child where severe or linked to OCD / moderate–severe mental health difficulty (check acceptance criteria); Tusla (Children First) where the home affects the child's safety or welfare; Tusla Family Support / Meitheal with consent; the parent's own GP for adult services; local authority fire service for home fire-safety advice (check locally).",
  "sooner": "'Keeping things is so ordinary in childhood that it's very hard to tell early on when it's becoming a difficulty. Noticing it now, and working with her rather than around her, is exactly the right time.'",
 },
 "differential": [
  "ORDINARY COLLECTING — organised, enjoyed, shared; no distress at discarding low-value items (Evans et al., 1997).",
  "OCD — saving driven by obsessional fear or 'just right' feelings; coded as OCD.",
  "AUTISM — organised collections linked to special interests; distress at change rather than at discarding as such.",
  "ADHD — disorganisation and lost items without emotional attachment to objects.",
  "LOSS / TRAUMA / DEPRIVATION — keeping items of a lost person; food hiding after neglect or care.",
  "MEDICAL / GENETIC — Prader-Willi syndrome, brain injury; excluded from Hoarding Disorder by DSM-5-TR.",
  "POVERTY OR CROWDED HOUSING — lack of space or keeping things out of necessity, not a mental health difficulty.",
 ],
 "next": [
  "Decide and record which referral this is: child's own saving, or child in a hoarded home.",
  "If any safety or neglect concern exists, Children First first — the same day — and tell your supervisor.",
  "Formulate the function with the child's voice; agree graded, child-led organisation supports at the right Continuum level.",
  "Refer via GP to CAMHS where hoarding is severe, persistent or linked to OCD, anxiety or low mood.",
 ],
 "presentations": [
  "Difficulty discarding / letting go of belongings",
  "Excessive collecting",
  "Disorganised belongings, lost equipment",
  "Food hiding or storing",
  "Distress at change to personal space",
  "Child living in a hoarded or unsafe home",
  "Poor hygiene or tiredness raising welfare concern",
 ],

 "bands": {
  "Early Years": {
   "applies": "N/A — not diagnosed at this age; collecting and 'just right' routines are developmentally ordinary (Evans et al., 1997)",
   "prevalence": "Not applicable — no diagnostic rate at this age; rate not stated here.",
   "see": "Pockets full of stones, attachment to particular objects, upset when a toy is thrown out — ordinary. Concern at this age is almost always about the HOME (safety, hygiene, space) or about food hiding after deprivation, which are welfare questions for Tusla and the public health nurse, not a hoarding question.",
   "tools": ["SDQ (2–4 version)"],
  },
  "School Age": {
   "applies": "RARELY — hoarding features may be seen within OCD, anxiety or autism; a stand-alone diagnosis is uncommon",
   "prevalence": "Youth prevalence not established — rate not stated here, check before quoting.",
   "see": "A tray or bag the child will not let anyone clear, distress when worksheets are recycled, keeping broken items 'in case'. Ask about the function and about loss. The more common referral is a child from a very cluttered home: tiredness, hygiene, missing equipment, shame. Formulate, support practically, and apply Children First thresholds.",
   "tools": ["SDQ", "RCADS", "BASC-3", "Conners-4", "BRIEF-2",
             "Children's Saving Inventory (Storch et al., 2011 — check reference) — AGE: school age, parent report · MEASURES: difficulty discarding, clutter, acquisition, distress in youth · CANNOT TELL YOU: a diagnosis, or whether OCD or autism better explains it; no Irish norms · TIME: 10 minutes"],
  },
  "Adolescent": {
   "applies": "RARELY — symptoms often begin now (Grisham et al., 2006), but diagnosis is usually later; CAMHS decides",
   "prevalence": "Not established for adolescents — rate not stated here, check before quoting.",
   "see": "A bedroom that cannot be used, distress and conflict when parents clear it, acquiring free items or buying, indecision. Screen mood, anxiety and OCD; ask the young person what keeping gives them. Self-report becomes useful; involve the young person fully in any goal.",
   "tools": ["RCADS self-report", "BASC-3 SRP", "MFQ (Mood and Feelings Questionnaire)", "BRIEF-2 self-report",
             "Saving Inventory-Revised (Frost et al., 2004) — AGE: adult self-report; older adolescents only with caution — check · MEASURES: clutter, difficulty discarding, acquisition · CANNOT TELL YOU: a diagnosis; not normed for Irish youth · TIME: 10 minutes"],
  },
  "Young Adult": {
   "applies": "YES — first diagnosis becomes more likely, usually through adult mental health services",
   "prevalence": "Adult pooled prevalence about 2.5% (Postlethwaite et al., 2019) — check before quoting.",
   "see": "In further education or independent living: a flat or room that cannot be used, conflict with housemates, missed deadlines from disorganisation, shame. Also appears as a history in files. Refer via GP to adult services; the EP role is educational access and support.",
   "tools": ["Adult self-report measures via the service",
             "Clutter Image Rating (Frost et al., 2008) — AGE: adult · MEASURES: clutter level per room against nine photographs · CANNOT TELL YOU: why items are kept or whether criteria are met · TIME: 5 minutes"],
  },
  "Special Setting": {
   "applies": "RARELY — collecting and keeping behaviours are common but usually better explained by autism, ID or a genetic syndrome",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Collecting specific items, distress if belongings are moved, food-seeking in Prader-Willi syndrome. Describe function, respect interests, and use visual organisation systems. Medical teams lead on syndrome-related food-seeking; the school's job is a safe, predictable environment.",
   "tools": ["Functional behaviour assessment (ABC)", "Vineland-3 / ABAS-3", "Communication Matrix / AAC review"],
  },
 },
})

# ============================================================================ 2 · INTERMITTENT EXPLOSIVE DISORDER
CONDS.append({
 "name": "Intermittent Explosive Disorder (IED)",
 "code": "DSM-5-TR Intermittent Explosive Disorder (ICD-10-CM F63.81) · ICD-11 6C73 Intermittent explosive disorder (within Impulse control disorders) — check codes before quoting",
 "neps": NEPS_BEH + " — and 3. EMOTIONAL (3.4 Mood · 3.7 Risk and safeguarding) where relevant",
 "coru": CORU,
 "psi": PSI,
 "law": LAW + " · Children Act 2001 · Department of Education guidance on reduced school days (2021) and on responding to behaviours of concern / crisis situations — check current versions",

 "what_it_is": [
  "A DSM-5-TR diagnosis in the 'Disruptive, Impulse-Control, and Conduct Disorders' chapter: RECURRENT BEHAVIOURAL OUTBURSTS that represent a failure to control aggressive impulses (APA, 2022).",
  "FREQUENCY/SEVERITY (Criterion A): EITHER verbal aggression or physical aggression that does not cause damage or injury, on average twice weekly for three months; OR three outbursts involving damage to property and/or physical assault causing injury within 12 months (APA, 2022). Verify wording against DSM-5-TR before quoting.",
  "The outburst is GROSSLY OUT OF PROPORTION to the provocation, is NOT PREMEDITATED (impulsive or anger-based), and is NOT committed for a tangible goal such as money, power or intimidation (APA, 2022). This separates it from the planned, instrumental aggression of conduct disorder.",
  "AGE: the person must be at least 6 years old, or the developmental equivalent. For children aged 6–18, aggression that is part of an adjustment disorder should not be counted (APA, 2022). This is why it is almost never a preschool diagnosis.",
  "EXCLUSIONS AND ADDITIONS: not better explained by another mental disorder or due to a medical condition (e.g. head injury) or substance. It may be diagnosed ALONGSIDE ADHD, conduct disorder, ODD or autism when outbursts exceed what is usually seen in those conditions and need separate clinical attention (APA, 2022). DSM-5-TR states DMDD cannot coexist with IED — if DMDD criteria are met, DMDD is given.",
  "The person typically feels BETWEEN OUTBURSTS much as usual — no persistent irritable mood — and often feels regret, shame or embarrassment afterwards. Coccaro (2012) framed IED as a disorder of impulsive aggression with problems in emotional information processing.",
  "For the EP, the question is not 'is this IED?' but 'what triggers these outbursts, what is the child experiencing before and after, and how do we keep everyone safe while we find out?'",
 ],
 "what_it_is_not": [
  "NOT DMDD. In DMDD there is a persistently irritable or angry mood most of the day, nearly every day, BETWEEN outbursts, with onset before age 10 (APA, 2022). In IED the child is broadly settled between episodes. Ask teachers what the child is like on a good afternoon.",
  "NOT ADHD alone. Impulsive, quick-flash anger is common in ADHD and usually brief and proportionate to frustration. IED is added only when outbursts go well beyond this. Assess ADHD in its own right.",
  "NOT a trauma response mislabelled — but it can be. Angry outbursts and hypervigilance are features of post-traumatic stress; a child re-experiencing threat may explode 'out of nowhere'. Ask about adversity and follow Children First if concerns arise.",
  "NOT an autistic meltdown. A meltdown is a response to overwhelming sensory, social or change-related load, often with early warning signs. It needs environmental change, not anger management. DSM-5-TR allows IED alongside autism only where outbursts exceed what is usual.",
  "NOT conduct disorder. Aggression in IED is impulsive and regretted; in conduct disorder it is often planned, used to get something, and part of a wider pattern of rule-breaking.",
  "NOT 'anger issues' as a character trait. Recurrent explosive outbursts can signal unrecognised language difficulty (Hollo et al., 2014), learning difficulty, pain, sleep problems, bullying, substance use or depression. Rule these out before accepting any label.",
  "NOT a school-level label. Teachers and parents may say 'he has IED' informally; unless CAMHS or a psychiatrist diagnosed it, it should not appear in a report.",
 ],
 "prevalence": [
  "OVERALL: DSM-5-TR reports a one-year prevalence of about 2.7% in US data (narrow definition) — check the current text before quoting (APA, 2022).",
  "ADOLESCENTS: McLaughlin et al. (2012), using the US National Comorbidity Survey Adolescent Supplement, reported a lifetime prevalence of about 7.8% using a broad definition — check the figure and definition before quoting. It is rarely diagnosed in Irish school-age children.",
  "AGE OF ONSET: usually late childhood or adolescence; DSM-5-TR states onset after age 40 is rare (APA, 2022).",
  "EARLY YEARS 0–5: not diagnosed — DSM-5-TR requires age 6 or developmental equivalent.",
  "IRELAND: no Irish prevalence figure is stated here — check before quoting.",
  "SEX RATIO: some studies find a male predominance; others do not — check DSM-5-TR text before quoting any ratio.",
 ],
 "cooccurring": [
  {"name": "ADHD", "rate": "commonly co-occurs — rate not stated here, check before quoting",
   "presents": "impulsivity and low frustration tolerance underneath outbursts; assess separately. IED is diagnosed in addition only if outbursts exceed what ADHD usually explains."},
  {"name": "ANXIETY AND DEPRESSION", "rate": "elevated in adolescent samples (McLaughlin et al., 2012) — check rate",
   "presents": "outbursts when overwhelmed, irritability as a face of low mood, shame and withdrawal afterwards. Screen mood and risk."},
  {"name": "TRAUMA AND ADVERSITY", "rate": "elevated — rate not stated here, check",
   "presents": "hypervigilance, startle, explosive response to perceived threat or shame. Children First applies whenever there is reasonable concern."},
  {"name": "DLD / UNIDENTIFIED LANGUAGE NEED", "rate": "elevated in EBD samples (Hollo et al., 2014) — check figure",
   "presents": "frustration when unable to explain or understand, outbursts after verbal reprimands or complex instructions. Language screening belongs in the assessment."},
  {"name": "ODD / CONDUCT DISORDER", "rate": "commonly co-occurs — rate not stated here, check",
   "presents": "a wider pattern of defiance or rule-breaking; IED may be added where impulsive outbursts need separate attention."},
  {"name": "AUTISM", "rate": "rate not stated here — check",
   "presents": "meltdowns triggered by sensory or change overload; IED considered only where outbursts exceed what is usual in autism."},
  {"name": "SUBSTANCE USE (adolescents)", "rate": "elevated in adolescent samples — rate not stated here, check",
   "presents": "outbursts linked to intoxication, withdrawal or conflict over use. Ask; signpost to local youth drug and alcohol services."},
 ],
 "recommendations": [
  "SAFETY FIRST, THEN FORMULATION. Where outbursts cause injury or risk to others, agree an individual safety / crisis plan with the principal and parents: early warning signs, a safe space, who responds, how others are protected, how the child is supported afterwards. Follow the school's policy and current Department of Education guidance on responding to behaviours of concern and crisis situations (check current version).",
  "FUNCTIONAL ASSESSMENT. ABC and 'antecedent diary' over at least a week, in more than one setting: time, task, people, sensory load, hunger, sleep, preceding interactions. Map the build-up; the earliest warning sign is where support is most effective.",
  "RULE OUT THE UNMET NEED. Attainment, language screen, sleep, pain, bullying, adversity, substance use. Many 'explosive' pupils have unidentified language or learning needs (Hollo et al., 2014).",
  "TEACH REGULATION WHEN CALM. Anger-management CBT has good evidence for children and adolescents (Sukhodolsky et al., 2004 meta-analysis): recognising body signals, calming strategies, problem-solving and social skills. School-based versions can be delivered at School Support Plus by trained staff.",
  "ADULT RESPONSE: low, calm voice; reduce audience; fewer words; offer an exit; never physical intervention except in line with policy and genuine immediate danger. After an outburst: restore, then reflect — a calm conversation later, not an interrogation during.",
  "CONTINUUM LEVEL: School Support Plus for most children where IED has been diagnosed or outbursts cause injury — outside services involved, individual behaviour and safety plan, review dates.",
  "REFER: GP → CAMHS where outbursts are severe, frequent, cause injury, or co-occur with mood difficulty, trauma or risk (check CAMHS acceptance criteria). Primary Care Psychology for milder difficulty. SLT for language. Tusla Family Support / Meitheal where family stress is part of the picture.",
  "DO NOT use exclusion, reduced timetables or restraint as intervention. Where a reduced school day is used, follow Department of Education guidelines on reduced school days (2021 — check current circular), including notification to Tusla Education Support Service. DO NOT write 'explosive', 'violent child' or 'IED' unless diagnosed and attributed.",
 ],
 "explain_parent": [
  "'The outbursts seem to come from nowhere, but they rarely do. Our job is to find the build-up — what happens in the hour before — so we can help earlier.'",
  "'I'm not able to diagnose. If it's decided that a specialist view is needed, that would be CAMHS through your GP. What I can do is describe what's happening, what sets it off, and what's working.'",
  "'Lots of children who have big outbursts feel awful afterwards. That regret is important — it tells us he wants to manage this, and it's something to build on.'",
  "'At home, the best time to talk about anger is when everyone is calm. In the middle of it, less talking and more space.'",
  "'If anyone is being hurt — at home or at school — tell us or your GP straight away. Keeping everyone safe comes first, and it's not a failure to ask for help.'",
  "SIGNPOST: GP (CAMHS or Primary Care Psychology referral); Tusla Family Resource Centre for parenting support; Parentline (check current number).",
 ],
 "explain_teacher": [
  "'What is he like on a good day, between outbursts? If he's broadly fine, that points one way; if he's irritable all day, that points another. It matters for what we recommend.'",
  "'Log the build-up, not just the explosion. Time, task, who was there, what was said. The first sign is our best chance.'",
  "'In the moment: calm voice, few words, clear the audience, offer the exit. Don't argue, don't block the door, and don't demand an apology there and then.'",
  "'Afterwards, repair. A quiet chat later: what was happening, what might help next time. Keep it short and don't lecture.'",
  "'If anyone is at risk of real harm, follow the crisis plan and tell the principal immediately. Safety for everyone, including him.'",
 ],
 "explain_child": [
  "YOUNGER (6+): 'Sometimes anger gets really big really fast, like a volcano. It's not your fault that it gets big, but we can learn together how to spot it early and cool it down.'",
  "OLDER: 'It sounds like sometimes the anger takes over before you can stop it, and afterwards you feel bad. That's really hard. Let's work out what happens just before, so you get more warning.'",
  "ASK: 'What does your body feel like just before you explode?' — helps build early warning signs.",
  "ASK: 'Who or what helps you calm down?' and 'What do adults do that makes it worse?' — the answers shape the plan.",
  "ASK (older): 'Do you ever feel down, worried, or like there's no point?' — outbursts can hide low mood or distress.",
 ],
 "analogies": [
  "THE VOLCANO: 'Pressure builds underground where nobody sees it; the eruption is just the part we notice.' For children, teachers and parents — focuses attention on the build-up.",
  "THE SMOKE ALARM SET TOO SENSITIVE: 'The alarm goes off for toast, not just fires. We don't rip it out; we help it tell the difference.' For threat sensitivity after adversity; good with parents.",
  "THE FIVE-POINT SCALE: 'Calm is 1, eruption is 5. Our work happens at 2 and 3.' (Buron & Curtis, 2012 — check edition.) Useful with children and staff.",
  "THE BRAKES: 'The engine works fine; the brakes are slow to engage.' Explains impulsive aggression without blame; good with older children and parents.",
 ],
 "language": [
  "Describe episodes factually: 'On 3 of 10 observed days X shouted and threw equipment after a peer comment; each episode lasted under 5 minutes.' Not 'X is explosive/violent'.",
  "Attribute any diagnosis: 'X was diagnosed with Intermittent Explosive Disorder by [service], [DD/MM/YYYY].'",
  "Avoid: 'violent child', 'aggressive boy', 'meltdown' (unless clearly sensory), 'temper tantrum' for an adolescent. Prefer: 'outburst', 'episode of distressed behaviour', 'behaviour of concern'.",
  "Record risk precisely: what happened, to whom, any injury, what was done. Vague language ('kicked off') makes risk hard to assess and can inflate reputation.",
 ],
 "red_flags": [
  "RED FLAG — risk of serious harm to others: threats with a plan, weapons, injury to peers or staff. Immediate safety response via the principal and school procedures; Gardaí where there is imminent danger. Same day. Supervision follows action.",
  "RED FLAG — self-harm, suicidal talk, or hopelessness after outbursts. Same-day risk protocol; the outburst label must not hide an emotional emergency.",
  "RED FLAG — outbursts linked to disclosure of harm, bruising, fear of going home, or exposure to domestic violence. Children First: DLP and your own mandated report to Tusla as soon as practicable — telling the DLP does not discharge your duty.",
  "BOUNDARY — you do not diagnose IED and you do not advise on medication (PSI 2.2.2). You describe, formulate, recommend and refer.",
  "WATCH — new-onset outbursts in a previously settled child, or after a head injury. Ask the family to consult their GP; medical causes are excluded from IED.",
  "WATCH — a school using a diagnosis to justify exclusion or restraint. Your role is to meet need and support safety, not supply grounds for removal.",
 ],
 "child_voice": [
  "THE FIVE-POINT SCALE or 'ANGER THERMOMETER' co-built with the child — good because the child names their own warning signs and calming strategies, which is the core of anger-management CBT.",
  "'MY THOUGHTS ABOUT SCHOOL' (NEPS) — good because it separates lessons and relationships the child finds hard from the outbursts themselves.",
  "BEFORE–DURING–AFTER comic strip or drawing — good because it lets the child sequence an episode visually, without being asked to justify it.",
  "SOLUTION-FOCUSED EXCEPTIONS: 'Tell me about a time you felt the anger coming and it didn't explode.' — good because it finds strategies the child already uses.",
  "SCALING WITH A KEY ADULT at the end of each day — good because it builds the relationship and gives the child a voice in the plan's review.",
 ],
 "questions": [
  "Q: 'Is IED just a fancy name for a bad temper?' — A: 'It's a recognised diagnosis for repeated outbursts that are far bigger than the trigger and can't be controlled at the time. It's only given by a specialist. What matters for us is what sets the outbursts off and how we help.'",
  "Q: 'What's the difference between this and DMDD?' — A: 'In DMDD the young person is irritable most of the day, nearly every day, between outbursts. In IED they are usually settled in between. A specialist decides, but the difference changes the plan.'",
  "Q: 'Will he grow out of it?' — A: 'Many young people get much better at managing anger with support and as they mature. Learning skills now — when he's calm — makes the biggest difference.'",
  "Q: 'Is there medication?' — A: 'That's a medical question for the GP or CAMHS; I can't advise on it. Talking therapies for anger have good evidence in children and teenagers.'",
  "Q (principal): 'He injured a teacher. Can we exclude him?' — A: 'Safety comes first, and the school's code of behaviour applies. But exclusion doesn't reduce future outbursts. Let's agree a safety plan and look at what was happening before the incident.'",
  "Q: 'He's lovely afterwards — is he manipulating us?' — A: 'Regret after an outburst is typical of impulsive aggression. It's a strength we can use, not manipulation.'",
 ],
 "supervision": [
  "Bring the safety plan: is it clear who does what, and is it proportionate and within policy?",
  "Discuss the differential — DMDD, ADHD, trauma, autism, language — and what evidence would separate them.",
  "Ask how the service supports schools after a serious injury incident, and how to hold a child-centred position when staff are frightened or angry.",
  "Rehearse how to explain to a principal why exclusion is unlikely to help, without dismissing staff safety.",
  "Notice your own response: fear or anger after an incident can shape your language and recommendations.",
 ],
 "reflection": [
  "ON THE DIFFERENTIAL — Did I ask what the child is like between outbursts? Did I test language, learning, trauma and mood?",
  "ON SAFETY — Was the safety plan agreed with the family and the child, and does it protect everyone, including the child?",
  "ON LANGUAGE — Did I describe outbursts factually, or use words that will follow this child through school?",
  "ON THE CHILD'S VOICE — Did the child help design the warning signs and calming strategies?",
  "ON POWER — Was my work being used to support exclusion? Did I name that?",
  "WHAT GOOD LOOKS LIKE: 'The referral said \"explosive\". The antecedent diary showed episodes after verbal reprimands in front of peers, late in the morning, on days without breakfast. SLT screening showed a receptive language need. The plan: breakfast club, private correction, visual instructions and a five-point scale. Episodes fell from four a week to one.'",
  "WHAT POOR LOOKS LIKE: 'Presentation consistent with IED. Recommend anger management and CAMHS.' — a diagnostic claim outside the role, no function, no safety plan, no unmet need tested.",
 ],
 "citations": [
  CIT_DSM,
  "Coccaro, E. F. (2012). Intermittent explosive disorder as a disorder of impulsive aggression for DSM-5. American Journal of Psychiatry, 169(6), 577–588.",
  "McLaughlin, K. A., Green, J. G., Hwang, I., Sampson, N. A., Zaslavsky, A. M., & Kessler, R. C. (2012). Intermittent explosive disorder in the National Comorbidity Survey Replication Adolescent Supplement. Archives of General Psychiatry, 69(11), 1131–1139.",
  CIT_SUKH,
  "McCloskey, M. S., Noblett, K. L., Deffenbacher, J. L., Gollan, J. K., & Coccaro, E. F. (2008). Cognitive-behavioral therapy for intermittent explosive disorder: A pilot randomized clinical trial. Journal of Consulting and Clinical Psychology, 76(5), 876–886.",
  CIT_HOLLO,
  "Buron, K. D., & Curtis, M. (2012). The incredible 5-point scale (2nd ed.). AAPC Publishing. [Check for the current edition.]",
  CIT_NEPS,
  CIT_IFF,
 ],

 "pathway": {
  "age": "Rarely diagnosed before adolescence. DSM-5-TR requires age 6 or developmental equivalent, and onset is typically late childhood or adolescence (APA, 2022). In school it usually surfaces after a run of serious incidents, when ADHD, ODD or DMDD have been considered and do not fully explain the outbursts.",
  "who_diagnoses": "Ireland: CAMHS psychiatrist or clinical psychologist, or a private psychiatrist or clinical psychologist. It is uncommon in Irish CAMHS reports; ADHD, ODD, DMDD or trauma formulations are more often used. The EP does not diagnose it.",
  "who_wrote_report": "CAMHS or a private psychiatrist or clinical psychologist; occasionally an adult mental health or forensic service for an older adolescent. A rating-scale aggression score from school is screening data, not a diagnosis.",
  "refer_to": "GP → CAMHS where outbursts cause injury, are frequent, or co-occur with mood difficulty, trauma or risk (check CAMHS acceptance criteria); Primary Care Psychology for milder difficulty; SLT for language; Tusla (Children First) for welfare concerns; Gardaí only where there is imminent danger.",
  "sooner": "'Outbursts can be very hard to read — lots of children have big tempers that settle. It's when they keep happening and are far bigger than the trigger that a pattern becomes clear. Now that we can see it, we can act on it.'",
 },
 "differential": [
  "DMDD — persistent irritable mood between outbursts, onset before 10; if met, DMDD is given, not IED.",
  "ADHD — brief, frustration-linked flashes of temper proportionate to ADHD-related difficulty.",
  "TRAUMA / PTSD — outbursts to perceived threat, hypervigilance, startle, re-experiencing.",
  "AUTISM — meltdowns triggered by sensory, social or change overload, often with early warning signs.",
  "CONDUCT DISORDER — planned, instrumental aggression within a wider pattern of rule-breaking.",
  "DEPRESSION / BIPOLAR — irritability as low mood; episodic change in mood and energy.",
  "MEDICAL / SUBSTANCE — head injury, other neurological causes, intoxication or withdrawal.",
 ],
 "next": [
  "If there is risk to others or to the child, act first: safety plan, principal, and the same-day route; tell your supervisor the same day.",
  "Complete a functional assessment and an antecedent diary across settings.",
  "Test the unmet-need hypotheses — language, learning, sleep, trauma, mood — before finalising.",
  "Agree a School Support Plus plan with regulation teaching, adult responses and review dates; refer via GP to CAMHS where indicated.",
 ],
 "presentations": [
  "Behaviour that challenges",
  "Aggression towards peers or staff",
  "Emotion regulation in the classroom",
  "Escalation and de-escalation pattern",
  "Damage to property",
  "Response to correction and repair after an incident",
  "Behaviour as communication of an unmet learning need",
 ],

 "bands": {
  "Early Years": {
   "applies": "N/A — DSM-5-TR requires age 6 or developmental equivalent",
   "prevalence": "Not applicable — not diagnosed under 6.",
   "see": "Tantrums and hitting are common in toddlers and usually developmental. Concern is intensity, frequency and whether it happens across settings. Language delay, sleep, sensory needs and family stress are the usual drivers; support the parent-child relationship and describe rather than classify.",
   "tools": ["SDQ (2–4 version)", "Conners EC", "Ages & Stages Questionnaires (ASQ-3)", "Preschool Language Scales-5 (PLS-5)", "Functional behaviour assessment (ABC)"],
  },
  "School Age": {
   "applies": "RARELY — possible from age 6, but ADHD, ODD, DMDD, autism or trauma formulations are far more common",
   "prevalence": "Not reliably estimated in school-age children here — check before quoting.",
   "see": "Sudden, very big outbursts — throwing, shouting, hitting — after minor triggers, with regret afterwards and settled periods in between. Test language, learning and attention; ask about adversity; build a safety plan where others are at risk. Parent–teacher differences tell you about triggers.",
   "tools": ["SDQ", "BASC-3", "Conners-4", "BRIEF-2", "Functional behaviour assessment (ABC)", "CELF-5 UK", "WIAT-III UK", "RCADS"],
  },
  "Adolescent": {
   "applies": "YES — the band where it is most often first diagnosed, by CAMHS or psychiatry",
   "prevalence": "Lifetime about 7.8% in a US adolescent survey using a broad definition (McLaughlin et al., 2012) — check before quoting; no Irish figure.",
   "see": "Fights, damage to property, shouting at staff, walking out, suspensions; regret and shame afterwards. Screen mood, substance use and trauma; ask the young person about triggers and what helps. Self-report and collaborative safety planning become central.",
   "tools": ["BASC-3 SRP", "Conners-4 self-report", "RCADS self-report", "MFQ (Mood and Feelings Questionnaire)", "BRIEF-2 self-report", "CELF-5 UK", "Functional behaviour assessment (ABC)"],
  },
  "Young Adult": {
   "applies": "YES — may be diagnosed or continue; also appears retrospectively in files",
   "prevalence": "Adult one-year prevalence about 2.7% in US data (APA, 2022) — check before quoting.",
   "see": "In further education, Youthreach, apprenticeships or work placements: arguments, damage, conflict with authority, legal consequences. Ask what support is in place and what has changed; many young adults have learnt to manage outbursts.",
   "tools": ["Adult self-report measures via the service"],
  },
  "Special Setting": {
   "applies": "RARELY — outbursts in pupils with ID, autism or limited communication are usually communication of need, pain or overload",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Hitting, throwing and self-injury in pupils with complex needs. Functional assessment, communication review, sensory profile and medical check (pain, sleep, epilepsy) come before any behavioural diagnosis. Adaptive functioning sets the developmental expectation.",
   "tools": ["Functional behaviour assessment (ABC)", "Vineland-3 / ABAS-3", "Communication Matrix / AAC review", "Adaptive measure in place of IQ"],
  },
 },
})

# ============================================================================ 3 · PYROMANIA AND KLEPTOMANIA
CONDS.append({
 "name": "Pyromania and Kleptomania",
 "code": "DSM-5-TR Pyromania (ICD-10-CM F63.1) · Kleptomania (ICD-10-CM F63.2) · ICD-11 6C70 Pyromania · 6C71 Kleptomania (within Impulse control disorders) — check codes before quoting",
 "neps": NEPS_BEH + " — and 3. EMOTIONAL (3.7 Risk and safeguarding); fire-setting is always a safety matter",
 "coru": CORU,
 "psi": PSI,
 "law": LAW + " · Children Act 2001 (Part 4 Garda Youth Diversion Programme; age of criminal responsibility, as amended by the Criminal Justice Act 2006 — check before quoting) · Criminal Damage Act 1991 (arson — check provisions) · Criminal Justice (Theft and Fraud Offences) Act 2001",

 "what_it_is": [
  "Two separate DSM-5-TR impulse-control disorders, grouped here because both are VERY RARE in children and the behaviours they name — FIRE-SETTING and STEALING — are common and almost always explained by something else (APA, 2022).",
  "PYROMANIA: deliberate, purposeful fire-setting on more than one occasion; tension or emotional arousal before; fascination with, interest in, or attraction to fire and its contexts; pleasure, gratification or relief when setting or watching fires. It is NOT done for money, ideology, to conceal crime, to express anger or vengeance, to improve living circumstances, in response to a delusion, or because of impaired judgement (e.g. intellectual disability, intoxication) (APA, 2022). Verify wording before quoting.",
  "KLEPTOMANIA: recurrent failure to resist impulses to steal objects NOT needed for personal use or for their money value; rising tension before, pleasure, gratification or relief during. The stealing is not to express anger or vengeance and not in response to a delusion or hallucination (APA, 2022). Stolen items are often given away, discarded or hoarded.",
  "BOTH are excluded if the behaviour is better explained by CONDUCT DISORDER, a manic episode or antisocial personality disorder (APA, 2022). In children and adolescents, that exclusion almost always applies: fire-setting and stealing are listed CRITERIA of conduct disorder.",
  "DSM-5-TR notes that pyromania as a primary diagnosis appears very rare, and that juvenile fire-setting is usually associated with conduct disorder, ADHD or adjustment disorder (APA, 2022 — check wording).",
  "Children's fire-setting is usefully described by MOTIVE: curiosity/experimentation (most common in young children), crisis or 'cry for help', peer-related or thrill-seeking, anger/revenge, and fire-setting as part of wider conduct difficulties (Lambie & Randell, 2011; Kolko, 2002). Motive, not diagnosis, drives the response.",
  "For the EP: fire-setting is ALWAYS a same-day SAFETY matter first and a formulation second. Stealing is almost never kleptomania — it is a behaviour to FORMULATE (need, peers, impulsivity, social understanding, emotional comfort, exploitation).",
 ],
 "what_it_is_not": [
  "NOT 'every child who plays with matches'. Curiosity about fire is common in young children; Kolko (2002) and Lambie and Randell (2011) describe curiosity fire-setting as the most frequent type in younger children. It still needs a safety response and fire-safety education, not a diagnosis.",
  "NOT every child who steals. Taking things is common in young children before ownership is fully understood; in older children it is usually linked to need, peers, impulsivity, anger or conduct difficulties. Kleptomania requires that the items are NOT needed or wanted — a child stealing food, money or trainers does not fit.",
  "NOT an explanation. 'He's a pyromaniac' or 'she's a kleptomaniac' said in a staffroom is a label, not an assessment. Unless a psychiatrist has diagnosed it, it does not belong in a report.",
  "NOT separate from the child's own safety. Fire-setting can be a sign of distress, abuse, neglect or exposure to violence; Lambie and Randell (2011) link it to adversity and family difficulty. Ask about home and follow Children First where there is reasonable concern.",
  "NOT deliberate cruelty in every case. Children with intellectual disability or autism may take items or play with fire without understanding risk or ownership. DSM-5-TR excludes pyromania where judgement is impaired by intellectual disability (APA, 2022).",
  "NOT to be handled by school discipline alone. Suspension for fire-setting without risk assessment, safety planning and referral leaves the risk in place and the reason unexplored.",
  "NOT criminal by default for a young child. Ireland's age of criminal responsibility is generally 12, with exceptions for certain serious offences from age 10 (Children Act 2001 as amended by the Criminal Justice Act 2006 — check before quoting). Garda involvement, where needed, is usually through the Juvenile Liaison Officer and Youth Diversion.",
 ],
 "prevalence": [
  "PYROMANIA: DSM-5-TR states population prevalence is not known and that it is very rare as a primary diagnosis (APA, 2022) — check before quoting.",
  "KLEPTOMANIA: DSM-5-TR gives a general-population prevalence of about 0.3–0.6%, and reports it among a minority of people apprehended for shoplifting (APA, 2022) — check the current text before quoting.",
  "FIRE-SETTING (behaviour, not diagnosis): common in childhood samples, especially curiosity fire-setting in young boys (Lambie & Randell, 2011; Kolko, 2002) — rates vary by study; check before quoting.",
  "STEALING (behaviour, not diagnosis): common across childhood and a conduct disorder criterion — rate not stated here, check before quoting.",
  "SEX RATIO: DSM-5-TR reports pyromania occurs much more often in males and kleptomania more often in females (about 3:1) — check before quoting.",
  "IRELAND: no Irish prevalence for either diagnosis, or for juvenile fire-setting, is stated here — check before quoting.",
 ],
 "cooccurring": [
  {"name": "CONDUCT DISORDER", "rate": "the usual context for fire-setting and stealing in youth (APA, 2022) — rate not stated here, check",
   "presents": "fire-setting or theft alongside aggression, destruction, deceit or serious rule-breaking. If CD explains it, pyromania/kleptomania are not diagnosed."},
  {"name": "ADHD", "rate": "associated with juvenile fire-setting (APA, 2022) — rate not stated here, check",
   "presents": "impulsive fire play or taking things without thinking of consequences; poor supervision of lighters and matches. Assess ADHD separately."},
  {"name": "TRAUMA, ABUSE AND NEGLECT", "rate": "elevated in fire-setting samples (Lambie & Randell, 2011) — rate not stated here, check",
   "presents": "fire-setting as distress or 'cry for help'; stealing food or comfort items after deprivation. Children First whenever there is reasonable concern."},
  {"name": "ANXIETY, DEPRESSION AND ADJUSTMENT DIFFICULTIES", "rate": "rate not stated here — check",
   "presents": "fire-setting or stealing after bereavement, separation or family crisis; relief-seeking. Screen mood and risk."},
  {"name": "INTELLECTUAL DISABILITY / AUTISM", "rate": "rate not stated here — check",
   "presents": "taking items without understanding ownership; fascination with fire as an interest without grasp of danger. Teach explicitly; supervise; DSM-5-TR excludes pyromania where judgement is impaired."},
  {"name": "SUBSTANCE USE AND EXPLOITATION (adolescents)", "rate": "rate not stated here — check",
   "presents": "stealing to fund use or pay debts; being made to steal or set fires by others. Consider criminal exploitation and drug-related intimidation; Tusla and Gardaí."},
  {"name": "HOARDING / OCD", "rate": "rate not stated here — check",
   "presents": "stolen items kept but unused in kleptomania; collecting driven by compulsion. Specialist differential for CAMHS."},
 ],
 "recommendations": [
  "FIRE-SETTING — SAME DAY: tell the principal; follow school safety procedures; remove access to ignition sources; inform parents; consider whether this is a Children First concern (DLP and your own mandated report to Tusla as soon as practicable). Tell your supervisor the same day. Supervision follows action.",
  "FIRE-SETTING — SPECIALIST: recommend referral via GP to CAMHS where fire-setting is repeated, planned, linked to distress, or part of wider conduct or mental health difficulty (check acceptance criteria). Ask the local authority fire service whether it offers fire-safety education for young people who set fires: UK fire and rescue services run established 'firesetter' intervention schemes, but an Irish equivalent is NOT confirmed here and may not exist in your county — check before recommending.",
  "FIRE-SETTING — FORMULATE MOTIVE: curiosity, crisis/cry for help, peer or thrill, anger/revenge, or part of conduct difficulty (Lambie & Randell, 2011). Record: how many times, where, what was burnt, whether planned, alone or with others, what happened afterwards, access to matches/lighters, supervision.",
  "STEALING — FORMULATE, DON'T LABEL. Ask: what was taken, from whom, what was done with it, alone or with peers, was it hidden or shown off? Then test hypotheses: NEED (hunger, poverty), PEERS or BULLYING (being made to steal), IMPULSIVITY (ADHD), SOCIAL UNDERSTANDING (autism, ID), EMOTIONAL COMFORT (loss, attachment), CONDUCT pattern, or EXPLOITATION.",
  "STEALING — SCHOOL RESPONSE: restorative not punitive; private, not public; return or repair; teach ownership explicitly for younger children or those with ID; meet any unmet need (breakfast club, uniform, equipment). School Support with a plan and review date.",
  "CONTINUUM LEVEL: School Support Plus for any fire-setting and for persistent stealing with outside services involved; School Support for isolated or developmentally typical stealing.",
  "REFER: GP → CAMHS (repeated fire-setting, distress, mood, or suspected impulse-control disorder); Tusla (Children First) for welfare concerns; Tusla Family Support / Meitheal; Garda Juvenile Liaison Officer / Youth Diversion where the Gardaí are already involved — not as a behaviour-management tool.",
  "DO NOT write 'pyromaniac', 'kleptomaniac', 'arsonist' or 'thief'. DO NOT recommend exclusion as the response to fire-setting without a safety plan and referral. DO NOT promise confidentiality about fire-setting or stealing that involves risk.",
 ],
 "explain_parent": [
  "(Fire) 'I need to be honest: any fire-setting is a safety matter, and we have to act on it today. That's not a judgement on your child or your family — it's about keeping everyone safe while we understand why.'",
  "(Fire) 'Many young children are curious about fire. Older children sometimes set fires when they're upset or under pressure. We'll find out which, and get the right help.'",
  "(Fire, home) 'Please keep matches and lighters out of reach and check smoke alarms. I'll also find out whether the local fire service does education sessions for young people.'",
  "(Stealing) 'Stealing in children is common and there's nearly always a reason — needing something, friends, not thinking ahead, or feeling low. It's very rarely a mental illness. Let's work out what's behind it.'",
  "'If you ever find things that worry you — or if anyone is pressuring your child to steal or do things — tell us or your GP. We'll help, and some of those things I have a duty to pass on.'",
  "SIGNPOST: GP (CAMHS referral); local authority fire service (fire-safety advice — check locally); Tusla Family Resource Centre; Parentline (check current number).",
 ],
 "explain_teacher": [
  "'Any fire-setting — even a small one in a bin — goes to the principal today. Write down exactly what happened, where, and who was there.'",
  "'Don't ask \"why did you do it?\" in front of others. Keep him safe and calm; the questions come later, privately, with the right people.'",
  "'For stealing, think detective, not judge. What was taken, and what did she do with it? That usually tells you the reason.'",
  "'Keep it private and restorative: return, repair, and make sure there isn't an unmet need — food, equipment, or someone making her do it.'",
  "'If a child tells you something about home or about older people pressuring them, that's the DLP today, and your own Tusla duty if you're a mandated person.'",
 ],
 "explain_child": [
  "YOUNGER (fire): 'Fire is very interesting, but it can hurt people and houses really fast. Grown-ups have to keep everyone safe, so we're going to talk about it and learn about fire safety together.'",
  "OLDER (fire): 'I'm not here to get you in trouble. When young people light fires there's usually something going on — curiosity, friends, feeling angry or upset. I'd like to understand what it was like for you.'",
  "YOUNGER (stealing): 'Sometimes we see something we really want and take it without thinking. Let's work out how to give it back and what to do next time.'",
  "OLDER (stealing): 'What was going on for you when you took it? Did you need it, did someone want you to, or was it something else?'",
  "ASK: 'Is anyone asking you to do things you don't want to do?' — opens the possibility of peer pressure or exploitation without accusation.",
  "BE CLEAR: 'If you tell me something that means you or someone else isn't safe, I can't keep it secret, but I'll tell you what I'm doing.'",
 ],
 "analogies": [
  "THE CAMPFIRE AND THE FOREST FIRE: 'Being interested in fire is like a campfire — normal. The worry is when it spreads where it shouldn't.' Separates curiosity from risk; good with parents and younger children.",
  "THE DETECTIVE: 'The stolen thing is a clue. What was taken, and what happened to it, tells us why.' For teachers and parents who want a sanction before a formulation.",
  "THE ITCH: 'Some people describe an urge that builds like an itch and only settles when they act on it.' Explains the tension–relief pattern of impulse-control disorders; for older adolescents and parents where a diagnosis has been given.",
  "THE ICEBERG: 'The fire or the theft is the tip; what's underneath — worry, need, friends, hurt — is what we have to find.' Works with staff and older children.",
 ],
 "language": [
  "Describe the behaviour: 'X set fire to paper in a bathroom bin on DD/MM/YYYY; no one was hurt.' Not 'X is a fire-setter/pyromaniac'.",
  "Stealing: 'X took items belonging to peers on three occasions this term' — not 'thief', 'light-fingered' or 'kleptomaniac'.",
  "Attribute any diagnosis: 'X was diagnosed with [Pyromania/Kleptomania] by [service], [DD/MM/YYYY].' These diagnoses are very rarely made in youth; check the source if one appears in a file.",
  "Avoid criminal language ('arson', 'offence') in a psychological report unless it reflects a formal Garda or court outcome, and then state it neutrally and only if necessary (PSI 1.2.8).",
 ],
 "red_flags": [
  "RED FLAG — any fire-setting in school, repeated fire-setting at home, planned fires, fires set in occupied buildings, or fires with intent to harm. Same-day safety response through the principal; Gardaí and fire service where there is immediate danger. Supervision follows action.",
  "RED FLAG — fire-setting or stealing linked to disclosure of abuse, neglect, hunger or domestic violence. Children First route the same day: DLP, and as a mandated person you report to Tusla as soon as practicable — telling the DLP does not discharge your own duty.",
  "RED FLAG — signs of criminal exploitation: stealing on demand, new possessions or money, older associates, debts, fear. Treat the child as a potential victim; Tusla and Gardaí.",
  "RED FLAG — fire-setting or stealing with low mood, self-harm or suicidal talk. Same-day risk protocol.",
  "BOUNDARY — you do not diagnose pyromania or kleptomania and you do not advise on medication (PSI 2.2.2). You assess risk to the extent of your role, formulate, recommend and refer.",
  "WATCH — a school wanting a diagnosis to support exclusion or transfer. Name the purpose; safety planning and referral are the response.",
 ],
 "child_voice": [
  "BEFORE–DURING–AFTER drawing or storyboard of the incident — good because it helps the child sequence events and reveals motive (curiosity, peers, anger, distress) without an interrogation.",
  "'MY THOUGHTS ABOUT SCHOOL' (NEPS) — good because it surfaces friendships, bullying and belonging, which often sit behind stealing.",
  "THREE HOUSES (worries / good things / dreams — Weld & Greenwood; check reference) — good because it opens home and safety concerns in a child-led way, essential when fire-setting may signal distress.",
  "SOLUTION-FOCUSED EXCEPTIONS: 'When did you feel like doing it and didn't?' — good because it identifies the child's own controls and strategies.",
  "SCALING ('how worried are you about this, 0–10?') — good because it tests insight and remorse, which informs risk and response.",
 ],
 "questions": [
  "Q: 'Is my son a pyromaniac?' — A: 'That diagnosis is very rare, especially in children, and it's not something I can diagnose. Most children who set fires do it out of curiosity, with friends, or when they're upset. What matters now is safety and understanding why.'",
  "Q: 'She keeps stealing — is it kleptomania?' — A: 'Almost never in children. Kleptomania means taking things you don't need or want because of an urge. Most children steal for a reason we can find — needing something, friends, or feelings. Let's look at that.'",
  "Q (principal): 'Do we have to call the Gardaí?' — A: 'Where there is immediate danger, yes. Otherwise, follow your safety procedures and inform the parents; involving the Gardaí is a decision for the principal. My role is to help understand the behaviour and plan.'",
  "Q: 'Is there a fire service programme for children in Ireland?' — A: 'Some fire services offer fire-safety education; I don't know of a national youth fire-setter programme, so I'll check with our local authority fire service before recommending one.'",
  "Q: 'Will he get a criminal record?' — A: 'That's a legal question I can't answer. In Ireland, younger children are generally dealt with through the Garda Youth Diversion Programme rather than the courts. The Juvenile Liaison Officer can explain the process.'",
  "Q: 'Should we exclude him after the fire?' — A: 'Safety comes first, and the code of behaviour applies. But exclusion alone doesn't reduce risk. A safety plan and a referral do.'",
 ],
 "supervision": [
  "Bring the risk decision the same day: what happened, what was done, who was told, and whether a Tusla report was needed.",
  "Discuss how to assess fire-setting motive within your role, and what specialist risk assessment looks like (CAMHS, forensic child and adolescent services — check local pathway).",
  "Ask whether your local authority fire service offers youth fire-safety education, and how to refer.",
  "Rehearse explaining to a principal why stealing needs formulation rather than exclusion.",
  "Discuss confidentiality limits with young people disclosing fire-setting or stealing, and how to explain them in advance.",
 ],
 "reflection": [
  "ON SAFETY — Did I act the same day on fire-setting, or treat it as ordinary misbehaviour?",
  "ON FORMULATION — Did I ask what was taken or burnt, and why, before accepting a label?",
  "ON NEED — Did I check for hunger, poverty, peers, bullying or exploitation?",
  "ON LANGUAGE — Is any criminal or diagnostic label in my report unattributed?",
  "ON THE CHILD — Did I hear the child's account of the incident, in a way that felt safe?",
  "WHAT GOOD LOOKS LIKE: 'The referral said \"kleptomaniac — steals every day\". The child was taking food from lunchboxes. Home had been disrupted by a parent's illness. The school started breakfast club and a discreet lunch arrangement; Tusla Family Support was offered with consent. Stealing stopped. No diagnosis was mentioned.'",
  "WHAT POOR LOOKS LIKE: 'Set fire to bin. Suspended for three days. Consider pyromania.' — no safety plan, no motive explored, no welfare consideration, no referral, and a diagnostic speculation outside the role.",
 ],
 "citations": [
  CIT_DSM,
  "Lambie, I., & Randell, I. (2011). Creating a firestorm: A review of children who deliberately light fires. Clinical Psychology Review, 31(3), 307–327.",
  "Kolko, D. J. (Ed.). (2002). Handbook on firesetting in children and youth. Academic Press.",
  "Gannon, T. A., & Pina, A. (2010). Firesetting: Psychopathology, theory and treatment. Aggression and Violent Behavior, 15(3), 224–238.",
  "Grant, J. E., & Odlaug, B. L. (2008). Kleptomania: Clinical characteristics and treatment. Revista Brasileira de Psiquiatria, 30(Suppl. 1), S11–S15. [Check reference details before quoting.]",
  CIT_ICD,
  CIT_TUSLA,
  CIT_NEPS,
  CIT_IFF,
 ],

 "pathway": {
  "age": "Very rarely diagnosed in children. Fire-setting and stealing are usually identified in primary school as behaviours, and formulated within conduct, ADHD, trauma or adjustment difficulties. Kleptomania, when it occurs, usually begins in adolescence or later (APA, 2022 — check). Pyromania as a primary diagnosis is very rare at any age.",
  "who_diagnoses": "Ireland: CAMHS psychiatrist, or a private or forensic psychiatrist or clinical psychologist. Specialist forensic child and adolescent assessment may be involved for serious fire-setting — check the local pathway. The EP does not diagnose either.",
  "who_wrote_report": "CAMHS, a private or forensic psychiatrist or clinical psychologist, or occasionally a report produced for court or probation. A school behaviour log is a record of incidents, not a diagnosis.",
  "refer_to": "Same-day safety and Children First route first where needed. Then GP → CAMHS for repeated fire-setting, distress or mood difficulty (check acceptance criteria); local authority fire service for fire-safety education (check availability); Tusla Family Support / Meitheal; Garda Juvenile Liaison Officer where Gardaí are involved.",
  "sooner": "'Curiosity about fire and taking things are both common in children, so it's hard to know when it's a pattern. What matters is that we're acting now, keeping everyone safe, and finding out what's behind it.'",
 },
 "differential": [
  "CONDUCT DISORDER — fire-setting and stealing within a wider pattern of aggression, deceit or rule-breaking; excludes both diagnoses.",
  "CURIOSITY / DEVELOPMENTAL — young children experimenting with fire or taking things before ownership is understood.",
  "NEED — stealing food, money or equipment because of hunger or poverty.",
  "PEER / EXPLOITATION — acting with or for others; criminal exploitation.",
  "TRAUMA / DISTRESS — fire-setting as a 'cry for help'; comfort stealing after loss or deprivation.",
  "ADHD — impulsive fire play or taking without thinking.",
  "ID / AUTISM — limited understanding of risk or ownership; fire as an interest.",
  "MANIA / PSYCHOSIS — rare; excluded by DSM-5-TR; CAMHS urgently if suspected.",
 ],
 "next": [
  "Fire-setting: same-day safety response and Children First decision; tell your supervisor the same day.",
  "Formulate motive and function with the child's voice and a factual incident history.",
  "Check for need, peers, exploitation, adversity and mood before any recommendation.",
  "Agree a School Support Plus plan with review dates; refer via GP to CAMHS where indicated; check local fire service provision.",
 ],
 "presentations": [
  "Fire-setting or fire play",
  "Stealing from peers or school",
  "Taking food or hiding food",
  "Behaviour that challenges",
  "Peer pressure and exploitation risk",
  "Risk to others",
  "Response to correction and repair after an incident",
 ],

 "bands": {
  "Early Years": {
   "applies": "N/A — not diagnosed; fire curiosity and taking things are developmental, but fire play is still a safety matter",
   "prevalence": "Not applicable — no diagnostic rate; rate of fire play not stated here.",
   "see": "Playing with matches or lighters, taking toys home from preschool. Respond with supervision, removing access, fire-safety education and teaching about ownership. Consider home supervision and welfare; involve the public health nurse or Tusla where there is concern.",
   "tools": ["SDQ (2–4 version)", "Ages & Stages Questionnaires (ASQ-3)"],
  },
  "School Age": {
   "applies": "RARELY — diagnosis is very rare; fire-setting and stealing are usually formulated within CD, ADHD, trauma or need",
   "prevalence": "Diagnostic rate not established in children — check before quoting.",
   "see": "Small fires in bins or toilets, playing with lighters, taking items from bags or the classroom. Same-day safety response for any fire. Formulate stealing: what, from whom, what happened to it. Check hunger, peers, bullying and home.",
   "tools": ["SDQ", "BASC-3", "Conners-4", "Functional behaviour assessment (ABC)", "CELF-5 UK", "WIAT-III UK",
             "Fire-setting history and risk interview — by CAMHS or a specialist service (e.g. Kolko & Kazdin's firesetting interviews — check reference) · MEASURES: frequency, motive, planning, access, response after · CANNOT TELL YOU: a diagnosis, or risk on its own without wider assessment · TIME: variable"],
  },
  "Adolescent": {
   "applies": "RARELY — kleptomania may begin in adolescence; both diagnoses remain rare, and CD or exploitation usually explains the behaviour",
   "prevalence": "Not established for adolescents — rate not stated here, check before quoting.",
   "see": "Fires with peers, shoplifting, stealing to fund substances or pay debts, secretive taking of unneeded items. Screen mood, substances and exploitation; ask the young person directly. Garda involvement is more likely; the Juvenile Liaison Officer is the usual route.",
   "tools": ["BASC-3 SRP", "Conners-4 self-report", "RCADS self-report", "MFQ (Mood and Feelings Questionnaire)", "Functional behaviour assessment (ABC)"],
  },
  "Young Adult": {
   "applies": "RARELY — kleptomania may be diagnosed by adult services; pyromania remains very rare",
   "prevalence": "Kleptomania about 0.3–0.6% in the general population (APA, 2022) — check before quoting.",
   "see": "Secretive, repeated stealing of unneeded items with shame afterwards; occasionally a history of fire-setting in files from Youthreach, probation or Oberstown. Ask what the history means now. Refer via GP to adult services.",
   "tools": ["Adult self-report measures via the service"],
  },
  "Special Setting": {
   "applies": "RARELY — taking items and fire interest are common but usually reflect limited understanding of ownership or risk",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Taking others' belongings, fascination with lighters or flames without grasp of danger. Explicit teaching, supervision and environmental safety come first; DSM-5-TR excludes pyromania where judgement is impaired by intellectual disability.",
   "tools": ["Functional behaviour assessment (ABC)", "Vineland-3 / ABAS-3", "Communication Matrix / AAC review", "Adaptive measure in place of IQ"],
  },
 },
})
