# Part I / Conditions sheet records — trauma and attachment (3.5 Trauma, attachment and loss)
# PTSD (incl. ICD-11 Complex PTSD) · Reactive Attachment Disorder · Disinhibited Social Engagement Disorder

CP_ROUTE = ("CHILD PROTECTION — if anything suggests abuse or neglect (a disclosure, an injury, sexualised behaviour, a "
            "child afraid to go home): listen, do not question or investigate, do not promise secrecy, write down the "
            "child's exact words with date and time. Report to Tusla as soon as practicable (Children First Act 2015; you "
            "are a mandated person) AND inform the school's DLP. Telling the DLP does NOT discharge your own duty. "
            "Supervision follows the action the same day; it never replaces it.")

CONDS = [
# ---------------------------------------------------------------------------------------------------------------
{
 "name": "Posttraumatic Stress Disorder (PTSD), including Complex PTSD",
 "code": "DSM-5-TR Posttraumatic Stress Disorder (with preschool subtype, 6 years and under) · ICD-11 6B40 PTSD · ICD-11 6B41 Complex PTSD (ICD-11 only — NOT a DSM-5-TR diagnosis) — check codes before quoting",
 "neps": "3. EMOTIONAL (3.5 Trauma, attachment and loss)",
 "coru": "1.2 · 1.12 · 3.1 · 3.2 · 3.10 · 5.28 · 5.31 · 5.32 · 5.45",
 "psi":  "2.2.2 · 2.2.4 · 1.2.5 · 1.3.14 · 3.3.2 · 3.3.4 · 1.2.8",
 "law":  "Children First Act 2015 · Children First: National Guidance (2017) · Child Protection Procedures for Primary and Post-Primary Schools (Department of Education — check current revision) · EPSEN Act 2004 · GDPR",

 "what_it_is": [
  "A trauma- and stressor-related disorder that can follow exposure to actual or threatened death, serious injury or sexual violence — experienced directly, witnessed, or learned about happening to someone close (APA, 2022, DSM-5-TR). The EVENT is a requirement; distress without a qualifying event is not PTSD.",
  "DSM-5-TR groups symptoms in four clusters: INTRUSION (memories, nightmares, flashbacks, distress at reminders), AVOIDANCE of reminders, NEGATIVE CHANGES IN THINKING AND MOOD (blame, shame, detachment, loss of interest), and ALTERED AROUSAL (hypervigilance, startle, irritability, sleep and concentration difficulty). Duration more than one month, with clear impairment.",
  "PRESCHOOL SUBTYPE (6 years and under) in DSM-5-TR: fewer symptoms required, and symptoms may show as play — repetitive play re-enacting themes, frightening dreams without recognisable content, regression, new fears (APA, 2022; building on Scheeringa's work with young children).",
  "ICD-11 (WHO, 2019/2022) defines PTSD more narrowly around three core elements: RE-EXPERIENCING IN THE PRESENT (vivid intrusions, flashbacks, nightmares — not simply remembering), AVOIDANCE, and a PERSISTENT SENSE OF CURRENT THREAT (hypervigilance, startle) (Brewin et al., 2017).",
  "COMPLEX PTSD is an ICD-11 diagnosis (6B41) and does NOT exist in DSM-5-TR. It requires the PTSD core PLUS 'disturbances in self-organisation': affect dysregulation, a persistently negative self-concept (worthless, defeated, ashamed), and difficulty sustaining relationships. It typically follows prolonged or repeated trauma from which escape was difficult — e.g. ongoing abuse or domestic violence (WHO, 2019/2022; Brewin et al., 2017). Evidence on applying it to children is still developing — check before relying on it.",
  "The best-supported psychological account (Ehlers & Clark, 2000) is that the trauma memory is poorly processed — stored as fragments that intrude, feel current, and are triggered by cues — while the person's appraisals ('I'm not safe', 'it was my fault') keep the sense of threat alive. This is why avoidance maintains it, and why trauma-focused therapy works.",
  "It is TREATABLE. Trauma-focused CBT for children and young people has the strongest evidence base and is the NICE first-line recommendation (NICE, 2018, NG116 — check for updates). Treatment is delivered by clinical services (CAMHS, Primary Care Psychology), not by the school EP.",
 ],
 "what_it_is_not": [
  "NOT the inevitable result of a frightening event. Alisic et al. (2014), meta-analysing trauma-exposed children and adolescents, found around 16% developed PTSD; most did not. Distress in the first weeks is expected and usually settles.",
  "NOT the same as 'trauma', 'complex trauma', 'developmental trauma' or ACEs. Those are descriptive terms (Part D lists them as NOT a DSM diagnosis). 'Developmental trauma disorder' was proposed (van der Kolk, 2005) and not adopted in DSM-5. Complex PTSD is a specific ICD-11 diagnosis, not a synonym for 'had a hard childhood'.",
  "NOT something an ACE score can identify. The ACE score was built for population epidemiology (Felitti et al., 1998); its originators warn against using it to screen or predict for individuals (Anda et al., 2020).",
  "NOT helped by getting the child to talk it all through straight away. NICE (2018, NG116) advises against psychologically-focused debriefing to prevent PTSD. Immediate support is practical safety, calm, connection and routine (Hobfoll et al., 2007) — the NEPS critical incident approach follows the same logic.",
  "NOT always visible as fear. In children it often looks like irritability, anger, poor concentration, 'daydreaming' (dissociation), sleep loss and falling attainment — and is routinely misread as ADHD, conduct difficulty or laziness.",
  "NOT permanent damage. 'Traumatised for life' framing is inaccurate and harmful; recovery is common and effective treatment exists. Equally NOT 'children are resilient, they'll forget' — untreated PTSD can persist for years.",
  "NOT a reason to drop expectations. Trauma-informed practice means predictability, safety and relationship WITH clear, calm boundaries — not the absence of structure.",
 ],
 "prevalence": [
  "AFTER EXPOSURE: about 15.9% of trauma-exposed children and adolescents developed PTSD in Alisic et al.'s (2014) meta-analysis. Rates were higher after interpersonal trauma (assault, abuse) than non-interpersonal (accidents, disasters), and higher in girls.",
  "BY AGE 18 (UK cohort): Lewis et al. (2019), E-Risk cohort in England and Wales, reported that 31.1% had experienced trauma and 7.8% met criteria for PTSD at some point by 18; only 20.6% of those with PTSD had received help from mental health professionals.",
  "IRELAND: no national child PTSD prevalence figure is stated here — check before quoting. Do not transfer UK or US figures to an Irish caseload as if local.",
  "COMPLEX PTSD IN CHILDREN: rate not stated here — the ICD-11 diagnosis is recent and child prevalence studies are limited. Check before quoting.",
  "EARLY YEARS 0–5: rate not stated here. Diagnosis at this age is specialist-only and uses the preschool subtype.",
  "SCHOOL AGE AND ADOLESCENT: most identification happens here, after a known event (road traffic accident, assault, sudden death witnessed, medical trauma, domestic violence) or when a child protection concern emerges.",
  "SEX RATIO: higher rates in girls in Alisic et al. (2014) — 32.9% for girls after interpersonal trauma vs 8.4% for boys after non-interpersonal trauma. Sex differences in Lewis et al. (2019) not stated here — check before quoting. Boys' presentations are more often read as behaviour.",
 ],
 "cooccurring": [
  {"name": "DEPRESSION AND LOW MOOD", "rate": "elevated — rate not stated here, check",
   "presents": "withdrawal, loss of interest, hopelessness, shame and self-blame. Overlaps with the 'negative mood and cognition' cluster; ask about both. Screen for risk every time."},
  {"name": "ANXIETY DISORDERS", "rate": "elevated — rate not stated here, check",
   "presents": "generalised worry, separation anxiety in younger children, school avoidance. Separate trauma-cued fear (reminders) from general anxiety — they need different help."},
  {"name": "SELF-HARM AND SUICIDAL THINKING", "rate": "high — 48.8% of young people with lifetime PTSD reported self-harm and 20.1% a suicide attempt by age 18 (Lewis et al., 2019)",
   "presents": "concealed; may be the first thing a school sees. Same-day risk protocol, never a routine referral."},
  {"name": "ADHD (and the ADHD look-alike)", "rate": "elevated and a major differential — rate not stated here, check",
   "presents": "hyperarousal, poor concentration and restlessness look identical to ADHD. Establish onset: ADHD is present from early development; trauma symptoms follow an event. They can also co-occur."},
  {"name": "CONDUCT / OPPOSITIONAL DIFFICULTY", "rate": "elevated — rate not stated here, check",
   "presents": "irritability, anger at perceived threat, reactive aggression. A child in 'threat mode' reacts to raised voices and cornering; punitive responses tend to escalate it."},
  {"name": "SUBSTANCE USE (adolescent)", "rate": "elevated — rate not stated here, check",
   "presents": "self-medicating sleep, intrusions and arousal. Ask routinely at post-primary; refer via CAMHS or local youth addiction services."},
  {"name": "SLEEP DIFFICULTY", "rate": "very common — part of the arousal cluster",
   "presents": "nightmares, fear of the dark, late settling. A chronically tired child screens positive on everything; always ask."},
  {"name": "LEARNING AND ATTAINMENT DROP", "rate": "common — rate not stated here, check",
   "presents": "concentration and memory difficulties after an event, falling grades, missed learning during disrupted periods. Assess attainment and ask what was missed before concluding a learning difficulty."},
 ],
 "recommendations": [
  "SAFETY AND PREDICTABILITY FIRST. Consistent routine, forewarning of change (fire drills, substitute teachers, trips), a known adult, and a known calm space the pupil can go to without having to explain. This is what trauma-informed practice means in a classroom.",
  "IDENTIFY AND REDUCE REMINDERS where reasonable — a curriculum topic, a sound, a route, a date. Agree with the pupil and parent how a reminder will be handled; do not remove all mention of the event without the family's view.",
  "REGULATE BEFORE YOU REASON. When the pupil is in threat mode, lower voice, reduce demands, give space and time; discuss afterwards. Emotion coaching (Gottman's model, used in UK and Irish schools — evidence in schools still limited, check) is a reasonable staff approach.",
  "ADJUST ACADEMIC DEMAND TEMPORARILY: reduced homework, extended time, notes provided, flexibility on assessments. For State Examinations, check RACE eligibility with the school — do not promise it.",
  "STAFF CONSULTATION rather than direct therapeutic work: help the class teacher build a formulation of THIS pupil's triggers, early signs and what helps. NEPS critical incident guidance where the event affected the school community.",
  "EVIDENCE: be honest that whole-school 'trauma-informed' programmes have a thin evaluation base — Maynard et al. (2019) found no rigorous trials. Recommend specific, reviewable adjustments with a review date rather than a branded package.",
  "CONTINUUM LEVEL: School Support, or School Support Plus where CAMHS, Primary Care or Tusla are involved. Name the level in the report.",
  "REFER: GP to Primary Care Psychology (milder) or CAMHS (moderate–severe, or with risk) for assessment and trauma-focused treatment. NICE (2018, NG116 — check for updates) recommends individual trauma-focused CBT for children and young people, with EMDR as an option for older children in some circumstances; drug treatment is not recommended for under-18s. The EP does not deliver trauma processing and does not advise on medication (PSI 2.2.2).",
  "TUSLA: where the trauma is abuse or neglect, or the child is not currently safe, the child protection route comes BEFORE any recommendation. For a child in care, involve the allocated Tusla social worker in planning.",
  "DO NOT interview the child about what happened, use trauma questionnaires with a young child, use an ACE score as a screen, or run a debriefing session. DO NOT write 'has PTSD' or 'has Complex PTSD' unless a clinician has diagnosed it — write 'presents with difficulties consistent with a trauma response; referral recommended'.",
 ],
 "explain_parent": [
  "'After something frightening, the brain's alarm system can stay switched on. That's why he's jumpy, not sleeping, and snapping at everyone. It's a normal system working too hard — not him being bold, and not him being damaged.'",
  "'Most children's alarm settles in the weeks after. When it doesn't — when the memories keep coming back as if it's happening now, and he's avoiding everything connected with it — that's when we ask for a specialist to look at it. There is good treatment for this.'",
  "'You don't have to get him to talk about it, and please don't push. Let him know he can talk when he wants to, and keep the everyday routine as steady as you can. Routine is one of the most healing things there is.'",
  "'My job is to help school get this right — how the day is set up, what the teachers do when he's upset, what we ease off on for now. The treatment itself is done by Primary Care Psychology or CAMHS, through your GP.'",
  "IF THE PARENT WAS ALSO AFFECTED: 'This happened to your family, not just to him. How are you doing?' Signpost the parent's own GP. A regulated adult is the child's best support.",
  "SIGNPOST: GP; Primary Care Psychology or CAMHS; Irish Childhood Bereavement Network where a death was involved; the NEPS critical incident leaflets the school holds.",
 ],
 "explain_teacher": [
  "'What you're seeing is a threat response, not defiance. When something reminds her of what happened, her body goes into protection mode — fight, flight or freeze. Thinking and learning go offline until she feels safe again.'",
  "'The zoning out is worth noticing. It can be dissociation — the mind stepping away — rather than daydreaming. Name it gently, bring her back to the room, and don't reprimand it.'",
  "'Predictability is the intervention. Warn her about fire drills, visitors, room changes, a sub. Surprise is the enemy.'",
  "'Calm first, consequences later. A raised voice or being cornered will escalate things. Give space, lower the demand, and talk it through when she is settled.'",
  "'You're not her therapist, and you don't need to hear the story. What she needs from you is a safe, steady classroom and one adult she knows is on her side.'",
  "'If she ever tells you something about being hurt, listen, don't ask leading questions, don't promise to keep it secret, write down her words and go straight to the DLP — and remember your own reporting duty.'",
 ],
 "explain_child": [
  "YOUNGER: 'When something really scary happens, your body gets a guard dog to keep you safe. Sometimes the guard dog keeps barking even when the scary thing is over. That's why you might feel jumpy or have bad dreams. The grown-ups are going to help the guard dog learn it can rest.'",
  "OLDER: 'After a frightening experience your brain's alarm system can get stuck on high. It fires at things that remind you of what happened, even when you're actually safe. That's not you being weak — it's your brain trying too hard to protect you. There are people whose job is to help the alarm reset, and it works for most young people.'",
  "DO NOT ask what happened. You are not there to hear the trauma story. Ask about school: 'What helps on a hard day?' 'Who in school do you feel safe with?' 'What would you like teachers to know — and not know?'",
  "GIVE CONTROL: children who have had control taken away need choices. 'You can stop at any time.' 'You can pass on any question.' Mean it.",
  "BE CLEAR ABOUT CONFIDENTIALITY at the start, in words they understand: 'Most of what you tell me stays between us and the people helping you. If I'm worried someone is hurting you or you might hurt yourself, I have to tell someone whose job is to keep you safe — and I'll tell you first.'",
 ],
 "analogies": [
  "THE SMOKE ALARM: 'A smoke alarm is meant to go off for fire. After a scary event, it can start going off for toast. The alarm isn't broken — it's oversensitive, and it can be reset.' Works with parents, teachers and older children; explains startle and overreaction without blame.",
  "THE UNFILED MEMORY (Ehlers & Clark, 2000, in plain terms): 'Most memories get filed away with a date on them — this happened then. A trauma memory can get stuffed in the drawer without a date, so when it falls out it feels like it's happening now. Therapy helps file it properly.' Good for adolescents and parents deciding about treatment.",
  "THE FLIPPED LID (Siegel's hand model of the brain): 'When the thinking part flips off, you can't reason with someone — you wait until the lid comes back down.' Very usable with teachers and children from about 8; keep it as a teaching image, not neuroscience.",
  "THE WINDOW OF TOLERANCE (Siegel, 1999): 'We all have a zone where we can think and learn. Trauma makes the window narrower — so it takes less to tip into panic or shutdown.' Good for staff planning — the aim is to widen the window, not to push through.",
 ],
 "language": [
  "Use 'has experienced a traumatic event', 'trauma-exposed', 'trauma response'. Reserve 'PTSD' and 'Complex PTSD' for when a clinician has made the diagnosis.",
  "When writing Complex PTSD, add '(ICD-11)'. It is not a DSM-5-TR diagnosis and some services will not use it.",
  "Avoid 'traumatised child', 'damaged', 'broken', 'a trauma case'. The child is not the event.",
  "'Victim' or 'survivor' — ask the young person; many prefer neither. Mirror the family's language.",
  "Avoid casual use of 'triggered', 'traumatic' for ordinary upset, and 'PTSD' for a bad week. Over-use dilutes the term and can frighten families.",
  "In reports, describe behaviour ('left the room when the fire alarm sounded, returned after ten minutes') rather than interpret it ('was triggered'). PSI 1.2.8 requires labelling opinion as opinion.",
 ],
 "red_flags": [
  "RED FLAG — any indication that the trauma is ONGOING (abuse, domestic violence, a child unsafe at home). " + CP_ROUTE,
  "RED FLAG — self-harm, suicidal thinking, or statements like 'I'd be better off dead'. Same-day risk protocol; do not end the session and leave the young person alone with it; inform parents unless that would increase risk; supervision the same day.",
  "RED FLAG — dissociation that is frequent, prolonged or unsafe (wandering, not responding, lost time), or a sudden change in presentation. Medical and CAMHS referral; rule out seizures via GP.",
  "RED FLAG — sexualised behaviour in a young child beyond developmental expectation. Record precisely and follow the child protection route; do not interpret in isolation.",
  "BOUNDARY — you do not diagnose PTSD or Complex PTSD, do not deliver trauma-focused therapy, do not conduct trauma or disclosure interviews, and do not screen young children for trauma — refer. PSI 2.2.2, 2.2.3, 2.2.4.",
  "BOUNDARY — you do not investigate. Tusla and An Garda Síochána investigate. Questioning a child about abuse can contaminate evidence and re-traumatise.",
  "WATCH — your own reaction. Hearing trauma material affects practitioners; CORU 5.45 names this. Take it to supervision.",
 ],
 "child_voice": [
  "'MY THOUGHTS ABOUT SCHOOL' (NEPS) — about school, not about the event, which is exactly why it is safe here. Surfaces the parts of the day that are hard. → https://www.gov.ie/en/publication/52ee2-neps-resources-and-publications/",
  "SAFE PEOPLE / HELPING HAND — the child traces a hand and names an adult on each finger they could go to. Good because it builds the safety network rather than exploring the trauma, and it tells you who the key adult should be. Links to the Stay Safe programme already in Irish primary schools.",
  "SCALING (0–10 'how calm is school today') with a follow-up: 'what makes it a 6 not a 3?' Good because it finds exceptions and gives a review measure without discussing the event.",
  "DAY MAPPING — green/amber/red timeline of the school day. Good because it locates reminders and hard moments in time and place, which is what the classroom plan needs.",
  "IDEAL SELF / 'ME AT MY BEST' drawing (Moran, 2001, for older pupils) — good because it gives an adolescent a way to describe what they want school to be like without disclosure.",
  "RULE FOR ALL OF THEM: the child chooses whether to take part and can stop at any time; nothing here is a route to disclosure, and if a disclosure comes anyway you follow the child protection route.",
 ],
 "questions": [
  "Q: 'Should we get her to talk about it?' — A: 'Let her know she can, and don't push. Forcing a child to go over it — or a one-off debriefing — isn't recommended and can make things worse. If the memories keep intruding after a few weeks, specialist trauma-focused therapy is the place to talk it through, with someone trained to do it safely.'",
  "Q: 'Has he got PTSD?' — A: 'I can't diagnose that — it's a clinical diagnosis made by Primary Care Psychology or CAMHS. What I can say is that what you're describing is consistent with a trauma response, and I think it's worth a referral through your GP. In the meantime, here's what school will do.'",
  "Q: 'What's Complex PTSD? I read about it online.' — A: 'It's a diagnosis in the World Health Organization's ICD-11, not in the American DSM. It's used when, on top of PTSD, someone has ongoing difficulty with managing emotions, how they see themselves, and relationships — usually after long-term trauma. It's only diagnosed by clinicians and research in children is still developing.'",
  "Q: 'She was only four when it happened — surely she won't remember?' — A: 'Young children can be affected even without clear memories; it often shows in play, sleep, fears and going back a stage. That's why a specialist should look at it, rather than anyone screening her in school.'",
  "Q: 'Is it ADHD or is it trauma?' — A: 'It can look identical — restless, distracted, reactive. The key question is timing: ADHD is there from early on in development, a trauma response follows an event. Sometimes it's both. I'd want a full history before anyone concludes either.'",
  "Q: (teacher) 'Isn't trauma-informed just letting them off?' — A: 'No. It's calm, predictable boundaries — consequences still happen, but after the child is regulated, not in the middle of a threat response. It's about timing and tone, not dropping expectations.'",
  "Q: 'Will this affect him for life?' — A: 'Most children recover, especially with support. There's good treatment when symptoms persist. What helps most right now is a steady routine and adults who stay calm.'",
  "Q: 'What's his ACE score?' — A: 'ACE scores were designed to study populations, not to predict what happens to one child. The people who developed them warn against using them that way. I'd rather describe what he's going through and what helps.'",
 ],
 "supervision": [
  "Bring any case with a possible child protection element BEFORE the school meeting — and remember supervision comes after any required report, not instead of it. Ask your supervisor to walk through the Tusla route with you on a real example.",
  "Ask where the line sits between school-based support and therapy in your service, and what you would say if a school asks you to 'do some trauma work' with a pupil.",
  "Bring the ADHD referral that you suspect is a trauma response (or the reverse). Ask how your supervisor weighs onset and history.",
  "Ask about the local route: Primary Care Psychology versus CAMHS thresholds for trauma, and what Tusla-commissioned therapeutic services exist locally — this varies.",
  "Bring your own reaction. If a case stayed with you, say so. CORU 5.45 and PSI 4.1.2 treat this as professional practice, not personal weakness.",
  "Ask how the service handled its last critical incident and what the EP role was — this is when you will first meet trauma at scale.",
 ],
 "reflection": [
  "ON HOW I EXPLAINED IT — Did I give the parent something that reduced blame (theirs and the child's), or did I give a lecture on the stress response?",
  "ON THE STORY — Did I find myself wanting to know what happened? Why? Did that curiosity serve the child or me?",
  "ON THE BOUNDARY — Was I asked to do something that was therapy? What did I say? Would I say it the same way again?",
  "ON THE DIFFERENTIAL — Did I rule out ADHD, a learning difficulty, hearing, sleep and ongoing harm, or did 'trauma' become the explanation for everything once it was mentioned?",
  "ON LANGUAGE IN THE REPORT — Did I write 'triggered', 'traumatised', 'PTSD' without a diagnosis? Did I record Complex PTSD as ICD-11?",
  "ON MYSELF — What did this case leave me with? Did I bring it to supervision or carry it home? (CORU 5.45.)",
  "WHAT GOOD LOOKS LIKE: 'The school wanted me to see the pupil and \"help him talk about it\". I explained why that isn't my role or good practice, and instead we mapped his day with his teacher, found three reminders and a safe adult, and I wrote the GP referral letter with his mother. He wasn't asked to tell the story once.'",
  "WHAT POOR LOOKS LIKE: 'Pupil presents with trauma. Trauma-informed approach recommended.' — no formulation, no differential, no specific adjustment, no referral, no check on safety.",
 ],
 "citations": [
  "American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.; DSM-5-TR). American Psychiatric Publishing.",
  "World Health Organization. (2019/2022). International classification of diseases (11th rev.; ICD-11): 6B40 Post traumatic stress disorder; 6B41 Complex post traumatic stress disorder. https://icd.who.int/ — check codes before quoting.",
  "National Institute for Health and Care Excellence. (2018). Post-traumatic stress disorder (NICE guideline NG116). https://www.nice.org.uk/guidance/ng116 — check for updates.",
  "Alisic, E., Zalta, A. K., van Wesel, F., Larsen, S. E., Hafstad, G. S., Hassanpour, K., & Smid, G. E. (2014). Rates of post-traumatic stress disorder in trauma-exposed children and adolescents: Meta-analysis. British Journal of Psychiatry, 204(5), 335–340.",
  "Lewis, S. J., Arseneault, L., Caspi, A., Fisher, H. L., Matthews, T., Moffitt, T. E., Odgers, C. L., Stahl, D., Teng, J. Y., & Danese, A. (2019). The epidemiology of trauma and post-traumatic stress disorder in a representative cohort of young people in England and Wales. The Lancet Psychiatry, 6(3), 247–256.",
  "Brewin, C. R., Cloitre, M., Hyland, P., Shevlin, M., Maercker, A., Bryant, R. A., Humayun, A., Jones, L. M., Kagee, A., Rousseau, C., Somasundaram, D., Suzuki, Y., Wessely, S., van Ommeren, M., & Reed, G. M. (2017). A review of current evidence regarding the ICD-11 proposals for diagnosing PTSD and complex PTSD. Clinical Psychology Review, 58, 1–15.",
  "Ehlers, A., & Clark, D. M. (2000). A cognitive model of posttraumatic stress disorder. Behaviour Research and Therapy, 38(4), 319–345.",
  "Maynard, B. R., Farina, A., Dell, N. A., & Kelly, M. S. (2019). Effects of trauma-informed approaches in schools: A systematic review. Campbell Systematic Reviews, 15(1–2), e1018.",
  "Anda, R. F., Porter, L. E., & Brown, D. W. (2020). Inside the adverse childhood experience score: Strengths, limitations, and misapplications. American Journal of Preventive Medicine, 59(2), 293–295.",
  "Department of Children and Youth Affairs. (2017). Children First: National guidance for the protection and welfare of children. Government Publications.",
  "Hobfoll, S. E., Watson, P., Bell, C. C., Bryant, R. A., Brymer, M. J., Friedman, M. J., et al. (2007). Five essential elements of immediate and mid-term mass trauma intervention: Empirical evidence. Psychiatry, 70(4), 283–315.",
  "Felitti, V. J., Anda, R. F., Nordenberg, D., Williamson, D. F., Spitz, A. M., Edwards, V., Koss, M. P., & Marks, J. S. (1998). Relationship of childhood abuse and household dysfunction to many of the leading causes of death in adults: The Adverse Childhood Experiences (ACE) Study. American Journal of Preventive Medicine, 14(4), 245–258.",
  "Jones, L., Bellis, M. A., Wood, S., Hughes, K., McCoy, E., Eckley, L., Bates, G., Mikton, C., Shakespeare, T., & Officer, A. (2012). Prevalence and risk of violence against children with disabilities: A systematic review and meta-analysis of observational studies. The Lancet, 380(9845), 899–907.",
 ],

 "pathway": {
  "age": "Any age after a qualifying event; most school referrals are at School Age or Adolescent, either weeks to months after a known event or when a child protection concern surfaces. Onset can be delayed. The preschool subtype exists but diagnosis at 0–6 is specialist-only.",
  "who_diagnoses": "Ireland: CAMHS (moderate–severe or with risk) or Primary Care Psychology (milder), via the GP; for children in care, Tusla may commission assessment — check locally. Complex PTSD is diagnosed only by clinicians using ICD-11. The EP does not diagnose.",
  "who_wrote_report": "CAMHS psychiatrist or clinical psychologist; Primary Care psychologist; a Tusla-commissioned or private clinical psychologist; a paediatric liaison team after medical trauma. A school-completed SDQ or rating scale is not a trauma assessment.",
  "refer_to": "GP → Primary Care Psychology or CAMHS for assessment and trauma-focused treatment. Tusla (and DLP) where there is any protection concern — same day. NEPS critical incident support where the school community is affected. Irish Childhood Bereavement Network resources where a death is involved.",
  "sooner": "'Early on, most children's distress settles by itself, and watching carefully is exactly the right thing to do. Coming now, when it hasn't settled, is the right time — not late.'",
 },
 "differential": [
  "ADHD — onset in early development and across settings versus onset after an event; both can be present. History is the discriminator.",
  "ADJUSTMENT DISORDER / NORMAL STRESS REACTION — distress after a stressor without the intrusion–avoidance–threat pattern, or within the first month (acute stress). Expected; monitor.",
  "BEREAVEMENT / PROLONGED GRIEF — longing and preoccupation with the person who died, rather than threat and intrusion. Can co-occur after a traumatic death.",
  "ANXIETY DISORDER — fear not tied to trauma reminders; no qualifying event.",
  "ATTACHMENT DIFFICULTY OR DISORDER — relationship-based difficulties after early neglect or care disruption, rather than event-based intrusions (see RAD / DSED rows).",
  "SEIZURES OR MEDICAL CAUSES of 'zoning out' — refer via GP; do not assume dissociation.",
  "ONGOING HARM — not a differential diagnosis but the first thing to rule out. A child who is still unsafe does not have a 'post'-traumatic problem.",
 ],
 "next": [
  "Safety first: if any protection concern exists, report to Tusla and inform the DLP today; supervision after.",
  "Consult with school and parents to build a formulation of triggers, early signs and what helps — no trauma interview with the child.",
  "Write specific classroom adjustments at School Support or School Support Plus with a review date.",
  "Refer via GP to Primary Care Psychology or CAMHS where symptoms persist beyond the first month or impair functioning.",
  "Review attainment and the ADHD/learning differential before closing the case.",
 ],
 "presentations": [
  "Complex or developmental trauma (descriptive — not a diagnosis)",
  "Adverse Childhood Experiences (ACEs)",
  "Bereavement reaction",
  "Displacement, asylum and resettlement",
  "Hypervigilance and exaggerated startle",
  "Dissociation / 'zoning out'",
  "Nightmares and sleep disruption",
  "Emotional dysregulation after an event",
  "Trauma-informed classroom practice (the systemic response)",
 ],

 "bands": {
  "Early Years": {
   "applies": "YES — DSM-5-TR preschool subtype (6 and under); identification and diagnosis belong to specialist services only",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Repetitive play re-enacting themes, regression (toileting, speech, sleep), separation distress, new fears, frightening dreams without clear content, irritability and tantrums. Parent and setting report only; do not screen a preschooler for trauma — refer via GP to Primary Care or CAMHS, and to Tusla if there is any protection concern.",
   "tools": ["SDQ (2–4 version)"]},
  "School Age": {
   "applies": "YES — most event-linked referrals arrive here",
   "prevalence": "About 16% of trauma-exposed children and adolescents develop PTSD (Alisic et al., 2014).",
   "see": "Re-enactment in play or drawing, intrusive memories, avoidance of places and topics, startle, poor sleep, falling concentration and attainment, somatic complaints and irritability misread as behaviour. Parent and teacher report, NEPS critical incident materials where relevant, consultation on trauma-informed practice; do not conduct trauma interviews.",
   "tools": ["SDQ", "BASC-3", "RCADS", "Piers-Harris 3"]},
  "Adolescent": {
   "applies": "YES — adult-like presentation; Complex PTSD features may be described",
   "prevalence": "7.8% lifetime PTSD by age 18 in an England and Wales cohort (Lewis et al., 2019); no Irish figure stated here.",
   "see": "Flashbacks, avoidance, numbing, shame and self-blame, withdrawal from peers, risk-taking, substance use, self-harm. Self-report only where safe and where the young person has chosen to speak; always supervision; CAMHS pathway. Your role is school support, not trauma treatment.",
   "tools": ["RCADS self-report", "MFQ (Mood and Feelings Questionnaire)", "Beck Youth Inventories-2", "BASC-3 SRP"]},
  "Young Adult": {
   "applies": "YES — via adult mental health services",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Presentation as for adults; Complex PTSD more often considered. The EP role is usually educational — third-level disability supports and exam arrangements — while treatment sits with adult mental health services or the GP. Signpost Jigsaw (12–25) for support, not trauma treatment.",
   "tools": ["Adult self-report measures via the service"]},
  "Special Setting": {
   "applies": "YES — and often missed through diagnostic overshadowing",
   "prevalence": "Rate not stated here. Children with disabilities are at higher risk of violence (Jones et al., 2012, Lancet meta-analysis) — check before quoting figures.",
   "see": "Where language is limited, trauma shows as behaviour change, regression, sleep disturbance, self-injury or new fear of a person or place. Do not attribute a change to the existing diagnosis until harm, pain and illness are ruled out. Setting stability and staff consistency are the intervention.",
   "tools": ["Functional behaviour assessment (ABC)", "Vineland-3 / ABAS-3"]},
 },
},

# ---------------------------------------------------------------------------------------------------------------
{
 "name": "Reactive Attachment Disorder (RAD)",
 "code": "DSM-5-TR Reactive Attachment Disorder (Trauma- and Stressor-Related Disorders) · ICD-11 6B44 — check code before quoting",
 "neps": "3. EMOTIONAL (3.5 Trauma, attachment and loss) — and 4. SOCIAL (4.2 Relationships with adults)",
 "coru": "1.2 · 1.12 · 3.1 · 3.2 · 5.28 · 5.29 · 5.32 · 5.39",
 "psi":  "2.2.2 · 2.2.4 · 1.2.8 · 3.3.2 · 3.3.4 · 1.3.11",
 "law":  "Children First Act 2015 · Child Care Act 1991 · Children First: National Guidance (2017) · EPSEN Act 2004 · GDPR",

 "what_it_is": [
  "A RARE disorder of the child's attachment behaviour toward caregivers, arising from SEVERELY INSUFFICIENT CARE in early childhood (APA, 2022, DSM-5-TR). It sits in the Trauma- and Stressor-Related Disorders chapter, not with neurodevelopmental conditions.",
  "CORE PICTURE: a consistent pattern of INHIBITED, emotionally WITHDRAWN behaviour toward adult caregivers — the child rarely seeks comfort when distressed and rarely responds to comfort when offered — plus social and emotional disturbance: minimal responsiveness to others, limited positive affect, and unexplained irritability, sadness or fearfulness even during non-threatening interactions with caregivers.",
  "REQUIRES a history of extremes of insufficient care: social neglect or deprivation, repeated changes of primary caregiver, or rearing in settings that severely limit the chance to form selective attachments (e.g. some institutional care). The care is presumed responsible for the behaviour.",
  "Further DSM-5-TR requirements: evident before age 5; developmental age of at least 9 months; criteria for autism NOT met. ICD-11 (WHO, 2019/2022) describes the same core picture.",
  "The underlying idea (Zeanah & Gleason, 2015) is that the child has had no consistent adult to form a selective attachment WITH — it is the ABSENCE or severe distortion of attachment, not an unusual attachment style.",
  "Features often REDUCE substantially once the child is placed in sensitive, stable care (Zeanah & Gleason, 2015 — check), which is itself diagnostically informative and hopeful.",
  "Diagnosis is specialist and multi-source: history of care, observation with caregivers and strangers, and ruling out autism, intellectual disability and depression. It is not made from school observation, from a questionnaire, or from a care history alone.",
 ],
 "what_it_is_not": [
  "NOT the same as 'attachment difficulties' or 'attachment issues' as used loosely in schools. Most children described that way do NOT have RAD. Woolgar and Baldock (2015) found attachment problems were over-identified in looked-after and adopted children by community services, while more common and treatable problems (ADHD, conduct, anxiety) were missed.",
  "NOT an insecure attachment pattern. Avoidant, ambivalent and disorganised patterns from the Strange Situation are research classifications of a relationship, not diagnoses; insecure patterns are common in the general population. Granqvist et al. (2017) warn specifically against using disorganised attachment as a diagnostic or child protection marker.",
  "NOT caused by ordinary parenting stress, working parents, crèche or a parent's depression alone. RAD requires EXTREMES of insufficient care.",
  "NOT autism. Both can look socially withdrawn, but RAD requires the care history and resolves substantially with good care; autism is neurodevelopmental, present regardless of care quality, and includes restricted and repetitive behaviour. DSM-5-TR excludes RAD if autism criteria are met (Davidson et al., 2015 on telling them apart).",
  "NOT a label for a child who is 'controlling', 'manipulative' or aggressive. Those words describe behaviour with many possible causes and do not make a RAD diagnosis.",
  "NOT treated by 'holding therapy', 'rebirthing' or coercive 'attachment therapy'. These are harmful, have caused deaths, and are rejected by NICE (2015, NG26 — check wording) and by an APSAC task force (Chaffin et al., 2006).",
  "NOT a reason to exclude other explanations. Children with this history also have high rates of language difficulty, ADHD and — where there was prenatal alcohol exposure — FASD. Assess these.",
 ],
 "prevalence": [
  "OVERALL: uncommon, and population data are scarce. Minnis et al. (2013) screened all 1,646 children aged 6–8 in a deprived urban UK area and estimated RAD prevalence at 1.40% (95% CI 0.94–2.10) — the authors concluded that in this deprived population RAD 'was not rare'. The rate in less deprived populations is not established — check before quoting.",
  "HIGHER in children with histories of institutional care, severe neglect or multiple placements; the Bucharest Early Intervention Project (Zeanah et al., 2005) found signs of RAD more common in institutionalised children. Rate not stated here — check.",
  "IRELAND: no national figure stated here — check before quoting. Children in care of Tusla are the group where the question most often arises.",
  "EARLY YEARS 0–5: the age at which it is defined and diagnosed (evident before age 5).",
  "SCHOOL AGE AND OLDER: RAD can be present at 6–8 (Minnis et al., 2013), so it is not only an early-years question; but what schools see is more often a descriptive attachment-related difficulty, ADHD, conduct difficulty, DLD or trauma.",
  "SEX RATIO: rate not stated here — check before quoting.",
 ],
 "cooccurring": [
  {"name": "LANGUAGE DELAY / DLD", "rate": "elevated in children with early neglect — rate not stated here, check",
   "presents": "limited verbal expression and comprehension that can look like social withdrawal. Refer to SLT; do not attribute to attachment."},
  {"name": "DEVELOPMENTAL DELAY / INTELLECTUAL DISABILITY", "rate": "elevated — rate not stated here, check",
   "presents": "global delay after deprivation. Diagnosis requires developmental age of at least 9 months; assess developmental level before interpreting social behaviour."},
  {"name": "ADHD", "rate": "elevated after early deprivation (Kumsta et al., 2010) — rate not stated here, check",
   "presents": "inattention and overactivity that persist in good care. Assess separately with standard ADHD routes."},
  {"name": "FASD (prenatal alcohol exposure)", "rate": "elevated in care-experienced and adopted children — rate not stated here, check",
   "presents": "learning, attention, memory and behaviour difficulties easily misattributed to attachment. Ask about prenatal history; refer to paediatrics."},
  {"name": "DEPRESSION / LOW MOOD", "rate": "elevated — rate not stated here, check",
   "presents": "withdrawal and limited positive affect overlap with RAD; depression does not require the care history and affects relationships beyond caregivers."},
  {"name": "PTSD AND TRAUMA RESPONSES", "rate": "elevated where maltreatment occurred — rate not stated here, check",
   "presents": "hypervigilance, startle, intrusions. Trauma is event-based; RAD is relationship-based. Both can be present."},
 ],
 "recommendations": [
  "DESCRIBE, DO NOT LABEL. In the report, describe the relational behaviour you observed and in what context; do not write 'attachment disorder' or 'attachment issues' unless a clinician has diagnosed RAD.",
  "A KEY ADULT in school — one consistent, available person who greets the child, checks in at set times and is the go-to at hard moments (Bomber, 2007). Plan for that adult's absence in advance.",
  "PREDICTABILITY: visual timetable, forewarning of change, planned transitions between rooms, teachers and years. Changes of adult are high-cost for this group.",
  "OFFER COMFORT WITHOUT DEMANDING IT. The child may not seek help or accept comfort; staff keep offering calmly and do not interpret rejection as rudeness or take it personally.",
  "RELATIONSHIP AND BOUNDARIES TOGETHER. Clear, calm limits delivered by a known adult; avoid exclusionary or shaming sanctions that confirm the child's expectation of rejection.",
  "ASSESS THE REST: language (SLT), learning and attainment, attention, and — where prenatal alcohol exposure is possible — refer to paediatrics for FASD consideration. Attachment is not the whole formulation.",
  "WORK WITH THE CARERS. Foster, kinship or adoptive parents often carry the most change; school and home using the same language and routines matters. For a child in care, include the Tusla social worker and check who holds consent — this depends on the care order and must be confirmed.",
  "CONTINUUM LEVEL: School Support Plus — Tusla, CAMHS or other services will usually be involved.",
  "REFER: CAMHS or specialist infant/child mental health service for assessment; SLT; paediatrics (development, FASD). NICE (2015, NG26 — check for updates) recommends interventions focused on caregiver sensitivity, such as video-feedback programmes, for younger children in care or adopted.",
  "DO NOT recommend holding therapy, rebirthing or any coercive 'attachment therapy'. DO NOT use an attachment label to explain behaviour that has not been assessed.",
 ],
 "explain_parent": [
  "FOR FOSTER, KINSHIP OR ADOPTIVE PARENTS: 'Before he came to you, he didn't have one steady adult he could count on. So he learned not to go to adults for comfort — because it didn't come. What you're doing now, being there over and over even when he pushes you away, is exactly what helps.'",
  "'The good news from research is that children often start to show attachment to a new carer once care is steady and sensitive. It takes time and it's not a straight line.'",
  "'Lots of children who've had a hard start get called \"attachment\" in school. The actual attachment disorder is rare and is diagnosed by a specialist. I'd want us to look at everything — language, learning, attention — not just attachment.'",
  "'Please be wary of anyone offering \"attachment therapy\" that involves holding a child down or forcing closeness. That approach is harmful and is not recommended.'",
  "WITH A BIRTH PARENT (where appropriate and safe): avoid blame. 'What matters now is what helps him from here, and that's what we're planning.' If you have any protection concern, follow the child protection route first.",
  "SIGNPOST: allocated Tusla social worker; Irish Foster Care Association; adoption support services (check current provider); CAMHS via GP.",
 ],
 "explain_teacher": [
  "'This child learned early that adults weren't reliable. So when he's upset, he won't come to you — and if you go to him, he may turn away. That's the learned pattern, not a judgement of you.'",
  "'Keep offering, calmly, without pressure. Consistency over weeks is what changes it, not one big conversation.'",
  "'Transitions and new adults are the hardest points. Warn him about a sub, a trip, a room change. If there's a key adult, protect their time with him.'",
  "'Be careful with the word \"attachment\" in the staffroom. Most children called that don't have an attachment disorder, and the label can stop us looking at language, learning or attention.'",
  "'Sanctions that isolate or shame usually confirm what he already believes about adults. Boundaries still matter; deliver them calmly and come back to him afterwards.'",
 ],
 "explain_child": [
  "USUALLY YOU DO NOT EXPLAIN A DIAGNOSIS to a young child with RAD. You explain the adults: 'Mrs X is your special person in school. She'll be here every morning. If something's hard, you can go to her, or she'll come and find you.'",
  "YOUNGER: 'Some children had lots of different grown-ups when they were small, and they learned to look after themselves. That was clever of you. In this school, the grown-ups' job is to help you, and we're going to keep showing you that.'",
  "OLDER (if the young person knows their history and raises it): 'When you were very young you didn't have one person you could always rely on. Your brain learned to manage on its own. That makes sense. It also means trusting people can take longer, and that's okay.'",
  "ASK: 'Who in school do you like being with?' 'What's the best bit of the day?' 'What would you change?' Build on the adult the child already chooses.",
  "DO NOT ask about their early life or birth family. That history belongs with the social worker and specialist services, and the child decides who hears it.",
 ],
 "analogies": [
  "THE UNANSWERED PHONE: 'If you rang for help a hundred times as a baby and nobody picked up, you'd stop ringing. Now someone always answers — but he's stopped dialling. We keep answering until he tries again.' Works with carers and teachers.",
  "THE SAFE HARBOUR (from attachment theory, Bowlby's secure base idea): 'Children go out to explore and come back to a harbour when the sea gets rough. This child never had a harbour, so he stays out in the storm. Our job is to be the harbour, over and over.' Good with teachers.",
  "LEARNING A NEW LANGUAGE LATE: 'Most children learn \"comfort\" from birth. He's learning it later, like a second language — it's possible, it just takes more practice and patience.' Good with adoptive and foster parents.",
 ],
 "language": [
  "Use 'Reactive Attachment Disorder' only for a clinical diagnosis. Otherwise describe: 'difficulty seeking or accepting comfort from adults', 'relationship-based difficulties following early adversity'.",
  "Avoid 'attachment kid', 'RAD child', 'unattached', 'damaged', 'manipulative', 'controlling' as descriptions of the child.",
  "Many young people in care prefer 'care-experienced' to 'looked after' (a UK term) — EPIC works with young people on this. Ask.",
  "Avoid 'attachment issues' as a catch-all in reports; it closes the formulation before it starts.",
  "Refer to foster, kinship and adoptive parents by their role as the child and family use it — many children call them 'Mum' and 'Dad'.",
 ],
 "red_flags": [
  "RED FLAG — any indication of current neglect or abuse. " + CP_ROUTE,
  "RED FLAG — a placement at risk of breaking down, or a sudden change in the child's presentation after a placement change or access visit. Inform the Tusla social worker; supervision.",
  "RED FLAG — anyone recommending holding therapy, rebirthing or coercive restraint as 'attachment therapy'. Raise it; PSI 4.5.1 applies to harmful practice by others.",
  "BOUNDARY — you do not diagnose RAD and should not write 'attachment disorder' in a report without a clinician's diagnosis. PSI 2.2.2, 1.2.8.",
  "BOUNDARY — consent for a child in care depends on the care order. Confirm with the Tusla social worker and your service before assessing. PSI 1.3.11.",
  "WATCH — 'attachment' becoming the explanation for everything. Language, learning, ADHD, FASD and trauma go unassessed once the word is used.",
  "WATCH — confusing RAD with autism. Both look withdrawn; the care history, restricted and repetitive behaviour, and response to good care distinguish them.",
 ],
 "child_voice": [
  "TALKING MATS — symbol-based sorting of topics onto a visual scale. Good because many of these children have language delay and struggle with direct adult questions. → https://www.talkingmats.com/",
  "THREE HOUSES (Weld and Greening) — house of worries, house of good things, house of dreams. Good because it is widely used in child protection social work and may already be familiar; check whether the social worker has used it so the child is not asked twice.",
  "'WHO HELPS ME' MAP — the child places people in school closer or further from themselves. Good because it shows which adult the child already gravitates to — that is your key adult.",
  "OBSERVATION as voice — for young children, what they do at separation, reunion and when hurt is their account. Record it descriptively.",
  "EPIC (Empowering People in Care) — Irish advocacy organisation for care-experienced children and young people. Good because it gives older pupils an independent voice in their care and education planning. → https://www.epiconline.ie/",
 ],
 "questions": [
  "Q: 'Does he have an attachment disorder?' — A: 'That's a specialist diagnosis and it's actually rare. Many children with a difficult start have attachment-related difficulties without having the disorder. I'd describe what I see and look at language, learning and attention too, rather than put a label on it.'",
  "Q: 'Is it too late for her to attach?' — A: 'No. Children commonly form attachments to new carers once care is steady and sensitive. It may take longer and look different, but it happens.'",
  "Q: 'Couldn't this be autism?' — A: 'It's a fair question; they can look alike. The things that separate them are the early care history, whether there are repetitive behaviours and intense interests, and whether things improve a lot in good care. That's a question for a specialist team, and I'd flag it.'",
  "Q: (teacher) 'Isn't she just manipulative?' — A: 'What looks like manipulation is usually a child trying to stay in control because adults weren't reliable before. It's worth naming the behaviour precisely and planning for it, but \"manipulative\" isn't a helpful explanation.'",
  "Q: 'Someone recommended holding therapy.' — A: 'I'd strongly advise against it. Coercive holding approaches are not supported by evidence and have caused serious harm. NICE guidance advises against them. The supported approaches work through carer sensitivity and consistency.'",
  "Q: 'Should school do attachment training?' — A: 'Training can help, but it's most useful when it's tied to a specific child — a one-page plan the staff actually use. And it shouldn't replace assessing language, learning and attention.'",
  "Q: 'Who can consent to you seeing him?' — A: 'It depends on the type of care arrangement. I'll check with his social worker and my service before I do anything.'",
 ],
 "supervision": [
  "Bring any case where the referral says 'attachment' and ask your supervisor to test your formulation: what else could explain this, and what have I not assessed?",
  "Ask how consent works for children in care under different orders in your service, and who you contact at Tusla.",
  "Discuss the RAD–autism differential on a real case, and what a school EP can and cannot contribute to it.",
  "Ask what local services exist for care-experienced children and for FASD assessment — this varies and changes.",
  "Bring your own reactions: work with care-experienced children can stir strong feelings about birth families, carers or the system. PSI 2.2.1.",
 ],
 "reflection": [
  "ON THE LABEL — Did I use the word 'attachment' in my report? Was it a diagnosis someone else made, or my shorthand?",
  "ON WHAT I DID NOT ASSESS — Language? Attention? Attainment? Prenatal alcohol exposure? If attachment explained everything, what did I stop looking for?",
  "ON THE CARERS — Did I recognise what the foster or adoptive parents are carrying, and did my recommendations add to their load or share it?",
  "ON CONSENT — Did I confirm who could consent before starting, or assume?",
  "ON MY OWN LENS — Do I lean on attachment theory because it fits, or because it is the frame I know best? PSI 2.2.1; CORU 5.44.",
  "WHAT GOOD LOOKS LIKE: 'The referral said \"attachment disorder\". There was no diagnosis. I described his behaviour at separation and with a new teacher, asked for SLT assessment of his language, and set up a key adult with a clear transition plan. His foster mother said it was the first report that didn't make him sound broken.'",
  "WHAT POOR LOOKS LIKE: 'Presents with attachment issues. Nurture approach recommended.' — no diagnosis to support the label, no differential, nothing specific.",
 ],
 "citations": [
  "American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.; DSM-5-TR). American Psychiatric Publishing.",
  "World Health Organization. (2019/2022). International classification of diseases (11th rev.; ICD-11): 6B44 Reactive attachment disorder. https://icd.who.int/ — check code before quoting.",
  "National Institute for Health and Care Excellence. (2015). Children's attachment: Attachment in children and young people who are adopted from care, in care or at high risk of going into care (NICE guideline NG26). https://www.nice.org.uk/guidance/ng26 — check for updates.",
  "Zeanah, C. H., & Gleason, M. M. (2015). Annual research review: Attachment disorders in early childhood — clinical presentation, causes, correlates, and treatment. Journal of Child Psychology and Psychiatry, 56(3), 207–222.",
  "Zeanah, C. H., Chesher, T., Boris, N. W., & the American Academy of Child and Adolescent Psychiatry (AACAP) Committee on Quality Issues. (2016). Practice parameter for the assessment and treatment of children and adolescents with reactive attachment disorder and disinhibited social engagement disorder. Journal of the American Academy of Child & Adolescent Psychiatry, 55(11), 990–1003.",
  "Minnis, H., Macmillan, S., Pritchett, R., Young, D., Wallace, B., Butcher, J., Sim, F., Baynham, K., Davidson, C., & Gillberg, C. (2013). Prevalence of reactive attachment disorder in a deprived population. British Journal of Psychiatry, 202(5), 342–346.",
  "Woolgar, M., & Baldock, E. (2015). Attachment disorders versus more common problems in looked after and adopted children: Comparing community and expert assessments. Child and Adolescent Mental Health, 20(1), 34–40.",
  "Granqvist, P., Sroufe, L. A., Dozier, M., Hesse, E., Steele, M., van IJzendoorn, M., et al. (2017). Disorganized attachment in infancy: A review of the phenomenon and its implications for clinicians and policy-makers. Attachment & Human Development, 19(6), 534–558.",
  "Chaffin, M., Hanson, R., Saunders, B. E., Nichols, T., Barnett, D., Zeanah, C., et al. (2006). Report of the APSAC task force on attachment therapy, reactive attachment disorder, and attachment problems. Child Maltreatment, 11(1), 76–89.",
  "Bomber, L. M. (2007). Inside I'm hurting: Practical strategies for supporting children with attachment difficulties in schools. Worth Publishing.",
 ],

 "pathway": {
  "age": "Defined before age 5 (DSM-5-TR) and usually identified in early childhood, often soon after a child comes into care or is adopted, when the contrast with a new, sensitive carer makes the pattern visible. A first diagnosis at school age or later is uncommon and needs the early history.",
  "who_diagnoses": "Ireland: CAMHS or a specialist infant/child mental health service, usually with input from the Tusla social worker and carers; some adoption or fostering specialist services. Not the school EP, and not from a questionnaire.",
  "who_wrote_report": "CAMHS psychiatrist or clinical psychologist; a specialist attachment or infant mental health clinician; occasionally a private clinical psychologist commissioned in care or adoption proceedings. A social work report describing 'attachment concerns' is not a diagnosis.",
  "refer_to": "CAMHS (via GP, or via Tusla for children in care) for assessment; SLT for language; paediatrics for development and FASD; the allocated Tusla social worker for any care-related planning. Tusla and the DLP immediately if there is a protection concern.",
  "sooner": "'Children usually come to attention when they move into steady care, because that's when the difference shows. You haven't missed anything by coming now — and good care is already the most important treatment.'",
 },
 "differential": [
  "AUTISM — social withdrawal plus restricted and repetitive behaviour, present regardless of care quality, not resolving with good care. DSM-5-TR excludes RAD if autism criteria are met.",
  "INTELLECTUAL DISABILITY / GLOBAL DELAY — social behaviour in line with developmental level; check developmental age before interpreting.",
  "DEPRESSION — withdrawal and low affect without the care history requirement, and not specific to caregivers.",
  "TRAUMA RESPONSE / PTSD — event-linked fear and avoidance rather than an absence of attachment behaviour.",
  "INSECURE ATTACHMENT PATTERN — a common relationship style, not a disorder.",
  "LANGUAGE DISORDER — apparent unresponsiveness that is comprehension difficulty.",
 ],
 "next": [
  "Check for any current protection concern first; act on it the same day.",
  "Confirm consent arrangements with the Tusla social worker for a child in care.",
  "Describe observed relational behaviour; assess language, learning and attention; consider FASD.",
  "Set up a key adult and transition plan at School Support Plus with a review date.",
  "Refer to CAMHS or specialist services where RAD is a genuine question; do not label it yourself.",
 ],
 "presentations": [
  "Attachment-related difficulties (descriptive — not a diagnosis)",
  "Care-experienced children (foster, kinship, residential, aftercare)",
  "Difficulty seeking or accepting comfort from adults",
  "Relationships with adults (NEPS 4.2)",
  "Controlling behaviour toward adults",
  "Difficulty with transitions and changes of adult",
  "Parent-infant mental health / 0–3 attachment work",
 ],

 "bands": {
  "Early Years": {
   "applies": "YES — the band in which it is defined and diagnosed (evident before age 5; developmental age at least 9 months)",
   "prevalence": "Rate for this age band not stated here — check before quoting. (Minnis et al., 2013, 1.4%, is for 6–8-year-olds — see School Age.)",
   "see": "A toddler or preschooler who rarely seeks or accepts comfort from carers when hurt or frightened, with flat affect and unexplained fearfulness or irritability with familiar adults, and a history of severe neglect, institutional care or multiple carers. Observe separation and reunion with the key worker; parent or carer report. Refer — do not screen.",
   "tools": ["SDQ (2–4 version)", "Ages & Stages Questionnaires (ASQ-3)"]},
  "School Age": {
   "applies": "RARELY — may persist from early childhood; a new first diagnosis needs early history and specialist assessment",
   "prevalence": "About 1.4% of 6–8-year-olds in a deprived urban UK area (Minnis et al., 2013); not a general-population figure.",
   "see": "Most school referrals labelled 'attachment' at this age are not RAD. Where RAD is present, the child does not go to adults when hurt or upset, is emotionally flat or wary with staff, and struggles with changes of adult. Assess language, attention and learning alongside.",
   "tools": ["SDQ", "BASC-3", "CELF-5 UK", "SCQ (Social Communication Questionnaire)"]},
  "Adolescent": {
   "applies": "RARELY — validity of the diagnosis in adolescence is uncertain; check current guidance",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Presentation overlaps with depression, conduct difficulty and trauma. The school question is usually relationships with staff, placement stability and transitions. Self-report where the young person chooses; CAMHS pathway.",
   "tools": ["BASC-3 SRP", "RCADS self-report"]},
  "Young Adult": {
   "applies": "RETROSPECTIVE ONLY — a childhood diagnosis in the history; not diagnosed de novo",
   "prevalence": "Not applicable as a new diagnosis.",
   "see": "A young adult with RAD in their childhood records is best described by current functioning. Aftercare (Tusla) and third-level supports are the practical questions; adult mental health services if needed.",
   "tools": []},
  "Special Setting": {
   "applies": "RARELY — must be distinguished carefully from autism and intellectual disability",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Withdrawal from adults in a child with intellectual disability or autism is not RAD without the care history and developmental age of at least 9 months. Staff consistency and a stable key adult are the intervention whatever the label.",
   "tools": ["Vineland-3 / ABAS-3", "Functional behaviour assessment (ABC)"]},
 },
},

# ---------------------------------------------------------------------------------------------------------------
{
 "name": "Disinhibited Social Engagement Disorder (DSED)",
 "code": "DSM-5-TR Disinhibited Social Engagement Disorder (Trauma- and Stressor-Related Disorders) · ICD-11 6B45 — check code before quoting",
 "neps": "4. SOCIAL (4.2 Relationships with adults) — and 3. EMOTIONAL (3.5 Trauma, attachment and loss)",
 "coru": "1.2 · 1.12 · 3.1 · 3.2 · 3.10 · 5.28 · 5.29 · 5.32",
 "psi":  "2.2.2 · 2.2.4 · 1.2.8 · 3.3.2 · 3.3.4 · 1.3.11",
 "law":  "Children First Act 2015 · Child Care Act 1991 · Children First: National Guidance (2017) · EPSEN Act 2004 · GDPR",

 "what_it_is": [
  "A RARE disorder in which a child ACTIVELY APPROACHES AND INTERACTS WITH UNFAMILIAR ADULTS without the normal wariness, following SEVERELY INSUFFICIENT CARE in early childhood (APA, 2022, DSM-5-TR). Previously part of 'RAD, disinhibited type' in DSM-IV; separated in DSM-5 (2013).",
  "DSM-5-TR features (at least two): reduced or absent reticence with unfamiliar adults; overly familiar verbal or physical behaviour; diminished or absent checking back with the caregiver in unfamiliar settings; willingness to go off with an unfamiliar adult with little or no hesitation.",
  "The behaviour is NOT simply impulsivity (as in ADHD) — it is socially disinhibited. Same care-history requirement as RAD: social neglect, repeated changes of caregiver, or rearing in severely limiting settings. Developmental age at least 9 months.",
  "Unlike RAD, DSED can occur in a child who HAS formed an attachment to a caregiver; it is about indiscriminate engagement with strangers, not the absence of attachment (Zeanah & Gleason, 2015).",
  "DSED tends to be MORE PERSISTENT than RAD after placement in good care (Zeanah & Gleason, 2015 — check). In the English and Romanian Adoptees study, disinhibited social engagement persisted into young adulthood in some who had experienced prolonged early institutional deprivation (Sonuga-Barke et al., 2017).",
  "In the ERA study, it was one of several 'deprivation-specific' patterns — alongside inattention/overactivity, cognitive impairment and quasi-autistic features — linked mainly to deprivation lasting beyond about six months (Kumsta et al., 2010).",
  "The main practical risk is SAFETY: a child who will go off with anyone, and an adolescent who over-trusts strangers online or offline.",
 ],
 "what_it_is_not": [
  "NOT a friendly, sociable or confident child. Many children are outgoing; DSED is marked, cross-context disinhibition with strangers PLUS the care history. Do not pathologise extroversion.",
  "NOT ADHD — though the two often co-occur. ADHD impulsivity is general; DSED is specifically social and specifically toward unfamiliar adults. Assess both.",
  "NOT autism. Some autistic children approach strangers without typical social caution, but autism includes the restricted/repetitive domain and is present regardless of care history.",
  "NOT Williams syndrome — a genetic condition in which marked sociability with strangers is characteristic. Where there are also medical, cognitive or facial features, the question is medical; refer via GP/paediatrics.",
  "NOT a sign that the child is 'well attached' because they are affectionate with everyone. Indiscriminate affection is the concern, not reassurance.",
  "NOT the result of ordinary parenting or day care. It requires extremes of insufficient care.",
  "NOT solved by attachment 'therapies' involving coercion — these are rejected (NICE, 2015, NG26; Chaffin et al., 2006).",
 ],
 "prevalence": [
  "OVERALL: RARE in the general population — rate not stated here, check before quoting.",
  "HIGHER in children with histories of institutional care or severe neglect; BEIP and ERA samples show it most clearly (Zeanah & Gleason, 2015; Sonuga-Barke et al., 2017). Rates vary by sample — check before quoting.",
  "IRELAND: no national figure stated here — check. Children adopted internationally from institutional settings and children in care of Tusla are the groups where it most often arises.",
  "EARLY YEARS 0–5: when it is most often first recognised, often soon after adoption or entry to care.",
  "SCHOOL AGE AND ADOLESCENT: persists in a proportion; the concern shifts to boundaries, peer relationships and vulnerability.",
  "SEX RATIO: rate not stated here — check before quoting.",
 ],
 "cooccurring": [
  {"name": "ADHD", "rate": "elevated — commonly co-occurs after early deprivation (Kumsta et al., 2010); rate not stated here, check",
   "presents": "general impulsivity and inattention alongside social disinhibition. Assess ADHD in its own right; the two need different plans."},
  {"name": "LANGUAGE DELAY / DLD", "rate": "elevated — rate not stated here, check",
   "presents": "chatty but poor comprehension; over-familiar talk masking limited understanding. Refer to SLT."},
  {"name": "COGNITIVE DELAY / INTELLECTUAL DISABILITY", "rate": "elevated after deprivation — rate not stated here, check",
   "presents": "social judgement in line with developmental level. Establish developmental level before interpreting."},
  {"name": "FASD (prenatal alcohol exposure)", "rate": "elevated in care-experienced and adopted children — rate not stated here, check",
   "presents": "poor social judgement, impulsivity and learning difficulty. Ask about prenatal history; paediatrics."},
  {"name": "PTSD AND TRAUMA RESPONSES", "rate": "elevated where maltreatment occurred — rate not stated here, check",
   "presents": "hypervigilance and startle alongside indiscriminate approach; the combination can be confusing to staff."},
  {"name": "PEER RELATIONSHIP DIFFICULTY", "rate": "common — rate not stated here, check",
   "presents": "over-familiar, intrusive or boundary-crossing with peers; relationships that start quickly and end quickly."},
 ],
 "recommendations": [
  "SAFETY PLAN FIRST. Collection and handover procedures tightened; visitors signed in and supervised; trips planned with named-adult ratios; staff agree what to do if the child approaches or leaves with an unfamiliar adult.",
  "TEACH SOCIAL BOUNDARIES EXPLICITLY — who is a stranger, a helper, a friend; what touch is okay and with whom; checking back with the key adult. Use the Stay Safe programme (the Irish primary school child abuse prevention programme within SPHE) and rehearse, don't just tell.",
  "A KEY ADULT the child checks back with — build and reward 'checking in' as a habit in new settings (trips, assemblies, visitors).",
  "CONSISTENT STAFF RESPONSE to over-familiarity: warm, brief, redirecting ('We give high-fives in school, not hugs, to people we don't know'), not shaming.",
  "ONLINE SAFETY (from late primary): explicit, repeated teaching about strangers online, sharing images and meeting people. Share the plan with carers.",
  "ASSESS THE REST: ADHD, language, learning and FASD. DSED rarely travels alone.",
  "CONTINUUM LEVEL: School Support Plus — Tusla, CAMHS or other services will usually be involved.",
  "REFER: CAMHS or specialist service for assessment; SLT; paediatrics (development, FASD, and where Williams syndrome or another genetic cause is a question). Inform the Tusla social worker for a child in care. NICE (2015, NG26 — check for updates) for caregiver-focused interventions.",
  "DO NOT label a sociable child as having an attachment disorder. DO NOT write 'DSED' without a clinician's diagnosis — describe the behaviour and the risk.",
 ],
 "explain_parent": [
  "FOR FOSTER, KINSHIP OR ADOPTIVE PARENTS: 'When she was very young, lots of different adults came and went, so she learned that any adult might be the one who helps. That's why she goes to strangers. It made sense then; it isn't safe now.'",
  "'This pattern can hang on longer than other difficulties even in really good care. That's not a sign you're doing anything wrong.'",
  "'The plan is safety first — making sure she can't leave with anyone — and then teaching and practising who's safe, lots of times, the same way at home and school.'",
  "'As she gets older, we'll need to think about online safety especially carefully. Let's plan that together early rather than after something happens.'",
  "SIGNPOST: allocated Tusla social worker; Irish Foster Care Association; adoption support services (check current provider); Webwise (Irish online safety resource for parents).",
 ],
 "explain_teacher": [
  "'This isn't confidence or friendliness — she will approach any adult, and she'd leave with one. The first job is a safety plan for collection, visitors and trips.'",
  "'Respond warmly but briefly to over-familiarity, and redirect: tell her what we do instead. Don't shame it, and don't reward it with lots of attention.'",
  "'Teach checking back: in any new place, she comes to you first. Practise it on the way to the hall, on trips, when visitors come.'",
  "'She may have ADHD or language difficulties as well — so watch whether she's impulsive with everything, or specifically with people.'",
  "'For older pupils, online safety is where this becomes serious. Build it into planning now.'",
 ],
 "explain_child": [
  "USUALLY YOU DO NOT EXPLAIN A DIAGNOSIS to a young child. You teach the rule: 'In school, if a grown-up you don't know talks to you, come and find Ms X first. Every time.'",
  "YOUNGER: 'Some grown-ups are our helpers — like your teacher and your key person. Some grown-ups we don't know yet. We're friendly to them, but we don't go anywhere with them or hug them. We check with our helper first.'",
  "OLDER: 'When you were small, you met lots of different adults, so you learned to trust people quickly. That was a good way to manage then. Now it's safer to get to know people slowly — especially online.'",
  "ASK: 'Who are your helpers in school?' 'What would you do if someone you didn't know asked you to come with them?' The answer tells you what to teach.",
  "DO NOT frighten. The aim is a clear rule and a trusted adult, not fear of all adults.",
 ],
 "analogies": [
  "THE OPEN DOOR: 'Most children's front door has a peephole — they check who's there before letting them in. Hers was left open because she never knew who would come. We're fitting the peephole now.' Works with carers and teachers.",
  "THE WRONG MAP: 'She learned a map where any adult might be the one who helps. The map was right for then. We're teaching her a new map for now.' Good with carers; takes blame off everyone.",
  "THE FRIENDSHIP SPEED LIMIT (older pupils): 'Trust has a speed limit. You go slower with people you've just met and speed up as you get to know them.' Good with adolescents, including for online safety.",
 ],
 "language": [
  "Use 'Disinhibited Social Engagement Disorder' only for a clinical diagnosis. Otherwise describe: 'approaches unfamiliar adults without the usual caution', 'over-familiar with adults she does not know'.",
  "Older literature uses 'indiscriminate friendliness' and 'disinhibited attachment'; recognise these in older reports but prefer current DSM-5-TR terms.",
  "Avoid 'attention-seeking', 'clingy', 'too friendly', 'promiscuous' — the last is never acceptable for a child.",
  "Prefer 'care-experienced' where the young person uses it; ask.",
 ],
 "red_flags": [
  "RED FLAG — any contact with an unknown adult outside school, gifts, secrets, online contact with adults, or sexualised behaviour. " + CP_ROUTE,
  "RED FLAG — an adolescent with persistent social disinhibition and signs of exploitation (older 'friends', money, phones, going missing). Child protection route; An Garda Síochána where there is immediate danger.",
  "RED FLAG — the child leaving school premises or going off with an unfamiliar adult. Immediate safety response; review the safety plan the same day.",
  "BOUNDARY — you do not diagnose DSED. Describe the behaviour and the risk; refer. PSI 2.2.2, 1.2.8.",
  "BOUNDARY — consent for a child in care depends on the care order; confirm with the Tusla social worker. PSI 1.3.11.",
  "WATCH — marked sociability with medical or developmental features: consider Williams syndrome or another genetic cause and refer via GP/paediatrics.",
 ],
 "child_voice": [
  "'WHO HELPS ME' MAP — the child places people closer or further. Good because it shows whether the child distinguishes familiar from unfamiliar adults at all, which is the core of the difficulty.",
  "SOCIAL STORY-STYLE SCENARIOS — 'what would you do if…' picture cards about visitors, strangers and online contact. Good because it assesses and teaches at the same time, without anyone having to disclose.",
  "TALKING MATS — for children with language delay. → https://www.talkingmats.com/",
  "STAY SAFE programme materials (Irish primary, SPHE) — good because the language is already used in the school, so the child hears one consistent message.",
  "EPIC (Empowering People in Care) — independent voice for care-experienced young people in their planning. → https://www.epiconline.ie/",
 ],
 "questions": [
  "Q: 'He's just really friendly — why is that a problem?' — A: 'Friendliness with people you know is lovely. What worries me is that he'd go off with an adult he's never met, without checking. That's a safety question first.'",
  "Q: 'Is it ADHD?' — A: 'It can look like it, and he may have both. The question is whether he's impulsive with everything, or specifically with people. That's worth assessing properly.'",
  "Q: 'She's been with us three years — why hasn't it stopped?' — A: 'This pattern can be more stubborn than other difficulties, even in really good homes. Research following adopted children found it lasting into adulthood for some. It doesn't mean your care isn't working.'",
  "Q: 'Does she have an attachment disorder?' — A: 'That's a specialist diagnosis, and it's rare. I'll describe what I see, put a safety plan in place, and recommend the right assessment rather than label it myself.'",
  "Q: (teacher) 'How do I stop the hugging without hurting her feelings?' — A: 'Warm, brief, and tell her what to do instead — a high-five or a wave. Same response every time from everyone. Consistency teaches it; telling off doesn't.'",
  "Q: 'What about when she's a teenager?' — A: 'That's the right question. Online safety and older \"friends\" are the big risks. We'll build that teaching in now, at home and school, and review it every year.'",
 ],
 "supervision": [
  "Bring the safety plan and ask your supervisor to stress-test it: collection, visitors, trips, online.",
  "Discuss the DSED–ADHD distinction on a real case, and how to write both into one formulation.",
  "Ask how your service links with Tusla when a child in care shows ongoing vulnerability, and who holds responsibility for what.",
  "Raise any case where 'friendly' was being used to dismiss a safety concern — or where a sociable child was being pathologised.",
 ],
 "reflection": [
  "ON SAFETY — Did I lead with the safety plan, or with the formulation? Which came first in my report?",
  "ON THE LABEL — Did I call a sociable child 'disinhibited' without the history? Did I call an at-risk child 'just friendly'?",
  "ON THE DIFFERENTIAL — Did I assess ADHD, language and learning, and consider FASD and genetic causes?",
  "ON CONSENT — Did I confirm who could consent for a child in care?",
  "ON THE FUTURE — Did my recommendations look ahead to adolescence and online risk, or only to this term?",
  "WHAT GOOD LOOKS LIKE: 'I described her approaches to visitors precisely, agreed a collection and visitor plan with the principal the same week, set up \"check-in with Ms X\" as a routine, and referred for ADHD and SLT assessment. I wrote \"approaches unfamiliar adults without caution\" rather than a diagnosis.'",
  "WHAT POOR LOOKS LIKE: 'Very sociable child with attachment needs; nurture approach recommended.' — no safety plan, no differential, a label without a diagnosis.",
 ],
 "citations": [
  "American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.; DSM-5-TR). American Psychiatric Publishing.",
  "World Health Organization. (2019/2022). International classification of diseases (11th rev.; ICD-11): 6B45 Disinhibited social engagement disorder. https://icd.who.int/ — check code before quoting.",
  "National Institute for Health and Care Excellence. (2015). Children's attachment: Attachment in children and young people who are adopted from care, in care or at high risk of going into care (NICE guideline NG26). https://www.nice.org.uk/guidance/ng26 — check for updates.",
  "Zeanah, C. H., & Gleason, M. M. (2015). Annual research review: Attachment disorders in early childhood — clinical presentation, causes, correlates, and treatment. Journal of Child Psychology and Psychiatry, 56(3), 207–222.",
  "Zeanah, C. H., Chesher, T., Boris, N. W., & the American Academy of Child and Adolescent Psychiatry (AACAP) Committee on Quality Issues. (2016). Practice parameter for the assessment and treatment of children and adolescents with reactive attachment disorder and disinhibited social engagement disorder. Journal of the American Academy of Child & Adolescent Psychiatry, 55(11), 990–1003.",
  "Sonuga-Barke, E. J. S., Kennedy, M., Kumsta, R., Knights, N., Golm, D., Rutter, M., Maughan, B., Schlotz, W., & Kreppner, J. (2017). Child-to-adult neurodevelopmental and mental health trajectories after early life deprivation: The young adult follow-up of the longitudinal English and Romanian Adoptees study. The Lancet, 389(10078), 1539–1548.",
  "Kumsta, R., Kreppner, J., Rutter, M., Beckett, C., Castle, J., Stevens, S., & Sonuga-Barke, E. J. (2010). III. Deprivation-specific psychological patterns. Monographs of the Society for Research in Child Development, 75(1), 48–78.",
  "Woolgar, M., & Baldock, E. (2015). Attachment disorders versus more common problems in looked after and adopted children: Comparing community and expert assessments. Child and Adolescent Mental Health, 20(1), 34–40.",
  "Chaffin, M., Hanson, R., Saunders, B. E., Nichols, T., Barnett, D., Zeanah, C., et al. (2006). Report of the APSAC task force on attachment therapy, reactive attachment disorder, and attachment problems. Child Maltreatment, 11(1), 76–89.",
  "Department of Children and Youth Affairs. (2017). Children First: National guidance for the protection and welfare of children. Government Publications.",
 ],

 "pathway": {
  "age": "Usually recognised in early childhood, often soon after adoption or entry to care, when carers and preschool staff notice the child going to any adult. Unlike RAD there is no 'before age 5' requirement in DSM-5-TR, and it can persist into adolescence and beyond.",
  "who_diagnoses": "Ireland: CAMHS or a specialist infant/child mental health service, with Tusla social worker and carer input; some adoption or fostering specialist services. Not the school EP.",
  "who_wrote_report": "CAMHS psychiatrist or clinical psychologist; a specialist attachment or infant mental health clinician; a private clinical psychologist in care or adoption work. Older reports may say 'disinhibited attachment' or 'RAD, disinhibited type' (DSM-IV).",
  "refer_to": "CAMHS (via GP, or via Tusla for children in care); SLT; paediatrics for development, FASD and genetic questions; the Tusla social worker for care planning. Tusla, the DLP and An Garda Síochána (if immediate danger) for any safety concern.",
  "sooner": "'This pattern often only shows once a child is settled and people can see how they are with strangers compared with family. Coming now, while we can build safety habits before adolescence, is good timing.'",
 },
 "differential": [
  "ADHD — impulsivity across all situations, not specifically social; often co-occurs.",
  "TEMPERAMENT — an outgoing, confident child who still checks back and is appropriately wary. No disorder.",
  "AUTISM — social approach without typical caution, plus restricted/repetitive behaviour; not dependent on care history.",
  "WILLIAMS SYNDROME OR OTHER GENETIC CONDITION — marked sociability with medical, cognitive or physical features; paediatrics.",
  "INTELLECTUAL DISABILITY — social judgement consistent with developmental level.",
 ],
 "next": [
  "Put a safety plan in place first (collection, visitors, trips, online), and act the same day on any protection concern.",
  "Confirm consent arrangements with the Tusla social worker for a child in care.",
  "Assess ADHD, language and learning; ask about prenatal alcohol exposure.",
  "Teach and rehearse checking back and social boundaries at School Support Plus with a review date.",
  "Refer to CAMHS or specialist services where DSED is a genuine question; do not label it yourself.",
 ],
 "presentations": [
  "Indiscriminate friendliness / over-familiarity with unfamiliar adults",
  "Not checking back with carers or staff in new settings",
  "Boundary difficulties with adults and peers",
  "Vulnerability to exploitation (online and offline)",
  "Care-experienced children (foster, kinship, residential, aftercare)",
  "Relationships with adults (NEPS 4.2)",
 ],

 "bands": {
  "Early Years": {
   "applies": "YES — most often first recognised here, after adoption or entry to care",
   "prevalence": "Rare; higher in children with institutional or severely neglectful early care — rate not stated here, check.",
   "see": "A toddler or preschooler who goes readily to strangers, climbs onto unfamiliar laps, does not check back with the carer or key worker, and would leave with an unknown adult. Observe in the setting; carer and key-worker report. Safety plan and refer — do not screen.",
   "tools": ["SDQ (2–4 version)", "Ages & Stages Questionnaires (ASQ-3)"]},
  "School Age": {
   "applies": "YES — persists in a proportion of children even in good care",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Over-familiar with visitors, substitute teachers and other parents; hugs or chats to strangers on trips; poor boundaries with peers; often alongside ADHD-type impulsivity. Safety planning, explicit teaching through Stay Safe, and assessment of attention and language.",
   "tools": ["SDQ", "BASC-3", "Conners-4", "CELF-5 UK"]},
  "Adolescent": {
   "applies": "RARELY — as a first diagnosis; where it has persisted, the concern is vulnerability and exploitation",
   "prevalence": "Rate not stated here — persistence into adolescence and adulthood documented in ERA (Sonuga-Barke et al., 2017).",
   "see": "Over-trusting of new people, online contact with strangers, quickly formed and intense relationships, susceptibility to older peers. Child protection vigilance, online safety teaching, CAMHS pathway.",
   "tools": ["BASC-3 SRP", "Conners-4 self-report"]},
  "Young Adult": {
   "applies": "RETROSPECTIVE ONLY — a childhood diagnosis in the history; persistence documented in some adults after prolonged early deprivation",
   "prevalence": "Not applicable as a new diagnosis; see Sonuga-Barke et al. (2017).",
   "see": "Social boundary difficulties may continue. The practical questions are aftercare (Tusla), third-level supports and vulnerability; adult services if needed.",
   "tools": []},
  "Special Setting": {
   "applies": "RARELY — must be distinguished from intellectual disability, autism and genetic syndromes",
   "prevalence": "Rate not stated here — check before quoting.",
   "see": "Approaching strangers in a child with intellectual disability may reflect developmental level rather than DSED. The safety plan applies regardless of label; staff consistency and explicit teaching are the intervention.",
   "tools": ["Vineland-3 / ABAS-3", "Functional behaviour assessment (ABC)"]},
 },
},
]
