# Easy Read versions: CORU standards of proficiency and PSI Code of Ethics clauses.
# Keys are "<kind>::<name>" from src/entries.json.

_CORU = "CORU: the body in Ireland that registers and regulates health and social care workers."
_PSI = "PSI: the Psychological Society of Ireland. This rule is from its Code of Ethics."
_OUT = "This rule is outside the scope of your placement."


def _build(name, says, practice, words):
    out = ["WHAT THIS RULE SAYS"] + ["• " + b for b in says]
    out += ["WHAT IT MEANS IN PRACTICE"] + ["• " + b for b in practice]
    out += ["WORDS TO KNOW"] + ["• " + b for b in words]
    out.append("• " + (_CORU if name.startswith("CORU") else _PSI))
    return "\n".join(out)


_R = [
    # ------------------------------------------------------------ CORU 1
    ("CORU 1.1",
     ["You work safely and well.",
      "You stay inside the law, the ethics and the limits of your job."],
     ["You know what your job lets you do.",
      "You do not step outside those limits."],
     ["Ethics: rules about what is right and fair in your work."]),
    ("CORU 1.2",
     ["You know the limits of what you can do.",
      "You know when to ask for advice or more expert help.",
      "You know when to pass the person on to another expert."],
     ["If something is beyond your skills, you get help or refer."],
     ["Refer: ask another worker or service to help the person."]),
    ("CORU 1.3",
     ["You always act in the best interest of the people you serve.",
      "You pay proper attention to what they want and choose."],
     ["You think about what is good for the person.",
      "You also listen to their own wishes."],
     ["Will and preference: what the person wants and would choose."]),
    ("CORU 1.4",
     ["You know the current rules and laws about candour.",
      "You also know them about disclosure."],
     ["You know what these rules ask of you.",
      "You keep up with them as they change."],
     ["Candour: being open and honest.",
      "Disclosure: telling people something they have a right to know."]),
    ("CORU 1.5",
     ["You respect the rights of every person you serve.",
      "You uphold their dignity and their right to choose.",
      "This includes their part in diagnosis, therapy and care."],
     ["The person has a say in what happens to them."],
     ["Dignity: being treated as a person who matters.",
      "Autonomy: a person's right to make their own choices."]),
    ("CORU 1.6",
     ["You have a duty of care to the people you serve.",
      "You are able to carry out this duty."],
     ["You take care that your work does not harm people."],
     ["Duty of care: your duty to look after the safety and wellbeing of the people you work with."]),
    ("CORU 1.7",
     ["You know what the Registration Board expects of you.",
      "You know the current Code of Conduct and Ethics for your job."],
     ["You read the Code and know what it says.",
      "You know the rules the Board sets for you."],
     ["Registration Board: the group that keeps the list of people allowed to work in the profession.",
      "Code: a written set of rules."]),
    ("CORU 1.8",
     ["You see why it matters to treat everyone fairly.",
      "You work in a way that is aware of culture.",
      "You respect that people have different beliefs and ways of life."],
     ["You do not treat anyone unfairly because of who they are."],
     ["Discrimination: treating someone unfairly because of who they are.",
      "Culturally sensitive: aware of and respectful of different cultures."]),
    ("CORU 1.9",
     ["You understand what policies and systems are for.",
      "They protect health, safety, welfare, equality and dignity.",
      "They protect the people you serve, staff and volunteers."],
     ["You know why these policies matter where you work."],
     ["Policy: a written plan for how things should be done.",
      "Welfare: a person's health, safety and happiness."]),
    ("CORU 1.10",
     ["You respect the privacy of the people you serve.",
      "You only use what they tell you for the reason they told you."],
     ["You do not use people's details for any other reason."],
     ["Confidentiality: keeping private information private."]),
    ("CORU 1.11",
     ["You understand confidentiality when you work in a team."],
     ["You know how privacy rules work when many people help one person.",
      "You think about this when you share in the team."],
     ["Confidentiality: keeping private information private."]),
    ("CORU 1.12",
     ["Confidentiality has limits.",
      "You understand these limits and can use them.",
      "This matters most for child protection, vulnerable adults and elder abuse."],
     ["Sometimes you cannot keep something private, because someone may be at risk."],
     ["Child protection: keeping children safe from abuse and neglect.",
      "Vulnerable adult: an adult who may find it hard to protect themselves."]),
    ("CORU 1.13",
     ["You know the current laws on data protection and freedom of information.",
      "You know other laws that matter for your job.",
      "You can find new laws as they come in."],
     ["You keep track of laws about personal information."],
     ["Data protection: laws that keep personal information safe.",
      "Freedom of information: laws that let people ask for records held by public bodies."]),
    ("CORU 1.14",
     ["Keeping things private and whistle-blowing can pull in different ways.",
      "You can spot this conflict.",
      "You can manage it."],
     ["You think carefully when privacy and speaking up clash."],
     ["Whistle-blowing: speaking up about wrongdoing at work.",
      "Confidentiality: keeping private information private."]),
    ("CORU 1.15",
     ["You get informed consent before assessment or treatment.",
      "You write down that you have got consent."],
     ["The person agrees once they know what will happen.",
      "You keep a record of this."],
     ["Informed consent: agreeing after being told what is involved.",
      "Assessment: finding out about a person's strengths and needs."]),
    ("CORU 1.16",
     ["Some people are not able to make a decision for themselves.",
      "You know the current laws and guidance on consent for them."],
     ["You know what the law says when a person lacks capacity."],
     ["Capacity: being able to understand and make a decision.",
      "Informed consent: agreeing after being told what is involved."]),
    ("CORU 1.17",
     ["You are responsible for your own actions.",
      "You can explain why you made each work decision."],
     ["You own your choices at work.",
      "You can give good reasons for them."],
     ["Accountability: being answerable for what you do.",
      "Justify: give good reasons for."]),
    ("CORU 1.18",
     ["You take charge of your own workload, as fits your role."],
     ["You manage the work you have.",
      "It is your job to manage it."],
     ["Workload: the amount of work you have to do."]),
    ("CORU 1.19",
     ["You understand how good work decisions are made.",
      "You can make informed choices when demands compete.",
      "This includes ethics clashes and limited resources."],
     ["You weigh up the options and decide with good information."],
     ["Ethical conflict: when two right things pull against each other.",
      "Resources: things like time, money and staff."]),
    ("CORU 1.20",
     ["You are aware of your own health and wellbeing.",
      "You take responsibility for looking after it."],
     ["You notice how you are.",
      "You take charge of staying well."],
     ["Wellbeing: feeling well in your body and mind."]),
    # ------------------------------------------------------------ CORU 2
    ("CORU 2.1",
     ["You explain findings and options so the person can understand.",
      "This includes diagnosis, assessment and treatment options."],
     ["You fit your words to the person."],
     ["Diagnosis: naming a condition or difficulty.",
      "Assessment: finding out about a person's strengths and needs."]),
    ("CORU 2.2",
     ["You change how you communicate to suit each person.",
      "This includes your words and your body language.",
      "You think about language, age, culture, beliefs and needs."],
     ["You might use simpler words with a young child."],
     ["Non-verbal: communicating without words, such as with your face or hands."]),
    ("CORU 2.3",
     ["The people you serve take an active part in their own care.",
      "You help them share their needs, choices and worries."],
     ["You treat the person as a partner.",
      "You help them speak up."],
     ["Active participant: someone who takes part and has a say."]),
    ("CORU 2.4",
     ["You help people manage their own wellbeing where they can.",
      "You see when it is right to give advice on self-care."],
     ["You help people feel able to look after themselves."],
     ["Empower: help someone feel able to take control.",
      "Self-treatment: things people can do to help themselves."]),
    ("CORU 2.5",
     ["You can tell when a trained translator is needed."],
     ["Sometimes you and the person do not share a language well.",
      "Then a trained translator may be needed."],
     ["Translator: a trained person who changes words from one language to another."]),
    ("CORU 2.6",
     ["You can use English at a high level.",
      "This is level C1 on a European scale of language skill."],
     ["You can speak, read and write English well for your job."],
     ["Common European Framework of Reference for Languages: a scale of language skill. C1 is an advanced level."]),
    ("CORU 2.7",
     ["You understand how to use media in the right way.",
      "This includes digital and social media.",
      "You use it in a way that is ethical, private and professional."],
     ["You think carefully before you post or share online."],
     ["Social media: websites and apps where people share posts.",
      "Ethical: right and fair."]),
    ("CORU 2.8",
     ["You write records that are clear, short, correct and fair."],
     ["Your notes are easy to follow.",
      "They stick to facts, not feelings."],
     ["Documentation: written records.",
      "Objective: based on facts, not personal feelings."]),
    ("CORU 2.9",
     ["You have good digital skills.",
      "You use the technology that fits your job."],
     ["You can use computers and other tools to communicate at work."],
     ["Digital literacy: skill in using computers and online tools."]),
    ("CORU 2.10",
     ["You know the rules for how records must be written.",
      "These can be local or national rules.",
      "You follow them."],
     ["This includes using the right words.",
      "It includes signing records in the right way."],
     ["Terminology: the special words used in a job."]),
    ("CORU 2.11",
     ["You can give a clear, well thought-out opinion.",
      "You share it with the people you serve, health workers and others.",
      "You stay within the limits of confidentiality."],
     ["You do this in many different places and settings."],
     ["Opinion: your view, based on your knowledge.",
      "Confidentiality: keeping private information private."]),
    ("CORU 2.12",
     ["You understand how good leadership and management affect work.",
      "You can see this effect."],
     ["You notice how the way a service is run changes the work."],
     ["Leadership: guiding and supporting others.",
      "Management: organising people and work."]),
    ("CORU 2.13",
     ["You understand how to handle conflict well.",
      "You can talk about the main ideas behind it."],
     ["You know ways to deal with disagreements."],
     ["Conflict management: ways of handling disagreements."]),
    ("CORU 2.14",
     ["You work in partnership with the people you serve, their families and other workers.",
      "Together you plan goals and support, and check how they work.",
      "You are aware of power in your relationships with the people you serve."],
     ["You keep in mind the power your role can give you."],
     ["Partnership: working together as equals.",
      "Carer: someone who looks after another person."]),
    ("CORU 2.15",
     ["You build and keep good work relationships.",
      "You do this when you work on your own.",
      "You also do it as part of a team."],
     ["You work well with others, alone or in a team."],
     ["Independent practitioner: someone who works on their own.",
      "Colleague: someone you work with."]),
    ("CORU 2.16",
     ["You understand how teams of different workers meet people's needs.",
      "You know why good teamwork matters.",
      "You can help the team make decisions."],
     ["You share your view when the team decides."],
     ["Interdisciplinary team: a team of workers from different professions."]),
    ("CORU 2.17",
     ["You understand how work relationships affect services.",
      "You build relationships based on respect and trust on both sides."],
     ["You treat colleagues and other workers with respect."],
     ["Colleague: someone you work with.",
      "Mutual: shared by both sides."]),
    # ------------------------------------------------------------ CORU 3
    ("CORU 3.1",
     ["You gather all the background information you need.",
      "It relates to the person's health and social care needs."],
     ["You find out about the person's history and situation."],
     ["Background information: facts about the person's life so far."]),
    ("CORU 3.2",
     ["You choose the right assessment methods and can say why.",
      "You carry out a full, careful and detailed assessment.",
      "You do it with care, and you record it."],
     ["You write down what you did and what you found."],
     ["Assessment: finding out about a person's strengths and needs.",
      "Justify: give good reasons for."]),
    ("CORU 3.3",
     ["You decide which tests or assessments are needed.",
      "You carry them out or arrange them."],
     ["Sometimes you do the test. Sometimes you arrange for someone else to."],
     ["Assessment: finding out about a person's strengths and needs.",
      "Test: a set task that measures a skill."]),
    ("CORU 3.4",
     ["You can study the information you collect in an assessment.",
      "You can judge it carefully."],
     ["You think about what the results mean.",
      "You think about how much you can trust them."],
     ["Critically evaluate: think carefully about how good and useful something is."]),
    ("CORU 3.5",
     ["You think clearly and solve problems.",
      "You use this to make problem lists, action plans and goals."],
     ["You work out the main needs.",
      "You make a plan with clear goals."],
     ["Action plan: a list of steps to reach a goal."]),
    ("CORU 3.6",
     ["You use evidence to help you make decisions.",
      "You fit your work to the needs of the person.",
      "You use your knowledge and skills to make good judgements."],
     ["You use what research shows, and adapt it to the person."],
     ["Evidence-informed: using research and facts to guide your work."]),
    ("CORU 3.7",
     ["You put safety first.",
      "You keep the people you serve safe.",
      "You also keep safe the people involved in their care."],
     ["You think about safety in what you do."],
     ["Prioritise: put first."]),
    ("CORU 3.8",
     ["You check how well support plans work.",
      "You use proper tools and outcome measures.",
      "You also use what the person says.",
      "You change the plan if needed, with the person where it fits."],
     ["Plans are checked and changed, not left as they are."],
     ["Intervention plan: a plan for help or support.",
      "Outcome measure: a way to measure change."]),
    ("CORU 3.9",
     ["You understand why the quality of work must be checked.",
      "You compare your own work with standards based on evidence.",
      "You make changes based on what you find."],
     ["You look back at your work honestly and improve it."],
     ["Audit: a careful check of how work is done.",
      "Evidence-based: backed by research."]),
    ("CORU 3.10",
     ["You can spot important risk factors and manage risk.",
      "You can decide to start, continue, change or stop a piece of work.",
      "You can guide others on this.",
      "You record your decisions and worries."],
     ["You write down why you decided."],
     ["Risk factor: something that makes harm more likely.",
      "Intervention: help or support that aims to make things better."]),
    ("CORU 3.11",
     ["You understand the main ideas of quality assurance.",
      "You understand the main ideas of quality improvement."],
     ["You know how services check and improve their work."],
     ["Quality assurance: checking that work meets a standard.",
      "Quality improvement: finding ways to make work better."]),
    ("CORU 3.12",
     ["You can do a risk analysis and write it down.",
      "You can put good controls in place to manage risk.",
      "You clearly report risks, adverse events and near misses.",
      "You follow current laws and guidance."],
     ["You tell the right people about risks."],
     ["Adverse event: something that caused harm.",
      "Near miss: something that nearly caused harm."]),
    ("CORU 3.13",
     ["You follow current health and safety laws.",
      "You follow current health and safety guidance."],
     ["You know the health and safety rules for your work."],
     ["Legislation: laws.",
      "Guidelines: advice on how to do things."]),
    ("CORU 3.14",
     ["You set up safe places to work.",
      "They lower risks to the people you serve, to staff and to others.",
      "This includes steps to stop infection."],
     ["You use steps that stop germs spreading."],
     ["Infection prevention and control: steps that stop germs spreading."]),
    # ------------------------------------------------------------ CORU 4
    ("CORU 4.1",
     ["You take part in your own professional development.",
      "You take responsibility for it."],
     ["You keep learning in your job."],
     ["Professional development: learning and growing in your job."]),
    ("CORU 4.2",
     ["You show proof of learning that goes on through your career.",
      "You know what the rules for your profession ask.",
      "You understand how this learning helps your work."],
     ["You keep a record of your learning."],
     ["CPD: continuing professional development. Learning you keep doing all through your career.",
      "Regulation: rules set by an official body."]),
    ("CORU 4.3",
     ["You think carefully about your own work.",
      "You find out what you need to learn.",
      "You choose learning that fits your goals.",
      "You use what you learn in your work."],
     ["You look back, learn, and do better."],
     ["Reflect critically: think carefully and honestly about your work."]),
    ("CORU 4.4",
     ["Your values and life experience affect your work.",
      "You understand and notice this.",
      "You manage it in a suitable way."],
     ["You notice when your own views may shape how you see things."],
     ["Values: beliefs about what is important."]),
    ("CORU 4.5",
     ["You see why learning, supervision, feedback and peer review matter.",
      "You look for them.",
      "They help you keep getting better at your work."],
     ["You ask for feedback on your work."],
     ["Supervision: regular meetings with a more experienced worker about your work.",
      "Peer review: colleagues looking at your work."]),
    ("CORU 4.6",
     ["You understand why performance management matters.",
      "Taking part in it helps services work well."],
     ["You see why it is worth taking part."],
     ["Performance management: checking how well someone does their job, and planning how to improve."]),
    # ------------------------------------------------------------ CORU 5
    ("CORU 5.1",
     ["You know the key ideas in the areas of knowledge for your profession.",
      "You understand them and use them."],
     ["You use this knowledge in your daily work."],
     ["Domains of knowledge: areas of learning."]),
    ("CORU 5.2",
     ["You know several sciences well enough to question them.",
      "These include biology, human development, and social and behavioural science.",
      "You also know about health and wellbeing."],
     ["You use this knowledge to understand people."],
     ["Behavioural science: the study of how people act.",
      "Critical understanding: knowing a subject well enough to question it."]),
    ("CORU 5.3",
     ["You know how science and research work.",
      "You can judge them carefully.",
      "This includes checking how well a treatment works.",
      "It includes evidence-informed practice."],
     ["You can tell strong research from weak research."],
     ["Efficacy: how well something works.",
      "Evidence-informed practice: using research to guide your work."]),
    ("CORU 5.4",
     ["You have skills in evidence-informed practice.",
      "You can turn theories, ideas and methods into real work."],
     ["You put what you learn into practice."],
     ["Theory: an idea that explains something.",
      "Evidence-informed practice: using research to guide your work."]),
    ("CORU 5.5",
     ["Government, groups, communities and society shape health and social care.",
      "Their structures, systems and culture all have an effect.",
      "You can spot and understand this effect."],
     ["You see the bigger picture around each person."],
     ["Structures and systems: the way groups are set up and run."]),
    ("CORU 5.6",
     ["You use practical, technical and professional skills.",
      "You use them safely and well."],
     ["You carry out the tasks of your job with care and skill."],
     ["Clinical: to do with direct work with clients."]),
    ("CORU 5.7",
     ["You can carry out research or lead it.",
      "It can be clinical, academic or based on practice."],
     ["You can plan and do a research project."],
     ["Research: careful study to find out new things.",
      "Academic: to do with university study."]),
    ("CORU 5.8",
     ["You know the basic ideas of good teaching and learning.",
      "You also know the basic ideas of mentoring and supervision."],
     ["You can help others learn."],
     ["Mentoring: guiding a less experienced person.",
      "Supervision: regular meetings to guide and check someone's work."]),
    ("CORU 5.9",
     ["You know the theories, models and research methods of educational psychology."],
     ["You know the main ideas that guide your field.",
      "You know how research in it is done."],
     ["Educational psychology: the study of how people learn and develop, and how to help them.",
      "Model: a way of explaining how something works."]),
    ("CORU 5.10",
     ["You know how educational psychology began.",
      "You know how it has grown and changed."],
     ["You know where your profession came from."],
     ["Educational psychology: the study of how people learn and develop, and how to help them."]),
    ("CORU 5.11",
     ["The person you serve takes an active part in planning.",
      "This covers their assessment, therapy, treatment and other help.",
      "You know this role."],
     ["You plan with the person, not just for them."],
     ["Active participant: someone who takes part and has a say.",
      "Intervention: help or support that aims to make things better."]),
    ("CORU 5.12",
     ["You know psychology theories of education and human development.",
      "You know theories of learning and teaching.",
      "You know how they apply to children, young people and adult learners."],
     ["You use these ideas to understand how people learn."],
     ["Theory: an idea that explains something."]),
    ("CORU 5.13",
     ["You know how schools, communities and social settings are set up.",
      "These are places where education, health and social care are given.",
      "This is for children, young people and adult learners."],
     ["You understand the places where people get help."],
     ["Structures and systems: the way groups are set up and run."]),
    ("CORU 5.14",
     ["The way education services are set up affects how people develop.",
      "You know this effect.",
      "It can be seen in one person, in groups and in whole organisations."],
     ["You look beyond the child to the systems around them."],
     ["Organisation: a group such as a school or service."]),
    ("CORU 5.15",
     ["You know psychology models of development.",
      "They cover thinking, behaviour, feelings, social skills and learning.",
      "They relate to children, young people and adults in services."],
     ["You use these models to understand how people grow."],
     ["Cognitive: to do with thinking.",
      "Model: a way of explaining how something works."]),
    ("CORU 5.16",
     ["You know psychology models about the world around a person.",
      "This means family, culture, community, groups and systems.",
      "These things affect how a person thinks, acts, feels, mixes and learns."],
     ["You think about the world around a person."],
     ["Model: a way of explaining how something works."]),
    ("CORU 5.17",
     ["Some things hold people back from what they could achieve.",
      "You know psychology models of these things.",
      "You use them to find needs and tackle barriers."],
     ["You look for what gets in the way of learning."],
     ["Barrier: something that gets in the way.",
      "Potential: what a person could achieve."]),
    ("CORU 5.18",
     ["You know therapy models that matter for educational psychology.",
      "You can judge how well they work in practice."],
     ["You think carefully before using a therapy model."],
     ["Psychotherapeutic: to do with talking therapies for thoughts and feelings."]),
    ("CORU 5.19",
     ["Medicines and other treatments can affect your work with people.",
      "You are aware of this effect."],
     ["You keep in mind any treatment a person is having."],
     ["Psychopharmacological: to do with medicines that affect the mind."]),
    ("CORU 5.20",
     ["You know what educational psychologists do.",
      "You can explain it.",
      "They use evidence to help people of all ages learn and grow.",
      "They work in education, health and social care."],
     ["Their work includes assessment, diagnosis, formulation and support.",
      "It also includes advocacy, advice, training and research.",
      "It includes work to stop problems starting."],
     ["Formulation: an account of why a difficulty happens.",
      "Advocacy: speaking up for someone."]),
    ("CORU 5.21",
     ["You start, keep up and end a work relationship safely.",
      "You do this in an ethical way.",
      "You notice and manage professional boundaries."],
     ["You keep the relationship safe and proper."],
     ["Boundaries: limits that keep a work relationship safe and proper."]),
    ("CORU 5.22",
     ["You can think carefully about what affects your work relationships.",
      "This includes power between you and the person."],
     ["You notice who holds more power, and how this affects the work."],
     ["Power dynamics: how power is shared, or not, between people."]),
    ("CORU 5.23",
     ["Working in partnership with the people you serve has benefits.",
      "It also has challenges.",
      "You know both, for assessment and support."],
     ["You plan for both the good points and the hard parts."],
     ["Partnership: working together as equals."]),
    ("CORU 5.24",
     ["People differ in many ways at once.",
      "You know about this and use what you know.",
      "You work in a way that includes everyone and is fair."],
     ["You are sensitive to each person's mix of needs."],
     ["Intersecting diversity: when many parts of who a person is overlap.",
      "Equitable: fair, giving people what they need."]),
    ("CORU 5.25",
     ["You choose ways of communicating that include everyone.",
      "You check how well they work and change them.",
      "You fit them to the setting and the audience."],
     ["You might use pictures or plain words, if they suit."],
     ["Inclusive communication: communicating in ways everyone can take part in."]),
    ("CORU 5.26",
     ["You know the technology used for online work.",
      "You can use it safely and ethically."],
     ["You take care when you work by video call or online."],
     ["Virtual: online, such as by video call."]),
    ("CORU 5.27",
     ["You write reports that are clear, short, easy to read and correct.",
      "Where it fits, you write them with the people you serve.",
      "They suit the reader and how they will be used.",
      "They explain and give reasons for your views."],
     ["You write for the reader."],
     ["Accessible: easy for everyone to use and understand."]),
    ("CORU 5.28",
     ["You can judge the theory and use of many assessment methods.",
      "They find psychological, educational and developmental needs.",
      "They can be used with one person or with groups."],
     ["You know what each method is good for, and its limits."],
     ["Assessment: finding out about a person's strengths and needs."]),
    ("CORU 5.29",
     ["You know educational psychology theory.",
      "You know frameworks about systems, the wider world and problem-solving.",
      "You use them with assessment methods."],
     ["You look at the person and the world around them."],
     ["Framework: a set of ideas that guides your work.",
      "Ecological: looking at the person within their whole world."]),
    ("CORU 5.30",
     ["You plan assessments and choose suitable methods.",
      "You think carefully about the person's needs and views.",
      "You think about social and cultural issues when you plan."],
     ["The person's view shapes the plan."],
     ["Assessment: finding out about a person's strengths and needs."]),
    ("CORU 5.31",
     ["You use a range of assessment methods.",
      "You use them safely and ethically.",
      "You change and review them when needed."],
     ["You adapt a method if it is not working for the person."],
     ["Ethically: in a right and fair way."]),
    ("CORU 5.32",
     ["You make sense of assessment results.",
      "You bring them together and judge them, using the right theories.",
      "This helps with formulation and with planning support."],
     ["Results lead to a clear picture and a plan."],
     ["Formulation: a shared account of why a difficulty is happening.",
      "Synthesise: bring together into one picture."]),
    ("CORU 5.33",
     ["You can judge the theory and use of ways of helping based on evidence.",
      "This is for one person and for groups.",
      "It is in education, health and social care settings."],
     ["You know which kinds of help have good evidence."],
     ["Intervention: help or support that aims to make things better.",
      "Evidence-based: backed by research."]),
    ("CORU 5.34",
     ["You design support based on the facts you have.",
      "You also use your judgement, the evidence and your formulation.",
      "You include the person's own view."],
     ["The plan fits the facts and the person."],
     ["Formulation: a shared account of why a difficulty is happening.",
      "Intervention: help or support that aims to make things better."]),
    ("CORU 5.35",
     ["You look at how a school is run and its culture.",
      "You judge what this means.",
      "You use this to help the school develop, so all learners take part and feel well."],
     ["You look at the whole school, not just one child."],
     ["School culture: the shared ways and values in a school."]),
    ("CORU 5.36",
     ["You use support that is safe and ethical.",
      "It fits the goals and purpose in the plan."],
     ["You follow the plan you agreed."],
     ["Intervention: help or support that aims to make things better."]),
    ("CORU 5.37",
     ["You check how well educational support is working.",
      "You change it if needed."],
     ["You keep checking, and change what is not working."],
     ["Intervention: help or support that aims to make things better."]),
    ("CORU 5.38",
     ["You know a range of ways to consult.",
      "You use them with one person, with groups and with whole organisations."],
     ["You work through problems together with others."],
     ["Consultation: thinking through a problem together with others, such as teachers or parents."]),
    ("CORU 5.39",
     ["You work as part of a team of different professions.",
      "You take an active part in joined-up support.",
      "This is for one person and for groups."],
     ["You play your part in the team's plan."],
     ["Multi-disciplinary team: a team of workers from different professions.",
      "Integrated: joined up."]),
    ("CORU 5.40",
     ["You work together with other professionals.",
      "This includes teachers, other school staff and teams of different workers.",
      "You help them build their skills to give support."],
     ["You share what you know, so others can help too."],
     ["Capacity: the skills and ability to do something."]),
    ("CORU 5.41",
     ["You can study and judge current research.",
      "This includes psychology research and other research that matters.",
      "You use it to guide practice based on evidence."],
     ["You read research with a careful eye."],
     ["Critically appraise: judge carefully how good something is."]),
    ("CORU 5.42",
     ["You can form good research questions and plans.",
      "You can carry out research.",
      "You can produce results that matter for educational psychology."],
     ["You can take a research project from idea to report."],
     ["Outputs: things produced from research, such as reports."]),
    ("CORU 5.43",
     ["You follow research ethics.",
      "You do this when you plan, carry out and report research.",
      "This covers research with the people you serve and others."],
     ["You keep people who take part safe and treated fairly."],
     ["Research ethics: rules that keep research fair and safe for people who take part."]),
    ("CORU 5.44",
     ["You think carefully about yourself.",
      "Your culture, values, experiences, beliefs and biases affect your work.",
      "You use supervision to help you reflect.",
      "You use what you learn to guide your work."],
     ["You notice how you affect the work."],
     ["Bias: a leaning for or against something, often without knowing.",
      "Reflect: think back carefully."]),
    ("CORU 5.45",
     ["You notice your own feelings about your work.",
      "You notice the effect of trauma you meet in your work and supervision.",
      "You use good tools to look after yourself.",
      "This helps you keep working well."],
     ["You take your own feelings seriously."],
     ["Trauma: harm from a very frightening or painful event.",
      "Self-care: looking after yourself."]),
    # ------------------------------------------------------------ PSI 1
    ("PSI 1.1.1",
     ["You pay sensible attention to each client's moral and cultural values."],
     ["You respect what matters to the person and their culture."],
     ["Client: a person you give a service to.",
      "Moral values: beliefs about right and wrong."]),
    ("PSI 1.1.2",
     ["Your service must not get worse because of who a client is.",
      "This includes gender, sexuality, disability, religion, race and age.",
      "It includes ethnicity, where they are from, politics, standing or class."],
     ["Every client gets the same good service."],
     ["Sexuality: who a person is attracted to.",
      "Ethnicity: a group a person belongs to by culture or background."]),
    ("PSI 1.1.3",
     ["You respect the customs of the community.",
      "You respect its cultural expectations.",
      "You follow them in your science and professional work."],
     ["You fit in with the ways of the community you work in."],
     ["Mores: the accepted customs of a community."]),
    ("PSI 1.1.4",
     ["You use respectful language in all you write or say.",
      "Your words respect the dignity of others.",
      "One example is using gender-neutral words."],
     ["You choose words that do not put people down."],
     ["Gender-neutral: words that do not assume someone is male or female.",
      "Dignity: being treated as a person who matters."]),
    ("PSI 1.1.5",
     ["You avoid or refuse practices that disrespect people's rights.",
      "This includes legal, civil and moral rights."],
     ["You say no to taking part in anything like this."],
     ["Civil rights: rights every person has in society."]),
    ("PSI 1.2.1",
     ["You only look for and collect information that is needed.",
      "It must relate to the purpose of the assessment or support.",
      "Or it must be required by law."],
     ["You do not gather personal details you do not need."],
     ["Germane: relevant, connected to the purpose."]),
    ("PSI 1.2.2",
     ["You take care not to intrude on people's private space.",
      "This applies in research and in services.",
      "Private space can be personal or set by culture.",
      "You only enter it with clear and proper permission."],
     ["You ask first."],
     ["Infringe: to intrude on or break."]),
    ("PSI 1.2.3",
     ["You respect the right of others you work with to reasonable privacy.",
      "This includes employees, supervisors, students and trainees."],
     ["You respect their personal lives."],
     ["Psychologist in training: someone learning to become a psychologist."]),
    ("PSI 1.2.4",
     ["Through your work, you learn private things about others.",
      "You take care not to pass these on.",
      "The only exception is when the law requires or justifies it."],
     ["You keep what you learn at work private."],
     ["Confidential: private, not to be shared."]),
    ("PSI 1.2.5",
     ["You only share private information in some cases.",
      "The person gave informed consent, or they cannot be identified.",
      "Or the law requires or justifies it.",
      "Or there is actual or possible risk of serious physical harm or death."],
     ["Otherwise you keep it private."],
     ["Informed consent: agreeing after being told what is involved."]),
    ("PSI 1.2.6",
     ["You store, handle, move and get rid of all records with care.",
      "You keep them private and secure.",
      "This includes written and unwritten records.",
      "You plan for your records in case you become seriously ill or die."],
     ["Someone else can deal with them safely if needed."],
     ["Records: notes and files about people."]),
    ("PSI 1.2.7",
     ["Records should show who a person is only as long as needed.",
      "You take reasonable steps to make sure of this.",
      "After that, you make records anonymous or destroy them."],
     ["You do not keep names on records for longer than needed."],
     ["Anonymous: with names and identifying details removed."]),
    ("PSI 1.2.8",
     ["You are very careful about what you write and share.",
      "This stops it being misread or used to harm others.",
      "You do not record things that could be misread.",
      "You do not guess. You label your opinions clearly."],
     ["You use language the reader understands."],
     ["Conjecture: guessing.",
      "Discretion: care about what you say or share."]),
    ("PSI 1.2.9",
     ["You tell people about the legal limits on confidentiality.",
      "You do this for those you offer services to, where it fits."],
     ["People know from the start what you may have to share."],
     ["Confidentiality: keeping private information private."]),
    ("PSI 1.2.10",
     ["You explain how confidentiality will be protected.",
      "You explain what family, group or community members must do.",
      "They have a part in protecting each other's privacy."],
     ["Everyone knows their part in keeping things private."],
     ["Confidentiality: keeping private information private."]),
    ("PSI 1.3.1",
     ["Informed consent is more than signing a form.",
      "It comes from a process of agreeing to work together.",
      "Some assessments or support may be required by law."],
     ["Consent is an agreement you build, not just a form."],
     ["Informed consent: agreeing after being told what is involved.",
      "Compulsory: required."]),
    ("PSI 1.3.2",
     ["You respect people's views and wishes on decisions that affect them.",
      "You include them as much as possible."],
     ["Their views shape the decisions."],
     ["Integrate: bring in and include."]),
    ("PSI 1.3.3",
     ["You get informed consent for any psychology service you give.",
      "This applies to all independent and partly dependent people."],
     ["You ask before you start."],
     ["Informed consent: agreeing after being told what is involved.",
      "Partially dependent: relying on others for some things."]),
    ("PSI 1.3.4",
     ["You give as much information as a sensible person would want.",
      "This is before they decide.",
      "You use language they understand.",
      "You take reasonable steps to check they really understand."],
     ["You explain clearly, then check."],
     ["Informed consent: agreeing after being told what is involved.",
      "Prudent: careful and sensible."]),
    ("PSI 1.3.5",
     ["People must at least understand: the purpose, what each side does, benefits and risks.",
      "Also: other options, and what happens if nothing is done.",
      "Also: they can say no or stop at any time without penalty.",
      "Also: how long consent lasts, and how to take it back."],
     ["The person should know all of this."],
     ["Consent: agreement.",
      "Penalty: being treated worse."]),
    ("PSI 1.3.6",
     ["In an emergency, you act on your professional judgement.",
      "One example is when a client threatens suicide.",
      "You may act without consent if needed.",
      "If possible, you get full informed consent later."],
     ["Safety comes first in an emergency."],
     ["Informed consent: agreeing after being told what is involved."]),
    ("PSI 1.3.7",
     ["You take all reasonable steps to make sure consent is free.",
      "No one should be forced or pushed too hard to agree."],
     ["People agree because they want to."],
     ["Coercion: forcing someone.",
      "Undue pressure: pushing someone too hard."]),
    ("PSI 1.3.8",
     ["Sometimes consent is given under pressure or in great need.",
      "Then you take reasonable steps to confirm it is free.",
      "Or you get it again, freely."],
     ["You check again that the person really chose."],
     ["Duress: being forced or threatened."]),
    ("PSI 1.3.9",
     ["You get informed consent for research that intrudes on people.",
      "This includes research into private life, research with risks, or trying to change behaviour."],
     ["You always ask first in these cases."],
     ["Obtrusive: getting in the way or intruding."]),
    ("PSI 1.3.10",
     ["Some people have reduced capacity to decide.",
      "You seek their willing and well-informed part in things.",
      "You only go ahead without consent if it directly benefits that person."],
     ["You still include the person as much as you can."],
     ["Capacity: being able to understand and make a decision."]),
    ("PSI 1.3.11",
     ["Some people are not able to consent for themselves.",
      "You do the consent process with the person legally responsible.",
      "Or with the person appointed to consent for them."],
     ["You speak to the right person."],
     ["Competent: able to decide for yourself."]),
    ("PSI 1.3.12",
     ["Some people have reduced capacity to decide.",
      "Do not use them in research if it could be done as well with others."],
     ["People with fuller capacity take part instead."],
     ["Capacity: being able to understand and make a decision."]),
    ("PSI 1.3.13",
     ["Some research involves vulnerable groups or people with reduced capacity.",
      "Before you start, you seek an independent ethics review.",
      "It looks at human rights and protections."],
     ["Someone outside checks it is safe and fair."],
     ["Ethical review: a check by others that research is right and fair.",
      "Vulnerable: more at risk of harm."]),
    ("PSI 1.3.14",
     ["You only share information with the client's consent.",
      "The exceptions are when the law requires it.",
      "Or when hiding it would put the client or others in danger."],
     ["Safety can come before privacy."],
     ["Consent: agreement."]),
    ("PSI 1.3.15",
     ["You only discuss people's psychology data for work reasons.",
      "You only discuss it with people clearly entitled to know or be asked."],
     ["You do not talk about clients' results casually."],
     ["Evaluative data: results from assessments."]),
    ("PSI 1.3.16",
     ["You only publish information about clients with their consent.",
      "Or you hide who they are well enough.",
      "This applies to spoken and written information."],
     ["No one should be able to tell who the client is."],
     ["Publish: share with the public."]),
    ("PSI 1.3.17",
     ["You only make audio, video or photo records of people if they agree first.",
      "They agree to the recording.",
      "They also agree to who can see it later."],
     ["You ask before you record."],
     ["Research participant: a person who takes part in research."]),
    ("PSI 1.3.18",
     ["Sometimes interests clash.",
      "An example is a client's interests and your employer's.",
      "You make clear to everyone where your loyalties lie."],
     ["Everyone knows whose side you are on."],
     ["Conflict of interest: when two duties or interests pull against each other."]),
    ("PSI 1.3.19",
     ["Sometimes a third party asks for your service or research.",
      "Before getting consent, you explain your different relationships to everyone.",
      "You explain the purpose, how information will be used and the limits on privacy."],
     ["Everyone knows who asked you and why."],
     ["Third party: someone other than you and the client, such as a school."]),
    ("PSI 1.3.20",
     ["Sometimes trainees or other people want to be present.",
      "They are not directly giving the service.",
      "You get the client's consent to them being there."],
     ["You ask the client first."],
     ["Trainee: someone learning the job."]),
    ("PSI 1.4.1",
     ["You seek as full and active a part as possible from people.",
      "This is in decisions that affect them."],
     ["People have a real say."],
     ["Participation: taking part."]),
    ("PSI 1.4.2",
     ["You respect people's right to protect their own dignity.",
      "This includes clients, research participants, employees, supervisees and students."],
     ["You treat people in a way that keeps their dignity."],
     ["Dignity: being treated as a person who matters.",
      "Supervisee: a person you supervise."]),
    ("PSI 1.4.3",
     ["People have the right to stop taking part at any time.",
      "You respect this right.",
      "You respond to signs without words that a person wants to stop."],
     ["You watch body language, not just words."],
     ["Non-verbal: communicating without words, such as with your face or hands."]),
    # ------------------------------------------------------------ PSI 2
    ("PSI 2.1.1",
     ["You accept the duty to study the Code of Professional Ethics.",
      "You accept the duty to understand it."],
     ["You know what the Code says."],
     ["Code: a written set of rules."]),
    ("PSI 2.1.2",
     ["You avoid agreements or contracts that might make you break the Code."],
     ["You check a contract does not clash with the Code."],
     ["Contract: a formal agreement.",
      "Contravene: go against or break."]),
    ("PSI 2.2.1",
     ["You are aware of how your experiences, attitudes, culture, beliefs and values affect how you deal with others.",
      "You use this to help people and not harm them."],
     ["You notice your own views at work."],
     ["Attitude: the way you think or feel about something."]),
    ("PSI 2.2.2",
     ["You know the limits of your competence.",
      "You do not go beyond them."],
     ["You only do what you are trained and able to do."],
     ["Competence: having the skills and knowledge to do something well."]),
    ("PSI 2.2.3",
     ["You only offer or do work without supervision if you are competent in it.",
      "Your competence is established, so the work benefits others."],
     ["If you are not yet competent, you do not do it alone."],
     ["Competence: having the skills and knowledge to do something well.",
      "Supervision: guidance and checking from a more experienced worker."]),
    ("PSI 2.2.4",
     ["Sometimes you find you are not competent to deal with a client's problem.",
      "Then you act at once.",
      "You consult a colleague or refer the client to a suitable professional."],
     ["You do not wait."],
     ["Refer: ask another worker or service to help the person.",
      "Consult: ask for advice."]),
    ("PSI 2.2.5",
     ["You avoid giving work to people who are not competent to do it."],
     ["You only hand on tasks to people who can do them well."],
     ["Delegate: give a task to someone else.",
      "Competent: having the skills to do something well."]),
    ("PSI 2.3.1",
     ["Psychology data and methods have limits.",
      "You keep these limits in mind when you make decisions."],
     ["A test result is not the whole story."],
     ["Data: facts and results collected."]),
    ("PSI 2.3.2",
     ["Your support aims at clear goals.",
      "You stop when the goals are met.",
      "You also stop if it is clear they cannot be met."],
     ["You do not keep going without a reason."],
     ["Intervention: help or support that aims to make things better.",
      "Objective: a goal."]),
    ("PSI 2.3.3",
     ["You end an activity when it clearly does more harm than good.",
      "You also end it when it is no longer needed."],
     ["You stop what is not helping."],
     ["Terminate: end."]),
    ("PSI 2.3.4",
     ["Some new methods might carry risks.",
      "You test their effects first in pilot studies.",
      "You do this before thinking of wider use."],
     ["You try new things on a small scale first."],
     ["Pilot study: a small first test of something new."]),
    ("PSI 2.3.5",
     ["You only do scientific or professional work if the likely benefit outweighs the risk.",
      "The benefit must be large compared with the risk."],
     ["You weigh up benefit and risk first."],
     ["Proportionately: in fair balance compared with something else."]),
    ("PSI 2.3.6",
     ["Sometimes your work touches on social policy or how society is set up.",
      "Then you discuss the limits of your data fully."],
     ["You say clearly what your data can and cannot show."],
     ["Social policy: government plans that affect people's lives."]),
    ("PSI 2.4.1",
     ["You keep up your professional skills.",
      "You keep building them."],
     ["You keep learning."],
     ["Competence: having the skills and knowledge to do something well."]),
    ("PSI 2.4.2",
     ["You take part in continuing education.",
      "You help your own growth and your colleagues' growth.",
      "This covers both practice and science."],
     ["You learn, and you help others learn."],
     ["Continuing education: learning you keep doing after you qualify."]),
    ("PSI 2.4.3",
     ["You keep up to date with knowledge, research methods and techniques.",
      "You do this by reading and talking with peers.",
      "You also do it through continuing education."],
     ["You keep your knowledge fresh."],
     ["Peer consultation: talking through work with colleagues."]),
    ("PSI 2.4.4",
     ["When you teach, you prepare carefully.",
      "This keeps your teaching current and based on careful study."],
     ["Your teaching is up to date."],
     ["Scholarly: based on careful study."]),
    ("PSI 2.5.1",
     ["Sometimes a physical or mental condition seriously harms your judgement.",
      "Or it harms your ability to help and not harm.",
      "Then you stop practising.",
      "You get skilled help to decide whether to limit, pause or end your work."],
     ["You get help and do not carry on alone."],
     ["Impaired: weakened or damaged."]),
    # ------------------------------------------------------------ PSI 3
    ("PSI 3.1.1",
     ["You add to the knowledge of psychology.",
      "You help society understand itself.",
      "You do this by freely seeking and sharing knowledge."],
     ["You share what you learn."],
     ["Discipline: a field of study, such as psychology."]),
    ("PSI 3.1.2",
     ["You check and judge the effects of your work.",
      "You record what you find.",
      "Where it fits, you share new knowledge with others in your field."],
     ["You learn from your own work."],
     ["Evaluate: judge how well something works."]),
    ("PSI 3.1.3",
     ["You are aware of society's needs, issues and problems.",
      "You keep them in mind when you choose research questions and services.",
      "You also keep them in mind when you collect and read findings."],
     ["You think about the world around your work."],
     ["Findings: what research finds out."]),
    ("PSI 3.1.4",
     ["You protect the dignity of research participants at all times.",
      "You protect their wellbeing at all times."],
     ["People who take part are treated with respect and care."],
     ["Research participant: a person who takes part in research.",
      "Dignity: being treated as a person who matters."]),
    ("PSI 3.1.5",
     ["You help build and promote accountability for your work.",
      "You take part in it."],
     ["You are open to having your work checked."],
     ["Accountability: being answerable for what you do."]),
    ("PSI 3.1.6",
     ["You keep records of your psychology work for a suitable time.",
      "You store them properly, and pass them on properly if your role changes.",
      "You act fairly as an employer, judge, editor or reviewer."],
     ["Records stay safe and fair process is kept."],
     ["Adjudicator: someone who judges or decides a case.",
      "Peer reviewer: someone who checks colleagues' work."]),
    ("PSI 3.1.7",
     ["You make every reasonable effort to stop psychology being misused.",
      "This means misuse that breaks human rights.",
      "It covers misuse on purpose or by accident."],
     ["You watch how your knowledge is used."],
     ["Human rights: basic rights every person has."]),
    ("PSI 3.1.8",
     ["Sometimes the rules where you work seriously ignore or go against this Code.",
      "Then you speak out."],
     ["You do not stay silent."],
     ["Code: a written set of rules."]),
    ("PSI 3.2.1",
     ["Psychology has a duty to society.",
      "You uphold this by keeping the highest standards in your field."],
     ["You do your work to a high standard."],
     ["Discipline: a field of study, such as psychology."]),
    ("PSI 3.2.2",
     ["You keep the highest standards of honesty in your research."],
     ["Your research is honest and accurate."],
     ["Scientific integrity: being honest and accurate in research."]),
    ("PSI 3.2.3",
     ["You protect the good name of psychology.",
      "You do this by making sure all your work follows this Code."],
     ["Following the Code keeps trust in psychology."],
     ["Reputation: what people think of something."]),
    ("PSI 3.2.4",
     ["You act at work in a way that does not weaken public trust in psychology."],
     ["The way you act reflects on all psychologists."],
     ["Public confidence: the trust people have in something."]),
    ("PSI 3.3.1",
     ["You act at work in a way that does not damage clients' interests."],
     ["You keep the client's good in mind."],
     ["Client: a person you give a service to."]),
    ("PSI 3.3.2",
     ["People differ, and some are more vulnerable.",
      "You know enough about this to see what will help and not harm."],
     ["You notice each person's needs and risks."],
     ["Vulnerable: more at risk of harm."]),
    ("PSI 3.3.3",
     ["You assess people, families, groups and communities well enough.",
      "This lets you see what will help and not harm them."],
     ["You find out enough before you act."],
     ["Assess: find out about strengths and needs."]),
    ("PSI 3.3.4",
     ["Sometimes others' actions are likely to cause serious physical harm or death.",
      "You do everything you reasonably can to stop it or lessen the harm.",
      "This includes telling the right authorities or the person at risk."],
     ["You do this even when the relationship is confidential."],
     ["Authorities: official bodies, such as the Gardaí.",
      "Confidential: private, not to be shared."]),
    ("PSI 3.3.5",
     ["You make every reasonable effort to stop psychology being misused.",
      "This means misuse that harms others or breaks human rights."],
     ["You watch how your knowledge is used."],
     ["Human rights: basic rights every person has."]),
    ("PSI 3.3.6",
     ["Only qualified and trained people should use tests and assessment methods.",
      "You take all reasonable steps to make sure of this."],
     ["You do not hand tests to people who are not trained."],
     ["Assessment: finding out about a person's strengths and needs."]),
    ("PSI 3.3.7",
     ["Some people may use knowledge or skills to harm others or break human rights.",
      "If you judge this, you refuse to advise, train or inform them."],
     ["You say no."],
     ["Human rights: basic rights every person has."]),
    ("PSI 3.3.8",
     ["You do not take part in work that promotes harm to people's minds.",
      "Or work on banned weapons, or harm to the environment.",
      "Or anything that breaks international law."],
     ["You do not help with such work at all."],
     ["Psychological integrity: a person's mental wholeness and wellbeing.",
      "International law: laws agreed between countries."]),
    ("PSI 3.3.9",
     ["You act to lessen the effect of research on participants.",
      "This covers their personality and their mental or physical wellbeing."],
     ["Research should do as little harm as possible."],
     ["Research participant: a person who takes part in research."]),
    ("PSI 3.3.10",
     ["Sometimes research might harm some participants.",
      "Then you screen people first.",
      "You choose people who are not likely to be harmed."],
     ["You check who is safe to take part."],
     ["Screen: check people before they take part."]),
    ("PSI 3.3.11",
     ["After research, you debrief participants.",
      "This helps you find any harm caused.",
      "You act to put right any harm."],
     ["You talk with people after they take part."],
     ["Debrief: talk with someone afterwards about what happened."]),
    ("PSI 3.3.12",
     ["Some studies have a control group that gets no service.",
      "Do not leave them without service for an unreasonable time.",
      "If the service helps, you then offer it to the control group."],
     ["No one misses out unfairly."],
     ["Control group: people in a study who do not get the service, so results can be compared."]),
    ("PSI 3.3.13",
     ["You do not offer rewards to get people to take part in risky activity.",
      "This covers possible or known risks."],
     ["People should not take risks for a reward."],
     ["Reward: something given in return, such as money."]),
    ("PSI 3.3.14",
     ["Some research uses methods with unknown effects.",
      "Some may cause pain, discomfort or harm.",
      "For these, you seek an independent ethics review.",
      "It weighs up the risks and benefits."],
     ["Someone outside checks the balance of risk."],
     ["Ethical review: a check by others that research is right and fair."]),
    ("PSI 3.3.15",
     ["Take special care when reporting results about vulnerable groups.",
      "This helps stop results being misread or misused.",
      "This matters in social policy, attitudes and practices."],
     ["You think about how others might use your results."],
     ["Vulnerable: more at risk of harm.",
      "Social policy: government plans that affect people's lives."]),
    ("PSI 3.3.16",
     ["You refuse to help people do things that would cause serious harm.",
      "This means serious physical or psychological harm to themselves or others.",
      "It applies to people, families, groups and communities."],
     ["You say no to harmful activity."],
     ["Psychological harm: harm to a person's mind or feelings."]),
    ("PSI 3.3.17",
     ["You only use animals in research if it may add to understanding.",
      "Or if it may in the end help the health and welfare of people or animals."],
     [_OUT],
     ["Welfare: health, safety and happiness."]),
    ("PSI 3.3.18",
     ["You only cause animals pain, stress or deprivation if there is no other way.",
      "And the goal must be justified by what may be gained."],
     [_OUT],
     ["Deprivation: going without something needed."]),
    ("PSI 3.3.19",
     ["You do all you can to reduce discomfort, illness and pain in animals."],
     [_OUT],
     ["Discomfort: feeling unwell or uneasy."]),
    ("PSI 3.3.20",
     ["You only use animals in class demonstrations if there is no other way to teach it.",
      "The likely gain must justify it."],
     [_OUT],
     ["Demonstration: showing how something works."]),
    ("PSI 3.4.1",
     ["You learn about the knowledge and skills of other fields, such as law and medicine.",
      "You advise using this knowledge where it would help people."],
     ["You know when another field could help."],
     ["Discipline: a field of study or work."]),
    ("PSI 3.4.2",
     ["You try to get the best possible service for people who need psychology help.",
      "This may mean recommending other professionals, if suitable."],
     ["The person's needs come first."],
     ["Recommend: suggest."]),
    ("PSI 3.4.3",
     ["When you refer a client, you stay responsible for their care.",
      "You keep supporting them until contact with the new service has started."],
     ["The client is not left without support."],
     ["Refer: ask another worker or service to help the person."]),
    ("PSI 3.4.4",
     ["Before you stop a service, you give reasonable notice.",
      "You make reasonably sure that stopping will not harm the client."],
     ["Ending is planned, not sudden."],
     ["Discontinue: stop."]),
    ("PSI 3.4.5",
     ["Where it fits, you help join up a client's services.",
      "This avoids doing things twice or working against each other.",
      "You keep good records and talk with other providers."],
     ["Services work together."],
     ["Co-ordination: organising people to work together."]),
    ("PSI 3.5.1",
     ["You take overall ethical responsibility for the work of those you supervise.",
      "You keep an eye on their work.",
      "You make them aware of the values and ethics of psychology."],
     ["You are responsible for how they work."],
     ["Supervise: guide and check someone's work.",
      "Subordinate: someone who works under you."]),
    ("PSI 3.5.2",
     ["You help the people you supervise grow in their work.",
      "You arrange suitable work experience.",
      "You give helpful feedback."],
     ["You help them learn."],
     ["Constructive feedback: comments that help someone improve."]),
    ("PSI 3.5.3",
     ["You guard against others misusing psychology data.",
      "You also guard against them misreading it."],
     ["You explain results so they are used well."],
     ["Data: facts and results collected."]),
    ("PSI 3.6.1",
     ["You use a step-by-step method to look into ethics issues.",
      "You use it to solve ethical dilemmas.",
      "The Code gives a method in its Appendix A."],
     ["You work through hard choices in order."],
     ["Ethical dilemma: a hard choice where rights or duties clash."]),
    ("PSI 3.6.2",
     ["Sometimes a real or possible conflict of interest arises.",
      "You tell all sides it must be solved in line with this Code.",
      "You take all reasonable steps to solve it."],
     ["You are open about it."],
     ["Conflict of interest: when two duties or interests pull against each other."]),
    ("PSI 3.6.3",
     ["Sometimes a case is hard, or the law seems to clash with ethics.",
      "Then you talk with colleagues or suitable groups and committees.",
      "In an emergency with no time to talk, you use your own best judgement."],
     ["You do not decide alone if you can help it."],
     ["Consult: ask for advice."]),
    # ------------------------------------------------------------ PSI 4
    ("PSI 4.1.1",
     ["You take part in self-care.",
      "This helps you avoid problems like burnout or addiction.",
      "These could harm your judgement and your ability to help and not harm."],
     ["Looking after yourself protects the people you serve."],
     ["Burnout: being worn out by stress at work.",
      "Self-care: looking after yourself."]),
    ("PSI 4.1.2",
     ["Sometimes hard work problems leave you stressed or vulnerable.",
      "Then you seek emotional support or supervision from colleagues."],
     ["You do not cope alone."],
     ["Supervision: regular meetings with a more experienced worker about your work."]),
    ("PSI 4.2.1",
     ["You describe your education, training and experience truthfully.",
      "You describe how well your services work truthfully.",
      "You make sure others do too.",
      "You act quickly to fix anything wrong."],
     ["You are honest about what you can do."],
     ["Misrepresentation: giving a false picture."]),
    ("PSI 4.2.2",
     ["You take care not to get things wrong, overstate them or twist them.",
      "This covers assessment results, research and how well services work.",
      "You act quickly to fix any error."],
     ["You report results honestly."],
     ["Distortion: twisting the facts."]),
    ("PSI 4.2.3",
     ["You make clear who you are speaking for.",
      "This may be yourself as a private person, a group, or psychology as a whole."],
     ["People know in which role you speak."],
     ["Private citizen: speaking only for yourself."]),
    ("PSI 4.2.4",
     ["You make sure families and others know one thing.",
      "The psychologist's main duty is usually to the individual."],
     ["You explain this at the start."],
     ["Individual: the one person you are working with."]),
    ("PSI 4.2.5",
     ["When you share what you know, you make clear what is fact.",
      "You make clear what is opinion, theory, hypothesis or idea."],
     ["People can tell a fact from a view."],
     ["Hypothesis: an idea that has not been proved yet."]),
    ("PSI 4.2.6",
     ["You do not hide evidence that goes against your findings or views.",
      "You accept that there may be other explanations."],
     ["You are open about all the evidence."],
     ["Disconfirming evidence: facts that do not support your view."]),
    ("PSI 4.2.7",
     ["You do research in an honest and open way.",
      "You clearly say what could affect it.",
      "This includes its aims, who pays, its social context, your values or money interests."],
     ["Readers can see what might shape the research."],
     ["Sponsorship: who pays for or backs something."]),
    ("PSI 4.2.8",
     ["You pay people fairly for their time, energy and intelligence.",
      "This does not apply if they refuse payment in advance."],
     [_OUT],
     ["Compensate: pay back or reward."]),
    ("PSI 4.2.9",
     ["You do not accept or seek fees beyond those agreed in advance.",
      "You do not accept large gifts that would make you less fair."],
     [_OUT],
     ["Impartiality: being fair and not taking sides."]),
    ("PSI 4.2.10",
     ["You do not take part in dishonesty or fraud.",
      "You do not accept it or allow yourself to be linked with it."],
     ["You stay away from anything dishonest."],
     ["Fraud: cheating people, often for money."]),
    ("PSI 4.2.11",
     ["You keep all promises and agreements, written or spoken.",
      "Sometimes serious and unexpected events get in the way.",
      "Then you give a full and honest explanation."],
     ["People can rely on your word."],
     ["Commitment: a promise to do something."]),
    ("PSI 4.2.12",
     ["When you make contracts with third parties, you are clear about your duties under this Code.",
      "You make sure everyone knows their rights and responsibilities."],
     ["All sides know the rules."],
     ["Third party: someone other than you and the client, such as a school."]),
    ("PSI 4.2.13",
     ["Some people pay for or ask for research.",
      "You make sure they know the rights and responsibilities of everyone involved."],
     ["All sides know the rules."],
     ["Commission: ask for and pay for a piece of work."]),
    ("PSI 4.2.14",
     ["You agree with those who commission research who owns the documents and data.",
      "You also agree who has the right to publish."],
     ["This is clear from the start."],
     ["Commission: ask for and pay for a piece of work.",
      "Publish: share with the public."]),
    ("PSI 4.2.15",
     ["You give credit in publications to others who helped, including students.",
      "The credit matches how much they gave."],
     ["People get fair credit for their work."],
     ["Publication credit: being named on published work."]),
    ("PSI 4.3.1",
     ["Clients and research participants have a right to an explanation.",
      "It covers the nature, purpose and results of assessments and research.",
      "You respect this right.",
      "You use language they can understand."],
     ["You explain results clearly."],
     ["Research participant: a person who takes part in research."]),
    ("PSI 4.3.2",
     ["You are clear about all that is needed for informed consent or any agreement.",
      "This includes fees, what each side does, and the purpose.",
      "It includes options, likely experiences, possible conflicts and outcomes.",
      "It includes how information will be used and shared."],
     ["Nothing is hidden."],
     ["Informed consent: agreeing after being told what is involved."]),
    ("PSI 4.3.3",
     ["You fully explain the reasons for your actions to people affected by them.",
      "You do this where it fits, or if they ask."],
     ["People know why you acted."],
     ["Justify: give good reasons for."]),
    ("PSI 4.3.4",
     ["You avoid deception in research or services if other options exist.",
      "You also avoid it if bad effects cannot be predicted or put right.",
      "This includes methods that might seem like deception."],
     [_OUT],
     ["Deception: misleading someone."]),
    ("PSI 4.3.5",
     ["If a study used deception, you debrief participants afterwards.",
      "You explain what really happened and why.",
      "You clear up wrong ideas and rebuild trust."],
     [_OUT],
     ["Debrief: talk with someone afterwards about what happened.",
      "Deception: misleading someone."]),
    ("PSI 4.3.6",
     ["Before research that uses deception, you seek an independent ethics review.",
      "It looks at the risks to public or personal trust."],
     [_OUT],
     ["Deception: misleading someone.",
      "Ethical review: a check by others that research is right and fair."]),
    ("PSI 4.4.1",
     ["You do not use any work relationship for your own gain.",
      "This includes personal, political or business gain."],
     ["The work is for the client, not for you."],
     ["Exploit: use someone unfairly for your own benefit."]),
    ("PSI 4.4.2",
     ["You do not exploit clients for sexual reasons.",
      "This applies during the work relationship.",
      "It also applies after it ends."],
     ["It still applies after the work ends."],
     ["Exploit: use someone unfairly for your own benefit."]),
    ("PSI 4.4.3",
     ["Dual relationships can cause problems, and you are very aware of this.",
      "They cannot always be avoided.",
      "Where possible, you avoid them.",
      "Where not, you take steps to protect students, employees or clients."],
     ["You keep roles clear."],
     ["Dual relationship: when you have two different roles with the same person."]),
    ("PSI 4.4.4",
     ["You do not use your work position to form, or try to form, some kinds of relationship.",
      "This means relationships that are sexual, emotionally wrong or exploitative."],
     ["This applies to any person."],
     ["Exploitative: using someone unfairly for your own benefit."]),
    ("PSI 4.5.1",
     ["A colleague or other worker may do clearly harmful or unethical work.",
      "You act to stop it or lessen its effects.",
      "You deal with it informally where you can.",
      "If the harm is serious or goes on, you report it to the right body."],
     ["You do not ignore it."],
     ["Regulatory body: an official group that sets and checks rules for a profession.",
      "Unethical: not right or fair."]),
    ("PSI 4.5.2",
     ["Colleagues may ask you for emotional support or supervision.",
      "You offer it, where it fits."],
     ["You support your colleagues."],
     ["Supervision: guidance and checking from a more experienced worker."]),
]

EASY = {"standard::" + n: _build(n, s, p, w) for n, s, p, w in _R}
