SKILL_TOPICS = {
    'Familiarise with SET provision and allocation || Understand how SET hours are allocated': ['ALL'],
    "Familiarise with SET provision and allocation || Cite the specific circular rather than 'guidance'": ['ALL'],
    'Familiarise with SET provision and allocation || Know how the school deploys what it has': ['ALL'],
    'Familiarise with SET provision and allocation || Know the SENO route and what the NCSE can do': ['Autism', 'General Learning Disability (GLD) / Intellectual Disability', 'Global Developmental Delay (GDD)', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Cerebral palsy (spastic / dyskinetic / ataxic / mixed)', 'Spina bifida (including associated hydrocephalus)', 'Muscular dystrophy', 'Hearing impairment (Deaf / hard of hearing)', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)', 'Acquired brain injury', 'Epilepsy (and its educational impact)', 'Developmental Language Disorder (DLD)'],
    "Map the school's organisation of supports || Map each Continuum level against provision": ['ALL'],
    "Map the school's organisation of supports || Identify a gap in the continuum": ['ALL'],
    "Map the school's organisation of supports || Say what would close the gap": ['ALL'],
    "Map the school's organisation of supports || Present the map back to the school": ['ALL'],
    'Visit a range of special education settings || Arrange visits early in the placement': ['ALL'],
    'Visit a range of special education settings || Observe structure, staffing and communication supports': ['Autism', 'General Learning Disability (GLD) / Intellectual Disability', 'Global Developmental Delay (GDD)', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Hearing impairment (Deaf / hard of hearing)', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)', 'Cerebral palsy (spastic / dyskinetic / ataxic / mixed)', 'Developmental Language Disorder (DLD)', 'Spina bifida (including associated hydrocephalus)', 'Muscular dystrophy', 'Acquired brain injury'],
    'Visit a range of special education settings || Talk to therapy and SNA staff, not only teachers': ['Cerebral palsy (spastic / dyskinetic / ataxic / mixed)', 'Spina bifida (including associated hydrocephalus)', 'Muscular dystrophy', 'Autism', 'General Learning Disability (GLD) / Intellectual Disability', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Hearing impairment (Deaf / hard of hearing)', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)', 'Global Developmental Delay (GDD)', 'Acquired brain injury', 'Epilepsy (and its educational impact)', 'Developmental Coordination Disorder (DCD / dyspraxia)'],
    'Visit a range of special education settings || Log each visit separately in Appendix 5': ['ALL'],
    'Attend service team meetings || Understand how casework is prioritised here': ['ALL'],
    'Attend service team meetings || Note what the service can and cannot offer': ['ALL'],
    'Attend service team meetings || Prepare something to contribute': ['ALL'],
    'Attend service team meetings || Contribute a psychological perspective': ['ALL'],
    'Learn consultation models || Learn a structured problem-solving model': ['ALL'],
    'Learn consultation models || Learn a solution-focused approach': ['ALL'],
    'Learn consultation models || Ask your supervisor which model they use': ['ALL'],
    'Learn consultation models || Follow one model explicitly for a set of consultations': ['ALL'],
    'Deliver the good practice presentation || Cite current peer-reviewed evidence': ['ALL'],
    'Deliver the good practice presentation || Pitch it at teachers rather than examiners': ['ALL'],
    'Deliver the good practice presentation || End with three things the school could do this term': ['ALL'],
    'Deliver the good practice presentation || Collect and file feedback from the school': ['ALL'],
    'Build rapport with a child during assessment || Meet the child at their level, literally and in register': ['ALL'],
    'Build rapport with a child during assessment || Explain what will happen and why': ['ALL'],
    'Build rapport with a child during assessment || Give the child a real choice early': ['ALL'],
    'Build rapport with a child during assessment || Notice and respond to reluctance': ['ALL'],
    'Build rapport with a child during assessment || Ask the child what they think would help': ['ALL'],
    'Build rapport with a child during assessment || Close so the child leaves feeling competent': ['ALL'],
    'Communicate with school staff, SENCO and principal || Know who does what in this school': ['ALL'],
    'Communicate with school staff, SENCO and principal || Negotiate a shared referral question': ['ALL'],
    'Communicate with school staff, SENCO and principal || Manage disagreement rather than avoiding it': ['ALL'],
    'Communicate with school staff, SENCO and principal || Maintain the relationship afterwards': ['ALL'],
    'Give feedback to parents on assessment findings || Prepare the structure before the meeting': ['ALL'],
    'Give feedback to parents on assessment findings || Use plain language and check understanding': ['ALL'],
    'Give feedback to parents on assessment findings || Lead with the child, not the scores': ['ALL'],
    'Give feedback to parents on assessment findings || Name strengths specifically': ['ALL'],
    'Give feedback to parents on assessment findings || Hold distress without rushing past it': ['ALL'],
    'Give feedback to parents on assessment findings || Leave the parent with something concrete': ['ALL'],
    "Keep case notes to service standard || Use the service's format and terminology": ['ALL'],
    'Keep case notes to service standard || Store and transfer records lawfully': ['ALL'],
    'Keep case notes to service standard || Separate fact from opinion and label opinion': ['ALL'],
    'Keep case notes to service standard || Avoid conjecture': ['ALL'],
    'Keep case notes to service standard || Write the same day': ['ALL'],
    'Keep case notes to service standard || Record consent, contacts and decisions': ['ALL'],
    'Produce the psychological report to countersigning standard || Know the countersigning standard before drafting': ['ALL'],
    'Produce the psychological report to countersigning standard || Proofread against the service template': ['ALL'],
    'Produce the psychological report to countersigning standard || Include a tool rationale': ['ALL'],
    'Produce the psychological report to countersigning standard || Include an integration section': ['ALL'],
    'Produce the psychological report to countersigning standard || Name the framework in the formulation': ['ALL'],
    'Produce the psychological report to countersigning standard || Include a limitations paragraph': ['ALL'],
    'Produce the psychological report to countersigning standard || Write recommendations a teacher could act on Monday': ['ALL'],
    "Produce the psychological report to countersigning standard || Quote the child's own words": ['ALL'],
    'Adapt written communication to the audience || Judge who will read this and what they need': ['ALL'],
    'Adapt written communication to the audience || Change register between family and professional audiences': ['ALL'],
    'Adapt written communication to the audience || Produce an accessible or plain-language version': ['English as an Additional Language and bilingual development (DLD vs EAL)', 'General Learning Disability (GLD) / Intellectual Disability', 'Dyslexia / Specific Learning Disorder with impairment in reading', 'Hearing impairment (Deaf / hard of hearing)', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)', 'Borderline Intellectual Functioning (BIF)', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)'],
    'Adapt written communication to the audience || Check the young person could read what is written about them': ['General Learning Disability (GLD) / Intellectual Disability', 'Borderline Intellectual Functioning (BIF)', 'Dyslexia / Specific Learning Disorder with impairment in reading', 'Developmental Language Disorder (DLD)', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)', 'English as an Additional Language and bilingual development (DLD vs EAL)', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Acquired brain injury'],
    'Garda vetting and Children First certification || Submit vetting early enough to clear before day one': ['ALL'],
    'Garda vetting and Children First certification || Complete Children First training and file the certificate': ['ALL'],
    'Garda vetting and Children First certification || Know the Tusla reporting thresholds': ['ALL'],
    'Garda vetting and Children First certification || Know you are a mandated person and what that means': ['ALL'],
    'Complete service induction || Complete health and safety and lone working induction': ['ALL'],
    'Complete service induction || Identify the DLP by name in week one': ['ALL'],
    'Complete service induction || Learn the referral and risk pathways': ['Major Depressive Disorder', 'Persistent Depressive Disorder (dysthymia)', 'Bipolar and related disorders (Bipolar I, Bipolar II, Cyclothymic Disorder)', 'Psychotic disorders (schizophrenia spectrum and other psychotic disorders)', 'Anorexia Nervosa', 'Bulimia Nervosa', 'Binge-Eating Disorder', 'Avoidant/Restrictive Food Intake Disorder (ARFID)', 'Posttraumatic Stress Disorder (PTSD), including Complex PTSD', 'Substance use disorders', 'Personality disorders (emerging in adolescence)', 'Dissociative disorders (Dissociative Identity Disorder, Dissociative Amnesia, Depersonalisation/Derealisation)', 'Catatonia', 'Relational problems and children in care (upbringing away from parents)'],
    'Complete service induction || Learn the records, IT and information governance policy': ['ALL'],
    'Complete service induction || Ask which tools you may administer independently here': ['ALL'],
    'Obtain informed consent and assent || Explain purpose, process and who will see the report': ['ALL'],
    'Obtain informed consent and assent || State the right to stop or withdraw': ['ALL'],
    'Obtain informed consent and assent || State the limits of confidentiality before disclosure': ['ALL'],
    'Obtain informed consent and assent || Establish who holds guardianship before contact': ['Relational problems and children in care (upbringing away from parents)', 'Reactive Attachment Disorder (RAD)', 'Disinhibited Social Engagement Disorder (DSED)', 'Posttraumatic Stress Disorder (PTSD), including Complex PTSD', 'Foetal Alcohol Spectrum Disorder'],
    'Obtain informed consent and assent || Use supported decision-making where capacity is in question': ['General Learning Disability (GLD) / Intellectual Disability', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Acquired brain injury', 'Global Developmental Delay (GDD)', 'Borderline Intellectual Functioning (BIF)', 'Autism', 'Psychotic disorders (schizophrenia spectrum and other psychotic disorders)', 'Catatonia', 'Bipolar and related disorders (Bipolar I, Bipolar II, Cyclothymic Disorder)'],
    'Obtain informed consent and assent || Recognise and respond to non-verbal withdrawal': ['Autism', 'General Learning Disability (GLD) / Intellectual Disability', 'Global Developmental Delay (GDD)', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Selective Mutism', 'Developmental Language Disorder (DLD)', 'Cerebral palsy (spastic / dyskinetic / ataxic / mixed)', 'Hearing impairment (Deaf / hard of hearing)', 'Social Anxiety Disorder (social phobia)', 'Social (Pragmatic) Communication Disorder', 'Posttraumatic Stress Disorder (PTSD), including Complex PTSD'],
    'Obtain informed consent and assent || Obtain assent from the child in their own language': ['English as an Additional Language and bilingual development (DLD vs EAL)', 'Hearing impairment (Deaf / hard of hearing)', 'Developmental Language Disorder (DLD)', 'Autism', 'General Learning Disability (GLD) / Intellectual Disability', 'Global Developmental Delay (GDD)', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Selective Mutism', 'Cerebral palsy (spastic / dyskinetic / ataxic / mixed)', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)', 'Speech Sound Disorder'],
    'Obtain informed consent and assent || Record what was explained, not just that consent was given': ['ALL'],
    'Recognise and act on child protection concerns || Recognise a concern against the threshold': ['ALL'],
    'Recognise and act on child protection concerns || Do not investigate or question further': ['ALL'],
    'Recognise and act on child protection concerns || Record verbatim what was said or seen, at the time': ['ALL'],
    'Recognise and act on child protection concerns || Act the same day without waiting for supervision': ['ALL'],
    'Recognise and act on child protection concerns || Report to the DLP and record the time': ['ALL'],
    'Recognise and act on child protection concerns || Bring it to supervision afterwards, not instead': ['ALL'],
    'Work an ethical dilemma through a decision procedure || Identify the issue and all affected parties': ['ALL'],
    'Work an ethical dilemma through a decision procedure || Scan the Code for the clauses that apply': ['ALL'],
    "Work an ethical dilemma through a decision procedure || Evaluate each party's rights and responsibilities": ['ALL'],
    'Work an ethical dilemma through a decision procedure || Generate as many alternative courses as possible': ['ALL'],
    'Work an ethical dilemma through a decision procedure || Evaluate the likely outcome of each': ['ALL'],
    'Work an ethical dilemma through a decision procedure || Decide and record the decision': ['ALL'],
    'Work an ethical dilemma through a decision procedure || Take responsibility for the consequences': ['ALL'],
    'Work an ethical dilemma through a decision procedure || Keep notes at each stage': ['ALL'],
    'State and hold the limits of your competence || Know your publisher competence level for every tool': ['ALL'],
    'State and hold the limits of your competence || Say early what you are not yet competent to do': ['ALL'],
    'State and hold the limits of your competence || Decline work that exceeds you': ['ALL'],
    'State and hold the limits of your competence || Refer on and maintain responsibility until contact is made': ['ALL'],
    'State and hold the limits of your competence || Include a limitations paragraph in every report': ['ALL'],
    'Manage workload and your own wellbeing || Track your actual caseload and travel load': ['ALL'],
    'Manage workload and your own wellbeing || Recognise your own warning signs': ['ALL'],
    'Manage workload and your own wellbeing || Raise workload before it becomes a problem': ['ALL'],
    'Manage workload and your own wellbeing || Seek supervision when stressed, not only when stuck': ['ALL'],
    'Manage workload and your own wellbeing || Know the seven-day notification duty': ['ALL'],
    'Manage workload and your own wellbeing || Refrain from practice where judgement is seriously impaired': ['ALL'],
    'Agree and sign the supervision contract || Know the 30 minutes per placement day entitlement': ['ALL'],
    'Agree and sign the supervision contract || Know the four components expected': ['ALL'],
    'Agree and sign the supervision contract || Bring a draft to week one': ['ALL'],
    'Agree and sign the supervision contract || Record day, time, duration and format': ['ALL'],
    'Agree and sign the supervision contract || Agree how cancellations are handled': ['ALL'],
    'Agree and sign the supervision contract || Both sign and date it': ['ALL'],
    'Take the weekly supervision hour || Protect the hour': ['ALL'],
    'Take the weekly supervision hour || Raise it if it slips twice': ['ALL'],
    'Take the weekly supervision hour || Keep to 30 minutes per placement day cumulatively': ['ALL'],
    'Prepare and send an agenda in advance || Send it the day before': ['ALL'],
    'Prepare and send an agenda in advance || Keep it to three items': ['ALL'],
    'Prepare and send an agenda in advance || Update on actions agreed last time': ['ALL'],
    'Prepare and send an agenda in advance || Include at least one thing that went badly': ['ALL'],
    'Keep supervision session records || Complete a record for every session': ['ALL'],
    'Keep supervision session records || Record topics, actions and who does what': ['ALL'],
    'Keep supervision session records || Get them co-signed': ['ALL'],
    'Keep supervision session records || Tag which of the four components the session covered': ['ALL'],
    'Keep supervision session records || Record any ethical dilemma using the seven steps': ['ALL'],
    'Observe your supervisor with a client || Arrange it in the first weeks': ['ALL'],
    'Observe your supervisor with a client || Agree a focus before observing': ['ALL'],
    'Observe your supervisor with a client || Record what they did that you would not have': ['ALL'],
    'Observe your supervisor with a client || Ask afterwards why they did it that way': ['ALL'],
    'Be observed with a client || Arrange both observations early': ['ALL'],
    'Be observed with a client || Request a focus you find hard': ['ALL'],
    'Be observed with a client || Receive critical feedback without defending': ['ALL'],
    'Be observed with a client || Act on the feedback and say so next time': ['ALL'],
    'Raise immediate concerns out of session || Know what counts as immediate here': ['ALL'],
    'Raise immediate concerns out of session || Know how to reach your supervisor out of session': ['ALL'],
    'Raise immediate concerns out of session || Act first where the duty is yours': ['ALL'],
    'Raise immediate concerns out of session || Record the contact and what was agreed': ['ALL'],
    'Contribute to peer and group supervision || Attend consistently': ['ALL'],
    'Contribute to peer and group supervision || Present a case at least once a trimester': ['ALL'],
    'Contribute to peer and group supervision || Bring a case from an under-covered age band': ['ALL'],
    "Contribute to peer and group supervision || Offer something useful to someone else's case": ['ALL'],
    'Complete Appendix 6 before and after || Rate all eight before day one, dated': ['ALL'],
    'Complete Appendix 6 before and after || Rate honestly, including low': ['ALL'],
    'Complete Appendix 6 before and after || Name two or three priority targets': ['ALL'],
    'Complete Appendix 6 before and after || Carry the targets into the next Placement Plan': ['ALL'],
    'Complete Appendix 6 before and after || Rate again at the end and compare': ['ALL'],
    'Write the reflective learning essay || Cover placement, college sessions and independent study': ['ALL'],
    'Write the reflective learning essay || Name what was hard and what it cost': ['ALL'],
    'Write the reflective learning essay || Reflect on your own culture, values and biases': ['ALL'],
    'Write the reflective learning essay || Trace a change in practice to a specific reflection': ['ALL'],
    'Write the reflective learning essay || Name a self-care strategy and evidence it works': ['ALL'],
    'Search and critically appraise evidence || Frame an answerable question from a real referral': ['ALL'],
    'Search and critically appraise evidence || Search a database rather than a search engine': ['ALL'],
    'Search and critically appraise evidence || Record the search terms and databases used': ['ALL'],
    'Search and critically appraise evidence || Appraise quality rather than accepting the first result': ['ALL'],
    'Search and critically appraise evidence || Judge applicability to this child in this context': ['ALL'],
    'Search and critically appraise evidence || Log the search as an Appendix 5 research entry': ['ALL'],
    'Cite evidence for recommendations || Attach a source to every substantial recommendation': ['ALL'],
    'Cite evidence for recommendations || Cite current sources rather than the familiar ones': ['ALL'],
    'Cite evidence for recommendations || Use APA 7th consistently': ['ALL'],
    'Cite evidence for recommendations || Say where the evidence is thin': ['ALL'],
    'State how a recommendation would be evaluated || Name the measure': ['ALL'],
    'State how a recommendation would be evaluated || Name who will measure it': ['ALL'],
    'State how a recommendation would be evaluated || Name when': ['ALL'],
    'State how a recommendation would be evaluated || Say what would count as no progress': ['ALL'],
    'State how a recommendation would be evaluated || Follow up whether anyone acted on it': ['ALL'],
}
