PRES_TOPICS = {
    'Working memory difficulty': ['ADHD', 'Developmental Language Disorder (DLD)', 'Dyslexia / Specific Learning Disorder with impairment in reading'],
    'Inhibition difficulty': ['ADHD'],
    'Cognitive flexibility difficulty': ['Autism', 'ADHD'],
    'Planning and organisation difficulty': ['ADHD', 'Developmental Coordination Disorder (DCD / dyspraxia)'],
    'Task initiation difficulty': ['ADHD'],
    'Self-monitoring difficulty': ['ADHD'],
    'Motivation and engagement with work': ['ADHD', 'Major Depressive Disorder'],
    'Work rate and pace of output': ['ADHD', 'Developmental Coordination Disorder (DCD / dyspraxia)', 'Specific Learning Disorder with impairment in written expression (dysgraphia)'],
    'Homework completion and follow-through': ['ADHD'],
    'Organisation of materials, books and equipment': ['ADHD', 'Developmental Coordination Disorder (DCD / dyspraxia)'],
    'Sustained attention in whole-class vs one-to-one': ['ADHD', 'Hearing impairment (Deaf / hard of hearing)'],
    'Note-taking and recording from the board': ['Specific Learning Disorder with impairment in written expression (dysgraphia)', 'Developmental Coordination Disorder (DCD / dyspraxia)', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)'],
    'Study skills and revision strategy': [],
    'Help-seeking': [],
    'Fatigue, sleep and time-of-day effects on attention': ['Sleep disorders (sleep–wake disorders)', 'ADHD', 'Epilepsy (and its educational impact)'],
    'AAC and communication access': ['Cerebral palsy (spastic / dyskinetic / ataxic / mixed)', 'Autism', 'Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)'],
    'English as an Additional Language (EAL)': ['English as an Additional Language and bilingual development (DLD vs EAL)', 'Developmental Language Disorder (DLD)'],
    'Bilingual language development': ['English as an Additional Language and bilingual development (DLD vs EAL)', 'Developmental Language Disorder (DLD)'],
    'Vocabulary gap from limited exposure': ['Developmental Language Disorder (DLD)', 'English as an Additional Language and bilingual development (DLD vs EAL)'],
    'Participation in oral work and classroom talk': ['Social Anxiety Disorder (social phobia)', 'Selective Mutism', 'Developmental Language Disorder (DLD)'],
    'Following multi-step verbal instructions': ['Developmental Language Disorder (DLD)', 'ADHD', 'Hearing impairment (Deaf / hard of hearing)'],
    'Narrative and sequencing in spoken account': ['Developmental Language Disorder (DLD)', 'Social (Pragmatic) Communication Disorder'],
    'Word-finding difficulty': ['Developmental Language Disorder (DLD)', 'Dyslexia / Specific Learning Disorder with impairment in reading'],
    'Interpreter need and how it changes the assessment': ['English as an Additional Language and bilingual development (DLD vs EAL)'],
    'Cognitive profile differences (verbal, fluid, working memory, processing speed)': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'Developmental Language Disorder (DLD)', 'Borderline Intellectual Functioning (BIF)'],
    'Underachievement not meeting SLD criteria': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'Borderline Intellectual Functioning (BIF)'],
    'Giftedness / exceptional ability': [],
    'Twice exceptional (high ability plus SLD, ADHD or ASD)': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'ADHD', 'Autism'],
    'Understanding and responding to adult direction': ['Developmental Language Disorder (DLD)', 'Oppositional Defiant Disorder (ODD)', 'ADHD'],
    'Curriculum access at the current level': ['General Learning Disability (GLD) / Intellectual Disability', 'Borderline Intellectual Functioning (BIF)'],
    'Interrupted or missed schooling': [],
    'Auditory processing concerns': ['Developmental Language Disorder (DLD)', 'Hearing impairment (Deaf / hard of hearing)', 'ADHD'],
    'Literacy difficulty not meeting SLD criteria': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'Specific Learning Disorder with impairment in written expression (dysgraphia)'],
    'Reading stamina and avoidance of reading aloud': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'Visual impairment (blind / partially sighted, including cerebral visual impairment)'],
    'Handwriting speed and legibility under time pressure': ['Specific Learning Disorder with impairment in written expression (dysgraphia)', 'Developmental Coordination Disorder (DCD / dyspraxia)'],
    'Spelling as a barrier to written output': ['Specific Learning Disorder with impairment in written expression (dysgraphia)', 'Dyslexia / Specific Learning Disorder with impairment in reading'],
    'Assistive technology not yet trialled': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'Specific Learning Disorder with impairment in written expression (dysgraphia)', 'Developmental Coordination Disorder (DCD / dyspraxia)'],
    'Instruction history': [],
    'Numeracy difficulty not meeting SLD criteria': ['Specific Learning Disorder with impairment in mathematics (dyscalculia)'],
    'Maths anxiety': ['Specific Learning Disorder with impairment in mathematics (dyscalculia)', 'Generalised Anxiety Disorder'],
    'Number sense and estimation': ['Specific Learning Disorder with impairment in mathematics (dyscalculia)'],
    'Recall of number facts vs procedural method': ['Specific Learning Disorder with impairment in mathematics (dyscalculia)'],
    'Word problems': ['Specific Learning Disorder with impairment in mathematics (dyscalculia)', 'Dyslexia / Specific Learning Disorder with impairment in reading', 'Developmental Language Disorder (DLD)'],
    'Working memory load in multi-step calculation': ['Specific Learning Disorder with impairment in mathematics (dyscalculia)', 'ADHD'],
    'Fine motor difficulty (handwriting, pencil grip)': ['Developmental Coordination Disorder (DCD / dyspraxia)', 'Specific Learning Disorder with impairment in written expression (dysgraphia)', 'Hypermobility spectrum disorder (HSD) and joint hypermobility'],
    'Gross motor difficulty (PE, balance, ball skills)': ['Developmental Coordination Disorder (DCD / dyspraxia)', 'Hypermobility spectrum disorder (HSD) and joint hypermobility'],
    'Sensory modulation difficulties (over- or under-responsive)': ['Autism', 'ADHD'],
    'Sensory discrimination difficulties': ['Developmental Coordination Disorder (DCD / dyspraxia)', 'Autism'],
    'Motor-based sensory difficulties': ['Developmental Coordination Disorder (DCD / dyspraxia)', 'Hypermobility spectrum disorder (HSD) and joint hypermobility'],
    'Presentation and care of written work': ['Specific Learning Disorder with impairment in written expression (dysgraphia)', 'Developmental Coordination Disorder (DCD / dyspraxia)'],
    'Self-care and independence skills at school': ['Developmental Coordination Disorder (DCD / dyspraxia)', 'General Learning Disability (GLD) / Intellectual Disability'],
    'Behaviour that challenges': ['Oppositional Defiant Disorder (ODD)', 'Conduct Disorder (CD)', 'Autism'],
    'Behaviour function (ABC analysis, trigger-behaviour-consequence)': [],
    'Emotion regulation in the classroom': ['Disruptive Mood Dysregulation Disorder (DMDD)', 'ADHD'],
    'Response to correction and repair after an incident': ['Oppositional Defiant Disorder (ODD)'],
    'Transitions between activities and between classes': ['Autism', 'ADHD'],
    'Behaviour system fit': [],
    'Escalation and de-escalation pattern': ['Intermittent Explosive Disorder (IED)', 'Disruptive Mood Dysregulation Disorder (DMDD)', 'Oppositional Defiant Disorder (ODD)'],
    'Behaviour as communication of an unmet learning need': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'Developmental Language Disorder (DLD)', 'General Learning Disability (GLD) / Intellectual Disability'],
    'Harmful or sexualised behaviour in children': ['Posttraumatic Stress Disorder (PTSD), including Complex PTSD', 'Conduct Disorder (CD)'],
    'Adolescent substance misuse / dual diagnosis': ['Substance use disorders'],
    'Unstructured time': ['Autism', 'ADHD'],
    'Supervision ratio and yard layout': [],
    'Group dynamics and peer influence': ['Conduct Disorder (CD)'],
    'Risk-taking without a diagnosis attached': ['ADHD', 'Conduct Disorder (CD)'],
    'Low confidence and self-esteem': ['Major Depressive Disorder', 'Persistent Depressive Disorder (dysthymia)'],
    'Learned helplessness': ['Major Depressive Disorder'],
    'Academic self-concept vs global self-esteem': [],
    'Attribution style': ['Major Depressive Disorder'],
    'Response to failure and setback': ['Generalised Anxiety Disorder', 'Major Depressive Disorder'],
    'Perfectionism and fear of getting it wrong': ['Generalised Anxiety Disorder', 'Obsessive-Compulsive Disorder', 'Anorexia Nervosa'],
    'Self-esteem as a consequence of unidentified SLD': ['Dyslexia / Specific Learning Disorder with impairment in reading', 'Specific Learning Disorder with impairment in mathematics (dyscalculia)'],
    'School anxiety presentations (not a standalone diagnosis)': ['Generalised Anxiety Disorder', 'Separation Anxiety Disorder', 'Emotionally Based School Avoidance (EBSA)'],
    'Test and exam anxiety': ['Generalised Anxiety Disorder', 'Panic Disorder and Agoraphobia'],
    'Performance anxiety in oral work': ['Social Anxiety Disorder (social phobia)', 'Selective Mutism', 'Childhood-Onset Fluency Disorder (stuttering)'],
    'Anticipatory anxiety about transitions': ['Generalised Anxiety Disorder', 'Separation Anxiety Disorder', 'Autism'],
    'Somatic complaints presenting at school (tummy aches, headaches)': ['Somatic Symptom Disorder and Functional Neurological (Conversion) Disorder', 'Generalised Anxiety Disorder', 'Emotionally Based School Avoidance (EBSA)'],
    'Anxiety secondary to an unmet learning need': ['Generalised Anxiety Disorder', 'Dyslexia / Specific Learning Disorder with impairment in reading'],
    'Rigidity and routine that is not OCD': ['Autism', 'Obsessive-Compulsive Disorder'],
    'Repeated checking of work': ['Obsessive-Compulsive Disorder', 'Generalised Anxiety Disorder'],
    'Ritual at transitions': ['Obsessive-Compulsive Disorder', 'Autism'],
    'Low mood without diagnostic threshold': ['Major Depressive Disorder', 'Persistent Depressive Disorder (dysthymia)'],
    'Loss of interest in school activities previously enjoyed': ['Major Depressive Disorder', 'Persistent Depressive Disorder (dysthymia)'],
    'Withdrawal from peers': ['Major Depressive Disorder', 'Social Anxiety Disorder (social phobia)'],
    'Irritability as the presentation of low mood in young people': ['Major Depressive Disorder', 'Persistent Depressive Disorder (dysthymia)', 'Disruptive Mood Dysregulation Disorder (DMDD)'],
    'Complex or developmental trauma': ['Posttraumatic Stress Disorder (PTSD), including Complex PTSD', 'Reactive Attachment Disorder (RAD)', 'Disinhibited Social Engagement Disorder (DSED)'],
    'Adverse Childhood Experiences (ACEs)': ['Posttraumatic Stress Disorder (PTSD), including Complex PTSD'],
    'Bereavement reaction': ['Prolonged Grief Disorder', 'Adjustment Disorder'],
    'Displacement, asylum and resettlement': ['Posttraumatic Stress Disorder (PTSD), including Complex PTSD', 'English as an Additional Language and bilingual development (DLD vs EAL)', 'Adjustment Disorder'],
    'Trauma-informed classroom practice': [],
    'Emotionally Based School Avoidance (school refusal)': ['Emotionally Based School Avoidance (EBSA)', 'Separation Anxiety Disorder', 'Generalised Anxiety Disorder'],
    'Truancy distinguished from EBSA': ['Emotionally Based School Avoidance (EBSA)', 'Conduct Disorder (CD)'],
    'Parentally condoned absence': [],
    'Absence due to chronic illness': [],
    'Late arrival and partial attendance': ['Emotionally Based School Avoidance (EBSA)'],
    'Return-to-school planning after extended absence': ['Emotionally Based School Avoidance (EBSA)'],
    'Pathological Demand Avoidance (PDA) profile': ['Autism', 'Oppositional Defiant Disorder (ODD)'],
    'Peer relationship difficulties and social isolation': ['Autism', 'Social Anxiety Disorder (social phobia)'],
    'Bullying': [],
    'Social adaptive skills': ['General Learning Disability (GLD) / Intellectual Disability', 'Autism'],
    'Co-operation with peers in group work': ['Autism', 'ADHD'],
    'Turn-taking and shared play': ['ADHD', 'Autism'],
    'Reading social cues and repair after conflict': ['Autism', 'Social (Pragmatic) Communication Disorder'],
    'Masking and the cost of it': ['Autism'],
    'Loneliness without observable difficulty': ['Major Depressive Disorder', 'Social Anxiety Disorder (social phobia)'],
    'Self-advocacy': [],
    'LGBTQ+ identity support': ['Gender dysphoria in children and adolescents'],
    'Cultural and linguistic identity': ['English as an Additional Language and bilingual development (DLD vs EAL)'],
    'Attitude towards staff': ['Oppositional Defiant Disorder (ODD)', 'Reactive Attachment Disorder (RAD)'],
    'Trust and the effect of one key adult': ['Reactive Attachment Disorder (RAD)', 'Posttraumatic Stress Disorder (PTSD), including Complex PTSD'],
    'Response to authority and to being corrected': ['Oppositional Defiant Disorder (ODD)', 'Conduct Disorder (CD)'],
    'Relationship with the SNA and dependence on adult proximity': [],
    'Help-seeking from adults': [],
    'Uncorrected refractive error': ['Visual impairment (blind / partially sighted, including cerebral visual impairment)'],
    'Visual fatigue in extended reading': ['Visual impairment (blind / partially sighted, including cerebral visual impairment)', 'Dyslexia / Specific Learning Disorder with impairment in reading'],
    'Access to print': ['Visual impairment (blind / partially sighted, including cerebral visual impairment)'],
    'Listening in noise vs listening one-to-one': ['Hearing impairment (Deaf / hard of hearing)', 'Recurrent otitis media with effusion (glue ear)'],
    'Classroom acoustics and seating': ['Hearing impairment (Deaf / hard of hearing)'],
    'Hearing history during the years phonics was taught': ['Recurrent otitis media with effusion (glue ear)', 'Hearing impairment (Deaf / hard of hearing)', 'Dyslexia / Specific Learning Disorder with impairment in reading'],
    'Physical disability (non-cerebral palsy)': ['Spina bifida (including associated hydrocephalus)', 'Muscular dystrophy'],
    'Multiple disabilities': ['Genetic syndromes (Down, Fragile X, 22q11.2, Williams, Prader-Willi, Angelman, Rett)', 'Cerebral palsy (spastic / dyskinetic / ataxic / mixed)'],
    'Chronic illness affecting school': ['Epilepsy (and its educational impact)'],
    'Fatigue and stamina needs': ['Epilepsy (and its educational impact)', 'Muscular dystrophy', 'Hypermobility spectrum disorder (HSD) and joint hypermobility'],
    'Medication effects on attention and learning': ['Epilepsy (and its educational impact)', 'ADHD'],
    'Missed curriculum from hospital admissions': [],
    'Re-entry to school after illness': ['Acquired brain injury'],
    'Parent-infant mental health / 0–3 attachment work': ['Reactive Attachment Disorder (RAD)', 'Disinhibited Social Engagement Disorder (DSED)'],
    'Early Intervention Team caseload (0–6, pre-diagnostic)': ['Global Developmental Delay (GDD)', 'Autism'],
    'Delayed developmental milestones': ['Global Developmental Delay (GDD)', 'General Learning Disability (GLD) / Intellectual Disability'],
    'AIM level and preschool support already in place': [],
    'Transition from preschool to primary': [],
    'Care-experienced children (foster, kinship, residential, aftercare)': ['Relational problems and children in care (upbringing away from parents)', 'Reactive Attachment Disorder (RAD)', 'Disinhibited Social Engagement Disorder (DSED)'],
    'Child protection and welfare concerns': ['Posttraumatic Stress Disorder (PTSD), including Complex PTSD'],
    'Domestic violence exposure': ['Posttraumatic Stress Disorder (PTSD), including Complex PTSD'],
    'Parenting capacity concerns': ['Relational problems and children in care (upbringing away from parents)'],
    'Family functioning difficulties': ['Relational problems and children in care (upbringing away from parents)'],
    'Housing and economic problems': [],
    'Social exclusion, discrimination, acculturation difficulty': ['Adjustment Disorder'],
    'Knowing which service does what, and the referral route': [],
    'Multi-disciplinary meetings and your role in them': [],
    'Professional and service boundaries': [],
    'Classroom environment': [],
    'Teaching match': [],
    'Curriculum demands': [],
    'Attendance and transitions': [],
    'Transition planning (early years to primary, primary to post-primary, school leaver)': [],
    'Assistive technology': [],
    'Reasonable Accommodations in State Examinations (RACE)': [],
    'SNA and resource teaching allocation': [],
    'Home learning environment': [],
    'Community context': [],
    'Continuum of Support level and whether it was actually implemented': [],
    'Whole-school policy and practice': [],
    'Staff training need identified through casework': [],
}
