"""More worked examples of reflective writing: fictional trainee, fictional cases.

Companion to worked_examples.py. Same rules: every example is about "Trainee A", a
fictional trainee on a fictional 2025-2026 placement in generic settings. These are
worked examples, not reflections to submit. The value is in the annotation: what the
strong version does that the weak one does not.
"""

STAMP = "WORKED EXAMPLE · fictional trainee (Trainee A) and fictional case · NOT FOR SUBMISSION. Read for the moves, then write your own from your Log"

EXAMPLES = [

# ── WEEKLY REFLECTIONS · 14 more, spread across the eight focus areas ─────────────────

{"type": "Weekly reflection", "focus": "What I would do differently, specifically",
 "competency": "5. Working with Others · CORU SoP 2.1",
 "title": "Four suggestions in the first ten minutes",
 "weak": "I had a consultation with a teacher this week about a child who is struggling. It went okay but I think I talked too much. Next time I will listen more.",
 "strong": "On 21/10/2025 I met a fourth-class teacher in a rural primary school about a girl who 'shuts down' during group work. I had prepared by reading the Student Support File and arrived with ideas. Reading my notes back that evening, I saw that I had offered four strategies before the teacher had finished describing a single incident, and she had answered each with 'I've tried that'. By the end she was polite and I had learned almost nothing new about the child. If I did it again I would ask her to walk me through one specific lesson from the previous week: who was in the group, what the task was, and what happened just before the girl stopped. I would offer nothing until I could summarise that lesson back to her and she agreed with my summary. Wagner (2000) describes consultation as joint problem-solving; what I did was closer to delivering advice. I have written three opening questions on an index card that sits on top of my notebook, and at my next consultation on 28/10/2025 I asked my supervisor to count how many suggestions I made before the fifteen-minute mark. It was one.",
 "why": "The failure is concrete (four suggestions, 'I've tried that') and seen from the teacher's side. The alternative is a specific sequence, not an intention. Theory is attributed and used to name the gap. The change is tested at a second dated consultation, with someone else counting.",
 "changed": "'Listen more' cannot be checked. The strong version turns it into a question to open with, a rule about when to suggest, and a count."},

{"type": "Weekly reflection", "focus": "Feedback I received and what I did about it",
 "competency": "1. Assessment · CORU SoP 5.2",
 "title": "Seven questions that answered themselves",
 "weak": "My supervisor watched me interview a pupil this week and said some of my questions were leading. I will try to ask more open questions in future.",
 "strong": "On 04/11/2025 my supervisor sat in while I interviewed a ten-year-old boy about lunchtime, which his teacher had flagged as the worst part of his day. Afterwards she showed me her tally: seven of my questions had contained their own answer ('Is it hard when the others don't let you play?') and he had agreed with every one. My first reaction was embarrassment, then a flicker of defensiveness, because he had seemed so relaxed. When I reread my notes I saw that almost every 'finding' was a sentence I had said and he had nodded to. I could not use them as his view. I rewrote the interview plan so that each topic opened with an open prompt ('Tell me about yesterday's lunchtime') and a follow-up that reused only his own words. I also added a 'best day to worst day' line he could place things on, so he could answer without matching my phrasing. At the second session on 11/11/2025 he placed the yard in the middle, not at the bottom, and said the hard part was lining up afterwards, when everyone was shouting. That is now the focus of the recommendation. I now draft interview questions in advance and cross out any that contain a feeling word the child has not used first.",
 "why": "The feedback is specific (a tally, a quoted question) and the reaction to it is honest. The trainee works out what the feedback means for the evidence: the first interview is unusable as the child's view. The revised method produces a different finding, which changes the recommendation.",
 "changed": "'More open questions' is a resolution. The strong version shows the cost of the leading questions, the redesign, and a result that proves the redesign mattered."},

{"type": "Weekly reflection", "focus": "Where my own assumptions shaped what I looked for (CORU 5.44)",
 "competency": "1. Assessment · CORU SoP 5.44",
 "title": "The boy by the wall",
 "weak": "I did a yard observation this week and at first I thought the child was isolated, but then I saw he was playing. I learned not to jump to conclusions.",
 "strong": "On 18/11/2025 I observed a seven-year-old in the yard of a large urban primary school, referred for 'difficulty with peers, possibly isolating himself'. For the first ten minutes I recorded him as alone: standing by the wall, not joining the football. I had already written 'solitary' in my notes when a girl ran over, tagged him, and he sprinted off laughing. He was in a game of chasing that ranged across the whole yard, and the wall was 'home'. I had come in with the teacher's word 'isolating' and read everything through it, watching for absence of contact rather than for what he was doing. I had also stood where I could see the football pitch best, because that was where I expected the social action to be. I went back on 20/11/2025, walked the yard first to see where the different games happened, and kept a simple interval record of who he was near and what they were doing. The picture was of a boy with two consistent playmates whose difficulty came at the bell, when games ended abruptly and he had to line up. Before a yard observation I now spend five minutes mapping the space, and I write the referrer's word at the top of the page so that I can check I am not simply looking for it.",
 "why": "The assumption is traced to two concrete sources: the referrer's word and where the trainee chose to stand. Both are correctable. A second observation with a changed method produces a different, more useful picture.",
 "changed": "'Not jump to conclusions' is advice to everyone. The strong version shows exactly how this conclusion was reached and the two habits that now guard against it."},

{"type": "Weekly reflection", "focus": "Where my own assumptions shaped what I looked for (CORU 5.44)",
 "competency": "5. Working with Others · CORU SoP 5.44",
 "title": "The adult who saw every transition",
 "weak": "This week I worked with an SNA, who gave me useful information about a child. I realised SNAs have a lot of knowledge and I will involve them more.",
 "strong": "In a small rural school I was working on a referral about a nine-year-old girl's afternoon meltdowns. For two weeks I had gathered information from the class teacher, the special education teacher and the parents. On 02/12/2025 the SNA who supports the girl stopped me at the classroom door and said quietly, 'It's always after she's been taken out for resource.' I had not asked her anything. Without ever putting it into words, I had assumed that the SNA's role was care needs and that the educational picture belonged to teachers. That assumption left out the one adult who was with the girl for every transition in her day. I asked the principal whether I could meet the SNA properly, and on 04/12/2025 we spent twenty minutes going through the timetable together. She could name which afternoons had gone badly and what had come before each one. When I checked her pattern against the teacher's incident notes, it held. The formulation shifted from 'afternoons' in general to the return from withdrawal, and the recommendation changed with it. At the start of each case I now list every adult who sees the child across a day before I decide whom to consult, and I ask the principal whether the SNA can be included.",
 "why": "Names an assumption the trainee had never said out loud and shows its cost: the key informant was missed. The SNA's account is checked against another source rather than simply adopted. The change is a routine at the start of every case.",
 "changed": "'Involve them more' is goodwill. The strong version shows why the SNA was left out, what her information did to the formulation, and a procedure that stops it happening again."},

{"type": "Weekly reflection", "focus": "A decision I made and the reasoning behind it",
 "competency": "1. Assessment · CORU SoP 3.5",
 "title": "Observing outside the special class",
 "weak": "I observed a pupil in a special class and in mainstream this week. I decided this was the best approach and it gave me a fuller picture.",
 "strong": "On 09/12/2025 I began work with a ten-year-old boy in an autism special class in a suburban primary school, referred because of increasing distress during the school day. The class teacher suggested I observe in the special class, where she could show me his visual schedule and work system. I decided instead to split my observation between the special class and the two mainstream sessions he joins each week, music and PE, because the class log showed his distress clustering on Tuesdays and Thursdays. I was aware this might read as second-guessing a very experienced teacher, so I explained my reasoning to her using her own log rather than my hypothesis, and she agreed. In the special class he was settled and used his schedule on his own. In the mainstream music lesson there was no schedule, the room was loud, and the return to his class meant crossing a busy corridor at break. The teacher had never seen these sessions, because she was teaching the rest of her class at the time. The decision meant the recommendations could focus on making the mainstream sessions predictable, with a portable schedule and a quieter return route, rather than adjusting a special-class routine that was working. I now check the child's full timetable, including inclusion sessions, before deciding where to observe.",
 "why": "The decision is set against a reasonable alternative and justified from data (the log). The trainee handles the relationship risk explicitly. The result shows what the other choice would have missed.",
 "changed": "The weak version asserts the decision was best. The strong version shows the evidence that drove it, how it was negotiated, and what it found."},

{"type": "Weekly reflection", "focus": "Something I did not know I did not know",
 "competency": "5. Working with Others",
 "title": "Eleven teachers and no single view",
 "weak": "I visited a post-primary school for the first time this week. It is very different from primary and there are lots of people involved. I learned a lot.",
 "strong": "My first post-primary visit, to a DEIS school on 13/01/2026, was about a second-year boy whose attendance had dropped. I had arranged to 'speak to his teacher', and only on arrival did I understand that he had eleven teachers, a class tutor, a year head, a guidance counsellor and an SEN coordinator, each holding a different part of the picture. Nobody had a complete view, and the year head assumed I would put it together. I had not known that the structure itself was information. In primary I had always started with the class teacher and had not realised how much that single relationship was doing for me. I asked the SEN coordinator for his timetable and a list of who taught him what, and sent a three-question note to each subject teacher: what he does well in your class, what you have noticed since October, and what you have tried. Seven replied within the week. Their replies showed that the absences were concentrated on two days with a double practical subject in a room he disliked, which no single adult had seen. For post-primary referrals I now ask for the timetable and the pastoral structure before the first meeting, and plan how I will gather information around them.",
 "why": "The gap is one the trainee could not have named in advance: that primary structures had been doing hidden work. The response is a method (timetable, short structured note) rather than more meetings, and it produces a finding nobody had.",
 "changed": "'Very different' and 'learned a lot' are true of every first visit. The strong version names the specific thing that was unknown and the procedure that now covers it."},

{"type": "Weekly reflection", "focus": "Something I avoided asking, and why",
 "competency": "7. Supervision · CORU SoP 5.44",
 "title": "What 'typical' looks like at three",
 "weak": "I visited a preschool this week. I didn't have much experience with early years, so I found it a bit challenging. I should have asked for more support.",
 "strong": "On 27/01/2026 I visited a community preschool about a three-year-old whose keyworker was worried about his language and play. Most of my work so far has been with school-age children, and on the drive there I realised I did not have a clear sense of what ordinary play looks like at three years and two months. I had not asked my supervisor beforehand, because early years is listed on my placement plan as something I 'covered' in college, and I did not want to show that it had not stuck. During the visit I was unsure whether his lining up of toy cars was unusual. I wrote it down with a question mark and said nothing about it to the keyworker. That was the right thing to do, but only because I had nothing to say. At supervision on 30/01/2026 I finally asked. My supervisor suggested I reread the developmental material from college before writing anything, and that I talk to the preschool staff about what they see across their group, since they watch many three-year-olds every year. The second suggestion embarrassed me: the expertise had been in the room with me. Before any visit to an age group I am less familiar with, I now write down one thing I am not sure is typical and ask it, of my supervisor or the setting, before I go.",
 "why": "The avoided question is named, with an honest reason (a plan that said the topic was 'covered'). The consequence is shown: silence in the setting that looked like caution but was not. The supervisor's second suggestion reframes where expertise sits.",
 "changed": "'Should have asked for more support' is vague. The strong version names what should have been asked, why it was not, and a habit that happens before each visit."},

{"type": "Weekly reflection", "focus": "Something I avoided asking, and why",
 "competency": "5. Working with Others · CORU SoP 5.44",
 "title": "The term I nodded along to",
 "weak": "I attended a team meeting this week. There were a lot of professionals there and I found it intimidating. I will try to contribute more at the next one.",
 "strong": "At a multi-agency meeting on 10/02/2026 about a pupil moving to post-primary, the speech and language therapist and a social worker used a name for a service pathway that I did not recognise. Everyone else nodded, and so did I. For the next forty minutes I followed a discussion built around that term without knowing what it committed the family to, and when the chair asked whether psychology had anything to add I said something general about transition planning. I avoided the question because I was the most junior person at the table, I was there as a trainee, and I assumed that asking would slow the meeting and mark me out. Walking to the car afterwards, I asked the social worker. It took her thirty seconds to explain, and the answer changed what I would have said: the pathway had a waiting period that overlapped with the pupil's first term, which was exactly the gap the school needed to plan for. I emailed the chair the next morning with that point, and it was added to the minutes. I now keep a column headed 'don't know' in my notes at every meeting and ask at the first natural pause. More than once since, someone else at the table has wanted the answer too.",
 "why": "The avoidance is specific (one unrecognised term) and its cost is concrete (a generic contribution when a specific one was needed). The trainee repairs the gap the next day. The change is small and repeatable.",
 "changed": "'Contribute more' treats the problem as confidence. The strong version shows that the problem was a question not asked, and what asking it would have added."},

{"type": "Weekly reflection", "focus": "A decision I made and the reasoning behind it",
 "competency": "6. Ethical Practice · CORU SoP 3.5",
 "title": "Late, and on purpose",
 "weak": "I had a report deadline this week and I asked for an extension because I needed more information. My supervisor agreed. I need to manage my time better.",
 "strong": "The report on a nine-year-old with literacy difficulties was due to the school on 24/02/2026, ahead of their planning meeting for the following year. By 20/02/2026 I had a complete draft, but the parent's rating scales had come back that morning and did not agree with the teacher's on attention at home. I had two options: send the report on time with the discrepancy in a footnote, or ask for a week to phone the parent and understand it. The pull to send was strong. I had promised the date, and I did not want to be the trainee who was late. I set out the choice for my supervisor in terms of what each option meant for the pupil: the planning meeting would work from the report's recommendations, and a footnote would be easy to miss. We agreed that I would send the school, on time, a one-page summary of the recommendations that did not depend on the discrepancy, and the full report a week later. I phoned the parent on 23/02/2026. The difference turned out to be about homework time specifically, which changed one recommendation. The school accepted the split without difficulty. When I set a report date now, I also set a date three days earlier for all information to be in, and I tell the school at the start what they will receive if it is not.",
 "why": "Two options are weighed against the pupil's interest rather than the trainee's image. The pull towards the easier option is named. The chosen route meets the school's need and the need for accuracy. The prevention is specific.",
 "changed": "'Manage my time better' misdiagnoses the problem. The strong version shows it was a judgement about evidence, and how the deadline was honoured in part."},

{"type": "Weekly reflection", "focus": "A moment I was uncertain and what I did with it",
 "competency": "6. Ethical Practice · Children First Act 2015",
 "title": "What I felt after I made the report",
 "weak": "I had a child protection concern this week. I told the DLP and my supervisor and it was dealt with. It was upsetting but I handled it professionally.",
 "strong": "During a session on 03/03/2026 a pupil said something that, once I had written it down in her own words, I recognised as meeting the threshold for a report. I will not describe it here; this reflection is about me. I told the school's Designated Liaison Person, as the school's procedure requires, and for a moment I felt relief, as if that had settled it. That moment of relief is the uncertainty I want to record. Then I remembered what our college session had made clear: as a mandated person under Children First, my duty is to report to Tusla myself, as soon as practicable, and telling the DLP does not discharge it. I submitted the report that afternoon following the service's procedure and recorded the time. Supervision on 05/03/2026 came after the report, not before it, and it was about my reaction. I had slept badly, I kept rereading my notes to check I had written her words and not mine, and I was anxious about seeing the pupil again. My supervisor helped me separate the part that was my responsibility, which was done, from the parts that belonged to Tusla and the school. I now keep the Children First procedure and the Tusla reporting route where I can reach them in two clicks, and I book a short check-in after any report rather than waiting for the scheduled session.",
 "why": "Keeps case details out entirely and reflects on the trainee's own reaction. Names the moment of false relief and corrects it: the report goes to Tusla as soon as practicable, and telling the DLP does not discharge a mandated person's duty. Supervision follows the action and is used for the trainee's response. Check your own mandated-person status and your service's procedure with your supervisor; this example assumes Trainee A is a mandated person.",
 "changed": "The weak version implies that telling the DLP was enough and calls the handling professional. The strong version shows the correct sequence, the feeling that nearly shortened it, and the support used afterwards."},

{"type": "Weekly reflection", "focus": "What I would do differently, specifically",
 "competency": "5. Working with Others · CORU SoP 2.1",
 "title": "Looking at the speakerphone",
 "weak": "I had a meeting with a parent through an interpreter this week. It was harder than I expected. Next time I will be better prepared.",
 "strong": "On 17/03/2026 I held a feedback meeting with a mother whose first language is Arabic, through a telephone interpreter arranged by the service. I had not spoken to the interpreter beforehand. Three things went wrong. I spoke in long paragraphs, so the interpretations came back shorter than what I had said and I could not tell what had been left out. I used the phrase 'working memory' twice without considering whether it had a direct equivalent. And by the second half I was looking at the speakerphone rather than at the mother, who was sitting across the table from me. At the end she thanked me warmly, and I had no idea what she had understood. If I did it again I would book ten minutes with the interpreter beforehand to go through the key terms and agree to speak in short sections. I would replace technical terms with descriptions of what her son does in class. I would keep my eyes on the mother and speak to her directly as 'you'. And I would close by asking her, through the interpreter, what she would tell her husband about the meeting. I have added an interpreter briefing to my feedback plan template, and a follow-up with the same interpreter is booked for 31/03/2026.",
 "why": "Three specific failures, each observable. Each maps onto a specific change. The closing check replaces the warm thanks, which told the trainee nothing, with evidence of understanding. A follow-up is in place.",
 "changed": "'Better prepared' could mean anything. The strong version is a four-step plan that someone else could follow."},

{"type": "Weekly reflection", "focus": "A moment I was uncertain and what I did with it",
 "competency": "5. Working with Others",
 "title": "Between the principal and the father",
 "weak": "There was a disagreement between a parent and the school at a meeting this week. I stayed neutral and tried to help everyone come to an agreement.",
 "strong": "At a review meeting on 24/03/2026 in a town primary school, the father of an eight-year-old said his son was 'fine at home' and that the school's concerns about aggression came from a teacher who did not like him. The principal, visibly annoyed, listed incidents by date. Then both of them looked at me. I was genuinely unsure. In two observations I had seen neither the child the school described nor the one the father described, but something in between, and I felt pressure to side with one of them because each expected me to confirm their view. What I did was say that I had seen something different from both accounts, and describe one incident from my observation: a push in the lunch queue immediately after he was bumped from behind. I asked each of them what they thought had happened there. The father said his son hates being touched unexpectedly; the principal said that fitted two of the incidents on her list. That did not end the disagreement, but it gave us one situation everyone could look at together. At supervision on 26/03/2026 my supervisor pointed out that I had never named the tension in the room, which may have left the father feeling outnumbered. Before review meetings I now plan for disagreement: I bring one concrete observation both parties can examine, and I name the difference in views early rather than hoping it won't come up.",
 "why": "The uncertainty is real and explained (the evidence fitted neither account). The move made is specific: a shared concrete incident. Supervision adds something the trainee missed. The change is a way of preparing, not a promise to stay neutral.",
 "changed": "'Stayed neutral' hides what was actually done. The strong version shows the move, what it achieved, what it did not, and what was learned from feedback."},

{"type": "Weekly reflection", "focus": "Feedback I received and what I did about it",
 "competency": "2. Formulation · CORU SoP 3.5",
 "title": "'Who, and when?'",
 "weak": "A teacher gave me feedback on my draft recommendations this week. She said they weren't realistic, so I changed them. I learned that recommendations need to be practical.",
 "strong": "On 14/04/2026 I shared my draft recommendations for a fourth-class pupil with the special education teacher before finalising the report, as my supervisor had suggested. She returned them the next day with one comment beside my third recommendation, 'daily one-to-one fluency practice for ten minutes': 'Who, and when? I have him twice a week in a group of five.' I felt stung. I thought the recommendation was well supported, and my first impulse was to write back explaining the reasoning. When I looked again, I saw that I had written what the pupil needed without asking what the school could deliver. A recommendation that cannot happen is not a recommendation. I phoned her on 16/04/2026 and we worked it through: the fluency practice could be paired reading with a trained sixth-class pupil during a reading slot already in the class timetable, with the special education teacher checking in weekly. That version is in the final report, with the person, the time and the review date named. I now write each recommendation in four parts (what, who, when, and how we will know) and share drafts with the person who will carry them out before the report is signed off.",
 "why": "The feedback comes from the person who has to act on it, not the supervisor. The trainee's first reaction is recorded, then set aside. The revised recommendation is concrete and negotiated. The change is a template for every recommendation.",
 "changed": "'Recommendations need to be practical' is a lesson anyone could write. The strong version shows what 'practical' meant in this school and how it is now built into the writing."},

{"type": "Weekly reflection", "focus": "My own response to the work — energy, pace, what it cost (CORU 5.45)",
 "competency": "6. Ethical Practice · CORU SoP 5.45",
 "title": "A flat week with no obvious reason",
 "weak": "I had low energy this week and found it hard to get motivated. I think I need a break. I will try to rest over the weekend.",
 "strong": "The week of 27/04/2026 was not especially busy, with two school visits and one report, but I felt flat from Monday. I noticed it first as avoidance: I left the report draft open and answered emails instead, and I put off phoning a parent I knew would be upset. On Wednesday, during a cognitive assessment, I realised I had given the instructions for a subtest in a monotone and the eleven-year-old had matched my energy. I could not be sure that her effort on that subtest reflected her ability, and I noted this on the record form. That was the point at which my tiredness stopped being private. I did not want to raise it at supervision because nothing had happened to explain it, and it felt like complaining without a reason. I raised it anyway on 01/05/2026, describing the three things I had noticed rather than the feeling. My supervisor asked what the previous month had involved, and when I listed it (a child-protection report, a difficult review meeting and three feedback meetings) the flatness had an obvious cause. We agreed I would book assessments for mornings for the next fortnight and make the difficult phone call with her in the room. I now keep a line in my weekly record for emotionally heavy contacts, not only hours, so I can see the load building before it shows in my practice.",
 "why": "Low energy is shown through its effects on practice, including one that could affect a child's results, which is recorded. The reluctance to raise it is honest. The cause is found by listing, not guessing. The prevention tracks emotional load, not just hours.",
 "changed": "'Rest over the weekend' treats a work problem as a personal one. The strong version links the state to practice, raises it with evidence, and changes what is tracked."},

# ── CASE-LEVEL REFLECTIONS · 8 more, across referral types ────────────────────────────

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "5. Working with Others",
 "title": "A DLD referral: making someone else's findings usable",
 "weak": "This case was about a child with DLD. I learned a lot about language difficulties and worked well with the speech and language therapist.",
 "strong": "In my earlier cases I was the first professional involved. In this case, a senior infants boy referred for 'not listening', the family already had a speech and language therapy report identifying Developmental Language Disorder, and the school had filed it without reading past the first page. What was new was that my job was not to find out what was wrong but to make someone else's findings usable. I read the therapy report twice, looked up the terminology the therapist had used, which follows the CATALISE consensus (Bishop et al., 2017), and phoned her on 06/11/2025 to ask which of her recommendations mattered most in a classroom. She named two: shorter spoken instructions, and pre-teaching topic vocabulary. I observed him in a PE lesson and saw exactly what she had described: a four-part instruction, and the boy copying the girl beside him. My report was shorter than any I had written and cross-referenced her findings rather than repeating an assessment. What this case taught me that the previous ones did not: sometimes the most useful thing I can do is translate between professionals, and a new assessment would only have delayed help the child already had grounds for.",
 "why": "Names what was new (arriving second, not first) and how it changed the role. Theory is attributed and used to read another profession's report. The observation confirms the therapist's account rather than replacing it.",
 "changed": "The weak version reports a topic. The strong version names a change in how the trainee understands their role on a case."},

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "2. Formulation · 5. Working with Others",
 "title": "An autism referral: the question behind the question",
 "weak": "This was my first autism referral. I did observations and spoke to the parent. The family were happy with the report and I learned about autism.",
 "strong": "Earlier referrals asked me questions the service could answer. This one, from a rural primary school about a seven-year-old girl, asked 'is she autistic?', and in this service a diagnostic assessment of autism is carried out by a multidisciplinary team, not by me. My first instinct was to decline the question and move on. At supervision on 25/11/2025 my supervisor pointed out that the question behind it was what the school should do while the family waited, possibly for a long time. I rewrote the referral question with the teacher: what helps her manage the unstructured parts of the day, and what should the school record that a future assessment team would find useful? I observed at lunch and during a group task, and asked the mother what she had noticed at home. Her account of her daughter rehearsing conversations alone in her bedroom told me more than either observation. The report described needs and strategies without a diagnostic label, and included a summary the family could bring to their GP. What was new: separating the question a school asks from the one I can answer, and making my work useful to the next professional in line rather than trying to be that professional.",
 "why": "Identifies a new kind of referral problem: a question outside the trainee's remit. Shows it being reframed with the teacher, not simply refused. The parent's account is treated as strong evidence. The learning is stated as a contrast with earlier cases.",
 "changed": "'I learned about autism' is about a topic. The strong version is about scope, reframing and handover, which are transferable."},

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "2. Formulation",
 "title": "An EBSA referral: the child who wasn't in the building",
 "weak": "This case was about a child who wasn't attending school. It was challenging, but we made a plan to get him back to school and it is going well.",
 "strong": "Every case before this one began with a school visit. This one, a nine-year-old who had attended on four days since the October break, could not start there, because he was not in school. I met him at home on 15/01/2026 with his mother's agreement, and at first I treated the meeting as a way to get him back to the building. The school wanted a return date. What changed my approach was using Kearney and Silverman's (1990) functional model as a set of questions rather than a category: what did staying at home give him, and what did school cost him? His answers pointed to something specific, the first ten minutes of the morning when the class did a spoken news round, not to school as a whole. The absence was the visible part; the demand he was avoiding was much narrower. The plan the family, the school and I agreed on 22/01/2026 began with arrival after news round for two weeks, with a named adult at the gate, and set review points rather than a return date. What this case taught me that the previous ones did not: when the child is not in the setting, the family becomes the main partner, and the first job is to find what the avoidance protects the child from before anyone plans a return.",
 "why": "The newness is structural (no school setting to start from) and conceptual (absence as the visible part of something narrower). Theory is attributed and used as questions. The plan follows directly from the formulation.",
 "changed": "The weak version reports an outcome. The strong version shows the reasoning that produced the plan and what it changed in the trainee's approach."},

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "1. Assessment",
 "title": "A maths referral: looking for the error, not the level",
 "weak": "This was a maths referral, which was different from my literacy cases. I gave the teacher some strategies for maths and she found them helpful.",
 "strong": "My earlier cases were all literacy referrals, where I had a clear sequence to follow. For this fifth-class pupil, referred for 'weak maths', I had no sequence, and I noticed I was about to reach for a standardised test simply because I had one. The school's standardised results already showed he was behind his peers; they did not show why. Instead, on 03/02/2026, I sat with him and a set of problems from his own copybook and asked him to talk me through each one, an approach drawn from Ginsburg's (1997) account of the clinical interview. He recalled number facts quickly, but when a problem was written in words he added whatever numbers he saw. He had no picture of what the problem was about. When I asked him to draw the story first, he solved most of them. That moved the recommendation from more fact practice, which his teacher had already been doing, to teaching him to represent word problems before calculating. What was new: in maths I had to find the error pattern, not just the level, and the child's own working was the richest evidence for it. I now ask for the child's copybook before choosing an assessment for any curricular referral.",
 "why": "Contrasts the new referral with the trainee's familiar sequence and names the pull towards a test. The method is attributed and fits the question. The finding redirects an intervention that was already failing.",
 "changed": "The weak version could describe any maths case. The strong one names a specific error pattern and a lasting change in how assessments are chosen."},

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "6. Ethical Practice",
 "title": "A child in care: gaps belong in the report",
 "weak": "This case involved a child in foster care. There were a lot of people involved and it took a long time. I learned about the importance of working with other agencies.",
 "strong": "In every earlier case, the person who signed the consent form was also the person who knew the child best. For this eight-year-old girl in foster care, those were different people. Her foster carer knew her daily life; her Tusla social worker could tell me what consent was needed and from whom; and her early history was partly in a file and partly unknown. I had to confirm with my supervisor and the social worker who could consent before I did anything, which took until 24/02/2026, longer than any case so far, and I felt the delay was letting the school down. The second new thing was the history. I had always asked parents a standard set of questions. Here several had no answer, and asking the foster carer to guess would have filled the report with speculation. I wrote 'not known' where it was not known and said in the report what that meant for interpretation. I also chose not to ask the girl about her family and let her lead our conversation, which went to her dog and her new bedroom. What this case taught me that the previous ones did not: the process of who consents, who knows what, and what I should not ask is part of the assessment, and gaps in the history belong in the report, not behind a smooth narrative.",
 "why": "Names two things that were new: consent and the history were split across people. Shows an honest reaction to the delay. Makes a principled decision about unknowns and about what not to ask the child.",
 "changed": "'Working with other agencies' is a generic lesson. The strong version shows specific decisions about consent, missing information and the child's own boundaries."},

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "1. Assessment · 6. Ethical Practice",
 "title": "A Deaf pupil: non-verbal is not the same as fair",
 "weak": "I assessed a Deaf child this week using an interpreter. It was a new experience and I learned about Deaf culture and the importance of adapting assessments.",
 "strong": "My earlier assessments all assumed that the child and I shared a language. This eleven-year-old boy, who is Deaf and whose first language is Irish Sign Language, was referred for slow progress in reading. I do not sign. My first plan was to use the non-verbal parts of a cognitive battery and treat those as a fair measure. On 10/03/2026 the Visiting Teacher for Deaf and hard of hearing children asked me whether those tests had been standardised with Deaf children who sign. I could not say that they had, and I could not find evidence that they were. That changed the case. I worked with a qualified ISL interpreter the school arranged, and with the Visiting Teacher, who had known him for five years. The report gave no standard scores for cognitive ability and said why. It focused instead on how reading was being taught: he was being taught phonics that depended on hearing speech sounds, with an improvised signed version that nobody had planned. What this case taught me that the previous one did not: a test being non-verbal does not make it fair, and when my tools do not fit the child, the honest report says so and treats the people who know the child's language as the main evidence.",
 "why": "A specific assumption is challenged by a named colleague, and the trainee checks it rather than defending it. Omitting the scores is a principled decision, explained in the report. The focus moves to teaching, where change is possible.",
 "changed": "'Adapting assessments' sounds right but hides the question of validity. The strong version shows the trainee deciding not to report a number and why."},

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "6. Ethical Practice",
 "title": "A post-primary anxiety referral: negotiating what is shared",
 "weak": "This was an anxiety referral for a teenager. She opened up to me and I built good rapport. I made recommendations to help her with exam stress.",
 "strong": "In earlier cases the parents were the people I reported to, and the child's view was one source among several. This case, a sixteen-year-old in fifth year at a DEIS post-primary, referred by her guidance counsellor for anxiety before exams, reversed that. At our first meeting on 17/03/2026 she asked who would see what she told me. No child had asked me that directly before, and I had no ready answer. I explained what would go into the report, what would be shared with the school, and the child-protection limit, and said I would check anything I was unsure about with my supervisor before it went anywhere. She told me the anxiety was mostly about a part-time job and money at home, not the exams the school had focused on, and that she did not want her parents to hear the part about money. At supervision on 19/03/2026 we worked through what the school needed to know in order to help, and it was less than I had assumed: a recommendation about a lighter homework load on the evenings she worked did not need the reason. She read the draft recommendations before they were finalised and changed one word. What this case taught me that the previous ones did not: with an older adolescent, negotiating what is shared is part of the work, and a report can serve her without disclosing everything she said.",
 "why": "Differs clearly from earlier anxiety work: the new learning is about confidentiality and the young person's role, not the anxiety. Limits are stated honestly, including child protection. Supervision is used to decide what the report needs. The young person reviews her own recommendations.",
 "changed": "'Built good rapport' is not evidence. The strong version shows the specific negotiation and how it shaped a report that still worked for the school."},

{"type": "Case-level reflection", "focus": "What this case taught me that the previous one did not",
 "competency": "1. Assessment",
 "title": "A special-class pupil with GLD: what the next setting needs to know",
 "weak": "This case was about a pupil in a special class who is moving to secondary school. I did an assessment and wrote a report to support the transition.",
 "strong": "All my earlier cases were about finding out: is there a difficulty, and what is it? This twelve-year-old boy, in a special class for pupils with mild general learning disability, already had an established profile. The referral, received on 21/04/2026, was about his move to post-primary in September. My first assessment plan included a full cognitive battery, and at supervision my supervisor asked what a new set of scores would change. I had to admit that nothing would: nobody was questioning the placement. What the post-primary school needed was a picture of what he could do independently (travelling, handling money, packing his bag, asking for help) and what he wanted. I used an adaptive behaviour interview with his mother and his class teacher, and asked him, with pictures, what he was looking forward to and what worried him. He was most worried about getting lost and most looking forward to woodwork. The transition plan built on both: his first visit would start in the woodwork room, and he would have a simple map of the building. What this case taught me that the previous ones did not: reassessing a child whose needs are already known is not neutral, since it costs time and he has to experience being tested again, and the useful question is what the next setting needs to know, not what his scores are now.",
 "why": "The new learning is a shift from diagnosis to planning, prompted by a sharp supervision question. The method fits the purpose. The pupil's own priorities appear directly in the plan. The cost of unnecessary testing is named.",
 "changed": "The weak version describes a task. The strong version explains why the obvious task was the wrong one and what replaced it."},
]
