"""Micro-skills written in Claude Code, in the micro.py format from HANDOVER.md.

Keyed (macro skill name, micro-skill name). Merge into micro.py when the
original build folder is back; apply_micro.py writes these straight into the
workbook in the meantime.
"""

MICRO = {

# ── 1. ASSESSMENT · Synthesise findings from multiple sources into one profile ──

("Synthesise findings from multiple sources into one profile","Identify where sources converge"): {
"why":   "Convergence is the strongest evidence an assessment produces: the same pattern seen by different people, in different settings, with different methods. Triangulation, the idea that agreement across methods beats any single method (Denzin, The Research Act, 1978), is the logic of every integrated report. Get it wrong and you claim agreement that is only surface. 'Teacher and parent both mention attention' is not convergence if one means daydreaming and the other means leaving the seat.",
"s1":    "WATCH FOR — how your supervisor lines sources up before writing. Many do it on one page: sources down the side, domains across the top. Notice whether they check that two sources describe the same behaviour, or only use the same word.\n\nWRITE DOWN — every source used (interview, rating scale, observation, standardised test, work sample, file) and which domains each one spoke to.\n\nASK AFTERWARDS — 'how did you know the teacher's and parent's reports were about the same thing and not just the same label?'",
"s2":    "YOU TAKE — building the source-by-domain grid from the file, and marking every cell where two or more sources point the same way, with the specific evidence quoted.\n\nTHEY HOLD — the judgement on whether each apparent agreement is real convergence or just shared vocabulary.\n\nWHY THAT SPLIT — the grid is mechanical and teaches you the file. Judging whether agreement is genuine is the clinical skill, and it is the one you will be tested on.",
"s3":    "YOU RUN IT — present the grid in supervision and state each convergence aloud: which sources, which behaviour, which setting, how you know they mean the same thing.\n\nWHAT THEY ARE WATCHING FOR — convergence you count rather than check. Three sources that all rely on the same parent report are one source, not three.\n\nSTEPPING IN LOOKS LIKE — 'the rating scale and the interview both came from mum on the same day — is that two sources?'",
"s4":    "YOU DO IT ALONE — build the grid, write the convergent findings into the integration section with each source named in the sentence, and bring it to supervision.\n\nPASS TEST — Convergence is stated rather than assumed\n\nEVIDENCE TO FILE — the integration section of the report and the grid as a working paper on the case file. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — 'all sources indicate attention difficulties' with no named sources, no settings and no check that the behaviours match.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer the difference between convergence of label and convergence of behaviour, and why sources that share an origin (the same informant, the same day, the same form) do not independently confirm each other.\n\nWHEN IT GOES WRONG — you can say what to do when you find you overstated agreement after the report is drafted: rewrite the sentence to name the actual sources, and weaken the claim to what the evidence carries.",
"error": "Writing 'findings were consistent across sources' without naming the sources or checking they described the same behaviour.",
"feeds": "→ Feeds into 'Identify where sources diverge and say so', 'Judge which source to weight and why', and into Formulation, where convergent evidence carries the working hypothesis.",
"evidence":"Report — integration section · grid on case file · Appendix 5 · Log sheet tagged 1. Assessment"},

("Synthesise findings from multiple sources into one profile","Identify where sources diverge and say so"): {
"why":   "Divergence between sources is information, not noise. A child who is described as anxious at home and settled at school is telling you something about context. The cross-informant meta-analysis by Achenbach, McConaughy and Howell (Psychological Bulletin, 1987) found only modest agreement between different types of informant; exact figures are in the paper — check before quoting. A report that smooths divergence away hides the most useful finding and misleads the reader about how certain you are.",
"s1":    "WATCH FOR — how your supervisor words a disagreement between sources in the report. Notice whether they name both sides, or quietly pick one.\n\nWRITE DOWN — each point of divergence in the case: which sources, which domain, which setting, and the likely explanations your supervisor considered.\n\nASK AFTERWARDS — 'when the teacher and parent disagree, how do you decide whether it's the child, the setting, or the informant?'",
"s2":    "YOU TAKE — listing every divergence on the grid and drafting the possible explanations for each: different setting, different demands, different informant threshold, different time period.\n\nTHEY HOLD — the wording that goes in the report, because divergence can land badly with a parent or school who feels disbelieved.\n\nWHY THAT SPLIT — generating explanations is thinking you can practise safely. Wording that will be read by the family carries relational risk.",
"s3":    "YOU RUN IT — draft the divergence paragraph yourself and read it aloud in supervision before it goes in the report.\n\nWHAT THEY ARE WATCHING FOR — divergence resolved by picking the professional source over the parent, or the adult over the child, without a reason. That is a bias, not a judgement.\n\nSTEPPING IN LOOKS LIKE — 'you've gone with the teacher's view there. What would the parent say if they read this sentence?'",
"s4":    "YOU DO IT ALONE — identify each divergence, offer at least one explanation grounded in the setting or task demands, and write it into the report in neutral language.\n\nPASS TEST — Discrepancy is named rather than smoothed away\n\nEVIDENCE TO FILE — the integration section of the report, marked in your Appendix 5 entry as the place divergence was handled. Log against 1. Assessment and 6. Ethical Practice (PSI Code 4.2.6).\n\nWHAT FAILURE LOOKS LIKE — a profile that reads as if everyone agreed, when your grid shows they did not.",
"s5":    "YOU CAN TEACH IT — you can explain why informant disagreement is expected rather than a problem, and describe the context-based reading of it (De Los Reyes & Kazdin, Psychological Bulletin, 2005, on informant discrepancies).\n\nWHEN IT GOES WRONG — you can say what to do when a family objects that the report calls them wrong: show them the sentence, explain that both accounts are reported as true in their setting, and amend wording that implies blame.",
"error": "Reporting only the account that fits the hypothesis and leaving the contradicting one out.",
"feeds": "→ Feeds into 'Analyse informant agreement and discrepancy' (rating scales), into Formulation, and into Ethical Practice — honest reporting of uncertainty.",
"evidence":"Report — integration section · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Synthesise findings from multiple sources into one profile","Judge which source to weight and why"): {
"why":   "Sources are not equal, and pretending they are is its own error. A standardised score has known reliability; a single twenty-minute observation may have caught an unusual day; a parent knows the child across years but not in class. Weighting is unavoidable, so the professional task is to make it explicit. An unstated weighting cannot be challenged, and one that cannot be challenged cannot be defended at a review meeting or complaint.",
"s1":    "WATCH FOR — the moment your supervisor treats one finding as more telling than another. Listen for the reason: reliability, proximity to the concern, the setting it came from, or how recent it is.\n\nWRITE DOWN — each source, the weight your supervisor gave it (high, moderate, low), and the stated or implied reason.\n\nASK AFTERWARDS — 'if the WISC and the classroom observation pointed opposite ways, which would you trust more for this question — and would that change for a different question?'",
"s2":    "YOU TAKE — writing a proposed weighting for each source with one line of reasoning beside it: how reliable, how close to the referral concern, how representative.\n\nTHEY HOLD — the final weighting and any sentence in the report that ranks one informant's account below another's.\n\nWHY THAT SPLIT — writing reasons makes your implicit weighting visible so it can be corrected. Ranking people's accounts in print has consequences for relationships you do not yet hold.",
"s3":    "YOU RUN IT — state your weighting in supervision before you write the synthesis, and defend it when challenged.\n\nWHAT THEY ARE WATCHING FOR — weighting by status (the psychologist's test over the parent's account) or by convenience (the source that fits your hypothesis) instead of by fit to the question.\n\nSTEPPING IN LOOKS LIKE — 'the referral question is about the yard. Which of your sources were actually in the yard?'",
"s4":    "YOU DO IT ALONE — decide the weighting, write it into the synthesis in one or two sentences, and bring it to supervision already written.\n\nPASS TEST — The weighting is defensible and written down\n\nEVIDENCE TO FILE — the sentence in the report stating which evidence carried most weight and why. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a conclusion that clearly rests on one source, with nothing in the report saying so, so the reader cannot tell what would change it.",
"s5":    "YOU CAN TEACH IT — you can explain the criteria for weighting (reliability, validity for the specific question, setting, recency, independence from other sources) and give a worked case where the same source deserves high weight for one question and low weight for another.\n\nWHEN IT GOES WRONG — you can say what to do when new information arrives that overturns your weighting: say so in an addendum rather than quietly revising the conclusion.",
"error": "Letting the standardised score overrule everything else because it has a number attached, without asking whether it answers the referral question.",
"feeds": "→ Feeds into 'Write an integration section rather than a list', into Formulation, and into defending conclusions at a review meeting.",
"evidence":"Report — integration and conclusions · Appendix 5 · Log sheet tagged 1. Assessment"},

("Synthesise findings from multiple sources into one profile","Write an integration section rather than a list"): {
"why":   "A report that lists findings test by test hands the hardest part of the job to the reader. Teachers and parents will not integrate a WISC section, a rating-scale section and an observation section on their own; they will skim to the recommendations. Report-writing texts are consistent on this: organise by theme or domain, not by instrument (Lichtenberger, Mather, Kaufman & Kaufman, Essentials of Assessment Report Writing, 2004). An unintegrated report is the commonest reason a trainee's report is returned.",
"s1":    "WATCH FOR — how your supervisor's reports are structured. Look for a section headed something like 'integration', 'summary of findings' or 'profile', and see whether it is organised by instrument or by question.\n\nWRITE DOWN — the headings of three of their reports, and one integration paragraph you think works, with why.\n\nASK AFTERWARDS — 'when you write the summary, do you start from the tests or from the referral question?'",
"s2":    "YOU TAKE — drafting the integration section for a case your supervisor is leading, organised by referral question or by domain, with each claim tied to named evidence.\n\nTHEY HOLD — the overall conclusions and the final draft that goes to the family.\n\nWHY THAT SPLIT — drafting integration is where you find out whether you understood the case. Your supervisor carries the conclusions, so an early draft that gets it wrong costs nothing.",
"s3":    "YOU RUN IT — write the integration section for your own case and bring it to supervision before the recommendations are written.\n\nWHAT THEY ARE WATCHING FOR — a list with joining words. 'The WISC showed X. The teacher reported Y. Observation found Z.' is still a list.\n\nSTEPPING IN LOOKS LIKE — 'read me the first sentence of each paragraph. Does it make a claim, or name a test?'",
"s4":    "YOU DO IT ALONE — write an integration section where each paragraph opens with a claim about the child, then gives the evidence from several sources, then says what it means for the referral question.\n\nPASS TEST — The reader is not left to do the synthesis\n\nEVIDENCE TO FILE — the report. Name this section in your Appendix 5 entry. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — recommendations that do not follow from anything the integration section said, because the integration section did not say anything.",
"s5":    "YOU CAN TEACH IT — you can show a peer how to rewrite a test-by-test summary into claim-first paragraphs, and explain why this is what makes recommendations defensible.\n\nWHEN IT GOES WRONG — you can say what to do when the findings genuinely do not integrate: say so, name the competing readings, and state what further evidence would decide between them.",
"error": "Repeating every score again in the summary instead of saying what the scores mean together.",
"feeds": "→ Feeds into 'Ask whether the profile answers the referral question', into Formulation, and into recommendations the school can act on.",
"evidence":"Report — integration section · Appendix 5 · Log sheet tagged 1. Assessment"},

("Synthesise findings from multiple sources into one profile","Ask whether the profile answers the referral question"): {
"why":   "The referral question is the contract. Schools and parents asked something specific, and a thorough report that answers a different question has failed them, however good the psychometrics. It is easy to drift: the assessment finds something interesting and the report follows it. The check is simple and often skipped — reread the question, reread your conclusion, and see whether one answers the other.",
"s1":    "WATCH FOR — whether your supervisor goes back to the referral form before finalising a report. Some print it and set it beside the draft.\n\nWRITE DOWN — the referral question in the referrer's own words, and the one-sentence answer your supervisor's report gives to it.\n\nASK AFTERWARDS — 'has a report of yours ever answered a different question from the one that was asked? What happened?'",
"s2":    "YOU TAKE — writing the referral question at the top of the draft in the referrer's words, and a one-line answer to it underneath, before anything else is written.\n\nTHEY HOLD — whether the question itself needs to be renegotiated with the school or parent.\n\nWHY THAT SPLIT — checking the fit is a habit you can build straight away. Going back to a referrer to say the question has changed is a consultation decision.",
"s3":    "YOU RUN IT — at the end of your draft, state aloud in supervision: the question asked, your answer, and which section of the report carries it.\n\nWHAT THEY ARE WATCHING FOR — an answer that is technically there but buried, or an answer to the question you would have preferred they asked.\n\nSTEPPING IN LOOKS LIKE — 'if the principal read only your summary, would they know the answer to what they asked?'",
"s4":    "YOU DO IT ALONE — before sending any report, check it against the referral question and fix it if it does not answer it. If it cannot answer it, say why in the report.\n\nPASS TEST — You noticed if it did not\n\nEVIDENCE TO FILE — the report, with the referral question stated at the start and answered in the summary. Note in the Log if the question was renegotiated. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — the school rings to ask what the report means for their question.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer how referral questions drift during an assessment, and show the simple check: question, answer, location in the report.\n\nWHEN IT GOES WRONG — you can say what to do when the assessment shows the original question was the wrong one: answer it anyway, then say plainly what you think the more useful question is and why.",
"error": "Sending a report that is thorough on cognition when the school asked about behaviour in the yard.",
"feeds": "→ Feeds into recommendations, into Working with Others — agreeing the question at the start — and into Formulation.",
"evidence":"Report — reason for referral and summary · Appendix 5 · Log sheet tagged 1. Assessment"},

("Synthesise findings from multiple sources into one profile","State what you did not assess and what that limits"): {
"why":   "Every assessment is partial. A report that does not say what was left out invites the reader to assume it was covered — that language was fine because it was not mentioned, or that mood was screened because anxiety was not reported. Stating the limits of your competence and your evidence is a professional obligation (CORU SoP 1.2; PSI Code 2.3.1). Missing limitations are what an external examiner or a complaint will find first.",
"s1":    "WATCH FOR — where in your supervisor's reports the limitations appear, and how they are worded. Some write a short paragraph; some fold them into each section.\n\nWRITE DOWN — every domain relevant to the referral that was not directly assessed in the case, and whether the report says so.\n\nASK AFTERWARDS — 'how do you decide what goes in the limitations without making the report sound like it achieved nothing?'",
"s2":    "YOU TAKE — drafting the limitations paragraph: what was not assessed, why (time, consent, scope, a test not available, the child's state on the day), and what that means for the conclusions.\n\nTHEY HOLD — the decision about whether a gap is serious enough to change the conclusions or require an onward referral.\n\nWHY THAT SPLIT — listing gaps is straightforward. Judging whether a gap undermines the conclusion needs experience of what those gaps usually hide.",
"s3":    "YOU RUN IT — write the limitations yourself and discuss in supervision which of them affect the conclusions directly.\n\nWHAT THEY ARE WATCHING FOR — a boilerplate paragraph ('results should be interpreted with caution') that could go in any report and tells the reader nothing about this one.\n\nSTEPPING IN LOOKS LIKE — 'caution about what, exactly? Which conclusion would change if you had assessed that?'",
"s4":    "YOU DO IT ALONE — every report you write has a specific limitations paragraph naming what was not assessed and which conclusion that affects.\n\nPASS TEST — A limitations paragraph exists\n\nEVIDENCE TO FILE — the limitations paragraph in the report. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — no limitations paragraph, or a generic one, so the school acts on a conclusion the evidence does not carry.",
"s5":    "YOU CAN TEACH IT — you can explain why a limitations paragraph protects the child, the reader and you, and show how to make one specific: name the gap, the reason, and the conclusion it qualifies.\n\nWHEN IT GOES WRONG — you can say what to do when a gap you did not report turns out to matter later: acknowledge it in writing, correct the record, and tell your supervisor before the family hears it from someone else.",
"error": "A generic 'interpret with caution' line that names no gap and qualifies no conclusion.",
"feeds": "→ Feeds into Ethical Practice — working within competence — and into onward referral decisions.",
"evidence":"Report — limitations · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

# ── 1. ASSESSMENT · Phonological and literacy measures ──

("Phonological and literacy measures","Explain why phonological awareness matters for reading"): {
"why":   "Teachers will ask why you tested sound games when the concern was reading. The answer is the core of the literacy evidence base. The Simple View of Reading splits reading into decoding and language comprehension (Gough & Tunmer, Remedial and Special Education, 1986). Phonological processing difficulty is the best-supported account of why decoding fails (the 'phonological core' view — Stanovich, Journal of Learning Disabilities, 1988). If you cannot explain this plainly, the recommendations that follow will not be implemented.",
"s1":    "WATCH FOR — how your supervisor explains phonological awareness to a teacher or parent. Note the example they use; most use rhyme, syllables and a spoken word broken into sounds.\n\nWRITE DOWN — the explanation in their words, and any question the listener asked that showed confusion.\n\nASK AFTERWARDS — 'how do you explain the difference between phonological awareness and phonics to a teacher who uses the words interchangeably?'",
"s2":    "YOU TAKE — the explanation of phonological awareness in a feedback meeting, prepared in advance and kept to two minutes.\n\nTHEY HOLD — linking it to this child's scores and to what the school should do.\n\nWHY THAT SPLIT — the general explanation can be rehearsed and is low-risk. Tying it to a named child's results carries the interpretation, which your supervisor still owns at this stage.",
"s3":    "YOU RUN IT — explain phonological awareness and its link to this child's reading in a feedback meeting, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — jargon ('phonemic segmentation deficit') and overclaiming, such as implying phonological difficulty is the whole story when comprehension or vocabulary are also weak.\n\nSTEPPING IN LOOKS LIKE — a supervisor asking, in the meeting, 'could you give an example of what that looks like in class?'",
"s4":    "YOU DO IT ALONE — explain it to a teacher or parent in plain language, with one example drawn from this child's work, and check that they understood.\n\nPASS TEST — You can explain it to a teacher without notes\n\nEVIDENCE TO FILE — a case note of the feedback meeting. Log against 1. Assessment and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — the teacher leaves thinking the answer is more phonics worksheets, or thinking the child cannot learn to read.",
"s5":    "YOU CAN TEACH IT — you can explain the Simple View of Reading, why decoding and comprehension can fail separately, and where phonological awareness sits — citing sources, not from memory of a lecture.\n\nWHEN IT GOES WRONG — you can say what to do when a teacher disagrees ('he knows all his sounds'): separate knowing letter–sound links from being able to manipulate sounds in spoken words, and show the difference with a quick oral example.",
"error": "Explaining phonological awareness with the child's scores instead of with an example the teacher will recognise in class.",
"feeds": "→ Feeds into 'Distinguish a specific difficulty from a general one', 'Interpret a phonological profile in context', and 'Link the profile to what the school can deliver'.",
"evidence":"Case note of feedback meeting · Appendix 5 · Log sheet tagged 1. Assessment and 5. Working with Others"},

("Phonological and literacy measures","Distinguish a specific difficulty from a general one"): {
"why":   "A child with weak reading and weak general language or reasoning needs different support from a child whose reading difficulty stands apart from otherwise typical abilities. Current definitions of dyslexia treat it as a continuum and do not rely on an IQ–achievement discrepancy (Rose, Identifying and Teaching Children and Young People with Dyslexia and Literacy Difficulties, 2009). But you still have to know the broader profile — especially oral language — before calling the difficulty specific. Skip that and the recommendation targets the wrong thing.",
"s1":    "WATCH FOR — which information your supervisor looks at before saying a literacy difficulty is 'specific': cognitive scores, oral language, attendance, teaching history, vision and hearing.\n\nWRITE DOWN — the checks they made and any they said were missing.\n\nASK AFTERWARDS — 'what would make you say this is a general learning difficulty showing up in reading, rather than a reading difficulty?'",
"s2":    "YOU TAKE — gathering the wider profile: cognitive or language scores, school history, attendance, sensory screening, and whether the child has had adequate teaching.\n\nTHEY HOLD — the conclusion about whether the difficulty is specific, and how it is worded.\n\nWHY THAT SPLIT — collecting the context teaches you what the question depends on. The label, or the absence of one, is what the family and school will act on.",
"s3":    "YOU RUN IT — present your view in supervision: specific, general, or unclear, and the evidence for each.\n\nWHAT THEY ARE WATCHING FOR — jumping from low phonological scores to 'dyslexic profile' without checking oral language comprehension or response to teaching.\n\nSTEPPING IN LOOKS LIKE — 'what's their receptive language like? And how long have they had structured literacy teaching?'",
"s4":    "YOU DO IT ALONE — check the broader profile before concluding, and state in the report what that check found.\n\nPASS TEST — You check the cognitive profile before concluding\n\nEVIDENCE TO FILE — the interpretation section of the report, with the broader profile referenced. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a report naming a specific literacy difficulty for a child whose oral language is as weak as their reading, so the language need goes unaddressed.",
"s5":    "YOU CAN TEACH IT — you can explain to a peer why discrepancy definitions were abandoned, what replaced them, and why the wider profile still matters — citing Rose (2009) and your service's own criteria.\n\nWHEN IT GOES WRONG — you can say what to do when the profile is mixed: describe both needs, say which is primary for the referral question, and avoid a label the evidence does not support.",
"error": "Concluding 'specific' from low phonological scores alone, without checking oral language or teaching history.",
"feeds": "→ Feeds into 'Interpret a phonological profile in context', into Formulation, and into Conditions — DLD and literacy difficulty.",
"evidence":"Report — interpretation · Appendix 5 · Log sheet tagged 1. Assessment"},

("Phonological and literacy measures","Administer phonological awareness subtests to standard"): {
"why":   "Phonological tasks are presented orally, so the stimulus is your voice. Speak too slowly, stress the wrong sound or repeat an item not allowed to be repeated, and the score reflects your delivery, not the child's skill. Many batteries use recorded audio for some tasks for this reason: CTOPP-2 (Wagner, Torgesen, Rashotte & Pearson, 2013) supplies audio for some subtests. Check your edition's manual for which ones. An inaccurate administration cannot be rescued at scoring.",
"s1":    "WATCH FOR — how your supervisor delivers oral items: pace, whether they use the audio where the manual requires it, how they handle a request to repeat, and what they do after a discontinue.\n\nWRITE DOWN — the subtests used, the start points, repeat rules and discontinue rules, checked against the manual afterwards.\n\nASK AFTERWARDS — 'what's the easiest way to spoil an elision item without noticing?'",
"s2":    "YOU TAKE — administering one phonological subtest while your supervisor watches, having practised it aloud at least twice beforehand.\n\nTHEY HOLD — the rest of the battery and the decision about whether your administration was valid enough to score.\n\nWHY THAT SPLIT — oral delivery is a motor skill that needs practice under observation. Whether a spoiled item invalidates the subtest is a judgement you have not yet seen enough to make.",
"s3":    "YOU RUN IT — administer the full phonological battery with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — adding sounds (saying 'buh' for /b/), unscripted feedback, repeating items the manual says cannot be repeated, and losing track of the discontinue rule.\n\nSTEPPING IN LOOKS LIKE — a quiet note to check the discontinue rule, or taking over for one item and handing back.",
"s4":    "YOU DO IT ALONE — administer the battery to manual standard, with the audio where required, correct start points and discontinues, and responses recorded as you go.\n\nPASS TEST — Administration is fluent and timing accurate\n\nEVIDENCE TO FILE — the completed record form. Log against 1. Assessment and Table 3 tools.\n\nWHAT FAILURE LOOKS LIKE — a discontinued subtest continued, or items repeated against the rules, so the scaled score cannot be interpreted.",
"s5":    "YOU CAN TEACH IT — you can demonstrate clean phoneme production (no added schwa), explain the start, repeat and discontinue rules from memory, and explain why each rule exists.\n\nWHEN IT GOES WRONG — you can say what to do when you realise mid-battery you broke a rule: note it on the form at that point, decide with the manual whether the subtest is still scoreable, and report the problem if it is not.",
"error": "Adding a vowel to isolated consonants ('buh' for /b/), which changes the task the child is doing.",
"feeds": "→ Feeds into 'Score the phonological composites correctly' and 'Interpret a phonological profile in context'.",
"evidence":"Completed protocol · Appendix 7 if observed · Log sheet tagged 1. Assessment"},

("Phonological and literacy measures","Administer rapid naming tasks accurately"): {
"why":   "Rapid automatised naming (RAN) — naming arrays of digits, letters, colours or objects as fast as possible — predicts reading fluency partly independently of phonological awareness. This is the basis of the double-deficit hypothesis (Wolf & Bowers, Journal of Educational Psychology, 1999). The score is a time, often adjusted for errors, so a stopwatch started late or an error not recorded changes the result directly.",
"s1":    "WATCH FOR — exactly when your supervisor starts and stops the timer, how they record errors and self-corrections, and whether they use the practice items as the manual requires.\n\nWRITE DOWN — the timing rule (when the clock starts and stops), how errors are counted, and whether the test has an error cut-off that invalidates a trial.\n\nASK AFTERWARDS — 'what do you do if a child loses their place on the array?'",
"s2":    "YOU TAKE — timing and error recording while your supervisor administers, then compare your times with theirs.\n\nTHEY HOLD — the administration and the decision on which timing counts if yours differs.\n\nWHY THAT SPLIT — timing reliability is checkable against another person, so it is the right thing to practise first. Administration adds the load of instructions and managing the child.",
"s3":    "YOU RUN IT — administer and time the RAN tasks with your supervisor present, timing in parallel.\n\nWHAT THEY ARE WATCHING FOR — timer starts that lag the child's first response, errors missed because you were watching the clock, and prompts the manual does not allow.\n\nSTEPPING IN LOOKS LIKE — comparing the two times afterwards and asking why they differ by more than a second.",
"s4":    "YOU DO IT ALONE — administer, time and record errors to manual standard, and note anything that affected speed (stammer, naming difficulty, losing place).\n\nPASS TEST — You timed and recorded errors correctly\n\nEVIDENCE TO FILE — the completed record form with times and errors. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a time that includes your instructions, or no record of errors, so the score and any error adjustment are wrong.",
"s5":    "YOU CAN TEACH IT — you can explain what RAN measures and does not measure, why it relates to fluency, and how to time it reliably — with the double-deficit literature cited.\n\nWHEN IT GOES WRONG — you can say what to do when the timing is compromised (interruption, timer failure): note it, do not estimate, and check the manual on whether the trial can be re-run.",
"error": "Starting the timer on your own instruction rather than on the child's first response, which adds seconds to every trial.",
"feeds": "→ Feeds into 'Score the phonological composites correctly' and 'Interpret a phonological profile in context' — especially fluency-focused recommendations.",
"evidence":"Completed protocol with times · Log sheet tagged 1. Assessment"},

("Phonological and literacy measures","Score the phonological composites correctly"): {
"why":   "Composite scores are what reports quote and what schools act on, and they are built from several conversions: raw to scaled for each subtest, scaled summed to a composite, composite to percentile and confidence interval. Each step uses the child's exact age on the day. On CTOPP-2 (Wagner et al., 2013), subtests are scaled scores (mean 10, SD 3) and composites are index scores (mean 100, SD 15). Which subtests feed which composite changes with age band, so check the manual for your edition. One wrong table and the whole profile shifts.",
"s1":    "WATCH FOR — how your supervisor calculates chronological age, which norm table they turn to, and whether they double-check the sum of scaled scores before looking up the composite.\n\nWRITE DOWN — for each composite, which subtests feed it at this child's age, and the table used.\n\nASK AFTERWARDS — 'which scoring mistake have you seen most often in trainee protocols?'",
"s2":    "YOU TAKE — scoring the protocol independently, from raw scores to composites, before seeing your supervisor's scoring.\n\nTHEY HOLD — the authoritative score, and resolving any difference between your scoring and theirs.\n\nWHY THAT SPLIT — independent double-scoring is the fastest way to find your systematic errors. Your supervisor's version stands until you have shown you score accurately.",
"s3":    "YOU RUN IT — score the protocol and the composites yourself; your supervisor checks it before anything is reported.\n\nWHAT THEY ARE WATCHING FOR — age calculated wrongly (especially borrowing months and days), the wrong age-band table, a subtest summed into the wrong composite, and transcription errors from protocol to report.\n\nSTEPPING IN LOOKS LIKE — handing it back with 'one of these is wrong — find it.'",
"s4":    "YOU DO IT ALONE — score, then check every step a second time on a different day or with scoring software, and reconcile any difference before reporting.\n\nPASS TEST — Composites calculated and checked\n\nEVIDENCE TO FILE — the scored protocol with your check marked, and the score table in the report. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a composite in the report that does not match the protocol, found by the family's private assessor or at a review.",
"s5":    "YOU CAN TEACH IT — you can walk a peer through age calculation, subtest-to-composite mapping, and confidence intervals, and explain why a composite is more reliable than any single subtest.\n\nWHEN IT GOES WRONG — you can say what to do when you find a scoring error after the report has gone: tell your supervisor, issue a corrected report with the change marked, and tell the family and school what changed and whether the conclusion changes.",
"error": "Calculating age without borrowing correctly across months and days, and reading off the wrong norm table.",
"feeds": "→ Feeds into 'Interpret a phonological profile in context' and into the score table and limitations of the report.",
"evidence":"Scored protocol with check · Report — score table · Appendix 5 · Log sheet tagged 1. Assessment"},

("Phonological and literacy measures","Interpret a phonological profile in context"): {
"why":   "A low phonological composite shows the child did poorly on these tasks, on this day, compared with the norm sample. It does not by itself establish dyslexia, explain every reading problem, or predict what intervention will work. Interpretation means putting the scores beside reading accuracy, fluency, comprehension, oral language, teaching history and the child's own account. Rose (2009) is explicit that dyslexia is best thought of as a continuum and that response to intervention is part of the picture. Overclaim here and the family leaves with a label the evidence does not carry.",
"s1":    "WATCH FOR — the words your supervisor uses when interpreting phonological scores: 'consistent with', 'suggests', 'is characteristic of'. Note what they will not say.\n\nWRITE DOWN — the other evidence they set beside the scores, and any conclusion they chose not to draw.\n\nASK AFTERWARDS — 'what would you need to see before you'd say this profile shows a dyslexic-type difficulty?'",
"s2":    "YOU TAKE — drafting the interpretation paragraph: what the scores show, which other evidence agrees or disagrees, and the limits.\n\nTHEY HOLD — any diagnostic or quasi-diagnostic language, and how the conclusion is framed for the family.\n\nWHY THAT SPLIT — writing interpretation shows your reasoning. Diagnostic language has consequences for school supports and for the child's view of themselves, so it stays with them.",
"s3":    "YOU RUN IT — write the interpretation and present it in supervision, including one sentence on what the profile does not establish.\n\nWHAT THEY ARE WATCHING FOR — reading scores as causes ('because of her phonological deficit') and ignoring evidence of adequate teaching, attendance, or language.\n\nSTEPPING IN LOOKS LIKE — 'you've said this explains her reading. What else could explain it?'",
"s4":    "YOU DO IT ALONE — interpret the profile against the wider evidence, and write explicitly what it does and does not establish.\n\nPASS TEST — You can say what it does and does not establish\n\nEVIDENCE TO FILE — the interpretation and limitations sections of the report. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — 'the results confirm dyslexia' on the basis of one battery, with no reference to the child's response to teaching.",
"s5":    "YOU CAN TEACH IT — you can explain the difference between describing a profile and diagnosing, why phonological scores are one strand of evidence, and how to write both halves: what it shows and what it does not.\n\nWHEN IT GOES WRONG — you can say what to do when a parent wants a label the evidence does not support: explain what the evidence does show, what support follows from it without a label, and what would need to happen for the question to be revisited.",
"error": "Writing that the scores 'confirm' a difficulty rather than that they are consistent with it alongside the other evidence.",
"feeds": "→ Feeds into 'Link the profile to what the school can deliver', into Formulation, and into Conditions — literacy difficulty and DLD.",
"evidence":"Report — interpretation and limitations · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Phonological and literacy measures","Link the profile to what the school can deliver"): {
"why":   "A recommendation the school cannot deliver is not a recommendation. Irish primary schools allocate special education teaching under the model set out in DES Circular 0013/2017 (post-primary 0014/2017), within the NEPS Continuum of Support. What is possible depends on staffing, timetable and the programmes staff are trained in. Recommendations should follow from the finding — phonological weakness points towards explicit, systematic phonological and phonics teaching — and be specific enough to act on.",
"s1":    "WATCH FOR — how your supervisor finds out what the school already offers before recommending. Listen for questions about the special education team, programmes in use, group sizes and timetabling.\n\nWRITE DOWN — each recommendation in their report, the finding it follows from, and whether it names who, what, how often and for how long.\n\nASK AFTERWARDS — 'how do you write a recommendation that is honest about what the child needs when the school can't provide all of it?'",
"s2":    "YOU TAKE — drafting the recommendations for the literacy section, each linked in one line to the finding it comes from.\n\nTHEY HOLD — the conversation with the school about what is feasible, and the final wording.\n\nWHY THAT SPLIT — linking finding to recommendation is reasoning you can practise. Negotiating provision with a principal involves a relationship and service expectations you do not yet hold.",
"s3":    "YOU RUN IT — ask the school what it can offer, write recommendations that fit, and present them in the feedback meeting with your supervisor there.\n\nWHAT THEY ARE WATCHING FOR — generic recommendations ('multisensory approach', 'extra time') that do not follow from this child's profile, and naming a programme the school does not have or cannot resource.\n\nSTEPPING IN LOOKS LIKE — 'which finding does that recommendation come from?'",
"s4":    "YOU DO IT ALONE — write recommendations that each follow from a named finding and that the school has confirmed it can deliver or adapt.\n\nPASS TEST — The recommendation follows from the finding\n\nEVIDENCE TO FILE — the recommendations section and the case note of the school conversation. Log against 1. Assessment, 3. Intervention and 4. Systemic Change.\n\nWHAT FAILURE LOOKS LIKE — ten recommendations copied from a template, none implemented, and a review six months later with nothing changed.",
"s5":    "YOU CAN TEACH IT — you can explain how the Continuum of Support and the allocation model shape what schools can do, and how to write a recommendation that names what, who, how often, for how long and how progress will be measured.\n\nWHEN IT GOES WRONG — you can say what to do when the child needs more than the school can give: state the need honestly, recommend what is feasible now, and say who else should be involved.",
"error": "A list of generic literacy recommendations that could have gone in any child's report.",
"feeds": "→ Feeds into Intervention — planning and review — and into Systemic Change, where repeated gaps in school provision become a consultation issue.",
"evidence":"Report — recommendations · case note · Appendix 5 · Log sheet tagged 1. Assessment and 3. Intervention"},

# ── 1. ASSESSMENT · Social communication screening measures ──

("Social communication screening measures","Recognise the limits of a screening instrument"): {
"why":   "A screen finds people who may need a fuller assessment. It does not diagnose. Questionnaires such as the Social Communication Questionnaire (SCQ; Rutter, Bailey & Lord, 2003) or the Social Responsiveness Scale (SRS-2; Constantino & Gruber, 2012) rely on one informant's view and use cut-offs chosen to trade missed cases against false alarms. Sensitivity and specificity vary by sample and age — check the manual and do not quote a figure from memory. A family who hears 'the score was high' as 'your child is autistic' has been misled.",
"s1":    "WATCH FOR — how your supervisor describes a screening result, in the report and aloud. Notice the words they avoid.\n\nWRITE DOWN — the instrument, the informant, the cut-off, what the manual says the cut-off means, and the exact sentence your supervisor used to report it.\n\nASK AFTERWARDS — 'have you ever had a screen come back below the cut-off for a child you were sure needed a full assessment? What did you do?'",
"s2":    "YOU TAKE — drafting the paragraph that reports the screen, including a sentence saying what a screen can and cannot establish.\n\nTHEY HOLD — the recommendation about onward referral, and the conversation with the family.\n\nWHY THAT SPLIT — the wording can be practised and corrected on paper. The onward decision and the family conversation carry emotional weight and service consequences.",
"s3":    "YOU RUN IT — report the screen yourself, in writing and aloud to the family, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — diagnostic language ('scores in the autistic range') and false reassurance from a low score when observation or history raise concern.\n\nSTEPPING IN LOOKS LIKE — your supervisor adding, 'just to be clear, this is a questionnaire, not an assessment for autism.'",
"s4":    "YOU DO IT ALONE — report every screen with a written statement that it is not a diagnosis, what it does suggest, and what happens next.\n\nPASS TEST — You said in writing that a screen is not a diagnosis\n\nEVIDENCE TO FILE — the report paragraph. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a school telling a parent 'the psychologist said he's autistic' because your report said 'scores in the autism range'.",
"s5":    "YOU CAN TEACH IT — you can explain sensitivity, specificity and why cut-offs are compromises, and why a single-informant questionnaire cannot carry a diagnosis.\n\nWHEN IT GOES WRONG — you can say what to do when a screen is being used as a diagnosis by the school or family: correct it in writing, explain the difference, and point to the pathway.",
"error": "Writing 'in the autism range' instead of 'above the screening threshold, which indicates a fuller assessment is warranted'.",
"feeds": "→ Feeds into 'Know the onward diagnostic pathway in this service', 'Integrate screening data with direct observation', and Ethical Practice.",
"evidence":"Report — findings and limitations · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Social communication screening measures","Know the onward diagnostic pathway in this service"): {
"why":   "A positive screen with nowhere to go leaves the family holding a worry and no route. In Ireland, autism diagnostic assessment is usually done by HSE multidisciplinary teams — Children's Disability Network Teams, primary care, or CAMHS where there is a co-occurring mental health need — or by private assessment. Assessment of Need under the Disability Act 2005 is one statutory route. Routes, waiting times and who can refer vary by area and change often, so find out the current local position rather than assuming.",
"s1":    "WATCH FOR — what your supervisor tells a family after a positive screen: who they should contact, who makes the referral, and roughly how long it takes.\n\nWRITE DOWN — the local pathway as your supervisor describes it: team names, referral route, who can refer, whether the school or GP is involved, and any local waiting time they quote.\n\nASK AFTERWARDS — 'what's changed in this pathway in the last two years, and where do you check it's still current?'",
"s2":    "YOU TAKE — writing a one-page summary of the local pathway for your own use, and checking it with your supervisor.\n\nTHEY HOLD — advising the family on the route, and any referral made.\n\nWHY THAT SPLIT — mapping the pathway is research you can do alone and it builds your knowledge of the area. Advice to a family must be current and accurate, so your supervisor gives it until you have checked the map.",
"s3":    "YOU RUN IT — explain the pathway to a family after a screen, with your supervisor there.\n\nWHAT THEY ARE WATCHING FOR — out-of-date information, promises about timescales, and not mentioning interim support the school can put in place without a diagnosis.\n\nSTEPPING IN LOOKS LIKE — your supervisor adding what the school can do in the meantime.",
"s4":    "YOU DO IT ALONE — name the onward pathway in the report and to the family, accurately for the area, with interim supports alongside.\n\nPASS TEST — You could name where a positive screen goes\n\nEVIDENCE TO FILE — the recommendations section of the report and the pathway summary on file. Log against 1. Assessment and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — 'the family should seek a diagnostic assessment', with no route named, and a family that does not know where to start.",
"s5":    "YOU CAN TEACH IT — you can explain the Irish routes (HSE teams, Assessment of Need, CAMHS, private), who refers, and the difference between a need-led support in school and a diagnosis-led service.\n\nWHEN IT GOES WRONG — you can say what to do when the pathway is blocked or very long: say so honestly, recommend what the school can do now, and record the gap for your service's systemic view.",
"error": "Telling a family to 'seek a diagnosis' without naming who, how, or what to do while they wait.",
"feeds": "→ Feeds into Working with Others — interagency referral — and into Systemic Change, where pathway gaps are raised.",
"evidence":"Report — recommendations · pathway summary on file · Appendix 5 · Log sheet tagged 1. Assessment and 5. Working with Others"},

("Social communication screening measures","Administer a screen with a parent"): {
"why":   "Parents complete screening questionnaires about their own child, often while already worried or defending against a worry. How you introduce it shapes what they report. Some over-endorse to secure help; some under-endorse to protect the child from a label. Explaining what the screen is for, what it cannot tell them, and what happens next is part of informed consent. It also makes the answers more accurate.",
"s1":    "WATCH FOR — how your supervisor introduces the questionnaire: purpose, how long it takes, how to handle items they are unsure of, and who will see the results.\n\nWRITE DOWN — their introduction as close to verbatim as you can, and any question the parent asked.\n\nASK AFTERWARDS — 'what do you say when a parent asks, before they start, whether a high score means autism?'",
"s2":    "YOU TAKE — introducing the questionnaire to the parent, from a script you have written and checked with your supervisor.\n\nTHEY HOLD — questions about diagnosis, and any distress that comes up.\n\nWHY THAT SPLIT — a scripted introduction is safe to practise. Questions about what the child 'has' need someone who can answer them in the moment without overstating.",
"s3":    "YOU RUN IT — introduce the questionnaire, answer the parent's questions, and stay available while they complete it, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — leading the parent ('does he do this a lot?') or interpreting items in a way that shifts the answer.\n\nSTEPPING IN LOOKS LIKE — your supervisor offering the standard response to an unclear item: 'answer as best you can and we'll talk about it after.'",
"s4":    "YOU DO IT ALONE — introduce the screen, explain what it can and cannot tell them, give neutral help with unclear items, and tell them when and how they will hear the results.\n\nPASS TEST — You explained what a screen can and cannot tell them\n\nEVIDENCE TO FILE — a case note recording the explanation given. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a parent who completed the form thinking the score would give them a diagnosis, and who is distressed or angry when it does not.",
"s5":    "YOU CAN TEACH IT — you can explain why the introduction matters for validity as well as consent, and how to answer a parent's questions about an item without shifting their answer.\n\nWHEN IT GOES WRONG — you can say what to do when a parent becomes distressed or angry during the questionnaire: stop, acknowledge it, offer to finish another time, and record that the conditions may have affected the responses.",
"error": "Handing the questionnaire over without explaining that it is a screen and not a diagnosis.",
"feeds": "→ Feeds into 'Integrate screening data with direct observation', into consent practice in Ethical Practice, and into Working with Others — families.",
"evidence":"Case note · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Social communication screening measures","Integrate screening data with direct observation"): {
"why":   "A questionnaire records one informant's summary of the child. Observation shows you the child — in the yard, in class, with peers and adults. Each can mislead alone. The screen can be skewed by the informant, and a short observation can catch an untypical day. Guidance on autism assessment consistently requires information from more than one source and setting — check the specific requirements of the guidance your service uses. Relying on the questionnaire alone makes the screen do a job it was not built for.",
"s1":    "WATCH FOR — which settings your supervisor chooses to observe after a screen, and what they look for: initiation, response to bids, reciprocity, play, transitions, sensory response.\n\nWRITE DOWN — the observation focus, the setting, and how the observation was later set beside the questionnaire.\n\nASK AFTERWARDS — 'when the screen and your observation disagree, what do you do?'",
"s2":    "YOU TAKE — the observation in one setting, with a focus agreed beforehand from the screen items.\n\nTHEY HOLD — putting the two together and deciding what it means for onward referral.\n\nWHY THAT SPLIT — a focused observation is a skill you are already building. Integrating it with a screen and deciding on referral is a clinical judgement.",
"s3":    "YOU RUN IT — plan the observation from the screen, observe, and present the integration in supervision.\n\nWHAT THEY ARE WATCHING FOR — observing only structured class time when the concern is unstructured social time, and treating 'did not see it' as 'it does not happen'.\n\nSTEPPING IN LOOKS LIKE — 'the parent reported difficulty at break. When did you observe?'",
"s4":    "YOU DO IT ALONE — observe in at least one setting chosen to test what the screen suggested, and write a paragraph that sets the two sources together.\n\nPASS TEST — You did not rely on the questionnaire alone\n\nEVIDENCE TO FILE — the observation write-up and the integration paragraph in the report. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a report whose conclusions rest entirely on a questionnaire score.",
"s5":    "YOU CAN TEACH IT — you can explain why screening and observation are complementary, how to choose an observation setting from screen items, and why absence of a behaviour in one short observation is weak evidence.\n\nWHEN IT GOES WRONG — you can say what to do when the two sources flatly contradict: report both, give the likeliest reasons, and let that uncertainty inform the onward referral rather than hiding it.",
"error": "Observing in the setting that was easiest to arrange rather than the one where the concern was reported.",
"feeds": "→ Feeds into 'Recognise masked or atypical presentation', into 'Identify where sources diverge and say so', and into onward referral.",
"evidence":"Observation write-up · Report — integration · Appendix 5 · Log sheet tagged 1. Assessment"},

("Social communication screening measures","Recognise masked or atypical presentation"): {
"why":   "Some autistic children — often, but not only, girls — learn to hide or compensate for social differences, at great cost to themselves. This is camouflaging, described in Hull et al. (Journal of Autism and Developmental Disorders, 2017). A meta-analysis estimated the true male-to-female ratio nearer 3:1 than the 4:1 often quoted, pointing to under-identification of girls (Loomes, Hull & Mandy, JAACAP, 2017). Screens and short observations may miss these children. The PSI Autism Guidelines (2022) are the reference named for this standard — read them directly rather than relying on a summary.",
"s1":    "WATCH FOR — how your supervisor asks about effort and exhaustion as well as behaviour: after-school collapse, scripted conversation, intense friendships that break down, anxiety, masking at school and releasing at home.\n\nWRITE DOWN — the questions they ask that go beyond the screen items.\n\nASK AFTERWARDS — 'what makes you suspect camouflaging when school says everything is fine?'",
"s2":    "YOU TAKE — preparing a short list of questions on masking and effort for the parent interview and the child, drawn from the literature, and checking them with your supervisor.\n\nTHEY HOLD — interpreting the answers and deciding whether they warrant onward referral despite a sub-threshold screen.\n\nWHY THAT SPLIT — the questions are the part you can research and improve. Acting on a hunch against a sub-threshold score needs experience of how often that hunch is right.",
"s3":    "YOU RUN IT — ask about masking in interview, with your supervisor present, and bring your view to supervision.\n\nWHAT THEY ARE WATCHING FOR — dismissing home reports because school sees no difficulty, and assuming a girl who makes eye contact and has friends cannot be autistic.\n\nSTEPPING IN LOOKS LIKE — 'what happens when she gets home from school?'",
"s4":    "YOU DO IT ALONE — consider camouflaging and late identification in every social communication assessment, and write in the report that you did.\n\nPASS TEST — You considered presentation in girls and late identification\n\nEVIDENCE TO FILE — a sentence in the report on how presentation and masking were considered. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a sub-threshold screen and a calm classroom observation reported as 'no social communication concerns', and a teenager identified years later.",
"s5":    "YOU CAN TEACH IT — you can explain camouflaging, why screens under-identify it, and what questions surface it — citing Hull et al. (2017), Loomes et al. (2017) and the PSI guidelines.\n\nWHEN IT GOES WRONG — you can say what to do when home and school accounts are irreconcilable: treat the difference as a possible sign of masking, not a reason to doubt the parent.",
"error": "Taking a calm classroom and a sub-threshold screen as evidence against autism in a child who is exhausted and distressed at home.",
"feeds": "→ Feeds into 'Analyse informant agreement and discrepancy', into Conditions — autism, and into Formulation.",
"evidence":"Report — findings and limitations · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

# ── 1. ASSESSMENT · Behavioural and emotional rating scales ──

("Behavioural and emotional rating scales","Select the right forms for informant and age"): {
"why":   "Rating scale systems come as families of forms for different informants and age bands. Using the wrong one gives you scores compared against the wrong norm group. The BASC-3 (Reynolds & Kamphaus, 2015) has teacher, parent and self-report forms by age band. The ASEBA (Achenbach & Rescorla, 2001) has the CBCL, TRF and Youth Self-Report (YSR). The SDQ (Goodman, 1997) has parent, teacher and self-report versions, the self-report for ages 11–17. Check the exact age ranges in the manual you are using before choosing.",
"s1":    "WATCH FOR — how your supervisor decides which forms go to whom: the child's age, which adults know the child in which setting, and whether the child can self-report.\n\nWRITE DOWN — the instrument, each form used, who completed it, and the age range printed on each form.\n\nASK AFTERWARDS — 'which teacher do you send it to when a post-primary student has eight?'",
"s2":    "YOU TAKE — proposing the forms, informants and age bands for the case, in writing, before anything is sent.\n\nTHEY HOLD — the final choice of instrument and of informants.\n\nWHY THAT SPLIT — form selection is rule-based and easy to check, so it is the right thing to practise. Choosing the instrument depends on the referral question and on what the service holds.",
"s3":    "YOU RUN IT — select and send the forms yourself; your supervisor checks your selection before they go out.\n\nWHAT THEY ARE WATCHING FOR — a form one band too young or too old for the child, a teacher who barely knows the child, and no self-report where one is available and appropriate.\n\nSTEPPING IN LOOKS LIKE — 'she turns twelve next month — which form will you use, and why?'",
"s4":    "YOU DO IT ALONE — choose forms matched to the age band on the date of completion, send them to informants who know the child in the relevant setting, and record who completed each.\n\nPASS TEST — Parent, teacher and self-report chosen appropriately\n\nEVIDENCE TO FILE — the method section of the report naming each form and informant. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — scores reported from a form normed for the wrong age band, found when someone checks the date of birth.",
"s5":    "YOU CAN TEACH IT — you can explain the structure of at least two rating scale systems, how to match forms to age and informant, and why the choice of informant is part of the evidence.\n\nWHEN IT GOES WRONG — you can say what to do when the wrong form was completed: do not score it against the wrong norms. Report it as descriptive only, or re-send the right form.",
"error": "Using a form normed for the wrong age band because the child's birthday fell between sending and completion.",
"feeds": "→ Feeds into 'Include the child's own self-report where age-appropriate', 'Score and convert to standardised scores', and 'Analyse informant agreement and discrepancy'.",
"evidence":"Report — method · Appendix 5 · Log sheet tagged 1. Assessment"},

("Behavioural and emotional rating scales","Include the child's own self-report where age-appropriate"): {
"why":   "Children have a right to express their views in matters affecting them, and those views must be given due weight (UNCRC Article 12). In assessment, that means the child's own account sits beside the adults' — not below it, and not only where it agrees. Internal states such as anxiety and low mood are often under-reported by adults who see only behaviour. Lundy's model of participation — space, voice, audience, influence (British Educational Research Journal, 2007) — is a useful check that the view was heard and acted on.",
"s1":    "WATCH FOR — how your supervisor introduces a self-report form to a child: who reads the items, how they check understanding, and whether the child is told who will see the answers.\n\nWRITE DOWN — the form, the child's age, how it was administered, and where the child's view appeared in the report.\n\nASK AFTERWARDS — 'what do you do when a child's self-report says everything is fine and every adult says it isn't?'",
"s2":    "YOU TAKE — administering the self-report with the child, reading items aloud where reading is a barrier, and recording anything the child says about the items.\n\nTHEY HOLD — how the child's account is weighted and worded in the report.\n\nWHY THAT SPLIT — sitting with the child is direct, supervised practice. Where their view lands in the report shapes the conclusions, which your supervisor still holds.",
"s3":    "YOU RUN IT — administer the self-report and write the section presenting the child's view, with your supervisor reviewing before it goes in.\n\nWHAT THEY ARE WATCHING FOR — the child's view summarised in one line after pages of adult ratings, or dismissed as 'lacking insight' without evidence.\n\nSTEPPING IN LOOKS LIKE — 'where in the report would the child find what they told you?'",
"s4":    "YOU DO IT ALONE — include self-report wherever the child's age and ability allow, present it alongside adult reports, and say how it informed the conclusions.\n\nPASS TEST — The child's account appears alongside the adults'\n\nEVIDENCE TO FILE — the findings section showing the child's account in parallel with adult ratings. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a report on a thirteen-year-old's anxiety with no self-report and no direct quote from the young person.",
"s5":    "YOU CAN TEACH IT — you can explain Article 12, Lundy's model, and the practical adaptations — reading items aloud, visual scales, checking understanding — that let younger or less able children self-report validly.\n\nWHEN IT GOES WRONG — you can say what to do when the child refuses or cannot complete a self-report: record that, and gather their view another way — conversation, drawing, scaling questions.",
"error": "Leaving out the child's own view because the adults' forms were enough to score.",
"feeds": "→ Feeds into 'Analyse informant agreement and discrepancy', into Ethical Practice — the child's voice — and into Working with Others.",
"evidence":"Report — findings · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Behavioural and emotional rating scales","Explain to informants how to complete them"): {
"why":   "A rating scale is only as good as the completion. Forms come back with half the items blank, several boxes ticked on one item, notes in the margins instead of ratings, or completed jointly by two parents without saying so. Each invalidates or weakens the score. Most manuals set a maximum number of omitted items before a scale cannot be scored — check yours. Two minutes of explanation at the start saves a wasted form and a second request to a busy teacher.",
"s1":    "WATCH FOR — what your supervisor says when handing out or sending forms: the time period to rate, answering every item, one rater per form, what to do when unsure, and the return date.\n\nWRITE DOWN — their instructions, and anything they put in a covering note for teachers.\n\nASK AFTERWARDS — 'what's the most common way forms come back unusable?'",
"s2":    "YOU TAKE — writing a covering note for teacher forms and giving the verbal explanation to parents, checked beforehand by your supervisor.\n\nTHEY HOLD — deciding whether a returned form is valid enough to score.\n\nWHY THAT SPLIT — the explanation is a script you can improve with feedback. Judging validity depends on the manual's rules and on experience of how different errors affect scores.",
"s3":    "YOU RUN IT — explain the forms to every informant yourself, and check the forms on return before the informant leaves where you can.\n\nWHAT THEY ARE WATCHING FOR — not stating the rating period ('in the last six months'), and not asking the informant to answer every item.\n\nSTEPPING IN LOOKS LIKE — 'did you mention the time period? Some of these answers sound like last year.'",
"s4":    "YOU DO IT ALONE — explain the rating period, one rater per form, answering every item, and how to handle uncertainty. Check forms on return and follow up omissions quickly.\n\nPASS TEST — Forms come back usable\n\nEVIDENCE TO FILE — the covering note template and returned forms. Log against 1. Assessment and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — a teacher form with twelve items blank, discovered a week later when the teacher has moved on to other work.",
"s5":    "YOU CAN TEACH IT — you can explain why each instruction matters for the score, and write a short covering note that gets forms back complete.\n\nWHEN IT GOES WRONG — you can say what to do when a form comes back incomplete: check the manual's omission rule, follow up the specific items if it is over, and never fill in or pro-rate beyond what the manual permits.",
"error": "Sending forms without a stated rating period and a request to answer every item.",
"feeds": "→ Feeds into 'Score and convert to standardised scores' and into Working with Others — teachers and families as informants.",
"evidence":"Covering note · returned forms · Appendix 5 · Log sheet tagged 1. Assessment and 5. Working with Others"},

("Behavioural and emotional rating scales","Score and convert to standardised scores"): {
"why":   "Most behaviour rating systems convert raw scores to T-scores (mean 50, SD 10) against a norm group chosen by age, sometimes sex, and sometimes a general or clinical sample. Choosing the wrong norm group, missing reverse-scored items, or mistyping into software all change the result without any sign on the page. Hand-scoring invites arithmetic errors; software moves the error to data entry. Either way, what makes the score trustworthy is the check.",
"s1":    "WATCH FOR — whether your supervisor hand-scores or uses software, which norm group they choose and why, and how they check the entry.\n\nWRITE DOWN — the instrument, the norm group, how omitted items were handled, and any validity or response-style index reported.\n\nASK AFTERWARDS — 'when do you use combined-sex norms and when separate, and does it change what you conclude?'",
"s2":    "YOU TAKE — scoring the forms independently, including any validity indices, before seeing your supervisor's version.\n\nTHEY HOLD — the authoritative score and the choice of norm group.\n\nWHY THAT SPLIT — double-scoring shows your systematic errors quickly. Norm-group choice changes the conclusion, so it is a judgement they keep until you can defend it.",
"s3":    "YOU RUN IT — score, choose norms, and present the scores in supervision with the norm group stated.\n\nWHAT THEY ARE WATCHING FOR — reverse-scored items missed, the wrong age band, validity indices ignored, and scores typed into the report wrongly.\n\nSTEPPING IN LOOKS LIKE — picking one scale and asking you to re-score it by hand in front of them.",
"s4":    "YOU DO IT ALONE — score each form, check the scoring by a second method or on a second occasion, state the norm group in the report, and check validity indices before interpreting.\n\nPASS TEST — Scoring is checked\n\nEVIDENCE TO FILE — scored forms or software printout with your check marked, and the score table in the report. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a clinically significant score reported from a form whose validity index flagged an extreme response style.",
"s5":    "YOU CAN TEACH IT — you can explain T-scores, norm-group choice, reverse scoring and validity indices, and show a peer a quick way to check software output against the raw form.\n\nWHEN IT GOES WRONG — you can say what to do when a validity index is flagged: do not interpret the clinical scales as if it were not, report the flag, and consider what the response style itself tells you.",
"error": "Interpreting clinical scales without first checking the form's validity or response-style indices.",
"feeds": "→ Feeds into 'Analyse informant agreement and discrepancy' and 'Distinguish elevated from clinically significant'.",
"evidence":"Scored forms with check · Report — score table · Appendix 5 · Log sheet tagged 1. Assessment"},

("Behavioural and emotional rating scales","Analyse informant agreement and discrepancy"): {
"why":   "Parent, teacher and child ratings routinely disagree. The Achenbach, McConaughy and Howell (1987) meta-analysis found cross-informant correlations were modest, and higher between similar informants than between different types — check the paper for the figures before quoting. Later work argues discrepancy often reflects real differences in how the child behaves across settings (De Los Reyes et al., Psychological Bulletin, 2015, on the Operations Triad Model). Treating discrepancy as someone being wrong throws away information about context.",
"s1":    "WATCH FOR — how your supervisor lays out scores from different informants: usually side by side by scale. Notice what they say about a scale where home and school differ sharply.\n\nWRITE DOWN — each scale where informants differ by a meaningful amount (your manual may give a guide), and the explanation your supervisor offered.\n\nASK AFTERWARDS — 'when a parent rates much higher than the teacher, what are the possible explanations, and how do you choose?'",
"s2":    "YOU TAKE — building the side-by-side table and listing, for each discrepancy, explanations based on setting, task demands, relationship and informant threshold.\n\nTHEY HOLD — which explanation the report adopts, and how it is worded.\n\nWHY THAT SPLIT — generating alternative explanations is safe practice. The wording can make a parent feel disbelieved or a teacher feel blamed.",
"s3":    "YOU RUN IT — present the discrepancies and your reading of them in supervision, then draft the paragraph.\n\nWHAT THEY ARE WATCHING FOR — averaging across informants, or writing one informant off as biased without evidence.\n\nSTEPPING IN LOOKS LIKE — 'what's different about the two settings that could make both ratings accurate?'",
"s4":    "YOU DO IT ALONE — lay out informant scores side by side, treat each discrepancy as a question about context, and write the likeliest explanation with its evidence.\n\nPASS TEST — Discrepancy treated as data about context\n\nEVIDENCE TO FILE — the rating scale section of the report. Log against 1. Assessment and 5. Working with Others.\n\nWHAT FAILURE LOOKS LIKE — 'the parent's ratings may reflect heightened anxiety', written with no evidence and read by the parent at the feedback meeting.",
"s5":    "YOU CAN TEACH IT — you can explain why informants disagree, cite the cross-informant literature, and show a peer how to turn a discrepancy into a hypothesis about context that feeds the formulation.\n\nWHEN IT GOES WRONG — you can say what to do when an informant disputes your reading of their rating: listen, check your interpretation against what they say about the setting, and revise if they have told you something you did not know.",
"error": "Averaging parent and teacher scores into one number, losing the difference that was the finding.",
"feeds": "→ Feeds into 'Identify where sources diverge and say so', into Formulation — context and maintaining factors — and into Working with Others.",
"evidence":"Report — rating scale findings · Appendix 5 · Log sheet tagged 1. Assessment and 5. Working with Others"},

("Behavioural and emotional rating scales","Distinguish elevated from clinically significant"): {
"why":   "Rating systems band T-scores, and the bands mean specific things. On the BASC-3, clinical scales at 60–69 are 'at-risk' and 70 and above 'clinically significant' (Reynolds & Kamphaus, 2015). On the ASEBA syndrome scales, 65–69 is borderline and 70 and above clinical (Achenbach & Rescorla, 2001). Other instruments use other cut-offs, so check each manual. 'Clinically significant' is a statistical statement about rarity against norms, not a diagnosis. Misusing either term misleads the reader about how concerned to be.",
"s1":    "WATCH FOR — the exact words your supervisor uses for each band, and whether they explain the band in plain language in the report.\n\nWRITE DOWN — the instrument, its band labels and cut-offs as printed in the manual, and the sentence your supervisor used to report an elevated score.\n\nASK AFTERWARDS — 'how do you explain to a parent that a clinically significant score doesn't mean their child has a disorder?'",
"s2":    "YOU TAKE — writing the band label and plain-language meaning beside each score in the draft score table.\n\nTHEY HOLD — how the scores are summarised in the conclusion and discussed with the family.\n\nWHY THAT SPLIT — attaching the right label is checkable against the manual. Deciding how much weight an elevated score carries in the conclusion is interpretation.",
"s3":    "YOU RUN IT — report the rating scale results in writing and in the feedback meeting, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — 'clinical' used to mean 'diagnosed', one instrument's cut-offs applied to another, and at-risk scores ignored because they are not clinical.\n\nSTEPPING IN LOOKS LIKE — your supervisor rephrasing: 'what that means is that fewer than about one in fifty children in the norm group scored this high.'",
"s4":    "YOU DO IT ALONE — report each score with the manual's band label, what the band means statistically, and a plain-language sentence, without implying diagnosis.\n\nPASS TEST — You know what the cut-offs mean and say so\n\nEVIDENCE TO FILE — the score table and narrative in the report. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a school acting on 'clinically significant anxiety' as if a diagnosis had been made.",
"s5":    "YOU CAN TEACH IT — you can explain T-scores, percentiles and band cut-offs, why cut-offs differ between instruments, and why statistical rarity is not the same as disorder.\n\nWHEN IT GOES WRONG — you can say what to do when a score sits just under a cut-off but everything else suggests serious concern: report the score honestly, and let the wider evidence carry the conclusion.",
"error": "Using 'clinically significant' as if it meant 'diagnosed'.",
"feeds": "→ Feeds into interpretation and limitations, into Formulation, and into onward referral decisions.",
"evidence":"Report — score table and narrative · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

# ── 1. ASSESSMENT · Adapt standardised procedure and record the adaptation ──

("Adapt standardised procedure and record the adaptation","Choose an adaptation proportionate to the need"): {
"why":   "Some children cannot access a standardised procedure as written: sensory, motor, language, attention or anxiety needs get in the way. Refusing to adapt can breach the duty of reasonable accommodation (Equal Status Acts 2000–2018). Adapting too much means the score no longer means what the norms say. The Standards for Educational and Psychological Testing (AERA, APA & NCME, 2014) separate accommodations, which leave the construct intact, from modifications, which change it. The skill is choosing the least adaptation that removes the barrier.",
"s1":    "WATCH FOR — which adaptations your supervisor uses, and when: breaks, a changed order, repeated instructions, a different seating arrangement, an interpreter, or stopping.\n\nWRITE DOWN — each adaptation, the barrier it responded to, and whether your supervisor considered it an accommodation or a modification.\n\nASK AFTERWARDS — 'what's the smallest change you could have made there, and why did you choose that one?'",
"s2":    "YOU TAKE — planning adaptations before the session from what you know of the child, and writing down why each is needed.\n\nTHEY HOLD — decisions made in the room, and whether a proposed change would invalidate the norms.\n\nWHY THAT SPLIT — planning ahead is reasoning you can check against the manual. In-the-moment decisions need experience of how each change affects the score.",
"s3":    "YOU RUN IT — administer with your planned adaptations and make in-session decisions yourself, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — over-adapting (rephrasing items, extra prompts) out of kindness, and under-adapting out of fear of breaking the rules.\n\nSTEPPING IN LOOKS LIKE — suggesting a break rather than a rephrase: 'shall we stop for a minute?'",
"s4":    "YOU DO IT ALONE — choose each adaptation deliberately from the least-change options (break, rephrase within the rules, reorder, discontinue), and know which ones change the construct.\n\nPASS TEST — Break, rephrase, reorder or discontinue, chosen deliberately\n\nEVIDENCE TO FILE — the protocol annotations and the report's administration notes. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a child who was given extra time and rephrased items reported with standard scores and no comment.",
"s5":    "YOU CAN TEACH IT — you can explain accommodation versus modification with worked examples, the reasonable-accommodation duty, and what each common adaptation does to interpretability.\n\nWHEN IT GOES WRONG — you can say what to do when an adaptation turns out to have changed the construct: report scores as descriptive rather than normative, and say why.",
"error": "Rephrasing items to help the child, then reporting standard scores as though nothing changed.",
"feeds": "→ Feeds into 'State the effect on validity in the report', 'Record the adaptation at the moment it happens', and Ethical Practice.",
"evidence":"Annotated protocol · Report — administration notes · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Adapt standardised procedure and record the adaptation","State the effect on validity in the report"): {
"why":   "Norms describe how children performed under standard conditions. Once conditions change, the reader needs to know whether the comparison still holds. Test publishers' guidance is that non-standard administration must be reported with its likely effect (AERA, APA & NCME, 2014; PSI Code 4.2.2). A score reported without that note tells the reader it means the same as any other score. If it does not, the report has misled them.",
"s1":    "WATCH FOR — where your supervisor reports adaptations: usually a short 'administration and validity' or 'behaviour during assessment' paragraph. Notice whether they say which scores are affected.\n\nWRITE DOWN — the adaptation, the subtests affected, and the sentence stating whether scores remain interpretable.\n\nASK AFTERWARDS — 'when do you decide a score can't be reported at all?'",
"s2":    "YOU TAKE — drafting the validity paragraph, naming each adaptation and the subtests it touched.\n\nTHEY HOLD — the judgement on whether the affected scores are interpretable, descriptive only, or should be withheld.\n\nWHY THAT SPLIT — listing what changed is a record-keeping task. Whether a score still means something requires knowledge of the test's construct and norms.",
"s3":    "YOU RUN IT — write the validity paragraph with your own judgement on interpretability, and defend it in supervision.\n\nWHAT THEY ARE WATCHING FOR — a validity statement that says 'results are a valid estimate' by default, and affected scores left in composites without comment.\n\nSTEPPING IN LOOKS LIKE — 'that subtest was timed and you gave extra time. Can it go into the index?'",
"s4":    "YOU DO IT ALONE — for every adapted administration, state in the report what changed, which scores it affects, and whether each remains interpretable against the norms.\n\nPASS TEST — You said whether scores remain interpretable\n\nEVIDENCE TO FILE — the administration and validity paragraph of the report. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — an index score built from a subtest you administered non-standardly, reported without comment and used to decide provision.",
"s5":    "YOU CAN TEACH IT — you can explain how to judge interpretability subtest by subtest, when to report scores as descriptive, and when to withhold a composite.\n\nWHEN IT GOES WRONG — you can say what to do when you realise after sending the report that a score was compromised: tell your supervisor, issue a correction, and say whether the conclusions change.",
"error": "A validity statement that says the results are valid when the administration was adapted.",
"feeds": "→ Feeds into 'Record the adaptation at the moment it happens', into the limitations paragraph, and into Ethical Practice.",
"evidence":"Report — administration and validity · Appendix 5 · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Adapt standardised procedure and record the adaptation","Recognise when standard procedure is not working"): {
"why":   "Standard procedure stops working in recognisable ways: the child disengages, becomes distressed, cannot understand the instructions, or answers from anxiety rather than ability. The later you notice, the more items are spoiled and the harder the session is to rescue. Early signs are often small — slowing responses, a change in posture, 'I don't know' before the item has been read. Noticing early is what makes a small adaptation enough.",
"s1":    "WATCH FOR — the moment your supervisor changes something, and what they noticed just before. Often it is a behaviour you did not register.\n\nWRITE DOWN — the sign, the time, the subtest, and what your supervisor did.\n\nASK AFTERWARDS — 'what did you see just before you offered a break?'",
"s2":    "YOU TAKE — watching and noting signs of strain during your supervisor's administration, and comparing your notes with theirs afterwards.\n\nTHEY HOLD — deciding when to act.\n\nWHY THAT SPLIT — when you are not administering, all your attention can go on the child, which is how you learn to see the signs. Deciding to act changes the assessment, so it stays with them.",
"s3":    "YOU RUN IT — administer, watch for signs, and act when you see them, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — pressing on to finish the subtest when the child is clearly struggling, because stopping feels like failure.\n\nSTEPPING IN LOOKS LIKE — a quiet 'how are you doing?' to the child, which gives you the cue.",
"s4":    "YOU DO IT ALONE — notice strain early and act in proportion, and record when and what you saw.\n\nPASS TEST — You noticed early rather than at the end\n\nEVIDENCE TO FILE — protocol annotations with time and behaviour, and the behavioural observations section of the report. Log against 1. Assessment.\n\nWHAT FAILURE LOOKS LIKE — a child in tears by the final subtest, and a protocol with no note of when it started.",
"s5":    "YOU CAN TEACH IT — you can describe the early signs of disengagement, anxiety and confusion, and how to tell them apart, and explain why acting early protects both the child and the validity of the scores.\n\nWHEN IT GOES WRONG — you can say what to do when you missed the signs and the session ended badly: tell your supervisor, check on the child, record it, and judge whether the later scores can be reported.",
"error": "Pushing through to the end of the subtest because stopping feels like losing the score.",
"feeds": "→ Feeds into 'Record the adaptation at the moment it happens', 'Re-evaluate whether to continue at all', and the behavioural observations section.",
"evidence":"Annotated protocol · Report — behavioural observations · Appendix 5 · Log sheet tagged 1. Assessment"},

("Adapt standardised procedure and record the adaptation","Record the adaptation at the moment it happens"): {
"why":   "A reconstructed record is not a record. By the time you write up, you will not remember which item you rephrased, how long the break was, or whether you repeated an instruction. CORU SoP 2.8 ties record-keeping to accuracy and timeliness. A protocol annotated in the moment is the only thing that lets you, your supervisor or a later reviewer judge which scores were affected. Without it you cannot write the validity statement honestly.",
"s1":    "WATCH FOR — how and when your supervisor annotates the protocol: margin notes, standard abbreviations, the time written beside a break.\n\nWRITE DOWN — the abbreviations they use and what each means.\n\nASK AFTERWARDS — 'what's your shorthand for a repeated instruction, a prompt and a break?'",
"s2":    "YOU TAKE — annotating the protocol in real time while your supervisor administers.\n\nTHEY HOLD — the administration.\n\nWHY THAT SPLIT — annotating at speed while watching the child is its own skill. Practising it without the load of administering builds the habit before you need both at once.",
"s3":    "YOU RUN IT — administer and annotate at the same time, with your supervisor present.\n\nWHAT THEY ARE WATCHING FOR — adaptations made and not written down, and notes added afterwards from memory.\n\nSTEPPING IN LOOKS LIKE — at the end, 'show me where you wrote down the break.'",
"s4":    "YOU DO IT ALONE — annotate every adaptation on the protocol as it happens: what changed, which item, the time. Do not add to the record after the session except as a dated, clearly marked addition.\n\nPASS TEST — Annotated on the protocol, not reconstructed\n\nEVIDENCE TO FILE — the annotated protocol. Log against 1. Assessment and 6. Ethical Practice.\n\nWHAT FAILURE LOOKS LIKE — a validity paragraph written from memory that does not match the protocol, found on audit.",
"s5":    "YOU CAN TEACH IT — you can teach a consistent annotation shorthand and explain why contemporaneous records carry weight that reconstructed ones do not.\n\nWHEN IT GOES WRONG — you can say what to do when you realise you did not record something: add a dated, clearly marked note saying it was written afterwards, and weaken any claim that depends on it.",
"error": "Writing up adaptations from memory after the session and presenting them as the record.",
"feeds": "→ Feeds into 'State the effect on validity in the report', and into Ethical Practice — record-keeping.",
"evidence":"Annotated protocol · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

("Adapt standardised procedure and record the adaptation","Re-evaluate whether to continue at all"): {
"why":   "Sometimes the right adaptation is to stop. A child who is distressed, unwell, withdrawing assent, or unable to access the task at all is not giving you valid data, and continuing may harm them and their trust in adults who assess them. Assent is ongoing, not a form signed at the start. Trainees often find stopping hardest because it feels like failing the assessment. Stopping well is a professional decision, not a failure.",
"s1":    "WATCH FOR — whether your supervisor stops or reschedules a session, and how they explain it to the child, the parent and the school.\n\nWRITE DOWN — the signs that led to stopping, what was said to the child, and what was planned instead.\n\nASK AFTERWARDS — 'what's the threshold where you stop rather than adapt?'",
"s2":    "YOU TAKE — watching for signs that assent has been withdrawn, and saying so to your supervisor, quietly or at a break.\n\nTHEY HOLD — the decision to stop, and the conversation with the family and school.\n\nWHY THAT SPLIT — noticing withdrawn assent is something you can do from the first session. Stopping has consequences — rescheduling, waiting lists, school expectations — that your supervisor manages.",
"s3":    "YOU RUN IT — make the call to continue, adapt or stop in your own session, with your supervisor present to support.\n\nWHAT THEY ARE WATCHING FOR — continuing because the school is waiting for the report, or because stopping feels like admitting something went wrong.\n\nSTEPPING IN LOOKS LIKE — 'do you want to check with them whether they'd like to keep going?'",
"s4":    "YOU DO IT ALONE — keep checking assent through the session, stop when the child cannot or will not continue validly, and record the reason.\n\nPASS TEST — You were willing to stop\n\nEVIDENCE TO FILE — the protocol note and a case note of the reason and the plan. Log against 1. Assessment and 6. Ethical Practice. Consider Appendix 8 if it raised a dilemma.\n\nWHAT FAILURE LOOKS LIKE — a distressed child pushed through the battery, and scores reported as though the session were typical.",
"s5":    "YOU CAN TEACH IT — you can explain ongoing assent, the signs that it has been withdrawn, and why stopping protects both the child and the validity of the assessment.\n\nWHEN IT GOES WRONG — you can say what to do when a school or parent pushes back on a stopped session: explain that invalid scores would harm the child more than a delay, and offer a plan for completing the assessment.",
"error": "Continuing a session the child has clearly withdrawn from because the report is due.",
"feeds": "→ Feeds into Ethical Practice — consent, assent and the child's welfare — and into 'State the effect on validity in the report'.",
"evidence":"Protocol note · case note · Appendix 8 if a dilemma arose · Log sheet tagged 1. Assessment and 6. Ethical Practice"},

}
